"""P2 — Oscillateurs : du mode propre à l'anharmonicité."""
from commun import slider, select, preset, lab

LABS = [
    lab('chaine_atomique', 'Une chaîne : modes propres, propagation et dispersion', 'P2 · Oscillateurs',
        'Déplacer une masse, choisir un mode ou envoyer une onde dans une chaîne périodique. Comparer la pulsation exacte à celle d’une onde non dispersive : quand peut-on remplacer des masses et des ressorts par un milieu continu ? Les valeurs choisies sont celles d’une maquette mécanique ; la même équation décrit un réseau atomique harmonique.',
        [slider('N', 'Nombre de masses distinctes N', 6, 24, 1, 12, integer=True), slider('m', 'Masse de chaque élément m', .5, 3, .1, 1, 'kg'),
         slider('k', 'Raideur entre deux voisins k', 10, 100, 5, 40, 'N/m'), slider('a', 'Espacement au repos a', .5, 2, .1, 1, 'm'),
         slider('A', 'Déplacement initial de référence A', .01, .2, .01, .08, 'm'), slider('q', 'Indice du mode q, ramené modulo N', 0, 12, 1, 2, integer=True),
         select('excitation', 'Préparation de la chaîne', [('standing', 'Mode stationnaire : masses lâchées sans vitesse'), ('traveling', 'Onde progressive sinusoïdale'), ('local', 'Une seule masse déplacée, sans vitesse')], 'standing')],
        [preset('Grande longueur d’onde', N=24, q=1, excitation='traveling'), preset('Mode alterné', N=12, q=6, excitation='standing'), preset('Impulsion locale', N=16, q=2, excitation='local')]),
    lab('molecule_co2', 'CO₂ : trois masses, deux vibrations et une translation', 'P2 · Oscillateurs',
        'Observer quels atomes bougent dans chacun des deux modes longitudinaux de CO₂. La masse du carbone diffère de celle des oxygènes : il faut résoudre un problème de valeurs propres avec une matrice de masse. Changer un isotope permet de relier mécanique et spectroscopie.',
        [slider('mO', 'Masse isotopique d’un oxygène', 16, 18, 1, 16, 'u'), slider('mC', 'Masse isotopique du carbone', 12, 13, 1, 12, 'u'),
         slider('k', 'Raideur de chaque liaison k', 500, 1800, 50, 1000, 'N/m'), slider('A', 'Déplacement atomique maximal de référence', 2, 12, 1, 6, 'pm'),
         select('mode', 'Mouvement préparé', [('oxygen', 'Oxygènes opposés, carbone immobile'), ('carbon', 'Oxygènes ensemble, carbone opposé'), ('mix', 'Superposition des deux vibrations'), ('translation', 'Déplacement commun des trois atomes')], 'oxygen')],
        [preset('Mode avec carbone immobile', mode='oxygen', mO=16, mC=12), preset('Mode avec carbone mobile', mode='carbon', mO=16, mC=12), preset('Carbone 13 et superposition', mode='mix', mO=18, mC=13)]),
    lab('foucault', 'Foucault : oscillation rapide, précession lente', 'P2 · Oscillateurs',
        'Séparer deux mouvements que l’œil confond facilement : la boule oscille en quelques secondes, tandis que la direction de son oscillation tourne en plusieurs heures. Changer la latitude puis comparer trois courts enregistrements du mouvement à des heures différentes.',
        [slider('latitude', 'Latitude λ : positive au nord', -90, 90, 5, 50, '°'), slider('L', 'Longueur du pendule L', 5, 80, 1, 67, 'm'),
         slider('A', 'Déplacement horizontal initial A', .1, 1.5, .1, .5, 'm'), slider('hours', 'Intervalle entre début et fin de l’observation', 1, 24, 1, 12, 'h')],
        [preset('Panthéon : latitude 49°', latitude=49, L=67, hours=12), preset('Équateur', latitude=0, L=30, hours=12), preset('Hémisphère sud', latitude=-50, L=67, hours=12)]),
    lab('pendule_exact', 'Pendule : mesurer la période sans petit angle', 'P2 · Oscillateurs',
        'Lâcher un pendule sans vitesse et augmenter l’angle initial. Comparer le mouvement à une sinusoïde, mesurer sa période puis retrouver cette période à partir de l’énergie. Au-delà de 90°, la liaison doit être une tige rigide sans masse : un fil ne resterait pas tendu au lâcher. Le laboratoire montre pourquoi T = 2π√(L/g) demande une hypothèse de petit angle.',
        [slider('angle', 'Angle initial θₘ, mesuré depuis la verticale', 5, 170, 5, 60, '°'), slider('L', 'Longueur L', .2, 5, .1, 1, 'm'),
         slider('cycles', 'Nombre de périodes exactes observées', 1, 6, 1, 3, integer=True)],
        [preset('Petit angle : 10°', angle=10, cycles=3), preset('Écart visible : 90°', angle=90, cycles=3), preset('Près du sommet : 165°', angle=165, cycles=2)]),
    lab('pendule_anharmonique', 'Anharmonicité : période corrigée et troisième harmonique', 'P2 · Oscillateurs',
        'Développer sin θ et le potentiel du pendule, puis mesurer ce que le terme cubique change réellement. Comparer trois modèles, repérer la troisième harmonique et distinguer une correction utile d’un développement employé trop loin de θ = 0.',
        [slider('angle', 'Amplitude angulaire maximale θₘ', 5, 80, 5, 40, '°'), slider('L', 'Longueur L', .5, 3, .1, 1, 'm')],
        [preset('Correction faible : 10°', angle=10), preset('Troisième harmonique visible : 50°', angle=50), preset('Tester les limites : 80°', angle=80)]),
    lab('ressorts_transverses', 'Deux ressorts : créer deux équilibres stables', 'P2 · Oscillateurs',
        'Une masse se déplace sur un rail horizontal, entre deux ressorts identiques fixés au-dessus et au-dessous du rail. Faire varier la distance L des points d’attache au centre : l’équilibre central peut devenir instable, et deux positions stables apparaissent. Retrouver ce changement sur le potentiel et sur le mouvement.',
        [slider('rho', 'Rapport L/L₀ entre distance d’attache et longueur à vide', .5, 1.5, .05, .8), slider('L0', 'Longueur à vide L₀ de chaque ressort', .5, 1.5, .1, 1, 'm'),
         slider('k', 'Raideur k de chaque ressort', 10, 100, 5, 40, 'N/m'), slider('m', 'Masse mobile m', .5, 3, .1, 1, 'kg'),
         slider('A', 'Écart initial à l’équilibre choisi, en unités de L₀', .05, 1.2, .05, .2),
         select('origin', 'Position de référence pour le lâcher', [('center', 'Centre x = 0'), ('well', 'Équilibre stable de droite, s’il existe')], 'well')],
        [preset('Un seul puits', rho=1.3, origin='center', A=.2), preset('Deux puits : rester à droite', rho=.7, origin='well', A=.1), preset('Franchir la barrière', rho=.7, origin='well', A=.8), preset('Au seuil L = L₀', rho=1, origin='center', A=.2)]),
    lab('oscillateur_quartique', 'Au seuil : un oscillateur sans raideur linéaire', 'P2 · Oscillateurs',
        'Placer les deux ressorts exactement au seuil L = L₀. Le terme quadratique du potentiel s’annule, mais le centre reste stable : le premier terme utile est en x⁴. Mesurer la période, vérifier sa dépendance en 1/A et comparer ce modèle au potentiel exact des ressorts.',
        [slider('A', 'Amplitude initiale A/L₀', .02, .8, .02, .2), slider('L0', 'Longueur à vide L₀', .5, 2, .1, 1, 'm'),
         slider('k', 'Raideur k de chaque ressort', 10, 100, 5, 40, 'N/m'), slider('m', 'Masse m', .5, 3, .1, 1, 'kg')],
        [preset('Près du centre : A = 0,04 L₀', A=.04), preset('Amplitude modérée : A = 0,20 L₀', A=.2), preset('Quitter le domaine quartique : A = 0,80 L₀', A=.8)]),
    lab('duffing_force', 'Duffing : une résonance qui dépend de l’amplitude', 'P2 · Oscillateurs',
        'Prolonger l’oscillateur forcé du cours en ajoutant une force de rappel cubique. Comparer l’amplitude calculée dans le temps à une approximation sinusoïdale de la réponse. Pour un rappel durcissant, la courbe se déforme et une même fréquence peut donner plusieurs amplitudes approchées.',
        [slider('beta', 'Coefficient cubique β, après réduction des unités', 0, 1.5, .05, 1), slider('zeta', 'Amortissement réduit ζ', .02, .2, .01, .05),
         slider('force', 'Amplitude réduite de la force f', .02, .5, .02, .2), slider('ratio', 'Rapport r = pulsation imposée / pulsation propre', .5, 1.6, .02, 1.2),
         slider('initial', 'Position initiale réduite u(0), vitesse nulle', 0, 2, .1, 0), slider('cycles', 'Nombre de périodes du forçage calculées', 30, 120, 10, 60, integer=True)],
        [preset('Référence linéaire', beta=0, force=.1, ratio=1, zeta=.05, initial=0, cycles=80), preset('Rappel durcissant', beta=1, force=.2, ratio=1.2, zeta=.05, initial=0, cycles=80), preset('Tester une autre préparation', beta=1, force=.2, ratio=1.2, zeta=.05, initial=1.2, cycles=100)]),
]
