"""Cours, exercices corrigés et objectifs P2 — sources : fiche P2, p. 275–282."""

def lesson(title, level, lab, html):
    return dict(title=title, level=level, lab=lab, html=html)

def exercise(title, level, lab, question, answer):
    return dict(title=title, level=level, lab=lab, question=question, answer=answer)

LESSONS = [
lesson('Des forces entre voisins aux modes propres d’une chaîne', 'Sup → Spé', 'chaine_atomique', '''
<p>On considère N masses identiques m, espacées de a au repos et reliées par des ressorts de raideur k. La variable u<sub>j</sub>(t) désigne le <strong>déplacement</strong> de la masse j : sa position est ja+u<sub>j</sub>. Les indices sont périodiques, u<sub>j+N</sub>=u<sub>j</sub>. Il y a N masses distinctes ; une masse supplémentaire dessinée pour fermer la cellule ne constitue pas un degré de liberté supplémentaire.</p>
<h3>1. Bilan mécanique local</h3><p>Le ressort de droite exerce k(u<sub>j+1</sub>−u<sub>j</sub>) et celui de gauche −k(u<sub>j</sub>−u<sub>j−1</sub>). Le principe fondamental donne m ü<sub>j</sub>=k(u<sub>j+1</sub>+u<sub>j−1</sub>−2u<sub>j</sub>). L’énergie totale est E=½m∑u̇<sub>j</sub>²+½k∑(u<sub>j+1</sub>−u<sub>j</sub>)² ; chaque ressort doit être compté une seule fois.</p>
<h3>2. Chercher une forme commune de mouvement</h3><p>Avec u<sub>j</sub>=Re(Ue<sup>i(κja−ωt)</sup>), la périodicité impose κa=2πq/N. Substituer donne mω²=k(2−e<sup>iκa</sup>−e<sup>−iκa</sup>)=4k sin²(κa/2). La pulsation positive est donc <strong>ω=2√(k/m)|sin(κa/2)|</strong>. q et q+N désignent le même mode ; q et N−q ont la même fréquence.</p>
<h3>3. Interpréter le mode nul</h3><p>Pour q=0, toutes les masses ont le même déplacement. Aucun ressort n’est allongé : ω=0. Le mouvement peut être une translation uniforme si l’on donne une vitesse initiale commune ; avec une vitesse initiale nulle, le déplacement commun reste constant.</p>
<p><strong>Technique CPGE :</strong> distinguer position et déplacement, faire le bilan de deux forces, utiliser l’écriture complexe puis revenir au mouvement réel. Un mode propre fait osciller toutes les masses à une pulsation unique ; une préparation locale est une superposition de modes.</p>'''),
lesson('Du réseau discret à l’équation des ondes', 'Spé → Au-delà', 'chaine_atomique', '''
<p>Le paramètre qui contrôle le passage au continu est |κa| : la longueur d’onde doit être grande devant l’espacement. Pour |κa|≪1, sin(κa/2)≈κa/2 et ω≈c|κ|, avec <strong>c=a√(k/m)</strong>. La dispersion linéaire du milieu continu est seulement la tangente au voisinage de κ=0.</p>
<h3>Développement spatial</h3><p>Si u<sub>j</sub>(t)≈u(ja,t), alors u(x+a)+u(x−a)−2u(x)=a²∂²u/∂x²+(a⁴/12)∂⁴u/∂x⁴+… . Au premier ordre utile, ∂²u/∂t²=c²∂²u/∂x². Le premier terme négligé explique pourquoi un réseau réel devient dispersif à courte longueur d’onde.</p>
<h3>Deux vitesses à distinguer</h3><p>Dans la première zone 0&lt;κa&lt;π, la vitesse de phase vaut ω/κ et la vitesse de groupe dω/dκ=c cos(κa/2). Elles tendent vers c quand κa→0. À κa=π, deux masses voisines se déplacent en sens opposés et la vitesse de groupe s’annule ; cela ne signifie pas que chaque masse est immobile.</p>
<h3>Une impulsion n’est pas une sinusoïde</h3><p>La transformée de Fourier discrète écrit u<sub>j</sub>(0)=∑Q<sub>q</sub>e<sup>2iπqj/N</sup>. Chaque coefficient évolue avec sa propre pulsation. Des vitesses de groupe différentes déforment une perturbation localisée ; dans une cellule périodique, les perturbations peuvent ensuite revenir vers leur point de départ.</p>
<p><strong>Limite du modèle :</strong> les nombres choisis décrivent une maquette mécanique. L’application à des vibrations cristallines utilise exactement cette mécanique harmonique, mais l’énergie quantifiée des phonons demande un modèle quantique distinct. Le laboratoire ne l’ajoute pas implicitement.</p>'''),
lesson('CO₂ : diagonaliser avec une matrice de masse', 'Spé', 'molecule_co2', '''
<p>Les déplacements longitudinaux des trois atomes forment X=(x₁,x₂,x₃)ᵀ. Les oxygènes ont la masse m<sub>O</sub>, le carbone m<sub>C</sub>. L’énergie cinétique est T=½ẊᵀMẊ, M=diag(m<sub>O</sub>,m<sub>C</sub>,m<sub>O</sub>) ; le potentiel est V=½XᵀKX, avec K=k[[1,−1,0],[−1,2,−1],[0,−1,1]]. Les deux ressorts représentent les liaisons chimiques autour de leur longueur d’équilibre.</p>
<h3>Équations et valeurs propres</h3><p>Le PFD, ou les équations de Lagrange, donne <strong>MẌ+KX=0</strong>. Un mode X=a cos(ωt) vérifie Ka=ω²Ma. Comme les masses sont différentes, diagonaliser K seul ne donne pas les pulsations. Poser b=M<sup>1/2</sup>a : la matrice D=M<sup>−1/2</sup>KM<sup>−1/2</sup> est réelle symétrique et Db=ω²b.</p>
<h3>Les trois mouvements</h3><ul><li>(1,1,1), ω=0 : translation de la molécule dans la direction étudiée.</li><li>(1,0,−1), ω₁²=k/m<sub>O</sub> : les oxygènes sont en opposition, le carbone reste immobile.</li><li>(1,−2m<sub>O</sub>/m<sub>C</sub>,1), ω₂²=k/m<sub>O</sub>+2k/m<sub>C</sub> : les oxygènes vont ensemble et le carbone en sens opposé.</li></ul>
<p>Pour les deux vibrations, ∑m<sub>j</sub>a<sub>j</sub>=0 : le centre de masse reste fixe. Ce contrôle donne immédiatement le rapport d’amplitude du carbone dans le second mode.</p>
<p><strong>À retenir :</strong> le mode nul appartient ici à un modèle longitudinal. Les flexions transversales de CO₂ ne sont pas contenues dans ces trois coordonnées ; elles nécessitent un autre potentiel et d’autres degrés de liberté.</p>'''),
lesson('Énergie des modes, isotopes et nombres d’onde', 'Spé → Au-delà', 'molecule_co2', '''
<p>Si a<sub>i</sub> et a<sub>j</sub> correspondent à des valeurs propres différentes, la symétrie de K donne (ω<sub>i</sub>²−ω<sub>j</sub>²)a<sub>i</sub>ᵀMa<sub>j</sub>=0. Les modes sont donc orthogonaux pour le produit scalaire <strong>pondéré par les masses</strong>. Leur norme usuelle n’a aucune raison d’être 1 ni de représenter une énergie.</p>
<h3>Découpler le mouvement</h3><p>Avec des modes normalisés par a<sub>i</sub>ᵀMa<sub>j</sub>=δ<sub>ij</sub>, écrire X=∑Q<sub>i</sub>a<sub>i</sub>. On obtient T=½∑Q̇<sub>i</sub>² et V=½∑ω<sub>i</sub>²Q<sub>i</sub>². Chaque coordonnée vibratoire vérifie Q̈<sub>i</sub>+ω<sub>i</sub>²Q<sub>i</sub>=0 ; la translation vérifie Q̈₀=0.</p>
<h3>Changer la masse sans changer la liaison</h3><p>Un remplacement isotopique change ici M, mais laisse k constant. Si seul m<sub>C</sub> augmente, ω₁ reste identique car le carbone ne participe pas à ce mode ; ω₂ diminue. Cette comparaison est plus formatrice qu’une simple substitution numérique dans √(k/m), car tous les atomes ne contribuent pas de la même façon.</p>
<h3>Relier les unités à la spectroscopie</h3><p>La fréquence est ν=ω/(2π), en Hz. Le nombre d’onde spectroscopique est ν/c, en m⁻¹, puis ν/(100c), en cm⁻¹. Il ne faut pas le confondre avec le nombre d’onde angulaire κ=2π/λ. L’unité de masse atomique vaut u=1,66053906660×10⁻²⁷ kg ; 1 pm=10⁻¹² m.</p>
<p><strong>Prolongement :</strong> le modèle prédit des fréquences mécaniques, sans calculer quelles vibrations sont actives en infrarouge ou en Raman. Les intensités et règles de sélection dépendent des variations du moment dipolaire et de la polarisabilité ; elles ne se déduisent pas des seules valeurs propres de D.</p>'''),
lesson('Le pendule de Foucault : écrire le PFD terrestre', 'Spé', 'foucault', '''
<p>On utilise des axes horizontaux x,y et un axe vertical z orienté vers le haut. La pesanteur effective vaut −g e<sub>z</sub> ; l’accélération centrifuge stationnaire est incluse dans cette pesanteur. La vitesse angulaire terrestre a une composante verticale Ω=Ω<sub>T</sub> sin λ, où λ est la latitude, positive au nord.</p>
<h3>Identifier la force qui dévie</h3><p>Le PFD dans le référentiel terrestre contient la force de Coriolis −2mΩ⃗<sub>T</sub>×v⃗. Aux petits angles, la tension est voisine de mg et son rappel horizontal vaut −mg(x,y)/L. Après projection et au premier ordre des déplacements horizontaux : <strong>ẍ+ω₀²x=2Ωẏ ; ÿ+ω₀²y=−2Ωẋ</strong>, avec ω₀²=g/L.</p>
<h3>Contrôles immédiats</h3><p>La force de Coriolis est perpendiculaire à la vitesse, donc elle ne travaille pas. Pour ces équations linéaires, ½m(ẋ²+ẏ²)+½mω₀²(x²+y²) est conservée. À l’équateur Ω=0 et les deux oscillateurs ne sont plus couplés ; changer de signe la latitude change de signe la déviation.</p>
<h3>Vérifier les hypothèses</h3><p>A/L mesure l’ordre de grandeur de l’angle. Le rapport |Ω|/ω₀ compare les deux échelles de temps et vaut quelques 10⁻⁴ pour un grand pendule. La composante horizontale de la rotation terrestre ne contribue pas au même ordre au mouvement horizontal linéarisé ; elle intervient dans les corrections de la tension et dans des termes de plus petit ordre.</p>
<p><strong>Technique CPGE :</strong> nommer le référentiel, dessiner les axes, distinguer pesanteur effective et forces d’inertie, projeter le PFD puis vérifier le signe par le produit vectoriel. L’équation obtenue est un modèle de petits déplacements, pas celle d’un pendule sphérique arbitraire.</p>'''),
lesson('Une oscillation rapide dans un plan qui tourne lentement', 'Spé → Au-delà', 'foucault', '''
<p>Poser z=x+iy regroupe les deux équations en z̈+2iΩż+ω₀²z=0. Le changement de variable <strong>z=e<sup>−iΩt</sup>w(t)</strong> donne ẅ+(ω₀²+Ω²)w=0. Le facteur complexe e<sup>−iΩt</sup> tourne la figure ; w(t) décrit son oscillation rapide.</p>
<h3>Respecter les conditions initiales</h3><p>Le lâcher sans vitesse dans les axes terrestres impose z(0)=A et ż(0)=0. Il faut donc w(0)=A et ẇ(0)=iΩA. Avec ν=√(ω₀²+Ω²), on obtient w=A[cos(νt)+i(Ω/ν)sin(νt)]. Remplacer w par une constante supprimerait l’oscillation ; négliger son petit terme imaginaire introduirait une vitesse initiale terrestre non nulle.</p>
<h3>Trois durées à ne pas confondre</h3><p>La période rapide est 2π/ν≈2π√(L/g). La direction tourne à la vitesse orientée −Ω. Un tour complet prend 2π/|Ω|=T<sub>sidéral</sub>/|sin λ|. Le jour sidéral vaut 86164,0905 s ; utiliser 24 h est une approximation raisonnable pour un premier calcul, mais le laboratoire emploie le jour sidéral.</p>
<p>Une droite n’a pas de sens privilégié : son orientation est définie modulo π. La durée d’un retour de la même droite est donc π/|Ω| ; la durée affichée dans le bilan est celle d’un tour orienté complet de 2π. Ces deux lectures doivent être distinguées.</p>
<h3>Observer sans créer de fausse lenteur</h3><p>Une trajectoire sur plusieurs heures ne peut pas être correctement représentée avec seulement quelques centaines de points espacés de minutes. Le laboratoire affiche trois enregistrements courts et suffisamment échantillonnés, séparés dans le temps. L’angle de précession, lui, varie réellement à l’échelle des heures.</p>'''),
lesson('Pendule exact : obtenir une période à partir de l’énergie', 'Sup → Spé', 'pendule_exact', '''
<p>L’angle θ est compté depuis la verticale descendante. Une masse ponctuelle m est reliée à un point fixe par une liaison de longueur L. Pour un fil, la tension doit rester positive ; pour un lâcher sans vitesse à plus de 90°, il faut une <strong>tige rigide</strong> sans masse. Le modèle à grande amplitude du laboratoire utilise cette possibilité.</p>
<h3>L’équation mécanique</h3><p>Le moment du poids donne mL²θ̈=−mgL sin θ. Ainsi θ̈+(g/L) sin θ=0. L’énergie vaut E=½mL²θ̇²+mgL(1−cos θ). Si l’on lâche à θₘ sans vitesse, E=mgL(1−cos θₘ) et |θ̇|=√[(2g/L)(cos θ−cos θₘ)].</p>
<h3>Le temps d’un quart d’oscillation</h3><p>Par symétrie, T=4∫₀^{θₘ}dθ/√[(2g/L)(cos θ−cos θₘ)]. L’intégrande devient infinie au point de rebroussement mais cette singularité est intégrable. Poser sin(θ/2)=s sin φ, s=sin(θₘ/2), élimine cette difficulté : <strong>T=4√(L/g)∫₀^{π/2}dφ/√(1−s²sin²φ)</strong>.</p>
<h3>Contrôler plutôt que supposer</h3><p>Le laboratoire calcule T par une quadrature de Gauss à 96 points. Il calcule séparément la trajectoire par l’algorithme de Verlet et mesure T entre deux passages descendants par θ=0. L’accord de ces méthodes et la variation de l’énergie fournissent des contrôles indépendants.</p>
<p><strong>Résultat physique :</strong> la masse n’intervient ni dans l’équation ni dans la période. En revanche, θₘ intervient dans la période exacte. L’isochronisme est une propriété approchée du pendule aux petits angles.</p>'''),
lesson('Petits angles, sommet instable et contrôle numérique', 'Sup → Spé', 'pendule_exact', '''
<p>Pour θₘ petit, développer l’intégrande de la période donne T/T₀=1+θₘ²/16+11θₘ⁴/3072+O(θₘ⁶), avec T₀=2π√(L/g). Les angles doivent être exprimés en <strong>radians</strong> : 60° vaut π/3, et non 60 dans cette formule.</p>
<h3>Que se passe-t-il près de θ=π ?</h3><p>θ=π est un équilibre instable du pendule à tige. Au niveau d’énergie E=2mgL, la trajectoire sépare oscillations et rotations. Pour θₘ=π−ε, ε petit et positif, la période diverge comme 4√(L/g) ln(8/ε). Le pendule passe un temps très long près du sommet, où le moment du poids devient très faible.</p>
<h3>Le portrait de phase</h3><p>Les petites orbites autour de (θ,θ̇)=(0,0) sont presque elliptiques. À énergie croissante, elles s’approchent de la trajectoire séparatrice passant par les sommets instables. Une grande période n’est pas une grande vitesse : elle provient surtout du ralentissement à proximité du sommet.</p>
<h3>L’algorithme de Verlet</h3><p>Avec a(θ)=−(g/L)sin θ : θ<sub>n+1</sub>=θ<sub>n</sub>+hθ̇<sub>n</sub>+½h²a(θ<sub>n</sub>), puis θ̇<sub>n+1</sub>=θ̇<sub>n</sub>+½h[a(θ<sub>n</sub>)+a(θ<sub>n+1</sub>)]. Cette méthode conserve bien la géométrie des trajectoires conservatives sans conserver exactement l’énergie à chaque pas. Diminuer h doit améliorer le bilan.</p>
<p><strong>Technique :</strong> séparer l’erreur de modèle, par exemple sin θ≈θ, de l’erreur de discrétisation. Une trajectoire numérique précise du modèle linéaire ne devient pas pour autant une trajectoire exacte du pendule réel.</p>'''),
lesson('Développement quartique : corriger le rappel du pendule', 'Sup → Spé', 'pendule_anharmonique', '''
<p>V=mgL(1−cos θ) donne V=mgL(θ²/2−θ⁴/24+O(θ⁶)). Le moment généralisé −∂V/∂θ est −mgL(θ−θ³/6+O(θ⁵)). Le mouvement tronqué vérifie donc <strong>θ̈+ω₀²(θ−θ³/6)=0</strong>. Le terme cubique réduit le rappel par rapport au modèle linéaire : on parle d’un oscillateur assouplissant.</p>
<h3>Pourquoi la correction change aussi la période</h3><p>Remplacer seulement la sinusoïde par une sinusoïde légèrement déformée à la même fréquence laisse une erreur de phase qui grandit au fil des oscillations. Il faut chercher une pulsation Ω=ω₀(1−θₘ²/16)+O(θₘ⁴), d’où T=T₀(1+θₘ²/16)+O(θₘ⁴).</p>
<h3>Une approximation locale</h3><p>Le polynôme θ²/2−θ⁴/24 possède un minimum local en 0, mais tend vers −∞ lorsque |θ|→∞. Le potentiel exact, lui, est périodique et borné. Le polynôme tronqué n’est donc pas un potentiel global de pendule ; l’utiliser à des angles arbitrairement grands produit un autre système.</p>
<p>Le laboratoire limite les comparaisons à θₘ≤80°. Le modèle avec rappel cubique est intégré avec les mêmes conditions initiales que le modèle exact. La différence mesurée provient d’abord des termes supprimés du développement ; la variation d’énergie du calcul exact contrôle séparément l’intégration.</p>
<p><strong>Points d’appui CPGE :</strong> développement limité, lien force–potentiel, stabilité locale, dimensions et conservation de l’énergie. Les corrections de pulsation obtenues par méthode perturbative constituent un prolongement de ces techniques.</p>'''),
lesson('D’où vient la troisième harmonique ?', 'Spé → Au-delà', 'pendule_anharmonique', '''
<p>La non-linéarité cubique produit une composante de rang 3 car cos³ψ=(3cosψ+cos3ψ)/4. Chercher θ=θₘ cos(Ωt)+θₘ³b(Ωt)+… fait apparaître une correction à la fréquence fondamentale et une oscillation à 3Ω.</p>
<h3>Fixer la convention d’amplitude</h3><p>Dans ce laboratoire, θₘ est l’angle au point de rebroussement, et θ̇(0)=0. À l’ordre utile : <strong>θ≈θₘ[(1+θₘ²/192)cos(Ωt)−(θₘ²/192)cos(3Ωt)]</strong>, avec Ω≈ω₀(1−θₘ²/16). Les deux corrections se compensent à t=0 : θ(0)=θₘ. Utiliser l’amplitude de la fondamentale comme paramètre conduirait à une écriture légèrement différente.</p>
<h3>Mesurer un spectre sans faux étalement</h3><p>Sur un nombre entier de périodes exactes, projeter θ(t) sur cos(jωt) et sin(jωt). Pour chaque rang, l’amplitude est la racine de la somme des carrés des deux coefficients. L’ajustement aux rangs impairs 1,3,…,9 évite de confondre une fréquence de FFT arrondie avec une véritable nouvelle harmonique.</p>
<p>La symétrie θ(t+T/2)=−θ(t) annule les harmoniques paires. Au premier ordre utile, A₃/A₁≈θₘ²/192. À plus grande amplitude, les rangs 5,7,… deviennent détectables et la formule à deux harmoniques cesse de suffire.</p>
<h3>Ce que l’on compare</h3><p>Une période peut être bien approchée alors que la forme du signal l’est moins, ou inversement. Les trois graphiques — trajectoire, période et harmoniques — testent trois propriétés distinctes du modèle. Une correction perturbative ne doit pas être jugée uniquement sur une seule oscillation.</p>'''),
lesson('Deux ressorts transversaux : une force géométriquement non linéaire', 'Sup → Spé', 'ressorts_transverses', '''
<p>Les points d’attache sont (0,L) et (0,−L). La masse se déplace suivant x sur le rail y=0. Chaque ressort a raideur k et longueur à vide L₀ ; sa longueur instantanée est ℓ=√(x²+L²). On suppose que les ressorts transmettent aussi la compression.</p>
<h3>Deux méthodes pour obtenir la force</h3><p>Chaque ressort stocke ½k(ℓ−L₀)². Leur somme donne <strong>V(x)=k(√(x²+L²)−L₀)²</strong>. En dérivant : V′=2k(1−L₀/ℓ)x et m ẍ=−V′. On peut aussi projeter sur x chacune des deux forces de Hooke ; le facteur x/ℓ explique la même expression.</p>
<h3>Chercher tous les équilibres</h3><p>V′=0 impose x=0 ou ℓ=L₀. Pour L&gt;L₀, seul le centre existe. Pour L&lt;L₀, les positions x=±√(L₀²−L²) s’ajoutent ; les deux ressorts y retrouvent leur longueur à vide. Ne retenir que la solution x=0 manquerait les minima les plus importants.</p>
<h3>Étudier la stabilité</h3><p>V″(0)=2k(1−L₀/L). Le centre est stable si L&gt;L₀ et instable si L&lt;L₀. Aux équilibres latéraux, V″=2k(1−L²/L₀²)&gt;0. Les pulsations de petites oscillations valent √(V″/m), évaluées au minimum étudié.</p>
<p><strong>Technique CPGE :</strong> construire une énergie potentielle complète, dériver, trouver toutes les racines, puis étudier la stabilité et la validité d’une linéarisation. La loi de Hooke linéaire n’implique pas une force linéaire dans une coordonnée liée à une géométrie variable.</p>'''),
lesson('Deux puits, barrière d’énergie et changement de stabilité', 'Spé → Au-delà', 'ressorts_transverses', '''
<p>Le paramètre de commande est ρ=L/L₀. Pour ρ&gt;1, le potentiel possède un seul minimum au centre. Pour ρ&lt;1, le centre devient un maximum local et deux minima symétriques apparaissent. Le graphe des équilibres en fonction de ρ montre ce changement de stabilité, appelé une bifurcation de type fourche dans les modèles symétriques.</p>
<h3>Prévoir le mouvement sans intégrer</h3><p>E=½m ẋ²+V(x) impose V(x)≤E. Pour L&lt;L₀, la barrière centrale vaut V(0)=k(L₀−L)². Si E&lt;V(0), une masse à droite reste dans le puits droit. Si E&gt;V(0), elle peut traverser le centre. À E=V(0), la trajectoire peut tendre asymptotiquement vers l’équilibre instable : la durée caractéristique diverge.</p>
<h3>Développement autour du centre</h3><p>Pour |x|≪L : V(x)=k(L−L₀)²+k(1−L₀/L)x²+[kL₀/(4L³)]x⁴+O(x⁶). Le coefficient de x² change de signe au seuil ; le coefficient de x⁴ est positif. Ce développement explique la forme locale du changement de stabilité.</p>
<p>Le développement est autour du centre, et non autour des minima latéraux. Si l’on veut une approximation harmonique dans un puits, il faut poser ξ=x−xₑ et développer V(xₑ+ξ)=V(xₑ)+½V″(xₑ)ξ²+… . Confondre ces deux centres de développement conduit à une mauvaise pulsation.</p>
<h3>Lire le portrait de phase</h3><p>Les courbes fermées autour de chaque minimum représentent les oscillations confinées. Au-dessus de la barrière, une seule orbite peut entourer les deux minima. Le calcul temporel du laboratoire vérifie cette prédiction énergétique ; il ne remplace pas le raisonnement sur V≤E.</p>'''),
lesson('Minimum quartique : la stabilité ne se réduit pas à V″ > 0', 'Sup → Spé', 'oscillateur_quartique', '''
<p>Au seuil L=L₀, √(L₀²+x²)−L₀=x²/(2L₀)+O(x⁴). Les deux ressorts donnent V=kx⁴/(4L₀²)+O(x⁶). On pose β=k/L₀², en N/m³, et on étudie le modèle <strong>V=βx⁴/4</strong>. La force vaut −βx³.</p>
<h3>Un équilibre stable avec V″(0)=0</h3><p>V(x)&gt;V(0) pour tout x≠0 : le centre est un minimum strict. Il est stable malgré une dérivée seconde nulle. Le critère V″&gt;0 est suffisant, mais une dérivée seconde nulle exige d’examiner le premier terme non nul du développement ; ici ce terme est pair et positif.</p>
<h3>Pourquoi la fréquence linéaire est inutilisable</h3><p>Linéariser m ẍ=−βx³ au centre donne ẍ=0. Cela signifie que le rappel linéaire est nul, et non que toute perturbation réelle s’éloigne sans retour. Pour calculer les petites oscillations, il faut conserver le premier terme de rappel existant, même s’il est non linéaire.</p>
<h3>Une amplitude et une période</h3><p>Au lâcher x=A&gt;0, ẋ=0 et E=βA⁴/4. Pour tout A positif, le mouvement est périodique entre −A et A. À amplitude nulle, le mouvement est stationnaire ; il n’y a pas de période mesurable. La limite T→∞ lorsque A→0 est compatible avec cette situation.</p>
<p><strong>Transfert de technique :</strong> un minimum en x⁶ ou x⁸ demanderait le même examen. Pour V∝x<sup>2p</sup> avec p&gt;1, le rappel dominant est en x<sup>2p−1</sup> et la période dépend nécessairement de l’amplitude.</p>'''),
lesson('La loi T ∝ 1/A : énergie et changement d’échelle', 'Spé → Au-delà', 'oscillateur_quartique', '''
<p>La conservation de l’énergie donne ẋ²=(β/2m)(A⁴−x⁴). Un quart de période est l’intégrale de dx/|ẋ| entre 0 et A. Avec u=x/A : <strong>T=4√(2m/β) A⁻¹ I</strong>, où I=∫₀¹du/√(1−u⁴).</p>
<h3>Régulariser l’intégrale</h3><p>Au point u=1, l’intégrande a une singularité intégrable. Poser u=sin φ donne I=∫₀^{π/2}dφ/√(1+sin²φ), sans singularité. Numériquement, I≈1,31103 et T≈7,41630√(m/β)/A. Les dimensions sont correctes : √(m/β) est en m·s.</p>
<h3>Retrouver la même loi sans quadrature</h3><p>Avec x=Au et τ=A√(β/m)t, l’équation devient u″+u³=0, u(0)=1, u′(0)=0. Tous les mouvements ont la même période en τ ; en secondes, leur période est donc proportionnelle à 1/A. Doubler A divise exactement T par deux dans le modèle quartique pur.</p>
<h3>Comparer au modèle exact des ressorts</h3><p>V<sub>exact</sub>=k(√(L₀²+x²)−L₀)² partage le même premier terme, mais possède des corrections en x⁶ et au-delà. Le produit T×A n’y est plus exactement constant. Le laboratoire calcule une seconde période par quadrature dans ce potentiel, puis la compare à la loi quartique.</p>
<p><strong>Interprétation :</strong> l’égalité T∝1/A est un résultat exact du modèle V=βx⁴/4. Pour les ressorts, c’est une loi asymptotique quand A/L₀→0. La distinction entre modèle exact et approximation locale permet de donner un sens physique à l’écart mesuré.</p>'''),
lesson('Oscillateur forcé : énergie, régime établi et Duffing', 'Sup → Spé', 'duffing_force', '''
<p>Le cours linéaire étudie m ẍ+λẋ+kx=F₀cos(ωt). Avec ω₀=√(k/m), ζ=λ/(2mω₀), r=ω/ω₀, x=x<sub>réf</sub>u et τ=ω₀t, on obtient u″+2ζu′+u=f cos(rτ), où f=F₀/(mω₀²x<sub>réf</sub>).</p>
<h3>Ajouter une force cubique</h3><p>Un potentiel V=½kx²+¼b x⁴ donne un terme b x³ dans l’équation. Après réduction, <strong>u″+2ζu′+u+βu³=f cos(rτ)</strong>, avec β=b x<sub>réf</sub>²/k. Le laboratoire choisit β≥0, un rappel durcissant et un potentiel borné inférieurement.</p>
<h3>Le bilan énergétique</h3><p>La multiplication par u′ donne dE/dτ=f cos(rτ)u′−2ζu′², avec E=½u′²+½u²+βu⁴/4. L’amplitude de la force seule ne suffit pas à prévoir son travail : c’est le produit force×vitesse qui donne la puissance. En régime périodique établi, l’énergie moyenne ne change plus et les puissances moyennes injectée et dissipée sont égales.</p>
<h3>Une réponse calculée, pas supposée</h3><p>Le calcul part de u(0) choisi et de u′(0)=0. L’intégration à fréquence fixe garde le transitoire. L’amplitude fondamentale est mesurée sur les dix dernières périodes, puis sur les dix précédentes. Leur écart sert à vérifier si la réponse est presque stationnaire ; une durée finie ne le garantit pas.</p>
<p><strong>Repères :</strong> oscillateur linéaire amorti forcé et puissances moyennes : cours CPGE. Le terme cubique, les réponses multiples et les bifurcations : prolongement explicite. Les unités physiques se retrouvent avec x=x<sub>réf</sub>u et t=τ/ω₀.</p>'''),
lesson('Une approximation de la résonance non linéaire', 'Spé → Au-delà', 'duffing_force', '''
<p>Pour une réponse presque sinusoïdale, chercher u≈A cos(rτ−φ). Comme cos³ψ=(3cosψ+cos3ψ)/4, négliger le rang 3 revient à remplacer βu³ par (3βA²/4)u dans la composante fondamentale.</p>
<h3>Éliminer le déphasage</h3><p>Projeter l’équation sur le cosinus et le sinus donne f²=A²[(1−r²+3βA²/4)²+(2ζr)²]. Avec Z=A², c’est un polynôme cubique. Pour β=0, on retrouve l’amplitude linéaire A=f/√[(1−r²)²+(2ζr)²]. Pour β&gt;0, la pulsation effective augmente avec A : la résonance se déforme vers les fréquences élevées.</p>
<h3>Ce que signifient trois racines</h3><p>Trois racines positives donnent trois amplitudes candidates de cette approximation. Elles ne prouvent pas que trois mouvements stables existent. Il faut examiner la stabilité des réponses périodiques et les harmoniques supprimées. Une préparation initiale et un balayage lent peuvent sélectionner des réponses différentes ; le laboratoire calcule une seule évolution à fréquence fixe.</p>
<h3>Lire les contrôles</h3><p>Le point mesuré sur la courbe de réponse est la fondamentale du mouvement intégré. Son écart aux racines approchées peut provenir d’harmoniques importantes, d’un transitoire ou d’une réponse non simplement périodique. Le bilan du travail et de la dissipation contrôle la méthode numérique, pas la pertinence de l’approximation à une harmonique.</p>
<p><strong>Prolongement guidé :</strong> pour démontrer une hystérésis, il faudrait construire deux balayages temporels lents, croissant et décroissant, et vérifier leurs vitesses. La seule forme repliée d’une équation approchée ne suffit pas ; cette expérience prépare cette étude sans la prétendre réalisée.</p>'''),
]

EXERCISES = [
exercise('Chaîne périodique : établir la dispersion', 'Sup → Spé', 'chaine_atomique', '<p>N masses m, espacées de a, sont reliées par des ressorts k. Pour uⱼ=Ueⁱ⁽κja−ωt⁾, établir les valeurs permises de κ et la relation de dispersion. Interpréter q=0.</p>', '<p>Le PFD donne m üⱼ=k(uⱼ₊₁+uⱼ₋₁−2uⱼ). La périodicité impose eⁱκNa=1, donc κ=2πq/(Na), q entier modulo N. Après substitution, mω²=k(2−2cosκa)=4k sin²(κa/2), d’où ω=2√(k/m)|sin(κa/2)|. Pour q=0, uⱼ est indépendant de j : aucune liaison n’est allongée, et le mode est une translation. À vitesse nulle, le déplacement commun reste constant.</p>'),
exercise('Combien de modes et quelle énergie ?', 'Spé', 'chaine_atomique', '<p>Pourquoi q et N−q ont-ils la même fréquence sans rendre tous leurs mouvements identiques ? Montrer que la somme des énergies cinétique et élastique est conservée.</p>', '<p>Les facteurs e²ⁱπqj/N et e⁻²ⁱπqj/N sont conjugués. Leurs combinaisons réelles donnent un cosinus et un sinus spatiaux de même fréquence ; sauf les cas q=0 et, pour N pair, q=N/2, ce sont deux directions indépendantes dans l’espace des déplacements. Pour E=½m∑u̇ⱼ²+½k∑(uⱼ₊₁−uⱼ)², dériver puis décaler les indices dans la somme périodique : dE/dt=∑u̇ⱼ[m üⱼ−k(uⱼ₊₁+uⱼ₋₁−2uⱼ)]=0. Chaque ressort est compté une fois.</p>'),
exercise('Vitesse de groupe et précision du milieu continu', 'Spé → Au-delà', 'chaine_atomique', '<p>Pour 0&lt;κa&lt;π, calculer la vitesse de groupe. Trouver le premier écart relatif entre la pulsation exacte et cκ pour κa petit.</p>', '<p>ω=2√(k/m)sin(κa/2), donc dω/dκ=a√(k/m)cos(κa/2)=c cos(κa/2). Le développement sin s=s−s³/6+… donne ω=cκ[1−(κa)²/24+O((κa)⁴)]. L’écart relatif à la pulsation linéaire vaut donc (κa)²/24 au premier ordre. La limite continue dépend de la longueur d’onde, pas seulement d’un nombre N élevé.</p>'),
exercise('CO₂ : retrouver les modes sans calculer un déterminant', 'Spé', 'molecule_co2', '<p>Pour trois masses mO,mC,mO et deux liaisons k, tester les formes (1,1,1), (1,0,−1) et (1,b,1). Déterminer leurs pulsations et b.</p>', '<p>La première forme annule K : ω=0. Pour (1,0,−1), Ka=k a et Ma=mO a, donc ω₁²=k/mO. Pour le troisième mode non nul, le centre de masse est fixe : 2mO+mC b=0, donc b=−2mO/mC. La première ligne Ka=ω²Ma donne k(1−b)=ω²mO, donc ω₂²=k/mO+2k/mC. Les trois formes sont indépendantes et couvrent les trois coordonnées longitudinales.</p>'),
exercise('Pourquoi diagonaliser une matrice symétrique ?', 'Spé', 'molecule_co2', '<p>Le problème est Ka=ω²Ma avec M positive diagonale. Le transformer en un problème symétrique et démontrer l’orthogonalité des modes de fréquences différentes.</p>', '<p>Poser b=M¹ᐟ²a donne D b=ω²b, D=M⁻¹ᐟ²KM⁻¹ᐟ². Comme K est symétrique, D l’est aussi. Pour deux modes, aᵢᵀKaⱼ=ωⱼ²aᵢᵀMaⱼ et, par symétrie, aᵢᵀKaⱼ=ωᵢ²aᵢᵀMaⱼ. Si ωᵢ²≠ωⱼ², aᵢᵀMaⱼ=0. C’est cette orthogonalité pondérée qui supprime les termes croisés dans l’énergie.</p>'),
exercise('Carbone 13 : quelle raie se déplace ?', 'Spé', 'molecule_co2', '<p>On remplace ¹²C par ¹³C sans changer k ni les oxygènes ¹⁶O. Calculer le rapport des deuxièmes fréquences et identifier le mode inchangé.</p>', '<p>ω₁²=k/(16u) est inchangé. Pour le mode avec carbone mobile, ω₂²=(k/u)(1/16+2/mC), où mC vaut 12 ou 13 en unités u. Le rapport ω₂(13)/ω₂(12)=√[(1/16+2/13)/(1/16+2/12)]≈0,9716. La fréquence baisse d’environ 2,84 %. Le déplacement des raies découle ici de la masse ; le modèle ne prédit pas leurs intensités.</p>'),
exercise('Foucault : équation complexe et conditions initiales', 'Spé', 'foucault', '<p>Partir de ẍ+ω₀²x=2Ωẏ et ÿ+ω₀²y=−2Ωẋ. Résoudre avec x(0)=A,y(0)=0 et vitesse nulle, en posant z=x+iy.</p>', '<p>L’addition donne z̈+2iΩż+ω₀²z=0. Avec z=e⁻ⁱΩt w, on obtient ẅ+ν²w=0, ν²=ω₀²+Ω². Les conditions initiales sont w(0)=A et ẇ(0)=iΩA, donc w=A[cosνt+i(Ω/ν)sinνt]. Finalement z=Ae⁻ⁱΩt[cosνt+i(Ω/ν)sinνt]. Le facteur lent et l’oscillation rapide remplissent des rôles différents ; les deux sont nécessaires à la solution.</p>'),
exercise('Un tour au Panthéon et à l’équateur', 'Sup → Spé', 'foucault', '<p>Avec λ=49° et L=67 m, estimer les périodes d’oscillation et de précession. Que devient la précession à l’équateur et dans l’hémisphère sud ?</p>', '<p>T₀=2π√(67/9,81)≈16,42 s. Ω=(2π/86164,0905)sin49°, donc le tour orienté complet dure 86164,0905/sin49°≈114171 s≈31,71 h. La direction non orientée d’une droite revient en la moitié de cette durée. À λ=0, Ω=0 : aucune précession dans le modèle. Au sud, sinλ est négatif, donc le sens de rotation est inversé ; sa durée positive dépend de |sinλ|.</p>'),
exercise('Coriolis conserve-t-elle l’énergie ?', 'Spé', 'foucault', '<p>Montrer directement à partir des deux équations linéaires que E=½m(ẋ²+ẏ²)+½mω₀²(x²+y²) est conservée.</p>', '<p>Dériver : Ė=m[ẋ(ẍ+ω₀²x)+ẏ(ÿ+ω₀²y)]=m(2Ωẋẏ−2Ωẏẋ)=0. Cette annulation traduit v⃗·(Ω⃗×v⃗)=0 : Coriolis dévie la vitesse sans fournir de travail. Elle peut donc changer l’orientation du mouvement sans dissiper son énergie dans le modèle.</p>'),
exercise('Pendule : passer de l’énergie à la période', 'Sup → Spé', 'pendule_exact', '<p>Un pendule est lâché à θₘ sans vitesse. Établir l’intégrale de la période et expliquer pourquoi le calcul ne dépend pas de la masse.</p>', '<p>La conservation de ½mL²θ̇²+mgL(1−cosθ) donne θ̇²=(2g/L)(cosθ−cosθₘ) : m se simplifie. Par symétrie, T=4∫₀^{θₘ}dθ/√[(2g/L)(cosθ−cosθₘ)]. Avec sin(θ/2)=sin(θₘ/2)sinφ, les racines de cosθ−cosθₘ se compensent dans le changement de variable, donnant T=4√(L/g)∫₀^{π/2}dφ/√[1−sin²(θₘ/2)sin²φ].</p>'),
exercise('Angle maximal pour une erreur de 1 %', 'Sup', 'pendule_exact', '<p>À partir de T/T₀≈1+θₘ²/16, estimer l’angle pour lequel la correction de période atteint 1 %. Donner les unités et la portée de cette estimation.</p>', '<p>θₘ²/16≈0,01 donne θₘ≈0,4 rad≈22,9°. C’est une estimation à l’ordre θₘ² ; le terme suivant 11θₘ⁴/3072≈9,17×10⁻⁵ ajoute environ 0,0092 %. Pour une tolérance rigoureuse, il faut comparer à l’intégrale exacte ou encadrer les termes négligés. La substitution de 22,9 en degrés dans θₘ² aurait été incorrecte.</p>'),
exercise('Grand angle et validité d’un fil', 'Spé', 'pendule_exact', '<p>Pour un lâcher sans vitesse, exprimer la tension d’un fil en fonction de θ et θₘ. Pourquoi utiliser une tige pour atteindre des amplitudes proches de π ?</p>', '<p>La projection radiale donne tension=mLθ̇²+mgcosθ. L’énergie donne Lθ̇²=2g(cosθ−cosθₘ), donc tension=mg(3cosθ−2cosθₘ). Au lâcher elle vaut mgcosθₘ. Si θₘ&gt;π/2, elle serait négative : un fil ne peut transmettre cette compression et se détendrait. Une tige rigide de masse négligeable conserve alors la distance et permet l’étude de T→∞ quand θₘ→π. Il faut distinguer la liaison physique du seul dessin d’un segment.</p>'),
exercise('Dériver le potentiel tronqué', 'Sup', 'pendule_anharmonique', '<p>Développer le potentiel du pendule à l’ordre 4, en déduire l’équation avec rappel cubique et préciser pourquoi elle ne constitue pas un modèle global.</p>', '<p>1−cosθ=θ²/2−θ⁴/24+O(θ⁶), donc V=mgL(θ²/2−θ⁴/24)+O(θ⁶). Le moment −V′=−mgL(θ−θ³/6)+O(θ⁵), et mL²θ̈=−V′ donne θ̈+(g/L)(θ−θ³/6)=0 à l’ordre retenu. Le polynôme V tronqué tend vers −∞ à grand |θ|, tandis que le potentiel exact est périodique et borné. Le développement n’a de sens qu’au voisinage de θ=0.</p>'),
exercise('Coefficient de la troisième harmonique', 'Spé → Au-delà', 'pendule_anharmonique', '<p>Chercher θ=A cosτ+A³[c cosτ+d cos3τ], τ=Ωt, Ω=ω₀(1+sA²), avec θ(0)=A. Déterminer s,c,d au premier ordre utile.</p>', '<p>Dans θ̈+ω₀²(θ−θ³/6)=0, le terme cubique vaut A³cos³τ/6=A³(3cosτ+cos3τ)/24. L’équation au rang 1 impose −2s−1/8=0, donc s=−1/16. Au rang 3, (1−9)d−1/24=0, donc d=−1/192. La condition θ(0)=A impose c+d=0, donc c=1/192. On obtient θ=A[(1+A²/192)cosτ−(A²/192)cos3τ]. A est bien l’amplitude au point de rebroussement ; l’amplitude de la fondamentale est A(1+A²/192).</p>'),
exercise('Pourquoi seulement des harmoniques impaires ?', 'Spé', 'pendule_anharmonique', '<p>Pour une oscillation symétrique autour de 0, on a θ(t+T/2)=−θ(t). Montrer que les coefficients de Fourier de rang pair sont nuls.</p>', '<p>Décomposer l’intégrale du coefficient en [0,T/2] et [T/2,T]. Dans la seconde partie, remplacer t par s+T/2. Le signal apporte un facteur −1 et e⁻²ⁱπnt/T apporte (−1)ⁿ. Le coefficient est proportionnel à 1−(−1)ⁿ : il s’annule si n est pair, y compris la moyenne n=0. Pour un potentiel symétrique et un mouvement entre deux points opposés, cette propriété rend le spectre impair ; une asymétrie du système pourrait produire des rangs pairs.</p>'),
exercise('Deux ressorts : force et équilibres', 'Sup → Spé', 'ressorts_transverses', '<p>Deux attaches sont en (0,±L), la masse en (x,0). Établir V, la force selon x et toutes les positions d’équilibre.</p>', '<p>Chaque longueur vaut ℓ=√(x²+L²), donc V=2×½k(ℓ−L₀)²=k(ℓ−L₀)². Comme dℓ/dx=x/ℓ, F=−V′=−2k(1−L₀/ℓ)x. Les équilibres sont x=0 ou ℓ=L₀. Le second cas existe pour L≤L₀ et donne x=±√(L₀²−L²), deux équilibres distincts si L&lt;L₀. À L=L₀, les trois expressions coïncident au centre et la stabilité demande le terme quartique.</p>'),
exercise('Petites oscillations dans chaque puits', 'Spé', 'ressorts_transverses', '<p>Calculer V″ au centre et aux minima latéraux. En déduire les pulsations de petites oscillations et discuter la limite L→L₀.</p>', '<p>V″(x)=2k[1−L₀L²/(x²+L²)³ᐟ²]. Au centre, V″(0)=2k(1−L₀/L), positif si L&gt;L₀. La pulsation centrale vaut √[2k(1−L₀/L)/m]. Aux minima latéraux ℓ=L₀, V″=2k(1−L²/L₀²), donc ωlat=√[2k(1−L²/L₀²)/m]. Ces pulsations tendent vers 0 au seuil. À amplitude finie, le modèle quartique fournit alors une période différente de celle d’une linéarisation.</p>'),
exercise('Confinement ou traversée des deux puits ?', 'Spé', 'ressorts_transverses', '<p>Pour L=0,7L₀, m=1 kg, k=40 N/m et L₀=1 m, trouver la barrière centrale. Une masse lâchée sans vitesse en x=0,8 m peut-elle franchir le centre ? Et en x=1,5 m ?</p>', '<p>V(0)=40(1−0,7)²=3,6 J. À x=0,8 m, ℓ=√(0,64+0,49)=√1,13 et E=40(√1,13−1)²≈0,159 J : E&lt;3,6, donc le centre est inaccessible. À x=1,5 m, ℓ=√2,74≈1,6553 et E≈17,18 J : le centre est accessible et la masse peut traverser les deux puits. La masse n’intervient pas dans ce test énergétique au lâcher ; elle intervient dans la durée du mouvement.</p>'),
exercise('Un minimum sans terme quadratique', 'Sup', 'oscillateur_quartique', '<p>Au seuil L=L₀, développer le potentiel des ressorts au premier ordre non nul. Pourquoi x=0 reste-t-il stable malgré V″(0)=0 ?</p>', '<p>√(L₀²+x²)=L₀+x²/(2L₀)+O(x⁴), donc V=k[x²/(2L₀)+O(x⁴)]²=kx⁴/(4L₀²)+O(x⁶). Le terme dominant est pair et positif pour x≠0 : le centre est un minimum strict. La condition V″(0)&gt;0 est suffisante pour un minimum, mais V″(0)=0 ne permet pas de conclure ; il faut regarder les termes suivants. Le premier rappel est −(k/L₀²)x³.</p>'),
exercise('Période quartique par quadrature', 'Spé', 'oscillateur_quartique', '<p>Pour m ẍ=−βx³, x(0)=A&gt;0 et ẋ(0)=0, établir la période et montrer exactement que doubler A la divise par deux.</p>', '<p>E=½m ẋ²+βx⁴/4=βA⁴/4, donc ẋ²=β(A⁴−x⁴)/(2m). Ainsi T=4√(2m/β)∫₀ᴬ dx/√(A⁴−x⁴)=4√(2m/β)A⁻¹∫₀¹du/√(1−u⁴). L’intégrale est indépendante de A ; T(2A)=T(A)/2. Avec u=sinφ, elle devient ∫₀^{π/2}dφ/√(1+sin²φ), ce qui facilite le calcul numérique.</p>'),
exercise('Généraliser à un potentiel en x²ᵖ', 'Spé → Au-delà', 'oscillateur_quartique', '<p>Pour V(x)=a x²ᵖ, a&gt;0 et p entier positif, prévoir la dépendance de T en l’amplitude A. Retrouver les cas harmonique et quartique.</p>', '<p>Au lâcher E=aA²ᵖ. Alors T=4√(m/2a)∫₀ᴬ dx/√(A²ᵖ−x²ᵖ). Poser x=Au donne T=4√(m/2a) A¹⁻ᵖ∫₀¹du/√(1−u²ᵖ). La période est indépendante de A pour p=1, harmonique. Pour p=2, elle varie comme A⁻¹. Pour p&gt;1, elle diverge à faible amplitude ; cela traduit un rappel de plus en plus faible près du minimum plat.</p>'),
exercise('Retrouver l’oscillateur forcé linéaire', 'Sup → Spé', 'duffing_force', '<p>Pour u″+2ζu′+u=f cos(rτ), établir l’amplitude établie et la pulsation de résonance en déplacement, si elle existe.</p>', '<p>Avec u=Re(Ueⁱʳτ), U=f/(1−r²+2iζr). Donc A=f/√[(1−r²)²+4ζ²r²]. Minimiser le dénominateur en r&gt;0 donne rres²=1−2ζ². La résonance en déplacement existe si ζ&lt;1/√2. Avec Q=1/(2ζ), rres=√[1−1/(2Q²)] ; la pulsation résonante n’est exactement ω₀ qu’à la limite d’un amortissement faible. Une résonance en vitesse ou en puissance n’utilise pas la même fonction à maximiser.</p>'),
exercise('Balance harmonique de Duffing', 'Spé → Au-delà', 'duffing_force', '<p>En ne gardant que la fondamentale dans u³, établir l’équation en A² de la réponse approximative à u″+2ζu′+u+βu³=f cos(rτ). Peut-on conclure à la stabilité à partir de ses seules racines ?</p>', '<p>Écrire u≈Acos(rτ−φ) et cos³ψ=(3cosψ+cos3ψ)/4. Les projections donnent fcosφ=A(1−r²+3βA²/4) et fsinφ=2ζrA. Après élévation au carré et somme : A²[(1−r²+3βA²/4)²+(2ζr)²]=f². Avec Z=A², (9β²/16)Z³+(3β/2)(1−r²)Z²+[(1−r²)²+4ζ²r²]Z−f²=0. Les racines positives sont des réponses candidates ; la stabilité et l’erreur due au rang 3 exigent une analyse supplémentaire.</p>'),
exercise('Puissances moyennes et durée du transitoire', 'Spé', 'duffing_force', '<p>Établir le bilan d’énergie réduit. Pour β=0, quel critère sur la durée d’observation permet d’attendre la disparition d’un transitoire ? Pourquoi ce seul critère ne règle-t-il pas tous les cas non linéaires ?</p>', '<p>E=½u′²+½u²+βu⁴/4 donne E′=fcos(rτ)u′−2ζu′². Sur une période d’une réponse établie, la moyenne de E′ est nulle, donc les puissances moyennes injectée et dissipée sont égales. Dans le cas linéaire sous-amorti, le transitoire décroît comme e⁻ζτ : attendre ζτ≫1 réduit son amplitude. Dans le cas non linéaire, plusieurs attracteurs, modulations ou relaxations lentes près d’une bifurcation peuvent exister. Il faut comparer des fenêtres successives et, au besoin, prolonger le calcul.</p>'),
]

GUIDES = {
'chaine_atomique': {
 'purpose':'Partir du PFD d’une masse, reconnaître un mode propre et déterminer quand la chaîne peut être décrite par une équation d’onde.',
 'objects':['N est le nombre de masses distinctes de la cellule périodique ; l’indice suivant N−1 est 0.', 'uⱼ est un déplacement en mètres, et non la position ja+uⱼ.', 'q repère un mode ; κ=2πq/(Na) est son nombre d’onde. q est ramené modulo N.', 'Une onde stationnaire est lâchée sans vitesse ; l’onde progressive possède les vitesses initiales nécessaires à sa propagation.'],
 'hypotheses':['Masses identiques, ressorts linéaires identiques, vibrations longitudinales et absence de dissipation.', 'La préparation locale se décompose en tous les modes : l’indice q ne décrit alors pas à lui seul le mouvement.', 'La dispersion linéaire est une approximation de grande longueur d’onde, |κa|≪1.'],
 'techniques':['PFD et projection de forces de rappel.', 'Écriture complexe, périodicité, diagonalisation par Fourier discret.', 'Conservation de l’énergie et développement limité pour comparer deux modèles.'],
 'levels':{'sup':'Écrire l’équation d’une masse et vérifier qu’une préparation uniforme ne déforme aucun ressort.', 'spe':'Calculer les modes, la dispersion et le passage à l’équation d’onde ; relier cette étude à l’exercice 2 du PDF.', 'beyond':'Vitesse de groupe, déformation d’une impulsion et mécanique harmonique des réseaux cristallins.'},
 'first_steps':['Choisir « Grande longueur d’onde » et comparer la chaîne exacte à la droite c|κ|.', 'Choisir « Mode alterné » : observer deux masses voisines puis expliquer la pulsation maximale.', 'Choisir « Impulsion locale » et comparer la propagation à la conservation de l’énergie.'],
 'expected':'Savoir distinguer une fréquence propre de la fréquence d’une excitation quelconque et justifier la condition |κa|≪1 pour le modèle continu.'},
'molecule_co2': {
 'purpose':'Identifier les deux vibrations longitudinales de CO₂, puis comprendre pourquoi les masses entrent dans la diagonalisation.',
 'objects':['X=(x₁,x₂,x₃) contient les écarts des atomes à leurs positions d’équilibre.', 'M est la matrice des masses ; K celle des raideurs. Le problème de modes est Ka=ω²Ma.', 'u désigne l’unité de masse atomique ; les déplacements sont en pm et le temps en fs.', 'Le nombre d’onde spectroscopique en cm⁻¹ vaut ω/(2πc), après conversion de mètres en centimètres.'],
 'hypotheses':['Deux liaisons identiques et harmoniques ; seulement les mouvements longitudinaux.', 'Le remplacement isotopique change la masse et laisse ici la raideur constante.', 'La scène amplifie les déplacements ; elle ne représente pas une molécule à l’échelle visuelle réelle.'],
 'techniques':['Énergies quadratiques et équations de Lagrange, ou bilan des forces sur chaque atome.', 'Valeurs propres d’une matrice symétrique après pondération par les masses.', 'Centre de masse fixe dans les vibrations et conversion des unités spectroscopiques.'],
 'levels':{'sup':'Observer les deux formes et retrouver qualitativement quel atome peut rester immobile.', 'spe':'Résoudre les modes et démontrer l’orthogonalité pour aᵀMb ; prolongement de l’exercice 3 du PDF.', 'beyond':'Effets isotopiques et lien avec la spectroscopie ; les intensités infrarouges et Raman demandent d’autres grandeurs.'},
 'first_steps':['Choisir le mode avec carbone immobile ; vérifier le centre de masse.', 'Choisir le mode avec carbone mobile ; comparer son amplitude aux deux oxygènes.', 'Passer de carbone 12 à carbone 13 : quelle fréquence change et pourquoi ?'],
 'expected':'Expliquer les deux pulsations sans confondre masse, raideur et normalisation des vecteurs propres.'},
'foucault': {
 'purpose':'Relier la force de Coriolis à la précession du plan d’oscillation et distinguer les secondes des heures.',
 'objects':['L est la longueur ; A le déplacement horizontal initial. Le petit angle est de l’ordre de A/L.', 'λ est la latitude, positive au nord. Ω=ΩTerre sinλ est la composante verticale de la rotation.', 'ω₀=√(g/L) est la pulsation rapide. z=x+iy regroupe les deux déplacements horizontaux.', 'Les trois traces représentent des enregistrements courts à des heures différentes, et non une trajectoire sous-échantillonnée sur toute la journée.'],
 'hypotheses':['Petits déplacements, pesanteur effective uniforme, aucune dissipation ni excitation d’entretien.', 'ΩTerre est calculée à partir du jour sidéral ; les termes de plus petit ordre sont négligés dans le PFD horizontal.', 'L’angle de la direction est suivi en continu ; une droite non orientée revient déjà après 180°.'],
 'techniques':['PFD dans un référentiel tournant, projection et signe du produit vectoriel.', 'Équation différentielle linéaire complexe et changement z=e⁻ⁱΩt w.', 'Ordres de grandeur et séparation des échelles de temps.'],
 'levels':{'sup':'Comparer T₀ et la durée de précession puis observer le signe de la rotation selon l’hémisphère.', 'spe':'Écrire Coriolis, résoudre l’équation complexe et contrôler les conditions initiales ; exercice 6 du PDF.', 'beyond':'Corrections d’un pendule sphérique, dissipation et précision d’une mesure géophysique.'},
 'first_steps':['Choisir le Panthéon et comparer les périodes en secondes et en heures.', 'Mettre la latitude à 0° : justifier la disparition de la précession.', 'Passer à une latitude négative ; expliquer le changement de signe à partir du PFD.'],
 'expected':'Distinguer le facteur qui tourne la direction et celui qui décrit l’oscillation rapide, sans supprimer les conditions initiales.'},
'pendule_exact': {
 'purpose':'Retrouver la période du pendule à partir de l’énergie, puis mesurer la limite de l’approximation de petit angle.',
 'objects':['θ est l’angle depuis la verticale descendante ; θₘ est l’angle du lâcher sans vitesse.', 'L est la longueur et g=9,81 m/s². La masse se simplifie dans l’équation.', 'T exact provient d’une intégrale ; T₀=2π√(L/g) provient de sinθ≈θ.', 'L’énergie affichée par unité de masse vaut ½L²θ̇²+gL(1−cosθ), en J/kg.'],
 'hypotheses':['Mouvement plan, liaison sans masse de longueur constante, aucune dissipation.', 'Pour θₘ>90°, une tige rigide est nécessaire : un fil ne serait pas tendu au lâcher.', 'Les amplitudes restent inférieures à 180° ; les rotations complètes ne sont pas calculées.'],
 'techniques':['Moment du poids ou PFD tangentiel.', 'Conservation de l’énergie, symétrie et changement de variable dans une intégrale.', 'Comparaison d’une quadrature, d’une trajectoire et d’une mesure de période.'],
 'levels':{'sup':'Équation et énergie du pendule, modèle harmonique, radians et dimensions.', 'spe':'Intégrale de période et développement en amplitude ; contrôle d’un modèle au-delà de sa linéarisation.', 'beyond':'Intégrale elliptique, divergence logarithmique près du sommet et géométrie de la séparatrice.'},
 'first_steps':['Choisir 10° et comparer exact et harmonique sur plusieurs oscillations.', 'Passer à 90° puis comparer T exact, T₀ et la mesure sur la trajectoire.', 'Choisir 165° ; repérer les longs ralentissements près des angles extrêmes et vérifier la liaison supposée.'],
 'expected':'Dire quelles hypothèses rendent la période indépendante de l’amplitude, et séparer erreur de modèle et erreur numérique.'},
'pendule_anharmonique': {
 'purpose':'Donner un sens observable au développement limité d’ordre 4 : une période corrigée et une troisième harmonique.',
 'objects':['θₘ est l’angle maximal du mouvement, et non l’amplitude du seul rang 1.', 'Le potentiel tronqué garde θ² et θ⁴ ; sa dérivée produit un rappel en θ et θ³.', 'Une harmonique de rang j oscille j fois pendant une période fondamentale.', 'Le spectre est mesuré par projection sur les sinus et cosinus des rangs impairs, sur quatre périodes exactes.'],
 'hypotheses':['Même angle initial et vitesse nulle pour les modèles comparés.', 'Angles en radians dans les développements ; l’approximation est locale autour de 0.', 'Le potentiel quartique tronqué ne doit pas être extrapolé à des angles arbitraires.'],
 'techniques':['Développement limité puis dérivation d’un potentiel.', 'Identification des coefficients avec cos³τ et correction de pulsation.', 'Mesure d’amplitude, symétrie du signal et comparaison de modèles.'],
 'levels':{'sup':'Retrouver le terme cubique de la force et prévoir un rappel plus faible que le rappel linéaire.', 'spe':'Comparer T≈T₀(1+θₘ²/16) et les harmoniques ; priorité à l’exercice 7 du PDF.', 'beyond':'Méthode de Lindstedt, choix de la convention d’amplitude et séries de Fourier d’un mouvement non linéaire.'},
 'first_steps':['Commencer à 10° : lire la correction de période et le rapport A₃/A₁.', 'Passer à 50° : identifier le rang 3 et comparer le signal exact à l’approximation.', 'Passer à 80° : expliquer les écarts de période et l’apparition de rangs supérieurs.'],
 'expected':'Relier le terme θ³ à des harmoniques nouvelles, et annoncer l’ordre et la convention d’amplitude d’une formule approchée.'},
'ressorts_transverses': {
 'purpose':'Utiliser le potentiel exact pour trouver les équilibres, leur stabilité et les déplacements accessibles à énergie donnée.',
 'objects':['La masse se déplace selon x ; les attaches fixes sont en (0,±L).', 'Chaque ressort a longueur à vide L₀ et longueur actuelle √(x²+L²).', 'ρ=L/L₀ commande le nombre d’équilibres. L’écart initial est ajouté au centre ou au minimum de droite selon la préparation.', 'V(0) est le niveau de la barrière entre les deux puits si L<L₀.'],
 'hypotheses':['Deux ressorts identiques qui transmettent compression et traction, rail sans frottement.', 'Le poids et la réaction du rail ne travaillent pas dans la direction x.', 'Le développement quartique représenté est autour du centre : sa validité demande |x|/L petit.'],
 'techniques':['Géométrie, somme des énergies et force −V′.', 'Équilibres, signe de V″ et pulsations autour des minima.', 'Condition V≤E, points de rebroussement et portrait de phase.'],
 'levels':{'sup':'Construire V puis faire le lien entre le signe de la force et la pente de V.', 'spe':'Étudier tous les équilibres, leurs petites oscillations et la barrière ; second système de l’exercice 7 du PDF.', 'beyond':'Bifurcation symétrique, trajectoire séparatrice et perte de validité d’une approximation locale.'},
 'first_steps':['Choisir « Un seul puits » et identifier le minimum central.', 'Choisir « Deux puits : rester à droite » : comparer E à V(0) avant de lire le mouvement.', 'Choisir « Franchir la barrière », puis placer L/L₀ à 1 et examiner la disparition du terme quadratique.'],
 'expected':'Prévoir le confinement ou la traversée sans intégrer, et calculer une pulsation autour du bon équilibre.'},
'oscillateur_quartique': {
 'purpose':'Comprendre un équilibre stable dont la linéarisation ne décrit aucune oscillation, puis établir la loi T∝1/A.',
 'objects':['Au seuil L=L₀, le potentiel des deux ressorts commence en x⁴.', 'β=k/L₀² est le coefficient du rappel cubique, en N/m³.', 'A est l’amplitude du lâcher, en mètres ; le contrôle affiche A/L₀.', 'Le modèle quartique pur et les ressorts exacts possèdent le même premier terme, mais des périodes différentes à amplitude non petite.'],
 'hypotheses':['Mouvement conservatif autour du centre, amplitude strictement positive.', 'Le quartique est une approximation des ressorts seulement si A/L₀≪1.', 'La comparaison sépare l’erreur du développement local de l’erreur de quadrature ou d’intégration.'],
 'techniques':['Premier terme non nul d’un développement et stabilité d’un minimum.', 'Énergie, intégrale de période et suppression d’une singularité intégrable.', 'Variables réduites et analyse dimensionnelle.'],
 'levels':{'sup':'Voir pourquoi V″=0 ne signifie pas instabilité et calculer la force cubique.', 'spe':'Établir T(A) par énergie et tester sa dépendance en amplitude ; prolongement direct de l’exercice 7.', 'beyond':'Changements d’échelle et périodes dans les potentiels en x²ᵖ.'},
 'first_steps':['Commencer à A=0,04L₀ et comparer quartique et ressorts exacts.', 'Doubler l’amplitude : vérifier que T quartique est divisée par deux.', 'Passer à A=0,80L₀ : attribuer l’écart de période aux termes négligés du potentiel.'],
 'expected':'Justifier la stabilité au-delà du seul critère V″>0 et distinguer une loi exacte d’une loi asymptotique.'},
'duffing_force': {
 'purpose':'Relier l’oscillateur forcé du cours à une résonance non linéaire, en contrôlant le transitoire et le bilan de puissance.',
 'objects':['τ=ω₀t et u=x/xréf sont le temps et la position réduits.', 'r est le rapport de pulsations ; ζ l’amortissement ; f l’amplitude de forçage ; β le coefficient cubique.', 'L’amplitude mesurée est celle de la composante à la fréquence imposée, sur une fenêtre de dix périodes.', 'Les courbes de réponse proviennent d’une approximation sinusoïdale ; les racines ne sont pas étiquetées comme stables.'],
 'hypotheses':['β≥0 : rappel durcissant et potentiel borné inférieurement ; frottement visqueux.', 'La fréquence est fixe pendant chaque calcul, et non balayée dans le temps.', 'Une réponse quasi stationnaire doit être vérifiée en comparant des fenêtres successives.'],
 'techniques':['Réduction des unités et réponse complexe de l’oscillateur linéaire.', 'Puissance force×vitesse et bilan intégré de l’énergie.', 'Projection harmonique et résolution d’un polynôme en A².'],
 'levels':{'sup':'Amplitude et phase de l’oscillateur linéaire, transitoire et puissance dissipée.', 'spe':'Résonance et bilan moyen ; TP d’oscillations forcées de la fiche P2.', 'beyond':'Balance harmonique de Duffing, réponses multiples et préparation d’une étude de stabilité ou d’hystérésis.'},
 'first_steps':['Choisir la référence linéaire et retrouver A=f/(2ζ) pour r=1.', 'Choisir le rappel durcissant : comparer le point mesuré aux amplitudes approchées.', 'Changer u(0) et augmenter le nombre de périodes ; comparer les deux fenêtres avant de conclure.'],
 'expected':'Dire ce qui est calculé exactement par le modèle temporel, ce qui est approché par une harmonique, et quel contrôle indique un transitoire persistant.'},
}
