"""Cours et exercices originaux associés aux applications P3 du recueil."""
from html import escape

def paragraph(text): return '<p>'+escape(text)+'</p>'
def formula(text): return '<div class="formula">'+escape(text)+'</div>'
def lesson(lab,title,level,context,equation,proof,application):
    return dict(lab=lab,title=title,level=level,html=paragraph(context)+formula(equation)+'<h3>Démonstration et méthode</h3>'+paragraph(proof)+'<h3>Application</h3>'+paragraph(application))
def exercise(lab,title,level,question,answer):
    return dict(lab=lab,title=title,level=level,question=question,answer=answer)

LESSONS=[
lesson('inertie_huygens','Construire une matrice d’inertie à partir de masses ponctuelles','Sup → Spé',
 'Pour un solide, l’inertie dépend de la direction de rotation. On mesure rᵢ=GMᵢ et on représente les positions par des colonnes. Une même formule doit donner tous les moments autour des axes passant par G.',
 'I_G=Σmᵢ[(rᵢ·rᵢ)Id−rᵢrᵢᵀ] ; I(u)=uᵀI_Gu, |u|=1 ; E_c,rotation=½ΩᵀI_GΩ.',
 'La distance au carré entre Mᵢ et l’axe de direction u vaut |rᵢ×u|²=|rᵢ|²−(rᵢ·u)². Sommer après multiplication par mᵢ donne la forme quadratique. I_G est symétrique et positive ; elle est définie positive si les masses ne sont pas toutes sur une même droite. Le théorème spectral fournit une base orthonormée d’axes principaux.',
 'Une tige mince a une inertie nulle suivant sa propre direction dans le modèle idéal, mais une forte inertie autour d’un axe perpendiculaire. Un satellite allongé ne réagit donc pas de la même façon à tous les couples.'),
lesson('inertie_huygens','Huygens : déplacer un axe sans changer sa direction','Spé',
 'O est un point quelconque et d=OG. Le théorème de Huygens relie les inerties autour de deux axes parallèles, l’un passant par G, l’autre par O. Sa version matricielle conserve les produits d’inertie.',
 'I_O=I_G+M[(d·d)Id−ddᵀ] ; I_O(u)=I_G(u)+M|d×u|².',
 'Dans la somme définissant I_O, remplacer OMᵢ par d+rᵢ. Tous les termes linéaires en rᵢ s’annulent parce que Σmᵢrᵢ=0. Il reste I_G et le terme de translation. En multipliant à gauche par uᵀ et à droite par u, on retrouve Huygens scalaire. Si d est parallèle à u, la distance entre les axes vaut zéro : il s’agit du même axe.',
 'Pour une barre homogène de longueur 2L, I_G=ML²/3 autour d’un axe transverse et I_O=4ML²/3 autour d’un pivot situé à l’extrémité.'),
lesson('konig','Second théorème de König : le terme croisé disparaît en G','Sup → Spé',
 'Le référentiel barycentrique a son origine en G et ses axes restent parallèles à ceux du laboratoire. Il peut être accéléré : le théorème de König est d’abord une identité cinématique.',
 'E_c=½M|v_G|²+E_c,G ; vᵢ=v_G+vᵢ/G ; Σmᵢvᵢ/G=0.',
 'Développer chaque carré |v_G+vᵢ/G|². Le terme croisé est v_G·Σmᵢvᵢ/G, nul par dérivation de ΣmᵢGMᵢ=0. Pour un solide rigide, vᵢ/G=Ω×GMᵢ et E_c,G=½ΩᵀI_GΩ. Il ne faut pas remplacer cette énergie par ½Iω² sans avoir identifié l’axe et l’inertie adaptés.',
 'Pour une roue roulant sans glissement, v_G=Rω. Avec I_G=kmR², E_c=½m(1+k)v_G². Le même gain de hauteur donne moins de vitesse de translation à un cerceau qu’à une boule.'),
lesson('konig','Premier théorème de König : moment orbital et moment propre','Spé',
 'Un solide peut tourner autour de son centre de masse tout en se déplaçant par rapport à O. Ces deux mouvements contribuent au moment cinétique en O, qui est un vecteur.',
 'L_O=OG×Mv_G+L_G ; L_G=I_GΩ pour un solide rigide.',
 'Insérer OMᵢ=OG+GMᵢ et vᵢ=v_G+vᵢ/G dans ΣOMᵢ×mᵢvᵢ. Les deux sommes croisées s’annulent grâce aux définitions de G et du référentiel barycentrique. Le terme OG×Mv_G est dit orbital ; le terme L_G décrit le mouvement autour de G. Les deux peuvent être opposés et se compenser.',
 'Une patineuse en mouvement possède un moment orbital par rapport au bord de la patinoire et un moment propre si elle tourne. Le choix du point O change le premier, pas le second.'),
lesson('barre_bascule','Basculement d’une barre : exploiter l’énergie avant le PFD','Sup → Spé',
 'Une barre homogène de longueur 2L est fixée à une extrémité. L’angle θ=0 correspond à la verticale ascendante, équilibre instable. Le pivot ne se déplace pas et sa réaction ne travaille pas.',
 'I_O=4ML²/3 ; E=½I_Oθ̇²+MgLcosθ ; θ̈=(3g/(4L))sinθ.',
 'Le moment du poids en O vaut MgLsinθ dans le sens de croissance de θ. Le théorème du moment cinétique donne I_Oθ̈=MgLsinθ. Multiplier par θ̇ retrouve la conservation de l’énergie. Sur la trajectoire limite E=MgL, θ̇²=(3g/(2L))(1−cosθ), puis θ̇=√(3g/L)sin(θ/2) pour un basculement vers les angles croissants.',
 'À θ=90°, θ̇=√(3g/(2L)) et la vitesse de G vaut √(3gL/2). Une barre longue acquiert une plus grande vitesse linéaire, mais bascule avec une plus faible vitesse angulaire.'),
lesson('barre_bascule','Durée exacte et force du pivot : deux calculs complémentaires','Spé',
 'L’énergie donne la vitesse sans calculer la réaction. Pour la réaction, il faut ensuite revenir au PFD et employer l’accélération normale autant que l’accélération tangentielle.',
 'Δt=2√(L/(3g))ln[tan(θ₂/4)/tan(θ₁/4)] ; Rᵣ=Mg(5cosθ−3)/2 ; Rθ=−Mg sinθ/4.',
 'Intégrer dt=dθ/[√(3g/L)sin(θ/2)] en utilisant une primitive 2ln tan(θ/4). Dans la base eᵣ,eθ, a_G=−Lθ̇²eᵣ+Lθ̈eθ et Mg=−Mgcosθ eᵣ+Mgsinθ eθ. Soustraire le poids à Ma_G donne les deux composantes de R. Rᵣ peut être négatif : un pivot est une liaison qui peut tirer, contrairement à un contact unilatéral.',
 'Le temps diverge logarithmiquement quand θ₁ tend vers 0. Cela traduit l’équilibre instable : une barre exactement dressée, sans perturbation, ne commence pas à tomber spontanément.'),
lesson('barre_rotule','Barre sur rotule : préciser la convention des angles','Spé',
 'La rotule fixe O et autorise une orientation spatiale. On choisit θ comme angle avec la verticale ascendante et φ comme azimut. Cette convention est annoncée pour éviter de mélanger colatitude et élévation.',
 'n=(sinθcosφ,sinθsinφ,cosθ) ; OG=Ln ; v_G=Lṅ ; E_c=½I⊥|ṅ|², I⊥=4ML²/3.',
 'Différencier n composante par composante, ou employer ṅ=θ̇eθ+φ̇sinθ eφ. La vitesse angulaire perpendiculaire à la barre est Ω⊥=n×ṅ. La composante parallèle à n ne modifie pas son axe. Pour une barre mince, l’inertie axiale est négligée : L_O=I⊥n×ṅ, mais il serait incorrect d’affirmer que toute vitesse angulaire est déterminée par OG et v_G.',
 'Un lancer sans vitesse d’azimut donne un mouvement plan. Avec φ̇ initiale non nulle, la conservation de L_z peut empêcher la barre de traverser la verticale.'),
lesson('barre_rotule','Énergie et moment vertical : réduire le pendule spatial','Spé → Au-delà',
 'Le couple du poids n’a pas de composante verticale. La rotule ne transmet aucun couple. Deux constantes du mouvement permettent de décrire l’évolution de l’inclinaison sans résoudre toutes les composantes.',
 'L_z=I⊥sin²θ φ̇ ; E=½I⊥θ̇²+L_z²/(2I⊥sin²θ)+MgLcosθ.',
 'Le théorème du moment cinétique donne dL_z/dt=0. Insérer φ̇=L_z/(I⊥sin²θ) dans l’énergie produit un potentiel effectif en θ. Pour L_z≠0, le terme en 1/sin²θ diverge près des verticales. Une rotation conique vérifie θ̇=0 et φ̇²=−(3g/(4L))/cosθ ; elle exige donc θ>90° avec notre convention.',
 'Pour L=0,7 m et θ=120°, la rotation conique demande φ̇≈4,585 rad/s. Le laboratoire vérifie cette valeur et montre la nutation si l’on perturbe l’inclinaison.'),
lesson('cylindre_bord','Au bord de la table : commencer par le régime d’adhérence','Spé',
 'Le cylindre plein est en contact avec une arête fixe. Pendant l’adhérence, il pivote autour de cette arête et le point matériel en contact a une vitesse nulle.',
 'I_I=3mR²/2 ; θ̇²=(4g/(3R))(1−cosθ) ; T=(mg/3)sinθ ; N=(mg/3)(7cosθ−4).',
 'Huygens donne I_I=I_G+mR². La perte d’énergie potentielle mgR(1−cosθ) fournit l’énergie de rotation. Le PFD tangent à la trajectoire du centre donne mRθ̈=mg sinθ−T ; la projection normale donne N=mg cosθ−mRθ̇². En remplaçant θ̇² et θ̈=(2g/(3R))sinθ, on trouve les expressions affichées.',
 'Les réactions ne sont pas constantes : le contact demande de plus en plus de réaction tangentielle alors que sa réaction normale diminue. La géométrie amplifie donc le risque de glissement.'),
lesson('cylindre_bord','Une formule cesse d’être utilisable quand le contact change','Spé',
 'Un contact unilatéral ne peut exercer une force normale négative. L’adhérence impose en outre |T|≤fₛN. Il faut rechercher le premier événement qui viole ces conditions.',
 'Glissement : sinθ=fₛ(7cosθ−4) ; référence de perte de contact en adhérence : θ_N=arccos(4/7).',
 'Sur 0<θ<θ_N, T/N=sinθ/(7cosθ−4) croît de 0 à +∞. Pour tout coefficient statique fini positif, l’égalité T=fₛN survient donc avant N=0. Après glissement, le point de contact n’est plus fixe : ni I_Iθ̇²/2 ni l’ancienne expression de N ne décrivent automatiquement le mouvement réel. Il faut reconstruire la cinématique et employer T=f_dN avec le bon sens du glissement.',
 'Un algorithme de simulation doit arrêter ce régime au seuil détecté. Prolonger son animation jusqu’à θ_N donnerait une prédiction physiquement injustifiée.'),
lesson('coulomb_horizontal','Loi de Coulomb : une inégalité au repos, une égalité en glissement','Spé · MP',
 'La force de frottement tangentielle est déterminée par le régime du contact. Le coefficient statique donne une borne, pas la valeur obligatoire de la réaction.',
 'Adhérence : |T|≤fₛN ; glissement : T⃗=−f_dN v⃗_contact/|v⃗_contact|.',
 'Sur un sol horizontal avec une traction F, le PFD vertical donne N=mg. Si la caisse reste au repos, le PFD horizontal impose T=−F, possible seulement si |F|≤fₛmg. Au-delà, elle démarre dans le sens de F ; pour une traction constante, T=−f_dmg signe(F) et a=(F+T)/m. À la limite statique, l’adhérence reste admissible : une perturbation peut provoquer le passage au régime cinétique.',
 'Une caisse de 3 kg avec fₛ=0,45 reste au repos sous 10 N, mais glisse sous 18 N. Pour f_d=0,315, l’accélération vaut environ 2,91 m/s².'),
lesson('coulomb_horizontal','Freinage et inversion : résoudre un changement de régime','Spé · MP',
 'En glissement, le frottement extrait de l’énergie mécanique et la transforme en chaleur. Le signe de la force dépend de la vitesse relative des deux surfaces, et non d’un axe arbitrairement choisi.',
 'Avant l’arrêt : a₁=(F−f_dmg)/m ; t_a=−v₀/a₁ si a₁<0 ; après : adhérence si |F|≤fₛmg, sinon a₂=(F+f_dmg)/m pour une reprise vers la gauche.',
 'Partir avec v₀>0 impose T=−f_dmg, quelle que soit la direction de F. Avec a₁<0, v=v₀+a₁t et x=v₀t+a₁t²/2 jusqu’à t_a. À cet instant, tester Coulomb statique : soit x reste égal à x_a, soit la caisse repart avec x=x_a+a₂(t−t_a)²/2 et v=a₂(t−t_a). Les deux raccordements sont continus. Le bilan W_F=ΔE_c+Q garde l’énergie initiale, et Q=f_dmg×distance parcourue. Après inversion, cette distance est x_a+|x−x_a|, et non |x|.',
 'Pour m=3 kg, fₛ=0,45 et f_d=0,315, une force F=−6 N freine puis maintient la caisse immobile ; F=−18 N freine puis relance vers la gauche. La simulation traite explicitement ce changement de mode de contact, attendu dans le programme MP.'),
lesson('plan_incline','Pourquoi une boule descend-elle plus vite qu’un cerceau ?','Sup → Spé',
 'Les deux solides gagnent la même énergie gravitationnelle par unité de masse. Mais la répartition entre translation et rotation dépend du nombre sans dimension k=I_G/(mR²).',
 'a=g sinα/(1+k) ; T=kmg sinα/(1+k) ; adhérence : [k/(1+k)]tanα≤fₛ.',
 'Projeter le PFD sur la pente : ma=mg sinα−T. Prendre le moment en G : I_Gω̇=TR. Imposer la condition de roulement a=Rω̇ seulement si la force requise respecte Coulomb. Pour k=2/5, 1/2 et 1, les accélérations sont respectivement (5/7), (2/3) et (1/2)g sinα.',
 'Le roulement sans glissement n’exige pas T=fₛN : il exige T≤fₛN. Augmenter fₛ au-delà du seuil ne change donc pas l’accélération d’un solide déjà en roulement idéal.'),
lesson('plan_incline','Le frottement statique peut modifier la translation sans dissiper','Spé',
 'Le travail de la force tangentielle sur le centre de masse n’est pas à lui seul la puissance de cette force pour tout le solide. Il faut additionner translation et rotation.',
 'P_T=−Tv_G+TRω=−T(v_G−Rω) ; roulement : v_G=Rω ⇒ P_T=0.',
 'Le frottement ralentit la translation mais accélère la rotation. Sans glissement, les deux puissances se compensent. En glissement, T=f_dN s’oppose à la vitesse du point de contact : la puissance totale est négative. Pour un solide initialement au repos dont le contact glisse vers le bas, a=g(sinα−f_dcosα) et ω̇=f_dgcosα/(kR). Vérifier que a−Rω̇ reste positif justifie le sens choisi pour T.',
 'Une caisse peut rester immobile sur un plan où une boule roule. Les conditions tanα≤fₛ et [k/(1+k)]tanα≤fₛ répondent à deux problèmes différents.'),
lesson('gyroscope','Le couple du poids produit une précession','Spé',
 'Une toupie tourne rapidement autour de son axe n. Son moment cinétique est alors principalement porté par cet axe. Le couple du poids est perpendiculaire à n : il dévie le moment cinétique plutôt qu’il ne le réduit.',
 'L≈I₃ω₃n ; M_O=−mgℓn×e_z ; Ω_p≈mgℓ/(I₃ω₃).',
 'Supposer une précession lente autour de la verticale et une inclinaison constante. Alors dL/dt≈Ω_p e_z×L. Identifier cette expression au couple du poids donne la fréquence angulaire approchée. La vitesse propre ω₃ doit être en rad/s : 18 tr/s correspond à 36π rad/s. Le rapport Ω_p/ω₃ teste une séparation des échelles, mais les conditions initiales peuvent toujours exciter une nutation.',
 'Doubler la vitesse propre divise la précession lente par deux. Ce mécanisme relie le TP de gyroscope aux précessions d’axes en astrophysique et, par analogie du moment cinétique, à la précession de Larmor.'),
lesson('gyroscope','Dépasser l’approximation : intégrer un solide de révolution','Spé → Au-delà',
 'Les équations vectorielles évitent les difficultés des angles d’Euler aux pôles. I₁ désigne l’inertie transversale autour de O et I₃ l’inertie axiale.',
 's=L·n=I₃ω₃ ; ṅ=(L×n)/I₁ ; L̇=−mgℓn×e_z ; E=|L−sn|²/(2I₁)+s²/(2I₃)+mgℓn_z.',
 'La composante axiale s est constante parce que le couple du poids n’a pas de composante suivant n. Décomposer L en sn et sa composante perpendiculaire. La cinématique ṅ=Ω×n donne l’équation de n. L_z et l’énergie totale sont aussi conservés. La nutation correspond à une variation périodique de l’inclinaison, visible quand le lancement ne place pas exactement la toupie sur une précession régulière.',
 'Une précession régulière exacte doit vérifier I₁cosθ Ω_p²−sΩ_p+mgℓ=0. L’approximation lente est la petite racine lorsque s²≫4I₁mgℓcosθ ; il peut exister une seconde branche rapide.'),
]

EXERCISES=[
exercise('inertie_huygens','Quatre masses et trois inerties principales','Sup → Spé','Quatre masses identiques m sont aux points (±a,0,0) et (0,±b,0). Donner I_G et les inerties principales.','Par symétrie, les produits d’inertie sont nuls. I_G=diag(2mb²,2ma²,2m(a²+b²)). Les axes x,y,z sont principaux. Si a>b, l’axe x minimise l’inertie. La masse totale est 4m.'),
exercise('inertie_huygens','Un axe décalé qui ne change pas d’inertie','Spé','On déplace le point d’attache de d parallèlement à l’axe de rotation u. Pourquoi l’inertie autour de cet axe ne change-t-elle pas ?','Huygens donne ΔI=M|d×u|². Si d est parallèle à u, ΔI=0 : les deux points définissent le même axe géométrique, et non deux axes distincts.'),
exercise('inertie_huygens','Inertie d’un parallélépipède anisotrope','Spé','Un parallélépipède homogène a pour côtés a,b,c et masse M. Calculer son inertie autour de u=(1,1,1)/√3 passant par G.','Les inerties principales valent M(b²+c²)/12, M(a²+c²)/12 et M(a²+b²)/12. Donc I(u)=M(a²+b²+c²)/18. Le vecteur u n’est pas en général un axe principal : I_Gu peut ne pas être parallèle à u.'),
exercise('konig','Translation et rotation d’un cylindre','Sup','Un cylindre plein de masse 2 kg et rayon 0,2 m roule à 3 m/s. Calculer les deux parts d’énergie.','ω=v/R=15 rad/s et I_G=mR²/2=0,04 kg·m². E_translation=mv²/2=9 J ; E_rotation=I_Gω²/2=4,5 J ; E_totale=13,5 J.'),
exercise('konig','Annuler le moment cinétique sans annuler l’énergie','Spé','Un solide se déplace avec un moment orbital opposé à son moment propre. Peut-il avoir L_O=0 et E_c>0 ?','Oui : L_O=L_orbital+L_G s’annule si les deux vecteurs sont opposés et de même norme. L’énergie vaut une somme de termes positifs ; elle ne s’annule que si toutes les vitesses sont nulles. Un bilan de moments cinétiques ne remplace pas un bilan d’énergie.'),
exercise('konig','Pourquoi choisir le centre de masse ?','Spé','Dans la décomposition des vitesses par rapport à un point A quelconque, quel terme empêche de retrouver directement König ?','Le terme croisé vaut v_A·Σmᵢvᵢ/A. Il n’est pas nul en général. Il disparaît pour le référentiel barycentrique parce que ΣmᵢGMᵢ=0 à tout instant. Si A est fixe mais distinct de G, les autres termes doivent être conservés.'),
exercise('barre_bascule','Vitesse au passage à l’horizontale','Sup','Une barre de longueur 2L=1,6 m suit la trajectoire limite issue de la verticale. Déterminer θ̇ à θ=90°.','I_O=4ML²/3 et ½I_Oθ̇²=MgL donnent θ̇=√(3g/(2L))≈4,289 rad/s. La vitesse de G vaut Lθ̇≈3,431 m/s. La masse se simplifie.'),
exercise('barre_bascule','Une réaction normale peut-elle être négative ?','Spé','La composante radiale de la réaction du pivot s’annule pour cosθ=3/5. La barre perd-elle alors sa liaison ?','Non. Un pivot idéal peut tirer ou pousser ; il impose la position de O. Rᵣ change simplement de signe à θ≈53,13°. Une condition de perte de contact N=0 s’applique à une liaison unilatérale, pas à ce pivot.'),
exercise('barre_bascule','Le temps dépend logarithmiquement de la perturbation','Spé','Comparer les temps de θ₁ à θ₂ quand θ₁ et θ₁/10 sont petits.','La formule exacte est Δt=2√(L/(3g)) ln[tan(θ₂/4)/tan(θ₁/4)]. Pour θ₁≪1, tan(θ₁/4)≈θ₁/4. Diviser θ₁ par 10 ajoute donc environ 2√(L/(3g)) ln 10 au temps ; on ne multiplie pas ce temps par dix.'),
exercise('barre_rotule','Une expression sphérique doit conserver la longueur','Sup → Spé','Avec θ colatitude et φ azimut, écrire OG et vérifier sa norme.','OG=L(sinθcosφ,sinθsinφ,cosθ). Sa norme au carré vaut L²[sin²θ(cos²φ+sin²φ)+cos²θ]=L². Changer de convention exige de modifier toutes les composantes et les dérivées.'),
exercise('barre_rotule','Le mouvement reste-t-il plan ?','Spé','Si la barre est initialement dans le plan xz et possède une vitesse dans ce même plan, montrer qu’elle y reste.','Alors n_y=ṅ_y=0. L’équation n̈=−λ(e_z−n_zn)−|ṅ|²n donne n̈_y=(λn_z−|ṅ|²)n_y=0. L’unicité de la solution maintient n_y=0. Une vitesse initiale d’azimut non nulle rompt cette condition.'),
exercise('barre_rotule','Rotation conique d’une barre','Spé','Pour une barre de demi-longueur L, chercher une solution θ constante, φ̇ constante non nulle.','L’équation de θ donne sinθ[φ̇²cosθ+3g/(4L)]=0. Pour θ non vertical, φ̇²=−3g/(4Lcosθ), donc cosθ<0. Avec L=0,7 m et θ=120°, φ̇≈4,585 rad/s.'),
exercise('cylindre_bord','Retrouver N par la projection normale','Spé','Pendant l’adhérence au bord, partir de l’énergie et calculer la réaction N.','Énergie : θ̇²=(4g/(3R))(1−cosθ). La projection radiale du PFD donne N−mgcosθ=−mRθ̇². Remplacer conduit à N=(mg/3)(7cosθ−4). L’expression n’est valable que tant que la cinématique d’adhérence subsiste.'),
exercise('cylindre_bord','Le glissement précède toujours le seuil N=0','Spé','Montrer que tout coefficient fₛ fini entraîne un seuil de glissement avant arccos(4/7).','Sur cet intervalle, T/N=sinθ/(7cosθ−4). Il vaut 0 en θ=0 et tend vers +∞ à droite. Sa dérivée vaut (7−4cosθ)/(7cosθ−4)²>0. Une unique égalité T/N=fₛ existe donc avant N=0 pour fₛ>0.'),
exercise('cylindre_bord','Petit coefficient de frottement','Spé','Obtenir une approximation de l’angle de début de glissement quand fₛ≪1.','L’équation sinθ=fₛ(7cosθ−4) donne θ≈3fₛ en radians au premier ordre. Pour fₛ=0,05, on trouve environ 0,15 rad, soit 8,6°. Une correction quadratique en θ diminue légèrement cette estimation.'),
exercise('coulomb_horizontal','Le frottement statique se règle sur la sollicitation','Sup','Une caisse de 4 kg repose sur un sol avec fₛ=0,4. Quelle est la réaction tangentielle sous une traction de 8 N ?','Le seuil vaut fₛmg=15,696 N. Comme 8 N est inférieur, la caisse peut rester immobile : T=−8 N. Employer T=−fₛmg donnerait une accélération injustifiée.'),
exercise('coulomb_horizontal','Sous une force constante, dresser le bilan','Sup → Spé','m=2 kg, F=12 N, fₛ=0,5 et f_d=0,3. Calculer a puis la chaleur dissipée après 2 s.','F dépasse 9,81 N. T=−5,886 N et a=3,057 m/s². Après 2 s, x=6,114 m, Q=5,886×6,114≈35,99 J ; W_F=73,368 J et E_c≈37,38 J. Leur différence est Q.'),
exercise('coulomb_horizontal','Freinage, arrêt et reprise inverse','Spé · MP','Une caisse de masse 2 kg est lancée à 3 m/s. fₛ=0,5 et f_d=0,3. Comparer les forces constantes F=−8 N et F=−12 N : temps et position d’arrêt, régime suivant, distance parcourue après inversion.','Pendant le mouvement initial, T=−5,886 N. Sous −8 N, a₁=−6,943 m/s², t_a≈0,4321 s et x_a≈0,6481 m. Comme 8<9,81 N, la caisse adhère ensuite et T devient +8 N. Sous −12 N, a₁=−8,943 m/s², t_a≈0,3355 s et x_a≈0,5032 m. Puis 12>9,81 N entraîne une reprise inverse : T=+5,886 N et a₂=−3,057 m/s². Pour t>t_a, x=x_a−(3,057/2)(t−t_a)², v=−3,057(t−t_a) et la distance parcourue vaut x_a+|x−x_a|. Multiplier cette distance par 5,886 N donne Q ; vérifier Fx=½m(v²−3²)+Q.'),
exercise('plan_incline','Une caisse ne glisse pas : ne saturer pas Coulomb','Sup','Sur un plan d’angle 20°, m=3 kg et fₛ=0,5. Calculer N et T.','tan20°≈0,364<0,5 : l’adhérence est possible. N=mgcos20°≈27,66 N et T=mgsin20°≈10,07 N. Le plafond fₛN≈13,83 N est supérieur à la réaction nécessaire.'),
exercise('plan_incline','Comparer les temps de descente','Spé','Une boule et un cerceau descendent une même distance d en roulement sans glissement. Quel est le rapport de leurs temps ?','a_boule=(5/7)g sinα et a_cerceau=(1/2)g sinα. Avec d=at²/2, t_cerceau/t_boule=√(a_boule/a_cerceau)=√(10/7)≈1,195. Vérifier auparavant les conditions de roulement pour chacun.'),
exercise('plan_incline','Travail du frottement et absence de dissipation','Spé','Pour un cylindre roulant sans glissement, le travail −Tx_G sur G est négatif. Pourquoi n’y a-t-il pas de perte d’énergie mécanique ?','Le couple en G fournit un travail +TRΔrotation. Or x_G=RΔrotation, donc la somme vaut zéro. La puissance d’une force sur le solide se calcule avec la vitesse du point où elle s’applique ; ce point est instantanément immobile en roulement sur un plan fixe.'),
exercise('gyroscope','Ne pas confondre tours par seconde et radians par seconde','Sup → Spé','Une toupie a m=1 kg, ℓ=0,15 m, I₃=0,0018 kg·m² et une rotation propre de 18 tr/s. Estimer sa précession lente.','ω₃=2π×18≈113,097 rad/s. Ω_p=mgℓ/(I₃ω₃)≈7,228 rad/s, soit environ 1,150 tr/s. Le rapport Ω_p/ω₃≈0,064 renseigne sur la séparation des vitesses, sans garantir une absence de nutation.'),
exercise('gyroscope','La rotation propre constante ne rend pas L constant','Spé','Expliquer comment s=L·n peut être constant alors que L change de direction.','Le couple est perpendiculaire à n et la cinématique assure L·ṅ=0. Donc d(L·n)/dt=L̇·n+L·ṅ=0. En revanche L̇=M_O est généralement non nul. La constance de la composante axiale n’implique pas celle du vecteur entier ni de sa norme.'),
exercise('gyroscope','Précession régulière : les deux branches','Au-delà','Une toupie conserve θ et précesse à Ω_p. Retrouver l’équation quadratique qui remplace l’approximation lente.','Avec ṅ=Ω_p e_z×n, L=I₁Ω_p(e_z−cosθ n)+sn. Dériver L et identifier au couple mgℓ e_z×n : Ω_p(s−I₁Ω_pcosθ)=mgℓ, soit I₁cosθ Ω_p²−sΩ_p+mgℓ=0. Pour une rotation rapide, la petite racine approche mgℓ/s. La réalité des racines dépend du discriminant.'),
]

GUIDE_DATA={
'inertie_huygens':('Comprendre pourquoi un même objet est plus facile à faire tourner autour de certaines directions que d’autres.','Six masses mᵢ et leurs positions ; G, centre de masse ; O, point où passe l’axe ; u, sa direction unitaire.','Calcul direct d’une distance à un axe ; théorème de Huygens ; diagonalisation d’une matrice symétrique.','Mettre dx=dy=0 et comparer les deux courbes.','Décaler O puis orienter l’axe parallèlement à OG.','Allonger l’assemblage et identifier la plus petite inertie principale.','Les inerties augmentent d’une quantité M|OG×u|² ; le déplacement parallèle à l’axe ne change rien.','Moments d’inertie autour d’axes simples ; calculs de distances.','Forme quadratique, Huygens, axes principaux et théorème spectral.','Inertie tensorielle d’un satellite et dynamique tridimensionnelle.'),
'konig':('Décomposer un mouvement réel en translation de G et rotation autour de G, puis vérifier deux identités indépendantes.','M, masse totale ; v_G, vitesse de G ; Ω, vitesse angulaire ; rᵢ=GMᵢ ; L_O, moment cinétique en O.','Développer un carré et un produit vectoriel ; exploiter Σmᵢrᵢ=0.','Choisir la translation seule et lire l’énergie de rotation.','Choisir la rotation seule puis observer les six vitesses.','Combiner les mouvements et déplacer la position initiale de G.','L’énergie est une somme positive ; le moment cinétique est une somme vectorielle qui dépend de O.','Énergie cinétique d’un système ; définition du centre de masse.','Les deux théorèmes de König et cinématique d’un solide.','Référentiel barycentrique accéléré : identité cinématique et théorème dynamique sont deux questions différentes.'),
'barre_bascule':('Faire d’un problème de basculement un enchaînement de trois outils : Huygens, énergie, puis PFD.','2L, longueur totale ; θ, angle depuis la verticale ascendante ; Rᵣ et Rθ, composantes de la force du pivot.','Conservation d’énergie ; quadrature exacte ; projections radiale et tangentielle.','Comparer les temps d’une barre courte et d’une barre longue.','Abaisser le premier angle à 0,2° et observer l’augmentation du temps.','Lire le changement de signe de Rᵣ puis contrôler l’énergie totale.','La durée dépend de √L et diverge près de la verticale ; la réaction peut tirer parce que la liaison est un pivot.','Bilan d’énergie et accélération d’un mouvement circulaire.','Moment cinétique, Huygens, équation non linéaire et durée intégrée.','Séparatrice d’un système conservatif : trajectoire limite issue d’un équilibre instable.'),
'barre_rotule':('Voir ce qui change lorsqu’une barre ne reste plus dans un plan et contrôler le calcul par deux invariants.','n, axe unitaire de la barre ; θ, colatitude ; φ, azimut ; L_z, composante verticale du moment cinétique.','Dériver une position sphérique ; théorème du moment cinétique ; potentiel effectif.','Lancer le pendule plan et regarder la trajectoire.','Donner une vitesse d’azimut et comparer la trajectoire spatiale.','Tester la rotation presque conique puis lire les écarts d’énergie et de L_z.','L’énergie et L_z restent constants à l’erreur numérique près ; l’azimut initial peut empêcher le passage par une verticale.','Vecteurs position, vitesse et accélération ; bilan d’énergie.','Rotation spatiale, moment cinétique vectoriel et invariants par symétrie.','Réduction lagrangienne, potentiel effectif et stabilité des rotations coniques.'),
'cylindre_bord':('Apprendre à arrêter un calcul au premier changement de régime, plutôt que prolonger une formule hors de ses hypothèses.','R, rayon ; θ, basculement du centre ; N et T, réactions ; fₛ, coefficient maximal d’adhérence.','Huygens ; énergie ; PFD ; inégalité de Coulomb et détection d’un événement.','Choisir un faible frottement et repérer l’intersection T=fₛN.','Augmenter fₛ et comparer ce seuil au seuil N=0.','Observer que l’animation s’arrête au glissement et lire les hypothèses.','Pour tout fₛ fini, le glissement précède le seuil de perte de contact calculé avec l’adhérence hypothétique.','Forces de contact et mouvement circulaire.','Modèle par régimes, roulement et tests de validité.','Après le seuil : reconstruire un modèle de contact avec glissement, sans reprendre les anciennes réactions.'),
'coulomb_horizontal':('Choisir la bonne branche de Coulomb puis suivre un arrêt et, éventuellement, une inversion du mouvement.','F, force algébrique ; N=mg ; v₀, vitesse initiale vers la droite ; fₛ et f_d, coefficients ; Q, énergie dissipée.','PFD ; signe de la vitesse relative ; solution par morceaux ; continuité de x et v ; bilan énergétique avec distance parcourue.','En mode repos, appliquer 10 N puis 18 N et identifier le seuil.','Choisir « Freiner puis rester au repos » : lire le temps d’arrêt et le changement de frottement.','Choisir « Freiner puis repartir à gauche » : vérifier le passage continu de v par zéro et le bilan d’énergie.','Avant l’arrêt, le frottement s’oppose à v₀ ; ensuite il équilibre F ou change de sens si la caisse repart. Q reste positif même lorsque le déplacement net diminue.','MPSI : PFD, équilibre et travail d’une force constante.','MP : frottements solides en translation et simulation avec changement du mode de glissement.','Traction variable, événements multiples et modèle de contact avec adhérence/glissement.'),
'plan_incline':('Comparer caisse et objets roulants sans imposer le roulement avant d’avoir vérifié sa possibilité.','α, angle de pente ; k=I_G/(mR²) ; v_G, vitesse du centre ; Rω, vitesse liée à la rotation ; v_contact=v_G−Rω.','PFD et moment en G ; condition de roulement ; inégalité de Coulomb ; puissance d’une force sur un solide.','Comparer cylindre, boule et cerceau avec assez de frottement.','Diminuer fₛ pour provoquer le glissement et comparer v_G à Rω.','Observer la dissipation : nulle en roulement idéal, positive en glissement.','Le frottement statique répartit l’énergie entre translation et rotation sans en dissiper ; le frottement dynamique dissipe par glissement.','Projection des forces sur un plan incliné.','Translation-rotation couplées ; contact ; puissance et bilan mécanique.','Résistance au roulement, déformation de contact et changements de régime.'),
'gyroscope':('Comprendre la précession par un bilan de moment cinétique et voir les limites de l’approximation de rotation rapide.','n, axe de la toupie ; I₁ et I₃, inerties transversale et axiale ; ω₃, rotation propre ; Ω_p, précession ; θ, inclinaison.','Théorème du moment cinétique vectoriel ; approximation par séparation des vitesses ; contrôle d’invariants.','Lancer rapidement en précession lente approchée et comparer les deux azimuts.','Lâcher sans précession initiale puis observer la nutation.','Réduire la vitesse propre et vérifier si l’approximation reste raisonnable.','La précession lente diminue quand la rotation propre augmente ; la nutation dépend aussi du lancement.','Couple du poids, produit vectoriel et sens d’une rotation.','Moment cinétique d’un solide, précession et approximation gyroscopique.','Équations de la toupie pesante, deux branches de précession régulière et applications astrophysiques.'),
}
GUIDES={}
HYPOTHESES={
'inertie_huygens':['Les six masses ponctuelles sont liées rigidement ; G est recalculé par barycentre.','Huygens compare deux axes parallèles, passant respectivement par G et O.'],
'konig':['La translation et la rotation sont prescrites ; les deux bilans sont des identités cinématiques.','Les axes du référentiel barycentrique restent parallèles à ceux du laboratoire.'],
'barre_bascule':['Barre homogène ; pivot fixe parfait ; poids uniforme.','Trajectoire limite d’énergie MgL : à θ₁, la vitesse n’est pas nulle. Une barre exactement dressée au repos reste immobile.'],
'barre_rotule':['Barre mince sans inertie axiale ; rotule fixe sans moment de réaction.','Le poids est uniforme ; l’énergie et L_z permettent de contrôler l’intégration numérique.'],
'cylindre_bord':['Cylindre plein homogène et contact ponctuel avec une arête fixe.','Le mouvement calculé s’arrête au début du glissement ; les réactions d’adhérence ne sont pas prolongées dans le nouveau régime.'],
'coulomb_horizontal':['Caisse sans rotation, sol horizontal et traction constante ; départ au repos ou à une vitesse v₀>0.','Le graphique force-frottement compare des essais indépendants au repos. Les courbes en temps résolvent l’état initial choisi, avec test de l’adhérence lors de l’arrêt ; 0≤f_d≤fₛ.'],
'plan_incline':['Plan immobile, départ sans vitesse et absence de résistance au roulement.','La condition de roulement est testée avant d’être imposée ; en glissement, le sens de la vitesse au contact est vérifié.'],
'gyroscope':['Solide de révolution sur pivot fixe, sans frottement ; inerties du modèle annoncées.','La précession lente est une approximation comparée au mouvement complet, avec E et L_z comme contrôles.'],
}
for lab,data in GUIDE_DATA.items():
    goal,objects,techniques,a,b,c,expected,sup,spe,beyond=data
    GUIDES[lab]=dict(purpose=goal,objects=[objects],hypotheses=HYPOTHESES[lab],techniques=[techniques],levels=dict(sup=sup,spe=spe,beyond=beyond),first_steps=[a,b,c],expected=expected)

# Repères annoncés pour MPSI/MP ; d’autres filières étudient davantage les solides.
PROGRAMME={
'inertie_huygens':('MPSI : moment d’inertie pour une rotation autour d’un axe fixe ; distance d’un point à un axe.','Prolongement pour MPSI/MP : Huygens tensoriel et axes principaux, reliés à l’algèbre linéaire.'),
'konig':('MPSI : mouvement de G, solide en translation ou en rotation autour d’un axe fixe.','Prolongement pour MPSI/MP : les deux identités de König pour une cinématique générale.'),
'barre_bascule':('MPSI : énergie, moment cinétique et rotation d’un solide autour d’un axe fixe.','Approfondissement : réaction du pivot et quadrature exacte d’un mouvement non linéaire.'),
'barre_rotule':('MPSI : vecteurs position et vitesse ; reprendre d’abord le cas plan de la barre.','Prolongement pour MPSI/MP : rotation spatiale, moment cinétique tensoriel et invariants.'),
'cylindre_bord':('MPSI : énergie et rotation autour d’un axe fixe pendant la phase d’adhérence.','MP : inégalité de Coulomb ; prolongement : contact d’un solide roulant au bord d’une table.'),
'plan_incline':('MPSI : projections du PFD et bilan d’énergie sur un plan incliné.','MP : frottement de la caisse en translation ; prolongement : roulement et couplage translation-rotation.'),
'gyroscope':('MPSI : couple, produit vectoriel et rotation autour d’un axe fixe comme préparation.','Prolongement pour MPSI/MP : gyroscope, précession, nutation et rotation spatiale.'),
}
for lab,(sup,spe) in PROGRAMME.items():
    GUIDES[lab]['levels'].update(sup=sup,spe=spe)
for item in LESSONS:
    if item['lab'] in {'inertie_huygens','konig','barre_rotule','gyroscope'}:
        item['level']='Spé · prolongement MPSI/MP'
    elif item['lab']=='plan_incline':
        item['level']='Spé · MP / prolongement roulement'
