'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const colors=['#2c7564','#c76c4e','#7560a6','#bd9853','#b15268'];
let reactions=[],selectedReaction=null,labs=[],lessons=[],exercises=[],guides={},figures=[],token='',active=null,params={},result=null,sequence=0,paused=false,time=0,lastTime=0,timer=null;
const fmt=n=>typeof n==='boolean'?(n?'Oui':'Non'):typeof n==='number'?(n===0?'0':Math.abs(n)<.001||Math.abs(n)>=1e5?n.toExponential(3):Number(n.toPrecision(5)).toLocaleString('fr-FR')):String(n);
const element=(tag,className,text)=>{const e=document.createElement(tag);if(className)e.className=className;if(text!==undefined)e.textContent=text;return e;};
function view(name){['home','laboratory','course'].forEach(id=>$(id).hidden=id!==name);document.querySelector('.hero').hidden=name!=='home';}
function home(){active=null;result=null;selectedReaction=null;view('home');$('lab-picker').value='home';$('status').textContent=`${reactions.length} fiches de réactions du recueil · ${labs.length} laboratoires · ${lessons.length} leçons · ${exercises.length} exercices corrigés`;$('error').hidden=true;}
function renderGuide(id){const g=guides[id],box=$('lab-guide');box.replaceChildren();box.hidden=!g;if(!g)return;box.innerHTML=`<p class="eyebrow">POUR ABORDER LE TP</p><h3>But du TP et lien avec le cours</h3><p class="guide-purpose">${esc(g.purpose)}</p><p class="guide-expected"><b>À l’issue du TP :</b> ${esc(g.expected)}</p>${g.objects?.length?`<div class="guide-context"><section><b>Objets et unités</b><ul>${g.objects.map(t=>`<li>${esc(t)}</li>`).join('')}</ul></section><section><b>Hypothèses de l’expérience</b><ul>${(g.assumptions||[]).map(t=>`<li>${esc(t)}</li>`).join('')}</ul></section></div>`:''}<div class="guide-techniques"><b>Les techniques à réinvestir</b><ul>${g.techniques.map(t=>`<li>${esc(t)}</li>`).join('')}</ul></div><div class="guide-levels">${[['sup','Sup'],['spe','Spé'],['beyond','Au-delà']].map(([k,n])=>`<div class="guide-level"><h4>${n}</h4><p>${esc(g.levels[k])}</p></div>`).join('')}</div><p class="level-note">Sup et spé indiquent les acquis à réinvestir, selon votre filière. Les notions nouvelles et les limites des modèles sont introduites explicitement.</p><div class="guide-links"><b>Préparer et justifier avec le cours :</b></div><details><summary>Un premier parcours en trois gestes</summary><ol>${g.first_steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol></details>`;for(const number of g.lesson_numbers){const l=lessons[number-1];if(!l)continue;const b=element('button','',l.title);b.onclick=()=>showCourse(number-1);box.querySelector('.guide-links').append(b);}}
function controlOptions(c){return (c.options||[]).map(o=>typeof o==='string'?{value:o,label:o}:Array.isArray(o)?{value:o[0],label:o[1]}:o);}
function controlVisible(c){return !c.visible_if || Object.entries(c.visible_if).every(([key,values])=>(Array.isArray(values)?values:[values]).includes(params[key]));}
function renderControls(){const box=$('controls');box.replaceChildren();for(const c of active.controls){if(!controlVisible(c))continue;const d=element('div','control'),label=element('label','',c.label),out=element('output','',fmt(params[c.key])+(c.unit?' '+c.unit:''));label.htmlFor='control-'+c.key;d.append(label);let input;if(c.type==='select'||c.options){input=element('select');for(const o of controlOptions(c)){const option=element('option','',o.label);option.value=o.value;input.append(option);}input.value=params[c.key];}else{input=element('input');input.type='range';for(const k of ['min','max','step'])input[k]=c[k];input.value=params[c.key];label.append(out);}input.id='control-'+c.key;input.oninput=()=>{params[c.key]=input.tagName==='SELECT'?input.value:Number(input.value);out.textContent=fmt(params[c.key])+(c.unit?' '+c.unit:'');if(c.type==='select')renderControls();clearTimeout(timer);timer=setTimeout(update,140);};d.append(input);box.append(d);}const p=$('presets');p.replaceChildren();for(const preset of active.presets||[]){const b=element('button','',preset.label);b.onclick=()=>{params={...params,...preset.values};renderControls();update();};p.append(b);}}
function showLab(id,reaction=null){selectedReaction=reaction;active=labs.find(l=>l.id===id);if(!active)return;params={...Object.fromEntries(active.controls.map(c=>[c.key,c.value??c.default])),...(reaction?.params||{})};result=null;paused=false;$('pause').textContent='Pause';time=0;view('laboratory');$('lab-picker').value=id;$('lab-category').textContent=active.category+' · PRÉVOIR · TRANSFORMER · JUSTIFIER';$('lab-title').textContent=active.title;$('lab-intro').textContent=active.intro;renderReactionDossier(reaction);renderGuide(id);renderControls();const index=lessons.findIndex(l=>l.lab===id);$('theory').innerHTML=index<0?'':`<h3>${esc(lessons[index].title)}</h3>${lessons[index].html}`;for(const f of figures.filter(f=>(f.labs||[]).includes(id))){const figure=element('figure');const img=element('img');img.src='/illustrations/'+f.file;img.alt=f.title;img.loading='lazy';figure.append(img,element('figcaption','',f.caption||f.title));$('theory').append(figure);}$('lesson-button').onclick=()=>showCourse(Math.max(0,index));update();window.scrollTo({top:0,behavior:'instant'});}
async function update(){if(!active)return;const lab=active.id,n=++sequence;$('status').textContent='Calcul du modèle et de ses bilans…';$('error').hidden=true;try{const response=await fetch('/api/calculate',{method:'POST',headers:{'Content-Type':'application/json','X-CPGE-Token':token},body:JSON.stringify({lab,...params})});const r=await response.json();if(n!==sequence||active?.id!==lab)return;if(!response.ok)throw new Error(r.error);result=r;time=0;$('metrics').replaceChildren();for(const m of r.metrics){const d=element('div','metric');d.append(element('span','',m.label),element('b','',fmt(m.value)),element('small','',typeof m.value==='number'?(m.unit||''):''));$('metrics').append(d);}$('charts').replaceChildren();for(const c of r.charts||[])renderChart(c);$('steps').replaceChildren(...(r.steps||[]).map(s=>element('li','',s)));$('assumptions').replaceChildren(...(r.assumptions||[]).map(s=>element('li','',s)));setupScene(r);$('status').textContent='Analyse terminée · mécanismes, bilans et hypothèses disponibles';}catch(e){if(n===sequence){$('error').textContent=e.message;$('error').hidden=false;$('status').textContent='Ajuster les paramètres de l’expérience.';}}}
function renderChart(c){const card=element('section','chart');card.append(element('h3','',c.title));const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 560 320');svg.setAttribute('role','img');svg.setAttribute('aria-label',c.title+` ; ${c.x_label} ; ${c.y_label}`);const raw=(c.series||[]).flatMap(s=>s.x.map((x,i)=>[x,s.y[i]])).filter(([x,y])=>Number.isFinite(x)&&Number.isFinite(y)&&(c.x_scale!=='log'||x>0)&&(c.y_scale!=='log'||y>0));if(!raw.length){card.append(element('p','','Aucune valeur dans ce domaine.'));$('charts').append(card);return;}const tx=x=>c.x_scale==='log'?Math.log10(x):x,ty=y=>c.y_scale==='log'?Math.log10(y):y;const xs=raw.map(p=>tx(p[0])),ys=raw.map(p=>ty(p[1]));let xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys);if(xmin===xmax)xmax=xmin+1;if(ymin===ymax){ymin-=.5;ymax+=.5;}const py=(ymax-ymin)*.055;ymin-=py;ymax+=py;const X=x=>62+(c.x_reverse?xmax-tx(x):tx(x)-xmin)/(xmax-xmin)*471,Y=y=>263-(ty(y)-ymin)/(ymax-ymin)*228;let content='';for(let i=0;i<5;i++){const x=c.x_reverse?xmax-(xmax-xmin)*i/4:xmin+(xmax-xmin)*i/4,y=ymin+(ymax-ymin)*i/4,xx=62+471*i/4,yy=263-228*i/4;content+=`<path d="M${xx} 35V263M62 ${yy}H533" stroke="#e0e7df"/><text x="${xx}" y="283" text-anchor="middle" font-size="10" fill="#5a7177">${esc(fmt(c.x_scale==='log'?10**x:x))}</text><text x="55" y="${yy+3}" text-anchor="end" font-size="10" fill="#5a7177">${esc(fmt(c.y_scale==='log'?10**y:y))}</text>`;}content+='<path d="M62 35V263H533" fill="none" stroke="#819a99"/>';for(let i=0;i<c.series.length;i++){const s=c.series[i];let pen=false,d='';s.x.forEach((x,j)=>{const y=s.y[j];if(!Number.isFinite(x)||!Number.isFinite(y)||(c.x_scale==='log'&&x<=0)||(c.y_scale==='log'&&y<=0)){pen=false;return;}d+=(pen?'L':'M')+X(x).toFixed(2)+' '+Y(y).toFixed(2);pen=true;});content+=`<path d="${d}" stroke="${colors[i%colors.length]}" fill="none" stroke-width="2.3"/>`;}content+=`<text x="300" y="309" text-anchor="middle" font-size="11" fill="#173944">${esc(c.x_label)}${c.x_scale==='log'?' (log)':''}</text><text transform="translate(13 150) rotate(-90)" text-anchor="middle" font-size="11" fill="#173944">${esc(c.y_label)}${c.y_scale==='log'?' (log)':''}</text>`;svg.innerHTML=content;card.append(svg);const legend=element('div','legend');c.series.forEach((s,i)=>{const span=element('span');const dot=element('i');dot.style.background=colors[i%colors.length];span.append(dot,document.createTextNode(s.label));legend.append(span);});card.append(legend);$('charts').append(card);}
function recueilLab(id){return ['effets','e1','enolatealkyl','aminealkyl','anhydride','hydrolyseacyle','photochlore','grignardprep','nitrobenzene','dipolesnitro','e2stereo','epoxydes'].includes(id);}
function showCourse(index=lessons.findIndex(l=>l.lab==='effets')){
  active=null;result=null;view('course');$('lab-picker').value='course';
  const l=lessons[index];$('lesson').innerHTML=`<p class="eyebrow">${esc(l.level)}</p><h2>${esc(l.title)}</h2>${l.html}`;
  const b=element('button','','Explorer le laboratoire associé');b.onclick=()=>showLab(l.lab);$('lesson').append(b);$('lesson-list').replaceChildren();
  for(const primary of [true,false]){
    $('lesson-list').append(element('p','eyebrow',primary?'Réactions du recueil':'Cours complémentaires'));
    lessons.forEach((lesson,i)=>{if(recueilLab(lesson.lab)!==primary)return;const button=element('button',i===index?'active':'',lesson.title);button.onclick=()=>showCourse(i);$('lesson-list').append(button);});
  }
  $('status').textContent=`${lessons.length} leçons · ${exercises.length} exercices corrigés · hypothèses et niveaux explicités`;window.scrollTo({top:0,behavior:'instant'});
}
function renderCourse(){const box=$('exercises');box.replaceChildren();$('exercise-title').textContent=exercises.length+' exercices corrigés';[...exercises.filter(e=>recueilLab(e.lab)),...exercises.filter(e=>!recueilLab(e.lab))].forEach((e,i)=>{const d=element('section','exercise');d.innerHTML=`<p class="eyebrow">${esc(e.level||'SUP / SPÉ · MÉTHODE')}</p><h3>${esc(e.title||'Exercice '+(i+1))}</h3><div>${e.question}</div><details><summary>Ouvrir la correction guidée</summary><div class="answer">${e.answer}</div></details>`;if(e.lab){const b=element('button','secondary','Expérimenter dans le laboratoire');b.onclick=()=>showLab(e.lab);d.append(b);}box.append(d);});$('gallery').replaceChildren();for(const f of figures){const figure=element('figure');const a=element('a');a.href='/illustrations/'+f.file;a.target='_blank';a.rel='noopener';const img=element('img');img.src=a.href;img.alt=f.title;img.loading='lazy';a.append(img);figure.append(a,element('figcaption','',f.caption||f.title));$('gallery').append(figure);}}
async function boot(){try{const r=await fetch('/api/bootstrap');const b=await r.json();token=b.token;reactions=b.reactions||[];labs=b.labs;lessons=b.lessons;exercises=b.exercises;guides=b.lab_guides;figures=b.figures||[];$('sources').innerHTML=b.sources.map(s=>'<p>'+s+'</p>').join('');const picker=$('lab-picker');for(const category of [...new Set(labs.map(l=>l.category))]){const group=element('optgroup');group.label=category;for(const l of labs.filter(l=>l.category===category)){const o=element('option','',l.title);o.value=l.id;group.append(o);}picker.append(group);}const opt=element('option','','Cours & exercices');opt.value='course';picker.append(opt);const cards=$('home-cards');for(const l of labs.filter(l=>['formule','stereo','conformeres','ir','rmn','ccm','extraction'].includes(l.id))){const b=element('button','lab-card');const canvas=element('canvas');canvas.setAttribute('aria-hidden','true');b.append(canvas);const copy=element('div','card-copy');copy.innerHTML=`<p class="eyebrow">${esc(l.category)}</p><h3>${esc(l.title)}</h3><p>${esc(l.intro)}</p><b>Ouvrir l’expérience ↗</b>`;b.append(copy);b.dataset.lab=l.id;b.onclick=()=>showLab(l.id);cards.append(b);}renderCourse();setupReactionAtlas();home();for(const card of cards.children)thumbnail(card.querySelector('canvas'),card.dataset.lab);$('home-tab').onclick=home;$('course-tab').onclick=()=>showCourse();picker.onchange=()=>picker.value==='home'?home():picker.value==='course'?showCourse():showLab(picker.value);document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>showLab(b.dataset.route));$('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?'Reprendre':'Pause';};$('export').onclick=()=>{if(!result)return;const a=element('a');a.href='/api/export/'+result.export_id;a.download='chimie-organique-'+result.lab+'.json';document.body.append(a);a.click();a.remove();};}catch(e){$('error').textContent='Impossible de charger l’atelier : '+e.message;$('error').hidden=false;$('status').textContent='Recharger la page après le lancement du serveur.';}}
function frame(now){const dt=Math.min(.05,(now-lastTime)/1000||.016);lastTime=now;if(!paused)time+=dt;drawScene(paused?0:dt);if(!$('home').hidden){const{ctx,w,h}=canvasContext($('hero-canvas'));ctx.clearRect(0,0,w,h);drawHero(ctx,w,h);}requestAnimationFrame(frame);}boot();requestAnimationFrame(frame);


function normalizeReactionText(text){return String(text).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();}
function setupReactionAtlas(){
  const family=$('reaction-family'),section=$('reaction-section');
  for(const value of [...new Set(reactions.map(r=>r.family))]){const o=element('option','',value);o.value=value;family.append(o);}
  for(const value of [...new Set(reactions.map(r=>r.rubric))]){const o=element('option','',value);o.value=value;section.append(o);}
  family.onchange=renderReactionAtlas;section.onchange=renderReactionAtlas;$('reaction-search').oninput=renderReactionAtlas;
  $('reset-reactions').onclick=()=>{family.value='all';section.value='all';$('reaction-search').value='';renderReactionAtlas();};
  renderReactionAtlas();
}
function renderReactionAtlas(){
  const query=normalizeReactionText($('reaction-search').value).trim(),family=$('reaction-family').value,section=$('reaction-section').value;
  const matches=reactions.filter(r=>(family==='all'||r.family===family)&&(section==='all'||r.rubric===section)&&(!query||normalizeReactionText([r.title,r.substrate,r.reagents,r.product,...(r.selectivity||[]),...(r.characterization||[])].join(' ')).includes(query)));
  $('reaction-count').textContent=`${matches.length} réaction${matches.length>1?'s':''} affichée${matches.length>1?'s':''} sur ${reactions.length} · pages 524–528 et 531–534`;
  $('reaction-empty').hidden=matches.length>0;const box=$('reaction-cards');box.replaceChildren();
  for(const r of matches){const card=element('article','reaction-card');card.dataset.reaction=r.id;
    card.innerHTML=`<div class="reaction-card-top"><span class="family-badge">${esc(r.family)}</span><span>p. ${esc(r.page)} · ${esc(r.level)}</span></div><h3>${esc(r.title)}</h3><div class="reaction-equation"><span>${esc(r.substrate)}</span><span class="reaction-arrow">→</span><span>${esc(r.product)}</span></div><p class="reaction-reagents">${esc(r.reagents)}</p><p class="reaction-rule">${esc((r.selectivity||r.changes||[])[0]||'Suivre les liaisons et les électrons.')}</p>`;
    const button=element('button','','Prévoir le produit et explorer');button.onclick=()=>showLab(r.lab,r);card.append(button);box.append(card);
  }
}
function renderReactionDossier(r){
  const box=$('reaction-dossier');box.replaceChildren();box.hidden=!r;if(!r)return;
  box.innerHTML=`<div class="dossier-heading"><div><p class="eyebrow">${esc(r.rubric)} · PAGE ${esc(r.page)}</p><h3>${esc(r.title)}</h3></div><span class="family-badge">${esc(r.family)}</span></div><div class="dossier-bilan"><span>${esc(r.substrate)}</span><span class="dossier-arrow"><b>${esc(r.reagents)}</b><i>→</i></span><span>${esc(r.product)}</span></div><div class="dossier-columns">${[['Liaisons et type',r.changes],['Règles et sélectivité',r.selectivity],['Caractériser le produit',r.characterization]].map(([title,lines])=>`<section><h4>${esc(title)}</h4><ul>${(lines||[]).map(t=>`<li>${esc(t)}</li>`).join('')}</ul></section>`).join('')}</div><details><summary>Lire le mécanisme en étapes</summary><ol>${(r.mechanism||[]).map(t=>`<li>${esc(t)}</li>`).join('')}</ol></details><div class="reaction-question"><b>Avant d’afficher la réponse</b><p>${esc(r.question)}</p><details><summary>Comparer avec la réponse argumentée</summary><p>${esc(r.answer)}</p></details></div>${r.model_note?`<p class="dossier-model-note"><b>Domaine du modèle :</b> ${esc(r.model_note)}</p>`:''}<p class="dossier-model-note">Le préréglage correspond à cette fiche. Une modification des commandes explore un autre cas : confronter le nouveau résultat au bilan ci-dessus.</p>`;
}
