"""Atlas original des transformations des pages 524-528 et 531-534 du recueil.

La page est le numéro imprimé. Une fiche décrit une transformation ; son bouton
ouvre un scénario effectivement disponible, jamais un rendement prédit sans données.
"""


def reaction(id, title, page, family, substrate, reagents, product, changes,
             selectivity, characterization, mechanism, lab, params, question,
             answer, level="Sup → PC", model_note=""):
    rubric = ("Formules, propriétés et règles" if page == 524 else
              "Types de réactions" if page == 525 else
              "Autres exemples / organomagnésiens" if page == 526 else
              "Exemples (suite)" if page in (527, 528) else
              "Alcènes et alcynes : applications" if page in (531, 533) else
              "Autour du nitrobenzène")
    return dict(id=id, title=title, page=page, rubric=rubric, family=family,
                substrate=substrate, reagents=reagents, product=product,
                changes=changes, selectivity=selectivity,
                characterization=characterization, mechanism=mechanism,
                lab=lab, params=params, question=question, answer=answer,
                level=level, model_note=model_note)


R = reaction
REACTIONS = [
    R("inductif", "Effet inductif : lire la polarisation avant l’attaque", 524, "Règle",
      "C–X, carbonyle et liaison C–Mg", "Comparaison des électronégativités ; groupes −I / +I",
      "Sites C électrophile ou nucléophile identifiés ; aucune molécule créée par la comparaison",
      ["La liaison C–O est polarisée Cδ+–Oδ− ; C–Mg est polarisée Cδ−–Mgδ+.", "Une charge partielle δ n’est pas une charge formelle entière."],
      ["L’effet inductif s’atténue avec la distance ; il faut ajouter conjugaison et encombrement au raisonnement."],
      ["Classer les sites avant de tracer une flèche : le C de C=O reçoit un doublet, le C de RMgX en fournit un."],
      ["Identifier les liaisons polarisées.", "Placer δ+ / δ− sans inventer une espèce ionique libre.", "Proposer le site d’attaque en fonction du réactif."],
      "effets", {"system": "inductive", "group": "chloro", "stage": 1},
      "Pourquoi le carbone d’un organomagnésien attaque-t-il un carbonyle ?",
      "C–Mg présente une polarisation inverse de C–O : le carbone organomagnésien est riche en électrons, celui du carbonyle est pauvre. La formation C–C doit déplacer simultanément les électrons π de C=O vers O.",
      model_note="Le bouton illustre l’effet inductif dans une chaîne portant Cl ; C=O et C–Mg sont ensuite comparés dans carbonyle et grignard."),
    R("mesomerie", "Effets mésomères : doublets, charges et conjugaison", 524, "Règle",
      "Anisole, chlorobenzène et nitrobenzène", "Groupes +M / −M dans un système conjugué",
      "Contributeurs électroniques d’une même molécule ; sites aromatiques différenciés",
      ["Les noyaux et les liaisons σ restent en place.", "Les flèches déplacent des électrons π ou un doublet, en conservant la charge totale."],
      ["OCH₃ est donneur +M ; NO₂ est attracteur −M.", "Cl combine −I et +M : désactivation et orientation ortho/para peuvent coexister."],
      ["Comparer les complexes σ des attaques ortho, méta et para ; une formule mésomère n’est pas un produit isolé."],
      ["Repérer une suite d’orbitales p.", "Construire des contributeurs respectant l’octet.", "Comparer la stabilisation des intermédiaires accessibles."],
      "effets", {"system": "mesomeric", "group": "nitro", "stage": 2},
      "Pourquoi orientation et activation ne doivent-elles pas être confondues ?",
      "L’orientation compare des voies sur un même aromatique ; l’activation compare leur vitesse à celle du benzène. Un halogène retire par −I tout en stabilisant relativement certains complexes ortho/para par donation +M."),
    R("markovnikov", "Markovnikov : choisir le carbocation, puis vérifier ses migrations", 524, "Règle",
      "But-1-ène", "HBr sans peroxydes ; comparer ensuite hydroboration–oxydation",
      "2-bromobutane en voie ionique ; butan-1-ol dans la voie hydroboration–oxydation",
      ["Une liaison π disparaît ; une liaison C–H et une liaison C–Br ou C–O sont créées."],
      ["La protonation donne préférentiellement le carbocation le mieux stabilisé.", "Une migration 1,2 peut modifier le squelette avant capture."],
      ["Repérer sur quel carbone se trouve Br ou OH ; contrôler la conservation du squelette, puis rechercher un réarrangement."],
      ["Protonation de C=C.", "Carbocation éventuellement réarrangé.", "Capture nucléophile ; déprotonation si le nucléophile était H₂O."],
      "effets", {"system": "markovnikov", "group": "alkyl", "conditions": "ordinary", "stage": 2},
      "Peut-on appliquer Markovnikov à toutes les additions d’alcènes ?",
      "Non. Cette justification par le carbocation convient aux additions ioniques concernées. Hydroboration, bromonium et chaîne radicalaire HBr suivent d’autres chemins et doivent être traités avec leur propre mécanisme."),
    R("zaitsev", "Zaïtsev : tendance de stabilité après le filtre géométrique", 524, "Règle",
      "Pentan-2-ol ; comparer au 2-bromopentane pour le cas à base encombrée", "H⁺ / chauffage pour l’alcool ; tert-BuO⁻ pour le dérivé bromé du scénario alternatif",
      "Pent-2-ène et pent-1-ène possibles ; tendance plus substituée ou moins encombrée selon le chemin",
      ["Rupture de Cα–groupe partant et Cβ–H ; création Cα=Cβ.", "OH doit être activé en H₂O partante dans la voie acide ; Br est le départ dans la voie basique alternative."],
      ["Une petite base favorise souvent l’alcène le plus substitué parmi les voies accessibles.", "La géométrie anti, une base encombrée ou la conjugaison peuvent changer cette tendance."],
      ["Dessiner chaque connectivité, puis attribuer E/Z si chaque carbone vinylique possède deux substituants différents."],
      ["Lister les Hβ.", "Éliminer les voies sans géométrie réactive.", "Comparer seulement les voies restantes."],
      "effets", {"system": "zaitsev", "group": "alkyl", "conditions": "ordinary", "stage": 2},
      "Pourquoi Zaïtsev ne suffit-il pas dans une chaise cyclohexanique ?",
      "Une E2 standard exige Br axial et un Hβ axial opposé. Si le substituant occupe la place de ce H, le produit correspondant est inaccessible, même s’il serait le plus substitué."),
    R("ab_alcool", "Acido-basique : activer un alcool par protonation", 525, "AB",
      "Alcool ROH", "Acide HA dans un milieu compatible", "Oxonium ROH₂⁺ et A⁻",
      ["Une liaison O–H se crée ; la liaison H–A cède ses électrons à A."],
      ["Le site basique est un doublet de O ; l’oxonium peut ensuite libérer H₂O."],
      ["O possède trois liaisons et une charge +1 après protonation ; la somme des charges est conservée."],
      ["Doublet O → H.", "Liaison H–A → A.", "Vérification des charges et du caractère du groupe partant."],
      "e1", {"substrate": "secondary", "stage": 0},
      "Pourquoi ROH₂⁺ est-il plus utile que ROH pour une substitution acide ?",
      "Le départ de ROH₂⁺ fournit l’espèce neutre H₂O ; le départ direct de HO⁻ à partir d’un alcool non activé est beaucoup moins favorable."),
    R("ae_hbr", "AE : addition ionique de HBr sur un alcène", 525, "AE",
      "Propène", "HBr, absence de peroxydes", "2-bromopropane",
      ["C=C devient C–C ; H et Br s’ajoutent aux deux carbones."],
      ["Régiochimie Markovnikov dans ce cas sans migration.", "Une espèce carbocationique plane peut être capturée sur les deux faces."],
      ["Br est porté par le carbone secondaire ; l’insaturation a disparu."],
      ["Les électrons π captent H ; H–Br se rompt hétérolytiquement.", "Formation du carbocation secondaire.", "Br⁻ attaque ce centre."],
      "alcene", {"substrate": "propene", "reagent": "hbr", "stage": 2},
      "Quel intermédiaire commande le produit ?",
      "Le carbocation secondaire issu de la protonation est plus stabilisé que le primaire. Br⁻ capture ensuite le carbone qui porte la charge : la règle se déduit de ce chemin."),
    R("an_carbonyle", "AN : hydrure sur un carbonyle", 525, "AN",
      "Éthanal", "NaBH₄ puis milieu protonant", "Éthanol",
      ["Une liaison C–H se forme ; C=O devient C–O, puis O reçoit H."],
      ["L’attaque porte sur Cδ+ ; le carbonyle est plan avant l’addition."],
      ["Disparition de C=O et apparition d’OH ; vérifier le passage d’un C trigonal à un C tétraédrique."],
      ["Transfert d’hydrure vers C ; π(C=O) → O.", "Alcoolate tétraédrique.", "Protonation de O."],
      "carbonyle", {"reaction": "addition", "stage": 2},
      "Pourquoi le carbone ne doit-il pas garder C=O après l’attaque ?",
      "Le déplacement du doublet π vers O accompagne nécessairement la formation de la nouvelle liaison ; conserver C=O donnerait cinq liaisons au carbone et violerait l’octet."),
    R("ae_acyle", "Addition–élimination : substituer sur un carbone acyle", 525, "AE-addition-élimination",
      "Chlorure d’éthanoyle et amine", "Amine nucléophile ; base piège à HCl", "Amide et sel chlorure",
      ["C–N remplace C–Cl ; C=O s’ouvre provisoirement puis se reforme."],
      ["Le C acyle est trigonal au départ ; l’intermédiaire d’addition est tétraédrique.", "Cette substitution acyle ne se décrit pas par une SN2 sur un C tétraédrique."],
      ["La fonction finale reste carbonylée ; nouvelle liaison C(acyle)–N, disparition C–Cl."],
      ["Attaque de N ; π(C=O) → O.", "Retour du doublet de O et départ Cl⁻.", "Transfert du proton de N à une base."],
      "acylation", {"activation": "chloride", "amine": 2, "base": 0, "stage": 2},
      "Que devient le second équivalent d’amine ?",
      "Il sert de base et devient ammonium chlorure ; il ne fournit pas un second groupe lié au carbone acyle."),
    R("or_alcool", "OR : alcool secondaire ⇄ cétone", 525, "OR",
      "Alcool secondaire, par exemple propan-2-ol", "Oxydant adapté ; voie inverse NaBH₄", "Propanone ; voie inverse propan-2-ol",
      ["L’oxydation enlève deux H au bilan et crée C=O ; la réduction effectue le bilan inverse."],
      ["Un alcool tertiaire n’est pas oxydé en cétone sans rupture de squelette dans ce cadre."],
      ["Comparer OH, C=O, H porté par le carbone fonctionnel et degré d’oxydation de ce carbone."],
      ["Identifier la fonction et le carbone oxydé.", "Établir un bilan adapté au réactif réel.", "Vérifier la chimiosélectivité avant de proposer le produit."],
      "oxydoreduction", {"substrate": "alcohol2", "reagent": "aqueous", "stage": 1},
      "Un tertiaire peut-il donner une cétone par le même simple bilan ?",
      "Non : le carbone portant OH ne possède pas de H. La conversion en carbonyle sans modifier ses trois liaisons C–C dépasserait sa valence."),
    R("e1_type", "E1 : ionisation puis perte de Hβ", 525, "E1",
      "2-Méthylbutan-2-ol, alcool tertiaire", "H⁺ ; chauffage et milieu adaptés à une déshydratation", "2-Méthylbut-2-ène et/ou 2-méthylbut-1-ène ; H₂O au bilan",
      ["Protonation de OH ; départ C–OH₂ avant perte Cβ–H ; une liaison π se forme au dernier acte."],
      ["Un carbocation peut tourner et se réarranger ; l’E1 n’est pas intrinsèquement stéréospécifique.", "La répartition des produits demande des données cinétiques ou expérimentales."],
      ["OH disparaît au bilan de déshydratation ; identifier les Cβ et les alcènes effectivement possibles."],
      ["ROH + H⁺ → ROH₂⁺.", "Départ d’eau et carbocation.", "Une base prélève Hβ ; Cβ–H → Cα=Cβ ; H⁺ est régénéré au bilan."],
      "e1", {"substrate": "tertiary", "stage": 2},
      "La loi de vitesse indique-t-elle la proportion E/Z ?",
      "Non. Une loi apparente d’ionisation peut décrire la disparition du précurseur activé ; les étapes après ce départ répartissent le flux. Le ratio des alcènes n’est pas fourni par l’ordre un et le paramètre de branchement est une donnée choisie.",
      model_note="Le tableau général E1 est illustré ici par un alcool activé en milieu acide, avec H₂O comme départ."),
    R("e2_type", "E2 : trois déplacements électroniques concertés", 525, "E2",
      "2-bromobutane", "Base ; conformation anti accessible", "But-1-ène et/ou but-2-ène selon les voies retenues",
      ["B: → Hβ ; Cβ–H → Cβ=Cα ; Cα–Br → Br⁻, dans un même acte."],
      ["Disposition anti-périplanaire standard ; configuration et conformation du réactif gouvernent le produit."],
      ["La stéréochimie se prédit depuis une projection de Newman ; aucun carbocation intermédiaire."],
      ["Placer Hβ et Br anti.", "Tracer simultanément les trois flèches.", "Dessiner l’alcène puis appliquer CIP."],
      "elimination", {"system": "acyclic", "dihedral": 180},
      "Pourquoi une étape concertée peut-elle avoir trois flèches ?",
      "Le nombre de flèches compte les doublets déplacés, pas le nombre d’intermédiaires. Ici trois doublets se réorganisent simultanément à travers un seul état de transition."),
    R("sn1_type", "SN1 : carbocation plan et capture des faces", 525, "SN1",
      "Halogénoalcane ionisable", "Solvant ionisant ; eau comme nucléophile dans la solvolyse", "Alcool et X⁻ après transfert de proton",
      ["Rupture C–X puis formation C–O ; pas de liaison C–C nouvelle sauf migration."],
      ["Un carbocation libre en milieu achiral donne la limite racémique si un centre chiral se reforme.", "Une paire d’ions peut rendre les deux faces inégalement accessibles."],
      ["Distinguer racémisation limite, mélange de configurations et changement éventuel de constitution."],
      ["Ionisation.", "Capture par H₂O sur un carbone plan.", "Déprotonation de l’oxonium."],
      "sn1", {"substrate": "secondary", "bias": 0, "stage": 2},
      "Une SN1 impose-t-elle toujours exactement 50/50 ?",
      "C’est la limite d’un carbocation libre dont les faces sont équivalentes. La cage de solvant, la paire d’ions ou un environnement chiral peuvent modifier ce résultat ; il faut préciser le modèle."),
    R("sn2_type", "SN2 : attaque arrière et inversion de Walden", 525, "SN2",
      "Halogénoalcane secondaire représenté en 3D", "Nucléophile, groupe partant et solvant compatibles", "Produit substitué avec inversion géométrique",
      ["Formation C–Nu et rupture C–X simultanées."],
      ["Attaque arrière ; obstruction des centres tertiaires.", "L’inversion géométrique ne signifie R→S qu’après un nouveau classement CIP."],
      ["Conserver les trois autres substituants, suivre leur disposition puis attribuer la configuration du produit."],
      ["Nu attaque selon l’axe opposé à C–X.", "État de transition à deux liaisons partielles.", "Produit inversé et X⁻."],
      "sn2", {"substrate": "secondary", "stage": 2},
      "Pourquoi l’état de transition n’est-il pas un intermédiaire à isoler ?",
      "Il est le sommet du chemin réactionnel, avec liaisons partielles. Le mécanisme SN2 est concerté et n’a pas un minimum d’énergie carbocationique entre attaque et départ."),
    R("sea_nitration", "SEA : addition au cycle puis retour de l’aromaticité", 525, "SEA",
      "Benzène ou aromatique substitué", "HNO₃ / H₂SO₄ : génération de NO₂⁺", "Nitroaromatique",
      ["Une liaison Ar–H est remplacée par Ar–NO₂ ; l’aromaticité est provisoirement rompue."],
      ["Complexe σ de Wheland ; orientation par les groupes déjà présents.", "La réaromatisation favorise le départ de H⁺ plutôt qu’une simple addition stable."],
      ["Le produit est toujours aromatique ; substitution et addition ne possèdent pas le même bilan de H."],
      ["Former l’électrophile.", "Attaque des électrons π et complexe σ.", "Prélèvement de H et reconstitution du système aromatique."],
      "aromatique", {"substituent": "h", "reaction": "nitration", "stage": 2},
      "Quel acte restaure l’aromaticité ?",
      "La base reprend le proton du carbone qui a capturé E ; les électrons C–H reforment une liaison π dans le cycle."),
    R("sea_sulfonation", "SEA réversible : sulfonation aromatique", 525, "SEA",
      "Benzène", "SO₃ / H₂SO₄ ; conditions d’équilibre", "Acide benzènesulfonique ; désulfonation sous conditions aqueuses chaudes",
      ["Ar–H devient Ar–SO₃H ; le noyau conserve six carbones."],
      ["La réversibilité permet d’utiliser SO₃H comme groupe temporaire ; conditions et orientation doivent être précisées."],
      ["Fonction acide sulfonique fortement polaire ; substitution du cycle sans gain de carbone."],
      ["Activation de l’électrophile soufré.", "Formation du complexe σ.", "Déprotonation et équilibre dépendant du milieu."],
      "aromatique", {"substituent": "h", "reaction": "sulfonation", "stage": 2}, "Pourquoi cette réaction est-elle utile comme blocage temporaire ?",
      "SO₃H peut occuper une position du cycle puis être retiré par désulfonation adaptée. Il faut suivre son effet directeur tant qu’il est présent, et non supprimer arbitrairement ce groupe du schéma.",
      model_note="Les barrières du laboratoire sont choisies ; elles ne prédisent pas un rendement réel ni la position d’équilibre."),
    R("enolate_c", "C-alkylation : l’énolate est un nucléophile ambident", 526, "SN2 / énolate",
      "Énolate de propanone ou de malonate", "Halogénoalcane primaire ; énolate formé préalablement", "Carbonyle alkylé en α",
      ["Création Cα–C(alkyle) ; départ X⁻ ; conservation du carbonyle dans la C-alkylation."],
      ["Électrophile primaire favorable à SN2 ; tertiaire propice à élimination.", "C- et O-alkylation sont deux connectivités distinctes."],
      ["Repérer le nouveau nombre de carbones et la fonction C=O ; un éther d’énol n’est pas la même structure."],
      ["Déprotonation en α.", "Délocalisation de l’énolate.", "Attaque de Cα sur R–X et départ X⁻."],
      "enolatealkyl", {"donor": "acetone", "electrophile": "ethyl", "site": "C", "stage": 2},
      "Un électrophile tertiaire convient-il pour la même SN2 ?",
      "La SN2 est fortement entravée ; la basicité de l’énolate permet une élimination concurrente. On choisit un autre partenaire ou une autre stratégie pour obtenir la liaison C–C."),
    R("epoxy_peracide", "Époxydation : conserver la relation E/Z dans un petit cycle", 526, "Addition concertée",
      "(E)- ou (Z)-but-2-ène", "Peracide RCO₃H", "Époxyde et acide carboxylique RCO₂H",
      ["C=C devient C–C ; deux liaisons C–O se forment avec un seul O transféré."],
      ["Le transfert concerté conserve la relation relative des substituants.", "Dans un milieu achiral, les faces équivalentes peuvent donner une paire d’énantiomères."],
      ["Reconnaître le cycle C–C–O à trois atomes, sans groupe OH dans l’époxyde isolé."],
      ["Approche du peracide sur une face.", "Réorganisation concertée des liaisons.", "Séparation époxyde / acide."],
      "epoxydes", {"substrate": "butene_E", "mode": "peracid", "stage": 3},
      "Combien d’atomes O du peracide sont transférés à l’alcène ?",
      "Un seul atome O forme le pont époxyde. Le reste du réactif donne l’acide carboxylique ; le bilan doit compter séparément ces deux produits."),
    R("fischer", "Estérification de Fischer : condensation catalysée par H⁺", 526, "AE-addition-élimination",
      "Acide éthanoïque et éthanol", "Catalyse acide ; gestion de l’eau et de l’excès d’alcool", "Éthanoate d’éthyle et H₂O",
      ["Le groupe OH acyle est remplacé par OEt au bilan ; le carbonyle reste présent."],
      ["Réaction réversible ; catalyse accélère les deux sens sans changer K.", "Un excès ou retrait d’eau déplace l’équilibre."],
      ["Ester : C=O et C–O ; identifier O–CH₂–CH₃ sans confondre avec un simple mélange des réactifs."],
      ["Protonation du carbonyle.", "Addition de l’alcool et transferts de H⁺.", "Départ d’eau puis régénération de H⁺."],
      "esterification", {"mode": "ester", "first": 1, "second": 1, "water": 0, "K": 4},
      "Pourquoi chauffer avec un catalyseur ne suffit-il pas à garantir 100 % de conversion ?",
      "La vitesse et la position d’équilibre sont distinctes. Pour K=4 et stocks équimolaires sans eau ni ester initiaux, l’avancement relatif est 2/3 ; modifier les stocks ou enlever l’eau agit sur l’équilibre."),
    R("ester_chlorure", "Ester par chlorure d’acyle : départ activé", 526, "AE-addition-élimination",
      "Chlorure de benzoyle et éthanol", "Alcool ; base piège à HCl possible dans un protocole", "Benzoate d’éthyle et HCl dans le bilan du laboratoire",
      ["C(acyle)–Cl remplacée par C(acyle)–OEt ; conservation du squelette aromatique."],
      ["Chlorure d’acyle plus réactif qu’un acide non activé ; l’eau est un nucléophile concurrent."],
      ["Nouvelle fonction ester, disparition du chlorure d’acyle ; vérifier quel O provient de l’alcool."],
      ["Attaque du doublet O sur C=O.", "Intermédiaire tétraédrique.", "Départ Cl⁻ et déprotonation."],
      "anhydride", {"variant": "chloridealcohol", "acyl": "benzoyl", "equivalents": 1, "stage": 2}, "Quelle précaution chimique impose le chlorure d’acyle ?",
      "Il faut contrôler l’eau et prévoir une base pour neutraliser l’acide produit ; l’hydrolyse concurrente consomme le dérivé activé.",
      model_note="Une base externe peut neutraliser HCl dans un protocole ; elle n’est pas comptée comme réactif dans ce scénario. L’eau est une voie concurrente."),
    R("hydrolyse_acide", "Hydrolyse d’ester en milieu acide : inverser Fischer", 526, "AE-addition-élimination",
      "Éthanoate d’éthyle et eau", "H⁺ catalytique ; eau en excès", "Acide éthanoïque et éthanol",
      ["La liaison C(acyle)–OEt est remplacée par C(acyle)–OH."],
      ["Équilibre réversible ; après traitement, la forme protonée dépend du pH."],
      ["Retour de la fonction acide et de l’alcool ; bilan eau/ester/acide/alcool."],
      ["Activation du carbonyle par H⁺.", "Addition de H₂O.", "Transferts de protons et départ de l’alcool."],
      "hydrolyseacyle", {"derivative": "ester", "medium": "acid", "equivalents": 1, "stage": 3},
      "L’eau est-elle seulement un solvant ?",
      "Elle est aussi un réactif nucléophile du bilan. Son activité élevée peut favoriser l’hydrolyse ; une stœchiométrie écrite sans H₂O ne permettrait pas de suivre cette dépendance."),
    R("saponification", "Saponification : piéger l’acide en carboxylate", 526, "AE-addition-élimination / AB",
      "Éthanoate d’éthyle", "HO⁻ aqueux", "Éthanoate et éthanol ; acide après acidification séparée",
      ["Remplacement OEt par O⁻ au bilan ; consommation nette de HO⁻."],
      ["Le transfert de proton final stabilise le carboxylate et rend le bilan favorable.", "HO⁻ est réactif stœchiométrique dans ce bilan."],
      ["Distinguer RCO₂⁻ dans le milieu basique et RCO₂H après traitement acide."],
      ["Attaque HO⁻ sur C=O.", "Retour du carbonyle et départ de l’alcoolate.", "Transfert de proton donnant carboxylate et alcool."],
      "esterification", {"mode": "saponification", "first": 1, "second": 1},
      "Quel produit doit-on dessiner avant l’acidification ?",
      "Le carboxylate RCO₂⁻, associé au contre-ion. Dessiner directement l’acide neutre omet le transfert de proton responsable du piégeage basique."),
    R("amide_chlorure", "Amide : une amine attaque un chlorure d’acyle", 526, "AE-addition-élimination",
      "Chlorure d’éthanoyle et amine", "Deux équivalents d’amine, ou un équivalent plus une base", "Amide et ammonium chlorure",
      ["Création C(acyle)–N ; départ Cl⁻ ; perte d’un H de l’amine attaquante."],
      ["L’amide n’est pas un sel ammonium ; le second équivalent d’amine peut piéger HCl."],
      ["C=O adjacent à N ; caractère partiellement double C–N par conjugaison ; azote moins basique qu’une amine."],
      ["Addition nucléophile de N.", "Élimination du chlorure.", "Déprotonation par une autre base."],
      "acylation", {"activation": "chloride", "amine": 2, "base": 0, "stage": 3},
      "Pourquoi acide carboxylique + amine à froid n’est-il pas la même voie ?",
      "Le transfert acido-basique donne souvent un sel ammonium carboxylate. La formation efficace de l’amide demande activation ou conditions de condensation spécifiques."),
    R("anhydride_formation", "Anhydride d’acide : unir deux groupes acyle", 526, "AE-addition-élimination",
      "Chlorure d’éthanoyle et ion éthanoate", "Carboxylate nucléophile ; milieu maîtrisé", "Anhydride éthanoïque et Cl⁻",
      ["Création C(acyle)–O(carboxylate) ; départ Cl⁻ ; deux carbonyles conservés."],
      ["Deux groupes acyle différents pourraient donner un anhydride mixte ; le modèle ici est symétrique."],
      ["Identifier le motif R–CO–O–CO–R ; ne pas le confondre avec un peroxyde O–O."],
      ["Attaque de l’oxygène carboxylate sur le chlorure d’acyle.", "Intermédiaire tétraédrique.", "Retour C=O et départ Cl⁻."],
      "anhydride", {"variant": "formation", "acyl": "acetyl", "stage": 2},
      "Le pont de l’anhydride comporte-t-il une liaison O–O ?",
      "Non : un seul O est lié aux deux carbones carbonylés. R–C(=O)–O–C(=O)–R est un anhydride ; le peracide possède une liaison O–O."),
    R("hemiacetal", "Hémiacétal : première addition d’un alcool", 526, "AN / AB",
      "Éthanal et éthanol", "Catalyse acide ; composition contrôlée", "Hémiacétal CH₃–CH(OH)–OEt",
      ["C=O devient C(OH)(OR) ; une liaison C–O(alcool) s’ajoute."],
      ["Équilibre ; un hémiacétal contient un OH et un OR sur le même carbone."],
      ["Carbone anciennement carbonylé désormais tétraédrique ; aucun deuxième OR à ce stade."],
      ["Activation du carbonyle.", "Addition de ROH.", "Déprotonation de l’oxonium."],
      "carbonyle", {"reaction": "acetal", "stage": 1},
      "Quel motif distingue hémiacétal et acétal ?",
      "L’hémiacétal porte OH et OR sur le même C ; l’acétal porte deux OR et n’y conserve pas de OH."),
    R("acetal", "Acétal : protection réversible d’un carbonyle", 526, "AE-addition-élimination / AB",
      "Éthanal et éthanol, ou carbonyle et diol", "H⁺ ; excès alcool ou élimination d’eau", "1,1-Diéthoxyéthane ; avec diol, acétal cyclique",
      ["Remplacement net de l’O carbonylé par deux groupes OR ; formation d’eau."],
      ["Stable dans de nombreux milieux basiques ; hydrolysable en milieu acide aqueux.", "Protéger avant une opération incompatible, déprotéger après."],
      ["Absence de C=O protégé ; présence du carbone C(OR)₂ ; vérifier la taille réelle d’un cycle si un diol est utilisé."],
      ["Formation de l’hémiacétal.", "Protonation OH puis perte d’eau.", "Capture par un second alcool et déprotonation."],
      "carbonyle", {"reaction": "acetal", "stage": 4, "water": 0.05},
      "Retirer l’eau et ajouter H⁺ ont-ils le même rôle ?",
      "Non : H⁺ catalyse le chemin tandis que le retrait d’un produit modifie le quotient réactionnel et déplace l’équilibre vers l’acétal."),
    R("benzene_photo", "Photohalogénation : addition sur le benzène", 526, "Radicalaire / addition",
      "Benzène", "3 Cl₂ sous irradiation hν", "Hexachlorocyclohexane : C₆H₆Cl₆, mélange stéréochimique possible",
      ["Les trois liaisons π du cycle sont consommées ; six liaisons C–Cl se forment ; les six H restent."],
      ["Conditions photoradicalaires distinctes de Cl₂ / acide de Lewis.", "Le bilan ne sélectionne pas à lui seul un unique isomère du cyclohexane chloré."],
      ["C₆H₆Cl₆ saturé et non aromatique, à distinguer de C₆H₅Cl aromatique issu d’une SEA."],
      ["Génération d’espèces radicalaires par la lumière.", "Additions sur le système π.", "Bilan de trois Cl₂ pour saturer les trois π."],
      "photochlore", {"mode": "addition", "chlorine": 3, "light": "on", "stage": 2},
      "Quel simple bilan distingue cette transformation de la chloration aromatique ?",
      "En addition photochimique six Cl sont ajoutés et aucun H n’est remplacé. En SEA un H est remplacé par Cl, l’aromaticité est conservée et HCl est produit."),
    R("amine_alkyl", "Alkylation d’amine : former un ammonium quaternaire", 526, "SN2",
      "Triméthylamine ou triéthylamine", "Halogénoalcane primaire, par exemple CH₃X", "Sel tétraalkylammonium [R₃N–CH₃]⁺ X⁻",
      ["Le doublet de N forme C–N ; C–X se rompt ; N porte quatre liaisons et +1."],
      ["Une amine tertiaire ne possède pas de N–H à déprotoner après alkylation.", "Amine et ammonium quaternaire n’ont pas la même basicité ni le même doublet disponible."],
      ["Compter quatre groupes carbonés autour de N et un contre-ion X⁻ ; aucune libération de H⁺ nécessaire."],
      ["Attaque arrière de N sur C–X.", "Départ de X⁻.", "Formation du sel ionique."],
      "aminealkyl", {"amine": "trimethyl", "electrophile": "methyl", "stage": 2},
      "Pourquoi N garde-t-il une charge positive ?",
      "Le N quaternaire possède quatre liaisons et aucun doublet libre. Sans H porté par N, une déprotonation de N ne peut pas rendre une amine tertiaire."),
    R("grignard_prepare", "Préparer RMgX : ordre d’introduction et absence de protons", 526, "Insertion / OR",
      "Bromoéthane ou bromobenzène", "Mg ; solvant éthéré anhydre ; ajout contrôlé RX", "EtMgBr ou PhMgBr",
      ["Remplacement du bilan C–Br par C–Mg–Br ; activation du métal."],
      ["L’eau ou un proton acide consomme RMgX en donnant RH.", "L’éther coordonne Mg ; hydrolyse uniquement lors du traitement final après la réaction recherchée."],
      ["Vérifier les équivalents disponibles plutôt que supposer un organomagnésien intact dans un milieu humide."],
      ["Amorcer le contact Mg / RX.", "Former l’organomagnésien en milieu sec.", "Éviter eau et fonctions protiques pendant son utilisation."],
      "grignardprep", {"group": "ethyl", "halide": "Br", "water": 0, "progress": 1, "stage": 2},
      "Pourquoi une hydrolyse avant l’addition détruit-elle le projet ?",
      "RMgX est une base forte : son carbone prélève H et donne RH. Il ne reste alors plus le nucléophile carboné requis pour construire C–C."),
    R("grignard_methanal", "RMgX + méthanal : allonger d’un carbone", 526, "AN / AB",
      "Méthanal", "EtMgBr puis hydrolyse séparée", "Propan-1-ol",
      ["Création Et–CH₂ ; C=O devient C–OH après hydrolyse."],
      ["Le méthanal donne un alcool primaire, car son C fonctionnel ne porte pas de groupe carboné avant l’addition."],
      ["Trois C au total ; carbone portant OH lié à un seul C."],
      ["Et attaque C=O ; π → O.", "Alcoolate magnésien.", "Protonation lors du traitement."],
      "grignard", {"substrate": "methanal", "alkyl": "ethyl", "equivalents": 1, "water": 0, "stage": 2},
      "De quel partenaire vient le carbone portant OH ?",
      "Du méthanal. L’éthyle devient son substituant carboné, ce qui allonge la chaîne d’un carbone par rapport à EtMgBr."),
    R("grignard_aldehyde", "RMgX + aldéhyde : alcool secondaire", 526, "AN / AB",
      "Éthanal", "PhMgBr puis hydrolyse", "1-Phényléthanol",
      ["Formation C(carbonyle)–Ph ; création d’un carbone tétraédrique portant OH."],
      ["Deux faces du carbonyle plan ; milieu achiral donnant le mélange racémique dans ce cas."],
      ["Alcool secondaire, groupe CH₃ et Ph sur le C–OH ; vérifier R/S après représentation 3D."],
      ["Addition nucléophile.", "Alcoolate magnésien.", "Hydrolyse finale."],
      "grignard", {"substrate": "aldehyde", "alkyl": "phenyl", "equivalents": 1, "stage": 2},
      "Pourquoi un centre chiral apparaît-il ici ?",
      "Le carbone fonctionnel porte OH, H, CH₃ et Ph : quatre groupes différents. Les deux faces planes donnent les deux configurations en milieu achiral."),
    R("grignard_cetone", "RMgX + cétone : alcool tertiaire", 526, "AN / AB",
      "Propanone", "EtMgBr puis hydrolyse", "2-Méthylbutan-2-ol",
      ["Le C carbonylé reçoit un troisième substituant carboné ; C=O devient C–OH."],
      ["Alcool tertiaire ; absence de centre chiral ici, car les deux CH₃ sont identiques."],
      ["C–OH lié à trois C ; compter cinq C au produit et contrôler la valence."],
      ["Transfert Et vers C=O.", "Alcoolate.", "Protonation de O."],
      "grignard", {"substrate": "ketone", "alkyl": "ethyl", "equivalents": 1, "stage": 2},
      "Toute addition à une cétone crée-t-elle de la chiralité ?",
      "Non : elle donne un alcool tertiaire mais un centre chiral exige quatre groupes différents. Ici les deux méthyles rendent le centre achiral."),
    R("grignard_co2", "RMgX + CO₂ : carboxylation", 526, "AN / AB",
      "Dioxyde de carbone", "PhMgBr puis traitement acide", "Acide benzoïque",
      ["Création Ph–C(CO₂) ; un C est ajouté au squelette ; carboxylate avant traitement."],
      ["Le carbone de CO₂ devient celui du groupe carboxylique."],
      ["RCO₂⁻ avant acidification, RCO₂H après ; formule C₇H₆O₂ pour l’acide benzoïque."],
      ["Attaque du carbone nucléophile sur CO₂.", "Carboxylate magnésien.", "Acidification séparée."],
      "grignard", {"substrate": "co2", "alkyl": "phenyl", "equivalents": 1, "stage": 2},
      "L’hydrolyse donne-t-elle un alcool dans ce cas ?",
      "Non. L’intermédiaire est un carboxylate : le traitement protonne cette fonction et livre un acide carboxylique."),
    R("hydrogenation", "Hydrogénation : saturation et addition syn", 527, "Addition / OR",
      "(E)- ou (Z)-but-2-ène", "H₂ / catalyseur métallique adapté", "Butane",
      ["C=C devient C–C ; un H est livré à chacun des deux carbones."],
      ["Addition sur une même face dans le modèle de surface ; adsorption et désorption expliquent le bilan syn."],
      ["Disparition de l’insaturation ; E/Z n’existe plus dans le butane."],
      ["Adsorption du substrat et activation de H₂.", "Transfert des H sur la même face dans le modèle.", "Désorption du produit."],
      "alcene", {"substrate": "butene_Z", "reagent": "hydrogen", "stage": 2},
      "Le butane garde-t-il l’étiquette Z de son précurseur ?",
      "Non : E/Z est une configuration d’une double liaison. La rotation autour de la nouvelle liaison simple produit des conformères du même butane."),
    R("hydroboration", "Hydroboration–oxydation : alcool anti-Markovnikov", 527, "Addition concertée / OR",
      "Propène", "1. BH₃ ; 2. H₂O₂ / HO⁻", "Propan-1-ol",
      ["Première étape : création C–B et C–H ; deuxième : remplacement C–B par C–O avec rétention."],
      ["B se fixe préférentiellement sur le C le moins encombré ; H et B s’ajoutent syn.", "Après oxydation, H et OH gardent cette relation relative ; pas de carbocation libre."],
      ["Alcool primaire au lieu du secondaire de l’hydratation acide du propène."],
      ["Addition concertée H–B.", "Oxydation du groupe organoboré.", "Traitement donnant l’alcool."],
      "alcene", {"substrate": "propene", "reagent": "borane", "stage": 2},
      "OH est-il transféré depuis BH₃ lors de la première étape ?",
      "Non : la première étape fixe H et B. La fonction OH apparaît pendant l’oxydation et le traitement suivants ; séparer les étapes explique l’orientation et la stéréochimie."),
    R("fc_alkyl", "Friedel–Crafts : alkylation aromatique", 527, "SEA",
      "Benzène", "Halogénoalcane / acide de Lewis dans un cas compatible", "Alkylbenzène et HX",
      ["Ar–H devient Ar–R ; une liaison C–C se forme."],
      ["Réarrangements possibles selon l’électrophile ; produit alkylé souvent plus réactif, donc polyalkylation possible.", "Un noyau fortement désactivé par NO₂ ne convient pas à la voie usuelle."],
      ["Un alkyle remplace un H du cycle ; aromaticité finale conservée."],
      ["Activation du dérivé halogéné.", "Attaque du cycle et complexe σ.", "Déprotonation et restauration de l’aromaticité."],
      "aromatique", {"substituent": "h", "reaction": "alkylation", "stage": 2},
      "Pourquoi une simple règle ortho/para ne prédit-elle pas une synthèse complète ?",
      "Il faut aussi vérifier la possibilité de la réaction, les migrations du groupe alkyle et la réactivité accrue du produit. Orientation, conversion et monoalkylation sont des questions distinctes."),
    R("fc_acyl", "Friedel–Crafts : acylation pour contrôler le squelette", 527, "SEA",
      "Benzène", "Chlorure d’éthanoyle / AlCl₃ puis traitement", "Acétophénone",
      ["Création Ar–C(=O)CH₃ ; remplacement d’un H aromatique."],
      ["Ion acylium stabilisé ; pas de migration de squelette de type carbocation alkyle.", "COCH₃ désactive le cycle et oriente une nitration suivante vers méta."],
      ["Cétone aromatique conjuguée ; le carbonyle fait partie du groupe ajouté."],
      ["Formation d’un électrophile acyle.", "Complexe σ.", "Réaromatisation puis libération du carbonyle complexé au traitement."],
      "aromatique", {"substituent": "h", "reaction": "acylation", "stage": 2},
      "Quel ordre permet d’obtenir une nitroacétophénone méta par cette stratégie ?",
      "Acyler d’abord un noyau compatible, puis nitrer : COCH₃ dirige vers méta. Nitrer d’abord donne un noyau trop désactivé pour la Friedel–Crafts usuelle."),
    R("aldol_croisee", "Aldolisation croisée : donner et recevoir ne sont pas symétriques", 527, "AN / énolate",
      "Acétophénone et benzaldéhyde", "Base ; conditions adaptées à l’addition", "β-Hydroxycétone PhCO–CH₂–CH(OH)–Ph",
      ["Création Cα(donneur)–C(carbonyle accepteur) ; C=O de l’accepteur devient alcool."],
      ["Le benzaldéhyde n’a pas de Hα et sert d’accepteur.", "Deux partenaires énolisables non dirigés peuvent multiplier les produits."],
      ["Produit possédant à la fois C=O et OH en β ; compter les deux noyaux Ph."],
      ["Formation de l’énolate de l’acétophénone.", "Attaque du Cα sur le benzaldéhyde.", "Protonation de l’alcoolate."],
      "aldol", {"donor": "acetophenone", "acceptor": "benzaldehyde", "mode": "aldol", "stage": 3},
      "Quel carbonyle est conservé ?",
      "Celui du donneur acétophénone. Le carbonyle du benzaldéhyde reçoit l’attaque et devient le groupe OH de la β-hydroxycétone."),
    R("crotonisation", "Crotonisation : construire l’énone conjuguée", 528, "E / E1cb",
      "β-Hydroxycétone issue de l’aldolisation acétophénone/benzaldéhyde", "Conditions déshydratantes adaptées, souvent base et chauffage", "Chalcone PhCO–CH=CH–Ph et eau au bilan",
      ["Perte de Hα et OHβ au bilan ; nouvelle Cα=Cβ conjuguée à C=O."],
      ["La conjugaison stabilise l’énone ; E souvent favorisé dans ce cas mais les conditions sont requises.", "En base, E1cb est une description utile quand l’énolate précède le départ d’un mauvais groupe partant."],
      ["OH disparaît ; deux carbones vinyliques apparaissent ; C=O reste présent."],
      ["Déprotonation en α.", "Énolate / base conjuguée stabilisée.", "Élimination formant la conjugaison ; bilan net H₂O."],
      "aldol", {"donor": "acetophenone", "acceptor": "benzaldehyde", "mode": "condensation", "stage": 3},
      "Pourquoi la crotonisation n’est-elle pas une nouvelle aldolisation ?",
      "L’aldolisation crée la liaison C–C par addition ; la crotonisation convertit le β-hydroxycarbonyle déjà formé en carbonyle α,β-insaturé par élimination."),
    R("amide_anhydride", "Amide via anhydride : choisir le départ et piéger l’acide", 528, "AE-addition-élimination / AB",
      "Anhydride éthanoïque et amine", "Amine nucléophile ; autre base ou second équivalent", "Amide et carboxylate d’ammonium selon le traitement",
      ["Une moitié acyle devient amide ; l’autre fournit un carboxylate / acide."],
      ["Ne pas compter deux amides pour un anhydride dans ce simple bilan d’acylation.", "La basicité des espèces détermine la forme acide ou salifiée en fin de réaction."],
      ["Un C=O adjacent à N dans l’amide et un carboxylate distinct ; N peut garder un H selon l’amine."],
      ["Addition de l’amine au carbone acyle.", "Élimination du carboxylate.", "Transferts de protons vers la base disponible."],
      "acylation", {"activation": "anhydride", "amine": 2, "base": 0, "stage": 3},
      "Quel fragment de l’anhydride devient le groupe partant ?",
      "Le carboxylate de l’autre moitié acyle. Sa structure stabilisée rend cette addition–élimination possible ; ce fragment ne reste pas lié au N du produit."),
    R("michael", "Michael : l’attaque conjuguée construit une liaison en β", 528, "AN conjuguée",
      "Énolate stabilisé de malonate et but-3-én-2-one", "Base puis traitement protonant", "Adduit portant le motif carbonyle et une nouvelle liaison C–C en β",
      ["Création C(donneur)–Cβ(accepteur) ; Cα=Cβ est consommée ; le carbonyle de l’accepteur revient après protonation."],
      ["Nucléophile stabilisé favorable à 1,4 dans ce cas.", "Un Grignard dur donne souvent une attaque 1,2 ; un organocuprate favorise fréquemment 1,4."],
      ["Adduit 1,4 : C=O présent et double liaison conjuguée consommée ; adduit 1,2 : alcool et C=C conservée."],
      ["Attaque du C nucléophile sur Cβ.", "Délocalisation vers l’énolate de l’accepteur.", "Protonation et retour du carbonyle."],
      "michaelwittig", {"reaction": "michael", "reagent": "enolate", "stage": 3},
      "Comment distinguer les produits 1,2 et 1,4 sans retenir seulement leur nom ?",
      "On suit les liaisons : 1,2 transforme C=O en alcool tout en gardant C=C ; 1,4 consomme C=C et conserve le carbonyle après traitement."),
    R("wittig", "Wittig : remplacer C=O par C=C", 528, "Oléfination / AN",
      "Benzaldéhyde et ylure de phosphore", "Ylure choisi puis traitement", "Alcène et oxyde de triphénylphosphine",
      ["Le C du carbonyle se lie au C de l’ylure ; O quitte le substrat pour former Ph₃P=O."],
      ["Stabilisation de l’ylure et conditions influencent E/Z ; aucune règle absolue indépendante du réactif."],
      ["Le carbone carbonylé appartient désormais à C=C ; reconnaître l’oxyde de phosphine comme coproduit distinct."],
      ["Attaque du carbone de l’ylure.", "Formation d’un oxaphosphétane dans la description du modèle.", "Fragmentation vers alcène et Ph₃P=O."],
      "michaelwittig", {"reaction": "wittig", "reagent": "unstabilized", "stage": 3},
      "Où va l’oxygène du carbonyle ?",
      "Dans l’oxyde de phosphine. Le compter uniquement dans l’alcène ferait violer le bilan d’atomes : l’oléfination enlève la fonction oxygénée du substrat."),
    R("epoxy_industriel", "Oxyde d’éthylène : époxydation catalytique ciblée", 528, "OR / catalyse",
      "Éthylène", "O₂ / argent dans le procédé catalytique adapté", "Oxyde d’éthylène : C₂H₄O",
      ["Ajout d’un O en pont ; C=C devient C–C."],
      ["Exemple industriel lié à l’éthylène ; ne pas généraliser O₂/Ag à tous les alcènes sans données.", "La sélectivité du catalyseur doit éviter l’oxydation totale."],
      ["Cycle à trois atomes C–C–O ; bilan global 2 C₂H₄ + O₂ → 2 C₂H₄O."],
      ["Activation catalytique de l’oxygène.", "Transfert à l’alcène dans les conditions du procédé.", "Séparation du produit."],
      "epoxydes", {"substrate": "ethylene", "mode": "silver", "stage": 3}, "Pourquoi le bilan global ne fournit-il pas un mécanisme élémentaire ?",
      "Il garantit la conservation des atomes. Les espèces adsorbées, étapes de surface et sélectivité nécessitent un modèle catalytique supplémentaire.",
      model_note="Procédé à l’argent réservé ici à l’éthylène ; sélectivité et mécanisme complet de surface non calculés."),
    R("epoxy_ouverture", "Époxyde : libérer la tension par une attaque nucléophile", 528, "SN2 / AN",
      "Oxyde d’éthylène", "HO⁻ puis traitement protonant ; autre nucléophile selon le projet", "Éthane-1,2-diol pour HO⁻ après protonation",
      ["Rupture d’une liaison C–O du cycle et formation C–Nu ; l’autre C–O devient OH."],
      ["En milieu basique : attaque arrière sur le site le moins encombré.", "Les conditions acides ont une autre pondération électronique ; ne pas les confondre."],
      ["Ouverture du cycle C–C–O ; suivre quel carbone porte Nu et lequel porte OH."],
      ["Attaque arrière du nucléophile.", "Rupture C–O et alcoolate.", "Protonation au traitement."],
      "epoxydes", {"substrate": "ethylene", "mode": "basic", "nucleophile": "water", "stage": 3},
      "Pourquoi l’oxygène n’est-il pas éliminé de la molécule ?",
      "Une seule des deux liaisons C–O du cycle est rompue ; l’autre conserve O sur le squelette, sous forme alcoolate puis alcool."),
    R("bromation_e", "Br₂ sur alcène E : bromonium puis ouverture anti", 531, "AE",
      "(E)-but-2-ène", "Br₂ sans irradiation radicalaire", "2,3-Dibromobutane méso dans ce cas",
      ["C=C consommée ; deux C–Br formées."],
      ["Intermédiaire ponté bromonium ; attaque de Br⁻ sur la face opposée.", "La relation anti est stéréospécifique et le substrat E mène ici au méso."],
      ["Deux centres stéréogènes mais une structure achirale par symétrie ; ne pas compter systématiquement 2² isomères."],
      ["Polarisation de Br₂ et formation du bromonium.", "Ouverture anti par Br⁻.", "Attribution des configurations et test de symétrie."],
      "alcene", {"substrate": "butene_E", "reagent": "bromine", "stage": 2},
      "Deux centres stéréogènes garantissent-ils une molécule chirale ?",
      "Non. Le 2,3-dibromobutane méso possède une symétrie qui rend l’image miroir superposable malgré ses deux centres."),
    R("bromation_z", "Br₂ sur alcène Z : paire d’énantiomères", 533, "AE",
      "(Z)-but-2-ène", "Br₂ sans lumière", "Mélange (2R,3R)/(2S,3S) de 2,3-dibromobutane",
      ["Même bilan de connectivité que le substrat E, mais autre stéréochimie."],
      ["Addition anti ; les deux faces donnent une paire racémique en milieu achiral."],
      ["Comparer le produit au méso issu du réactif E ; une RMN achirale ne distingue pas les deux énantiomères."],
      ["Bromonium depuis chacune des faces équivalentes.", "Ouverture anti.", "Dessiner les deux produits 3D avant CIP."],
      "alcene", {"substrate": "butene_Z", "reagent": "bromine", "stage": 2},
      "Quelle observation démontre la stéréospécificité ?",
      "Les alcènes E et Z, sous un même mécanisme anti, donnent des ensembles stéréochimiques différents : méso pour E dans ce cas, paire racémique pour Z."),
    R("hydratation_acide", "Hydratation acide : AE puis capture nucléophile", 531, "AE / AN / AB",
      "Propène", "H₂O / H⁺", "Propan-2-ol et catalyseur régénéré",
      ["H et OH s’ajoutent au bilan ; H⁺ n’est pas consommé net."],
      ["Orientation par carbocation ; réarrangements possibles sur des substrats adaptés."],
      ["OH en C2 ; alcool secondaire ; distinguer le bilan global et les actes élémentaires."],
      ["Protonation de C=C : acte électrophile.", "Capture du carbocation par H₂O : acte nucléophile.", "Déprotonation : acte acido-basique."],
      "alcene", {"substrate": "propene", "reagent": "water", "stage": 2},
      "Une réaction globale peut-elle contenir plusieurs types d’actes élémentaires ?",
      "Oui. L’hydratation acide combine protonation électrophile, capture nucléophile et transfert de proton. Il faut annoncer l’échelle du classement choisi."),
    R("e1_rearrangement", "E1 du recueil : deux positions β, deux connectivités", 531, "E1",
      "2-Chloro-3-méthylbutane", "Milieu permettant l’ionisation ; base disponible ; conditions précisées",
      "2-Méthylbut-2-ène et/ou 3-méthylbut-1-ène pour les deux branches représentées",
      ["Départ de Cl⁻ puis perte de H sur l’un des Cβ ; une liaison C=C se forme."],
      ["Les deux positions β représentées n’aboutissent pas au même degré de substitution.", "Le branchement du modèle est imposé ; il ne déduit pas un pourcentage de la seule règle de Zaïtsev.", "Un carbocation peut se réarranger sous certaines conditions ; les migrations sont hors du modèle des deux éliminations directes représentées."],
      ["Dessiner chaque alcène et recompter cinq C ; distinguer alcène interne et terminal."],
      ["C–Cl → Cl⁻ et carbocation secondaire.", "Choisir un Hβ sur chacun des deux sites.", "La base capte H ; C–H forme la nouvelle liaison π."],
      "e1", {"substrate": "source", "stage": 3},
      "Quel élément du raisonnement permet de dessiner les deux produits ?",
      "L’énumération des sites β et de leurs H. La stabilité peut ensuite comparer les voies accessibles, mais ne remplace ni le dessin des liaisons ni des données de branchement pour un pourcentage."),
    R("e2_source_e", "E2 du recueil : (3S,4S)/(3R,4R) vers E", 531, "E2",
      "3-Bromo-3,4-diméthylhexane, paire (3S,4S)/(3R,4R)", "Base ; H de C4 anti à Br", "(E)-3,4-Diméthylhex-3-ène pour l’élimination C3–C4",
      ["Rupture C3–Br et C4–H ; formation C3=C4."],
      ["Les deux réactifs énantiomères donnent le même alcène E achiral dans cette voie.", "D’autres Hβ permettent d’autres régioisomères : ils ne sont pas supprimés par l’étiquette E2."],
      ["Sur chaque C vinylique Et est prioritaire sur CH₃ ; Et opposés donnent E."],
      ["Construire Newman suivant C3–C4 sans changer R/S.", "Placer H4 et Br anti par rotation.", "Supprimer H et Br et attribuer E/Z du produit."],
      "e2stereo", {"configuration": "SS", "dihedral": 180, "beta": "c4"},
      "Pourquoi SS et RR aboutissent-ils au même E ?",
      "Ils sont images miroir au départ. La double liaison plane du produit E de cette connectivité ne garde pas ces centres tétraédriques ; le miroir est superposable."),
    R("e2_source_z", "E2 du recueil : (3S,4R)/(3R,4S) vers Z", 533, "E2",
      "3-Bromo-3,4-diméthylhexane, paire (3S,4R)/(3R,4S)", "Base ; H de C4 anti à Br", "(Z)-3,4-Diméthylhex-3-ène pour l’élimination C3–C4",
      ["Même rupture C3–Br / C4–H que l’autre paire, mais configuration relative distincte."],
      ["La disposition anti impose ici Et du même côté ; E2 est stéréospécifique pour la voie choisie."],
      ["Et prioritaire sur CH₃ de chaque côté ; priorités du même côté donnent Z."],
      ["Dessiner l’isomère SR ou RS.", "Mettre Br et H4 anti par rotation propre.", "Lire Z après l’élimination."],
      "e2stereo", {"configuration": "SR", "dihedral": 180, "beta": "c4"},
      "Peut-on obtenir l’autre E/Z en tournant simplement une liaison après la réaction ?",
      "Non : la rotation libre autour de C=C n’est pas permise sans casser le système π. La rotation avant l’E2 respecte les configurations et ne change pas le produit stéréospécifique de cette voie."),
    R("ozonolyse", "Ozonolyse : couper pour reconstruire l’alcène initial", 531, "OR / coupure",
      "But-2-ène E ou Z", "1. O₃ ; 2. traitement réducteur indiqué", "Deux molécules d’éthanal",
      ["C=C coupée ; chacun des deux anciens carbones devient un carbone carbonylé."],
      ["Le traitement final compte : réducteur et oxydant ne conduisent pas toujours aux mêmes fonctions.", "La coupure ne conserve pas une information E/Z dans les deux fragments éthanal."],
      ["Chaque C de la double liaison portant H donne ici un aldéhyde ; sans H il donnerait une cétone."],
      ["Réaction de l’ozone avec C=C.", "Intermédiaires oxygénés.", "Traitement et séparation des carbonyles."],
      "alcene", {"substrate": "butene_E", "reagent": "ozone", "stage": 2},
      "Comment retrouver C=C à partir de deux fragments carbonylés ?",
      "Relier les deux carbones carbonylés par une double liaison après avoir retiré leurs O dans le raisonnement rétrosynthétique. Les substituants conservés reconstruisent la constitution, pas nécessairement E/Z."),
    R("diol_syn", "Oxydation douce : dihydroxylation syn", 533, "OR / addition syn",
      "But-2-ène", "Oxydant adapté en conditions douces, diluées et froides", "Butane-2,3-diol",
      ["C=C devient C–C ; deux C–O créées ; pas de coupure C–C dans ces conditions."],
      ["Addition syn ; les conditions fortes peuvent au contraire cliver la liaison."],
      ["Diol vicinal avec deux OH sur carbones voisins ; comparer à l’époxyde qui contient un seul O pontant."],
      ["Addition sur une face selon le mécanisme de l’oxydant.", "Intermédiaire cyclique oxygéné.", "Hydrolyse vers le diol."],
      "alcene", {"substrate": "butene_E", "reagent": "diol", "stage": 2},
      "Un même oxydant garantit-il le même produit quelle que soit la température ?",
      "Non. Concentration, température et traitement déterminent si la transformation s’arrête au diol ou poursuit l’oxydation jusqu’à des fragments carbonylés ou acides."),
    R("alcyne_hcl", "Alcyne + deux HX : halogénure vinylique puis geminal", 531, "AE",
      "Propyne", "1 puis 2 équivalents HCl dans le cas du recueil", "2-Chloroprop-1-ène puis 2,2-dichloropropane",
      ["Une première π est consommée ; la seconde addition sature la liaison restante.", "Deux Cl finissent sur le même carbone : geminal."],
      ["Distinguer 1 et 2 équivalents ; l’intermédiaire vinylique n’est pas encore un alcane."],
      ["Après 1 HX : C=C présente ; après 2 HX : deux halogènes sur un seul C et absence de liaison multiple."],
      ["Première addition HX sur C≡C.", "Halogénoalcène.", "Deuxième addition sur C=C."],
      "alcyne", {"substrate": "propyne", "reagent": "hcl2", "stage": 2},
      "Que signifie geminal, et pourquoi préciser les équivalents ?",
      "Geminal signifie deux halogènes sur le même carbone. Un équivalent livre ici le chlorure vinylique ; un second consomme la double liaison restante et livre le dichlorure saturé."),
    R("alcyne_br", "Alcyne + Br₂ : contrôler une ou deux additions", 533, "AE",
      "Propyne ou but-2-yne", "1 puis 2 équivalents Br₂", "Dibromoalcène puis tétrabromoalcane",
      ["Première addition : perte d’une π et création de deux C–Br ; deuxième : deux C–Br supplémentaires."],
      ["Addition anti prédominante dans les cas standards de première addition.", "Le tétrabromure possède deux Br sur chacun des anciens C sp."],
      ["Compter quatre Br au produit saturé ; distinguer ce tétrabromure du dibromure geminal issu de 2 HBr."],
      ["Addition de Br₂ sur une π.", "Alcène dibromé.", "Nouvelle addition de Br₂."],
      "alcyne", {"substrate": "propyne", "reagent": "br2", "stage": 2},
      "Pourquoi 2 HBr et 2 Br₂ n’aboutissent-ils pas au même nombre de Br ?",
      "HBr livre un Br par équivalent tandis que Br₂ en livre deux. Le comptage des atomes précède toute lecture du nom de mécanisme."),
    R("alcyne_lindlar", "Réduction partielle d’alcyne : sélectionner Z", 531, "OR / addition syn",
      "But-2-yne", "H₂ / catalyseur de Lindlar", "(Z)-but-2-ène",
      ["C≡C devient C=C ; un H ajouté sur chaque C."],
      ["Addition syn et catalyseur modéré permettant l’arrêt à l’alcène.", "Na / NH₃ liquide fournit un autre chemin, souvent l’alcène E."],
      ["Une insaturation reste ; deux CH₃ du même côté de C=C donnent Z."],
      ["Adsorption sur le catalyseur adapté.", "Livraison syn de H.", "Désorption de l’alcène sans réduction exhaustive dans les conditions choisies."],
      "alcyne", {"substrate": "butyne", "reagent": "lindlar", "stage": 2},
      "Faut-il deux équivalents H₂ pour atteindre l’alcène ?",
      "Un équivalent H₂ suffit au bilan alcyne→alcène. Deux équivalents sont nécessaires pour alcyne→alcane."),
    R("alcyne_h2_total", "Réduction exhaustive d’alcyne : saturer deux π", 533, "OR / addition",
      "But-2-yne", "H₂ en excès / métal actif", "Butane",
      ["C≡C devient C–C ; quatre H ajoutés au bilan."],
      ["Le catalyseur et l’excès différencient cette voie de Lindlar.", "Pas de configuration E/Z au produit saturé."],
      ["Bilan C₄H₆ + 2 H₂ → C₄H₁₀ ; indice d’insaturation passe de 2 à 0."],
      ["Première hydrogénation vers alcène.", "Deuxième hydrogénation.", "Produit saturé."],
      "alcyne", {"substrate": "butyne", "reagent": "hydrogen", "stage": 2},
      "Pourquoi le catalyseur doit-il être précisé avec H₂ ?",
      "La formule H₂ seule ne dit pas si la réaction s’arrête à l’alcène ou va à l’alcane. Activité, nature de la surface et quantité de H₂ déterminent les conditions de sélectivité."),
    R("alcyne_hydratation", "Hydratation d’alcyne : énol transitoire, cétone isolée", 531, "AE / tautomérie",
      "Propyne", "H₂O / H⁺ / Hg²⁺ dans le cas du recueil", "Énol puis propanone",
      ["Hydratation de C≡C vers C=C–OH ; transfert de proton et déplacement de π vers C=O."],
      ["Orientation du cas terminal conduisant à la méthylcétone.", "Une hydroboration sélective/oxydation d’un terminal offre au contraire un aldéhyde."],
      ["Ne pas isoler graphiquement l’énol comme produit final si le traitement conduit au carbonyle ; cétone C=O sans OH vinylique."],
      ["Activation de l’alcyne et addition de l’eau.", "Énol.", "Tautomérie catalysée vers la cétone."],
      "alcyne", {"substrate": "propyne", "reagent": "mercury", "stage": 2},
      "La tautomérie est-elle une mésomérie ?",
      "Non : elle déplace un proton et change des liaisons σ, donc décrit des espèces distinctes. Une mésomérie ne déplace pas les noyaux."),
    R("nitro_lewis", "Nitrobenzène : charges correctes avant de réagir", 532, "Structure / mésomérie",
      "Nitrobenzène C₆H₅NO₂", "Comptabilité de Lewis et conjugaison", "Deux contributeurs principaux Ph–N⁺(=O)–O⁻ et Ph–N⁺(–O⁻)=O",
      ["Aucun produit créé ; les deux O échangent leur rôle de liaison simple/double dans les contributeurs."],
      ["N de deuxième période respecte l’octet : quatre liaisons au total, charge +1.", "Le groupe nitro retire par −I et −M."],
      ["Vérifier neutralité globale, octets, deux O équivalents dans la description délocalisée et absence de doublet libre sur N."],
      ["Compter les électrons de valence.", "Placer N⁺ et O⁻.", "Déplacer des doublets sans déplacer les atomes."],
      "nitrobenzene", {"mode": "lewis", "contributor": "oxygen_a", "stage": 0},
      "Peut-on dessiner deux N=O et une liaison N–Ph sans charges ?",
      "Ce N aurait cinq liaisons et dix électrons autour de lui ; il n’est pas une représentation de Lewis usuelle respectant l’octet. Les contributeurs N⁺/O⁻ résolvent le comptage."),
    R("nitro_reduction", "Nitrobenzène → aniline : trois réductions à deux électrons", 534, "OR / AB",
      "Nitrobenzène", "Réducteur métal/acide adapté puis neutralisation", "Aniline ; nitroso et hydroxylamine comme états intermédiaires de la banque",
      ["PhNO₂ → PhNO → PhNHOH → PhNH₂ ; conservation de la liaison C–N."],
      ["Bilan acide : PhNO₂ + 6 H⁺ + 6 e⁻ → PhNH₂ + 2 H₂O.", "En milieu acide, l’aniline peut être protonée ; la neutralisation est une opération distincte."],
      ["Le groupe NO₂ devient NH₂, sans hydrogénation obligatoire du cycle ; suivre N, O, H et charge à chaque état."],
      ["Deux électrons et deux H⁺ : nitro → nitroso + H₂O.", "Deux électrons et deux H⁺ : nitroso → hydroxylamine.", "Deux électrons et deux H⁺ : hydroxylamine → aniline + H₂O."],
      "nitrobenzene", {"mode": "reduction", "stage": 3},
      "Pourquoi le total vaut-il six électrons et deux eaux ?",
      "Additionner les trois bilans 2 e⁻ / 2 H⁺ annule les intermédiaires. Les premier et dernier actes forment chacun une eau, soit le bilan global 6 e⁻, 6 H⁺ et 2 H₂O."),
    R("nitro_nitration", "Nitration du nitrobenzène : orientation et désactivation", 532, "SEA",
      "Nitrobenzène", "HNO₃ / H₂SO₄ ; conditions compatibles avec un noyau désactivé", "Dinitrobenzènes ; isomère méta généralement favorisé",
      ["Un H aromatique est remplacé par NO₂ ; un second groupe nitro apparaît."],
      ["NO₂ retire par −M et −I ; les complexes ortho/para sont moins favorables.", "Une orientation qualititative ne fournit pas les proportions sans données expérimentales ou cinétiques."],
      ["Dessiner les connectivités 1,2 / 1,3 / 1,4 puis utiliser la symétrie pour le diagnostic, sans convertir un dipôle en rendement."],
      ["Formation de NO₂⁺.", "Comparer les complexes σ des trois positions.", "Déprotonation et retour de l’aromaticité."],
      "aromatique", {"substituent": "nitro", "reaction": "nitration", "stage": 2},
      "Le caractère méta-directeur signifie-t-il que le nitrobenzène est activé ?",
      "Non : méta compare les voies sur le nitrobenzène. La désactivation compare leur vitesse à celle du benzène ; toutes peuvent être plus lentes."),
    R("nitro_dipoles", "Dinitrobenzènes : somme de vecteurs, pas somme de rendements", 534, "Caractérisation / vecteurs",
      "Isomères ortho, méta et para du dinitrobenzène", "Modèle de deux dipôles égaux μ₀ radiaux dans un hexagone régulier", "Normes idéalisées √3 μ₀, μ₀ et 0",
      ["Aucune liaison modifiée ; somme vectorielle de deux contributions fixes."],
      ["Angles entre directions : 60° pour ortho, 120° pour méta, 180° pour para.", "Le modèle néglige les effets d’interaction entre substituants."],
      ["Pour μ₀=4,03 D : environ 6,98 D, 4,03 D et 0 D dans ce modèle.", "Une molécule polaire ne représente pas une fraction du mélange ; composition et propriété doivent être séparées."],
      ["Choisir les deux directions.", "Additionner les composantes.", "Calculer μ²=μ₀²+μ₀²+2μ₀² cos θ."],
      "dipolesnitro", {"isomer": "ortho", "mu0": 4.03, "rotation": 0},
      "Ces trois normes suffisent-elles à retrouver trois proportions de produits ?",
      "Non : elles caractérisent trois isomères dans un modèle. Pour remonter aux fractions d’un mélange il faut un protocole de mesure et une loi de mélange, avec assez d’informations indépendantes."),
    R("nitro_strategie", "Ordre des SEA : construire une cible à quatre substituants", 534, "SEA / stratégie",
      "Bromobenzène comme point de départ", "Acylation compatible puis nitration puis chloration, avec choix d’isomères", "Cible portant COCH₃ en C1, Cl en C3, Br en C4, NO₂ en C5",
      ["Trois H du noyau remplacés successivement par COCH₃, NO₂ et Cl ; Br initial conservé."],
      ["Une première acylation sur le bromobenzène permet de choisir l’isomère para utile.", "COCH₃ méta-directeur et Br ortho/para-directeur peuvent converger ; NO₂ change ensuite les possibilités.", "Une route plausible n’est pas la preuve d’un produit unique ni d’un rendement garanti."],
      ["Numéroter le cycle ; contrôler les relations ortho/méta/para à chaque étape ; suivre la formule finale C₈H₅BrClNO₃."],
      ["Acyler avant d’installer un groupe nitro fortement désactivant.", "Choisir/isoler l’isomère compatible avec la cible.", "Réévaluer l’orientation de chaque nouvelle SEA sur le noyau alors présent."],
      "nitrobenzene", {"mode": "strategy", "route": "bromobenzene", "stage": 3},
      "Pourquoi tester un ordre inverse dans le laboratoire ?",
      "Le groupe NO₂ installé d’abord rend la Friedel–Crafts usuelle incompatible. L’ordre de synthèse doit satisfaire la réactivité aussi bien que les règles d’orientation."),
]

REACTION_BY_ID = {item["id"]: item for item in REACTIONS}
FAMILIES = list(dict.fromkeys(item["family"] for item in REACTIONS))
