"""Buts, grandeurs et parcours de raisonnement des 30 laboratoires."""


def guide(purpose, objects, assumptions, techniques, first_steps, sup, spe,
          beyond, lessons, expected):
    return dict(purpose=purpose, objects=objects, assumptions=assumptions,
                techniques=techniques, first_steps=first_steps,
                levels=dict(sup=sup, spe=spe, beyond=beyond),
                lesson_numbers=lessons, expected=expected)


LAB_GUIDES = {
    "electrons": guide(
        "Apprendre à lire une transformation par les électrons : identifier donneur et accepteur, construire une flèche licite et contrôler les charges. Les quatre familles font distinguer transfert de proton, substitution, homolyse et formes mésomères avant de mémoriser des noms de réaction.",
        ["Atomes, liaisons, doublets, charges formelles en unités de charge élémentaire e ; δ représente une charge partielle", "Étapes et flèches du schéma : une paire d’électrons pour une flèche pleine, un électron pour une demi-flèche"],
        ["Structures et étapes choisies pour expliciter le formalisme ; les noyaux restent fixes dans une mésomérie", "Les schémas sont une comptabilité de liaison, pas une trajectoire classique complète des électrons"],
        ["Comptage Lewis et octet", "Conservation des atomes et de la charge", "Différenciation hétérolyse/homolyse/mésomérie"],
        ["Repérer le site riche et le site pauvre en électrons avant d’afficher une étape ; prévoir la charge de chaque produit.", "Comparer les scénarios acido-basique, SN2, homolyse et mésomérie ; lire l’origine et la destination de chaque flèche.", "Redessiner les doublets et calculer la somme des charges après chaque étape ; expliquer pourquoi une mésomérie ne déplace pas les H."],
        "Lewis, charges et formalisme des mécanismes : tronc commun PCSI.", "Intermédiaires conjugués et justification électronique des transformations.", "Densités électroniques, méthodes quantiques et chemin réactionnel multidimensionnel.", [1,2,3,4],
        "Quatre transformations distinguées par une comptabilité exacte, avec des flèches justifiées plutôt que reproduites."),
    "acidebase": guide(
        "Relier un écart de pKa à un bilan de transformation et à la disponibilité d’une forme réactive. L’expérience force à distinguer la conversion de deux stocks finis, la composition d’un tampon et le rôle cinétique d’un nucléophile.",
        ["pKa d’un acide HA et de BH⁺, sans unité et dans le même solvant ; ratio initial base/acide b sans unité", "K sans unité ; avancement normalisé par le stock d’acide et fraction des espèces conjuguées"],
        ["Une seule réaction HA+B⇌A⁻+BH⁺, milieu homogène, activités assimilées à des concentrations", "Le pH d’un tampon n’est pas imposé dans le calcul d’avancement à deux stocks ; tables fournies dans un solvant cohérent"],
        ["Constante d’équilibre issue de deux Ka", "Bilan d’avancement et racine physique", "Distinction basicité/nucléophilie"],
        ["Prévoir le sens favorable pour ΔpKa positif, puis comparer stocks équimolaires et excès de base sans confondre K et conversion.", "Choisir un transfert favorable puis presque équilibré ; augmenter le ratio de base et relever la fraction convertie.", "Retrouver K=x²/[(1−x)(b−x)], vérifier 0≤x≤min(1,b) et expliquer pourquoi x=K/(1+K) ne vaut pas ici."],
        "Acido-basicité et réactivité : PCSI, avec données de solvant annoncées.", "Disponibilité d’énolates, protonation des amines et compatibilité des fonctions.", "Activités, effet de solvant et nivellement ; cinétique de transferts de proton.", [5,6],
        "Une conversion calculée par conservation de matière et une justification du rôle acide/base dans une synthèse."),
    "sn2": guide(
        "Vérifier la cinétique d’une réaction A+B→P tout en suivant l’inversion d’une attaque arrière. L’expérience relie le schéma moléculaire à des concentrations finies : le nom bimoléculaire ne dispense pas de choisir l’intégration adaptée aux stocks.",
        ["Concentrations de substrat et nucléophile en mol·L⁻¹, temps en s ; k₂ en L·mol⁻¹·s⁻¹", "Conversion et quantité de produit normalisées ; disposition tétraédrique et état de transition"],
        ["Réaction irréversible bimoléculaire unique à k₂ imposé, volume constant ; bilan A+B→P", "L’état de transition montré illustre le mécanisme ; l’inversion géométrique n’est pas une attribution CIP automatique universelle"],
        ["Loi de vitesse et intégration à deux stocks", "Contrôle dimensionnel et pseudo-premier ordre", "Inversion de Walden et accessibilité stérique"],
        ["Prévoir l’effet d’un doublement de Nu sur v₀ et tester si Nu peut vraiment être pris constant.", "Comparer stocks égaux et Nu en excès ; relever t₁/₂ et les concentrations finales sans consommer plus que le réactif limitant.", "Retrouver les lois d’intégration dans les cas égal/excès, puis expliquer pourquoi primaire, néopentyle et tertiaire ne sont pas équivalents pour une SN2."],
        "SN2, ordre 2 et stéréochimie : PCSI.", "Réactions concurrentes, paramètres d’activation et synthèse de Williamson.", "Recouvrement Nu/σ*, dynamique de solvatation et surfaces d’énergie.", [17,7,19],
        "Une inversion expliquée et une loi de concentration validée par ses hypothèses et son réactif limitant."),
    "sn1": guide(
        "Distinguer disparition du substrat, accumulation d’un intermédiaire et formation du produit dans une ionisation suivie d’un piégeage. La stéréochimie fait discuter le cas limite racémique et les effets d’un environnement qui différencie les faces.",
        ["k₁ d’ionisation et k₂ de capture apparent en s⁻¹ ; temps en s ; concentrations normalisées", "Fraction de capture sur une face paramétrée, sans unité ; elle illustre un biais et n’est pas une donnée universelle"],
        ["Schéma séquentiel irréversible RX→I→P, constantes imposées et bilan S+I+P constant", "Un cation libre symétriquement piégé est un cas limite ; paires d’ions et réarrangements réels demandent des données supplémentaires"],
        ["Système d’équations cinétiques séquentielles", "Étape déterminante et accumulation", "Perte de configuration et différence de faces"],
        ["Prévoir si I s’accumule lorsque k₂ devient beaucoup plus petit ou plus grand que k₁.", "Comparer capture rapide et lente ; observer séparément S, I et P puis faire varier le biais de face.", "Vérifier S+I+P=1, expliquer quand v≈k₁[S] décrit la disparition et pourquoi elle ne garantit pas une formation immédiate du produit."],
        "Ionisation SN1 et solvolyse en PCSI ; introduction accompagnée de l’intermédiaire.", "Étape déterminante, AEQS et réarrangements, approfondissements PC.", "Paires d’ions, participation de groupes voisins et stéréodynamique en solution.", [18,22],
        "Une courbe d’intermédiaire interprétée et une distinction entre mécanisme limite et racémisation exacte."),
    "competition": guide(
        "Décider entre substitution et élimination à partir de chemins compatibles, puis séparer conversion et sélectivité. L’expérience compare un embranchement commun après ionisation et les attaques bimoléculaires, sans compter deux fois le même départ lent.",
        ["Constantes et concentrations déclarées dans la simulation ; taux apparents des chemins en s⁻¹", "Stocks de réactifs et fractions de produits ; conversion et sélectivité affichées séparément"],
        ["Schéma de chemins parallèles avec une ionisation commune aux issues SN1/E1, puis capture répartie", "Paramètres choisis et réservoirs de Nu/base : les pourcentages ne prédisent pas tous les réactifs et solvants réels"],
        ["Addition et embranchement de flux", "Analyse substrate/Nu/base/solvant", "Bilan produit, conversion et récupération"],
        ["Avant le calcul, proposer les chemins accessibles pour un primaire peu encombré puis un tertiaire avec base forte.", "Faire varier la base et le nucléophile indépendamment ; relever conversion totale et fractions de substitution/élimination.", "Écrire le bilan de flux avec une seule ionisation, expliquer les chemins supprimés par la structure et calculer le rendement de produit depuis conversion×sélectivité."],
        "SN1/SN2/E2 et lecture de cinétique, réinvestissement PCSI.", "Modèle de compétition et effets des barrières, consolidation PC.", "Réseaux multietapes, retour du produit et modèles ajustés à des données expérimentales.", [19,17,18,20],
        "Un choix de mécanisme argumenté et trois nombres correctement distingués : conversion, sélectivité et rendement isolé."),
    "elimination": guide(
        "Construire les alcènes à partir des Hβ réellement disponibles et de leur géométrie. Le cas cyclohexanique montre pourquoi le produit de stabilité maximale peut être absent lorsque le H anti-périplanaire est empêché.",
        ["Angle dièdre et conformation ; disponibilité des Hβ, classe du substrat et nature de la base", "Rapports de voies ou niveaux paramétrés ; configurations E/Z attribuées seulement si elles existent"],
        ["E2 concertée avec disposition anti dans les scénarios standards ; E1 présenté comme schéma distinct", "Les proportions illustratives suivent les paramètres affichés ; trans-diaxial impose une contrainte de structure avant les tendances Zaitsev/Hofmann"],
        ["Projection de Newman ou chaise", "Flèches concertées et Hβ", "Classement de connectivités et E/Z"],
        ["Énumérer tous les Cβ puis dessiner au moins une conformation anti pour chacun avant d’invoquer Zaitsev.", "Comparer petite base et base encombrée ; ouvrir le cas trans-1-bromo-2-méthylcyclohexane et basculer la chaise.", "Expliquer le produit moins substitué lorsque le site axial de C2 est occupé par CH₃ ; distinguer contrainte géométrique et stabilité des produits."],
        "β-élimination E2 et mécanisme : PCSI.", "Conformations réactives, E1/E2 et contrôle de stéréochimie.", "Effets isotopiques cinétiques et éliminations syn contraintes.", [20,21,10],
        "Une liste d’alcènes construite depuis les liaisons et les H, accompagnée des voies réellement autorisées."),
    "alcene": guide(
        "Comparer trois dimensions d’une transformation d’alcène : orientation, stéréochimie et rôle des conditions. Les voies ioniques, bromonium et hydroboration donnent des produits différents sans que la seule règle de Markovnikov suffise à les construire.",
        ["Substrats choisis : propène, E/Z-but-2-ène et alcène pouvant réarranger ; fonctions et centres créés", "Conditions de la banque, faces d’attaque et disposition syn/anti ; aucun rendement universel associé au seul nom de réaction"],
        ["Chaque transformation suit le mécanisme annoncé : carbocation, pont bromonium ou addition concertée", "Les faces sont équivalentes dans un milieu achiral sauf influence indiquée ; règles d’orientation discutées avec réarrangements éventuels"],
        ["Suivi des atomes dans une addition", "Orientation et intermédiaire", "Conservation ou création de stéréochimie"],
        ["Prévoir propan-1-ol ou propan-2-ol suivant les conditions, puis dessiner les produits de bromation des deux but-2-ènes.", "Comparer hydratation acide, HBr ionique, hydroboration/oxydation et bromation ; observer les nouvelles liaisons et les faces.", "Justifier chaque orientation par son chemin ; expliquer la différence entre H/OH syn et deux OH syn, puis reconnaître méso ou paire d’énantiomères."],
        "Nucléophile/électrophile, stéréochimie et lecture d’une banque en Sup.", "Réactivité des alcènes, orientation et stéréospécificité : parcours PC.", "Catalyse énantiosélective et mécanismes d’addition plus fins.", [23,8],
        "Quatre voies d’addition distinguées par conditions, connectivité et résultat stéréochimique."),
    "alcyne": guide(
        "Apprendre à arrêter une transformation au bon degré d’insaturation et à suivre un énol jusqu’au carbonyle final. Les comparaisons Lindlar/métal dissous/réduction totale font comprendre le rôle du catalyseur et du bilan d’hydrogène.",
        ["Alcyne terminal ou interne et équivalents réactifs ; nombre d’unités d’insaturation", "Alcène E/Z si défini, énol intermédiaire, aldéhyde ou cétone finale"],
        ["Transformations de banque avec conditions spécifiques, sans extrapolation d’un catalyseur à toutes les réductions", "La tautomérie est un changement d’espèce avec transfert de H ; les conditions sont fournies pour les extensions"],
        ["Comptage des additions", "Stéréochimie syn/anti", "Tautomérie et suivi du C terminal"],
        ["Prévoir les produits de but-2-yne sous trois conditions de réduction ; compter les H ajoutés.", "Comparer Lindlar, métal dissous et réduction totale ; suivre l’hydratation du prop-1-yne puis son hydroboration/oxydation.", "Redessiner chaque énol avant sa tautomérie et expliquer pourquoi un équivalent global de H₂ sans catalyseur ne garantit pas un alcène pur."],
        "Insaturation et bilan ; transformations accompagnées à partir d’une banque.", "Réactivité des alcynes du recueil et choix de conditions : PC.", "Acétylures en synthèse, couplages et catalyse sélective.", [25,11],
        "Une fonction finale correctement identifiée et une stratégie d’arrêt au stade alcène justifiée."),
    "radical": guide(
        "Construire une chaîne qui régénère un radical, puis relier initiation, propagation et terminaison à une loi cinétique. HBr radicalaire sert à expliquer une orientation différente sans introduire un carbocation caché.",
        ["Vitesse d’initiation en mol·L⁻¹·s⁻¹ et constante de terminaison en L·mol⁻¹·s⁻¹ ; sélectivité relative par site sans unité", "Concentration radicalaire stationnaire et enthalpies de propagation estimées en kJ·mol⁻¹ ; électrons célibataires et demi-flèches"],
        ["Initiateur et conditions adaptés explicitement requis ; chaîne simplifiée avec terminaison choisie", "Un régime quasi stationnaire est une approximation après l’initiation ; HCl/HI ne sont pas assimilés automatiquement à HBr"],
        ["Annulation des intermédiaires dans un bilan", "Demi-flèches et stabilité radicalaire", "AEQS et dépendance en racine carrée"],
        ["Écrire les deux propagations de HBr sur propène et prévoir le radical le plus stabilisé.", "Modifier initiation et terminaison ; relever la concentration stationnaire. En halogénation, comparer la sélectivité par site à celle corrigée par le nombre de H.", "Vérifier que le radical se régénère dans la propagation et disparaît en terminaison ; retrouver la loi √Ri dans les conditions stationnaires."],
        "Homolyse, radical et bilan de matière, entrée accompagnée.", "Mécanismes de chaîne et réactivité comparée : approfondissement PC avec données fournies.", "Polymérisation radicalaire, inhibiteurs et réactions photochimiques.", [24,2],
        "Une chaîne fermée au bilan et un effet de l’initiation expliqué par le mécanisme de terminaison."),
    "carbonyle": guide(
        "Identifier ce qui arrive après une attaque du carbonyle : alcoolate d’addition, départ d’un groupe, protection, énolate ou construction de C=C. La banque de familles aide à choisir le bon mécanisme pour la fonction plutôt qu’à traiter tous les C=O de la même façon.",
        ["Famille de carbonyle et nucléophile : charges, fonction voisine, groupe éliminable", "Étapes de la banque et produits après traitement ; nouvelle liaison et fonction conservée ou transformée"],
        ["Mécanismes et conditions fournis par famille ; les scénarios ne simulent pas toutes les polyfonctionnalités", "Addition à aldéhyde/cétone et substitution d’acyle sont des bilans distincts ; la protonation finale est indiquée"],
        ["Polarisation C=O et attaque", "Intermédiaire tétraédrique et départ", "Comparaison de fonctions et compatibilité"],
        ["Pour une cétone puis un ester, dessiner l’attaque et demander si un groupe peut quitter l’intermédiaire.", "Comparer les familles proposées, dont acétal, aldol et Wittig ; suivre les atomes plutôt que le seul nom.", "Écrire le bilan de la famille choisie, restaurer charges/doublets et expliquer pourquoi une cétone formée par Grignard sur ester réagit encore."],
        "Addition nucléophile aux aldéhydes/cétones : PCSI.", "Dérivés d’acide, énolates et création C−C : PC.", "Sélectivité faciale, catalyse et paramètres quantiques de réactivité.", [26,31,33,34,35],
        "Un mécanisme sélectionné à partir de la fonction et un produit suivi jusqu’au traitement final."),
    "grignard": guide(
        "Créer un squelette C−C tout en comptant les consommations concurrentes. Le laboratoire met au premier plan l’anhydrie, les H labiles, les équivalents d’ester et le traitement aqueux final ; les quantités calculées sont des bornes stœchiométriques.",
        ["Quantités d’électrophile, de RMgX et de protons labiles en mmol ; équivalents sans unité", "Classe d’alcool et nombre de C de la cible ; quantité maximale après consommation protique"],
        ["RMgX représente une espèce organométallique solvatée ; équivalents et incompatibilités fournis", "Une borne de matière ne donne ni rendement réel ni composition garantie d’un mélange d’ester sous-stœchiométrique"],
        ["Addition carbonylée et hydrolyse", "Bilan d’équivalents et réactif limitant", "Coupure rétrosynthétique et comptage C"],
        ["Prévoir primaire/secondaire/tertiaire selon méthanal, aldéhyde ou cétone, puis compter les deux additions sur ester.", "Introduire des protons labiles à quantité fixée de RMgX ; comparer l’ester, CO₂ et l’oxirane.", "Calculer le réactif réellement disponible, vérifier les C et justifier l’ordre milieu anhydre→addition→hydrolyse."],
        "Synthèse magnésienne et compatibilités : tronc commun PCSI.", "Esters, époxydes et polyfonctionnalité, prolongements fournis PC.", "Agrégation organométallique, échange métal/halogène et couplages.", [27,28,5],
        "Une cible C−C obtenue depuis un bilan d’atomes et d’équivalents, avec incompatibilités explicitement traitées."),
    "oxydoreduction": guide(
        "Relier le niveau d’oxydation d’un carbone aux fonctions transformées et choisir une chimiosélectivité. Les alcools, carbonyles et groupe nitro illustrent une même comptabilité électronique avec des mécanismes et réactifs différents.",
        ["Fonctions du substrat, nombres d’oxydation et électrons de demi-équation", "Conditions réelles de la banque, fonctions conservées et signatures IR/RMN attendues"],
        ["Sélectivités attachées aux conditions fournies ; aucun réducteur universel pour toute molécule", "L’inertie d’un tertiaire concerne l’oxydation douce en carbonyle à squelette conservé, pas toute rupture oxydante forte"],
        ["Demi-équations et bilan d’électrons", "Choix de réactif chimiosélectif", "Validation par plusieurs spectroscopies"],
        ["Prévoir les niveaux accessibles depuis un alcool primaire, secondaire puis tertiaire sans casser C−C.", "Comparer les réductions usuelles NaBH₄ et LiAlH₄ en présence de cétone/ester ; ouvrir la réduction nitro→amine.", "Équilibrer les protons/eau/électrons, vérifier les fonctions préservées et proposer une donnée spectrale qui réfute un produit concurrent."],
        "Niveaux d’oxydation, NaBH₄ et alcools : PCSI option PC.", "Choix de conditions et chimiosélectivité multietapes : PC.", "Oxydations catalytiques, réductions énantiosélectives et électrosynthèse.", [29,12,13],
        "Une demi-équation équilibrée et une sélection de réactif validable expérimentalement."),
    "aromatique": guide(
        "Lire séparément l’activation d’un noyau et l’orientation de sa substitution. Les chemins ortho/méta/para puis les routes ordonnées montrent comment choisir les étapes sans déduire leur vitesse de simples moments dipolaires.",
        ["Substituant, caractère inductif/mésomère et positions du noyau ; nombre de sites équivalents", "Barrières déclarées en kJ·mol⁻¹ et température en K ; fractions de voies issues du modèle cinétique"],
        ["SEA par intermédiaire σ et restauration aromatique ; barrières de démonstration et multiplicité des sites", "Les dipôles caractérisent une structure mais ne servent pas à prédire les proportions ; Friedel–Crafts exclue sur NO₂ fortement désactivant dans les conditions usuelles"],
        ["Mésomérie du complexe de Wheland", "Multiplicité et comparaison de barrières", "Ordre de synthèse et changement de directeurs"],
        ["Prévoir les orientations pour OMe, NO₂ et Br, en distinguant direction et activation globale.", "Comparer les barrières et les multiplicités ortho/méta/para ; examiner acylation avant puis après nitration.", "Justifier les voies par les complexes σ et les conditions ; montrer pourquoi un calcul de dipôle ne remplace pas un modèle de vitesse."],
        "Conjugaison et effets électroniques comme prérequis PCSI ; banque accompagnée.", "SEA, directeurs et stratégies aromatiques : PC avec transformations précisées.", "Effets de substituants quantifiés, Hammett et calcul des états de transition.", [36,4,22],
        "Une orientation argumentée et une route ordonnée dont chaque étape reste réactive."),
    "orbitales": guide(
        "Faire le lien entre l’algèbre linéaire et la réactivité : normaliser une CLOA, remplir les niveaux puis lire phases et coefficients d’une HO/BV. Le modèle de Hückel donne des calculs contrôlables plutôt qu’une règle visuelle sans hypothèses.",
        ["Recouvrement S sans unité, α et β en eV ; matrice d’adjacence et énergie des niveaux", "Coefficients orbitaux signés, occupation électronique et densité de site ; écart HO/BV en eV"],
        ["CLOA et Hückel sont deux approximations annoncées ; Hückel prend un recouvrement nul dans sa base", "La phase globale ne change pas la densité ; remplissage égal des niveaux dégénérés quand indiqué ; pas de rendement synthétique prédit"],
        ["Normalisation d’une combinaison", "Diagonalisation et remplissage", "Recouvrement et coefficients terminaux"],
        ["Pour S non nul, prévoir pourquoi √2 ne normalise plus les deux combinaisons ; compter les électrons π.", "Faire varier le recouvrement, puis comparer chaînes et cycles Hückel ; relever HO/BV et coefficients de site.", "Vérifier c†Sc=1 ou l’orthonormalité Hückel, conserver le nombre d’électrons et expliquer le rôle des phases relatives dans une interaction."],
        "Lewis/conjugaison, avec introduction accompagnée de l’outil mathématique.", "CLOA, orbitales frontières et applications de réactivité PC selon le cadre fourni.", "Méthodes quantiques avec recouvrement, corrélation et calcul de barrières.", [37,38,39],
        "Une combinaison normalisée, des niveaux remplis correctement et une interprétation qualitative sans surpromesse du modèle."),
    "cinetique": guide(
        "Comprendre pourquoi le produit formé le plus vite peut ne pas être le plus stable. Les courbes séparent évolution irréversible, comparaison des barrières et comparaison thermodynamique, afin de choisir une expérience qui peut distinguer les deux contrôles.",
        ["ΔH‡ en kJ·mol⁻¹, ΔS‡ en J·mol⁻¹·K⁻¹ et température en K ; ΔG‡=ΔH‡−TΔS‡ avec conversion d’unité", "Énergies G des produits en kJ·mol⁻¹, temps en s et coordonnée réactionnelle sans unité distincte du temps ; rapports de voies"],
        ["Préfacteurs et barrières imposés dans la comparaison ; Eyring est un prolongement explicité", "Le comparatif d’équilibre ne rend pas réversible l’intégration irréversible ; l’interconversion doit exister pour atteindre la composition thermodynamique"],
        ["Exponentielles et rapports de constantes", "Lecture maximum/minimum de profil", "Conception d’un test temps/température"],
        ["Prévoir quelle barrière donne le produit initial majoritaire et quel minimum donne l’équilibre préféré.", "Varier température et différence de barrières ; observer l’évolution puis la comparaison indépendante d’équilibre.", "Calculer les deux rapports, vérifier les unités RT et définir les conditions nécessaires pour passer du contrôle cinétique au thermodynamique."],
        "Loi d’Arrhenius, catalyse et mécanismes : PCSI option PC.", "Contrôles cinétique/thermodynamique et intermédiaires : PC.", "Eyring, réseaux réversibles et méthodes d’ajustement de cinétiques.", [22,19],
        "Deux compositions reliées à deux hypothèses distinctes, accompagnées d’un protocole permettant de les tester."),
    "formule": guide(
        "Commencer une identification par un bilan d’atomes, de masse et d’insaturation. Les signatures isotopiques de Cl/Br montrent qu’une formule fournit des contraintes solides sans déterminer à elle seule la connectivité.",
        ["Nombres entiers d’atomes C,H,N,O et halogènes ; IHD sans unité", "Masse moyenne molaire en g·mol⁻¹, masse monoisotopique et enveloppe isotopique ; m/z dépend du type d’ion"],
        ["Formules neutres usuelles et valences annoncées pour IHD ; domaine entier vérifié", "Enveloppe halogène simplifiée et séparée des fragmentations ; pas d’attribution d’ionisation universelle"],
        ["Indice d’insaturation et valences", "Masse moyenne/masse exacte/ion", "Polynômes isotopiques et contraintes structurelles"],
        ["Calculer IHD de C₈H₈O₂ et proposer au moins deux structures compatibles avant de regarder les autres données.", "Ajouter un puis deux Cl ou Br ; lire les enveloppes M/M+2/M+4 et comparer masses moyenne/exacte.", "Démontrer les rapports par développement binomial, identifier quel ion serait mesuré et expliquer pourquoi IR/RMN restent nécessaires."],
        "Formule, valences et insaturation ; complément analytique accompagné en PCSI.", "Résolution de structures et lecture de masse avec données fournies, PC.", "Haute résolution, isotopes multiples et fragmentation mécanistique.", [11,14],
        "Une formule contrôlée et une liste de connectivités candidates compatible avec toutes ses contraintes."),
    "stereo": guide(
        "Construire les priorités CIP d’un cas lisible puis relier composition d’énantiomères et polarimétrie. La manipulation vise à conserver une configuration sous rotation du dessin et à reconnaître les conditions d’une attribution fiable.",
        ["Acide lactique : substituants explicitement classés OH>CO₂H>CH₃>H ; configuration et miroir", "Proportions R/S et ee ; rotation spécifique [α]R en °·mL·g⁻¹·dm⁻¹, tube ℓ en dm, concentration c en g/mL ; rotation observée α en degrés"],
        ["Un seul couple d’énantiomères, milieu et concentrations comparables ; réponse de polarimétrie linéaire", "Le cas CIP est fourni et ne constitue pas un moteur général d’assignation ; le signe optique n’est pas déduit de R/S"],
        ["Priorités CIP et vue 4 à l’arrière", "Miroir/superposition et symétrie", "Calcul d’ee et contrôle de polarimétrie"],
        ["Classer CO₂H et CH₃ au premier rang différent et attribuer la configuration avant de tourner le modèle.", "Comparer l’image miroir, un mélange racémique et un mélange 80/20 ; modifier [α]R, tube et concentration.", "Vérifier ee=|xR−xS| et α=[α]Rℓc(xR−xS), justifier R/S indépendamment du signe et nommer les conditions nécessaires à la quantification."],
        "Stéréoisomérie et CIP : PCSI.", "Stéréosélectivité de synthèse et caractérisation d’ee.", "Séparation chirale, rotations calculées et catalyse asymétrique.", [7,8],
        "Une configuration attribuée par une règle, puis un ee calculé sans assimilation R=+."),
    "conformeres": guide(
        "Passer d’un dessin de Newman ou d’une chaise à des populations thermiques. Le butane et le méthylcyclohexane font expliciter minima, dégénérescence, stabilité et vitesse d’échange plutôt que confondre conformère le plus stable et produit nécessairement majoritaire.",
        ["Angle dièdre en degrés ; énergie ou différence de G en kJ·mol⁻¹, température en K", "Anti/gauche du butane, chaise axiale/équatoriale ; probabilités sans unité et barrières indicatives"],
        ["Profil périodique de torsion interpolé entre niveaux annoncés, et population discrète des minima traitée séparément", "Deux minima gauche comptés ; deux chaises de même dégénérescence ; la barrière ne détermine pas le ratio d’équilibre"],
        ["Projections et rotation autour de σ", "Poids de Boltzmann et dégénérescence", "Basculement axial/équatorial sans changement cis/trans"],
        ["Placer anti/gauche/éclipsé, compter les deux minima gauche et prévoir quelle chaise est préférée.", "Faire varier la température pour butane, dont le coût gauche est fixé à 3,8 kJ·mol⁻¹ ; pour le méthylcyclohexane, changer aussi le coût axial. Lire profil et populations.", "Retrouver la normalisation des poids, conserver haut/bas après basculement et distinguer population, barrière d’échange et vitesse de réaction."],
        "Conformation Newman/chaise : PCSI ; populations introduites avec la formule.", "Conformations réactives, E2 trans-diaxiale et contrôle de synthèse.", "Curtin–Hammett, mécanique moléculaire et intégration de distributions continues.", [9,10,20],
        "Une population qui tient compte de la dégénérescence et une chaise correctement basculée."),
    "ir": guide(
        "Identifier des groupes caractéristiques tout en comprenant le lien vibration/absorption. Les courbes calculées servent à distinguer absorbance additive, transmittance non additive et signatures fonctionnelles, puis à formuler une caractérisation réfutable.",
        ["Nombre d’onde en cm⁻¹, largeur et position des bandes simulées ; concentration et trajet selon l’échelle du modèle", "Absorbance A sans unité et transmittance en % ; molécules choisies et hypothèses de bandes typiques"],
        ["Bandes gaussiennes pédagogiques, pas une reproduction de spectre NIST mesuré", "Beer–Lambert dans son domaine déclaré ; environnement, couplages et liaisons hydrogène peuvent modifier un spectre réel"],
        ["Oscillateur harmonique et masse réduite", "Transformation A↔T", "Diagnostic fonctionnel croisé avec RMN"],
        ["Prévoir les différences entre éthanol, propanone, acide et ester avant d’ouvrir leurs courbes.", "Comparer les molécules et doubler concentration/épaisseur ; observer ce qui double et ce qui ne double pas.", "Justifier les bandes, expliquer les absences et calculer T=10⁻ᴬ ; compléter le diagnostic par une autre donnée plutôt que par une seule bande OH."],
        "IR et interprétation spectrale : PCSI option PC.", "Suivi de sélectivité et problèmes multitechnniques de PC.", "Modes normaux couplés, isotopes et spectres quantitatifs expérimentaux.", [12,14,29],
        "Un diagnostic de fonctions, des unités correctes et une distinction nette entre spectre calculé et référence mesurée."),
    "rmn": guide(
        "Résoudre des connectivités à partir de δ, J et intégrales, puis vérifier quand le premier ordre est fiable. Le groupe éthyle, les singulets et les environnements ¹³C forment des problèmes d’assemblage de fragments plutôt que de reconnaissance visuelle de pics.",
        ["δ en ppm ; J en Hz ; fréquence du spectromètre en MHz ; intégrales associées à un nombre d’H", "Environnements ¹³C découplés et dégénérescences ; paquets aromatiques explicitement approximatifs"],
        ["Simulation de multiplets du premier ordre : Δν/J doit être grand ; aromaticité non résolue en système complet AA′BB′", "OH/NH échangeables modélisés simplement ; spectre ¹³C découplé non réputé quantitatif par ses hauteurs"],
        ["Assemblage intégrale/déplacement/couplage", "Règle n+1 et coefficients binomiaux", "Contrôle Δν/J et environnements équivalents"],
        ["Prévoir les trois signaux de l’éthanoate d’éthyle et les distinguer d’un propanoate de méthyle.", "Comparer les sept molécules, changer la fréquence et élargir les raies ; lire intégrales et même J du groupe éthyle.", "Convertir J en ppm, vérifier Δν/J et expliquer pourquoi des énantiomères en milieu achiral ou des multiplets superposés ne suffisent pas toujours à une identité unique."],
        "RMN ¹H et couplages premier ordre : PCSI option PC.", "Analyse de mélanges et structure combinée en PC ; ¹³C fourni comme complément.", "Couplages forts, RMN bidimensionnelle et environnements chiraux.", [13,14],
        "Une structure justifiée par toutes les données, avec diagnostic explicite du domaine premier ordre."),
    "ccm": guide(
        "Choisir une séparation exploitable et un suivi de réaction. La plaque simulée relie force éluante, rétention et largeur des taches pour apprendre à décider quand une CCM informe réellement le TP.",
        ["Distance du dépôt, des taches et du front ; Rf sans unité ; proportions de l’éluant", "Largeur et centres des taches ; réponse de rétention paramétrée pour la silice en phase normale"],
        ["Modèle pédagogique de rétention et d’étalement, pas calcul universel de toutes les molécules sur silice", "L’intensité de révélation et un Rf ne mesurent pas seuls une quantité ou une identité absolue"],
        ["Rapport de distances et séparation", "Choix de force éluante", "Prélèvement et comparaison à référence/co-tache"],
        ["Prévoir si un éluant trop faible ou trop fort sépare mieux deux espèces proches ; distinguer ΔRf et largeurs.", "Faire varier l’éluant puis observer le dépôt, le front et les taches ; comparer le suivi aux références.", "Calculer les Rf depuis le même zéro, sélectionner un éluant argumenté et expliquer ce qu’une disparition de tache prouve ou ne quantifie pas."],
        "CCM, observation et suivi : techniques expérimentales PCSI.", "Sélection de purification et validation d’une séquence de PC.", "Chromatographie sur colonne, HPLC et quantification étalonnée.", [15,41],
        "Un choix d’éluant motivé par la résolution et un compte rendu de suivi sans faux rendement visuel."),
    "extraction": guide(
        "Choisir le nombre de contacts et le pH pour isoler une espèce. Le bilan distingue partage de la forme neutre et distribution totale, puis compare un seul grand contact à plusieurs volumes de solvant neuf.",
        ["P de la forme neutre et D total sans unité ; pKa et pH d’un milieu maintenu", "Volumes aqueux/organiques en mL ; nombre entier d’extractions et fractions récupérées"],
        ["Équilibre atteint à chaque contact, phases de volumes constants et solvant neuf", "Espèce ionisée supposée aqueuse ; pH tamponné imposé, ni émulsion ni consommation du tampon ni dégradation dans le modèle"],
        ["Conservation de quantité entre deux phases", "Henderson–Hasselbalch et partition", "Optimisation de contacts à volume total fixé"],
        ["Prévoir l’effet du pH sur acide puis amine et comparer une extraction de 100 mL à deux de 50 mL.", "Faire varier nombre de contacts et pH ; relever D et masse restant dans l’eau.", "Démontrer la fraction résiduelle, vérifier la conservation et nommer ce qui changerait si le tampon ou la séparation de phases devenait insuffisant."],
        "Ampoule à décanter et partage : TP PCSI.", "Séparations acido-basiques et bilans couplés dans une synthèse PC.", "Transfert de matière, solvants mutuellement solubles et procédés continus.", [16,5,41],
        "Une récupération prédite sous hypothèses et une sélection du pH fondée sur la forme chimique."),
    "esterification": guide(
        "Retrouver les leviers d’un TP d’ester : excès de réactif, eau initiale et équilibre. Le passage à la saponification fait distinguer une transformation réversible catalysée et un bilan basique pratiquement complet dans le modèle choisi.",
        ["Stocks de réactifs, ester et eau ; avancement et K sans unité pour le mélange homogène idéal", "Mode estérification/hydrolyse/saponification ; proportions et réactif limitant"],
        ["Activités simplifiées du mélange homogène ; le modèle d’eau réactif n’est pas celui d’un solvant aqueux majoritaire", "Saponification modélisée stœchiométriquement complète pour le limitant ; la cinétique du reflux n’est pas une constante d’équilibre"],
        ["Tableau d’avancement et K", "Déplacement par excès ou eau", "Distinction carboxylate/acide et traitement final"],
        ["Pour K=4 et stocks 1/1 sans produit initial, calculer x puis prévoir l’effet d’un excès d’alcool.", "Comparer estérification, hydrolyse avec eau initiale et saponification ; relever les quantités de chaque forme.", "Choisir la racine physique, vérifier tous les stocks et expliquer pourquoi catalyse accélère sans changer K, puis pourquoi acidifier un carboxylate est une étape supplémentaire."],
        "Équilibre et techniques de synthèse : PCSI.", "Substitution d’acyle, équilibres et optimisation des conditions : PC.", "Activités non idéales, séparation réactive et catalyse enzymatique.", [30,5,41],
        "Un avancement contrôlé et une interprétation distincte des trois bilans ester/acide/carboxylate."),
    "acylation": guide(
        "Construire une amide en comptant à la fois l’attaque et le piégeage de l’acidité libérée. La comparaison chlorure/anhydride et amine/base rappelle qu’un équivalent peut avoir un rôle de neutralisation sans être incorporé à la cible.",
        ["Stocks d’amine et de base en équivalents par rapport à l’acyle de référence ; chlorure, anhydride ou acide non activé", "Produit théorique, sel ammonium ou acidité résiduelle ; intermédiaire tétraédrique et sous-produit"],
        ["Bilan choisi avec réactivité et base adaptées ; chlorure libère un équivalent acide à piéger", "Les bornes sont stœchiométriques et ne remplacent pas les équilibres, la solubilité et le rendement isolé"],
        ["Addition–élimination d’acyle", "Rôle nucléophile/base de l’amine", "Activation et comptage des équivalents"],
        ["Prévoir combien d’équivalents d’amine servent à la cible puis au piégeage de HCl sans base externe.", "Comparer chlorure et anhydride, ajouter une base séparée et lire le limitant avec des stocks identiques.", "Écrire l’équation équilibrée et expliquer pourquoi acide+amine peut donner un sel avant l’amide, puis proposer une caractérisation de N-acylation."],
        "Activation de fonction et transfert de doublets, prérequis PCSI.", "Dérivés d’acides et substitutions d’acyle : PC.", "Couplage peptidique, agents activants et catalyse d’acylation.", [31,32,6],
        "Une quantité théorique qui respecte la neutralisation et un mécanisme où le groupe partant est identifié."),
    "protection": guide(
        "Évaluer une protection depuis les fonctions à préserver, les conditions à traverser et son coût global. Les séquences comparent un carbonyle masqué avant réduction, une déprotection trop précoce et un OH libre ou protégé avant l’étape organomagnésienne.",
        ["Fonctions présentes et ordre des opérations ; stabilité de l’acétal dans la banque", "Rendements déclarés par opération et rendement global ; étapes de traitement/protection/déprotection"],
        ["Protection sélective fournie pour le cas étudié ; sa possibilité n’est pas généralisée à tous les dicarbonyles", "Compatibilité évaluée avec fonction et milieu ; les rendements sont des données de scénario, pas des prédictions ab initio"],
        ["Matrice fonction/réactif/milieu", "Ordre de synthèse et isolement", "Produit des rendements et alternative compatible"],
        ["Repérer ce qui réagirait avec l’étape visée ; choisir un acétal pour préserver C=O ou le groupe fourni pour masquer OH.", "Comparer les séquences correcte, sans protection et déprotégée trop tôt ; lire séparément les routes OH libre/organomagnésien et OH protégé.", "Justifier chaque opération, vérifier la récupération de la fonction et calculer le rendement global. Les traitements anhydres et aqueux nécessaires sont explicités dans le cours."],
        "Protection/déprotection et stratégie : PCSI option PC.", "Polyfonctionnalité et sélectivité des routes de PC.", "Orthogonalité de protections et synthèses totales.", [33,27,40],
        "Une séquence complète compatible et un coût de protection évalué sans compter seulement les étapes."),
    "aldol": guide(
        "Former une liaison C−C en choisissant quel partenaire fournit l’énolate. La chalcone donne un cas emblématique où l’absence d’Hα du benzaldéhyde simplifie une réaction croisée ; l’aldol et le produit crotonisé restent clairement distincts.",
        ["Carbonyles donneur/accepteur et présence d’Hα ; mode de préparation de l’énolate et étape observée", "β-hydroxycarbonyle, liaison C−C nouvelle, eau de crotonisation et carbonyle α,β-insaturé"],
        ["Choix de donneur et banque de conditions explicités ; sélectivité croisée ne suit pas automatiquement de deux carbonyles mélangés", "L’orientation E fréquente après déshydratation n’est pas un rendement ou un ratio universel"],
        ["Énolate et sites α/β", "Suivi de la liaison C−C", "Distinction aldolisation/condensation complète"],
        ["Identifier Hα sur acétophénone et leur absence sur benzaldéhyde ; dessiner le β-hydroxyproduit.", "Comparer aldol croisé et partenaires énolisables ; déclencher ou omettre la crotonisation.", "Suivre chaque C et O, compter l’eau du bilan condensé et expliquer les auto/croisements possibles si les deux partenaires donnent un énolate."],
        "Mésomérie et nucléophile comme prérequis Sup ; réaction fournie pour l’entrée.", "Énolates, aldolisation et stratégie C−C : PC.", "Aldols énantiosélectives, modèles de transition et aldols intramoléculaires.", [34,4],
        "Un donneur/accepteur choisi et deux produits distincts pour l’addition puis la déshydratation."),
    "michaelwittig": guide(
        "Comparer deux façons de construire C−C : ajouter à une énone en 1,2/1,4 ou remplacer l’oxygène d’un carbonyle par le C d’un ylure. Les produits servent à choisir une disconnexion plutôt qu’à mémoriser le même mot addition pour toutes les fonctions.",
        ["Accepteur conjugué, type de nucléophile et carbone attaqué ; carbonyle ou alcène restant", "Ylures CHCH₃ non stabilisé et CHCO₂Et stabilisé ; substituants de C=C et tendances E/Z qualitatives, sans ratio chiffré"],
        ["Préférences 1,2/1,4 et E/Z rattachées aux conditions du scénario", "Une tendance d’ylure stabilisé/non stabilisé ne fournit pas une composition universelle ; Ph₃P=O figure dans le bilan"],
        ["Repérage de sites 1 et 4", "Conservation du C introduit et O éliminé", "Sélectivité et coupure rétrosynthétique"],
        ["Dessiner les produits 1,2 et 1,4 d’une énone avant de choisir le donneur ; vérifier où reste C=O.", "Comparer Michael et Wittig puis sélectionner les ylures non stabilisé CHCH₃ et stabilisé CHCO₂Et proposés.", "Écrire le sous-produit phosphine-oxyde, décider si E/Z existe et proposer IR/RMN pour distinguer addition allylique et conjuguée. Le cas méthylène est un exercice complémentaire du cours."],
        "Nucléophile et carbonyle, avec une banque accompagnée.", "Michael, Wittig et choix des constructions C−C : PC selon transformations fournies.", "Annulations, ylures spécialisés et mécanismes de sélectivité avancés.", [35,26,34],
        "Une connectivité cible obtenue par la bonne famille, avec bilan d’atomes et limites de sélectivité."),
    "dielsalder": guide(
        "Construire un cycle en conservant la géométrie des partenaires, puis séparer préférence endo cinétique et stabilité exo éventuelle. L’exemple bicyclique associe stéréospécificité, s-cis et interactions orbitalaires à un bilan de six centres.",
        ["Diène et diénophile, disposition s-cis/s-trans, géométrie cis/trans des substituants", "Différence de barrières et de stabilités en kJ·mol⁻¹, température en K ; comparatifs endo/exo"],
        ["Cycloaddition concertée [4+2] dans les scénarios fournis ; diène bloqué s-trans interdit dans ce chemin", "Rapport endo/exo de produits appliqué au cas bicyclique cis seulement ; fumarate trans garde un ester endo et l’autre exo. Comparaisons cinétique et thermodynamique indépendantes."],
        ["Numérotation de six centres", "Conservation stéréochimique et pont", "Rapports exponentiels de deux modèles"],
        ["Dessiner les deux liaisons σ nouvelles et la liaison π résiduelle ; prévoir la relation des substituants du maléate puis fumarate.", "Comparer s-cis et s-trans ; dans le cas cyclopentadiène+maléate cis, faire varier les différences d’énergie endo/exo.", "Conserver cis/trans du diénophile, calculer chaque rapport applicable avec RT et expliquer quand une rétro-réaction est nécessaire pour observer l’équilibre."],
        "Conformation/stéréochimie comme prérequis Sup ; cycloaddition introduite par sa banque.", "Diels–Alder et lecture HO/BV : PC.", "Catalyse asymétrique, demande électronique inverse et synthèses bicycliques.", [39,38,22],
        "Un adduit correctement connecté et deux préférences conditionnelles distinctes, sans règle endo absolue."),
    "retrosynthese": guide(
        "Choisir des coupures, reconstruire chaque route dans le sens direct et comparer une livraison de produit pur. Aspirine, paracétamol, chalcone et routes C−C/aromatiques font mobiliser compatibilités, ordre et indicateurs de matière.",
        ["Cible, précurseurs et banques de réaction ; étapes et rendements isolés déclarés en %", "Quantité de référence en mmol, nombre d’opérations et quantité obtenue ; l’économie d’atomes et le PMI sont étudiés dans le cours complémentaire"],
        ["Routes définies et compatibles à vérifier ; rendements fournis, sans prédiction universelle de synthèse", "Rendements isolés multipliés sur une séquence ; le calcul de PMI/E-factor demande les données de masse supplémentaires fournies dans les exercices"],
        ["Disconnexion et équivalent synthétique", "Reconstruction directe et ordre des fonctions", "Réactif limitant, pureté et bilan global"],
        ["Choisir une cible et proposer une coupure au niveau de la fonction construite ; lister les fonctions qu’elle doit épargner.", "Comparer routes courtes et plus longues, dont acylation aromatique avant nitration ; modifier le rendement par opération et la quantité de référence.", "Valider les étapes dans le sens direct, calculer le produit des rendements puis demander quelles mesures prouvent identité, pureté et quantité."],
        "Analyse de stratégie et TP : PCSI option PC.", "Rétrosynthèse multietapes, chimiosélectivité et évaluation de route : PC.", "Synthèse totale convergente, procédés et optimisation multicritère.", [40,41,36,33],
        "Une route défendable par ses transformations et un bilan livré de produit pur."),
    "polymeres": guide(
        "Comprendre pourquoi une conversion de fonction très élevée et une stœchiométrie précise sont nécessaires aux longues chaînes. Le modèle par étapes transforme les bilans ester/amide en un degré moyen de polymérisation, puis le cours introduit les distributions de tailles.",
        ["Conversion p des fonctions limitantes et rapport de fonctions r≤1, sans unité ; monomères bifonctionnels", "DPn moyen, quantités de monomères/chaînes en mmol et nombre de chaînes actives imposé dans le modèle en chaîne ; distributions et dispersité dans le cours"],
        ["Carothers : égalité de réactivité, bifonctionnalité, absence de cyclisation et bilan de fonctions défini", "Polymérisation en chaîne et par étapes distinguées ; distribution idéale ne décrit pas un réseau ramifié ou toute polymérisation radicalaire"],
        ["Conservation des fonctions et chaînes", "Moyennes en nombre/masse", "Sensibilité à p et déséquilibre r"],
        ["Comparer p=0,9/0,99/0,999 à r=1 puis prévoir l’effet d’un ratio r=0,98.", "Faire varier p et r ; lire DPn et les quantités, puis comparer les familles chaîne/étapes à nombre de chaînes actives imposé.", "Retrouver Carothers et sa limite à p→1, expliquer ce que compte r et utiliser ensuite le problème du cours pour montrer pourquoi Xn seul ne décrit pas toutes les molécules."],
        "Fonctions organiques et stœchiométrie comme prérequis Sup ; introduction accompagnée.", "Macromolécules, synthèse et matériaux : parcours PC avec modèle fourni.", "Gélification, réseaux, polymérisations contrôlées et distributions mesurées.", [42,31,30],
        "Un matériau relié à un bilan de fonctions et à une distribution, avec les hypothèses de linéarité explicites."),
}
