"""Dix expériences guidées de convergence et de séries, reliées au recueil."""
from commun import lab, slider, select, preset

LABS = [
    lab('couche_limite', 'Le pic qui échappe au maillage', 'Convergences',
        'Étudier fₙ(x)=nx/(1+n²x²) sur [0,1] : le pic se rapproche de 0 sans perdre de hauteur. Comparer convergence simple, uniforme et uniforme sur un compact éloigné de 0.',
        [slider('n','Indice n',1,1000,1,30,integer=True), slider('delta','Bord gauche δ du compact',0.001,0.5,0.001,0.08)],
        [preset('Le pic se déplace',n=15,delta=0.08),preset('Maillage mis en défaut',n=800,delta=0.03),preset('Un compact protecteur',n=150,delta=0.2)]),
    lab('concentration', 'La limite perd une unité d’aire', 'Convergences',
        'Étudier fₙ(x)=n²xe⁻ⁿˣ sur [0,1]. En chaque point la limite est nulle ; l’intégrale tend pourtant vers 1. Une loupe x=u/n dévoile où se concentre la masse.',
        [slider('n','Indice n',1,300,1,35,integer=True),slider('x0','Point fixe x₀',0.01,1,0.01,0.2)],
        [preset('Concentration naissante',n=8,x0=0.3),preset('Pic fin, aire conservée',n=200,x0=0.2),preset('Observer un point fixe',n=80,x0=0.7)]),
    lab('tp99_original', 'Deux termes qui s’annulent', 'Convergences',
        'Retrouver le TP p.99 : cos(x/n)−1/√(1+(x/n)²). L’annulation de l’ordre deux révèle l’ordre quatre ; une majoration uniforme justifie la convergence normale sur les compacts.',
        [slider('n','Indice n',1,60,1,8,integer=True),slider('R','Rayon R du compact [−R,R]',0.1,6,0.1,2),slider('N','Nombre N de termes de la somme',2,180,1,60,integer=True)],
        [preset('Le quatrième ordre',n=40,R=1,N=100),preset('Un compact plus vaste',n=6,R=4,N=100),preset('Somme et premier terme local',n=12,R=2,N=80)]),
    lab('geometrie', 'Dériver une série sur un compact', 'Séries entières',
        'Approcher 1/(1−x) par une somme géométrique, puis dériver terme à terme. Le rayon reste 1, mais les bornes uniformes se dégradent lorsque le compact touche le bord.',
        [slider('N','Degré N de la somme',2,100,1,15,integer=True),slider('r','Rayon r du compact',0.1,0.97,0.01,0.8)],
        [preset('Compact confortable',N=12,r=0.5),preset('Près du bord',N=20,r=0.95),preset('Dérivée stabilisée',N=100,r=0.8)]),
    lab('arcsin_ex4', 'Une EDO fabrique les coefficients', 'Séries entières',
        'Exercice 4 : développer arcsin(x)/√(1−x²) à partir de (1−x²)f′−xf=1. Construire la récurrence des coefficients et suivre le reste près des singularités ±1.',
        [slider('N','Nombre N de coefficients impairs',1,100,1,16,integer=True),slider('r','Rayon r du compact',0.2,0.98,0.01,0.85)],
        [preset('Identifier les premiers termes',N=4,r=0.6),preset('La singularité ralentit',N=20,r=0.98),preset('Convergence sur le compact',N=80,r=0.85)]),
    lab('asymptotique_ex5', 'Une série entière à l’échelle e²x', 'Séries entières',
        'Exercice 5 : aₙ=(1+2/n²)ⁿ³/n! pour n≥2. Montrer R=∞ puis S(x)∼exp(e²x) quand x→+∞. Une représentation par des poids de Poisson évite les débordements numériques.',
        [slider('x','Abscisse positive x',0.2,60,0.2,8),slider('N','Dernier indice N de la somme partielle',2,700,1,120,integer=True)],
        [preset('Le début de l’asymptotique',x=2,N=45),preset('Le rapport tend vers 1',x=50,N=650),preset('Tronquer avant le pic est risqué',x=30,N=100)]),
    lab('binomiale_ex10', 'Au-delà du binôme polynomial', 'Séries entières',
        'Exercice 10 : développer (1−u)⁻ᵅ avec α=(2p+1)/2. Observer coefficients, signes et vitesse de convergence sur |u|≤r ; α=1/2 fournit la série de l’intégrale elliptique.',
        [select('p','Entier p : α=p+1/2',[(str(i),str(i)) for i in range(-3,4)],'0'),slider('N','Nombre N de termes',8,100,1,24,integer=True),slider('r','Rayon r du compact',0.1,0.95,0.01,0.75)],
        [preset('La racine inverse',p='0',N=25,r=0.85),preset('Un exposant négatif',p='-3',N=25,r=0.85),preset('Une forte singularité',p='3',N=60,r=0.9)]),
    lab('elliptique_pendule', 'La période du pendule devient elliptique', 'Intégrales et séries',
        'Exercice 10 : intégrer la série binomiale dans I(k)=∫₀π(1−k²sin²t)⁻¹ᐟ²dt. Avec k=sin(θ₀/2), I(k)/π donne le rapport entre période exacte et période des petites oscillations.',
        [slider('angle','Amplitude initiale θ₀',1,160,1,90,'°'),slider('N','Nombre N de termes',1,80,1,12,integer=True),slider('length','Longueur ℓ du pendule',0.2,4,0.1,1,'m')],
        [preset('Petites oscillations',angle=10,N=4,length=1),preset('Amplitude emblématique',angle=120,N=20,length=1),preset('Approcher la séparatrice',angle=160,N=60,length=2)]),
    lab('integrale_sh_ex11', 'Additionner des aires positives', 'Intégrales et séries',
        'Exercice 11 : calculer ∫₀∞t/sinh(t)dt en décomposant l’intégrande en 2t e⁻⁽²ⁿ⁺¹⁾ᵗ. Les aires exactes permettent une justification et une borne du reste, sans dépendre du dessin.',
        [slider('N','Nombre N de modes positifs',1,400,1,25,integer=True),slider('T','Fin T de la fenêtre représentée',2,15,0.5,8)],
        [preset('Voir les premiers modes',N=3,T=6),preset('Encadrer π²/4',N=200,T=12),preset('Zoom sur la couche près de zéro',N=80,T=3)]),
    lab('dominee_ex12', 'Une domination pour des signaux complexes', 'Intégrales et séries',
        'Exercice 12 : remplacer e⁻ᵗ par (1−t/n)ⁿ dans une intégrale pondérée. Tester une fonction affine, une fonction à saut ou une exponentielle complexe et justifier l’échange limite–intégrale.',
        [slider('n','Indice n',1,600,1,12,integer=True),select('family','Fonction f(t)', [('linear','1+t : réelle affine'),('jump','Signal à saut en t=0,4'),('complex','exp(iωt) : complexe'),('oscillatory','sin(ωt) : réelle oscillante')],'complex'),slider('omega','Pulsation ω',1,30,1,8)],
        [preset('Affine, n=1',n=1,family='linear',omega=8),preset('Continue par morceaux',n=80,family='jump',omega=8),preset('Intégrer dans le plan complexe',n=20,family='complex',omega=15)]),
]
