"""Dix expériences : transformées, systèmes linéaires et synthèse harmonique."""
from commun import lab, slider, select, preset

WAVES = [('square', 'Créneau ±1'), ('triangle', 'Triangle entre 0 et 1'), ('sawtooth', 'Rampe entre −1 et 1')]
LABS = [
    lab('rc_reponses', 'RC : du calcul de Laplace à la réponse temporelle', 'Laplace et systèmes',
        'Relier une équation différentielle, sa transformée et trois entrées causales. Le condensateur peut être initialement chargé.',
        [select('mode', 'Entrée causale', [('step', 'Pas'), ('impulse', 'Impulsion de Dirac'), ('ramp', 'Rampe affine')], 'ramp'),
         slider('tau', 'Constante de temps τ', .05, 3, .05, .8, 's'), slider('amplitude', 'Amplitude du pas / aire de l’impulsion A', .2, 3, .1, 1, 'V / V·s'),
         slider('a', 'Pente a de la rampe', -.5, 2, .1, .7, 'V/s'), slider('b', 'Ordonnée b de la rampe', -1, 2, .1, .4, 'V'), slider('y0', 'Tension initiale y₀', -1, 2, .1, 0, 'V')],
        [preset('Rampe du TP, repos initial', mode='ramp', tau=.8, a=.7, b=.4, y0=0), preset('Charge d’un condensateur', mode='step', tau=.5, amplitude=1, y0=0), preset('État initial non nul', mode='ramp', tau=1.4, a=.5, b=.7, y0=1.2), preset('Réponse impulsionnelle', mode='impulse', tau=.7, amplitude=1, y0=0)]),
    lab('rc_bode', 'RC : gain, phase et déformation de trois harmoniques', 'Laplace et systèmes',
        'Un filtre agit sur chaque fréquence : comparer le diagramme de Bode et la recomposition du signal de sortie.',
        [slider('tau', 'Constante de temps τ', .02, 2, .02, .2, 's'), slider('frequency', 'Fréquence fondamentale ν₁', .1, 8, .1, 1, 'Hz')],
        [preset('Fondamentale dans la bande passante', tau=.1, frequency=.3), preset('Fondamentale au voisinage de la coupure', tau=.2, frequency=.8), preset('Harmoniques fortement filtrées', tau=.6, frequency=1.5)]),
    lab('rlc_poles', 'RLC : pôles, amortissement et trois régimes', 'Laplace et systèmes',
        'Lire le transitoire d’un système du second ordre dans son plan des pôles, y compris le pôle double du régime critique.',
        [slider('omega0', 'Pulsation propre ω₀', 1, 20, .5, 6, 'rad/s'), slider('zeta', 'Amortissement ζ', .05, 2, .05, .3), select('mode', 'Entrée', [('step', 'Pas unitaire'), ('impulse', 'Impulsion unitaire')], 'step')],
        [preset('Résonateur sous-amorti', omega0=6, zeta=.15, mode='step'), preset('Amortissement critique', omega0=6, zeta=1, mode='step'), preset('Deux pôles réels distincts', omega0=6, zeta=1.8, mode='step'), preset('Réponse impulsionnelle', omega0=10, zeta=.25, mode='impulse')]),
    lab('dirichlet_abel', 'L’intégrale de Dirichlet par régularisation d’Abel', 'Laplace et systèmes',
        'Calculer une intégrale conditionnellement convergente en introduisant e^(−pt), puis distinguer limite, troncature et quadrature.',
        [slider('p', 'Paramètre de régularisation p', .02, 3, .02, .2), slider('cutoff', 'Borne de troncature L', 20, 180, 5, 80)],
        [preset('Damping visible', p=.6, cutoff=40), preset('Vers l’intégrale de Dirichlet', p=.02, cutoff=180), preset('Une borne courte ne suffit pas', p=.04, cutoff=20)]),
    lab('porte_sinc', 'Porte, sinus cardinal et phase d’une translation', 'Fourier et convolution',
        'Mesurer le compromis durée–largeur spectrale et observer la phase complexe produite par un décalage temporel.',
        [slider('width', 'Largeur L de la porte', .2, 3, .1, 1, 's'), slider('shift', 'Centre temporel t₀', -2, 2, .1, .4, 's')],
        [preset('Porte centrée', width=1, shift=0), preset('Signal bref, spectre large', width=.3, shift=.2), preset('Même module, autre phase', width=1, shift=1.3)]),
    lab('gaussienne', 'Gaussienne : Fourier et incertitude temps–fréquence', 'Fourier et convolution',
        'Passer de l’amplitude à la densité d’énergie avant de définir les écarts types. La gaussienne sature la borne 1/(4π).',
        [slider('sigma', 'Largeur σ de l’amplitude gaussienne', .1, 2, .1, .6, 's'), slider('amplitude', 'Amplitude A', .5, 2, .1, 1)],
        [preset('Impulsion brève', sigma=.2, amplitude=1), preset('Impulsion longue', sigma=1.4, amplitude=1), preset('L’énergie change, les largeurs restent', sigma=.6, amplitude=2)]),
    lab('convolution_portes', 'Convoluer : l’aire d’un recouvrement mobile', 'Fourier et convolution',
        'La convolution de deux portes devient un triangle ou un trapèze. Retrouver simultanément le produit de leurs spectres.',
        [slider('width1', 'Largeur L₁ de f', .2, 3, .1, 1, 's'), slider('width2', 'Largeur L₂ de g', .2, 3, .1, 1.8, 's'), slider('shift', 'Centre d de g', -2, 2, .1, .5, 's'), slider('probe', 'Position t du recouvrement', -4, 4, .1, .8, 's')],
        [preset('Deux portes identiques : triangle', width1=1, width2=1, shift=0, probe=.3), preset('Largeurs inégales : trapèze', width1=.6, width2=2, shift=.5, probe=.5), preset('Translation et support', width1=1.5, width2=1, shift=1.2, probe=2)]),
    lab('gibbs_fourier', 'Synthèse de Fourier : Gibbs et moyennes de Fejér', 'Séries harmoniques',
        'Comparer une somme partielle à une moyenne de Cesàro. Un saut conserve un dépassement ; un triangle continu présente un autre régime.',
        [select('wave', 'Signal périodique', WAVES, 'square'), slider('N', 'Dernier indice harmonique N', 1, 120, 1, 25, integer=True), slider('period', 'Période T', .5, 4, .5, 2, 's')],
        [preset('Créneau : dépassement persistant', wave='square', N=55, period=2), preset('Triangle : coefficients en 1/n²', wave='triangle', N=15, period=2), preset('Rampe : demi-somme au raccord', wave='sawtooth', N=40, period=2), preset('Première harmonique seulement', wave='square', N=1, period=2)]),
    lab('parseval_spectre', 'Parseval : énergie, harmoniques et sommes classiques', 'Séries harmoniques',
        'Construire un bilan exact d’énergie moyenne : la puissance des harmoniques relie les créneaux et triangles aux sommes en 1/n² et 1/n⁴.',
        [select('wave', 'Signal périodique', WAVES, 'triangle'), slider('N', 'Dernier indice harmonique N', 1, 200, 1, 30, integer=True)],
        [preset('Créneau et somme des inverses des carrés impairs', wave='square', N=35), preset('Triangle et somme des inverses des puissances quatrièmes', wave='triangle', N=15), preset('Rampe et somme de Bâle', wave='sawtooth', N=60)]),
    lab('poisson_noyau', 'Noyau de Poisson : convergence normale et lissage', 'Séries harmoniques',
        'Sommer une série géométrique bilatérale, contrôler son reste uniforme et voir comment les coefficients r^|n| lissent un créneau.',
        [slider('r', 'Paramètre r', 0, .97, .01, .75), slider('N', 'Dernier indice harmonique N', 1, 120, 1, 25, integer=True), slider('period', 'Période T', .5, 3, .5, 2, 's')],
        [preset('Lissage prononcé', r=.35, N=12, period=2), preset('Noyau concentré', r=.94, N=70, period=2), preset('Trop peu de termes près de r=1', r=.97, N=12, period=2), preset('Moyenne seule', r=0, N=1, period=2)]),
]
