"""Du théorème de Poisson à une chaîne de mesure et de traitement."""
from commun import lab, slider as s, select as q, preset as p

LABS = [
lab('poisson_gaussienne','Poisson : une gaussienne, deux descriptions','Échantillonner et reconstruire',
'Relier une somme de gaussiennes translatées à sa série de Fourier ; observer comment la largeur temporelle commande le nombre de raies.',
[s('sigma','Largeur σ de la gaussienne',.08,1.2,.02,.3,'s'),s('T','Période de répétition T',.5,3,.1,1.5,'s'),s('N','Troncature symétrique |k| ≤ N',1,30,1,8,integer=True)],
[p('Impulsions bien séparées',sigma=.14,T=1.5,N=8),p('Signal presque constant',sigma=1,T=1.5,N=8),p('Peu de raies',N=1)]),
lab('shannon','Shannon : reconstruire un paquet à bande limitée','Échantillonner et reconstruire',
'Échantillonner sinc²(Bt) cos(2πf₀t), comparer ses bandes spectrales au seuil de Nyquist et reconstruire à partir d’un nombre fini de mesures.',
[s('F','Fréquence d’échantillonnage F',4,40,1,24,'Hz'),s('B','Demi-largeur spectrale B',1,6,.5,3,'Hz'),s('f0','Fréquence centrale f₀',0,12,.5,5,'Hz'),s('M','Échantillons de chaque côté M',8,100,2,40,integer=True)],
[p('Au-dessus du seuil',F=24,B=3,f0=5,M=40),p('Bandes repliées',F=12,B=3,f0=5),p('Effet de la troncature',F=24,M=8)]),
lab('aliasing','Repliement : deux fréquences, les mêmes mesures','Échantillonner et reconstruire',
'Identifier les sinusoïdes indiscernables sur une grille de mesure ; distinguer fréquence réelle, fréquence apparente et cas limite de Nyquist.',
[s('F','Fréquence de mesure F',8,80,2,24,'Hz'),s('f','Fréquence de la sinusoïde',0,80,.5,19,'Hz'),s('phase','Phase initiale',0,360,5,30,'°')],
[p('19 Hz vus à 5 Hz',F=24,f=19,phase=30),p('Sous le seuil',F=24,f=5),p('Nyquist : phase perdue',F=24,f=12,phase=90),p('Fréquence multiple de F',F=24,f=24,phase=0)]),
lab('anti_repliement','Avant la mesure : le filtre antirepliement','Échantillonner et reconstruire',
'Comparer une chaîne sans filtre et une chaîne analogique de Butterworth, puis suivre ce qui reste d’une perturbation au-delà de F/2.',
[s('F','Fréquence d’échantillonnage F',20,100,2,50,'Hz'),s('fc','Fréquence de coupure f꜀',2,35,1,12,'Hz'),s('noise_f','Fréquence perturbatrice',20,120,2,72,'Hz'),s('order','Ordre du filtre analogique',1,6,1,4,integer=True),s('amplitude','Amplitude perturbatrice',.1,2,.1,1)],
[p('Perturbation fortement atténuée',F=50,fc=12,noise_f=72,order=4),p('Filtre trop peu sélectif',order=1),p('Coupure trop haute',fc=35)]),
lab('fenetres_fft','FFT : fuite spectrale et fenêtrage','Mesurer et analyser',
'Mesurer une fréquence entre deux cases de la FFT ; comparer largeur du lobe principal, lobes secondaires et correction du gain de la fenêtre.',
[s('f','Fréquence du signal',4,40,.125,13.375,'Hz'),q('window','Fenêtre',[('rect','Rectangulaire'),('hann','Hann périodique'),('blackman','Blackman périodique')],'hann'),s('N','Nombre d’échantillons N',64,512,32,256,integer=True),s('padding','Facteur de zéros ajoutés',1,8,1,4,integer=True)],
[p('Une fréquence sur une case',f=13,N=256,window='rect'),p('Entre deux cases',f=13.375,window='rect'),p('Réduire les lobes secondaires',window='blackman'),p('Interpoler la courbe',padding=8)]),
lab('resolution','Résolution : voir deux fréquences proches','Mesurer et analyser',
'Faire varier la durée d’observation et l’écart de deux raies ; vérifier pourquoi ajouter des zéros ne remplace pas une acquisition plus longue.',
[s('N','Durée via N échantillons à 128 Hz',64,512,32,128,integer=True),s('delta','Écart des fréquences Δf',.25,4,.25,1,'Hz'),s('padding','Interpolation spectrale',1,8,1,4,integer=True)],
[p('Deux raies confondues',N=64,delta=1),p('Acquisition plus longue',N=512,delta=1),p('Seulement des zéros',N=64,padding=8)]),
lab('spectrogramme','Spectrogramme : suivre un chirp','Mesurer et analyser',
'Explorer le compromis entre localisation temporelle et précision fréquentielle sur une fréquence qui croît au cours du temps.',
[s('length','Longueur de la fenêtre STFT',16,128,16,48,integer=True),s('f0','Fréquence de départ',4,24,1,8,'Hz'),s('f1','Fréquence finale',25,55,1,48,'Hz')],
[p('Bonne localisation temporelle',length=16),p('Bonne localisation fréquentielle',length=128),p('Balayage plus lent',f0=20,f1=32)]),
lab('modulation','Modulation : traduire le spectre d’un message','Transmettre et détecter',
'Construire une modulation d’amplitude puis une démodulation synchrone ; suivre porteuse, bandes latérales et erreurs de fréquence ou de phase.',
[s('m','Profondeur de modulation m',0,1.5,.05,.7),s('fm','Fréquence du message fₘ',1,8,.5,3,'Hz'),s('fc','Fréquence porteuse f꜀',15,45,1,30,'Hz'),s('offset','Écart de l’oscillateur local',-2,2,.1,0,'Hz'),s('phase','Phase de l’oscillateur local',0,180,5,0,'°')],
[p('Démodulation synchrone',offset=0,phase=0,m=.7),p('Quadrature : message effacé',phase=90),p('Battements parasites',offset=.8),p('Surmodulation',m=1.4)]),
lab('correlation_retard','Corrélation : mesurer un temps de vol','Transmettre et détecter',
'Envoyer une impulsion codée, rechercher sa copie retardée dans le bruit et convertir le retard en distance d’aller-retour.',
[s('delay','Retard de l’écho',.1,1.2,.02,.6,'s'),s('noise','Écart-type du bruit',0,1.5,.05,.45),s('speed','Vitesse de propagation',100,1500,50,350,'m/s'),s('seed','Réalisation du bruit (graine)',0,20,1,4,integer=True)],
[p('Écho net',noise=.05),p('Écho noyé dans le bruit',noise=1.1),p('Ultrasons dans l’eau',speed=1500,delay=.2)]),
lab('debruitage','Débruiter : réduction du bruit et déformation','Transmettre et détecter',
'Comparer moyenne glissante et filtre récursif ; quantifier séparément le bruit résiduel et la déformation du signal utile.',
[q('filter','Filtre numérique',[('mean','Moyenne glissante causale'),('rc','Passe-bas récursif de type RC')],'mean'),s('width','Longueur de mémoire',1,31,2,9,integer=True),s('noise','Écart-type du bruit blanc',0,1.5,.05,.5),s('f','Fréquence utile',2,16,.5,5,'Hz'),s('seed','Réalisation du bruit',0,20,1,3,integer=True)],
[p('Lisser sans trop déformer',width=5,f=3),p('Filtre trop lent',width=31,f=12),p('Filtre récursif',filter='rc',width=9)])
]
