"""Cours originaux, démonstrations et exercices de l'atelier Séries & Signaux.

Les conventions sont explicites : Fourier en Hz et sinc normalisée pour le
signal, Laplace unilatérale pour les systèmes causaux. Les textes du recueil
servent de point de départ ; les explications et problèmes ci-dessous sont
nouvellement rédigés. Aucun scan du document source n'est distribué.
"""
from html import escape


def P(label, text):
    return '<p><b>' + escape(label) + '</b> ' + escape(text) + '</p>'


def F(text):
    return '<div class="formula">' + escape(text).replace('\n', '<br>') + '</div>'


def record(lab, title, level, context, formula, proof, application,
           lemma_title, lemma_statement, lemma_formula, lemma_proof,
           ex1_title, ex1_question, ex1_answer, ex2_title, ex2_question, ex2_answer):
    return dict(lab=lab, title=title, level=level, context=context, formula=formula,
                proof=proof, application=application, lemma_title=lemma_title,
                lemma_statement=lemma_statement, lemma_formula=lemma_formula,
                lemma_proof=lemma_proof,
                exercises=[(ex1_title, ex1_question, ex1_answer),
                           (ex2_title, ex2_question, ex2_answer)])


DATA = [
    record('rc_reponses', 'Un RC : Laplace conserve aussi l’état initial', 'Sup → Spé',
        'Le TP de la page 107 suit la tension y aux bornes du condensateur d’un RC. On note τ=RC en secondes, u la tension d’entrée en volts et y₀=y(0⁻). La loi de maille donne τy′+y=u. Une entrée affine est ici u(t)=b+at pour t>0 : a est une pente en V/s, b une ordonnée en V. Les noms a et b sont donc volontairement explicités avant tout calcul.',
        'τy′+y=u ; Y(p)=[U(p)+τy₀]/(1+τp)\nPas A : y=A+(y₀−A)e^(−t/τ)\nRampe b+at : y=b+at−aτ+(y₀−b+aτ)e^(−t/τ)',
        'Une intégration par parties donne L(y′)=pY−y₀. Pour la rampe, U=b/p+a/p² ; on sépare un polynôme particulier b+at−aτ et un transitoire Ce^(−t/τ). La condition initiale fournit C=y₀−b+aτ. Pour une impulsion d’aire A en V·s, intégrer l’équation autour de zéro donne le saut τ[y(0⁺)−y(0⁻)]=A ; la contribution impulsionnelle vaut (A/τ)e^(−t/τ).',
        'Avec τ=0,8 s, a=0,7 V/s, b=0,4 V et y₀=0, la sortie vaut 0,7t−0,16+0,16e^(−t/0,8). Elle part de zéro et, après le transitoire, suit la pente de l’entrée avec un retard en tension aτ=0,56 V. Vérifier l’état initial et l’équation différentielle est plus sûr que reconnaître seulement une forme exponentielle.',
        'La convolution décrit le repos initial',
        'Pour y₀=0, la réponse d’un système linéaire invariant est la convolution de son entrée avec h(t)=𝟙_{t≥0}e^(−t/τ)/τ. L’indicatrice 𝟙 assure la causalité ; elle est distincte du transfert H(p). Un état initial non nul ajoute une solution homogène et ne se cache pas dans le même produit de transfert.',
        'y(t)=∫₀ᵗ h(t−s)u(s)ds + y₀e^(−t/τ)\nH(p)=L(h)(p)=1/(1+τp), Re p>−1/τ',
        'Le facteur intégrant e^(t/τ) transforme l’équation en [ye^(t/τ)]′=u e^(t/τ)/τ. Intégrer de 0 à t fournit directement la convolution et le terme initial. L’intégrale de h sur [0,+∞[ vaut 1 : le gain statique est donc 1, tandis que h a l’unité s⁻¹. La transformée de h existe dans le demi-plan indiqué, ce qui inclut l’axe imaginaire pour τ>0.',
        'Une rampe n’est pas une sortie identique décalée dès t=0',
        'Un RC au repos reçoit u(t)=2+3t V pour t>0, avec τ=0,5 s. Calculer y(t), y′(0⁺) et le décalage asymptotique u−y. Vérifier la solution en la substituant dans la maille.',
        'La solution est y=0,5+3t−0,5e^(−2t). À zéro elle vaut 0. Sa dérivée est 3+e^(−2t), donc y′(0⁺)=4 V/s=u(0⁺)/τ. Ensuite 0,5y′+y=(1,5+0,5e^(−2t))+(0,5+3t−0,5e^(−2t))=2+3t. Le décalage tend vers aτ=1,5 V. Le retard asymptotique n’autorise pas à remplacer la solution pour tout t par u(t−τ), qui imposerait un état initial différent.',
        'L’aire d’une impulsion commande le saut',
        'Un condensateur possède y(0⁻)=0,8 V. Une impulsion d’entrée d’aire A=0,6 V·s lui est appliquée avec τ=0,3 s ; l’entrée est nulle ensuite. Trouver y(0⁺), y(t>0) et son aire. Quelle grandeur distingue une impulsion d’un pas ?',
        'L’intégration donne y(0⁺)=0,8+0,6/0,3=2,8 V, puis y(t)=2,8e^(−t/0,3). Son aire est 2,8×0,3=0,84 V·s, dont 0,24 provient de l’état initial et 0,60 de l’impulsion. Le paramètre d’une impulsion est son aire A, et non une tension de plateau : Aδ(t) a l’unité V puisque δ a l’unité s⁻¹. Un pas est décrit au contraire par une amplitude constante en volts.'),
    record('rc_bode', 'Une fréquence : gain et phase sont deux informations', 'Sup → Spé',
        'Pour une entrée sinusoïdale après extinction du transitoire, le RC agit sur l’exponentielle complexe e^(iωt). La fréquence ν est en Hz, la pulsation ω=2πν en rad/s ; il faut cette conversion avant de placer la coupure. Le gain mesure un rapport d’amplitudes, la phase un décalage du motif.',
        'H(iω)=1/(1+iωτ)\n|H|=1/√(1+ω²τ²), arg H=−arctan(ωτ)\nνc=1/(2πτ) ; GdB=20log₁₀|H|',
        'Remplacer y par Ye^(iωt) et u par Ue^(iωt) dans τy′+y=u donne (1+iωτ)Y=U. Une entrée cos(ωt+φ) devient |H|cos(ωt+φ+arg H). À la coupure, le gain vaut 1/√2 et la phase −π/4. À haute fréquence le gain est équivalent à 1/(ωτ), soit une pente −20 dB par décade ; à basse fréquence il tend vers 1.',
        'Le banc combine trois harmoniques : chacune possède son propre gain et sa propre phase. Une sortie plus lisse n’est donc pas seulement une version de l’entrée réduite par une constante. À τ=0,2 s, νc≈0,796 Hz ; une fondamentale de 0,8 Hz est déjà atténuée, et ses harmoniques davantage.',
        'Pourquoi Laplace donne Fourier sur l’axe imaginaire',
        'L’évaluation de H(p) en p=iω est justifiée ici parce que h est absolument intégrable. Cette propriété assure la stabilité du filtre en amplitude et l’existence de son intégrale de Fourier.',
        'H(iω)=∫₀^∞ h(t)e^(−iωt)dt\n‖h*u‖∞ ≤ ‖h‖₁‖u‖∞',
        'Pour h(t)=e^(−t/τ)/τ sur t≥0, l’intégrale de |h| vaut 1. On peut donc fixer ω réel et faire le calcul sans régularisation. L’inégalité de convolution se déduit de |∫h(s)u(t−s)ds|≤‖u‖∞∫|h|. Un transfert possédant un pôle sur l’axe imaginaire demanderait un autre examen : écrire p=iω dans une expression rationnelle ne justifie pas à lui seul une réponse permanente bornée.',
        'Concevoir une atténuation plutôt que choisir τ au hasard',
        'On veut conserver au moins 0,95 de l’amplitude à 2 Hz et atténuer à au plus 0,10 l’amplitude à 50 Hz avec un seul RC. Déterminer les contraintes sur τ et conclure.',
        'La première contrainte donne τ≤√(1/0,95²−1)/(4π)≈0,0262 s. La seconde donne τ≥√99/(100π)≈0,0317 s. Les intervalles ne se rencontrent pas : un RC d’ordre un ne répond pas à ce cahier des charges. Il faut modifier les spécifications ou employer un filtre plus sélectif. Ce raisonnement utilise des gains d’amplitude ; remplacer 20log par 10log sans passer à une puissance changerait le sens des données.',
        'Reconstruire deux harmoniques avec leurs phases',
        'Pour τ=1/(2π) s, u(t)=cos(2πt)+(1/3)cos(6πt). Donner le régime permanent de la sortie et les gains en dB à 1 et 3 Hz.',
        'On a ωτ=1 pour 1 Hz et 3 pour 3 Hz. La sortie est (1/√2)cos(2πt−π/4)+(1/(3√10))cos(6πt−arctan3). Les gains valent −3,010 dB et −10 dB. Le coefficient 1/3 était déjà dans l’entrée et ne doit pas être compté dans le gain propre du filtre. Le rapport entre les harmoniques change, ce qui modifie la forme du signal.'),
    record('rlc_poles', 'Les pôles d’un second ordre organisent le transitoire', 'Spé, physique et SI selon filière',
        'Le modèle normalisé y″+2ζω₀y′+ω₀²y=ω₀²u représente notamment un circuit RLC ou un oscillateur mécanique. La pulsation propre ω₀ a l’unité rad/s, ζ est sans unité. Le banc part du repos et compare un pas unitaire et une impulsion unitaire.',
        'H(p)=ω₀²/(p²+2ζω₀p+ω₀²)\np±=−ζω₀ ± ω₀√(ζ²−1)\nζ<1 : paire complexe ; ζ=1 : pôle double ; ζ>1 : deux pôles réels',
        'Le dénominateur se factorise à partir de l’équation caractéristique. Pour ζ<1, poser ωd=ω₀√(1−ζ²) donne des termes e^(−ζω₀t)cos(ωdt) et e^(−ζω₀t)sin(ωdt). À ζ=1, les deux modes fusionnent : la seconde solution est te^(−ω₀t). On ne peut pas utiliser deux coefficients de fractions simples distinctes au point de fusion.',
        'Le plan des pôles donne la vitesse de décroissance par leur partie réelle et la fréquence d’oscillation par leur partie imaginaire. Une augmentation de ζ supprime le dépassement, mais un ζ très élevé crée aussi un pôle lent proche de zéro. « Plus amorti » ne signifie donc pas systématiquement « plus rapide ».',
        'Calculer le dépassement sans lire approximativement un graphe',
        'Pour 0<ζ<1, la réponse au pas possède un premier maximum à π/ωd. Sa hauteur au-dessus de la valeur finale se calcule exactement à partir de la réponse impulsionnelle.',
        'h(t)=(ω₀²/ωd)e^(−ζω₀t)sin(ωdt)\nMp=exp[−πζ/√(1−ζ²)], tp=π/ωd',
        'La dérivée de la réponse au pas est h. Elle s’annule la première fois pour ωdt=π, avec changement de signe positif vers négatif. Dans y=1−e^(−ζω₀t)[cos(ωdt)+(ζω₀/ωd)sin(ωdt)], substituer ce temps donne y(tp)=1+e^(−πζ/√(1−ζ²)). Pour ζ≥1, la réponse au pas au repos est monotone dans ce modèle.',
        'Retrouver l’amortissement à partir du dépassement',
        'Une réponse au pas de gain statique 1 dépasse sa valeur finale de 20 %. Calculer ζ, puis ω₀ si le premier maximum est observé à 0,40 s.',
        'Avec L=−ln0,20≈1,609, L=πζ/√(1−ζ²), donc ζ=L/√(π²+L²)≈0,456. Puis ωd=π/0,40≈7,854 rad/s et ω₀=ωd/√(1−ζ²)≈8,83 rad/s. Cette identification repose sur le modèle du second ordre au repos ; un zéro, un état initial ou d’autres modes pourraient modifier le dépassement.',
        'La limite critique crée un facteur t',
        'Montrer que la réponse impulsionnelle précédente tend vers ω₀²te^(−ω₀t) lorsque ζ→1⁻. En déduire la réponse critique au pas.',
        'Lorsque ζ→1⁻, ωd→0 et sin(ωdt)/ωd→t pour chaque t fixé. Le facteur exponentiel tend vers e^(−ω₀t), d’où hcrit=ω₀²te^(−ω₀t). En intégrant de zéro à t, ycrit=1−(1+ω₀t)e^(−ω₀t). Sa dérivée est positive pour t>0, son départ et sa valeur finale sont respectivement 0 et 1. Cela retrouve la solution à pôle double sans diviser par deux pôles qui se confondent.'),
    record('dirichlet_abel', 'Une intégrale conditionnelle calculée par Laplace', 'Spé',
        'La page 107 propose I=∫₀^∞ sin(t)/t dt. L’intégrale impropre converge, mais ∫|sin(t)|/t diverge. L’expérience introduit p>0 dans Ip=∫₀^∞ e^(−pt)sin(t)/t dt, puis fait tendre p vers zéro. La borne finie L et le paramètre p sont deux opérations distinctes.',
        'Ip′=−∫₀^∞ e^(−pt)sin(t)dt=−1/(1+p²)\nIp=π/2−arctan p ; limp→0⁺ Ip=π/2',
        'Sur tout compact p≥p₀>0, une domination exponentielle permet de dériver sous l’intégrale. On utilise L(sin)(p)=1/(1+p²), puis la condition Ip→0 lorsque p→+∞ pour déterminer la constante d’intégration. Pour retrouver l’intégrale sans amortissement, il reste à justifier le passage au bord p=0 ; une domination par 1/t ne convient pas sur l’infini.',
        'Le banc affiche valeur fermée, intégrale amortie tronquée et intégrale non amortie tronquée. Leur proximité numérique ne remplace pas le contrôle de la queue. Pour p petit, augmenter L ; pour une borne L fixée, on n’a que la limite d’une intégrale sur [0,L].',
        'Contrôler uniformément une queue oscillante',
        'L’intégration par parties donne une borne O(1/L) pour les queues de sin(t)/t, avec ou sans amortissement p≥0. C’est ce contrôle qui permet la limite d’Abel sans convergence dominée absolue sur [0,+∞[.',
        '|∫L^∞ e^(−pt)sin(t)/t dt|≤2/L, p≥0\n∫L^∞ sin(t)/t dt = cos L/L − ∫L^∞ cos(t)/t² dt',
        'Poser a(t)=e^(−pt)/t, positive décroissante. L’intégration par parties sur [L,R] avec la primitive −cos t majore l’intégrale par a(L)+a(R)+∫L^R|a′|≤2a(L). Puis R→∞ donne ≤2/L indépendamment de p. Sur [0,L], la fonction sin(t)/t se prolonge en 1 et le passage p→0 est dominé. On contrôle alors d’abord la queue, puis le paramètre.',
        'Choisir une borne pour une précision garantie',
        'On approxime I par ∫₀ᴸ sin(t)/t dt. Quelle borne L suffit pour garantir une erreur au plus 0,01 d’après l’estimation générale ? Pourquoi un résultat numérique proche de π/2 avec L=20 ne donne-t-il pas cette garantie ?',
        'La borne 2/L≤0,01 impose L≥200. Elle est suffisante, pas nécessaire : certaines phases de L annulent partiellement la queue. À L=20, la majoration ne donne que 0,10 ; une petite erreur observée peut provenir d’une compensation circonstancielle. La précision de la quadrature sur [0,L] doit aussi être séparée de l’erreur de troncature.',
        'Généraliser l’échelle de l’intégrale de Dirichlet',
        'Pour b>0 et p>0, calculer J(p,b)=∫₀^∞ e^(−pt)sin(bt)/t dt. Déterminer sa limite quand p→0⁺ et le résultat pour b<0.',
        'En dérivant par rapport à b sous domination exponentielle, ∂bJ=∫₀^∞ e^(−pt)cos(bt)dt=p/(p²+b²), avec J(p,0)=0. Donc J=arctan(b/p). Pour b>0 la limite vaut π/2 ; pour b<0 elle vaut −π/2 par imparité. Une dilatation t↦bt explique l’indépendance en la valeur positive de b pour l’intégrale non amortie.'),
    record('porte_sinc', 'Un signal bref occupe un spectre large', 'Sup → Spé',
        'La porte Π vaut 1 pour |t|<1/2. Une porte de durée L centrée en t₀ est f(t)=Π((t−t₀)/L), d’amplitude 1. Fourier est ici en Hz : f̂(ν)=∫ℝf(t)e^(−2iπνt)dt. On écrit sincₙ(u)=sin(πu)/(πu), avec sincₙ(0)=1 ; la sinc du PDF sin z/z vaut sincₙ(z/π).',
        'f̂(ν)=L sincₙ(Lν)e^(−2iπνt₀)\nPremiers zéros : ν=±1/L ; f̂(0)=L',
        'Intégrer e^(−2iπνt) entre t₀−L/2 et t₀+L/2 donne un facteur de translation puis sin(πνL)/(πν). Sa limite en zéro est L, l’aire de la porte. Réduire L élargit le lobe principal ; déplacer t₀ modifie la phase sans changer le module. Aux zéros du spectre, la phase n’est pas définie et ne doit pas être interprétée comme une mesure fiable.',
        'Une porte de 0,25 s possède ses premiers zéros à ±4 Hz ; une porte de 2 s les possède à ±0,5 Hz. Le rapport durée–largeur est exact pour ces zéros. Ce n’est pas le produit de deux écarts types d’énergie, car le spectre sinc de la porte possède un second moment divergent.',
        'Translations et dilatations : dériver les facteurs',
        'Un changement de variable conserve le facteur d’aire et fixe le sens des déplacements du spectre. C’est un outil commun à la porte, aux gaussiennes et au peigne de Dirac.',
        'TF[f(t−t₀)](ν)=e^(−2iπνt₀)f̂(ν)\nTF[f(t/a)](ν)=|a|f̂(aν), a≠0',
        'Dans la première intégrale, poser u=t−t₀ ; dans la seconde, u=t/a. Pour a<0, inverser les bornes compense le signe du Jacobien et produit |a|. Si l’on normalise la dilatation par 1/|a| pour garder une aire 1, ce facteur disparaît de la transformée. On distingue donc toujours largeur, amplitude et aire.',
        'Lire une durée à partir de zéros spectraux',
        'Une porte réelle d’amplitude A=3 V possède un premier zéro positif à 5 Hz et est centrée en t₀=0,12 s. Calculer sa durée, sa transformée en zéro et sa phase à 1 Hz.',
        'La durée est L=1/5=0,20 s. On a f̂(0)=AL=0,60 V·s. À 1 Hz, sincₙ(0,20)>0, donc la phase est −2π×1×0,12=−0,24π rad, soit −43,2°. Au-delà d’un zéro où la sinc change de signe, un π supplémentaire entre dans l’argument : une droite de phase seule ne décrit pas tous les lobes.',
        'Une porte d’aire 1 prépare la distribution de Dirac',
        'Poser dε(t)=Π(t/ε)/ε. Montrer que son aire vaut 1, sa TF vaut sincₙ(εν), et que ∫dε(t)φ(t)dt→φ(0) pour toute fonction test continue près de zéro. Est-ce une convergence uniforme de fonctions ?',
        'L’aire vaut ε/ε=1 et la formule de la porte donne d̂ε=sincₙ(εν), qui tend vers 1 à fréquence fixée. L’action sur φ est la moyenne (1/ε)∫₋ε/₂^ε/₂φ(t)dt ; son écart à φ(0) est majoré par le maximum de |φ(t)−φ(0)| sur ce petit intervalle, donc tend vers zéro. La hauteur 1/ε diverge et aucune fonction limite uniforme n’apparaît : il s’agit de convergence au sens des distributions.'),
    record('gaussienne', 'Une gaussienne dans deux domaines', 'Sup → Spé ; incertitude en prolongement',
        'On étudie f(t)=A exp[−t²/(2σ²)], où σ>0 mesure la largeur de l’amplitude et A son amplitude. Pour parler d’incertitude temps–fréquence, les densités sont |f|² et |f̂|² normalisées par l’énergie. Leur largeur n’est pas directement le σ écrit dans l’amplitude.',
        'f̂(ν)=Aσ√(2π)e^(−2π²σ²ν²)\nE=∫|f|²dt=A²σ√π\nΔt=σ/√2 ; Δν=1/(2√2πσ) ; Δt·Δν=1/(4π)',
        'La TF peut se déduire sans déplacer une intégrale complexe : f′=−tf/σ² implique, par intégration par parties et dérivation en ν, f̂′=−4π²σ²ν f̂. L’aire f̂(0)=Aσ√(2π) fournit la constante. Les densités d’énergie sont ensuite des gaussiennes de paramètres plus étroits ; calculer leurs moments donne les deux écarts types affichés.',
        'Multiplier A par deux quadruple l’énergie sans changer les deux largeurs normalisées. Réduire σ par deux réduit Δt par deux et double Δν. Ce modèle relie impulsions optiques, paquets d’ondes et mesure du signal, avec une convention en Hz qui explique le facteur 4π.',
        'La borne d’incertitude par Cauchy–Schwarz',
        'Pour un signal centré suffisamment régulier, à énergie finie, tel que tf et f′ appartiennent à L², une intégration par parties puis Cauchy–Schwarz donnent la borne temps–fréquence. Les exemples discontinus n’ont pas automatiquement ces moments finis.',
        '‖f‖₂² = −2 Re∫t f̄(t)f′(t)dt\n‖tf‖₂‖f′‖₂ ≥ ‖f‖₂²/2\nTF(f′)=2iπνf̂ ⇒ Δt·Δν≥1/(4π)',
        'Intégrer la dérivée de t|f|² avec un terme de bord nul. Majorer la partie réelle par le module du produit scalaire, puis par les normes L². Parseval transforme ‖f′‖₂ en 2π‖νf̂‖₂. L’égalité de Cauchy–Schwarz impose f′ proportionnel à tf avec une constante réelle négative, ce qui conduit à une gaussienne centrée.',
        'Séparer amplitude et largeur d’énergie',
        'Pour A=2 et σ=0,40 s, calculer E, Δt, Δν et leur produit. Qu’arrive-t-il en remplaçant A par 1 ?',
        'E=4×0,40√π≈2,836 unités d’amplitude²·s. Δt≈0,2828 s, Δν≈0,2813 Hz et leur produit≈0,07958=1/(4π). Avec A=1, E est divisé par quatre, tandis que les densités normalisées et les écarts types restent identiques. Employer σ=0,40 comme écart type de |f|² donnerait un facteur √2 erroné.',
        'Pourquoi la porte ne sature pas la même borne',
        'Comparer f(t)=Π(t/L) à une gaussienne. La durée finie de la porte entraîne-t-elle un Δν fini ? Examiner ∫ν²|f̂(ν)|²dν.',
        'La transformée vaut L sincₙ(Lν). Donc ν²|f̂|²=sin²(πLν)/π², dont l’intégrale sur ℝ diverge. La porte possède un Δt fini mais un Δν infini dans ce sens. Le produit largeur entre premiers zéros × durée est une autre mesure, qui reste utile mais n’est pas l’incertitude par moments quadratiques. La discontinuité de la porte produit ici la queue spectrale trop lente.'),
    record('convolution_portes', 'Une convolution se lit comme un recouvrement', 'Sup → Spé',
        'On prend deux portes d’amplitude 1, de largeurs L₁ et L₂, centrées respectivement en 0 et d. La convolution bilatérale vaut ∫ℝ f(u)g(t−u)du. Pour ces fonctions indicatrices, l’intégrale est exactement la longueur de l’intersection de deux intervalles : une construction géométrique devient une formule de signal.',
        '(f*g)(t)=max(0,min(L₁/2,t−d+L₂/2)−max(−L₁/2,t−d−L₂/2))\nTF(f*g)=L₁L₂ sincₙ(L₁ν)sincₙ(L₂ν)e^(−2iπνd)',
        'Le premier intervalle est [−L₁/2,L₁/2] ; le second, obtenu en résolvant |t−u−d|<L₂/2, est [t−d−L₂/2,t−d+L₂/2]. Leur intersection donne la formule avec min et max. Pour L₁=L₂=L, le résultat est (L−|t−d|) positif sur |t−d|<L : un triangle. Si les largeurs diffèrent, un plateau apparaît lorsque la petite porte est entièrement dans la grande.',
        'Le curseur de sonde t déplace le second intervalle et rend visible l’intégrale avant de regarder le produit spectral. Le résultat possède l’unité s si les amplitudes sont sans unité ; sa hauteur n’est pas automatiquement 1. L’aire de la convolution vaut L₁L₂.',
        'Pourquoi une convolution devient un produit',
        'Pour f et g dans L¹, le produit d’intégrabilité permet Fubini. Le calcul utilise deux variables indépendantes ; remplacer la convolution par le produit f(t)g(t) conduirait au résultat spectral inverse.',
        '∫ℝ∫ℝ|f(u)g(t−u)|du dt=‖f‖₁‖g‖₁\nTF(f*g)(ν)=f̂(ν)ĝ(ν)',
        'Dans l’intégrale double de la TF, poser v=t−u. L’exponentielle e^(−2iπνt) devient e^(−2iπνu)e^(−2iπνv), et les deux intégrales se séparent. Cette preuve explique à la fois le produit spectral et l’identité d’aire en évaluant en ν=0. Pour un système causal, les prolongements nuls avant zéro réduisent l’intégrale aux bornes 0 et t.',
        'Un trapèze calculé par des intervalles',
        'Deux portes de largeurs 1 s et 3 s sont centrées en 0 et 2 s. Déterminer support, plateau, hauteur maximale et aire de leur convolution.',
        'Le centre du résultat est d=2 s. Son support fermé est [2−(1+3)/2,2+(1+3)/2]=[0,4]. Le plateau existe pour |t−2|≤(3−1)/2=1, donc t∈[1,3], à hauteur min(1,3)=1 s. Les bords montent et descendent linéairement sur une seconde. L’aire vaut L₁L₂=3 s² ; on la retrouve par le rectangle central d’aire 2 et deux triangles d’aire 1/2 chacun.',
        'Un triangle d’aire 1 et son spectre',
        'Poser qL(t)=Π(t/L)/L. Calculer qL*qL et sa TF ; vérifier l’aire et la valeur au centre. Que devient cette famille quand L→0 ?',
        'La convolution vaut (1/L)(1−|t|/L) pour |t|<L et 0 sinon. Sa TF est sincₙ²(Lν), son aire est 1 et sa valeur au centre est 1/L. Elle agit sur une fonction test comme une moyenne triangulaire de support rétrécissant, donc tend vers δ au sens des distributions. Son point haut diverge ; il ne s’agit pas de convergence uniforme vers une fonction ordinaire.'),
    record('gibbs_fourier', 'Un saut survit dans les sommes partielles', 'Spé ; premières harmoniques accessibles en Sup',
        'Les pages 110-111 associent créneaux, rampes et triangles à leurs séries de Fourier. L’expérience compare Sₙ, qui garde les harmoniques |k|≤N, et la moyenne de Fejér σₙ, qui pondère chaque coefficient par 1−|k|/(N+1). Les deux reconstructions ont des comportements différents au voisinage d’un saut.',
        'Créneau ±1 : f(t)=(4/π)Σk≥0 sin[2π(2k+1)t/T]/(2k+1)\nσN=Σ|k|≤N(1−|k|/(N+1))cₖe^(2iπkt/T)',
        'Les coefficients d’un créneau décroissent comme 1/k. La série converge vers la demi-somme des limites latérales aux sauts, mais les sommes partielles développent un dépassement qui se resserre sans disparaître en hauteur. La limite du dépassement vaut environ 0,08949 fois le saut. Un triangle continu possède des coefficients en 1/k², donc une convergence normale et uniforme.',
        'Le curseur N est le dernier indice harmonique, pas le nombre de termes non nuls. Le créneau n’utilise que les indices impairs. La moyenne de Fejér élargit la transition mais limite le dépassement grâce à un noyau positif ; sa stabilité peut être préférable à une troncature brutale.',
        'Fejér est une moyenne positive',
        'La moyenne des N+1 premières sommes partielles est une convolution périodique avec un noyau positif de masse 1. Elle conserve donc les bornes d’un signal réel borné, contrairement au noyau de Dirichlet.',
        'KN(θ)=[sin((N+1)θ/2)]²/[(N+1)sin²(θ/2)]≥0\nKN(0)=N+1, par prolongement aux points 2πℤ\n(1/2π)∫₋π^πKN(θ)dθ=1\nσN(f)=(1/2π)∫₋π^πKN(u)f(θ−u)du',
        'Développer la somme géométrique Σj=0ᴺe^(ijθ), puis son module carré, donne les poids triangulaires 1−|k|/(N+1). Le coefficient constant du noyau est 1, d’où sa masse normalisée. Si m≤f≤M, multiplier par le noyau positif et intégrer fournit m≤σN(f)≤M. Pour f continue périodique, la concentration du noyau donne la convergence uniforme.',
        'Une série uniforme ne peut créer un saut',
        'Montrer sans calcul de maximum que les sommes de Fourier d’un créneau ne convergent pas uniformément sur une période entière. Cela interdit-il la convergence en moyenne quadratique ?',
        'Chaque somme partielle est continue. Une limite uniforme de fonctions continues serait continue, tandis que le créneau et sa version à demi-somme restent discontinus aux raccords. La convergence uniforme est donc impossible sur toute la période. Elle n’interdit pas la convergence L² : les coefficients en 1/k donnent une somme de carrés convergente et Parseval contrôle l’énergie du reste.',
        'Le triangle normalisé possède une série normale',
        'Pour le triangle f(t)=|2t/T| sur [−T/2,T/2], prolongé périodiquement, retrouver sa moyenne et justifier la convergence normale de f=1/2−(4/π²)Σk≥0 cos[2π(2k+1)t/T]/(2k+1)².',
        'La moyenne de |2t/T| sur une période vaut 1/2. La fonction est paire ; les coefficients sinusoïdaux sont nuls. Deux intégrations par parties par morceaux donnent an=−4/(π²n²) pour n impair et 0 pour n pair. La série des normes est majorée par (4/π²)Σ1/(2k+1)², convergente. La limite est donc continue et uniforme, en cohérence avec les raccords continus du triangle.'),
    record('parseval_spectre', 'Une somme de carrés devient une énergie', 'Spé',
        'L’énergie moyenne d’un signal périodique est E=(1/T)∫₀ᵀ|f|²dt. Les coefficients cₙ sont normalisés par 1/T. Parseval affirme E=Σ|cₙ|², ou, pour une fonction réelle, E=a₀²/4+(1/2)Σ(an²+bn²). Une aire sur une période et une puissance moyenne ne possèdent pas le même facteur T.',
        'E=Σn∈ℤ|cₙ|²=a₀²/4+(1/2)Σn≥1(an²+bn²)\n‖f−SN‖²moy=E−Σ|n|≤N|cₙ|²',
        'Les fonctions e^(2iπnt/T) sont orthonormales pour le produit scalaire (1/T)∫f ḡ. Développer le carré d’une somme partielle élimine les termes croisés. La projection minimise ensuite l’erreur L² dans l’espace des harmoniques retenues. Le théorème de complétude permet de passer de Bessel à Parseval pour f dans L² périodique.',
        'Pour le créneau ±1, E=1 et bn=4/(πn) pour n impair : Σk≥0 1/(2k+1)²=π²/8. Pour le triangle entre 0 et 1, E=1/3, la composante moyenne contribue 1/4 et les autres donnent Σ1/(2k+1)⁴=π⁴/96. La somme de Bâle et ζ(4) en découlent en séparant indices pairs et impairs.',
        'Une projection harmonique est le meilleur compromis L²',
        'L’orthogonalité fixe les coefficients optimaux indépendamment de la forme graphique du signal. Ajouter un mode augmente l’énergie capturée sans détériorer l’erreur quadratique, même si un dépassement ponctuel augmente.',
        '‖f−v‖²=‖f−SN‖²+‖SN−v‖²\nv appartient à span{e^(2iπkt/T), |k|≤N}',
        'Le résidu f−SN est orthogonal à chaque mode retenu, donc à SN−v. Le développement du carré donne Pythagore. Les notions de meilleur ajustement quadratique, de Gibbs et de convergence uniforme répondent ainsi à trois questions différentes : une projection optimale L² ne minimise pas automatiquement l’erreur maximale.',
        'Retrouver ζ(2) à partir d’un créneau',
        'Sachant Σk≥0 1/(2k+1)²=π²/8, calculer Σn≥1 1/n². Quel pourcentage de l’énergie du créneau est contenu dans sa première harmonique ?',
        'En séparant les pairs, ζ(2)=π²/8+ζ(2)/4, donc ζ(2)=π²/6. La première harmonique contribue b₁²/2=8/π²≈0,8106, soit 81,06 % de l’énergie moyenne totale. Ce nombre n’est pas le pourcentage d’amplitude ou une erreur uniforme : le créneau reste mal reproduit près de ses sauts malgré une forte énergie capturée.',
        'Un triangle et la puissance quatrième',
        'Pour un triangle entre 0 et 1, E=1/3 et a₀=1. Les coefficients non constants valent −4/(π²n²) pour n impair. Déduire les sommes sur les impairs et sur tous les entiers en puissance quatrième.',
        'Parseval donne 1/3=1/4+(8/π⁴)Σimpairs1/n⁴. La différence 1/12 conduit à Σimpairs1/n⁴=π⁴/96. Puis ζ(4)=π⁴/96+ζ(4)/16, donc ζ(4)=π⁴/90. La composante continue ne doit pas être oubliée : elle porte à elle seule une énergie 1/4, et son absence changerait la somme obtenue.'),
    record('poisson_noyau', 'Une série normale fabrique un filtre de lissage', 'Spé ; prolongement harmonique',
        'Le noyau de Poisson de la page 108 est Pᵣ(t)=Σk∈ℤr^|k|e^(2iπkt/T), avec |r|<1. Le banc emploie 0≤r<1. La série est normale puisque Σr^|k| converge, et sa masse sur une période vaut T. Le filtre normalisé est donc une convolution périodique par Pᵣ/T.',
        'Pᵣ(t)=(1−r²)/(1−2r cos(2πt/T)+r²)\n∫₀ᵀPᵣ(t)dt=T\nReste après |k|≤N : ‖RN‖∞≤2r^(N+1)/(1−r)',
        'Séparer k=0, k>0 et k<0 puis sommer deux séries géométriques donne la forme fermée. Le coefficient constant vaut 1, ce qui explique la masse. Pour le reste, chaque exponentielle a un module 1 ; la somme des deux queues géométriques fournit une majoration uniforme indépendante de t. À r proche de 1, un petit N peut donc être très insuffisant.',
        'Filtrer une série de Fourier multiplie son coefficient cₖ par r^|k|. Les hautes harmoniques sont davantage atténuées. Quand r→1⁻, le noyau devient étroit et haut autour des multiples de T ; il approche l’identité pour les signaux continus, avec une valeur de demi-somme aux sauts réguliers.',
        'La positivité donne un principe de maximum',
        'Pour 0≤r<1, Pᵣ est positif et de masse T. Son action sur un signal réel borné est donc une moyenne pondérée ; elle ne crée pas de valeur extérieure à l’intervalle des amplitudes d’entrée.',
        '(Pᵣ*f)pér(t)=(1/T)∫₀ᵀPᵣ(t−u)f(u)du\nm≤f≤M ⇒ m≤(Pᵣ*f)pér≤M',
        'Le numérateur 1−r² est positif et le dénominateur est |1−re^(2iπt/T)|²>0. On multiplie les inégalités m≤f≤M par Pᵣ/T et intègre ; la masse normalisée vaut 1. La convergence vers f pour r→1 utilise ensuite la continuité uniforme sur une période et le fait que la masse hors d’un petit voisinage de zéro tend vers zéro.',
        'Dimensionner une troncature proche de r=1',
        'Pour r=0,9, combien d’harmoniques N suffisent à garantir un reste uniforme au plus 0,01 ? Utiliser seulement la majoration géométrique.',
        'La condition 2×0,9^(N+1)/0,1≤0,01 équivaut à 0,9^(N+1)≤0,0005. Donc N+1≥ln(0,0005)/ln(0,9)≈72,14. Le plus petit entier satisfaisant cette borne est N=72. Il s’agit d’une garantie suffisante ; les annulations peuvent réduire l’erreur ailleurs. Le ralentissement lorsque r approche 1 relie concrètement convergence normale et coût du calcul.',
        'Un filtrage qui garde exactement la moyenne',
        'Un signal possède c₀=3, c₁=c₋₁=1 et c₂=c₋₂=1/2. Écrire sa version filtrée par le noyau avec r=1/2. Calculer l’énergie avant et après.',
        'L’entrée vaut 3+2cos(2πt/T)+cos(4πt/T). Les coefficients deviennent c₀=3, c±1=1/2 et c±2=1/8, donc la sortie vaut 3+cos(2πt/T)+(1/4)cos(4πt/T). Parseval donne Eavant=9+2+1/2=11,5 et Eaprès=9+1/2+1/32=9,53125. La moyenne reste 3, tandis que l’énergie des variations décroît.'),
    record('poisson_gaussienne', 'Poisson : périodiser le temps discrétise le spectre', 'Spé ; prolongement harmonique',
        'La page 108 relie un signal s et sa périodisation f(t)=Σk∈ℤs(t+kT). Pour la gaussienne s(t)=exp[−t²/(2σ²)], toutes les dérivées décroissent rapidement : les échanges de séries et d’intégrales se justifient. Les deux constructions affichées sont une somme de gaussiennes dans le temps et une série de cosinus.',
        'cₙ=ŝ(n/T)/T=(σ√(2π)/T)e^(−2π²σ²n²/T²)\nf(t)=c₀+2Σn≥1cₙcos(2πnt/T)',
        'Dans cₙ=(1/T)∫₀ᵀΣks(t+kT)e^(−2iπnt/T)dt, poser u=t+kT pour chaque terme. Les intervalles [kT,(k+1)T] couvrent ℝ et le facteur e^(2iπnk) vaut 1 : on obtient ŝ(n/T)/T. Insérer la TF gaussienne donne les coefficients. Leur décroissance quadratique exponentielle assure la convergence normale de la série spectrale.',
        'Lorsque σ/T est petit, les impulsions sont séparées et de nombreuses raies sont utiles. Lorsque σ/T est grand, la périodisation varie peu et c₀ domine. Le banc augmente automatiquement la borne de la somme directe pour couvrir les gaussiennes éloignées ; N règle surtout la troncature spectrale, dont l’erreur n’est pas celle de l’identité exacte.',
        'La formule de Jacobi comme cas particulier de Poisson',
        'Évaluer une périodisation gaussienne en zéro transforme une somme lentement convergente en une autre rapidement convergente. Cette dualité relie Fourier aux fonctions thêta et donne une technique de calcul.',
        'Σk∈ℤe^(−πa k²)=(1/√a)Σn∈ℤe^(−πn²/a), a>0',
        'Appliquer Poisson avec T=1 à s(t)=e^(−πa t²), dont la TF en Hz vaut a^(−1/2)e^(−πν²/a). Si a est petit, la somme directe exige beaucoup de k ; la somme duale a des termes exponentiellement faibles dès |n|=1. Pour a grand, on choisit l’autre côté. Le changement de représentation accélère le calcul sans changer la quantité mathématique.',
        'Une moyenne qui ne dépend pas du recouvrement',
        'Une gaussienne de largeur σ=0,30 s est répétée toutes les T=1,50 s. Trouver la moyenne de la périodisation et le rapport c₁/c₀. Interpréter les unités.',
        'La moyenne vaut c₀=σ√(2π)/T≈0,5013. Le rapport c₁/c₀=e^(−2π²(0,30/1,50)²)≈0,4540. La TF ŝ a l’unité seconde pour une amplitude sans unité ; la division par T donne des coefficients sans unité. La moyenne est l’aire d’une impulsion divisée par la période, même lorsque les impulsions se recouvrent.',
        'Choisir le côté rapide d’une identité',
        'Estimer Σk∈ℤe^(−π·0,01·k²) en utilisant la forme duale. Quelle valeur dominante apparaît, et quel ordre de grandeur a le premier terme omis si l’on garde seulement n=0 ?',
        'Poisson donne 10Σn∈ℤe^(−100πn²), donc la valeur dominante est 10. Les deux premiers termes non nuls donnent une correction 20e^(−100π), inférieure à 10⁻¹³⁴ ; les autres sont beaucoup plus petits. La somme directe possède au contraire plusieurs termes significatifs autour de zéro. L’exemple montre l’intérêt algorithmique de la transformée, au-delà d’une simple vérification graphique.'),
    record('shannon', 'Shannon : un support spectral avant une reconstruction', 'Spé ; signal selon filière',
        'Le paquet s(t)=sincₙ²(Bt)cos(2πf₀t) appartient à L¹ et L², contrairement à une sinusoïde permanente. B est en Hz et décrit la demi-largeur des deux triangles spectraux, centrés en ±f₀. La plus grande fréquence du support est W=f₀+B. Le banc prend F>2W comme critère strict de marge avant de reconstruire.',
        'ŝ(ν)=[Λ((ν−f₀)/B)+Λ((ν+f₀)/B)]/(2B)\nΛ(u)=max(1−|u|,0)\ns(t)=Σn∈ℤs(n/F)sincₙ(Ft−n), si F>2W',
        'La TF de sincₙ(Bt) est une porte de hauteur 1/B et de largeur B. Le carré dans le temps convolue ces deux portes dans le spectre, donnant Λ(ν/B)/B. Multiplier par cos(2πf₀t) crée deux translations, avec un facteur 1/2. Le peigne de pas 1/F répète ensuite ce spectre tous les F Hz, avec facteur F ; un filtre de gain 1/F dans la bande centrale restitue le signal.',
        'La formule utilise une infinité d’échantillons. L’expérience n’en garde que 2M+1 : au-dessus du seuil, une erreur peut encore provenir de cette troncature. Augmenter M à F fixé sépare cet effet du repliement. Le seuil exact au bord demande de préciser la classe de signaux : en L², des valeurs spectrales ponctuelles ne comptent pas comme une raie de Dirac.',
        'La sinc interpolatrice et son facteur de gain',
        'Poser a=1/F et φ=s·Σδ(t−na). L’échantillonnage multiplie par un peigne dans le temps, donc crée des copies spectrales. Le facteur de reconstruction vient de l’aire des impulsions et ne peut pas être omis.',
        'φ̂(ν)=FΣk∈ℤŝ(ν−kF)\nŝ(ν)=(1/F)φ̂(ν)Π(ν/F)\nTF⁻¹[(1/F)Π(ν/F)]=sincₙ(Ft)',
        'Le filtre idéal garde seulement la copie centrale lorsque les bandes sont séparées. La TF inverse de Π(ν/F) vaut F sincₙ(Ft), et le gain 1/F annule ce F. Convoluer les impulsions de poids s(n/F) avec sincₙ(Ft) donne la somme de Shannon. Aux instants j/F, sincₙ(j−n)=0 pour j≠n et vaut 1 pour j=n : les mesures sont exactement interpolées.',
        'Un paquet possède une bande entière, pas une seule fréquence',
        'Pour B=3 Hz et f₀=5 Hz, tracer mentalement le support de ŝ. Parmi F=12,16,24 Hz, quelle fréquence possède une marge strictement positive ? Une somme sinc finie y est-elle exacte partout ?',
        'Les bandes sont [2,8] et [−8,−2] Hz ; W=8. Le critère strict est F>16. F=12 entraîne un chevauchement des copies, F=16 est le bord sans marge et F=24 laisse une marge. À F=24, l’identité exacte exige tous les n∈ℤ. Une somme finie reste une approximation ; en particulier des échantillons extérieurs à la fenêtre affichée contribuent encore à l’intérieur.',
        'Vérifier l’interpolation ne vérifie pas le théorème',
        'Soit rM(t)=Σn=−Mᴹs(n/F)sincₙ(Ft−n). Montrer que rM(j/F)=s(j/F) pour |j|≤M, même lorsque F est trop faible. Pourquoi la réussite aux points mesurés ne détecte-t-elle pas l’aliasing ?',
        'À t=j/F, toutes les sinc sauf n=j s’annulent, donc rM(j/F)=s(j/F). Cette propriété algébrique ne dépend pas du support spectral. Un signal replié peut partager les mêmes mesures avec un autre signal à bande plus basse ; la reconstruction les interpole mais choisit alors cette autre possibilité entre les instants. Le contrôle spectral doit précéder la comparaison des points.'),
    record('aliasing', 'Les mesures identifient une fréquence modulo F', 'Sup → Spé',
        'Une sinusoïde de fréquence f est mesurée aux instants k/F. Ajouter un multiple entier de F à f ne change aucune valeur de l’exponentielle complexe. Le représentant signé dans [−F/2,F/2[ conserve aussi la phase ; prendre seulement sa valeur absolue demanderait d’adapter cette phase.',
        'e^(2iπ(f+ℓF)k/F)=e^(2iπfk/F), ℓ∈ℤ\nfₐ=((f+F/2) modulo F)−F/2\nsin(2πfk/F+φ)=sin(2πfₐk/F+φ)',
        'La différence des arguments est 2πℓk, multiple de 2π. Les signaux sont identiques sur la grille, mais distincts entre ses points. Pour F=24 Hz et f=19 Hz, le représentant est −5 Hz. La courbe sin(−2π5t+φ) a exactement les mêmes valeurs mesurées. L’ambiguïté est une perte d’information, pas une erreur du calcul de FFT.',
        'Le cas f=F/2 mérite une expérience séparée : sin(πk+φ)=(−1)ᵏsinφ. Les phases φ et π−φ deviennent indiscernables, et une phase nulle produit une suite entièrement nulle. Les sinusoïdes permanentes ont une énergie infinie ; elles servent ici à démontrer l’ambiguïté et ne sont pas confondues avec le paquet de Shannon.',
        'Un repliement négatif change la lecture de la phase',
        'Pour une sinusoïde réelle, un représentant fréquentiel négatif peut être écrit à fréquence positive, mais sa phase est modifiée. Cela explique les animations où le motif semble tourner dans l’autre sens.',
        'sin(−ωt+φ)=sin(ωt+π−φ)\ncos(−ωt+φ)=cos(ωt−φ)',
        'Ces identités suivent des parités du sinus et du cosinus. Elles évitent d’attribuer au signal apparent la phase initiale inchangée à la fréquence positive. Un signal complexe distingue le sens de rotation par le signe de la fréquence ; un signal réel combine nécessairement des fréquences opposées conjuguées.',
        'Deux fréquences exactes, une seule suite',
        'Un capteur mesure à 30 Hz un signal sin(2π·23t+π/6). Trouver son représentant signé et une écriture à fréquence positive donnant les mêmes échantillons.',
        'Le représentant est 23−30=−7 Hz. La suite est celle de sin(−2π·7t+π/6), soit sin(2π·7t+5π/6). La différence des arguments entre 23 et −7 Hz vaut 2πk aux instants k/30. Entre ces instants les courbes diffèrent ; aucune méthode fondée sur ces seules mesures ne peut choisir la fréquence physique sans hypothèse supplémentaire.',
        'À Nyquist, une sinusoïde peut disparaître',
        'Pour F=40 Hz et f=20 Hz, comparer les phases 0, π/2 et π/6. Peut-on déduire toute la phase d’une suite non nulle ?',
        'Les suites valent respectivement 0, (−1)ᵏ et (1/2)(−1)ᵏ. La mesure ne connaît que sinφ ; π/6 et 5π/6 donnent donc la même suite. Une phase 0 ou π efface entièrement une sinusoïde pourtant non nulle entre les points. Ce contre-exemple justifie une marge stricte dans une expérience de mesure de sinusoïdes arbitraires.'),
    record('anti_repliement', 'Un filtre analogique précède la perte d’information', 'Spé ; SI et physique selon filière',
        'La chaîne contient une composante utile de 3 Hz et une perturbation de fréquence fₚ, puis un échantillonneur de cadence F. Un Butterworth analogique d’ordre n et coupure fc atténue la perturbation avant la mesure. Le module seul ne suffit pas à recomposer les sinusoïdes : la phase complexe est aussi utilisée.',
        '|H(i2πν)|=1/√[1+(ν/fc)^(2n)]\npₖ=2πfc exp[iπ(2k+1+n)/(2n)], k=0,…,n−1\nH(p)=Πk[−pₖ/(p−pₖ)] ; H(0)=1',
        'Les pôles sont tous dans le demi-plan gauche ; les paires conjuguées produisent un filtre réel stable. À ν=fc, le gain est 1/√2 quel que soit n. À haute fréquence, la pente asymptotique vaut −20n dB par décade. Le banc filtre chaque composante en régime permanent par son gain complexe, puis mesure la sortie aux instants k/F.',
        'Un parasite de 72 Hz mesuré à 50 Hz se replie à 22 Hz. Le filtre peut réduire son amplitude, mais un filtre numérique placé après la mesure ne connaît plus son origine à 72 Hz. Un Butterworth n’a pas de support spectral strictement borné : l’atténuation limite le repliement, elle ne transforme pas le signal en signal parfaitement bandé.',
        'Déterminer l’ordre d’un filtre à partir d’une spécification',
        'Une contrainte de gain à une fréquence supérieure à fc donne un ordre minimal par un logarithme. Il faut ensuite contrôler l’atténuation de la composante utile et accepter une phase associée au filtre causal.',
        'Gain à fp ≤ ε ⇒ (fp/fc)^(2n)≥ε⁻²−1\nn≥ln(ε⁻²−1)/[2ln(fp/fc)], fp>fc',
        'Mettre au carré l’inégalité 1/√(1+x^(2n))≤ε, puis isoler x^(2n). Comme x>1, le logarithme est croissant et positif, d’où la borne sur n. On prend ensuite le plus petit entier admissible. Le gain à la fréquence utile se calcule séparément : une bonne suppression du parasite ne garantit pas la fidélité de toute la bande utile.',
        'Un ordre minimal chiffré',
        'Avec fc=10 Hz, on impose une amplitude parasite à 60 Hz inférieure à 1 % de l’amplitude initiale. Calculer l’ordre Butterworth minimal, puis le gain à 3 Hz.',
        'Il faut n≥ln9999/(2ln6)≈2,57, donc n=3. Le gain à 60 Hz vaut 1/√(1+6⁶)≈0,00463, inférieur à 0,01. À 3 Hz, le gain est 1/√(1+0,3⁶)≈0,999636. Le calcul porte sur des amplitudes, d’où le seuil −40 dB pour 1 %. L’ordre 2 ne suffit pas : son gain à 60 Hz vaut environ 0,0278.',
        'Un parasite replié sur le signal utile devient indissociable',
        'Un signal utile de 8 Hz et un parasite de 42 Hz sont mesurés à F=50 Hz. Montrer que le parasite se replie sur la même fréquence absolue. Un passe-bas numérique peut-il séparer les deux contributions ?',
        'Le représentant signé de 42 Hz est 42−50=−8 Hz. Pour des signaux réels, cela correspond à une composante de 8 Hz avec une phase adaptée. Après mesure, les deux contributions occupent la même fréquence et se combinent en amplitude et phase. Un filtre numérique agissant sur 8 Hz modifie les deux ensemble ; la distinction requiert une hypothèse supplémentaire ou un filtrage analogique préalable.'),
    record('fenetres_fft', 'Une FFT observe un signal multiplié par une fenêtre', 'Spé ; prolongement numérique',
        'N valeurs sont acquises à F=128 Hz, aux instants k/F, k=0,…,N−1. La durée DFT est T=N/F et le pas natif F/N. Une fréquence située entre deux cases produit une fuite spectrale. La fenêtre de Hann ou de Blackman réduit les lobes secondaires en élargissant le lobe principal ; le signal observé est le produit xkwk.',
        'Xj=Σk=0ᴺ⁻¹xkwk e^(−2iπjk/N)\nAmplitude positive isolée ≈2|Xj|/Σwk\nCG=(1/N)Σwk ; ENBW=FΣwk²/(Σwk)²',
        'La fenêtre finie transforme une raie infiniment fine en une copie de son propre spectre. Diviser par Σw corrige le gain cohérent d’une raie sur une case ; cela ne corrige pas exactement tous les biais hors case ni le recouvrement de raies voisines. Les amplitudes DC et Nyquist ne sont pas doublées : ces cases n’ont pas une partenaire distincte dans la représentation monolatérale.',
        'Le zero padding n’ajoute aucune mesure. Il échantillonne plus densément le même polynôme trigonométrique et permet de mieux lire un maximum interpolé. Le banc affiche séparément F/N, F/(Nq), le gain cohérent et la bande équivalente de bruit, pour éviter de confondre calibration, interpolation et résolution.',
        'Distinguer DFT et approximation d’une TF continue',
        'La DFT est une somme algébrique de N valeurs sans unité de temps ajoutée. Une approximation de l’intégrale de Fourier exige le pas Δt, et une origine temporelle t₀ ajoute une phase.',
        'f̂(νj)≈Δt e^(−2iπνjt₀)Σk=0ᴺ⁻¹f(t₀+kΔt)e^(−2iπjk/N)\nνj=j/(NΔt) ; TF en Hz',
        'C’est la somme de Riemann de f(t)e^(−2iπνjt). À chaque instant, l’exponentielle se factorise en une phase d’origine puis en e^(−2iπjk/N). Omettre Δt change la normalisation et les unités ; omettre t₀ change la phase mais pas le module. La troncature temporelle et le remplacement par une somme restent deux approximations distinctes.',
        'Calibrer une raie exactement sur une case',
        'Un cosinus d’amplitude 2 à 10 Hz est mesuré à 128 Hz sur N=256 points, sans fenêtre autre que la rectangulaire. Trouver l’indice de sa case positive et son module DFT. Refaire avec une fenêtre de Hann périodique.',
        'Le pas est 128/256=0,5 Hz, donc j=20. La raie positive vaut N×2/2=256 ; le doublement monolatéral et la division par N redonnent 2. La Hann périodique a Σw=N/2=128 ; pour cette raie isolée, son module central vaut AΣw/2=128 et 2|X|/Σw redonne encore 2. Les cases voisines sont remplies par le lobe de la fenêtre.',
        'Des zéros changent une grille, pas une acquisition',
        'Avec N=128 à F=128 Hz, comparer une FFT de 128 points et une FFT après ajout de zéros jusqu’à 1024 points. Donner les pas et la durée de mesure. Quelles informations restent identiques ?',
        'La durée d’acquisition reste T=1 s et le pas natif est 1 Hz. Le zero padding donne un pas de lecture 0,125 Hz. Les 128 valeurs mesurées, la fenêtre temporelle, ses lobes et le bruit acquis restent identiques. Le spectre est mieux interpolé ; deux raies que le lobe ne sépare pas ne deviennent pas séparées parce que l’on affiche davantage de points.'),
    record('resolution', 'La durée de mesure distingue des fréquences proches', 'Sup → Spé ; expérimentation numérique',
        'Deux cosinus d’amplitudes égales ont des fréquences 18 et 18+Δf Hz. Leur somme possède des battements et leur spectre observé résulte de deux lobes de fenêtre qui peuvent se recouvrir. Le banc garde F=128 Hz et compare une acquisition longue à un simple ajout de zéros.',
        'cos(2πf₁t)+cos(2πf₂t)=2cos(πΔft)cos[2π(f₁+f₂)t/2]\nT=N/F ; pas natif=1/T ; premiers zéros de Hann à environ ±2/T',
        'La formule trigonométrique distingue une porteuse à la fréquence moyenne et une enveloppe de module 2|cos(πΔft)|. Si ΔfT est petit, la fenêtre ne montre qu’une faible partie d’un battement et les lobes se recouvrent fortement. Allonger T réduit les lobes en fréquence ; ajouter des zéros augmente seulement le nombre de points d’affichage.',
        'Le repère 1/T est un pas de grille, pas une loi universelle de séparation de deux pics. La fenêtre, le rapport d’amplitudes, les phases et le bruit comptent aussi. Pour Hann, la largeur entre premiers zéros d’un lobe est environ 4/T : une séparation critique différente apparaît selon le critère retenu.',
        'Battements : enveloppe signée et enveloppe observée',
        'L’enveloppe signée cos(πΔft) et son module n’ont pas la même période. Les maxima visibles d’intensité ou de module se répètent avec période 1/Δf, tandis que le facteur signé a période 2/Δf.',
        'A(t)=2|cos(πΔft)|\nPériode des maxima de A : 1/Δf ; premiers minima : 1/(2Δf)',
        'Les maxima de |cos θ| se reproduisent après π plutôt qu’après 2π. Les zéros apparaissent à θ=π/2+kπ, donnant les dates (k+1/2)/Δf. Cette distinction évite un facteur deux lorsque l’on mesure l’écart des fréquences à partir de battements acoustiques ou d’un oscilloscope.',
        'Mesurer un écart avec des battements',
        'Deux sons proches présentent des maxima d’enveloppe toutes les 0,40 s. Calculer l’écart de fréquences et la date du premier minimum si les deux cosinus sont en phase en t=0. Une acquisition de 0,10 s contient-elle un battement complet ?',
        'L’écart vaut Δf=1/0,40=2,5 Hz. Le premier minimum arrive à 1/(2Δf)=0,20 s. Une durée de 0,10 s ne couvre pas même ce premier minimum ; elle contient seulement une portion du motif de battement. La précision d’une analyse paramétrique peut dépendre du modèle et du bruit, mais la fenêtre ne présente pas directement un cycle complet.',
        'Comparer durée et interpolation',
        'Pour F=128 Hz, comparer N=64 avec padding 8 et N=512 avec padding 1. Les deux grilles spectrales ont-elles le même pas ? Leurs lobes de Hann ont-ils la même largeur ?',
        'Les deux calculs affichent un pas 128/512=0,25 Hz. Pourtant les durées sont respectivement 0,5 s et 4 s. Les largeurs entre premiers zéros de Hann sont environ 4/T, soit 8 Hz et 1 Hz. Une grille identique masque donc des résolutions très différentes : dans le premier cas on a interpolé une acquisition courte, dans le second acquis huit fois plus longtemps.'),
    record('spectrogramme', 'Un chirp ne possède pas une seule fréquence permanente', 'Spé ; prolongement temps–fréquence',
        'Le chirp est x(t)=cos[2π(f₀t+kt²/2)]. Sa fréquence instantanée est la dérivée de sa phase divisée par 2π : ν(t)=f₀+kt. L’expérience dure 3 s et échantillonne à 128 Hz. Une fenêtre mobile de L valeurs permet de localiser les fréquences au cours du temps.',
        'STFTx(t₀,ν)=∫x(t)w(t−t₀)e^(−2iπνt)dt\nνinst(t)=f₀+kt ; durée locale L/F ; pas natif F/L',
        'On extrait chaque segment, le multiplie par une Hann et calcule une FFT locale. Une fenêtre courte suit un changement rapide mais possède un lobe spectral large. Une fenêtre longue réduit ce lobe, mais le chirp parcourt alors plusieurs fréquences pendant la fenêtre, ce qui étale aussi l’énergie. La carte affiche des dB relatifs à son propre maximum, avec un plancher −65 dB.',
        'Les zéros ajoutés à 256 points densifient les colonnes de fréquence ; ils ne changent pas la durée locale L/F. La ligne ν=f₀+kt sert de repère analytique. Une crête de carte est une estimation issue de données fenêtrées, pas une preuve que le signal était stationnaire dans chaque segment.',
        'Un compromis contrôlé par deux largeurs',
        'Pour un chirp linéaire, une fenêtre de durée τw voit une variation de fréquence |k|τw. Son propre étalement est de l’ordre de 1/τw. Leur comparaison donne un ordre de grandeur pour choisir une fenêtre adaptée au balayage.',
        'Variation dans une fenêtre : |k|τw\nÉtalement d’une fenêtre : C/τw\nÉquilibre d’échelles : τw de l’ordre de 1/√|k|',
        'La première largeur augmente avec τw, la seconde diminue. En les équilibrant sans prétendre fixer une constante universelle, on obtient τw² de l’ordre de 1/|k|. Le choix final dépend de la fenêtre et du critère de lecture. Cette argumentation d’échelles explique pourquoi la plus longue fenêtre n’est pas toujours la meilleure pour un signal dont la fréquence varie.',
        'Calculer une fréquence instantanée',
        'Un chirp passe de 8 Hz à 48 Hz en 3 s. Écrire sa phase, sa fréquence à 1,2 s et le nombre de périodes de phase accumulées pendant les 3 s.',
        'La pente vaut k=(48−8)/3=40/3 Hz/s. La phase est 2π(8t+(20/3)t²), à une constante près. À 1,2 s, ν=8+(40/3)×1,2=24 Hz. Le nombre de périodes accumulées est ∫₀³ν(t)dt=8×3+(40/3)×9/2=84. Ce nombre dépend de la fréquence moyenne 28 Hz, et non uniquement de la fréquence finale.',
        'Une carte relative n’est pas un niveau absolu',
        'La carte emploie D=10log₁₀(P/Pmax). Quelle puissance relative représentent −20 dB et −40 dB ? Si l’amplitude du chirp est doublée, la carte renormalisée change-t-elle ?',
        '−20 dB correspond à P/Pmax=10⁻² et −40 dB à 10⁻⁴. Doubler l’amplitude multiplie toutes les puissances par quatre, y compris Pmax ; les rapports restent identiques et la carte relative ne change pas. Pour une calibration absolue, il faudrait conserver les unités et une référence de puissance fixe. Le logarithme de puissance utilise 10log, contrairement au 20log d’un rapport d’amplitudes.'),
    record('modulation', 'Multiplier un message déplace son spectre', 'Sup → Spé ; communications en prolongement',
        'La modulation d’amplitude utilise s(t)=[1+m cos(2πfmt)]cos(2πfct). Le message varie à fm, la porteuse à fc ; m est une profondeur sans unité. Pour 0≤m≤1, l’enveloppe signée ne devient pas négative. Le banc compare ce signal et une démodulation synchrone dont l’oscillateur local peut être déphasé ou légèrement désaccordé.',
        's(t)=cos(2πfct)+(m/2)cos[2π(fc−fm)t]+(m/2)cos[2π(fc+fm)t]\nAprès mélange ×2cos[2π(fc+Δf)t+φ] et passe-bas :\ny(t)=[1+m cos(2πfmt)]cos(2πΔft+φ)',
        'Le produit de deux cosinus se transforme en demi-somme aux fréquences somme et différence. Le mélange synchrone ramène une copie vers les basses fréquences et en crée une seconde autour de 2fc ; le passe-bas idéal du modèle retire cette seconde copie. À Δf=0, le gain est cosφ ; à φ=π/2, la composante utile disparaît malgré un signal reçu non nul.',
        'Les barres spectrales positives du banc sont des amplitudes de cosinus : 1 et m/2. En TF bilatérale de distributions, chaque cosinus possède deux Dirac de poids moitié de cette amplitude. Lorsque m>1, l’enveloppe change de signe ; son module ne permet plus de restituer directement le message par un détecteur d’enveloppe.',
        'Le théorème de modulation et ses facteurs 1/2',
        'Pour un signal a intégrable, une exponentielle translate sa TF et un cosinus produit deux translations. Ce théorème s’applique à un paquet de durée finie autant qu’à la décomposition idéale en raies.',
        'TF[a(t)e^(2iπfct)](ν)=â(ν−fc)\nTF[a(t)cos(2πfct)](ν)=[â(ν−fc)+â(ν+fc)]/2',
        'Regrouper les exponentielles dans l’intégrale définit directement â(ν−fc). Décomposer cos=(e^(iθ)+e^(−iθ))/2 donne la seconde égalité. La distinction entre deux bandes complexes et les amplitudes de cosinus réels évite de doubler à tort les coefficients lors d’un bilan d’énergie.',
        'Puissance d’une modulation AM',
        'Pour m=0,8 et une porteuse d’amplitude 1, calculer les amplitudes des bandes latérales et l’énergie moyenne totale du signal idéal. Quelle fraction vient de la porteuse ?',
        'Les deux bandes ont chacune amplitude m/2=0,4. Pour des fréquences distinctes sur une moyenne longue, les cosinus sont orthogonaux : la puissance vaut 1/2+2×0,4²/2=0,66. La porteuse fournit 0,50/0,66≈75,76 %. Plus généralement P=(1/2)(1+m²/2). Le bilan ne s’obtient pas en additionnant les amplitudes, mais leurs carrés avec le facteur 1/2.',
        'Phase perdue et oscillateur local désaccordé',
        'Un démodulateur synchrone a Δf=0 et φ=60°. Quelle fraction d’amplitude récupère-t-il ? Avec φ=0 et Δf=0,5 Hz, à quelle première date le signal démodulé est-il multiplié par zéro ?',
        'À fréquence correcte, le gain cos60° vaut 1/2 : il récupère la moitié de l’amplitude du signal de base, y compris sa composante moyenne. Avec Δf=0,5 Hz, le facteur est cos(πt) ; son premier zéro arrive à t=0,5 s. Ce battement ne vient pas du message mais du désaccord local. Le modèle supprime analytiquement les fréquences proches de 2fc et suppose un canal idéal.'),
    record('correlation_retard', 'Une corrélation estime un retard dans le bruit', 'Spé ; mesure et probabilités',
        'La convention de la page 108 est Cfg(τ)=∫ℝḡ(t)f(t+τ)dt. g est l’impulsion émise, f sa copie retardée reçue et bruitée. Avec cette convention, une réception f(t)=g(t−d) donne un pic à τ=d. Les mesures sont faites à 200 Hz ; le pas de recherche vaut donc 5 ms.',
        'Cfg(τ)=∫ḡ(t)f(t+τ)dt\nγfg(τ)=Cfg(τ)/(‖f‖₂‖g‖₂) ; |γfg|≤1\nDistance aller-retour : D=cτ/2',
        'La corrélation est un produit scalaire glissant : elle devient grande lorsque le signal reçu ressemble à une translation du signal émis. La normalisation utilise les énergies globales, conservées par une translation sur ℝ. La fenêtre de trois secondes et la grille numérique introduisent une troncature et une quantification ; le bruit peut déplacer le maximum entre plusieurs oscillations de l’impulsion codée.',
        'La graine choisit une réalisation reproductible du bruit gaussien, sans changer son écart type théorique. La distance déduite suppose un trajet aller-retour dans un milieu de vitesse c connue. Une grille de 5 ms donne à elle seule un pas de distance c×0,005/2 ; elle ne garantit pas une erreur de mesure de ce seul ordre en bruit fort.',
        'Cauchy–Schwarz et Wiener–Khintchine',
        'La borne de cohérence et la TF de l’autocorrélation se déduisent de produits scalaires et d’un changement de variable. Elles relient la page 108 aux techniques d’espaces préhilbertiens et au bilan spectral d’énergie.',
        'Cff(0)=‖f‖₂² ; Cfg(τ)=conj[Cgf(−τ)]\nTF(Cfg)(ν)=f̂(ν)conj[ĝ(ν)]\nTF(Cff)(ν)=|f̂(ν)|²',
        'Appliquer Cauchy–Schwarz à g et f(·+τ) donne la borne normalisée. Pour la TF, intégrer e^(−2iπντ)ḡ(t)f(t+τ), poser u=t+τ puis séparer les intégrales : f̂(ν)∫ḡ(t)e^(2iπνt)dt. L’autocorrélation est ainsi la TF inverse de la densité d’énergie spectrale. La conjugaison est essentielle pour les signaux complexes.',
        'Fixer le signe du retard',
        'Si f(t)=g(t−0,60), exprimer Cfg(τ) avec Cgg. Pour une vitesse c=350 m/s, calculer la distance d’aller-retour et le pas de distance correspondant à 200 Hz.',
        'Cfg(τ)=∫ḡ(t)g(t+τ−0,60)dt=Cgg(τ−0,60), donc le maximum principal est attendu à τ=0,60 s. La distance vaut 350×0,60/2=105 m et le pas vaut 350/(2×200)=0,875 m. Si l’on échangeait f et g, le pic passerait au retard opposé ; annoncer la convention est donc nécessaire.',
        'Une corrélation maximale n’est pas une certitude statistique',
        'Pourquoi une forte corrélation près du retard attendu est-elle utile, mais ne suffit-elle pas à garantir une distance exacte ? Citer trois sources d’écart déjà présentes dans le banc et proposer une comparaison contrôlée.',
        'La corrélation additionne des produits sur toute l’impulsion et favorise une forme connue, mais le bruit possède aussi des projections sur cette forme. Ici la réalisation finie du bruit, la grille de 5 ms et les maxima secondaires de l’impulsion modulée peuvent déplacer le pic ; la troncature joue aussi. Garder le retard et la vitesse fixes, augmenter le bruit puis changer la graine distingue un comportement moyen de la réussite d’une réalisation particulière. Aucune probabilité d’erreur chiffrée ne découle du seul maximum affiché.'),
    record('debruitage', 'Débruiter distingue bruit résiduel et signal déformé', 'Spé ; prolongement numérique',
        'Un signal utile contient une fondamentale et sa deuxième harmonique. Le banc ajoute un bruit blanc puis applique soit une moyenne glissante causale de M valeurs, soit un filtre récursif de pôle ρ=e^(−1/M). Il filtre aussi le signal utile seul : cette référence sépare la déformation du signal du bruit restant.',
        'Moyenne : yk=(1/M)Σj=0ᴹ⁻¹xk−j\nRC numérique : yk=ρyk−1+(1−ρ)xk\nBruit résiduel=L(s+b)−L(s) ; distorsion=L(s)−s',
        'La linéarité donne L(s+b)=L(s)+L(b). Comparer seulement la sortie à l’entrée propre mélange deux effets : supprimer le bruit et modifier le signal utile. La moyenne glissante possède une phase de retard et des zéros spectraux ; le récursif possède une mémoire exponentielle. Les bilans RMS excluent une partie initiale pour limiter l’effet du repos initial.',
        'Une longue mémoire réduit davantage le bruit blanc indépendant mais peut effacer une harmonique ou retarder fortement la forme. L’expérience donne un facteur de variance théorique et une RMS mesurée sur une réalisation finie : elles n’ont pas à coïncider exactement. La durée et la graine permettent d’interpréter cette fluctuation.',
        'Le bruit blanc donne une somme de carrés de coefficients',
        'Si bk sont centrés, indépendants et de variance σ², une sortie Σhjbk−j possède une variance σ²Σhj². Le calcul justifie des facteurs exacts pour les deux filtres, après extinction du transitoire.',
        'Var(Σhj bk−j)=σ²Σhj²\nMoyenne M : facteur 1/M\nRécursif : facteur (1−ρ)/(1+ρ)',
        'Développer le carré de la somme. Les termes croisés ont une espérance nulle par indépendance et centrage. Pour la moyenne, M coefficients 1/M donnent 1/M. Pour le récursif, hj=(1−ρ)ρʲ, j≥0, et la série géométrique des carrés vaut (1−ρ)²/(1−ρ²)=(1−ρ)/(1+ρ). Un bruit coloré exigerait ses covariances et ne suit pas ce calcul simple.',
        'Réduire le bruit sans oublier le retard',
        'Une moyenne glissante causale de M=9 mesures fonctionne à F=128 Hz. Pour un bruit blanc d’écart type 0,6, calculer l’écart type de sortie théorique et le retard de groupe de la moyenne.',
        'Le facteur de variance est 1/9, donc l’écart type devient 0,6/3=0,2. La réponse harmonique est une exponentielle e^(−iω(M−1)/2) multipliée par un quotient de sinus ; hors changement de signe, son retard est (M−1)/(2F)=8/256=0,03125 s. Cette baisse du bruit n’empêche ni atténuation de certaines fréquences ni décalage du signal.',
        'Récursif : somme infinie et gain statique',
        'Pour yk=ρyk−1+(1−ρ)xk, 0<ρ<1, déterminer la réponse impulsionnelle, son gain statique et le facteur de variance. Comparer sa mémoire au repos initial et au régime permanent.',
        'Au repos, une impulsion en k=0 produit hj=(1−ρ)ρʲ pour j≥0. Leur somme vaut 1 : une entrée constante est retrouvée après le transitoire. Le facteur de variance vaut (1−ρ)/(1+ρ). Pour ρ=e^(−1/M), le transitoire décroît en environ M échantillons par facteur e ; une réalisation commencée en y−1=0 n’est pas immédiatement stationnaire. Écarter un début de signal rend la comparaison au bilan stationnaire plus pertinente.'),
    record('couche_limite', 'Le pic mobile sépare convergence simple et uniforme', 'Sup → Spé',
        'Pour améliorer l’expérience de convergence de la page 99, on commence par fₙ(x)=nx/(1+n²x²) sur [0,1]. Le point x est fixé avant le passage n→∞ en convergence simple. En convergence uniforme, le point le plus défavorable peut au contraire dépendre de n. Le compact [δ,1], δ>0, permet de localiser précisément l’obstacle.',
        'fₙ(x)→0 pour chaque x∈[0,1]\nfₙ′(x)=n(1−n²x²)/(1+n²x²)²\n‖fₙ‖∞,[0,1]=1/2 en x=1/n ; ‖fₙ‖∞,[δ,1]≤1/(nδ)',
        'En x=0 la valeur est nulle. En x>0, on a fₙ(x)≤1/(nx), donc la limite est zéro. La dérivée s’annule à 1/n et change de signe : le maximum vaut 1/2. Il ne tend pas vers zéro, donc la convergence uniforme échoue sur [0,1]. Sur [δ,1], la borne indépendante de x tend vers zéro ; la convergence y est uniforme.',
        'La variable de loupe u=nx montre fₙ(u/n)=u/(1+u²), un profil qui ne dépend pas de n. La bosse devient étroite sans perdre de hauteur. Une grille fixe peut manquer son sommet et donner l’impression d’une convergence uniforme : le maximum analytique est donc calculé indépendamment du tracé.',
        'Les quantificateurs font la différence',
        'La convergence simple laisse le rang dépendre de x ; la convergence uniforme exige un rang qui convient simultanément à tous les x du domaine. Choisir xₙ=1/n fournit un contre-exemple directement adapté à cette différence.',
        'Simple : ∀x,∀ε>0,∃N(x,ε),∀n≥N, |fₙ(x)|≤ε\nUniforme : ∀ε>0,∃N(ε),∀n≥N,∀x, |fₙ(x)|≤ε',
        'Pour ε=1/4, aucun rang N ne peut contrôler tous les x puisque, pour chaque n≥N, xₙ=1/n donne fₙ(xₙ)=1/2. Ce point mobile ne contredit pas la convergence simple : dans cette dernière, x est fixé une fois pour toutes. Sur [δ,1], N>1/(δε) convient, ce qui exhibe un rang uniforme concret.',
        'Un compact éloigné de zéro a une norme exacte',
        'Pour n=100 et δ=0,05, calculer la norme sur [δ,1]. Comparer au majorant 1/(nδ) et expliquer pourquoi le maximum global n’est plus dans ce compact.',
        'Le maximum global est à 1/n=0,01<δ. La fonction décroît donc sur [0,05,1], et la norme vaut 100×0,05/[1+(100×0,05)²]=5/26≈0,1923. Le majorant donne 1/5=0,20. Quand n augmente à δ fixé, les deux quantités tendent vers zéro. L’exclusion d’un voisinage fixe de zéro retire la couche mobile du domaine.',
        'Une intégrale converge malgré l’échec uniforme',
        'Calculer ∫₀¹fₙ(x)dx et sa limite. Est-ce en contradiction avec l’absence de convergence uniforme ? Quelle domination permet aussi de conclure ?',
        'Avec u=nx, l’intégrale vaut (1/(2n))ln(1+n²), qui tend vers zéro puisque ln n/n→0. Il n’y a aucune contradiction : la convergence uniforme est une condition suffisante d’interversion, pas une condition nécessaire. Ici 0≤fₙ≤1/2 sur un intervalle fini, et la convergence dominée fournit également la limite de l’intégrale.'),
    record('concentration', 'Une aire peut se concentrer sur un point', 'Sup → Spé ; mesures au-delà',
        'La deuxième expérience améliorée étudie fₙ(x)=n²xe^(−nx) sur [0,1]. Pour chaque x fixé la limite est zéro, mais l’aire ne disparaît pas. Ce contre-exemple oblige à vérifier les hypothèses d’une interversion limite–intégrale au lieu de se fier à une convergence visuelle.',
        'fₙ(x)→0 ; maximum=n/e en x=1/n\n∫₀¹fₙ(x)dx=∫₀ⁿue^(−u)du=1−(n+1)e^(−n)→1\nlimn∫fₙ ≠ ∫limnfₙ',
        'À x>0 fixé, l’exponentielle domine tout polynôme en n, donc n²xe^(−nx)→0. La dérivée est n²e^(−nx)(1−nx), d’où le sommet en 1/n. Le changement u=nx révèle une hauteur de l’ordre de n, une largeur de l’ordre de 1/n et une aire de l’ordre de 1. Le profil dilaté fₙ(u/n)/n=ue^(−u) conserve la masse.',
        'Le point fixe x₀ permet de distinguer croissance initiale et limite finale : une valeur peut augmenter pendant plusieurs rangs avant de décroître. La courbe d’aire est obtenue par une formule exacte, indépendante du maillage. Il ne peut exister de majorant intégrable commun, car la convergence dominée imposerait une limite d’aire nulle.',
        'La masse limite agit comme une Dirac',
        'Au-delà du cours usuel de suites de fonctions, une famille peut converger comme mesure plutôt que comme fonction. Pour chaque φ continue sur [0,1], l’aire pondérée par φ tend vers φ(0).',
        '∫₀¹φ(x)fₙ(x)dx=∫₀ⁿφ(u/n)ue^(−u)du→φ(0)\n∫₀^∞ue^(−u)du=1',
        'Prolonger l’intégrande par zéro pour u>n. Pour chaque u fixé, φ(u/n) tend vers φ(0), et le module est majoré par ‖φ‖∞ue^(−u), intégrable. La convergence dominée s’applique dans la variable dilatée u, même si elle échoue avec un majorant commun dans la variable x. Cela annonce la distribution de Dirac sans lui attribuer une valeur infinie ordinaire.',
        'Quantifier où passe l’aire',
        'Calculer la part d’aire de fₙ entre 0 et c/n pour c>0 et n≥c. Pour c=3, quelle fraction limite de la masse est déjà dans cette fenêtre ?',
        'Le changement u=nx donne ∫₀ᶜ/ⁿfₙ=∫₀ᶜue^(−u)du=1−(c+1)e^(−c). Pour c=3, cette fraction vaut 1−4e^(−3)≈0,80085. Environ 80 % de la masse est donc dans une fenêtre de largeur 3/n qui tend vers zéro. L’aire totale sur [0,1] tend vers 1 ; la comparaison rend visible la concentration.',
        'Une famille à paramètre change trois régimes',
        'Pour gₙ,α(x)=n^αxe^(−nx), α réel, étudier le maximum et l’aire asymptotique sur [0,1]. Déterminer les seuils de convergence uniforme et de perte d’aire.',
        'Le maximum vaut n^(α−1)/e à x=1/n et l’aire vaut n^(α−2)[1−(n+1)e^(−n)]. La convergence simple vers zéro reste vraie pour tout α fixé. Elle est uniforme si α<1, échoue à α=1 avec une hauteur constante, et le maximum diverge si α>1. L’aire tend vers 0 pour α<2, vers 1 pour α=2 et diverge pour α>2. Les seuils de hauteur et d’aire sont donc différents.'),
    record('tp99_original', 'Une annulation d’ordre deux améliore la série', 'Spé',
        'Le TP de la page 99 est conservé comme expérience complémentaire : fₙ(x)=cos(x/n)−[1+(x/n)²]^(−1/2). Les deux expressions ont la même limite 1 et le même terme quadratique. Leur différence commence à l’ordre quatre. Une justification uniforme demande pourtant un majorant sur tout le compact, pas seulement un développement à x fixé.',
        'cos u=1−u²/2+u⁴/24+O(u⁶)\n(1+u²)^(−1/2)=1−u²/2+3u⁴/8+O(u⁶)\nfₙ(x)=−x⁴/(3n⁴)+O(x⁶/n⁶)',
        'Taylor avec reste donne |cos u−1+u²/2|≤u⁴/24. Pour v=u²≥0, la dérivée seconde de (1+v)^(−1/2) est au plus 3/4, d’où un reste ≤3u⁴/8. Ainsi |fₙ(x)|≤5R⁴/(12n⁴) pour |x|≤R. La série de ces majorants converge, donc Σfₙ converge normalement sur tout compact réel.',
        'Le banc compare n⁴fₙ à −x⁴/3 et compare la somme partielle au terme local −π⁴x⁴/270. Ce dernier est un développement au voisinage de zéro, pas la formule de la somme sur tout ℝ. Pour les petites valeurs de x/n, le calcul utilise une expression stable afin d’éviter la soustraction de deux nombres presque égaux à 1.',
        'Sommer un développement local demande un reste sommable',
        'Sur un voisinage |x|≤r<1, les restes d’ordre six des deux fonctions sont uniformément contrôlés. Leur somme en n conserve un ordre O(x⁶). On peut ainsi relier le coefficient local de la somme à ζ(4).',
        'S(x)=Σn≥1fₙ(x)=−[ζ(4)/3]x⁴+O(x⁶)\nζ(4)=π⁴/90 ⇒ S(x)=−π⁴x⁴/270+O(x⁶)',
        'Choisir r<1 fixe permet de majorer les dérivées qui contrôlent le reste de chaque terme par une constante indépendante de n, puisque |x/n|≤r. Le reste est alors ≤C|x|⁶/n⁶, et Σn⁻⁶ converge. Le terme quartique se somme séparément. Le raisonnement explique pourquoi un simple équivalent terme à terme ne suffit pas sans un contrôle de la famille.',
        'Une borne de reste pour la somme de fonctions',
        'Sur [−2,2], on garde n=1,…,N. Calculer une borne uniforme du reste après N=100 à partir du majorant 5R⁴/(12n⁴). Quel est son ordre en N ?',
        'La somme des queues satisfait Σn>Nn⁻⁴≤∫N^∞t⁻⁴dt=1/(3N³). Donc ‖S−SN‖∞≤5R⁴/(36N³). Avec R=2 et N=100, la borne est 80/(36×10⁶)≈2,22×10⁻⁶. L’ordre est N⁻³ ; il diffère de l’ordre n⁻⁴ d’un terme individuel, car on additionne toute une queue.',
        'Une petite différence exige un calcul adapté',
        'Pour u=10⁻⁴, estimer cos u−1/√(1+u²). Pourquoi soustraire directement ces deux valeurs peut-il perdre des chiffres ? Quel développement donne une évaluation contrôlée ?',
        'Le premier terme vaut −u⁴/3≈−3,33×10⁻¹⁷, tandis que les deux nombres soustraits sont proches de 1. En arithmétique flottante usuelle, leur arrondi est du même ordre que la différence recherchée. Le développement −u⁴/3+(14/45)u⁶+O(u⁸) évite cette annulation : ici la correction sextique vaut environ 3,11×10⁻²⁵, négligeable par rapport au terme quartique.'),
    record('geometrie', 'Le disque de convergence protège les opérations', 'Sup → Spé',
        'La série géométrique donne un modèle exact pour distinguer rayon de convergence, convergence sur un compact et précision d’une somme finie. Le banc utilise PN(x)=Σk=0ᴺxᵏ sur [−r,r], avec r<1. N est le degré : le polynôme possède N+1 termes.',
        'PN=(1−x^(N+1))/(1−x) ; S=1/(1−x)\nS−PN=x^(N+1)/(1−x)\n‖S−PN‖∞,[−r,r]=r^(N+1)/(1−r)',
        'L’identité finie se démontre par télescopage après multiplication par 1−x. Pour |x|<1, x^(N+1)→0. Sur |x|≤r, la norme de xᵏ est rᵏ, donc la série converge normalement. Le maximum du reste est atteint à x=r, ce qui rend la borne exacte. Près de r=1, le dénominateur petit amplifie l’erreur.',
        'Dériver terme à terme donne Σk≥1kx^(k−1)=1/(1−x)². La série dérivée est encore normale sur tout compact intérieur, puisque Σkr^(k−1) converge. La somme dérivée demande davantage de termes pour une même précision ; le rayon demeure 1, mais les majorants changent.',
        'Les dérivées demandent leur propre contrôle uniforme',
        'La convergence uniforme des fonctions seule ne permet pas de dériver leur limite. Pour la série géométrique, on calcule le reste de la série dérivée et l’on dispose donc d’une justification supplémentaire.',
        'Σk>Nkr^(k−1)=rᴺ[(N+1)−Nr]/(1−r)²\n‖S′−PN′‖∞,[−r,r]≤ce même nombre',
        'Dériver la queue r^(N+1)/(1−r) pour r∈[0,1[ fournit la formule. La série dérivée converge normalement sur le compact et la série initiale converge en un point ; le théorème de dérivation des séries identifie alors la dérivée de la somme. Ce contrôle peut être réutilisé pour primitives, solutions d’EDO et fonctions génératrices.',
        'Choisir un degré avec une précision fixée',
        'Sur |x|≤1/2, quel degré N suffit pour garantir |1/(1−x)−PN(x)|≤10⁻³ ? Combien de termes calcule-t-on ?',
        'La norme exacte vaut (1/2)^(N+1)/(1/2)=2^(−N). Il faut N≥log₂1000≈9,966, donc N=10 suffit. Le polynôme comprend N+1=11 termes. À x=1/2 le reste vaut 1/1024≈0,0009766. La même valeur N ne convient pas automatiquement à r=0,95 : le compact doit entrer dans la spécification.',
        'Au bord, un rayon ne décide pas tout',
        'Comparer Σxⁿ, Σxⁿ/n et Σxⁿ/n² aux points x=1 et x=−1. Les trois rayons valent 1 ; pourquoi leurs comportements au bord sont-ils différents ?',
        'Pour Σxⁿ, le terme ne tend pas vers zéro aux deux points, donc divergence. Pour Σxⁿ/n, à x=1 c’est l’harmonique divergente ; à x=−1 la série alternée converge conditionnellement. Pour Σxⁿ/n², la convergence est absolue aux deux points. Le rayon décrit le disque ouvert et l’extérieur ; chaque point du cercle frontière demande une étude propre.'),
    record('arcsin_ex4', 'L’exercice 4 : une EDO donne la série entière', 'Spé',
        'On cherche le développement de f(x)=arcsin(x)/√(1−x²) au voisinage de zéro. Plutôt que multiplier deux longues séries, on calcule une équation différentielle et une condition initiale. La construction de la série puis l’unicité de cette EDO justifient son identification à la fonction.',
        '(1−x²)f′−xf=1 ; f(0)=0\na₀=0, a₁=1, (n+2)aₙ₊₂=(n+1)aₙ\nf(x)=Σk≥0 [4ᵏ(k!)²/(2k+1)!]x^(2k+1), |x|<1',
        'La dérivée du quotient vérifie l’EDO. En remplaçant f par Σanxⁿ et en identifiant les coefficients, les termes pairs sont nuls et cₖ=a₂ₖ₊₁ vérifie c₀=1, cₖ=(2k/(2k+1))cₖ₋₁. Le quotient des termes non nuls tend vers x², donc le rayon est 1. Sur ce disque les opérations sont licites et la série résout l’EDO avec la bonne valeur initiale.',
        'Les premiers termes sont x+(2/3)x³+(8/15)x⁵+(16/35)x⁷. Les coefficients restent positifs et au plus 1, donnant un majorant géométrique du reste sur |x|≤r<1. Les singularités ±1 expliquent le ralentissement de convergence, pas une erreur dans la récurrence.',
        'Un résidu d’EDO contrôle une construction algébrique',
        'Le polynôme PN qui garde N termes impairs ne satisfait pas exactement l’EDO. Son résidu possède pourtant une forme très simple, qui permet de détecter une erreur de coefficient.',
        'PN=Σk=0ᴺ⁻¹cₖx^(2k+1)\n(1−x²)PN′−xPN−1=−2N cN−1 x^(2N)\n‖f−PN‖∞,|x|≤r≤r^(2N+1)/(1−r²)',
        'Tous les coefficients internes du résidu s’annulent par la récurrence. Seul le degré maximal, produit de −x²PN′−xPN, subsiste avec le facteur −2N. Pour le reste de fonction, 0<cₖ≤1 permet de sommer Σk≥Nr^(2k+1). Une petite erreur de résidu et une borne de reste sont deux contrôles différents, complémentaires au dessin.',
        'Construire quatre termes sans dériver huit fois',
        'Partir de l’EDO pour calculer le polynôme à quatre termes impairs et son résidu. Donner une majoration du reste sur |x|≤1/2.',
        'La récurrence donne c₀=1, c₁=2/3, c₂=8/15 et c₃=16/35. Donc P₄=x+(2/3)x³+(8/15)x⁵+(16/35)x⁷. Le résidu vaut −8×(16/35)x⁸=−128x⁸/35. Le majorant du reste est (1/2)⁹/[1−(1/2)²]=1/384≈0,002604. Cette borne est suffisante mais peut être améliorée avec le premier coefficient omis.',
        'Reconnaître une primitive et la singularité',
        'Montrer que f=(1/2)[(arcsin x)²]′. En déduire une série pour (arcsin x)² et l’équivalent de f(x) quand x→1⁻.',
        'La règle de dérivation donne [(arcsin x)²]′=2arcsin x/√(1−x²). En intégrant la série sur un compact intérieur et en utilisant arcsin0=0, (arcsin x)²=Σk≥0cₖx^(2k+2)/(k+1). Quand x→1⁻, arcsin x→π/2 et √(1−x²)~√[2(1−x)], donc f(x)~π/[2√2√(1−x)]. Cette singularité explique le rayon 1 et l’échec d’une approximation uniforme jusqu’au bord.'),
    record('asymptotique_ex5', 'L’exercice 5 : du coefficient à une croissance entière', 'Spé ; lien probabiliste',
        'Pour n≥2, aₙ=(1+2/n²)^(n³)/n! et S(x)=Σn≥2aₙxⁿ. L’exercice demande le rayon puis un équivalent lorsque x→+∞. Le développement du logarithme doit précéder l’exponentiation ; confondre e²x avec 2x changerait complètement la croissance.',
        'n³ln(1+2/n²)=2n−2/n+O(n⁻³)\naₙ~e^(2n)/n! ; R=+∞\nS(x)~exp(e²x), x→+∞',
        'Les racines n-ièmes satisfont aₙ^(1/n)=exp[n²ln(1+2/n²)]/(n!)^(1/n). Le premier facteur tend vers e² et le second dénominateur tend vers l’infini, donc R=∞ par Cauchy–Hadamard. Le quotient aₙ/(e^(2n)/n!) tend vers 1. Pour passer à la somme à x positif, encadrer les coefficients à partir d’un rang fixe ; la contribution des premiers rangs est un polynôme négligeable devant exp(e²x).',
        'L’expérience pose λ=e²x et calcule S(x)e^(−λ), qui tend vers 1. Les poids dominants se trouvent autour de n≈λ : une somme arrêtée avant ce cœur peut paraître bien calculée mais manquer presque tout le résultat. Les logarithmes évitent les débordements causés par des valeurs exponentielles énormes.',
        'Une loi de Poisson fournit un transfert rigoureux',
        'Le coefficient normalisé rₙ=(1+2/n²)^(n³)e^(−2n) est dans ]0,1[ et tend vers 1. Le rapport de sommes est donc une espérance sous une loi de Poisson, à laquelle manquent les rangs 0 et 1.',
        'S(x)e^(−λ)=Σn≥2rₙe^(−λ)λⁿ/n!, λ=e²x\nP(Nλ=n)=e^(−λ)λⁿ/n!',
        'Fixer ε>0 puis choisir m avec |rₙ−1|≤ε pour n≥m. La masse des rangs n<m est e^(−λ) fois un polynôme en λ, donc tend vers zéro. Sur les autres rangs, l’erreur est au plus ε fois une masse au plus 1. Le rapport tend vers 1. Cette preuve exploite x>0 et des poids positifs ; elle ne s’étend pas automatiquement à une direction complexe.',
        'Une troncature avant le cœur de la somme',
        'Pour x=30, estimer λ=e²x et l’ordre des indices significatifs. Pourquoi N=100 ne peut-il pas être choisi en se fondant seulement sur le rayon infini ?',
        'λ≈7,389×30≈221,67. Les poids de Poisson se concentrent autour de ce nombre, avec un écart type √λ≈14,89. Une troncature à 100 est très loin avant la zone dominante et perd l’essentiel de la somme normalisée. Le rayon infini garantit la convergence pour tout x fixé, mais ne donne aucun degré uniforme permettant une bonne approximation à tous les x.',
        'Un transfert élémentaire sans loi de probabilité',
        'Supposer bn>0, an/bn→1 et B(x)=Σbnxⁿ croît plus vite que tout polynôme lorsque x→+∞. Démontrer A(x)/B(x)→1 pour x positif, puis l’appliquer ici.',
        'Pour ε>0, choisir m tel que (1−ε)bn≤an≤(1+ε)bn pour n≥m. Multiplier par xⁿ≥0 et sommer la queue : les différences entre les sommes entières et ces queues sont des polynômes de degré inférieur à m. Diviser par B(x) fait disparaître ces polynômes, puis ε→0 donne le résultat. Ici bn=e^(2n)/n!, B=exp(e²x) à un polynôme près, ce qui établit l’équivalent demandé.'),
    record('binomiale_ex10', 'L’exercice 10 : le binôme pour un exposant non entier', 'Spé',
        'On pose α=p+1/2, p entier, et f(u)=(1−u)^(−α). Le banc considère des demi-entiers positifs et négatifs, afin de ne pas réduire le binôme à une suite toujours positive. La série se construit par une EDO : (1−u)f′=αf et f(0)=1.',
        'c₀=1 ; cₙ₊₁=(α+n)cₙ/(n+1)\n(1−u)^(−α)=Σn≥0[(α)ₙ/n!]uⁿ, |u|<1\nα=1/2 : cₙ=binom(2n,n)/4ⁿ',
        'Le symbole (α)ₙ désigne le produit α(α+1)…(α+n−1), avec (α)₀=1. Identifier les coefficients dans l’EDO donne la récurrence. Pour les demi-entiers non entiers du banc, le rapport des modules des termes tend vers |u|, donc R=1. La série obtenue résout l’EDO sur le disque et fournit le développement voulu ; une fonction C∞ seule ne suffirait pas à garantir cette analyticité.',
        'Pour α>0, les coefficients sont positifs ; près de u=1 ils deviennent difficiles à sommer avec peu de termes. Pour α négatif non entier, la fonction peut rester finie au bord mais possède une singularité de dérivées ou de branche, conservant R=1. Les signes des coefficients doivent être lus dans la récurrence, pas imposés par analogie au cas α=1/2.',
        'Une dérivée déplace l’exposant dans le bon sens',
        'La dérivation répétée fournit un produit croissant d’exposants. Elle explique les coefficients de Taylor et prépare l’intégration de la racine inverse dans l’exercice elliptique.',
        'dᵏ/duᵏ (1−u)^(−α)=(α)ₖ(1−u)^(−α−k)\nf_p′=(p+1/2)f_{p+1}\nf_p^(k)=[2^(−k)Π_{j=0}^{k−1}(2p+1+2j)]f_{p+k}',
        'La première dérivée combine le signe de l’exposant −α et celui de la dérivée de 1−u, donnant +α. Chaque dérivation augmente l’exposant α d’une unité et multiplie par cette nouvelle valeur. En zéro, on obtient f^(k)(0)=(α)ₖ, puis cₖ=f^(k)(0)/k!. Pour α=1/2, réarranger le produit des nombres impairs donne binom(2k,k)/4ᵏ.',
        'Calculer les coefficients et leurs signes',
        'Donner les quatre premiers termes de (1−u)^(−1/2) puis de (1−u)^(3/2). Quel α faut-il utiliser pour la seconde fonction ?',
        'Pour α=1/2, la récurrence donne 1+(1/2)u+(3/8)u²+(5/16)u³+… . La seconde fonction correspond à α=−3/2, d’où c₁=−3/2, c₂=3/8 et c₃=1/16 ; le début est 1−(3/2)u+(3/8)u²+(1/16)u³+… . Le signe ne suit pas une alternance perpétuelle : il dépend du nombre de facteurs négatifs dans (α)ₙ.',
        'Le produit d’une série et sa dérivée',
        'À partir de g(u)=(1−u)^(−1/2), montrer que (1−u)^(−3/2)=2g′(u). Retrouver le coefficient de uⁿ et le rayon.',
        'La dérivée vaut g′=(1/2)(1−u)^(−3/2). En dérivant terme à terme sur tout compact |u|≤r<1, le coefficient de uⁿ de 2g′ est 2(n+1)binom(2n+2,n+1)/4^(n+1), égal à (2n+1)binom(2n,n)/4ⁿ. La multiplication par un facteur polynomial en n ne change pas le rayon 1. Le résultat s’obtient sans refaire toutes les dérivées.'),
    record('elliptique_pendule', 'Le pendule relie une série à une période non linéaire', 'Sup → Spé',
        'L’exercice 10 contient I(k)=∫₀π[1−k²sin²t]^(−1/2)dt, |k|<1. Pour un pendule idéal de longueur ℓ, lancé sans vitesse à l’angle θ₀, poser k=sin(θ₀/2). La conservation de l’énergie conduit à T=4√(ℓ/g)K(k), où K=I/2 ; le facteur 2 entre I et K est essentiel.',
        'I(k)=πΣn≥0[binom(2n,n)/4ⁿ]²k^(2n)\nT₀=2π√(ℓ/g) ; T/T₀=I(k)/π\nT/T₀=1+k²/4+9k⁴/64+…',
        'Développer la racine inverse en u=k²sin²t. Pour |k|≤r<1, les termes sont majorés par cnr²ⁿ, ce qui justifie l’intégration terme à terme. Wallis donne ∫₀πsin²ⁿt dt=πbinom(2n,n)/4ⁿ ; les deux coefficients binomiaux se multiplient. Tous les termes sont positifs, donc les sommes partielles sous-estiment la période.',
        'Le modèle harmonique sinθ≈θ prédit une période indépendante de l’amplitude. La série elliptique montre la correction réelle et son coût près de la séparatrice θ₀=180°. La longueur multiplie les périodes par √ℓ sans modifier T/T₀. La trajectoire numérique illustre ce résultat et reste distincte de la quadrature qui calcule la période.',
        'Retrouver le changement de variable énergétique',
        'L’équation θ″+(g/ℓ)sinθ=0 possède une énergie conservée. En choisissant l’amplitude maximale, on exprime la vitesse puis le quart de période avec sin(θ/2)=k sinφ.',
        'θ̇²=(4g/ℓ)[k²−sin²(θ/2)]\nT/4=√(ℓ/g)∫₀π/₂dφ/√(1−k²sin²φ)',
        'L’énergie par unité de masse vaut ℓ²θ̇²/2+gℓ(1−cosθ), égale à gℓ(1−cosθ₀). Utiliser 1−cosθ=2sin²(θ/2), puis différencier sin(θ/2)=k sinφ. Le facteur cosφ s’annule avec la racine de k²−sin²(θ/2), donnant K. Ce calcul justifie à la fois le module k et le facteur quatre, sans supposer petites oscillations.',
        'Une correction à petite amplitude en radians',
        'Déduire de la série le premier terme de T/T₀ en fonction de θ₀ lorsque θ₀→0. Estimer l’allongement relatif pour θ₀=20°.',
        'Comme k=sin(θ₀/2)~θ₀/2, T/T₀=1+θ₀²/16+O(θ₀⁴), avec θ₀ en radians. Pour 20°=π/9≈0,3491, la correction vaut θ₀²/16≈0,007615, soit 0,762 %. Introduire 20 directement dans cette formule serait une erreur d’unité ; l’amplitude doit être convertie avant le développement.',
        'Pourquoi la période diverge près du sommet',
        'Étudier qualitativement K(k) lorsque k→1⁻. Au point k=1, que devient l’intégrande près de φ=π/2 ? Pourquoi les sommes de peu de termes sont-elles insuffisantes ?',
        'À k=1, l’intégrande vaut 1/|cosφ| sur [0,π/2[, et cosφ~π/2−φ près du bord. Son intégrale diverge logarithmiquement. Pour k proche de 1, le pendule passe longtemps près de son point haut, où la vitesse est faible. Le facteur k²ⁿ décroît alors lentement et de nombreux termes sont nécessaires ; une approximation quadratique de sinθ ne peut représenter cette séparatrice.'),
    record('integrale_sh_ex11', 'L’exercice 11 : additionner des intégrales positives', 'Spé',
        'Pour t>0, t/sinh t=2te^(−t)/(1−e^(−2t)). Le développement géométrique donne une série de fonctions positives dont chaque aire se calcule par intégration par parties. Le prolongement continu de t/sinh t vaut 1 en zéro, mais chaque somme partielle de la série vaut 0 en ce point.',
        't/sinh t=Σn≥0 2t e^(−(2n+1)t), t>0\n∫₀^∞2t e^(−(2n+1)t)dt=2/(2n+1)²\n∫₀^∞t/sinh t dt=π²/4',
        'Le changement u=(2n+1)t ramène chaque aire à [2/(2n+1)²]∫₀∞ue^(−u)du. La somme des intégrales absolues est finie, puisque Σ1/(2n+1)² converge. Le théorème d’intégration des séries, ou la convergence monotone pour cette famille positive, permet l’échange sur ]0,+∞[. La somme sur les impairs vaut (1−1/4)ζ(2)=π²/8.',
        'Le banc calcule les aires sur tout [0,+∞[ et utilise [0,T] seulement pour la représentation. Une queue à grande valeur de t et un reste de série après N sont donc séparés. Le décalage au point t=0 ne modifie aucune intégrale, mais interdit de prétendre à une convergence uniforme jusqu’à ce bord.',
        'La norme choisie change le type de convergence',
        'Cette série converge absolument dans L¹ mais n’est pas normale pour la norme uniforme sur ]0,+∞[. Les deux constats sont compatibles et relient séries de fonctions, espaces normés et intégration.',
        '‖2t e^(−(2n+1)t)‖₁=2/(2n+1)²\n‖2t e^(−(2n+1)t)‖∞=2/[e(2n+1)]\nΣ‖terme‖₁<∞ ; Σ‖terme‖∞=∞',
        'Le maximum du terme se trouve en t=1/(2n+1), donnant la seconde norme. Les aires forment une série en 1/n² ; les maxima une série en 1/n. Sur un domaine t≥δ>0, les maxima des grands rangs passent au bord δ et décroissent exponentiellement, ce qui rétablit une convergence normale uniforme loin de zéro.',
        'Un encadrement du reste de série',
        'Après N termes n=0,…,N−1, montrer que le reste RN est entre 1/(2N+1) et 1/(2N+1)+2/(2N+1)². Quelle valeur N garantit RN<0,01 avec cette borne ?',
        'La fonction a(x)=2/(2x+1)² est positive décroissante. Pour la queue Σn≥Na(n), l’encadrement intégral donne ∫N∞a≤RN≤a(N)+∫N∞a, et l’intégrale vaut 1/(2N+1). Pour N=50, la borne supérieure dépasse légèrement 0,01 ; pour N=51 elle vaut environ 0,0098973. N=51 suffit donc selon cette garantie.',
        'Le point zéro ne change pas l’aire',
        'La somme de la série vaut 0 en t=0 si l’on y évalue les termes un par un, tandis que le prolongement de t/sinh t vaut 1. Pourquoi l’intégration reste-t-elle correcte ? Que dit cette différence de la convergence uniforme près de zéro ?',
        'Modifier une fonction en un point ne change pas son intégrale. L’identité de série sur t>0 suffit donc au calcul impropre. Chaque somme partielle tend vers 0 lorsque t→0⁺, tandis que l’intégrande complet tend vers 1 ; pour tout N, l’erreur près de zéro tend vers 1. La convergence uniforme sur ]0,T] échoue, même si la convergence L¹ est absolue.'),
    record('dominee_ex12', 'L’exercice 12 : dominer un signal réel ou complexe', 'Spé',
        'Pour f continue par morceaux sur [0,1], on compare In=∫₀¹f(t)(1−t/n)ⁿdt à I=∫₀¹f(t)e^(−t)dt. Le noyau est réel positif, mais f peut être complexe ou posséder un saut. La domination porte sur |f|, et le théorème s’applique aux deux composantes complexes.',
        '(1−t/n)ⁿ→e^(−t), 0≤(1−t/n)ⁿ≤1\n|f(t)(1−t/n)ⁿ|≤|f(t)|, intégrable\nIn→I par convergence dominée',
        'Pour t fixé, n ln(1−t/n)→−t. Le cas n=1,t=1 est défini directement par le noyau 0 et ne gêne pas le passage à la limite en n. Une fonction continue par morceaux sur un segment est bornée et intégrable ; |f| fournit un majorant indépendant de n. Les parties réelle et imaginaire convergent donc toutes deux vers les composantes de I.',
        'Pour f=e^(iωt), le banc dessine le chemin des In dans le plan complexe et calcule I=[e^(−1+iω)−1]/(−1+iω). Pour un saut en 0,4, la quadrature se fait sur deux intervalles. Ces précautions distinguent une identité de convergence d’un simple calcul numérique sur une grille.',
        'Une borne quantitative issue du logarithme',
        'La convergence dominée donne une limite mais pas de vitesse automatique. Ici le logarithme permet d’obtenir une borne uniforme pour le noyau, puis une borne de l’erreur d’intégrale en fonction de ‖f‖₁.',
        'n≥2 : 0≤e^(−t)−(1−t/n)ⁿ≤1/[2(n−1)]\n|In−I|≤‖f‖₁/[2(n−1)]',
        'Poser q=−n ln(1−t/n)−t=Σk≥2tᵏ/(k n^(k−1)). Pour 0≤t≤1, q≤t²/[2n(1−t/n)]≤1/[2(n−1)]. La différence des noyaux vaut e^(−t)(1−e^(−q)), majorée par q grâce à 1−e^(−q)≤q. Multiplier par |f|, intégrer puis utiliser l’inégalité triangulaire donne la borne annoncée.',
        'Une fonction complexe possède une limite fermée',
        'Pour f(t)=e^(iωt), calculer I et une borne de |In−I| pour n≥2. Quelle valeur n suffit à garantir une erreur au plus 0,005 indépendamment de ω ?',
        'L’intégrale vaut I=[exp(−1+iω)−1]/(−1+iω), puisque −1+iω n’est jamais nul pour ω réel. On a |f|=1 et ‖f‖₁=1, donc l’erreur est au plus 1/[2(n−1)]. Pour une garantie 0,005, il faut n−1≥100, donc n=101 suffit. La borne ne dépend pas de la fréquence, même si l’erreur réelle peut être bien plus petite par oscillation.',
        'Une discontinuité n’interdit pas la domination',
        'Prendre f=1 sur [0,0,4[ et f=−3/4 sur [0,4,1]. Calculer I et ‖f‖₁. Montrer pourquoi la valeur choisie exactement en 0,4 ne joue aucun rôle.',
        'I=∫₀⁰,⁴e^(−t)dt−(3/4)∫₀,₄¹e^(−t)dt=1−(7/4)e^(−0,4)+(3/4)e^(−1). La norme L¹ vaut 0,4+(3/4)×0,6=0,85, donc |In−I|≤0,85/[2(n−1)]. Une valeur en un point ne modifie ni l’intégrale ni cette norme. Le théorème exige ici la continuité par morceaux et l’intégrabilité du majorant, pas une continuité globale.'),
]


ORDER = ['couche_limite','concentration','tp99_original','geometrie','arcsin_ex4',
         'asymptotique_ex5','binomiale_ex10','elliptique_pendule','integrale_sh_ex11',
         'dominee_ex12','rc_reponses','rc_bode','rlc_poles','dirichlet_abel',
         'porte_sinc','gaussienne','convolution_portes','gibbs_fourier',
         'parseval_spectre','poisson_noyau','poisson_gaussienne','shannon',
         'aliasing','anti_repliement','fenetres_fft','resolution','spectrogramme',
         'modulation','correlation_retard','debruitage']
DATA.sort(key=lambda item: ORDER.index(item['lab']))

LESSONS = []
EXERCISES = []
for item in DATA:
    LESSONS.append(dict(title=f"{len(LESSONS)+1}. {item['title']}",
                        level=item['level'], lab=item['lab'],
                        html=P('Objets et but.',item['context'])+F(item['formula'])
                             +P('Démonstration.',item['proof'])
                             +P('Lire l’expérience.',item['application'])))
    LESSONS.append(dict(title=f"{len(LESSONS)+1}. {item['lemma_title']}",
                        level=item['level'], lab=item['lab'],
                        html=P('Propriété ciblée.',item['lemma_statement'])
                             +F(item['lemma_formula'])
                             +P('Justification.',item['lemma_proof'])))
    for title, question, answer in item['exercises']:
        EXERCISES.append(dict(title=f'{len(EXERCISES)+1}. {title}',
                              level=item['level'],lab=item['lab'],
                              question=P('Énoncé.',question),
                              answer=P('Corrigé.',answer)))


SOURCES = [
    "<p>Point de départ : recueil fourni par l’utilisateur, fiches M10 et M11, "
    "pages imprimées 98–111. Priorités : TP p.99 ; exercices 4, 5, 10, 11, 12 "
    "p.103–105 ; TP RC et intégrale de Dirichlet p.107 ; analyse du signal p.108. "
    "Les cours, expériences et problèmes sont rédigés pour cet atelier ; le PDF "
    "n’est pas redistribué.</p>",
    "<p><a href='https://dlmf.nist.gov/1.8'>NIST DLMF, §1.8</a> : séries de "
    "Fourier, Parseval et sommation de Poisson. "
    "<a href='https://dlmf.nist.gov/1.14'>NIST DLMF, §1.14</a> : transformées "
    "de Fourier et Laplace ; les signes et facteurs sont adaptés aux "
    "conventions explicitement affichées dans cet atelier.</p>",
    "<p><a href='https://ocw.mit.edu/courses/res-6-007-signals-and-systems-spring-2011/resources/lecture-16-sampling/'>"
    "MIT OpenCourseWare, Alan V. Oppenheim, Signals and Systems : Sampling</a> "
    "et <a href='https://ocw.mit.edu/courses/2-161-signal-processing-continuous-and-discrete-fall-2008/resources/samplingdft/'>"
    "Sampling and the Discrete Fourier Transform</a> : compléments sur "
    "échantillonnage, reconstruction, DFT et fenêtrage.</p>",
]
