"""Buts, variables, premiers gestes et niveaux des trente laboratoires."""
from cours import ORDER


def _items(text):
    # The ASCII bar separates list entries, while the mathematical bar belongs
    # to an expression. Preserve these expressions before splitting the list.
    for expression in ('|x|','|u|','|k|','|f|','|f̂|','|H|'):
        text=text.replace(expression,expression.replace('|','∣'))
    return text.split('|')


def guide(purpose, objects, assumptions, techniques, steps, sup, spe, beyond, expected):
    return dict(purpose=purpose, objects=_items(objects),
                assumptions=_items(assumptions), techniques=_items(techniques),
                first_steps=steps, levels=dict(sup=sup, spe=spe,beyond=beyond),
                expected=expected, lesson_numbers=[])


LAB_GUIDES = {
    'couche_limite': guide(
        'Prouver une convergence simple puis repérer le point mobile qui empêche la convergence uniforme. Le but est d’apprendre à calculer une norme, et à distinguer une preuve d’un dessin bien résolu.',
        'n entier, x∈[0,1] et fₙ(x)=nx/(1+n²x²) sans unité|δ>0 fixe le compact [δ,1] ; u=nx est la coordonnée de loupe|Le sommet est calculé analytiquement, pas estimé sur les points du graphe',
        'Domaine fixe [0,1] pour la convergence simple et uniforme globale|La comparaison locale utilise un δ positif fixé avant n→∞',
        'Étude d’une dérivée et d’un maximum|Quantificateurs de convergence|Changement d’échelle u=nx',
        ['Pour n=15, prévoir la position 1/n et la hauteur du pic avant de déplacer les curseurs.',
         'Passer à n=800 puis comparer le tracé global, la loupe et les deux normes ; garder δ=0,03 fixe.',
         'Écrire la preuve de CS, le contre-exemple à CU et la borne 1/(nδ) sur le compact ; expliquer ce qu’un maillage peut manquer.'],
        'Dérivation, signe, maximum et lecture de quantificateurs ; entrée progressive vers les suites de fonctions.',
        'Convergence simple et uniforme, norme sup et convergence locale sur les compacts.',
        'Couches limites et limites singulières d’équations différentielles.',
        'Trois conclusions distinctes : CS sur [0,1], échec CU global, CU sur chaque [δ,1].'),
    'concentration': guide(
        'Mettre en défaut une interversion limite–intégrale et localiser la masse perdue par la limite ponctuelle. L’expérience prépare ensuite la notion d’impulsion de Dirac utilisée en signal.',
        'fₙ(x)=n²xe^(−nx), x∈[0,1], n entier|x₀ est un point fixe où l’on suit la suite numérique fₙ(x₀)|Aire exacte, position 1/n, hauteur n/e ; loupe u=nx',
        'Fonctions positives ; limite simple nulle, y compris en zéro|La famille ne possède pas de domination intégrable commune sur [0,1]',
        'Exponentielle contre puissance|Intégration par parties et changement de variable|Vérification des hypothèses de convergence dominée',
        ['Pour n=8, prévoir simultanément hauteur, largeur caractéristique et aire ; ne conclure ni d’après la hauteur seule ni d’après un point.',
         'Comparer n=8 puis n=200 et observer fₙ(x₀) avec x₀=0,2 ; utiliser la loupe pour conserver le profil.',
         'Calculer 1−(n+1)e^(−n) et justifier pourquoi une domination intégrable commune est impossible.'],
        'Limites exponentielles, étude de fonction et calcul d’aire.',
        'Convergence dominée, contre-exemple à l’interversion et changement de variable adapté.',
        'Convergence de mesures vers une Dirac et concentration de masse.',
        'Une limite ponctuelle nulle et une limite d’aire égale à 1, réconciliées par une couche de largeur 1/n.'),
    'tp99_original': guide(
        'Reprendre le TP p.99 après les deux expériences de convergence. L’objectif est de transformer une annulation locale en un majorant sommable uniforme sur tout compact, puis de contrôler le reste de série.',
        'fₙ(x)=cos(x/n)−[1+(x/n)²]^(−1/2)|R fixe [−R,R] ; n règle un terme ; N règle la somme des n=1,…,N|n⁴fₙ et −π⁴x⁴/270 comparent deux développements locaux distincts',
        'Majoration Taylor valable pour tout x réel sur un compact fixé|Le terme quartique de la somme est une approximation en zéro, pas son expression globale|Évaluation stable des petites différences',
        'Développements limités et cancellation|Critère de Weierstrass|Borne d’une queue par une intégrale',
        ['Avec R=1 et n=40, prédire les deux termes quadratiques puis expliquer leur annulation.',
         'Comparer n⁴fₙ à −x⁴/3 ; augmenter ensuite R jusqu’à 4 et distinguer somme et approximation quartique.',
         'Démontrer |fₙ|≤5R⁴/(12n⁴), puis la borne 5R⁴/(36N³) du reste de la somme.'],
        'Développements limités usuels, différences de fonctions proches et sommabilité de n⁻⁴.',
        'Convergence normale sur les compacts et sommation contrôlée d’un développement.',
        'Conditionnement numérique et calcul de différences par des développements stables.',
        'Une justification de CN accompagnée d’un reste uniforme et d’une distinction entre identité et développement local.'),
    'geometrie': guide(
        'Utiliser une série dont le reste est exact pour apprendre à choisir un degré et justifier dérivation et intégration terme à terme. Le compact intérieur est une donnée de précision, pas un détail du graphique.',
        'PN(x)=Σk=0ᴺxᵏ comporte N+1 termes|r<1 définit le compact |x|≤r ; R=1 est le rayon de convergence|Deux restes affichés : somme et dérivée',
        'Le compact reste strictement intérieur au disque|Les normes des restes sont majorées analytiquement',
        'Télescopage|Somme géométrique et norme sup|Convergence normale de la série dérivée',
        ['Avec r=0,5, prévoir un degré garantissant une erreur de 10⁻³, puis comparer à la borne affichée.',
         'Garder N=20 et déplacer r de 0,5 à 0,95 ; observer la dérivée et la somme séparément.',
         'Calculer les deux queues et expliquer pourquoi le même rayon ne donne pas la même précision pour les dérivées.'],
        'Identité géométrique finie, limites et dérivation de polynômes.',
        'Séries entières, convergence normale sur les compacts et opérations terme à terme.',
        'Estimations de Cauchy et approximation de fonctions analytiques.',
        'Un degré choisi à partir d’une borne et une dérivation de série justifiée sur un domaine annoncé.'),
    'arcsin_ex4': guide(
        'Résoudre l’exercice 4 prioritaire par une EDO plutôt que des dérivations successives lourdes. Identifier la parité, construire la récurrence et vérifier un polynôme par son résidu.',
        'f(x)=arcsin x/√(1−x²), |x|<1|N est le nombre de termes impairs ; le degré vaut 2N−1|r fixe le compact ; cₖ est le coefficient de x^(2k+1)',
        'L’analyticité est construite par une série de rayon 1 puis l’unicité de l’EDO|Les singularités ±1 restent hors du domaine de contrôle uniforme',
        'EDO du premier ordre|Identification de coefficients|Récurrence et majorant géométrique',
        ['Pour N=4, retrouver c₀,c₁,c₂,c₃ à la main avant de lire le graphe des coefficients.',
         'Comparer r=0,6 et r=0,98 avec N=20 ; repérer l’amplification du reste près du bord.',
         'Calculer (1−x²)PN′−xPN−1 et retrouver son unique terme maximal ; justifier le rayon 1.'],
        'Dérivation de composées et récurrence de nombres ; introduction accompagnée de l’EDO.',
        'Développement en série entière par EDO, opérations sur les compacts et contrôle du résidu.',
        'Asymptotique des coefficients et singularités analytiques.',
        'Un DSE démontré avec rayon, parité, récurrence et test algébrique indépendant.'),
    'asymptotique_ex5': guide(
        'Résoudre l’exercice 5 prioritaire et prouver le passage de coefficients équivalents à des sommes équivalentes. Une représentation probabiliste explique aussi comment choisir la troncature.',
        'aₙ=(1+2/n²)^(n³)/n!, n≥2 ; S(x)=Σaₙxⁿ|λ=e²x ; rₙ=aₙn!/e^(2n) ; x>0|N est le dernier rang conservé ; rapport S_N/e^λ et rapport S/e^λ sont distincts',
        'Transfert asymptotique pour x→+∞ avec coefficients positifs|Calculs normalisés en logarithmes ; la somme automatique est tronquée loin après le cœur n≈λ',
        'Logarithme et développement limité|Cauchy–Hadamard|Encadrement des coefficients ou poids de Poisson',
        ['Pour x=2, calculer λ ; examiner quels indices portent l’essentiel de la somme.',
         'Passer à x=30 et N=100 puis augmenter N au-delà de λ ; comparer rapport partiel et rapport de référence.',
         'Démontrer R=∞ et le transfert S(x)~exp(e²x) en séparant un début polynomial d’une queue positive.'],
        'Exponentielles, factorielles et ordre de grandeur ; calculs préparatoires accompagnés.',
        'Rayon, équivalents de coefficients et transfert justifié de somme.',
        'Concentration de Poisson, approximation de Laplace et arithmétique logarithmique.',
        'Une preuve de l’équivalent et une troncature argumentée, sans confondre exp(e²x) et exp(2x).'),
    'binomiale_ex10': guide(
        'Construire le binôme généralisé de l’exercice 10 pour des demi-entiers positifs et négatifs. Relier dérivées, récurrence, signes des coefficients et domaine de convergence.',
        'p entier de −3 à 3 ; α=p+1/2|N est le nombre de termes ; u∈[−r,r], r<1|c₀=1 et cₙ₊₁=(α+n)cₙ/(n+1)',
        'Puissance réelle bien définie pour u<1|Les demi-entiers du banc ne donnent pas de polynômes finis|Borne de reste par rapport de termes ou borne de Cauchy',
        'Dérivation répétée|Récurrence multiplicative|Rayon et convergence sur les compacts',
        ['Choisir p=0 et retrouver 1,1/2,3/8,5/16 ; comparer à la formule binomiale centrale.',
         'Choisir p=−3 puis p=3 ; prévoir les signes et observer la forte singularité près de u=1.',
         'Justifier le rayon 1 et calculer f_p′ en précisant le signe et le sens du déplacement de p.'],
        'Dérivation des puissances et premiers coefficients, avec guidage.',
        'Binôme généralisé, séries entières et singularité au bord.',
        'Symboles de Pochhammer, fonctions hypergéométriques et bornes complexes de Cauchy.',
        'Une formule de coefficients et de dérivées cohérente, avec signes contrôlés.'),
    'elliptique_pendule': guide(
        'Donner une application emblématique à l’intégrale de l’exercice 10 : le pendule à grande amplitude. Relier énergie mécanique, changement de variable, intégrale elliptique et série de correction.',
        'θ₀ en degrés dans le contrôle, en radians dans les développements|ℓ en m, g=9,81 m·s⁻² ; k=sin(θ₀/2)|I(k) est sur [0,π], K=I/2 ; T/T₀=I/π ; N compte les termes',
        'Pendule idéal sans frottement, vitesse initiale nulle|Période par quadrature de Gauss ; trajectoire par Runge–Kutta d’ordre 4|Pas de passage à θ₀=180° où la période diverge',
        'Énergie et intégrale première|Série binomiale et Wallis|Convergence normale puis borne de queue positive',
        ['Comparer θ₀=10° puis 120° et prédire le signe de la correction à T₀.',
         'Garder θ₀=160° et augmenter N ; changer ensuite ℓ pour vérifier que le rapport T/T₀ ne change pas.',
         'Retrouver T=4√(ℓ/g)K, puis I=2K, et expliquer la divergence près de la séparatrice.'],
        'Énergie du pendule et modèle harmonique ; première correction accompagnée.',
        'Intégrale elliptique, échange série–intégrale et contrôle du reste.',
        'Séparatrice, fonctions elliptiques et comparaison de solveurs numériques.',
        'Une période non linéaire calculée avec le bon facteur 2 et une limite des petites oscillations justifiée.'),
    'integrale_sh_ex11': guide(
        'Calculer l’intégrale impropre de l’exercice 11 par une série de fonctions. L’objectif est de justifier l’échange, additionner des aires exactes et distinguer reste de série et queue temporelle.',
        'f(t)=t/sinh t, prolongée en 1 à t=0|N modes n=0,…,N−1 ; chaque aire vaut 2/(2n+1)²|T borne la fenêtre dessinée ; les aires affichées sont sur [0,+∞[',
        'Identité de série pour t>0 ; un point isolé ne modifie pas l’intégrale|Termes positifs et somme des intégrales absolues finie|La série ne converge pas uniformément près de zéro',
        'Série géométrique|Intégration par parties|Théorème d’intégration des séries et comparaison intégrale',
        ['Avec N=3, calculer à la main les trois premières aires et observer ce que le tracé manque près de zéro.',
         'Augmenter N jusqu’à 200 puis T ; suivre séparément la borne de reste de série et la queue au-delà de T.',
         'Démontrer l’interversion et déduire π²/4 de la somme sur les indices impairs.'],
        'Séries numériques positives et intégrales élémentaires accompagnées.',
        'Intégration de séries de fonctions, normes L¹/sup et encadrements de restes.',
        'Convergence dans des espaces fonctionnels et transformées thermiques.',
        'Une valeur exacte π²/4 avec une justification d’interversion et deux erreurs de troncature distinguées.'),
    'dominee_ex12': guide(
        'Appliquer la convergence dominée de l’exercice 12 à des signaux réels, discontinus ou complexes. Obtenir aussi une vitesse de convergence par une inégalité logarithmique.',
        't∈[0,1], n entier ; noyau (1−t/n)ⁿ|ω sans dimension dans exp(iωt) ou sin(ωt)|In complexe est représentée par Re et Im ; signal à saut en 0,4',
        'f continue par morceaux, |f| intégrable|Quadrature de Gauss sur chaque intervalle de continuité ; limite calculée analytiquement|Pour n=1,t=1, le noyau est défini par 0',
        'Convergence simple et domination|Intégrales complexes|Inégalité de logarithme et borne quantitative',
        ['Choisir la famille affine avec n=1 et prédire le signe de la différence entre les noyaux.',
         'Passer au signal complexe et augmenter n ; lire son chemin d’intégrales dans le plan complexe.',
         'Vérifier la domination par |f| et démontrer |In−I|≤‖f‖₁/[2(n−1)] pour n≥2 ; tester ensuite le saut.'],
        'Limite de (1−t/n)ⁿ et intégration de fonctions réelles/complexes, avec accompagnement.',
        'Convergence dominée, fonctions continues par morceaux et contrôle quantitatif.',
        'Convergence d’opérateurs intégraux et extrapolation numérique.',
        'Une interversion justifiée et une borne d’erreur indépendante de la quadrature.'),
    'rc_reponses': guide(
        'Reconstruire le TP RC p.107 en reliant maille, Laplace, convolution et état initial. Chaque entrée fournit une vérification concrète de la solution temporelle et de ses unités.',
        'τ=RC en s ; u,y,y₀ en V|Rampe u=at+b : a en V/s, b en V|Un pas a une amplitude A en V ; une impulsion une aire A en V·s',
        'RC idéal, τ>0, entrée causale|y₀=y(0⁻) est explicite ; une impulsion produit un saut A/τ|Le transfert décrit la réponse au repos initial, l’état initial ajoute un terme homogène',
        'EDO linéaire du premier ordre|Laplace unilatérale et fractions simples|Convolution causale et contrôle par substitution',
        ['Pour τ=0,8,a=0,7,b=0,4,y₀=0, prévoir la pente finale et le décalage aτ avant de lire la courbe.',
         'Comparer pas, rampe et impulsion, puis imposer y₀=1,2 ; vérifier le départ de chaque sortie.',
         'Écrire Y=[U+τy₀]/(1+τp) et retrouver la solution ; pour l’impulsion, intégrer la maille autour de zéro.'],
        'Circuits RC, équation différentielle et constante de temps.',
        'Transformée de Laplace, réponse impulsionnelle et conditions initiales selon filière.',
        'Systèmes d’état, distributions causales et identification expérimentale.',
        'Trois réponses temporelles vérifiées, avec pente/intercept et aire d’impulsion explicités.'),
    'rc_bode': guide(
        'Voir comment gain et phase par harmonique déforment un signal. La réponse temporelle, le diagramme de Bode et le domaine de convergence de Laplace décrivent le même filtre.',
        'τ en s ; fréquence fondamentale ν₁ en Hz ; ω=2πν en rad/s|H(iω) est complexe ; GdB=20log₁₀|H| et phase en degrés|Signal à trois harmoniques, recomposées avec leur gain et leur phase',
        'RC idéal en régime permanent|Réponse impulsionnelle intégrable, donc axe imaginaire dans le domaine de convergence|Transitoire initial non représenté dans cette expérience de Bode',
        'Complexes et régime sinusoïdal|Asymptotes et coupure|Superposition harmonique',
        ['Calculer νc pour τ=0,2 s et prévoir gain et phase vers 0,8 Hz.',
         'Comparer fondamentale sous la coupure et harmoniques filtrées ; modifier τ à fréquence fixe.',
         'Recomposer une somme de trois sinusoïdes et justifier pourquoi la sortie n’est pas une réduction uniforme de l’entrée.'],
        'Régime sinusoïdal, gain, phase et diagrammes fréquentiels.',
        'Filtrage harmonique, relation Laplace–Fourier et stabilité.',
        'Identification fréquentielle et conception de filtres.',
        'Une coupure calculée et une déformation expliquée par les gains ET les phases.'),
    'rlc_poles': guide(
        'Classer les régimes d’un second ordre par ses pôles et prévoir les transitoires. Le pôle double critique est traité comme un vrai cas limite.',
        'ω₀ en rad/s ; ζ sans unité|Entrée pas ou impulsion unitaire ; repos initial|Pôles p± en s⁻¹, parties réelle et imaginaire affichées séparément',
        'Système normalisé y″+2ζω₀y′+ω₀²y=ω₀²u|ζ>0, système stable|Régime critique traité avec te^(−ω₀t), sans division par des pôles confondus',
        'Équation caractéristique|Laplace et modes exponentiels|Limite critique et calcul de dépassement',
        ['À ω₀=6,ζ=0,15, prévoir le signe des parties réelles et l’existence d’oscillations.',
         'Comparer ζ=0,15,1,1,8 sur le pas ; repérer le pôle lent à fort amortissement.',
         'Calculer ωd et le premier dépassement pour ζ<1 ; retrouver la réponse critique par passage à la limite.'],
        'Oscillateur amorti et EDO du second ordre.',
        'Pôles, stabilité, réponse indicielle et identification selon filière.',
        'Commande, espace d’état et amortissement optimal suivant un cahier des charges.',
        'Une classification des trois régimes et un temps de maximum ou de décroissance relié aux pôles.'),
    'dirichlet_abel': guide(
        'Calculer l’intégrale de Dirichlet du TP p.107 sans invoquer à tort une domination absolue. Séparer régularisation, troncature et erreur de quadrature.',
        'p>0 amortit e^(−pt) ; L est la borne d’intégration|Ip=∫₀∞e^(−pt)sin(t)/t dt ; valeur exacte π/2−arctan p|sin(t)/t se prolonge en 1 à zéro',
        'Intégrale non amortie conditionnellement convergente|Contrôle uniforme de la queue oscillante ≤2/L|Intégrales numériques sur des bornes finies distinctes des formules sur [0,+∞[',
        'Dérivation sous intégrale|Laplace de sin|Intégration par parties et limite d’Abel',
        ['Avec p=0,6,L=40, comparer les trois quantités exactes/amorties/tronquées.',
         'Réduire p à 0,02 puis augmenter L ; distinguer les effets des deux paramètres.',
         'Démontrer Ip′=−1/(1+p²), fixer la constante à p→∞ et justifier p→0 grâce à une borne de queue uniforme.'],
        'Intégration par parties, sinus cardinal et oscillations.',
        'Intégrales impropres, dérivation sous intégrale et convergence conditionnelle.',
        'Méthodes d’Abel, distributions et quadratures oscillantes.',
        'La valeur π/2 obtenue avec un passage au bord justifié et des erreurs identifiées.'),
    'porte_sinc': guide(
        'Relier une durée finie, un spectre sinc et la phase d’un retard. L’expérience introduit la convention de Fourier en Hz et l’aire d’une impulsion.',
        'L en s ; t₀ centre temporel en s|Porte d’amplitude 1 ; f̂ a l’unité s|sincₙ(u)=sin(πu)/(πu), sincₙ(0)=1 ; le PDF écrit aussi sin z/z',
        'TF bilatérale en Hz, noyau e^(−2iπνt)|Module et phase distingués ; phase indéfinie aux zéros|Porte idéale discontinue, spectre non borné',
        'Intégrale exponentielle|Translation et dilatation|Limite en zéro et bilan d’aire',
        ['Pour L=1, t₀=0, calculer l’aire et les deux premiers zéros spectraux.',
         'Réduire L à 0,3 puis déplacer t₀ de 0 à 1,3 à L fixé ; distinguer changements de module et de phase.',
         'Démontrer f̂=L sincₙ(Lν)e^(−2iπνt₀), puis préparer une porte d’aire 1 en divisant l’amplitude par L.'],
        'Intégration complexe, oscillations et unités de fréquence.',
        'Fourier, phase de retard et distribution de Dirac en introduction.',
        'Résolution spectrale, limites de moments et distributions tempérées.',
        'Une TF normalisée avec aire, premiers zéros et phase de translation cohérents.'),
    'gaussienne': guide(
        'Définir des largeurs temps–fréquence à partir des densités d’énergie, puis montrer l’égalité gaussienne de l’incertitude. L’amplitude et l’écart type sont étudiés séparément.',
        'σ en s est la largeur de l’amplitude Aexp[−t²/(2σ²)]|Δt et Δν sont les écarts types de |f|²/E et |f̂|²/E|E=A²σ√π ; Fourier en Hz',
        'Gaussienne sur ℝ, à moments finis|Borne d’incertitude en prolongement selon filière|Les demi-largeurs ou premiers zéros sont d’autres mesures',
        'Intégrale gaussienne|Équation différentielle pour la TF|Moments quadratiques et Cauchy–Schwarz',
        ['Pour σ=0,6,A=1, calculer Δt et Δν avant de lire les graphes.',
         'Doubler A puis diviser σ par deux ; séparer énergie et largeurs normalisées.',
         'Démontrer la TF par f′=−tf/σ², puis retrouver ΔtΔν=1/(4π) avec les bonnes densités.'],
        'Gaussienne et changements d’échelle, avec calculs de moments accompagnés.',
        'Parseval et inégalité de Cauchy–Schwarz appliqués à un signal régulier.',
        'Incertitude de Heisenberg, paquets d’ondes et fonctions de Gabor.',
        'Une largeur d’énergie correcte et un facteur 4π expliqué par la convention en Hz.'),
    'convolution_portes': guide(
        'Calculer une convolution par la géométrie du recouvrement avant d’utiliser le produit spectral. Une sonde mobile rend l’intégrande observable.',
        'L₁,L₂ et d en s ; amplitude des deux portes égale à 1|t sonde le recouvrement de [−L₁/2,L₁/2] et [t−d−L₂/2,t−d+L₂/2]|Convolution de dimension s, aire totale L₁L₂',
        'Convolution bilatérale sur ℝ|Portes à support compact, Fubini justifié|Triangle si largeurs égales, trapèze sinon',
        'Intersection d’intervalles|Intégrale et convolution|Fubini et produit de TF',
        ['Choisir L₁=L₂=1,d=0 et prévoir support, sommet et aire du triangle.',
         'Passer à L₁=0,6,L₂=2,d=0,5 ; déplacer la sonde et mesurer le plateau.',
         'Retrouver la formule min/max et vérifier l’aire au point spectral ν=0.'],
        'Intervalles, aires et fonctions définies par morceaux.',
        'Convolution, changements de variables et théorème spectral.',
        'Réponses de systèmes linéaires et B-splines.',
        'Un triangle ou trapèze normalisé et son produit spectral, avec unités et aire vérifiées.'),
    'gibbs_fourier': guide(
        'Comparer trois classes de signaux et deux procédés de sommation. Le but est de distinguer convergence L², uniforme, aux sauts et lissage par noyau positif.',
        'N est le dernier indice harmonique, pas le nombre de coefficients non nuls|T période en s ; créneau ±1, triangle 0→1, rampe −1→1|Fejér pondère par 1−∣k∣/(N+1)',
        'Signaux périodiques réguliers par morceaux|Valeur limite aux sauts = demi-somme latérale|La comparaison utilise le même dernier indice N',
        'Parité et coefficients de Fourier|Convergence normale vs saut|Moyenne de Cesàro et noyau positif',
        ['Choisir le créneau, prévoir sa valeur reconstruite au saut et le sens du dépassement.',
         'Comparer N=10 et N=55 puis le triangle ; observer somme partielle et Fejér séparément.',
         'Justifier l’échec de CU pour le créneau, la CN du triangle et le contrôle d’amplitude de Fejér.'],
        'Harmoniques et synthèse de signaux, avec coefficients fournis.',
        'Séries de Fourier, convergence aux raccords et norme L².',
        'Théorème de Fejér, constantes de Lebesgue et approximation positive.',
        'Une explication du dépassement persistant et un choix de sommation adapté au signal.'),
    'parseval_spectre': guide(
        'Transformer un bilan d’énergie harmonique en sommes classiques. L’expérience met en relation projection orthogonale, puissance moyenne et erreur quadratique.',
        'E=(1/T)∫|f|²dt ; cₙ normalisés par 1/T|N borne les harmoniques conservées ; énergie capturée et reste séparés|Triangle 0→1 : moyenne 1/2 ; créneau ±1 : moyenne 0',
        'Signaux réels périodiques dans L²|Les carrés des amplitudes portent un facteur 1/2 hors composante continue|La norme moyenne ne décrit pas une erreur maximale',
        'Orthogonalité|Parseval et Pythagore|Séparation d’indices pairs/impairs',
        ['Pour le créneau, calculer l’énergie de la première harmonique avant de lire son pourcentage.',
         'Passer au triangle et repérer la contribution 1/4 de sa moyenne ; augmenter N.',
         'Déduire π²/6 et π⁴/90 avec Parseval puis expliquer pourquoi un faible reste L² ne supprime pas Gibbs.'],
        'Produit scalaire, trigonométrie et énergie de sinusoïdes.',
        'Projection, Parseval et sommes classiques de Fourier.',
        'Complétude dans L² et compression spectrale.',
        'Un bilan exact d’énergie et deux sommes numériques obtenues avec les facteurs corrects.'),
    'poisson_noyau': guide(
        'Sommer le noyau de Poisson p.108, contrôler sa troncature normale et utiliser sa positivité pour lisser un signal. La limite r→1 se lit comme une approximation de l’identité.',
        'r∈[0,1[ ; T période en s ; N dernier indice|Pᵣ de masse T ; filtre périodique normalisé par 1/T|Chaque harmonique est multipliée par r^|k|',
        'Le banc reste à r≤0,97|La limite r→1 se traite après la somme infinie|La borne de queue est uniforme en t pour r fixé',
        'Deux séries géométriques|Critère de Weierstrass|Convolution périodique et positivité',
        ['Avec r=0,35, prévoir quelles harmoniques survivent ; vérifier la moyenne inchangée.',
         'Comparer r=0,94,N=70 à r=0,97,N=12 ; observer noyau exact et noyau tronqué.',
         'Démontrer la masse T, le reste≤2r^(N+1)/(1−r) et l’absence de dépassement pour le filtrage exact.'],
        'Sommes géométriques complexes et premières harmoniques.',
        'Convergence normale, convolution et contrôle uniforme.',
        'Équation de Laplace dans le disque et extension harmonique.',
        'Un filtre de masse 1 dont précision et effet sur chaque coefficient sont quantifiés.'),
    'poisson_gaussienne': guide(
        'Rendre concrète la formule de Poisson p.108 en comparant une périodisation temporelle et ses raies de Fourier. La gaussienne donne un cadre où tous les échanges sont justifiés.',
        'σ et T en s ; N borne les raies |k|≤N|cₖ=ŝ(k/T)/T ; c₀=σ√(2π)/T|La somme temporelle utilise automatiquement assez de répétitions lointaines',
        'Gaussienne de Schwartz, TF en Hz|Identité exacte, deux approximations tronquées|L’écart affiché compare ces troncatures, pas une erreur du théorème',
        'Périodisation et coefficients|TF gaussienne|Fubini et convergence normale',
        ['Avec σ=0,14,T=1,5, prévoir si le signal ressemble à des impulsions séparées.',
         'Augmenter σ à 1 puis réduire N ; comparer c₀ et les raies restantes.',
         'Démontrer cₖ=ŝ(k/T)/T et utiliser l’identité gaussienne pour choisir la somme la plus rapide.'],
        'Gaussiennes répétées et lecture de spectre discret.',
        'Sommation de Poisson et normalisations temps–fréquence.',
        'Fonctions thêta, accélération de séries et réseaux de Bravais.',
        'Une identité vérifiée par deux constructions avec sa moyenne et ses facteurs 1/T explicites.'),
    'shannon': guide(
        'Partir d’un paquet vraiment à bande limitée et démontrer la reconstruction. Le spectre précède le critère de mesure ; la troncature sinc est isolée du repliement.',
        's(t)=sincₙ²(Bt)cos(2πf₀t), B,f₀,F en Hz|M mesures de chaque côté :2M+1 valeurs ; tₙ=n/F|Support spectral jusqu’à W=f₀+B ; marge choisie F>2W',
        'Signal continu dans L¹∩L²|La formule exacte utilise une infinité de mesures|La somme affichée est tronquée ; les courbes spectrales conservent le facteur F du peigne',
        'Porte/triangle en TF|Peigne de Dirac et Shannon|Borne de bande vs erreur de troncature',
        ['Avec B=3,f₀=5, dessiner les deux bandes et calculer le seuil strict 16 Hz.',
         'Comparer F=24 et F=12 puis, au-dessus du seuil, M=8 et M=40.',
         'Retrouver les facteurs du peigne et du filtre idéal ; expliquer pourquoi la réussite aux points ne prouve pas une reconstruction entre points.'],
        'Mesure discrète et sinc avec un guidage spectral.',
        'Shannon, produits de TF et normalisations selon filière.',
        'Espaces de Paley–Wiener, reconstruction stable et échantillonnage non uniforme.',
        'Un seuil justifié par un support, puis deux erreurs distinctes : repliement et somme finie.'),
    'aliasing': guide(
        'Prouver que des fréquences physiques différentes donnent exactement les mêmes mesures. Explorer le signe de la fréquence apparente et la perte de phase à Nyquist.',
        'f,F en Hz ; phase φ en degrés|Échantillons à k/F ; représentant signé dans [−F/2,F/2[|Fréquence absolue du motif et phase adaptée sont deux informations',
        'Sinusoïdes idéales périodiques, illustration d’ambiguïté|Elles sont distinctes du paquet à énergie finie du labo Shannon|Au bord de Nyquist, la phase n’est pas complètement identifiable',
        'Congruence de phases modulo 2π|Parité du sinus/cosinus|Contre-exemple de mesure',
        ['Avec F=24,f=19,φ=30°, prédire le représentant−5 Hz puis comparer les points.',
         'Choisir f=12 Hz et tester plusieurs phases, dont 0° ; observer une sinusoïde invisible aux instants de mesure.',
         'Écrire l’égalité des arguments modulo 2π et une représentation à fréquence positive avec phase corrigée.'],
        'Sinusoïdes, phases et périodicité.',
        'Repliement et limite d’un théorème de reconstruction.',
        'Signaux complexes, modulation IQ et bandes repliées.',
        'Une ambiguïté démontrée par une égalité exacte de mesures et un cas limite interprété.'),
    'anti_repliement': guide(
        'Construire une chaîne où le filtre intervient avant la mesure. Quantifier atténuation du parasite, fidélité de la composante utile et limites d’un filtrage à pente finie.',
        'F,fc et fréquence parasite en Hz ; utile à 3 Hz|n ordre Butterworth ; amplitude parasite sans unité|Pôles analogiques en s⁻¹ ; gains complexes avec phase',
        'Butterworth analogique idéal stable en régime permanent|Coupure à−3,01 dB, pas suppression exacte hors bande|Le filtre numérique après mesure ne distingue pas des contributions repliées identiques',
        'Pôles du demi-plan gauche|Inégalités de gain|Chaîne analogique puis mesure discrète',
        ['Calculer le repliement de 72 Hz à F=50 Hz avant de regarder les sorties.',
         'Comparer n=1 et n=4 à fc=12 Hz ; suivre le gain utile et le gain parasite.',
         'Déterminer un ordre minimal pour une atténuation spécifiée et expliquer pourquoi fc doit aussi respecter la bande utile.'],
        'Filtres, diagrammes de gain et cadence de mesure.',
        'Ordre, pôles et conception selon cahier des charges en physique/SI.',
        'Filtres analogiques réels, tolérances et architectures de conversion.',
        'Une atténuation chiffrée avant mesure avec un compromis utile/parasite clairement annoncé.'),
    'fenetres_fft': guide(
        'Mesurer un spectre sur une acquisition finie, calibrer ses amplitudes et distinguer fenêtre, fuite et interpolation par ajout de zéros.',
        'F=128 Hz fixe ; N valeurs, durée DFT N/F|f en Hz ; fenêtre périodique rect/Hann/Blackman|padding ajoute des zéros ; CG et ENBW décrivent gain cohérent et bande de bruit',
        'Cosinus isolé de phase 0,3 rad ; FFT monolatérale|Amplitude corrigée par Σw et doublée hors DC/Nyquist|Une raie hors case garde un biais dépendant de la fenêtre',
        'DFT et sommes de Riemann|Produit temporel/convolution spectrale|Calibration d’amplitude et largeur de lobe',
        ['Choisir f=13 Hz,N=256,rect : calculer la case native 26 avant de lire la FFT.',
         'Passer à 13,375 Hz puis comparer les fenêtres ; observer lobe principal et lobes secondaires.',
         'Augmenter uniquement padding ; distinguer F/N et F/(N·padding), et retrouver le facteur de calibrationΣw.'],
        'Sinusoïde mesurée et observation finie, introduction numérique.',
        'Fourier/DFT, résolution et calibration selon filière.',
        'ENBW, estimateurs spectraux et métrologie du bruit.',
        'Un spectre avec fréquence, amplitude et limite de résolution explicitement distinguées.'),
    'resolution': guide(
        'Comparer des acquisitions ayant le même pas d’affichage mais des durées différentes. Les battements et les lobes expliquent la séparation de fréquences proches.',
        'F=128 Hz ; N règle la durée T=N/F|Deux fréquences 18 et 18+ΔfHz ; amplitudes égales|padding règle l’interpolation, pas la durée',
        'Signal sans bruit et phases initiales nulles|Fenêtre de Hann : largeur entre premiers zéros environ 4/T|Pas natif 1/T et résolution effective distincts',
        'Formule de somme de cosinus|Battements|Compromis durée/fréquence',
        ['Pour Δf=1 Hz, prévoir l’intervalle entre maxima et le premier zéro d’enveloppe.',
         'Comparer N=64,padding=8 et N=512,padding=1 ; observer le même pas mais des lobes différents.',
         'Exprimer le rôle de Δf·T et annoncer le critère de séparation utilisé, sans faire de 1/T une loi universelle.'],
        'Battements et lecture d’enveloppe.',
        'Résolution spectrale, fenêtres et acquisition.',
        'Superrésolution paramétrique, estimation et rapport signal/bruit.',
        'Une comparaison démontrant que durée et interpolation produisent des informations différentes.'),
    'spectrogramme': guide(
        'Suivre une fréquence variable et choisir une fenêtre locale. La carte relie dérivation de phase et compromis de localisation dans deux domaines.',
        'F=128 Hz, durée 3 s ; chirp de f₀ à f₁|L points par Hann mobile, avance 8 points|Carte en dB relatifs au maximum, FFT locales complétées à 256 points',
        'Fréquences du chirp sous 64 Hz|Carte relative, sans calibration absolue de puissance|Une fenêtre locale ne rend pas exactement stationnaire un chirp',
        'Dérivation de phase|Transformée de Fourier à fenêtre|Analyse d’échelles temporelle/fréquentielle',
        ['Calculer la pente pour 8→48 Hz en 3 s et prévoir la fréquence à 1,2 s.',
         'Comparer L=16 puis 128 ; repérer largeur fréquentielle et étalement temporel.',
         'Évaluer |k|L/F et F/L, puis expliquer la normalisation relative et le rôle de la ligne analytique.'],
        'Phase et fréquence instantanée ; lecture d’une carte guidée.',
        'Analyse temps–fréquence en prolongement du programme selon filière.',
        'STFT, ondelettes, réaffectation et signaux non stationnaires.',
        'Une fenêtre choisie avec deux échelles et une carte dont les unités relatives sont comprises.'),
    'modulation': guide(
        'Transmettre un message par traduction de son spectre puis le retrouver par mélange synchrone. Comprendre les bandes latérales, la surmodulation et l’accord de l’oscillateur local.',
        'fm et fc en Hz ; m profondeur sans unité|Δf est le désaccord local en Hz ; φ phase en degrés|Barres positives = amplitudes de cosinus, non poids bilatéraux de Dirac',
        'AM à porteuse transmise et canal idéal|Démodulation par passe-bas idéal supprimant analytiquement les termes autour de 2fc|Pour m>1, l’enveloppe signée traverse zéro',
        'Produit de cosinus|Translation de TF|Démodulation et phase',
        ['Avec m=0,7,fm=3,fc=30, prévoir fréquences et amplitudes des trois raies positives.',
         'Comparer φ=0° et 90°, puis Δf=0,8 Hz ; distinguer disparition et battements.',
         'Développer les produits trigonométriques et tester m=1,4 pour expliquer la limite d’une détection d’enveloppe.'],
        'Identités trigonométriques, modulation et détection guidées.',
        'Spectre AM et démodulation synchrone selon filière.',
        'Modulations IQ, porteuse supprimée et communications numériques.',
        'Une chaîne d’émission/réception reconstruite avec les facteurs 1/2 et l’effet de phase.'),
    'correlation_retard': guide(
        'Mesurer le retard d’une impulsion codée dans le bruit et relier le résultat à un trajet aller-retour. Le produit scalaire fournit la normalisation et explique le signe du pic.',
        'Émission g, réception f ; Cfg(τ)=∫ḡ(t)f(t+τ)dt|Cadence 200 Hz, grille de retard 5 ms ; retard en s|Vitesse c en m/s ; distance cτ/2 ; graine choisit une réalisation de bruit',
        'Fenêtre finie de 3 s, signaux réels, bruit gaussien|Normalisation par les énergies globales ; module ≤1 par Cauchy–Schwarz|Bruit et maxima secondaires peuvent déplacer le pic',
        'Produit scalaire glissant|Cauchy–Schwarz|Temps de vol et convention de corrélation',
        ['Pour un retard 0,6 s et c=350m/s, prévoir la distance et le signe du pic.',
         'Augmenter le bruit puis changer la graine sans changer le retard ; observer la robustesse et ses limites.',
         'Écrire Cfg=Cgg(τ−d), calculer le pas de distance et relier TF(Cff) à |f̂|².'],
        'Temps de vol et produit scalaire sur des données.',
        'Corrélation, normalisation et Fourier selon filière.',
        'Filtre adapté, radar/sonar et probabilités de détection.',
        'Un retard de signe fixé, une distance calculée et une limite de précision sans certitude inventée.'),
    'debruitage': guide(
        'Quantifier séparément le bruit restant et la déformation utile. Une moyenne causale et un filtre récursif donnent deux mémoires et deux calculs exacts de variance.',
        'F=128 Hz ; signal sin(2πft)+0,25sin(4πft)|M longueur de mémoire ; récursif de pôleρ=e^(−1/M)|Écart type du bruit et RMS de sortie ; début du signal exclu du bilan',
        'Bruit blanc centré indépendant, réalisation reproductible|Filtres au repos initial ; transitoire partiellement écarté|Bilan théorique stationnaire et RMS finie distincts',
        'Convolution discrète et récurrence|Linéarité|Variance d’une somme indépendante et phase du filtre',
        ['Pour moyenne M=9, prévoir le facteur 1/9 de variance et le retard 4/F.',
         'Comparer mémoire 5 à 31 puis le récursif ; observer bruit résiduel et signal propre filtré.',
         'Démontrer σ²Σh² et les deux facteurs théoriques ; expliquer pourquoi une sortie très lisse peut être une mauvaise mesure du signal utile.'],
        'Moyenne, bruit et retards, première expérimentation accompagnée.',
        'Filtres numériques et calcul de variance en lien avec probabilités.',
        'Filtrage de Wiener, bruit coloré et estimation optimale.',
        'Un compromis bruit/distorsion chiffré à partir de deux références distinctes.'),
}

for index, lab_id in enumerate(ORDER):
    LAB_GUIDES[lab_id]['lesson_numbers'] = [2*index+1,2*index+2]
