'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const colors=['#6950a4','#c48538','#367f96','#b85b77','#7b8c38'];
let labs=[],lessons=[],exercises=[],guides={},figures=[],token='',active=null,params={},result=null,sequence=0,paused=false,time=0,lastTime=0,particles=[],timer=null;
const fmt=n=>typeof n==='number'?(n===0?'0':Math.abs(n)<.001||Math.abs(n)>=1e5?n.toExponential(3):Number(n.toPrecision(5)).toLocaleString('fr-FR')):String(n);
const element=(tag,className,text)=>{const e=document.createElement(tag);if(className)e.className=className;if(text!==undefined)e.textContent=text;return e;};
function view(name){['home','laboratory','course'].forEach(id=>$(id).hidden=id!==name);document.querySelector('.hero').hidden=name!=='home';}
function home(){active=null;result=null;view('home');$('lab-picker').value='home';$('status').textContent=`${labs.length} expériences · ${lessons.length} leçons · ${exercises.length} exercices corrigés`;$('error').hidden=true;window.scrollTo({top:0,behavior:'instant'});}
function renderGuide(id){const g=guides[id],box=$('lab-guide');box.replaceChildren();box.hidden=!g;if(!g)return;box.innerHTML=`<p class="eyebrow">POUR ABORDER LE TP</p><h3>But du TP et lien avec le cours</h3><p class="guide-purpose">${esc(g.purpose)}</p><p class="guide-expected"><b>À l’issue du TP :</b> ${esc(g.expected)}</p><div class="guide-objects"><div><b>Objets, variables et unités</b><ul>${(g.objects||[]).map(t=>`<li>${esc(t)}</li>`).join('')}</ul></div><div><b>Cadre de l’expérience</b><ul>${(g.hypotheses||[]).map(t=>`<li>${esc(t)}</li>`).join('')}</ul></div></div><div class="guide-techniques"><b>Les techniques à réinvestir</b><ul>${g.techniques.map(t=>`<li>${esc(t)}</li>`).join('')}</ul></div><div class="guide-levels">${[['sup','Sup'],['spe','Spé'],['beyond','Au-delà']].map(([k,n])=>`<div class="guide-level"><h4>${n}</h4><p>${esc(g.levels[k])}</p></div>`).join('')}</div><p class="level-note">Sup et spé indiquent les acquis à réinvestir, selon votre filière. Les notions nouvelles et les limites des modèles sont introduites explicitement.</p><div class="guide-links"><b>Préparer et justifier avec le cours :</b></div><details><summary>Un premier parcours en trois gestes</summary><ol>${g.first_steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol></details>`;for(const number of g.lesson_numbers){const l=lessons[number-1];if(!l)continue;const b=element('button','',l.title);b.onclick=()=>showCourse(number-1);box.querySelector('.guide-links').append(b);}}
function controlOptions(c){return (c.options||[]).map(o=>typeof o==='string'?{value:o,label:o}:Array.isArray(o)?{value:o[0],label:o[1]}:o);}
function controlVisible(c){return true;}
function renderControls(){const box=$('controls');box.replaceChildren();for(const c of active.controls){if(!controlVisible(c))continue;const d=element('div','control'),label=element('label','',c.label),out=element('output','',fmt(params[c.key])+(c.unit?' '+c.unit:''));label.htmlFor='control-'+c.key;d.append(label);let input;if(c.type==='select'||c.options){input=element('select');for(const o of controlOptions(c)){const option=element('option','',o.label);option.value=o.value;input.append(option);}input.value=params[c.key];}else{input=element('input');input.type='range';for(const k of ['min','max','step'])input[k]=c[k];input.value=params[c.key];label.append(out);}input.id='control-'+c.key;input.oninput=()=>{params[c.key]=input.tagName==='SELECT'?input.value:Number(input.value);out.textContent=fmt(params[c.key])+(c.unit?' '+c.unit:'');if(c.key==='mode')renderControls();clearTimeout(timer);timer=setTimeout(update,140);};d.append(input);box.append(d);}const p=$('presets');p.replaceChildren();for(const preset of active.presets||[]){const b=element('button','',preset.label);b.onclick=()=>{params={...params,...preset.values};renderControls();update();};p.append(b);}}
function showLab(id){active=labs.find(l=>l.id===id);if(!active)return;params=Object.fromEntries(active.controls.map(c=>[c.key,c.value??c.default]));result=null;paused=false;$('pause').textContent='Pause';time=0;view('laboratory');$('lab-picker').value=id;$('lab-category').textContent=active.category+' · MODÉLISER ET CONTRÔLER';$('lab-title').textContent=active.title;$('lab-intro').textContent=active.intro;renderGuide(id);renderControls();const index=lessons.findIndex(l=>l.lab===id);$('theory').innerHTML=index<0?'':`<h3>${esc(lessons[index].title)}</h3>${lessons[index].html}`;for(const f of figures.filter(f=>(f.labs||[]).includes(id))){const figure=element('figure');const img=element('img');img.src='/illustrations/'+f.file;img.alt=f.title;img.loading='lazy';figure.append(img,element('figcaption','',f.caption||f.title));$('theory').append(figure);}$('lesson-button').onclick=()=>showCourse(Math.max(0,index));update();window.scrollTo({top:0,behavior:'instant'});}
async function update(){if(!active)return;const lab=active.id,n=++sequence;$('status').textContent='Calcul des fonctions, solutions et contrôles…';$('error').hidden=true;try{const response=await fetch('/api',{method:'POST',headers:{'Content-Type':'application/json','X-Analyse-Token':token},body:JSON.stringify({lab,...params})});const r=await response.json();if(n!==sequence||active?.id!==lab)return;if(!response.ok)throw new Error(r.error);result=r;particles=[];time=0;$('metrics').replaceChildren();for(const m of r.metrics){const d=element('div','metric');d.append(element('span','',m.label),element('b','',fmt(m.value)),element('small','',typeof m.value==='number'?(m.unit||''):''));$('metrics').append(d);}$('charts').replaceChildren();for(const c of r.charts||[])renderChart(c);$('steps').replaceChildren(...(r.steps||[]).map(s=>element('li','',s)));$('assumptions').replaceChildren(...(r.assumptions||[]).map(s=>element('li','',s)));renderTable(r.table);setupScene(r);$('status').textContent='Calcul terminé · justifications et hypothèses disponibles';}catch(e){if(n===sequence){$('error').textContent=e.message;$('error').hidden=false;$('status').textContent='Ajuster les paramètres de l’expérience.';}}}
function renderChart(c){const card=element('section','chart');card.append(element('h3','',c.title));const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 560 320');svg.setAttribute('role','img');svg.setAttribute('aria-label',c.title+` ; ${c.x_label} ; ${c.y_label}`);const raw=(c.series||[]).flatMap(s=>s.x.map((x,i)=>[x,s.y[i]])).filter(([x,y])=>Number.isFinite(x)&&Number.isFinite(y)&&(c.x_scale!=='log'||x>0)&&(c.y_scale!=='log'||y>0));if(!raw.length){card.append(element('p','','Aucune valeur dans ce domaine.'));$('charts').append(card);return;}const tx=x=>c.x_scale==='log'?Math.log10(x):x,ty=y=>c.y_scale==='log'?Math.log10(y):y;const xs=raw.map(p=>tx(p[0])),ys=raw.map(p=>ty(p[1]));let xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Number.isFinite(c.yMin)?ty(c.yMin):Math.min(...ys),ymax=Number.isFinite(c.yMax)?ty(c.yMax):Math.max(...ys);if(xmin===xmax)xmax=xmin+1;if(ymin===ymax){ymin-=.5;ymax+=.5;}const py=(ymax-ymin)*.055;ymin-=py;ymax+=py;const X=x=>62+(tx(x)-xmin)/(xmax-xmin)*471,Y=y=>263-(ty(y)-ymin)/(ymax-ymin)*228;const clip='graph-'+$('charts').children.length;let content=`<defs><clipPath id="${clip}"><rect x="62" y="35" width="471" height="228"/></clipPath></defs>`;for(let i=0;i<5;i++){const x=xmin+(xmax-xmin)*i/4,y=ymin+(ymax-ymin)*i/4,xx=62+471*i/4,yy=263-228*i/4;content+=`<path d="M${xx} 35V263M62 ${yy}H533" stroke="#e0e7df"/><text x="${xx}" y="283" text-anchor="middle" font-size="10" fill="#5a7177">${esc(fmt(c.x_scale==='log'?10**x:x))}</text><text x="55" y="${yy+3}" text-anchor="end" font-size="10" fill="#5a7177">${esc(fmt(c.y_scale==='log'?10**y:y))}</text>`;}content+='<path d="M62 35V263H533" fill="none" stroke="#819a99"/>';if(Number.isFinite(c.xMarker)){const xx=X(c.xMarker);content+=`<path d="M${xx} 35V263" stroke="#aa6578" stroke-dasharray="5 4"/><text x="${Math.min(520,xx+6)}" y="29" font-size="10" fill="#874e62">${esc(c.xMarkerLabel||'Seuil')}</text>`;}for(let i=0;i<c.series.length;i++){const s=c.series[i];let pen=false,d='';s.x.forEach((x,j)=>{const y=s.y[j];if(!Number.isFinite(x)||!Number.isFinite(y)||(c.x_scale==='log'&&x<=0)||(c.y_scale==='log'&&y<=0)){pen=false;return;}d+=(pen?'L':'M')+X(x).toFixed(2)+' '+Y(y).toFixed(2);pen=true;});content+=`<path d="${d}" stroke="${colors[i%colors.length]}" fill="none" stroke-width="2.3" clip-path="url(#${clip})"/>`;}content+=`<text x="300" y="309" text-anchor="middle" font-size="11" fill="#173944">${esc(c.x_label)}${c.x_scale==='log'?' (log)':''}</text><text transform="translate(13 150) rotate(-90)" text-anchor="middle" font-size="11" fill="#173944">${esc(c.y_label)}${c.y_scale==='log'?' (log)':''}</text>`;svg.innerHTML=content;card.append(svg);const legend=element('div','legend');c.series.forEach((s,i)=>{const span=element('span');const dot=element('i');dot.style.background=colors[i%colors.length];span.append(dot,document.createTextNode(s.label));legend.append(span);});card.append(legend);$('charts').append(card);}
function canvasContext(canvas){const w=canvas.clientWidth||700,h=canvas.clientHeight||380,dpr=window.devicePixelRatio||1;if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);}const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);return{ctx,w,h};}
function line(ctx,p,color='#c9b8ed',width=2,dash=[]){if(!p.length)return;ctx.beginPath();let pen=false;for(const q of p){if(!q.every(Number.isFinite)){pen=false;continue;}if(pen)ctx.lineTo(...q);else ctx.moveTo(...q);pen=true;}ctx.strokeStyle=color;ctx.lineWidth=width;ctx.setLineDash(dash);ctx.stroke();ctx.setLineDash([]);}
function dot(ctx,x,y,r=4,color='#edc27c'){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();}
function text(ctx,str,x,y,color='#d9d3e8',size=12){ctx.fillStyle=color;ctx.font=size+'px Segoe UI';ctx.fillText(str,x,y);}
function arrow(ctx,x,y,dx,dy,color='#b3a2da',width=1){const a=Math.atan2(dy,dx),ex=x+dx,ey=y+dy;line(ctx,[[x,y],[ex,ey]],color,width);line(ctx,[[ex-4*Math.cos(a-.45),ey-4*Math.sin(a-.45)],[ex,ey],[ex-4*Math.cos(a+.45),ey-4*Math.sin(a+.45)]],color,width);}
const sceneColors=['#c4b5f0','#e4b56f','#86c9d5','#ee9caf','#c2d593'];
let inspectPoint=null;

function renderTable(data){const box=$('computed-table');box.replaceChildren();box.hidden=!data;if(!data)return;const table=element('table');const head=element('thead'),row=element('tr');for(const label of data.headers||[])row.append(element('th','',label));head.append(row);table.append(head);const body=element('tbody');for(const values of data.rows||[]){const row=element('tr');for(const v of values)row.append(element('td','',fmt(v)));body.append(row);}table.append(body);box.append(element('h3','','Lire les contributions calculées'),table);}

function setupScene(r){const s=r.scene;$('visual').hidden=!s;if(!s)return;$('scene').style.height='410px';$('visual-title').textContent=s.title||active.title;$('visual-caption').textContent=(s.description||'Vue construite à partir des valeurs calculées.')+' Le curseur parcourt les données : il ne représente pas un temps physique. Survoler ou toucher le dessin pour lire les coordonnées.';$('scene').setAttribute('aria-label',$('visual-title').textContent);$('scene-progress').value=0;inspectPoint=null;}
function curves(s){return (s.curves||s.paths||[]).map(p=>({...p,x:p.x||s.x||[]}));}
function diagramBounds(s,paths){if(s.bounds?.length===4)return s.bounds;const pts=paths.flatMap(p=>p.x.map((x,i)=>[x,p.y[i]])).filter(p=>p.every(Number.isFinite));if(!pts.length)return[0,1,0,1];let a=Math.min(...pts.map(p=>p[0])),b=Math.max(...pts.map(p=>p[0])),c=Math.min(...pts.map(p=>p[1])),d=Math.max(...pts.map(p=>p[1]));if(a===b)b=a+1;if(c===d){c-=.5;d+=.5;}const margin=(d-c)*.08;return[a,b,c-margin,d+margin];}
function diagramAxes(ctx,w,h,b,s){const left=90,right=w-28,top=60,bottom=h-75,X=x=>left+(x-b[0])/(b[1]-b[0])*(right-left),Y=y=>bottom-(y-b[2])/(b[3]-b[2])*(bottom-top);for(let j=0;j<5;j++){const x=b[0]+(b[1]-b[0])*j/4,y=b[2]+(b[3]-b[2])*j/4;line(ctx,[[X(x),top],[X(x),bottom]],'#45415f',.7);line(ctx,[[left,Y(y)],[right,Y(y)]],'#45415f',.7);text(ctx,fmt(x),X(x)-12,bottom+19,'#aaa1c1',10);ctx.save();ctx.textAlign='right';text(ctx,fmt(y),left-10,Y(y)+3,'#aaa1c1',10);ctx.restore();}line(ctx,[[left,top],[left,bottom],[right,bottom]],'#867698',1);text(ctx,s.xLabel||s.x_label||'x',Math.max(left,w/2-25),h-28,'#dcd3ed',11);ctx.save();ctx.translate(14,h/2);ctx.rotate(-Math.PI/2);ctx.textAlign='center';text(ctx,s.yLabel||s.y_label||'y',0,0,'#dcd3ed',11);ctx.restore();return{X,Y,left,right,top,bottom};}
function readProgress(n){const fraction=inspectPoint?inspectPoint[0]:(time/12)%1,i=Math.min(n-1,Math.max(0,Math.floor(fraction*n)));$('scene-progress').value=fraction;return i;}
function drawCurves(ctx,w,h,s){const paths=curves(s);if(!paths.length)return;const env=s.envelope&&{...s.envelope,x:s.envelope.x||s.x||paths[0].x};const all=env?[...paths,env]:paths,b=diagramBounds(s,all),a=diagramAxes(ctx,w,h,b,s);const n=Math.max(...paths.map(p=>p.x.length)),i=readProgress(n),q=paths[0],k=Math.min(i,q.x.length-1),x=q.x[k];ctx.save();ctx.beginPath();ctx.rect(a.left,a.top,a.right-a.left,a.bottom-a.top);ctx.clip();for(let j=0;j<paths.length;j++){const p=paths[j],col=sceneColors[j%5];line(ctx,p.x.map((x,k)=>[a.X(x),a.Y(p.y[k])]),col,j===0?2.7:1.8);const nearest=p.x.reduce((best,v,k)=>Math.abs(v-x)<Math.abs(p.x[best]-x)?k:best,0);dot(ctx,a.X(p.x[nearest]),a.Y(p.y[nearest]),4,col);}if(env)line(ctx,env.x.map((x,k)=>[a.X(x),a.Y(env.y[k])]),'#d6bd77',1.8,[5,4]);line(ctx,[[a.X(x),a.top],[a.X(x),a.bottom]],'#c3b2d9',1,[4,4]);if(s.fills!==false&&paths.length===1&&b[2]<=0&&b[3]>=0){ctx.beginPath();ctx.moveTo(a.X(q.x[0]),a.Y(0));for(let j=0;j<=k;j++)ctx.lineTo(a.X(q.x[j]),a.Y(q.y[j]));ctx.lineTo(a.X(x),a.Y(0));ctx.closePath();ctx.fillStyle='rgba(196,181,240,.13)';ctx.fill();}ctx.restore();for(let j=0;j<Math.min(3,paths.length);j++)text(ctx,paths[j].label||'Courbe '+(j+1),24,20+j*17,sceneColors[j%5],11);if(env)text(ctx,env.label||'Majorante intégrable',w*.57,22,'#d6bd77',11);$('scene-time').textContent='x = '+fmt(x)+' · y = '+fmt(q.y[k]);}
function drawField(ctx,w,h,s){const paths=curves(s),b=diagramBounds(s,paths),a=diagramAxes(ctx,w,h,b,s);const i=readProgress(Math.max(1,...paths.map(p=>p.x.length)));ctx.save();ctx.beginPath();ctx.rect(a.left,a.top,a.right-a.left,a.bottom-a.top);ctx.clip();for(const p of s.arrows||[]){const px=a.X(p.x),py=a.Y(p.y),dx=p.dx/(b[1]-b[0])*(a.right-a.left),dy=-p.dy/(b[3]-b[2])*(a.bottom-a.top),norm=Math.hypot(dx,dy)||1;arrow(ctx,px-7*dx/norm,py-7*dy/norm,14*dx/norm,14*dy/norm,'#655882',1);}paths.forEach((p,j)=>{const col=sceneColors[j%5],k=Math.min(i,p.x.length-1);line(ctx,p.x.map((x,k)=>[a.X(x),a.Y(p.y[k])]),col,1.2);line(ctx,p.x.slice(0,k+1).map((x,i)=>[a.X(x),a.Y(p.y[i])]),col,2.8);dot(ctx,a.X(p.x[k]),a.Y(p.y[k]),5,col);});ctx.restore();for(let j=0;j<Math.min(3,paths.length);j++)text(ctx,paths[j].label||'Solution '+(j+1),24,20+j*17,sceneColors[j%5],11);if(paths.length){const p=paths[0],k=Math.min(i,p.x.length-1);$('scene-time').textContent=fmt(p.x[k])+' ; '+fmt(p.y[k]);}}
function drawHeatmap(ctx,w,h,s){const x=s.x,y=s.y,z=s.z||[],nx=x.length,ny=y.length;if(!nx||!ny)return;const left=70,right=w-80,top=35,bottom=h-68,b=[Math.min(...x),Math.max(...x),Math.min(...y),Math.max(...y)];const max=Math.max(...z.flat().map(Math.abs)),scale=Math.max(max,1e-12);for(let j=0;j<ny;j++)for(let i=0;i<nx;i++){const v=z[j]?.[i]||0,q=Math.min(1,Math.abs(v)/scale);const rgb=v>=0?[120+110*q,116-30*q,158-50*q]:[120-50*q,116+70*q,158+50*q];ctx.fillStyle=`rgb(${rgb.map(Math.round).join(',')})`;ctx.fillRect(left+i*(right-left)/nx,top+(ny-1-j)*(bottom-top)/ny,(right-left)/nx+1,(bottom-top)/ny+1);}for(let i=0;i<5;i++){text(ctx,fmt(b[0]+(b[1]-b[0])*i/4),left+(right-left)*i/4-12,bottom+19,'#d9d3e8',10);text(ctx,fmt(b[2]+(b[3]-b[2])*i/4),10,bottom-(bottom-top)*i/4+3,'#d9d3e8',10);}text(ctx,s.xLabel||'x',w/2,h-27);text(ctx,s.yLabel||'y',10,20);for(let j=0;j<80;j++){const q=(j/79)*2-1,abs=Math.abs(q);ctx.fillStyle=`rgb(${q>=0?120+110*abs:120-50*abs},${q>=0?116-30*abs:116+70*abs},${q>=0?158-50*abs:158+50*abs})`;ctx.fillRect(w-51,top+(79-j)*2,16,3);}text(ctx,fmt(scale),w-65,top-8,'#d9d3e8',10);text(ctx,fmt(-scale),w-70,top+178,'#d9d3e8',10);text(ctx,'résidu',w-66,top+199,'#d9d3e8',10);const col=Math.min(nx-1,readProgress(nx)),row=inspectPoint?Math.min(ny-1,Math.floor((1-inspectPoint[1])*ny)):Math.floor(.72*ny),px=left+(col+.5)*(right-left)/nx,py=top+(ny-row-.5)*(bottom-top)/ny;ctx.strokeStyle='#edc27c';ctx.lineWidth=2;ctx.strokeRect(px-5,py-5,10,10);$('scene-time').textContent='('+fmt(x[col])+', '+fmt(y[row])+') · résidu '+fmt(z[row]?.[col]||0);text(ctx,'Maximum absolu mesuré : '+fmt(max),left,bottom+39,'#d9d3e8',11);}
function drawScene(){if(!result||$('visual').hidden||$('laboratory').hidden)return;const{ctx,w,h}=canvasContext($('scene'));ctx.clearRect(0,0,w,h);const s=result.scene;if(s.kind==='heatmap')drawHeatmap(ctx,w,h,s);else if(['field','phase'].includes(s.kind))drawField(ctx,w,h,s);else drawCurves(ctx,w,h,s);}
$('scene-progress').oninput=()=>{paused=true;inspectPoint=[Number($('scene-progress').value),.5];$('pause').textContent='Reprendre';drawScene();};
$('scene').addEventListener('pointermove',e=>{const box=e.currentTarget.getBoundingClientRect(),heat=result?.scene?.kind==='heatmap',left=heat?70:90,right=heat?80:28,top=heat?35:60,bottom=heat?68:75;inspectPoint=[Math.max(0,Math.min(.999,(e.clientX-box.left-left)/(box.width-left-right))),Math.max(0,Math.min(.999,(e.clientY-box.top-top)/(box.height-top-bottom)))];drawScene();});
$('scene').addEventListener('pointerleave',()=>{if(!paused)inspectPoint=null;});
$('scene').addEventListener('pointerdown',()=>{paused=true;$('pause').textContent='Reprendre';});
function thumbnail(canvas,id){const{ctx,w,h}=canvasContext(canvas);ctx.fillStyle='#ede8f4';ctx.fillRect(0,0,w,h);const P=(x,y)=>[25+x*(w-50),h*.8-y*h*.6],plot=(f,col='#6950a4')=>line(ctx,Array.from({length:161},(_,i)=>P(i/160,f(i/160))),col,2);line(ctx,[[25,15],[25,h*.82],[w-20,h*.82]],'#b9aecd',1);if(id.includes('cauchy')&&!id.includes('euler')){if(id==='cauchy_additive'){plot(x=>x*.8);plot(x=>.7*x+.1*Math.sin(x*15),'#c48538');}else{plot(x=>.05+Math.exp(2*x)*.09);plot(x=>.8-Math.exp(-3*x)*.7,'#c48538');}}
else if(id==='dalembert'){plot(x=>.4+.33*Math.cos(2*Math.PI*x));plot(x=>.1+.12*Math.cosh(2*x),'#c48538');}
else if(id==='identification_symetrie'){plot(x=>.2+.6*x*x);plot(x=>.8-.6*(1-x)**2,'#c48538');}
else if(id==='continuite_defaut'){for(let a of[.1,.3,.6])plot(x=>.08/a*Math.exp(-x/a),'#6950a4');}
else if(id.includes('gamma')){plot(x=>.02+(.12/(x+.14)+Math.exp(4*x)*.012));}
else if(id==='beta_geometrie'){plot(x=>8*x*(1-x)**2);plot(x=>8*x*x*(1-x),'#c48538');}
else if(id.includes('zeta')){plot(x=>.1+.18/(x+.22));for(let j=0;j<8;j++)dot(ctx,25+j*(w-50)/8,h*.8-(.13+.6/(j+1))*h*.6,2,'#c48538');}
else if(id.includes('fractionnaire')){plot(x=>Math.sqrt(x)*.75);plot(x=>x*.75,'#c48538');}
else if(id==='faa_di_bruno'){for(let j=0;j<5;j++){const x=(j+1)/6;line(ctx,[[w*.5,20],[w*x,h*.7]],'#b2a1cf',1);dot(ctx,w*x,h*.7,5,'#6950a4');}dot(ctx,w*.5,20,6,'#c48538');}
else if(id==='hermite_gauss'){plot(x=>Math.exp(-16*(x-.5)**2));plot(x=>.5+2*(x-.5)*Math.exp(-16*(x-.5)**2),'#c48538');}
else if(id==='lineaire_systeme'){for(let j=0;j<3;j++){dot(ctx,w*(.2+j*.3),h*.5,12,['#6950a4','#c48538','#367f96'][j]);if(j<2)arrow(ctx,w*(.2+j*.3)+16,h*.5,w*.2,0,'#9981bb');}}
else if(['cauchy_lipschitz','explosion_logistique'].includes(id)){for(let j=0;j<3;j++)plot(x=>id==='cauchy_lipschitz'?Math.max(0,x-j*.25)**2:.85/(1+Math.exp(8*(.5-x)+j)) ,['#6950a4','#c48538','#367f96'][j]);}
else if(['oscillateur_resonance','green_bords'].includes(id)){plot(x=>(.5+.4*Math.sin(x*7*Math.PI)*Math.exp(-x)));plot(x=>.5+.12*Math.sin(x*7*Math.PI),'#c48538');}
else if(id==='euler_rk4'){plot(x=>.2+.5*Math.sin(Math.PI*x));line(ctx,Array.from({length:6},(_,i)=>P(i/5,.2+.5*Math.sin(Math.PI*i/5)+i*.035)),'#c48538',2);}
else if(id==='euler_cauchy'){plot(x=>x*x*.75);plot(x=>.15+.45*x,'#c48538');}
else if(id==='riccati'){plot(x=>.15+.65*x*x);plot(x=>.3+.45*x*x,'#c48538');}
else if(id==='variation_constantes'){plot(x=>.1+.01*Math.exp(4*x));plot(x=>.25+.03*Math.exp(3*x),'#c48538');}
else if(id==='facteur_integrant'){plot(x=>.2+.6*(1-Math.exp(-3*x)));plot(x=>.8*Math.exp(-3*x),'#c48538');}
else if(id==='leibniz_frullani'){plot(x=>.7*Math.exp(-4*x));plot(x=>.5*Math.exp(-2*x),'#c48538');}
else if(id==='leibniz_arctan'){plot(x=>.7*Math.exp(-2*x)*Math.cos(7*x));}
else if(id==='derivees_laplace'){plot(x=>x*x*Math.exp(-5*x)*12);plot(x=>x*Math.exp(-5*x)*4,'#c48538');}
else{plot(x=>.8*Math.exp(-10*(x-.4)**2)*Math.cos(x*8));plot(x=>.8*Math.exp(-10*(x-.4)**2),'#c48538');}}
function drawHero(){const{ctx,w,h}=canvasContext($('hero-canvas'));ctx.clearRect(0,0,w,h);const a=(time*.25)%1,L=45,R=w-25,T=48,B=h-53,mid=(T+B)/2,scale=(B-T)/5;line(ctx,[[L,T],[L,B],[R,B]],'#8276aa',1);line(ctx,[[L,mid],[R,mid]],'#8276aa',1,[3,5]);for(let j=0;j<3;j++){const p=Array.from({length:241},(_,i)=>{const t=-3+6*i/240,g=Math.exp(-t*t),f=j===0?g:j===1?-2*t*g:(4*t*t-2)*g;return[L+(R-L)*i/240,mid-scale*f];});line(ctx,p,sceneColors[j],2);const k=Math.floor(a*240);dot(ctx,...p[k],4,sceneColors[j]);}text(ctx,'Gaussienne g ; dérivées g′ et g″ ; même échelle',24,24,'#e8dff5',12);text(ctx,'Un graphe suggère. Les hypothèses permettent de conclure.',24,h-16,'#d7c8ed',11);}

function showCourse(index=0){active=null;result=null;view('course');$('lab-picker').value='course';const l=lessons[index];$('lesson').innerHTML=`<p class="eyebrow">${esc(l.level)}</p><h2>${esc(l.title)}</h2>${l.html}`;const b=element('button','', 'Explorer le laboratoire associé');b.onclick=()=>showLab(l.lab);$('lesson').append(b);$('lesson-list').replaceChildren();lessons.forEach((lesson,i)=>{const button=element('button',i===index?'active':'',lesson.title);button.onclick=()=>showCourse(i);$('lesson-list').append(button);});$('status').textContent=`${lessons.length} leçons · ${exercises.length} exercices corrigés · hypothèses et niveaux explicités`;window.scrollTo({top:0,behavior:'instant'});}
function renderCourse(){const box=$('exercises');box.replaceChildren();$('exercise-title').textContent=exercises.length+' exercices corrigés';exercises.forEach((e,i)=>{const d=element('section','exercise');d.innerHTML=`<p class="eyebrow">${esc(e.level||'SUP / SPÉ · MÉTHODE')}</p><h3>${esc(e.title||'Exercice '+(i+1))}</h3><div>${e.question}</div><details><summary>Ouvrir la correction guidée</summary><div class="answer">${e.answer}</div></details>`;if(e.lab){const b=element('button','secondary','Expérimenter dans le laboratoire');b.onclick=()=>showLab(e.lab);d.append(b);}box.append(d);});$('gallery').replaceChildren();for(const f of figures){const figure=element('figure');const a=element('a');a.href='/illustrations/'+f.file;a.target='_blank';a.rel='noopener';const img=element('img');img.src=a.href;img.alt=f.title;img.loading='lazy';a.append(img);figure.append(a,element('figcaption','',f.caption||f.title));$('gallery').append(figure);}}
async function boot(){try{const r=await fetch('/api/bootstrap');const b=await r.json();token=b.token;labs=b.labs;lessons=b.lessons;exercises=b.exercises;guides=b.lab_guides;figures=b.figures||[];$('sources').innerHTML=b.sources.map(s=>'<p>'+s+'</p>').join('');const picker=$('lab-picker');for(const category of [...new Set(labs.map(l=>l.category))]){const group=element('optgroup');group.label=category;for(const l of labs.filter(l=>l.category===category)){const o=element('option','',l.title);o.value=l.id;group.append(o);}picker.append(group);}const opt=element('option','','Cours & exercices');opt.value='course';picker.append(opt);const cards=$('home-cards');for(const l of labs){const b=element('button','lab-card');const canvas=element('canvas');canvas.setAttribute('aria-hidden','true');b.append(canvas);const copy=element('div','card-copy');copy.innerHTML=`<p class="eyebrow">${esc(l.category)}</p><h3>${esc(l.title)}</h3><p>${esc(l.intro)}</p><b>Ouvrir l’expérience ↗</b>`;b.append(copy);b.onclick=()=>showLab(l.id);cards.append(b);}renderCourse();home();for(let i=0;i<labs.length;i++)thumbnail(cards.children[i].querySelector('canvas'),labs[i].id);$('home-tab').onclick=home;$('course-tab').onclick=()=>showCourse();picker.onchange=()=>picker.value==='home'?home():picker.value==='course'?showCourse():showLab(picker.value);document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>showLab(b.dataset.route));$('pause').onclick=()=>{paused=!paused;if(!paused)inspectPoint=null;$('pause').textContent=paused?'Reprendre':'Pause';};$('export').onclick=()=>{if(!result)return;const a=element('a');a.href='/api/export/'+result.export_id;a.download='analyse-'+result.lab+'.json';document.body.append(a);a.click();a.remove();};}catch(e){$('error').textContent='Impossible de charger l’atelier : '+e.message;$('error').hidden=false;$('status').textContent='Recharger la page après le lancement du serveur.';}}
function frame(now){const dt=Math.min(.05,(now-lastTime)/1000||.016);lastTime=now;if(!paused)time+=dt;drawScene();if(!$('home').hidden)drawHero();requestAnimationFrame(frame);}boot();requestAnimationFrame(frame);
