"""Recherche de fonctions et six applications des trois théorèmes du recueil, p. 63."""
from commun import lab, slider, select, preset

LABS = [
    lab('cauchy_additive', 'Cauchy : une équation à deux variables détermine une droite', 'Équations fonctionnelles',
        'Chercher toutes les fonctions continues vérifiant f(x+y)=f(x)+f(y). Les substitutions 0, −x et les multiples rationnels donnent des conditions nécessaires ; la continuité permet de passer des rationnels aux réels. La carte représente le défaut de l’équation pour des couples (x,y). Une perturbation sinusoïdale peut paraître petite sur une courbe, mais elle ne vérifie plus l’équation.',
        [slider('a', 'Pente a de la solution ax', -2, 2, .1, 1), slider('b', 'Perturbation b dans ax+b sin x', -1, 1, .05, .3)],
        [preset('Solution exacte', a=1, b=0), preset('Une courbe presque droite', a=1, b=.1), preset('La dérivée en 0 ne suffit pas', a=.5, b=.7)]),
    lab('cauchy_multiplicative', 'Produit, logarithme, puissance : changer de variable pour résoudre', 'Équations fonctionnelles',
        'Sur les réels strictement positifs, x=eᵘ transforme les produits en sommes. Comparer f(xy)=f(x)+f(y), dont les solutions continues sont a ln x, et f(xy)=f(x)f(y), dont les solutions continues non nulles sont xᵃ. La carte utilise les coordonnées u=ln x et v=ln y : son résidu mesure la véritable équation choisie.',
        [select('equation', 'Équation sur x,y>0', [('log', 'f(xy)=f(x)+f(y)'), ('power', 'f(xy)=f(x)f(y)')], 'log'), slider('a', 'Coefficient a', -2, 2, .1, 1), slider('b', 'Amplitude du défaut b', -.7, .7, .05, .2)],
        [preset('Logarithme exact', equation='log', a=1, b=0), preset('Puissance exacte', equation='power', a=1.5, b=0), preset('Exposant négatif : inverse', equation='power', a=-1, b=0), preset('Une perturbation à détecter', equation='power', a=.5, b=.3)]),
    lab('dalembert', 'D’Alembert : pourquoi apparaissent cosinus et cosinus hyperbolique ?', 'Équations fonctionnelles',
        'L’équation f(x+y)+f(x−y)=2f(x)f(y) contient les formules d’addition du cosinus et du cosinus hyperbolique. Les valeurs en 0, la parité puis deux dérivations en y permettent, pour f de classe C², de retrouver une équation différentielle. Faire varier la fréquence et une perturbation, puis comparer le résidu fonctionnel au résidu différentiel.',
        [select('family', 'Famille de solutions', [('cos', 'cos(kx)'), ('cosh', 'cosh(kx)'), ('zero', 'Fonction identiquement nulle')], 'cos'), slider('k', 'Fréquence ou taux k', 0, 1.2, .05, 1), slider('b', 'Perturbation b x²', -.2, .2, .01, 0)],
        [preset('Oscillation exacte', family='cos', k=1, b=0), preset('Croissance hyperbolique', family='cosh', k=.7, b=0), preset('La solution nulle, à traiter séparément', family='zero', k=0, b=0), preset('Une équation différentielle ne remplace pas la condition f(0)', family='cos', k=1, b=.1)]),
    lab('identification_symetrie', 'Substituer −x : identifier une fonction sans la deviner', 'Équations fonctionnelles',
        'Résoudre f(x)+f(−x)/x=x pour x≠0. Écrire aussi l’égalité au point −x produit un système de deux équations pour f(x) et f(−x). La solution se décompose en partie paire et partie impaire ; sa vérification se fait dans l’équation initiale. Le point 0 est exclu de cette équation, mais la solution obtenue admet un prolongement continu.',
        [slider('b', 'Défaut ajouté : b sin x', -1, 1, .05, 0), slider('radius', 'Étendue du domaine visible |x|≤R', 1, 5, .25, 3)],
        [preset('Identification exacte', b=0, radius=3), preset('Une perturbation même petite échoue', b=.1, radius=3), preset('Comparer les comportements à grande distance', b=0, radius=5)]),
    lab('continuite_gauss', 'Théorème 1 : continuité d’une transformée gaussienne', 'Intégrales à paramètre · p. 63',
        'Étudier F(a)=∫ℝ e⁻ᵗ² cos(at)dt. Pour chaque t, l’intégrande dépend continûment de a ; sa valeur absolue est dominée par e⁻ᵗ², une fonction intégrable indépendante de a. Le théorème de continuité s’applique sur tout ℝ. Comparer le calcul sur [−L,L] à √π e⁻ᵃ²/⁴ et vérifier que le majorant reste valable même lorsque l’intégrande change de signe.',
        [slider('a', 'Paramètre a', -6, 6, .1, 2), slider('L', 'Borne de troncature L', 2, 6, .25, 4)],
        [preset('Intégrale gaussienne a=0', a=0, L=4), preset('Oscillations et compensation', a=5, L=4), preset('Une troncature plus courte', a=2, L=2)]),
    lab('continuite_defaut', 'Théorème 1 : une masse qui se concentre interdit le passage à la limite', 'Intégrales à paramètre · p. 63',
        'Pour a>0 et t>0, prendre fₐ(t)=e⁻ᵗ/ᵃ/a ; poser f₀(t)=0. À chaque t>0, fₐ(t) tend vers 0 lorsque a tend vers 0, mais ∫₀∞fₐ(t)dt=1. Toute la masse se concentre près de 0. Un changement de variable t=au évite de perdre numériquement le pic. Identifier précisément l’hypothèse de domination qui manque au voisinage de a=0.',
        [slider('a', 'Largeur a de la concentration', .01, 1, .01, .1), slider('epsilon', 'Intervalle observé [0,ε]', .01, .5, .01, .2), slider('L', 'Borne visible L', 1, 8, .25, 2)],
        [preset('Concentration modérée', a=.4, epsilon=.2, L=2), preset('Presque toute la masse près de 0', a=.02, epsilon=.2, L=2), preset('Réduire aussi la fenêtre observée', a=.02, epsilon=.02, L=1)]),
    lab('leibniz_frullani', 'Théorème 2 : Frullani, un logarithme retrouvé par dérivation', 'Intégrales à paramètre · p. 63',
        'Calculer F(a,b)=∫₀∞(e⁻ᵃᵗ−e⁻ᵇᵗ)/t dt, avec a,b>0. La compensation enlève la singularité en 0. À b fixé, ∂f/∂a=−e⁻ᵃᵗ ; sur un voisinage a≥a₀>0, e⁻ᵃ⁰ᵗ est un majorant intégrable. Le théorème de Leibniz donne ∂F/∂a=−1/a et la condition F(b,b)=0 fixe la constante.',
        [slider('a', 'Paramètre a>0', .25, 4, .05, 1), slider('b', 'Paramètre b>0 fixé pour la dérivation', .25, 4, .05, 2), slider('L', 'Borne de troncature L', 4, 32, 1, 16)],
        [preset('Retrouver ln 2', a=1, b=2, L=16), preset('Intégrale nulle, dérivée non nulle', a=2, b=2, L=16), preset('Décroissance lente : vérifier la queue', a=.25, b=1, L=8)]),
    lab('leibniz_arctan', 'Théorème 2 : transformer une intégrale oscillante en arctangente', 'Intégrales à paramètre · p. 63',
        'Calculer F(a)=∫₀∞e⁻ᵃᵗ sin(t)/t dt pour a>0. Dériver enlève le facteur 1/t : F′(a)=−∫₀∞e⁻ᵃᵗ sin t dt=−1/(1+a²). Justifier la dérivation sur chaque voisinage restant dans ]0,+∞[, puis fixer la constante avec la limite en +∞. Les queues d’intégrale et les intégrandes oscillantes sont affichées séparément.',
        [slider('a', 'Amortissement a>0', .2, 3, .05, .8), slider('L', 'Borne de troncature L', 6, 48, 2, 24)],
        [preset('Compensation bien amortie', a=1, L=24), preset('Faible amortissement : augmenter L', a=.2, L=12), preset('Même a, queue réduite', a=.2, L=48)]),
    lab('derivees_gamma', 'Théorème 3 : dérivées de Γ, moments logarithmiques et convexité', 'Intégrales à paramètre · p. 63',
        'Pour a>0, dériver Γ(a)=∫₀∞tᵃ⁻¹e⁻ᵗdt plusieurs fois fait apparaître les puissances de ln t. Vérifier une domination locale pour tous les ordres jusqu’à n, à la fois près de 0 et à l’infini. Le changement de variable u=ln t rend visibles les deux queues. La densité tᵃ⁻¹e⁻ᵗ/Γ(a) relie ensuite (ln Γ)″ à une variance, donc à la convexité de ln Γ.',
        [slider('a', 'Paramètre a>0', .6, 5, .1, 2.3), slider('n', 'Ordre de dérivation n', 1, 5, 1, 3, integer=True), slider('q', 'Coupure basse ε=10⁻ᑫ', 3, 8, 1, 6, integer=True), slider('T', 'Coupure haute T', 12, 50, 2, 26)],
        [preset('Moments autour de Γ(2)', a=2, n=2, q=6, T=26), preset('Singularité intégrable près de 0', a=.6, n=3, q=8, T=30), preset('Dérivée cinquième', a=3.5, n=5, q=6, T=40)]),
    lab('derivees_laplace', 'Théorème 3 : dérivées de Laplace et monotonie complète', 'Intégrales à paramètre · p. 63',
        'Partir de F(a)=∫₀∞e⁻ᵃᵗdt=1/a. Le théorème de dérivation d’ordre n donne F⁽ⁿ⁾(a)=∫₀∞(−t)ⁿe⁻ᵃᵗdt=(−1)ⁿn!/aⁿ⁺¹. Un seul majorant local permet de contrôler tous les ordres jusqu’à n. Observer le déplacement du maximum de tⁿe⁻ᵃᵗ vers n/a et mesurer la masse perdue lorsque la troncature est trop courte.',
        [slider('a', 'Paramètre de Laplace a>0', .25, 3, .05, 1), slider('n', 'Ordre n', 1, 8, 1, 4, integer=True), slider('L', 'Borne de troncature L', 4, 48, 2, 24)],
        [preset('Quatrième dérivée : 24/a⁵', a=1, n=4, L=24), preset('Le maximum sort de la fenêtre', a=.25, n=8, L=12), preset('Capturer davantage de masse', a=.25, n=8, L=48)])
]
