"""Équations différentielles : dix expériences de Sup, Spé et prolongements."""
from commun import slider, select, preset, lab

CAT = 'C · Équations différentielles'
LABS = [
    lab('euler_rk4', 'Euler et RK4 : mesurer un ordre de convergence', CAT,
        'Retrouver la fonction du TP p. 69, y′ = cos(x)(y + 1), puis comparer deux méthodes numériques à sa solution exacte. Diviser le pas par deux : une petite erreur devient une mesure de l’ordre de la méthode.',
        [slider('T','Abscisse finale T',1,12,.5,6),slider('N','Nombre de pas N',20,400,10,80,integer=True),slider('y0','Valeur initiale y(0)',-.5,1,.1,0)],
        [preset('TP : près d’une période',T=6,N=80,y0=0),preset('Pas grossier',T=12,N=20,y0=0),preset('Même EDO, autre condition initiale',T=6,N=100,y0=1)]),
    lab('facteur_integrant', 'Facteur intégrant : transformer une EDO en intégrale', CAT,
        'Résoudre y′ + (a + bx)y = F cos(ωx). Suivre le facteur intégrant et comparer la variation des constantes à une intégration RK4 indépendante. Deux solutions soumises au même forçage se rapprochent-elles ?',
        [slider('a','Coefficient constant a',0,2,.1,1),slider('b','Variation du coefficient b',0,1,.1,.3),slider('F','Amplitude du second membre F',0,2,.1,1),slider('omega','Pulsation ω',.5,3,.1,1.5),slider('y0','Valeur y(0)',-1,2,.1,.5),slider('T','Abscisse finale',1,6,.5,4)],
        [preset('Relaxation à coefficient constant',a=1,b=0,F=1,omega=1),preset('Coefficient variable',a=.2,b=1,F=1,omega=2),preset('Homogène sans amortissement',a=0,b=0,F=0,y0=1)]),
    lab('cauchy_lipschitz', 'Une condition initiale ne suffit pas toujours', CAT,
        'Comparer y′ = λy à y′ = 2√max(y,0), avec y(0)=0. Dans le second cas, une solution peut rester nulle puis démarrer à un instant choisi. Identifier précisément l’hypothèse qui garantit l’unicité.',
        [slider('delay','Instant de départ τ d’une solution en attente',0,3,.25,1),slider('lam','Coefficient λ de l’EDO linéaire',-2,1,.1,-1),slider('epsilon','Petit déplacement initial ε',.001,.1,.001,.01),slider('T','Durée observée',3,5,.5,4)],
        [preset('Départs différents, même donnée initiale',delay=1,lam=-1),preset('Départ immédiat',delay=0),preset('Sensibilité linéaire croissante',lam=1,epsilon=.01,T=5)]),
    lab('explosion_logistique', 'Solution maximale : explosion ou saturation', CAT,
        'Comparer une croissance quadratique y′=ay², qui explose en temps fini, à la loi logistique z′=rz(1−z/K). L’existence et l’unicité locales ne garantissent pas une solution définie pour tout temps.',
        [slider('a','Coefficient de croissance quadratique a',.2,2,.1,1),slider('y0','Valeur initiale commune',.1,2,.1,.5),slider('r','Taux logistique r',.2,2,.1,1),slider('K','Niveau d’équilibre K',.5,4,.1,2),slider('fraction','Fraction du temps d’explosion observée',.3,.95,.05,.8)],
        [preset('Comparer les deux modèles',a=1,y0=.5,r=1,K=2,fraction=.8),preset('Près de l’explosion',fraction=.95),preset('Logistique : partir au-dessus de K',y0=2,K=.8,fraction=.8)]),
    lab('oscillateur_resonance', 'Oscillateur : transitoire, résonance et travail', CAT,
        'Étudier y″+2ζω₀y′+ω₀²y=Fcos(ωt), avec des conditions initiales explicites. Relier les racines caractéristiques, la réponse forcée et le bilan énergétique. À amortissement nul et à résonance, aucune amplitude stationnaire finie n’existe.',
        [slider('omega0','Pulsation propre ω₀',.5,2,.1,1),slider('zeta','Amortissement réduit ζ',0,1.5,.05,.1),slider('ratio','Rapport ω/ω₀',.2,2,.05,1),slider('F','Amplitude du forçage F',0,2,.1,1),slider('y0','Position initiale',-.5,1,.1,0),slider('v0','Vitesse initiale',-.5,1,.1,0),slider('cycles','Nombre de périodes propres',2,10,1,5,integer=True)],
        [preset('Résonance amortie',zeta=.1,ratio=1,F=1),preset('Résonance sans amortissement',zeta=0,ratio=1,F=1,y0=0,v0=0),preset('Régime apériodique libre',zeta=1.2,F=0,y0=1,v0=0),preset('Amortissement critique',zeta=1,F=0,y0=1,v0=0)]),
    lab('variation_constantes', 'Variation des constantes : un noyau de Green initial', CAT,
        'Résoudre l’exercice 1 p. 71, y″−5y′+6y=eˣ/cosh²x. Construire le Wronskien, les coefficients variables et le noyau qui transforme le second membre en solution. Vérifier les conditions initiales et comparer à RK4.',
        [slider('amplitude','Multiplicateur du second membre',0,2,.1,1),slider('y0','Valeur y(0)',-.5,1,.1,0),slider('v0','Valeur y′(0)',-.5,3,.1,0),slider('T','Abscisse finale',.5,3,.25,2)],
        [preset('Particulière à données initiales nulles',amplitude=1,y0=0,v0=0),preset('Ajouter une solution homogène',y0=1,v0=2),preset('Équation homogène seule',amplitude=0,y0=1,v0=3)]),
    lab('euler_cauchy', 'Euler–Cauchy : singularités et série entière', CAT,
        'Résoudre l’exercice 2 p. 71, x²y″+xy′−y=x²/(1−x²). Séparer les intervalles de résolution ; distinguer le mode x, le mode 1/x et la solution particulière prolongeable en 0. Comparer cette dernière à sa série entière.',
        [select('domain','Intervalle étudié',[('regular','Branche régulière incluant 0'),('singular','Entre 0 et 1, mode 1/x permis'),('outside','À droite de la singularité x=1')],'regular'),slider('gap','Distance aux abscisses singulières',.03,.3,.01,.1),slider('C1','Coefficient du mode x',-1,1,.1,.5),slider('C2','Coefficient de 1/x, sauf branche régulière',-1,1,.1,.2),slider('terms','Nombre de termes de la série particulière',3,30,1,10,integer=True)],
        [preset('Prolongement régulier en 0',domain='regular',C1=.5,C2=0,terms=10),preset('Le mode singulier 1/x',domain='singular',C1=0,C2=.2),preset('Après x=1',domain='outside',C1=0,C2=0),preset('Près du rayon de convergence',domain='regular',gap=.03,terms=30)]),
    lab('riccati', 'EDO homogène et Riccati : deux changements de fonction', CAT,
        'Résoudre xy′=y+√(x²+y²), puis raccorder les branches de part et d’autre de 0. En parallèle, transformer la véritable équation de Riccati z′=z²−1 en une équation linéaire d’ordre 2. Nommer et justifier chaque changement de variable.',
        [slider('c','Paramètre positif c de la famille y',.1,2,.1,.5),slider('extent','Étendue de l’axe x',1,4,.5,2),slider('z0','Valeur z(0) pour l’équation de Riccati',-1.5,1.5,.1,.2),slider('T','Durée demandée pour Riccati',1,4,.5,3)],
        [preset('Raccordement à travers 0',c=.5,z0=.2),preset('Riccati : équilibre stable',z0=-1),preset('Riccati : explosion à droite',z0=1.5,T=3),preset('Riccati : équilibre instable',z0=1)]),
    lab('lineaire_systeme', 'Trois réservoirs : conservation, modes et exponentielle', CAT,
        'Faire circuler une quantité entre trois réservoirs de même volume. Passer de trois bilans à Y′=AY, diagonaliser une matrice symétrique et reconstruire l’évolution. Les modes expliquent la conservation et la relaxation vers une répartition uniforme.',
        [slider('k12','Taux d’échange entre 1 et 2',.1,2,.1,1),slider('k23','Taux d’échange entre 2 et 3',.1,2,.1,.5),slider('k13','Taux d’échange entre 1 et 3',.1,2,.1,.2),slider('decay','Taux de perte identique δ',0,.5,.05,0),select('initial','Réservoir contenant toute la quantité initiale',[('1','Réservoir 1'),('2','Réservoir 2'),('3','Réservoir 3')],'1'),slider('T','Temps final',1,10,.5,5)],
        [preset('Quantité totale conservée',decay=0,k12=1,k23=.5,k13=.2),preset('Échanges symétriques',k12=1,k23=1,k13=1,decay=0),preset('Avec perte uniforme',decay=.2,T=10),preset('Un échange lent',k12=.1,k23=2,k13=.1)]),
    lab('green_bords', 'Deux bords : existence, unicité et résonance', CAT,
        'Comparer un problème de Cauchy et y″+λy=f sur [0,π], avec y(0)=y(π)=0. Certaines valeurs de λ rendent les deux conditions dépendantes : vérifier la compatibilité du second membre avant de parler de solution.',
        [slider('lam','Paramètre λ',0,12,.25,2),slider('a','Composante a sin x du second membre',-1,1,.1,1),slider('b','Composante b sin(2x) du second membre',-1,1,.1,.5),slider('free','Amplitude libre du mode résonant, si compatible',-1,1,.1,.5)],
        [preset('Solution unique',lam=2,a=1,b=.5),preset('Résonance incompatible',lam=1,a=1,b=0),preset('Résonance compatible, infinité de solutions',lam=1,a=0,b=1,free=.5),preset('Troisième mode libre',lam=9,a=1,b=.5,free=.5)]),
]
