"""Cours et exercices d'EDO ; priorité aux méthodes et aux applications."""

def lesson(title,level,lab,html):
    return dict(title=title,level=level,lab=lab,html=html)

def exercise(title,level,lab,question,answer):
    return dict(title=title,level=level,lab=lab,question=question,answer=answer)

LESSONS = [
lesson('Du champ de pentes à la solution exacte du TP', 'Sup', 'euler_rk4', '''
<p>Une EDO y′=f(x,y) ne donne pas directement les valeurs de y : elle indique la <strong>pente</strong> d’une courbe lorsqu’elle passe par (x,y). La condition y(0)=y₀ choisit une trajectoire. Le champ de petites directions du laboratoire représente (1,f(x,y)), ramené à une longueur lisible ; cette normalisation ne change pas la pente.</p>
<p>Dans le TP p. 69, f(x,y)=cos(x)(y+1). Poser z=y+1 transforme l’équation en z′=cos(x)z. Multiplier par e<sup>−sin x</sup> donne (ze<sup>−sin x</sup>)′=0. Par conséquent <strong>y(x)=(y₀+1)e<sup>sin x</sup>−1</strong>, sur ℝ. Cette démonstration inclut le cas y₀=−1 sans diviser par y+1.</p>
<p>Pour y₀=0, y′ a le signe de cos x ; les maxima sont atteints en π/2+2kπ, avec valeur e−1, et les minima en 3π/2+2kπ, avec valeur e<sup>−1</sup>−1. Une formule exacte fournit ici un étalon pour l’expérience numérique.</p>
<p><strong>Technique attendue :</strong> changement de fonction, équation linéaire du premier ordre, condition initiale puis tableau de variations. Le dessin aide à interpréter ; la vérification par dérivation démontre.</p>'''),
lesson('Euler, RK4 et les deux erreurs à distinguer', 'Sup → Spé', 'euler_rk4', '''
<p>Sur xⱼ=jh, Euler explicite pose yⱼ₊₁=yⱼ+h f(xⱼ,yⱼ). Son erreur sur <em>un</em> pas, en partant d’une valeur exacte, est O(h²) ; les erreurs propagées sur un intervalle fixé donnent généralement une erreur globale O(h). Ces deux ordres répondent à deux questions différentes.</p>
<p>RK4 calcule k₁=f(x,y), k₂=f(x+h/2,y+hk₁/2), k₃=f(x+h/2,y+hk₂/2), k₄=f(x+h,y+hk₃), puis y<sub>suiv</sub>=y+h(k₁+2k₂+2k₃+k₄)/6. Pour une fonction suffisamment régulière et un intervalle fixé, son erreur globale est O(h⁴).</p>
<p>Le laboratoire mesure E(h)=maxⱼ|yⱼ−y(xⱼ)| et l’ordre p≈log₂[E(h)/E(h/2)]. Une droite de pente p apparaît dans des coordonnées logarithmiques lorsque le maillage est assez fin. Un pas grossier, un intervalle trop long ou les arrondis peuvent masquer ce comportement.</p>
<p><strong>Application :</strong> choisir une précision avant de résoudre un problème sans solution exacte. Il faut alors comparer des maillages successifs, surveiller un bilan ou une quantité conservée et ne pas confondre le lissage du graphique avec la précision.</p>'''),
lesson('Le facteur intégrant : le signe se retrouve par dérivation', 'Sup', 'facteur_integrant', '''
<p>On étudie y′+a(x)y=c(x), avec a,c continues sur un intervalle I. Prendre une primitive A de a, puis calculer <strong>(eᴬy)′=eᴬ(y′+ay)=eᴬc</strong>. L’intégration entre x₀ et x donne y(x)=e<sup>−A(x)</sup>[e<sup>A(x₀)</sup>y₀+∫<sub>x₀</sub><sup>x</sup>e<sup>A(s)</sup>c(s)ds]. Le facteur devant la parenthèse est e<sup>−A</sup>.</p>
<p>Dans l’atelier a(x)=a+bx et c(x)=Fcos(ωx), donc A(x)=ax+bx²/2 et x₀=0. On peut aussi écrire l’intégrale avec le noyau e<sup>−(A(x)−A(s))</sup>. Pour 0≤s≤x et a,b≥0 ce noyau est au plus 1 ; cette forme évite de produire séparément des exponentielles très grandes.</p>
<p>Les constantes d’intégration ne sont pas une décoration : le premier terme y₀e<sup>−A(x)</sup> impose la donnée initiale. La vérification consiste à dériver la formule et à l’évaluer en 0.</p>
<p><strong>Applications CPGE :</strong> circuit RC soumis à une tension variable, bilan thermique avec coefficient d’échange variable ou relaxation chimique linéarisée. Chaque application demande de préciser les unités et le domaine de validité.</p>'''),
lesson('Sensibilité, mémoire et variation des constantes', 'Spé', 'facteur_integrant', '''
<p>Deux solutions du même second membre, séparées initialement de d₀, ont pour différence d(x)=d₀e<sup>−(A(x)−A(x₀))</sup>. Ce résultat permet de mesurer la sensibilité à la préparation initiale sans résoudre deux problèmes complets.</p>
<p>Lorsque a(x)≥0 à droite de x₀, l’écart ne croît pas. Cela ne veut pas dire que chaque solution décroît : le forçage c peut faire osciller y. Il faut distinguer <strong>évolution de la solution</strong> et <strong>évolution de la différence de deux solutions</strong>.</p>
<p>Le noyau e<sup>−∫ₛˣa(u)du</sup> pondère les contributions passées. Pour a constant positif, une contribution ancienne décroît exponentiellement ; pour a+bx, la mémoire dépend des deux instants. La linéarité permet de sommer ces contributions, même si le forçage n’est pas sinusoïdal.</p>
<p>La quadrature de Gauss du laboratoire évalue cette intégrale. Un RK4 indépendant intègre l’EDO elle-même : leur accord fournit un contrôle numérique. Il ne prouve pas qu’un modèle thermique ou électrique serait pertinent sans ses hypothèses physiques.</p>'''),
lesson('Unicité : la démontrer ou construire un contre-exemple', 'Spé → Au-delà', 'cauchy_lipschitz', '''
<p>Pour une EDO linéaire à coefficients continus, une donnée initiale détermine une solution unique sur l’intervalle de continuité. Le théorème de Cauchy–Lipschitz prolonge cette propriété à certaines EDO non linéaires : f doit être continue et <strong>localement lipschitzienne par rapport à y</strong>. Ce théorème général est présenté comme un prolongement, sans remplacer les démonstrations linéaires accessibles en CPGE.</p>
<p>La continuité seule ne suffit pas. Avec f(y)=2√max(y,0), les fonctions yτ(t)=0 pour t≤τ et yτ(t)=(t−τ)² pour t≥τ, τ≥0, sont C¹. À l’instant τ, les valeurs valent 0 et les dérivées valent 0 des deux côtés. Elles vérifient toutes y′=f(y) et y(0)=0.</p>
<p>Le quotient |f(ε)−f(0)|/ε=2/√ε tend vers +∞. Aucune constante locale ne borne donc ce quotient près de 0 : l’hypothèse de Lipschitz manque exactement au point de départ.</p>'''),
lesson('Existence, unicité et stabilité sont trois propriétés distinctes', 'Spé → Au-delà', 'cauchy_lipschitz', '''
<p>Pour y′=λy, la solution de donnée ε est εe<sup>λt</sup>. Deux trajectoires peuvent rester proches, ou s’éloigner rapidement si λ&gt;0, tout en étant chacune parfaitement unique. L’unicité interdit deux trajectoires pour <em>la même</em> donnée ; la stabilité compare des données voisines.</p>
<p>Le cas y′=2√max(y,0) montre aussi une limite du calcul numérique. Euler ou RK4, partant exactement de y=0, obtiennent y=0 à chaque pas. Cela ne démontre pas l’unicité : ces méthodes sélectionnent une solution parmi plusieurs. L’existence d’autres solutions exige une construction ou un raisonnement.</p>
<p>Enfin, l’échec d’une hypothèse suffisante ne prouve pas à lui seul l’échec de la conclusion. Pour établir la non-unicité, le laboratoire donne trois solutions et les vérifie ; constater seulement que f n’est pas lipschitzienne serait insuffisant.</p>
<p><strong>Réflexe formateur :</strong> nommer la propriété étudiée, écrire ses quantificateurs, puis fournir la preuve adaptée — différence de solutions, formule explicite ou contre-exemple.</p>'''),
lesson('Une solution maximale peut exploser en temps fini', 'Spé → Au-delà', 'explosion_logistique', '''
<p>Pour y′=ay² avec a&gt;0 et y(0)=y₀&gt;0, on obtient (1/y)′=−a et <strong>y(t)=y₀/(1−ay₀t)</strong>. Le premier pôle à droite est t*=1/(ay₀). La solution contenant 0 est définie sur ]−∞,t*[ ; elle ne peut être prolongée à t* comme fonction réelle continue.</p>
<p>Le second membre ay² est dérivable en y, donc localement lipschitzien. L’explosion est compatible avec l’existence et l’unicité <em>locales</em>. Pour une existence globale, il faut d’autres contrôles, par exemple empêcher y de quitter tout domaine borné en temps fini.</p>
<p>L’expression algébrique existe aussi pour t&gt;t*, mais cette branche n’est pas un prolongement de la solution initiale à travers le pôle. Une courbe ne doit pas relier les deux côtés de l’asymptote.</p>
<p>Le mot « maximale » porte sur le domaine de définition par prolongement. Il ne signifie pas que la fonction atteint un maximum, ni qu’elle domine toutes les autres solutions.</p>'''),
lesson('Logistique : équilibres, monotonie et linéarisation', 'Sup → Spé', 'explosion_logistique', '''
<p>La loi z′=rz(1−z/K), r,K&gt;0, possède deux équilibres : 0 et K. Pour 0&lt;z&lt;K, z′&gt;0 ; pour z&gt;K, z′&lt;0. Une donnée positive conduit à z(t)=K/[1+(K/z₀−1)e<sup>−rt</sup>] et z(t)→K lorsque t→+∞.</p>
<p>Près de K, poser z=K+η. On trouve η′=−rη−(r/K)η². Au premier ordre, η≈η₀e<sup>−rt</sup> : le taux de retour vaut r. Près de 0, z′≈rz : les petites perturbations positives croissent ; 0 est instable à droite.</p>
<p>Cette étude rassemble plusieurs techniques : recherche des zéros du second membre, tableau de signes, séparation des variables, limites et développement limité autour d’un équilibre. La formule explicite confirme le raisonnement qualitatif.</p>
<p>Comparer à y′=ay² montre ce que change le terme de saturation. La logistique évite l’explosion pour les données positives à droite ; elle ne transforme pas tout modèle non linéaire en modèle global. Les paramètres et le sens physique du freinage doivent être justifiés.</p>'''),
lesson('Équation caractéristique : trois régimes, deux données', 'Sup', 'oscillateur_resonance', '''
<p>L’équation libre y″+2ζω₀y′+ω₀²y=0 conduit à r²+2ζω₀r+ω₀²=0. Pour 0≤ζ&lt;1, les racines sont −ζω₀±iω₀√(1−ζ²) et le mouvement combine sinus et cosinus amortis. Pour ζ=1, y=(A+Bt)e<sup>−ω₀t</sup>. Pour ζ&gt;1, il existe deux exponentielles réelles décroissantes.</p>
<p>Une donnée y(0) fixe seulement une combinaison des deux constantes. Il faut aussi y′(0) pour déterminer le mouvement : c’est un <strong>problème de Cauchy d’ordre 2</strong>. Les deux conditions sont prises au même instant.</p>
<p>Un amortissement critique ne donne pas un sinus de fréquence nulle : c’est la racine double qui impose le facteur t. Le laboratoire change de formule au seuil, au lieu de diviser par une pulsation devenue nulle.</p>
<p>Le portrait (y,y′) visualise la position et la vitesse. En mouvement libre, son champ est autonome ; sous forçage il dépend aussi du temps. Le champ affiché est alors explicitement figé à t=0 tandis que la trajectoire tient compte de tout le forçage.</p>'''),
lesson('Résonance : régime établi, croissance et bilan', 'Sup → Spé', 'oscillateur_resonance', '''
<p>Pour le forçage Fcos(ωt), une particulière hors résonance non amortie s’obtient en écriture complexe : U=F/(ω₀²−ω²+2iζω₀ω). L’amplitude établie est |U|. La partie homogène ajuste les données initiales et constitue le transitoire.</p>
<p>Si ζ&gt;0, maximiser |U| donne ω<sub>res</sub>=ω₀√(1−2ζ²), lorsqu’il existe un maximum à pulsation positive, donc pour ζ&lt;1/√2. Résonance en déplacement et pulsation propre ne sont pas exactement identiques.</p>
<p>Si ζ=0 et ω=ω₀, le dénominateur s’annule. Une particulière est <strong>Ft sin(ω₀t)/(2ω₀)</strong> : son enveloppe croît avec t. Il n’existe pas d’amplitude stationnaire finie. Le laboratoire compare alors des maxima sur un horizon fixé.</p>
<p>Avec E=[(y′)²+ω₀²y²]/2, l’équation multipliée par y′ donne E′=Fcos(ωt)y′−2ζω₀(y′)². Intégrer donne E−E₀=W−D. C’est un contrôle portant sur la trajectoire entière, plus instructif qu’un seul accord à l’instant final.</p>'''),
lesson('Variation des constantes et Wronskien', 'Spé', 'variation_constantes', '''
<p>Pour y″−5y′+6y=g(x), les solutions homogènes y₁=e<sup>2x</sup>, y₂=e<sup>3x</sup> ont W=y₁y₂′−y₁′y₂=e<sup>5x</sup>≠0. Elles constituent donc une base de l’espace des solutions homogènes.</p>
<p>Écrire y_p=a(x)y₁+b(x)y₂ puis imposer a′y₁+b′y₂=0 simplifie la dérivation. L’équation donne a′y₁′+b′y₂′=g. Par Cramer : <strong>a′=−gy₂/W, b′=gy₁/W</strong>.</p>
<p>Pour l’exercice 1 p. 71, g=eˣ/cosh²x : a′=−e<sup>−x</sup>/cosh²x et b′=e<sup>−2x</sup>/cosh²x. Des intégrales définies de 0 à x évitent de perdre une constante ; elles produisent une particulière de données initiales nulles.</p>
<p>Une particulière ne fournit pas encore la solution du problème de Cauchy. Ajouter Ae<sup>2x</sup>+Be<sup>3x</sup> puis résoudre A+B=y₀ et 2A+3B=v₀ donne A=3y₀−v₀ et B=v₀−2y₀.</p>'''),
lesson('Du Wronskien à la réponse impulsionnelle initiale', 'Spé → Au-delà', 'variation_constantes', '''
<p>En réunissant les deux intégrales de coefficients, on obtient y_p(x)=∫₀ˣK(x−s)g(s)ds, avec <strong>K(u)=e<sup>3u</sup>−e<sup>2u</sup></strong>. Le noyau satisfait K(0)=0, K′(0)=1 et K″−5K′+6K=0.</p>
<p>Dériver sous l’intégrale donne y_p′=∫₀ˣK′(x−s)g(s)ds puis y_p″=g(x)+∫₀ˣK″(x−s)g(s)ds. Le terme g(x) vient de K′(0)=1. Par conséquent y_p″−5y_p′+6y_p=g et y_p(0)=y_p′(0)=0.</p>
<p>Le noyau exprime la superposition de réponses à des sollicitations élémentaires. Cette construction est un pont entre variation des constantes, convolution et transformée de Laplace.</p>
<p>Les deux modes homogènes sont croissants. Une petite erreur de donnée initiale peut être amplifiée, même si la formule et l’algorithme sont corrects. Le graphique d’écart Gauss/RK4 distingue cette sensibilité du problème et la précision des deux calculs.</p>'''),
lesson('Euler–Cauchy : la forme normale et ses limites', 'Spé', 'euler_cauchy', '''
<p>L’équation x²y″+xy′−y=x²/(1−x²) présente trois abscisses particulières : ±1 rendent le second membre singulier ; 0 annule le coefficient dominant. Sur un intervalle évitant ces points, on peut diviser par x² et appliquer les résultats linéaires usuels.</p>
<p>Pour l’homogène, chercher y=xᵐ donne m(m−1)+m−1=m²−1. Les deux solutions sont x et 1/x, indépendantes sur tout intervalle évitant 0. Le changement x=eᵗ, x&gt;0, transforme aussi x²y″+xy′ en la dérivée seconde de Y(t)=y(eᵗ).</p>
<p>Une solution particulière est y_p=[(x²−1)ln|(1+x)/(1−x)|+2x]/(4x). Le laboratoire la vérifie par ses dérivées et par le résidu de l’équation. Une formule contenant ln|…| peut être valable sur plusieurs intervalles ; les constantes de résolution sont choisies séparément sur chacun.</p>
<p>Dans un prolongement régulier à travers 0, le coefficient de 1/x doit disparaître. Il reste le mode C₁x et une particulière régulière. Le coefficient annulé exige une étude directe ; une division par x² aurait supprimé précisément le point à examiner.</p>'''),
lesson('Série entière : résoudre et régulariser un calcul', 'Spé', 'euler_cauchy', '''
<p>Pour |x|&lt;1, x²/(1−x²)=∑ₙ≥₁x<sup>2n</sup>. Sur un monôme xᵐ, l’opérateur L[y]=x²y″+xy′−y agit par multiplication par m²−1. On cherche donc y_p=∑ₙ≥₁x<sup>2n</sup>/(4n²−1).</p>
<p>Le coefficient du mode x reste libre car L[x]=0. Les termes impairs de rang au moins 3 sont nuls. La particulière commence par x²/3+x⁴/15+x⁶/35 ; ainsi y_p(0)=y_p′(0)=0 et y_p″(0)=2/3.</p>
<p>La série a rayon 1 : le rapport des coefficients tend vers 1 lorsqu’on la considère comme série en x². Une somme de N termes approche bien la fonction près de 0 mais plus lentement près de |x|=1.</p>
<p>Cette série sert aussi au calcul numérique. Dans la formule logarithmique, deux termes presque égaux se soustraient au voisinage de 0. La série évite cette perte de précision. Elle ne doit en revanche pas être utilisée pour |x|&gt;1, où elle diverge.</p>'''),
lesson('Une EDO homogène et un raccordement à vérifier', 'Spé', 'riccati', '''
<p>L’exercice 3 p. 71 est xy′=y+√(x²+y²). Hors de 0, poser z=y/x. Pour x&gt;0, xz′=√(1+z²), d’où argsh z=ln x+A. Pour x&lt;0, la racine contient |x| ; ce signe modifie l’équation transformée.</p>
<p>Les branches compatibles avec un raccordement continu en 0 donnent la famille <strong>y=cx²−1/(4c), c&gt;0</strong>. Elle est en fait dérivable sur ℝ. Pour la vérifier, noter x²+y²=(cx²+1/(4c))². Comme c&gt;0, la racine vaut cx²+1/(4c), et xy′=2cx²=y+√(x²+y²).</p>
<p>À x=0, l’équation impose y(0)+|y(0)|=0, donc y(0)≤0. La famille obtenue a y(0)&lt;0 et y′(0)=0. Une condition imposée au point singulier doit être vérifiée directement.</p>
<p>L’équation est dite homogène après division et substitution y/x ; elle n’a pas la forme quadratique caractéristique d’une équation de Riccati. Le laboratoire présente séparément les deux méthodes.</p>'''),
lesson('Riccati : une non-linéarité quadratique se linéarise', 'Spé → Au-delà', 'riccati', '''
<p>Une équation de Riccati a la forme z′=a(t)z²+b(t)z+c(t). Dans l’exemple z′=z²−1, poser <strong>z=−u′/u</strong> sur un intervalle où u≠0. Alors z′=z²−u″/u, et l’équation linéaire u″=u convient.</p>
<p>Pour imposer z(0)=z₀, choisir u(0)=1 et u′(0)=−z₀. On obtient u=cosh t−z₀sinh t et z=(z₀cosh t−sinh t)/(cosh t−z₀sinh t). Le changement n’est valable que tant que le dénominateur reste non nul.</p>
<p>Les équilibres z=−1 et z=1 sont visibles dans z′=(z−1)(z+1). −1 est attractif, 1 est répulsif. Si z₀&gt;1, u s’annule en t*=argth(1/z₀) et z explose à droite. L’EDO linéaire u″=u reste régulière : c’est le quotient qui devient singulier.</p>
<p><strong>Technique de prolongement :</strong> reconnaître une structure, calculer la dérivée du changement et surveiller son domaine. Linéariser un problème n’autorise pas à oublier les divisions introduites.</p>'''),
lesson('Trois bilans deviennent une équation matricielle', 'Spé', 'lineaire_systeme', '''
<p>Yᵢ(t) est la quantité présente dans le réservoir i. Les échanges symétriques de taux kᵢⱼ donnent Y₁′=k₁₂(Y₂−Y₁)+k₁₃(Y₃−Y₁)−δY₁, et deux équations analogues. Sous forme matricielle : <strong>Y′=AY</strong>.</p>
<p>La matrice A est symétrique ; les termes hors diagonale sont les taux positifs, et la diagonale est l’opposé de la somme des taux sortants, moins δ. Sommer les trois bilans annule tous les échanges : S′=−δS. Pour S(0)=1, S=e<sup>−δt</sup>.</p>
<p>Diagonaliser A=QDQᵀ transforme le système en Z′=DZ, avec Z=QᵀY. Chaque coordonnée propre satisfait Zⱼ′=λⱼZⱼ, donc Zⱼ=Zⱼ(0)e<sup>λⱼt</sup>. Revenir à Y donne l’exponentielle matricielle e<sup>tA</sup>=Q diag(e<sup>λⱼt</sup>)Qᵀ.</p>
<p>Ce système à trois dimensions relie réellement algèbre linéaire et analyse. Les valeurs propres ne sont pas seulement calculées : elles donnent les temps de relaxation et les grandeurs conservées.</p>'''),
lesson('Mode conservé et deux modes de relaxation', 'Spé → Au-delà', 'lineaire_systeme', '''
<p>Sans perte, A(1,1,1)ᵀ=0. Le mode uniforme est constant. Pour tout vecteur v, −vᵀAv=k₁₂(v₁−v₂)²+k₂₃(v₂−v₃)²+k₁₃(v₁−v₃)²≥0. Les deux autres valeurs propres sont négatives puisque les trois taux sont strictement positifs.</p>
<p>La projection de Y₀ sur le mode uniforme donne (S₀/3)(1,1,1). Les autres composantes décroissent : à quantité conservée 1, chaque réservoir tend vers 1/3. Le plus petit taux non nul donne la relaxation la plus lente.</p>
<p>Avec perte uniforme δ, tous les modes sont multipliés par e<sup>−δt</sup>. Les proportions P=Y/S satisfont le système sans perte ; elles tendent toujours vers 1/3. Il faut distinguer une quantité qui tend vers 0 d’une proportion qui tend vers 1/3.</p>
<p>Le portrait de phase se situe dans le triangle P₁≥0, P₂≥0, P₁+P₂≤1, puisque P₃=1−P₁−P₂. La représentation plane respecte la conservation au lieu d’oublier le troisième réservoir.</p>'''),
lesson('Deux conditions aux bords : une autre question que Cauchy', 'Spé', 'green_bords', '''
<p>Le problème de Cauchy y(0)=α, y′(0)=β fixe deux données au même point et admet une solution unique lorsque les coefficients sont continus. Les conditions y(0)=y(π)=0 imposent deux valeurs en deux points ; l’argument de Cauchy ne s’y applique pas automatiquement.</p>
<p>Considérer y″+λy=f sur [0,π]. Pour λ&gt;0, une solution homogène s’annulant en 0 est Csin(√λx). Elle s’annule aussi en π pour tout C lorsque λ=n². Ces valeurs créent un noyau non nul pour le problème aux bords.</p>
<p>Pour f=a sin x+b sin(2x), hors λ=1,4, la particulière a sin x/(λ−1)+b sin(2x)/(λ−4) satisfait les bords. Si λ n’est aucun carré entier positif, elle est unique. Si λ=9, par exemple, on peut encore ajouter Csin(3x).</p>
<p>La méthode de tir démarre y(0)=0,y′(0)=1. Pour l’homogène, sa valeur finale sin(π√λ)/√λ détecte les valeurs résonantes ; à λ=0 la limite vaut π. Un zéro signifie que la pente initiale ne peut pas être déterminée par la seule valeur finale.</p>'''),
lesson('Compatibilité : l’alternative se prouve par intégration', 'Spé → Au-delà', 'green_bords', '''
<p>À λ=n², multiplier l’équation par s(x)=sin(nx). Les deux intégrations par parties utilisent y(0)=y(π)=s(0)=s(π)=0 et s″=−n²s. Il vient <strong>∫₀^π f(x)sin(nx)dx=0</strong>. C’est une condition nécessaire d’existence.</p>
<p>Pour le second membre du laboratoire, les sinus sont orthogonaux : ∫sin²(nx)=π/2, et ∫sin(mx)sin(nx)=0 pour m≠n. À λ=1, il faut a=0 ; à λ=4, il faut b=0. Si cette condition manque, il n’existe aucune solution.</p>
<p>Si la condition est satisfaite, la partie non résonante donne une particulière, et Csin(nx) reste libre. Il existe alors une infinité de solutions. Le curseur « amplitude libre » modifie réellement la solution sans changer l’équation ni les bords.</p>
<p>La proximité d’une valeur résonante produit une grande réponse : un coefficient contient 1/(λ−n²). Cette sensibilité correspond au phénomène physique de résonance. À la valeur exacte, il faut traiter la compatibilité ; remplacer un dénominateur nul par un petit nombre fabriquerait une fausse solution.</p>'''),
]

EXERCISES = [
exercise('TP : résoudre sans perdre la solution constante','Sup','euler_rk4','<p>Résoudre y′=cos(x)(y+1), y(0)=y₀. Pourquoi diviser par y+1 demande-t-il une précaution ?</p>','<p>Poser z=y+1 et dériver ze<sup>−sin x</sup> : la dérivée est nulle. Ainsi z=(y₀+1)e<sup>sin x</sup> et y=(y₀+1)e<sup>sin x</sup>−1. Pour y₀=−1, z=0 et y≡−1 ; une division par z aurait exclu cette solution. Toutes les formules sont globales et vérifient la condition initiale.</p>'),
exercise('Maxima, minima et périodicité du TP','Sup','euler_rk4','<p>Pour y(0)=0, déterminer la période, les extrema et leurs abscisses. Que change y₀&lt;−1 ?</p>','<p>y=e<sup>sin x</sup>−1 est 2π-périodique. Sa dérivée e<sup>sin x</sup>cos x a le signe de cos x. Les maxima e−1 sont en π/2+2kπ ; les minima e<sup>−1</sup>−1 sont en 3π/2+2kπ. Si y₀&lt;−1, le facteur y₀+1 est négatif et les types des extrema s’inversent. Si y₀=−1, la fonction est constante.</p>'),
exercise('Choisir un maillage par un ordre mesuré','Spé','euler_rk4','<p>Une méthode donne E(h)=3,2×10⁻⁴ et E(h/2)=2,0×10⁻⁵. Estimer son ordre et le pas requis pour E≤10⁻⁶, en supposant le régime asymptotique atteint.</p>','<p>Le rapport vaut 16, donc p≈log₂16=4. Après une nouvelle division par 2, E(h/4)≈1,25×10⁻⁶ ; ce n’est pas encore suffisant. Après deux divisions, E(h/8)≈7,81×10⁻⁸. Une estimation continue donnerait h<sub>nouveau</sub>≈(h/2)(10⁻⁶/2×10⁻⁵)¹ᐟ⁴≈0,473(h/2). Il faut vérifier ce choix par un raffinement supplémentaire, car l’ordre est observé et non garanti par ces seules données.</p>'),
exercise('Le facteur intégrant à coefficient variable','Sup','facteur_integrant','<p>Résoudre y′+(a+bx)y=Fcos(ωx), y(0)=y₀, sous forme d’intégrale définie. Vérifier le signe de la primitive.</p>','<p>A(x)=ax+bx²/2 satisfait A′=a+bx. Alors (eᴬy)′=eᴬFcos(ωx). Intégrer entre 0 et x donne y=e<sup>−A(x)</sup>[y₀+F∫₀ˣe<sup>A(s)</sup>cos(ωs)ds]. En dérivant, le premier terme produit −A′y et la borne variable fournit Fcos(ωx) ; on retrouve bien y′+(a+bx)y=Fcos(ωx).</p>'),
exercise('Deux préparations, un même forçage','Sup → Spé','facteur_integrant','<p>Deux solutions ont les données y₀ et y₀+1. Calculer leur différence et expliquer pourquoi sa décroissance ne force pas la décroissance de chacune.</p>','<p>Leur différence d satisfait d′+(a+bx)d=0, d(0)=1. Donc d=e<sup>−ax−bx²/2</sup>. Pour a,b≥0 et x≥0, d est décroissante. Chaque solution possède toutefois une contribution forcée oscillante ; elle peut croître sur certains intervalles. La stabilité de la différence est une propriété distincte du sens de variation d’une trajectoire.</p>'),
exercise('Circuit RC : retrouver la convolution','Sup → Spé','facteur_integrant','<p>Un condensateur vérifie RC u′+u=V(t), avec u(0)=u₀. Donner sa solution et interpréter le noyau pour un échelon V(t)=V₀.</p>','<p>Après division, a=1/(RC) et c=V/(RC). Ainsi u(t)=u₀e<sup>−t/(RC)</sup>+(1/(RC))∫₀ᵗe<sup>−(t−s)/(RC)</sup>V(s)ds. Pour V constant, u=V₀+(u₀−V₀)e<sup>−t/(RC)</sup>. Le noyau pondère les contributions passées et la constante RC fixe le temps de relaxation. R,C doivent être strictement positifs et constants.</p>'),
exercise('Construire trois solutions avec la même donnée','Spé → Au-delà','cauchy_lipschitz','<p>Vérifier que yτ(t)=max(t−τ,0)², τ≥0, résout y′=2√max(y,0), y(0)=0. Examiner la dérivabilité à τ.</p>','<p>Pour t&lt;τ, y=0 et y′=0 ; pour t&gt;τ, y=(t−τ)² et y′=2(t−τ)=2√y. À τ, les quotients différentiels tendent vers 0 des deux côtés. y est donc C¹, et les deux membres valent 0 à τ. Toutes les valeurs τ≥0 donnent la même donnée initiale et des solutions différentes : l’unicité échoue.</p>'),
exercise('Localement lipschitzien ou seulement continu ?','Spé → Au-delà','cauchy_lipschitz','<p>Comparer f(y)=λy et g(y)=2√max(y,0) au voisinage de 0. Que peut-on conclure si une hypothèse suffisante d’un théorème échoue ?</p>','<p>|f(y)−f(z)|≤|λ||y−z| : f est lipschitzienne. Pour ε&gt;0, |g(ε)−g(0)|/ε=2/√ε n’est pas borné au voisinage de 0 ; g n’est pas localement lipschitzienne en 0. L’échec de cette hypothèse ne suffit pas en général à réfuter l’unicité. Ici la famille explicite yτ fournit en plus le contre-exemple nécessaire.</p>'),
exercise('Unicité et instabilité ne se contredisent pas','Sup → Spé','cauchy_lipschitz','<p>Pour y′=2y, comparer les données 0 et 10⁻⁶. Donner le temps où la différence atteint 10⁻². Pourquoi chaque solution reste-t-elle unique ?</p>','<p>Les solutions sont 0 et 10⁻⁶e²ᵗ. L’écart atteint 10⁻² lorsque e²ᵗ=10⁴, soit t=2ln10≈4,605. Les deux données sont différentes ; l’unicité ne demande pas que leurs solutions restent proches. Pour une donnée fixée, la différence de deux prétendues solutions serait Ce²ᵗ avec C=0, donc elles coïncideraient.</p>'),
exercise('Déterminer un intervalle maximal','Spé → Au-delà','explosion_logistique','<p>Résoudre y′=ay², a&gt;0, y(0)=y₀&gt;0, et donner le domaine maximal contenant 0. Peut-on prolonger la solution avec la même expression après le pôle ?</p>','<p>La solution est y=y₀/(1−ay₀t). Son pôle t*=1/(ay₀) donne le domaine ]−∞,t*[ contenant 0. Comme y→+∞ à gauche de t*, aucun prolongement réel continu n’est possible à t*. La branche algébrique définie après le pôle est une autre solution sur un autre intervalle ; elle n’est pas un prolongement à travers t*.</p>'),
exercise('Logistique : résoudre et prévoir le sens du mouvement','Sup → Spé','explosion_logistique','<p>Résoudre z′=rz(1−z/K), z(0)=z₀&gt;0. Traiter également les équilibres et discuter les cas z₀&lt;K et z₀&gt;K.</p>','<p>Les équilibres sont 0 et K ; il faut les noter avant de séparer les variables. Pour une donnée positive, z=K/[1+(K/z₀−1)e<sup>−rt</sup>]. Si z₀&lt;K, le dénominateur décroît vers 1 et z croît vers K. Si z₀&gt;K, le dénominateur croît vers 1 et z décroît vers K. z₀=K donne la constante K ; z₀=0 donne la constante 0.</p>'),
exercise('Linéariser au bon équilibre','Spé','explosion_logistique','<p>Poser z=K+η dans la logistique. Trouver le taux de relaxation des petites perturbations et le comparer à celui près de 0.</p>','<p>η′=r(K+η)(−η/K)=−rη−rη²/K. Au premier ordre η′≈−rη, donc η≈η₀e<sup>−rt</sup>. Près de 0, z′≈rz, donc une petite perturbation positive croît comme eʳᵗ. K est stable et 0 est instable à droite. La linéarisation décrit des écarts suffisamment petits, pas tout le mouvement à grande amplitude.</p>'),
exercise('Amortissement critique avec des données explicites','Sup','oscillateur_resonance','<p>Résoudre y″+2ω₀y′+ω₀²y=0, y(0)=1,y′(0)=0, ω₀&gt;0. Vérifier le comportement au départ.</p>','<p>La racine double −ω₀ donne y=(A+Bt)e<sup>−ω₀t</sup>. A=1 et y′(0)=B−ω₀A=0 imposent B=ω₀. Donc y=(1+ω₀t)e<sup>−ω₀t</sup>, y′=−ω₀²te<sup>−ω₀t</sup>. La dérivée est nulle au départ puis négative, et y tend vers 0 sans oscillation. Un sinus de pulsation nulle n’aurait pas fourni le facteur t nécessaire.</p>'),
exercise('La résonance non amortie est une croissance','Sup → Spé','oscillateur_resonance','<p>Résoudre y″+ω₀²y=Fcos(ω₀t), y(0)=y′(0)=0. Vérifier par dérivation puis commenter l’amplitude.</p>','<p>Une particulière est y=Ft sin(ω₀t)/(2ω₀). Elle vérifie les deux données nulles. Sa dérivée vaut F[sin(ω₀t)+ω₀tcos(ω₀t)]/(2ω₀), et sa dérivée seconde ajoutée à ω₀²y vaut Fcos(ω₀t). L’enveloppe Ft/(2ω₀) croît ; il n’existe aucune amplitude stationnaire finie. Sur une durée fixée, un maximum reste mesurable, mais dépend de cette durée.</p>'),
exercise('Résonance en déplacement et puissance','Spé','oscillateur_resonance','<p>Établir |U| pour l’oscillateur amorti forcé, déterminer son maximum éventuel et retrouver le bilan d’énergie.</p>','<p>U=F/(ω₀²−ω²+2iζω₀ω), donc |U|=F/[ω₀²√((1−r²)²+4ζ²r²)], r=ω/ω₀. Dériver le dénominateur au carré donne r²=1−2ζ² ; une résonance à r&gt;0 existe si ζ&lt;1/√2. Multiplier l’EDO par y′ donne E′=Fcos(ωt)y′−2ζω₀(y′)². Une moyenne sur un régime périodique établi impose puissance injectée moyenne égale à puissance dissipée moyenne.</p>'),
exercise('Le Wronskien de l’exercice 1','Spé','variation_constantes','<p>Pour y″−5y′+6y=g, calculer le Wronskien de e²ˣ,e³ˣ et les dérivées des coefficients de variation des constantes.</p>','<p>W=e²ˣ3e³ˣ−2e²ˣe³ˣ=e⁵ˣ. Imposer a′e²ˣ+b′e³ˣ=0 et 2a′e²ˣ+3b′e³ˣ=g. Cramer donne a′=−ge<sup>−2x</sup>, b′=ge<sup>−3x</sup>. Pour g=eˣ/cosh²x, a′=−e<sup>−x</sup>/cosh²x et b′=e<sup>−2x</sup>/cosh²x. W ne s’annule jamais, donc la construction est valable sur tout ℝ.</p>'),
exercise('Une particulière à deux données nulles','Spé','variation_constantes','<p>Poser K(u)=e³ᵘ−e²ᵘ et y_p(x)=∫₀ˣK(x−s)g(s)ds. Vérifier l’EDO et les données y_p(0)=y_p′(0)=0.</p>','<p>K(0)=0, K′(0)=1 et K″−5K′+6K=0. La première dérivation donne y_p′=∫₀ˣK′(x−s)g(s)ds ; la seconde ajoute g(x). Combiner les trois intégrales donne y_p″−5y_p′+6y_p=g. À x=0 les intégrales sont nulles, donc y_p et y_p′ le sont. Ces identités demandent seulement g continue pour les dérivations considérées.</p>'),
exercise('Ajuster deux constantes et mesurer la sensibilité','Spé','variation_constantes','<p>Ajouter une homogène à la particulière précédente pour imposer y(0)=y₀,y′(0)=v₀. Comment une petite erreur ε sur v₀ se propage-t-elle ?</p>','<p>On résout A+B=y₀, 2A+3B=v₀, d’où A=3y₀−v₀ et B=v₀−2y₀. Une erreur ε sur v₀ change la solution de ε(e³ˣ−e²ˣ). Elle est fortement amplifiée pour x&gt;0. Ce comportement vient du problème lui-même ; un contrôle numérique doit comparer l’erreur à une échelle adaptée au mouvement et ne pas supposer une stabilité absente.</p>'),
exercise('Transformer une équation d’Euler–Cauchy','Spé','euler_cauchy','<p>Pour x&gt;0, poser x=eᵗ et Y(t)=y(eᵗ). Exprimer Y′ et Y″, puis transformer x²y″+xy′−y=f(x).</p>','<p>Y′=xy′ et Y″=xy′+x²y″. L’équation devient Y″−Y=f(eᵗ). L’homogène a pour solutions eᵗ,e<sup>−t</sup>, qui redonnent x et 1/x. Le changement impose x&gt;0 ; on peut traiter x&lt;0 avec x=−eᵗ. Le point 0 n’est atteint que lorsque t→−∞ et doit être étudié par prolongement.</p>'),
exercise('Identifier la série et ses premiers coefficients','Spé','euler_cauchy','<p>Résoudre par série entière x²y″+xy′−y=x²/(1−x²) au voisinage de 0. Quels coefficients sont libres ?</p>','<p>Pour y=∑aₘxᵐ, le membre gauche vaut ∑(m²−1)aₘxᵐ. Le second membre est ∑ₙ≥₁x²ⁿ. On obtient a₀=0, a₁ libre, a₂ₙ=1/(4n²−1), et les autres coefficients impairs nuls. Ainsi y=a₁x+x²/3+x⁴/15+x⁶/35+… . Le rayon de la particulière est 1. La série est régulière et ne contient pas le mode 1/x.</p>'),
exercise('Prolonger une formule présentant 0/0','Spé','euler_cauchy','<p>Étudier en 0 P(x)=[(x²−1)ln|(1+x)/(1−x)|+2x]/(4x). Donner P(0),P′(0),P″(0) et préciser les singularités restantes.</p>','<p>ln((1+x)/(1−x))=2(x+x³/3+x⁵/5+…). La substitution donne P=x²/3+x⁴/15+… . Le prolongement est analytique, P(0)=P′(0)=0 et P″(0)=2/3. Un terme C₂/x ne serait pas prolongeable régulièrement et doit être exclu. Les points ±1 restent singuliers pour le second membre de l’EDO ; ce calcul en 0 ne les supprime pas.</p>'),
exercise('Vérifier une solution globale au point singulier','Spé','riccati','<p>Pour c&gt;0, vérifier sur tout ℝ que y=cx²−1/(4c) satisfait xy′=y+√(x²+y²). Pourquoi c&gt;0 est-il utile ?</p>','<p>On calcule x²+y²=(cx²+1/(4c))². Le facteur cx²+1/(4c) est positif si c&gt;0 ; sa valeur absolue est donc lui-même. Le membre droit vaut 2cx², comme xy′ avec y′=2cx. À x=0 il vaut −1/(4c)+1/(4c)=0. La positivité de c fixe le signe de la racine ; sans elle, on ne pourrait pas supprimer la valeur absolue de la même manière.</p>'),
exercise('Riccati : produire un pôle par une solution linéaire','Spé → Au-delà','riccati','<p>Transformer z′=z²−1 par z=−u′/u, imposer z(0)=z₀ et trouver le temps d’explosion pour z₀&gt;1.</p>','<p>z′=z²−u″/u, donc prendre u″=u. Avec u(0)=1,u′(0)=−z₀, u=cosh t−z₀sinh t. Il s’annule lorsque tanh t=1/z₀, donc t*=argth(1/z₀)&gt;0. Le quotient z=(z₀cosh t−sinh t)/u explose à ce point, alors que u reste une solution régulière de l’EDO linéaire. Le changement est valable seulement entre deux zéros de u.</p>'),
exercise('Deux équilibres de Riccati et leur stabilité','Spé','riccati','<p>Étudier qualitativement z′=z²−1 autour de −1 et 1, puis vérifier les solutions constantes dans la formule explicite.</p>','<p>Le second membre vaut (z−1)(z+1) : il est positif pour z&lt;−1 et z&gt;1, négatif entre −1 et 1. Les trajectoires proches de −1 y reviennent, celles proches de 1 s’en éloignent. Dans la formule explicite, z₀=−1 donne u=eᵗ et z=−1 ; z₀=1 donne u=e<sup>−t</sup> et z=1. Ces deux cas doivent être conservés, notamment avant une séparation par z²−1.</p>'),
exercise('Écrire la matrice et le bilan total','Spé','lineaire_systeme','<p>Écrire A pour trois réservoirs symétriquement couplés de taux k₁₂,k₂₃,k₁₃, avec perte δ. Montrer S′=−δS.</p>','<p>A a pour diagonale (−k₁₂−k₁₃−δ,−k₁₂−k₂₃−δ,−k₁₃−k₂₃−δ), et pour coefficients hors diagonale kᵢⱼ. Les sommes de colonnes sont −δ, donc (1,1,1)AY=−δ(Y₁+Y₂+Y₃). Ainsi S′=−δS et S=S₀e<sup>−δt</sup>. La perte peut réduire chaque quantité sans modifier la conservation des échanges internes.</p>'),
exercise('Échanges identiques : diagonaliser sans déterminant','Spé','lineaire_systeme','<p>Avec tous les taux égaux à k&gt;0 et δ=0, déterminer les modes et l’évolution d’une quantité initiale placée dans le premier réservoir.</p>','<p>A=k(J−3I), où J est la matrice de tous les 1. Le vecteur uniforme a valeur propre 0 ; tout vecteur de somme nulle a valeur propre −3k. Décomposer (1,0,0)=(1/3,1/3,1/3)+(2/3,−1/3,−1/3). Donc Y₁=1/3+(2/3)e<sup>−3kt</sup>, Y₂=Y₃=1/3−(1/3)e<sup>−3kt</sup>. Ces trois quantités sont positives et de somme 1.</p>'),
exercise('Démontrer les taux négatifs et interpréter les proportions','Spé','lineaire_systeme','<p>Pour δ=0, démontrer vᵀAv≤0. Que deviennent les valeurs propres et les proportions lorsqu’on ajoute une perte uniforme δ ?</p>','<p>vᵀAv=−∑ᵢ&lt;ⱼkᵢⱼ(vᵢ−vⱼ)²≤0. Le noyau est le mode uniforme puisque les taux sont positifs ; les autres valeurs propres sont strictement négatives. Ajouter −δI translate toutes les valeurs propres de −δ. Comme S=e<sup>−δt</sup>, les proportions P=Y/S satisfont P′=(A+δI)P et retrouvent le système conservatif. Elles tendent vers 1/3, tandis que les quantités tendent vers 0 si δ&gt;0.</p>'),
exercise('Unicité de Cauchy contre non-unicité aux bords','Spé','green_bords','<p>Donner un exemple où y″+y=0, y(0)=y(π)=0 possède une infinité de solutions. Comparer à y(0)=0,y′(0)=1.</p>','<p>Toutes les fonctions Csin x satisfont les deux valeurs aux bords, donc l’unicité échoue. Pour le problème de Cauchy, écrire y=Acos x+Bsin x ; y(0)=0 impose A=0 et y′(0)=1 impose B=1. La solution est sin x. Deux conditions ne jouent pas le même rôle lorsqu’elles sont imposées en deux points ou au même point.</p>'),
exercise('Démontrer l’incompatibilité à la résonance','Spé','green_bords','<p>Montrer qu’il n’existe aucune solution de y″+y=sin x sur [0,π] avec y(0)=y(π)=0.</p>','<p>Multiplier par sin x et intégrer. Deux intégrations par parties, les quatre valeurs aux bords étant nulles, donnent ∫₀^π(y″+y)sin x dx=0. Le second membre impose ∫₀^πsin²x dx=π/2, contradiction. Ce raisonnement démontre l’absence de solution ; tracer une très grande courbe obtenue en divisant par un petit dénominateur ne la remplacerait pas.</p>'),
exercise('Compatibilité et amplitude libre d’un troisième mode','Spé → Au-delà','green_bords','<p>Résoudre y″+9y=sin x+(1/2)sin(2x), y(0)=y(π)=0. Expliquer pourquoi aucune donnée du second membre ne fixe le mode sin(3x).</p>','<p>Une particulière est (1/8)sin x+(1/10)sin(2x), car 9−1=8 et (1/2)/(9−4)=1/10. Ajouter Csin(3x), C réel, donne toutes les solutions satisfaisant les bords. Le second membre est orthogonal à sin(3x), donc compatible avec la valeur résonante 9 ; il ne détermine pas l’amplitude du mode appartenant au noyau. Une condition supplémentaire adaptée pourrait la fixer.</p>'),
]

def guide(purpose,objects,hypotheses,techniques,sup,spe,beyond,first_steps,expected):
    return dict(purpose=purpose,objects=objects,hypotheses=hypotheses,techniques=techniques,levels=dict(sup=sup,spe=spe,beyond=beyond),first_steps=first_steps,expected=expected)

GUIDES = {
'euler_rk4':guide('Résoudre le TP p. 69 et mesurer la précision de deux méthodes plutôt que juger seulement l’allure des courbes.',
 ['x est l’abscisse en radians ; y est la fonction recherchée, sans dimension.', 'N est le nombre de pas ; h=T/N est leur longueur.', 'E est l’erreur maximale aux nœuds par rapport à la formule exacte.'],
 ['Même condition initiale et même intervalle pour les trois courbes.', 'L’équation est linéaire, régulière et globalement résoluble ; les erreurs viennent ici des méthodes numériques.'],
 ['Résoudre une EDO linéaire et vérifier une formule par dérivation.', 'Comparer des maillages, utiliser un graphique logarithmique et estimer un ordre.'],
 'Retrouver y=e^{sin x}−1 et ses extrema.', 'Comparer Euler à RK4, distinguer erreur locale et globale.', 'Contrôle d’erreur et choix d’une méthode sur des EDO sans solution exacte.',
 ['Choisir le TP et suivre les pentes sur la solution exacte.', 'Choisir le pas grossier puis augmenter N.', 'Lire les ordres mesurés ; vérifier pourquoi diviser le pas par 2 ne produit pas le même gain pour Euler et RK4.'],
 'Justifier l’ordre observé, annoncer la référence utilisée et séparer précision et présentation du graphique.'),
'facteur_integrant':guide('Transformer une équation différentielle linéaire en intégrale définie, puis interpréter la mémoire et la sensibilité.',
 ['a+bx est le coefficient de y ; Fcos(ωx) est le second membre.', 'A=ax+bx²/2 est une primitive ; eᴬ est le facteur intégrant.', 'Les deux préparations ont un écart initial exactement égal à 1.'],
 ['Coefficients continus ; a,b≥0 pour une relaxation à droite.', 'Quadrature de Gauss et RK4 calculent indépendamment le même problème.'],
 ['Dérivation d’un produit et primitive.', 'Variation des constantes, différence de deux solutions et noyau intégral.'],
 'Construire le facteur intégrant en vérifiant son signe.', 'Interpréter le noyau et démontrer la décroissance de l’écart.', 'Mémoire d’un système linéaire à coefficient variable.',
 ['Choisir la relaxation constante et retrouver l’exponentielle.', 'Choisir le coefficient variable et examiner le noyau par l’écart initial.', 'Mettre a=b=F=0 puis expliquer pourquoi les deux solutions restent constantes et distinctes.'],
 'Reconstruire la formule intégrale avec la bonne constante et relier sa dérivée à l’EDO.'),
'cauchy_lipschitz':guide('Distinguer une hypothèse d’un théorème, sa conclusion et une preuve effective de non-unicité.',
 ['τ est un instant de départ choisi ; toutes les courbes non linéaires ont y(0)=0.', 'ε est un petit écart initial dans le problème linéaire.', 'Le quotient 2/√ε teste la possibilité d’une constante de Lipschitz près de 0.'],
 ['Les branches en attente sont exactes et C¹.', 'Cauchy–Lipschitz est un prolongement ; le cours CPGE fournit le cas linéaire.'],
 ['Vérification par morceaux et raccordement des dérivées.', 'Différence de solutions et analyse d’une hypothèse suffisante.'],
 'Vérifier directement chaque solution et chaque donnée initiale.', 'Séparer unicité et stabilité ; expliquer le contre-exemple.', 'Existence locale, conditions de Lipschitz et limites d’une simulation.',
 ['Changer τ : noter que la donnée initiale ne change jamais.', 'Lire le quotient pour de petits ε.', 'Passer λ de −1 à 1 : expliquer pourquoi une divergence de deux préparations ne réfute pas l’unicité.'],
 'Savoir expliquer pourquoi un calcul partant de zéro peut sélectionner une solution sans démontrer son unicité.'),
'explosion_logistique':guide('Donner un sens au domaine maximal d’une solution, puis étudier qualitativement un modèle avec saturation.',
 ['t*=1/(ay₀) est le temps d’explosion à droite.', 'Le curseur fraction arrête le tracé strictement avant t*.', 'K est un niveau d’équilibre, r le taux de relaxation logistique.'],
 ['Données et paramètres positifs ; aucun pôle n’est traversé.', 'Les deux équations ont le même point initial mais des seconds membres différents.'],
 ['Séparation des variables, limites et intervalle de définition.', 'Équilibres, tableau de signes et linéarisation.'],
 'Résoudre les deux équations et lire leurs tableaux de variations.', 'Relier saturation et stabilité ; distinguer solution locale et globale.', 'Solution maximale, explosion et contrôle a priori.',
 ['Comparer les deux modèles au réglage initial.', 'Approcher la fraction 0,95 et suivre la droite 1/y.', 'Partir au-dessus de K ; prévoir le sens d’évolution logistique avant le calcul.'],
 'Nommer un intervalle maximal et justifier la saturation par le second membre, sans confondre les deux notions.'),
'oscillateur_resonance':guide('Relier l’équation d’ordre 2, ses deux données initiales et les applications physiques de la résonance.',
 ['ω₀ est la pulsation propre ; ω/ω₀ le rapport de pulsations.', 'ζ est l’amortissement réduit ; Fcos(ωt) le forçage.', 'y′ est la vitesse ; E=[(y′)²+ω₀²y²]/2 est l’énergie réduite.'],
 ['Équation linéaire à coefficients constants, masse unité.', 'À ζ=0, les maxima de la réponse sont mesurés sur un temps fini.', 'Le champ de phase forcé est figé à t=0 ; la trajectoire reste temporelle.'],
 ['Équation caractéristique, données de Cauchy et réponse complexe.', 'Résonance, puissances et bilan énergétique.'],
 'Identifier les trois régimes libres et ajuster les constantes.', 'Calculer l’amplitude et sa résonance, vérifier le travail.', 'Réponse impulsionnelle et interprétation spectrale.',
 ['Choisir le cas critique puis le cas apériodique libre.', 'Comparer la résonance amortie à la résonance sans amortissement.', 'Doubler la durée sans amortissement : expliquer la croissance du maximum et contrôler E−E₀=W−D.'],
 'Énoncer quand une amplitude stationnaire a un sens et quand le temps d’observation fait partie du résultat.'),
'variation_constantes':guide('Résoudre l’exercice 1 p. 71 et interpréter chaque étape de la variation des constantes.',
 ['g(x)=eˣ/cosh²x, multiplié par le curseur amplitude.', 'W=e^{5x} est le Wronskien de e^{2x} et e^{3x}.', 'a(x),b(x) sont les coefficients de la particulière de données initiales nulles.'],
 ['Coefficient dominant non nul et fonctions continues sur ℝ.', 'Deux modes homogènes croissants rendent les erreurs initiales sensibles.'],
 ['Équation caractéristique, Wronskien et système de Cramer.', 'Intégrales à borne variable et ajustement de deux données.'],
 'Identifier la base homogène et les deux conditions initiales.', 'Construire a′,b′ puis le noyau integral.', 'Convolution, réponse impulsionnelle et transformée de Laplace.',
 ['Calculer la particulière à données nulles et comparer ses deux coefficients.', 'Ajouter la solution homogène de donnée y₀=1,v₀=2.', 'Supprimer le second membre : vérifier le mode e^{3x} puis examiner l’écart Gauss/RK4.'],
 'Retrouver le signe des coefficients et expliquer pourquoi une particulière doit encore être ajustée au problème initial.'),
'euler_cauchy':guide('Résoudre l’exercice 2 p. 71 sans oublier le domaine, puis utiliser les séries entières pour comprendre et calculer.',
 ['C₁x et C₂/x sont les deux modes homogènes hors de 0.', 'Le réglage régulier impose C₂=0.', 'La série est toujours comparée sur [0,1−écart], même si le tracé principal est à droite de 1.'],
 ['Les points ±1 ne sont jamais inclus ; la branche en 0 est traitée séparément.', 'La formule logarithmique est calculée par sa série près de 0 pour limiter la perte de précision.'],
 ['Essai xᵐ, transformation x=eᵗ et formes normales.', 'Identification de coefficients, rayon de convergence et prolongement.'],
 'Repérer les points où une formule ou une division demande une précaution.', 'Construire la série, les modes et le prolongement analytique.', 'Points singuliers réguliers et méthode de Frobenius.',
 ['Choisir le prolongement régulier et vérifier le comportement x²/3 près de 0.', 'Activer le mode 1/x sur un intervalle évitant 0.', 'Approcher x=1 puis augmenter le nombre de termes ; comparer convergence de la série et singularité du problème.'],
 'Donner la solution avec son intervalle et distinguer un faux 0/0 d’un véritable mode singulier.'),
'riccati':guide('Comparer deux substitutions classiques en surveillant leurs domaines de validité.',
 ['c>0 paramètre la famille globale de l’exercice 3.', 'Le premier changement est z=y/x, réalisé seulement hors de 0.', 'La Riccati indépendante z′=z²−1 utilise z=−u′/u.'],
 ['La racine √(x²+y²) garde le signe de |x| dans les transformations.', 'Le calcul Riccati s’arrête avant un zéro de u.'],
 ['Substitution homogène, fonctions hyperboliques et raccordement.', 'Dérivation d’un quotient et linéarisation exacte d’une Riccati.'],
 'Vérifier directement la famille et sa valeur en 0.', 'Retrouver les changements et les signes dans la racine.', 'EDO de Riccati, pôles et réduction à une équation linéaire.',
 ['Changer c et observer le raccordement en 0.', 'Choisir z₀=−1 puis z₀=1 : vérifier les équilibres de Riccati.', 'Choisir z₀=1,5 ; rapprocher le pôle de Riccati du zéro de u.'],
 'Nommer correctement l’équation et expliciter les points où le changement de fonction cesse d’être valable.'),
'lineaire_systeme':guide('Passer de bilans concrets à un système de dimension 3 et utiliser ses modes pour expliquer l’évolution.',
 ['Yᵢ est une quantité ; Pᵢ=Yᵢ/S une proportion.', 'Les kᵢⱼ sont des taux symétriques positifs ; δ est une perte commune.', 'Le triangle de phase utilise P₁,P₂ et P₃=1−P₁−P₂.'],
 ['Volumes identiques et coefficients constants.', 'La perte uniforme réduit le total sans modifier la dynamique des proportions.'],
 ['Mise en équations, matrice symétrique et diagonalisation.', 'Exponentielle matricielle, bilan global et formes quadratiques.'],
 'Écrire les trois bilans et vérifier la quantité totale.', 'Calculer les modes et interpréter le taux lent.', 'Réseaux de diffusion et générateurs conservant la positivité.',
 ['Choisir des échanges symétriques et retrouver les deux modes de taux 3k.', 'Ralentir un échange et comparer les temps propres.', 'Introduire une perte : comparer les quantités et les proportions au temps final.'],
 'Associer chaque valeur propre à un bilan ou à une relaxation et conserver le sens du troisième réservoir.'),
'green_bords':guide('Étudier concrètement l’existence et l’unicité sous deux conditions aux bords ; favoriser les applications des théorèmes.',
 ['λ est le paramètre spectral ; les valeurs n² sont résonantes.', 'Le second membre est a sin x+b sin(2x).', 'L’amplitude libre n’est utilisée que si le problème est résonant et compatible.'],
 ['Bords homogènes en 0 et π.', 'Une candidate incompatible n’est pas annoncée comme une solution : son résidu reste affiché.'],
 ['Solutions homogènes, méthode de tir et orthogonalité des sinus.', 'Intégration par parties et condition de compatibilité.'],
 'Résoudre l’homogène et comparer données au même point / deux points.', 'Établir la condition intégrale et classer unique / aucune / infinité.', 'Alternative de Fredholm, fonctions de Green et problèmes spectraux.',
 ['Choisir λ=2 : vérifier la solution unique.', 'Choisir la résonance incompatible : interpréter le résidu.', 'Rendre le second membre compatible puis varier l’amplitude libre sans modifier l’équation ni les bords.'],
 'Vérifier la compatibilité avant de conclure à une solution et démontrer pourquoi l’unicité de Cauchy ne suffit pas ici.'),
}
