"use strict";
const $ = s => document.querySelector(s);
const COLORS = {ink:'#17363d', green:'#23745c', mint:'#88c4a8', gold:'#c79432', rose:'#b66375', grey:'#627477', line:'#e2e6df'};
const clone = x => JSON.parse(JSON.stringify(x));
const fmt = (x, n=5) => x === null ? '∅' : !Number.isFinite(x) ? '—' : x !== 0 && Math.abs(x)<.0001 ? x.toExponential(2).replace('.', ',') : x.toLocaleString('fr-FR',{maximumFractionDigits:n});
const defaults = {
 approximation:{L:Math.PI/2,degre:1,poids:0,a:-.1,b:.6},
 matrices:{theta:55,n:3,complexe:false,eta:0,phase:45},
 produit:{axes:[2,1.2,.8],puissances:[1,1,1],longitude:25,latitude:20},
 point:{centre:[.4,-.2,.1],axes:[2,1.2,.8],angles:[15,25,35],point:[3,2,1]},
 paire:{e1:{centre:[-2.4,-.6,0],axes:[1.8,1,.7],angles:[10,20,25]},e2:{centre:[2.4,.8,.5],axes:[1.4,.9,.6],angles:[-20,35,-35]}}
};
let states=clone(defaults), current='approximation', bootstrap, result, serial=0, timer, camera={yaw:.7,pitch:.42};
const meta={
 approximation:['Sup → Spé','Approcher cosinus, choisir une norme','Le TP devient un laboratoire de projection : degré, poids, norme uniforme et descente de gradient.','Courbe, erreurs et descente'],
 matrices:['Sup → Spé','Projeter une matrice, optimiser une distance','L’exercice 4, puis la contrainte antisymétrique de déterminant 1 sur ℝ ou ℂ.','Décomposition orthogonale'],
 produit:['Sup → Spé','De la sphère à l’ellipsoïde','L’exercice 6 : huit maximiseurs, une boîte de volume maximal et des produits pondérés.','Ellipsoïde, points extrémaux et boîte'],
 point:['Spé','Les points les plus proches et les plus éloignés','Translation, axes différents, rotations : cherchez les extrema sur toute la surface.','Deux extrema globaux'],
 paire:['Spé · approfondissement','La distance entre deux ellipsoïdes','Deux solides orientés différemment ; bornes primal-dual et plan de séparation à marge maximale.','Points proches & plan de séparation']
};
function get(obj,path){return path.split('.').reduce((o,k)=>o[k],obj)}
function set(obj,path,v){const p=path.split('.'), last=p.pop();p.reduce((o,k)=>o[k],obj)[last]=v}
function control(label,path,min,max,step,unit='',type='range'){
 const value=get(states[current],path), id='c-'+path.replaceAll('.','-');
 if(type==='select')return `<div class="control"><label for="${id}">${label}</label><select id="${id}" data-path="${path}">${min.map(x=>`<option value="${x}" ${value===x?'selected':''}>${x}</option>`).join('')}</select></div>`;
 if(type==='checkbox')return `<div class="control"><label for="${id}">${label}<input type="checkbox" id="${id}" data-path="${path}" ${value?'checked':''}></label></div>`;
 return `<div class="control"><label for="${id}">${label}<output for="${id}">${fmt(value,3)}${unit}</output></label><input type="range" id="${id}" data-path="${path}" min="${min}" max="${max}" step="${step}" value="${value}"></div>`;
}
function sliders3(labels,prefix,min,max,step,unit=''){return labels.map((x,i)=>control(x,`${prefix}.${i}`,min,max,step,unit)).join('')}
function buildControls(){
 let html='', presets=[], note='Les résultats se recalculent lorsque vous modifiez les paramètres.';
 if(current==='approximation'){
  html=control('Intervalle [0,L]','L',.3,Math.PI/2,'any')+control('Degré du polynôme','degre',[0,1,2,3,4,5,6],0,0,'','select')+control('Poids κ','poids',-.8,4,.1)+`<fieldset><legend>Droite d’essai : a t + b</legend></fieldset>`+control('Pente a','a',-2,1,.02)+control('Ordonnée b','b',-.5,2,.02);
  presets=[['Le TP',()=>states.approximation=clone(defaults.approximation)],['Degré 3',()=>states.approximation.degre=3],['Poids croissant',()=>states.approximation.poids=3]];
  note='w(t)=1+κt/L reste positif. La droite uniforme (dorée) concerne la norme non pondérée, quel que soit le degré choisi.';
 }else if(current==='matrices'){
  html=control('Rotation θ','theta',-180,180,1,'°')+control('Dimension n','n',[2,3,4,5,6,7,8,9,10],0,0,'','select')+control('Matrices complexes','complexe',0,0,0,'','checkbox')+control('Déformation η','eta',-2,2,.05)+control('Phase φ','phase',-180,180,5,'°');
  presets=[['Dimension 3',()=>states.matrices.n=3],['Minimum n=4',()=>Object.assign(states.matrices,{n:4,eta:0})],['Complexe',()=>Object.assign(states.matrices,{n:4,complexe:true,eta:0,phase:45})]];
  note='La rotation est toujours réelle 3×3. L’ensemble de déterminant 1 utilise n. η et φ agissent sur deux blocs si n≥4 pair ; φ agit seulement en mode complexe.';
 }else if(current==='produit'){
  html=sliders3(['Demi-axe a','Demi-axe b','Demi-axe c'],'axes',.3,4,.1)+control('Longitude du point','longitude',-180,180,1,'°')+control('Latitude du point','latitude',-90,90,1,'°')+'<fieldset><legend>Exposants du produit</legend></fieldset>'+sliders3(['Exposant de |x|','Exposant de |y|','Exposant de |z|'],'puissances',.2,3,.2);
  presets=[['Sphère',()=>Object.assign(states.produit,{axes:[1,1,1],puissances:[1,1,1]})],['Ellipsoïde 3,2,1',()=>Object.assign(states.produit,{axes:[3,2,1],puissances:[1,1,1]})],['Produit |x|²|y||z|',()=>states.produit.puissances=[2,1,1]]];
  note='Ellipsoïde centré et aligné sur les axes. La boîte dorée maximise le volume pour les exposants (1,1,1). Les points verts maximisent le produit actuellement choisi.';
 }else if(current==='point'){
  html=sliders3(['Demi-axe a','Demi-axe b','Demi-axe c'],'axes',.3,4,.1)+sliders3(['Point p : x','Point p : y','Point p : z'],'point',-5,5,.1)+'<fieldset><legend>Orientation de l’ellipsoïde</legend></fieldset>'+sliders3(['Rotation x','Rotation y','Rotation z'],'angles',-90,90,5,'°');
  presets=[['Point extérieur',()=>states.point=clone(defaults.point)],['Au centre',()=>states.point.point=clone(states.point.centre)],['Sphère',()=>Object.assign(states.point,{axes:[1.5,1.5,1.5],angles:[0,0,0]})]];
  note='Centre c=(0,4 ; −0,2 ; 0,1). Les segments montrent les distances à la SURFACE. La distance au solide vaut zéro pour un point intérieur.';
 }else{
  html=control('Centre E₂ : x','e2.centre.0',-.5,6,.05)+'<fieldset><legend>Ellipsoïde E₁ · vert</legend></fieldset>'+sliders3(['Demi-axe a₁','Demi-axe b₁','Demi-axe c₁'],'e1.axes',.3,3,.1)+control('Rotation z₁','e1.angles.2',-90,90,5,'°')+'<fieldset><legend>Ellipsoïde E₂ · bleu</legend></fieldset>'+sliders3(['Demi-axe a₂','Demi-axe b₂','Demi-axe c₂'],'e2.axes',.3,3,.1)+sliders3(['Rotation x₂','Rotation y₂','Rotation z₂'],'e2.angles',-90,90,5,'°');
  presets=[['Axes & centres distincts',()=>states.paire=clone(defaults.paire)],['Deux sphères',()=>states.paire={e1:{centre:[-2,0,0],axes:[1,1,1],angles:[0,0,0]},e2:{centre:[2,0,0],axes:[1.5,1.5,1.5],angles:[0,0,0]}}],['Solides qui se recouvrent',()=>{states.paire=clone(defaults.paire);states.paire.e2.centre=[-.8,-.3,.1]}]];
  note='Distance entre les SOLIDES. Pour des ellipsoïdes disjoints, elle est aussi la distance entre leurs surfaces. En cas de recouvrement, le minimum des solides est zéro.';
 }
 $('#controls').innerHTML=html;$('#control-note').textContent=note;$('#presets').replaceChildren();
 for(const [name,fn] of presets){let b=document.createElement('button');b.textContent=name;b.onclick=()=>{fn();buildControls();calculate()};$('#presets').append(b)}
 $('#controls').oninput=e=>{const el=e.target;if(!el.dataset.path)return;const v=el.type==='checkbox'?el.checked:Number(el.value);set(states[current],el.dataset.path,v);if(el.type==='range')el.previousElementSibling.querySelector('output').textContent=fmt(v,3)+(el.dataset.path.includes('angles')||el.dataset.path==='theta'||el.dataset.path==='phase'||el.dataset.path.includes('latitude')||el.dataset.path.includes('longitude')?'°':'');clearTimeout(timer);timer=setTimeout(calculate,120)};
 $('#controls').onsubmit=e=>e.preventDefault();
}
async function calculate(){
 const id=++serial, lab=current, params=clone(states[lab]);$('#error').hidden=true;$('.results').classList.add('loading');
 try{const response=await fetch('/api',{method:'POST',headers:{'Content-Type':'application/json','X-Optimisation-Token':bootstrap.token},body:JSON.stringify({...params,action:lab})});const data=await response.json();if(!response.ok)throw Error(data.error);if(id!==serial||lab!==current)return;result=data;render();}
 catch(e){if(id===serial){$('#error').textContent=e.message;$('#error').hidden=false}}
 finally{if(id===serial)$('.results').classList.remove('loading')}
}
function metric(label,value,note){return `<div class="metric"><span>${label}</span><b>${value}</b><small>${note}</small></div>`}
function legend(entries){$('#legend').innerHTML=entries.map(([text,color])=>`<span><i class="${Object.keys(COLORS).find(k=>COLORS[k]===color)}"></i>${text}</span>`).join('')}
function matrixHtml(m){return '<table>'+m.map(row=>'<tr>'+row.map(([re,im])=>`<td>${fmt(re,3)}${Math.abs(im)>1e-10?' '+(im>0?'+':'−')+fmt(Math.abs(im),3)+'i':''}</td>`).join('')+'</tr>').join('')+'</table>'}
function render(){
 const d=result;let metrics='',details='', entries=[];
 if(current==='approximation'){
  metrics=metric('Erreur quadratique I',fmt(d.I,8),'Intégrale pondérée · distance au carré')+metric(d.poids===0?'Distance L²':'Distance L² pondérée',fmt(d.distance,7),'Racine de I')+metric('Erreur uniforme',fmt(d.sup,7),d.degre<=1?'Valeur calculée aux points critiques':`Encadrement : ≤ ${fmt(d.sup_upper,7)}`);
  details=`<p><b>Projection :</b> p(t) = ${d.coefficients.map((c,i)=>`${i?' + ':''}(${fmt(c,7)})${i?' t'+(i>1?'^'+i:''):''}`).join('')}.</p><p><b>Droite minimax non pondérée :</b> ${fmt(d.minimax.a,6)} t + ${fmt(d.minimax.b,6)} ; erreur ${fmt(d.minimax.erreur,7)}, contact intérieur t*=${fmt(d.minimax.contact,6)}.</p><p>Résidu d’orthogonalité maximal : ${fmt(Math.max(...d.orthogonalite.map(Math.abs)))}. Conditionnement de Gram (monômes) : ${fmt(d.condition_gram,1)} ; tableau QR (base normalisée) : ${fmt(d.condition_design,2)}.</p><p>La descente porte sur une droite affine, même lorsque le degré choisi est supérieur à 1. Point d’arrivée après ${d.descente.length-1} pas : a=${fmt(d.descente.at(-1)[0],5)}, b=${fmt(d.descente.at(-1)[1],5)}.</p>`;
  entries=[['cos t',COLORS.ink],['projection L²',COLORS.green],['droite minimax L∞',COLORS.gold],['droite d’essai',COLORS.rose]];
 }else if(current==='matrices'){
  metrics=metric('Rotation → symétriques',fmt(d.distance_rotation),'√2 |sin θ|')+metric('Dimension maximale',d.dimension,`Sous-espace diagonalisable réel de M${d.n}`)+metric('Ensemble det = 1',d.vide?'Vide':fmt(d.distance_ensemble),d.vide?'n impair : pas de distance finie':'Distance minimale à Sₙ : √n');
  details=`<p><b>Rotation Rθ</b>${matrixHtml(d.rotation)}</p><p><b>Projeté symétrique</b>${matrixHtml(d.symetrique)}</p>`;
  if(d.vide)details+='<p><b>Impossible :</b> une matrice antisymétrique de dimension impaire a un déterminant nul. La convention étendue donne inf ∅=+∞.</p>';
  else details+=`<p><b>Exemple antisymétrique A de déterminant 1</b>${matrixHtml(d.matrice)}</p><p>‖A‖F=${fmt(d.norme,6)} ≥ √n=${fmt(d.distance_ensemble,6)} ; det A=${fmt(d.determinant[0])}${Math.abs(d.determinant[1])>1e-10?' + '+fmt(d.determinant[1])+'i':''}. ${d.egalite?'Égalité : A*A=I.':'La déformation augmente la distance de cet exemple à Sₙ.'}</p><p>Valeurs propres de A*A : ${d.valeurs_propres.map(x=>fmt(x,4)).join(' ; ')}.</p>`;
  entries=[['symétrique',COLORS.green],['antisymétrique',COLORS.rose]];
 }else if(current==='produit'){
  metrics=metric('Maximum du produit',fmt(d.maximum,6),'Huit choix de signes')+metric('Produit au point choisi',fmt(d.valeur,6),`${fmt(100*d.valeur/d.maximum,1)} % du maximum`)+metric('Volume maximal de la boîte',fmt(d.volume_boite,6),'Pour |xyz| · axes parallèles');
  details=`<p><b>Fractions optimales xᵢ²/aᵢ² :</b> ${d.fractions.map(x=>fmt(x,4)).join(' ; ')}.</p><p>Un maximiseur : (${d.maximiseurs.at(-1).map(x=>fmt(x,5)).join(' ; ')}). Les autres sont obtenus par les huit combinaisons de signes. Le minimum est 0 sur les plans de coordonnées.</p><p>Le point mobile est (${d.point.map(x=>fmt(x,4)).join(' ; ')}), situé sur la surface. La boîte dorée représente l’exemple de volume maximal ; les points verts s’adaptent aux exposants.</p>`;
  entries=[['ellipsoïde',COLORS.ink],['maximiseurs',COLORS.green],['boîte de volume maximal',COLORS.gold],['point mobile',COLORS.rose]];
 }else if(current==='point'){
  metrics=metric('Minimum sur la surface',fmt(d.minimum.distance,6),d.minimum.cas_singulier?'Multiplicateur singulier traité':'Minimum global')+metric('Maximum sur la surface',fmt(d.maximum.distance,6),d.maximum.cas_singulier?'Multiplicateur singulier traité':'Maximum global')+metric('Distance au solide',fmt(d.distance_solide,6),d.interieur?'p appartient au solide':'p est extérieur');
  details=`<p>Niveau ellipsoïdal de p : ${fmt(d.niveau,5)} (intérieur si ≤1). Les points affichés sont des représentants en cas de multiplicité.</p><table><tr><th>Contrôle numérique</th><th>Minimum</th><th>Maximum</th></tr><tr><td>|‖u‖²−1|</td><td>${fmt(d.minimum.contrainte)}</td><td>${fmt(d.maximum.contrainte)}</td></tr><tr><td>Résidu de stationnarité</td><td>${fmt(d.minimum.stationnarite)}</td><td>${fmt(d.maximum.stationnarite)}</td></tr><tr><td>Plus petite valeur propre de la matrice de preuve</td><td>${fmt(d.minimum.borne_spectrale)}</td><td>${fmt(d.maximum.borne_spectrale)}</td></tr></table><p>Une matrice de preuve positive assure un extremum global. Le cas singulier a une borne spectrale nulle et peut admettre plusieurs extrema.</p>`;
  entries=[['surface',COLORS.ink],['p',COLORS.rose],['minimum',COLORS.green],['maximum',COLORS.gold]];
 }else{
  metrics=metric('Borne inférieure L',fmt(d.inferieure,7),'Fonctions support · direction unitaire')+metric('Borne supérieure U',fmt(d.superieure,7),'Distance entre deux points admissibles')+metric('Écart U − L',fmt(d.ecart),`${d.iterations} projections · ${d.converge?'critère atteint':'limite atteinte'}`);
  details=`<p><b>${d.separes?'Solides séparés : distance comprise entre L et U.':d.converge?'Distance compatible avec zéro à la précision du calcul.':'La séparation reste indéterminée à cette précision.'}</b> ${d.separes?'Les deux points se trouvent sur les surfaces.':'Le calcul concerne les solides, pas les surfaces emboîtées.'}</p><p>Normes des coordonnées ellipsoïdales des points : ${d.faisabilite.map(x=>fmt(x,10)).join(' ; ')} (admissibles si ≤1, à l’arrondi près).</p>`;
  if(d.separes)details+=`<p>Plan médian : (${d.normal.map(x=>fmt(x,4)).join(' ; ')})·x = ${fmt(d.niveau_plan,5)}. Marge garantie par cette direction : ${fmt(d.marge,7)}.</p><p>SVM : w=(${d.w_svm.map(x=>fmt(x,4)).join(' ; ')}), b=${fmt(d.b_svm,5)}. Quand l’écart U−L est petit, la marge approche la marge maximale.</p>`;
  details+='<p>Les bornes sont évaluées en virgule flottante, sans arithmétique d’intervalles. Leur écart contrôle l’optimisation numérique ; une séparation minuscule demande une précision adaptée.</p>';
  entries=[['E₁',COLORS.green],['E₂',COLORS.ink],['segment admissible',COLORS.gold],['plan médian',COLORS.rose]];
 }
 $('#metrics').innerHTML=metrics;$('#details').innerHTML=details;legend(entries);draw();
}
function selectLab(lab){clearTimeout(timer);serial++;current=lab;document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.lab===lab));$('#cours').hidden=lab!=='cours';$('#laboratoire').hidden=lab==='cours';$('#error').hidden=true;if(lab==='cours')return;const m=meta[lab];$('#lab-level').textContent=m[0];$('#lab-title').textContent=m[1];$('#lab-description').textContent=m[2];$('#plot-title').textContent=m[3];$('#plot-hint').textContent=['produit','point','paire'].includes(lab)?'Glissez pour tourner la vue':'Calculs locaux en Python';const lesson=bootstrap.lessons[lab==='approximation'?1:bootstrap.lessons.findIndex(x=>x.lab===lab)];$('#theory-text').innerHTML=lesson.texte;buildControls();calculate()}
function showLesson(i){const l=bootstrap.lessons[i];$('#lesson').innerHTML=`<span class="badge">${l.niveau}</span><h2>${l.titre}</h2>${l.texte}<button id="lesson-lab">Expérimenter dans le laboratoire</button>`;$('#lesson-lab').onclick=()=>selectLab(l.lab);document.querySelectorAll('#course-menu button').forEach((b,j)=>b.classList.toggle('active',j===i))}
function buildCourse(){bootstrap.lessons.forEach((l,i)=>{const b=document.createElement('button');b.textContent=l.titre;b.onclick=()=>showLesson(i);$('#course-menu').append(b)});showLesson(0);$('#exercises').innerHTML=bootstrap.exercises.map(([title,question,answer,lab],i)=>`<section class="exercise"><h3>${i+1}. ${title}</h3><p>${question}</p><details><summary>Voir la correction</summary><p>${answer}</p></details><button class="secondary" data-experience="${lab}">Vérifier par l’expérience</button></section>`).join('');document.querySelectorAll('[data-experience]').forEach(b=>b.onclick=()=>selectLab(b.dataset.experience));$('#sources').innerHTML=bootstrap.sources.map(s=>`<p><b>${s.url?`<a href="${s.url}" target="_blank" rel="noopener">${s.titre} ↗</a>`:s.titre}</b><br>${s.texte}</p>`).join('')}
// Illustrations Canvas : l'optimisation reste entièrement effectuée en Python.
const canvas=$('#scene'), ctx=canvas.getContext('2d');let W,H;
function setup(){W=canvas.clientWidth;H=canvas.clientHeight;const d=window.devicePixelRatio||1;canvas.width=W*d;canvas.height=H*d;ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,W,H);ctx.font='12px Segoe UI';ctx.lineWidth=1;ctx.fillStyle=COLORS.ink;ctx.lineJoin='round'}
function line(points,color,width=1,dash=[]){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.setLineDash(dash);ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.stroke();ctx.setLineDash([])}
function text(t,x,y,color=COLORS.grey,size=11){ctx.fillStyle=color;ctx.font=`${size}px Segoe UI`;ctx.fillText(t,x,y)}
function dot(p,color,r=4){ctx.fillStyle=color;ctx.beginPath();ctx.arc(p[0],p[1],r,0,2*Math.PI);ctx.fill()}
function graph(rect,xrange,yrange){const [x,y,w,h]=rect;const project=(a,b)=>[x+(a-xrange[0])/(xrange[1]-xrange[0])*w,y+h-(b-yrange[0])/(yrange[1]-yrange[0])*h];for(let i=0;i<=4;i++){let xx=xrange[0]+(xrange[1]-xrange[0])*i/4, yy=yrange[0]+(yrange[1]-yrange[0])*i/4;line([[x+i*w/4,y],[x+i*w/4,y+h]],COLORS.line);line([[x,y+i*h/4],[x+w,y+i*h/4]],COLORS.line);text(fmt(xx,2),x+i*w/4-8,y+h+18);text(fmt(yy,2),x-40,y+h-i*h/4+4)}return project}
function drawApprox(){const d=result, split=H*.59;const all=[...d.cos,...d.projection,...d.uniforme,...d.trial];const low=Math.min(...all)-.05, high=Math.max(...all)+.05;const P=graph([52,30,W-78,split-75],[0,d.L],[low,high]);[[d.cos,COLORS.ink],[d.projection,COLORS.green],[d.uniforme,COLORS.gold],[d.trial,COLORS.rose]].forEach(([ys,col])=>line(d.x.map((x,i)=>P(x,ys[i])),col,2));text('t',W-20,split-24);const hist=d.descente, amin=Math.min(...hist.map(x=>x[0]),d.affine_optimum[0])-.1, amax=Math.max(...hist.map(x=>x[0]),d.affine_optimum[0])+.1,bmin=Math.min(...hist.map(x=>x[1]),d.affine_optimum[1])-.1,bmax=Math.max(...hist.map(x=>x[1]),d.affine_optimum[1])+.1;const G=graph([52,split+28,W*.52-65,H-split-67],[amin,amax],[bmin,bmax]);text('Descente dans le plan (a,b)',52,split+14,COLORS.ink,12);const [ao,bo]=d.affine_optimum,[h0,h1]=d.hessienne;for(const radius of [.008,.025,.07,.2]){let pts=[];const det=h0[0]*h1[1]-h0[1]**2;for(let i=0;i<=120;i++){let t=i*2*Math.PI/120;let da=Math.sqrt(2*radius/h0[0])*Math.cos(t)-h0[1]/h0[0]*Math.sqrt(2*radius*h0[0]/det)*Math.sin(t),db=Math.sqrt(2*radius*h0[0]/det)*Math.sin(t);pts.push(G(ao+da,bo+db))}ctx.save();ctx.beginPath();ctx.rect(52,split+28,W*.52-65,H-split-67);ctx.clip();line(pts,COLORS.line);ctx.restore()}line(hist.map(x=>G(x[0],x[1])),COLORS.rose,2);dot(G(ao,bo),COLORS.green);text('a',W*.52-6,H-16);text('b',24,split+36);const residual=d.cos.map((y,i)=>y-d.projection[i]), extent=Math.max(.005,...residual.map(Math.abs));const E=graph([W*.58,split+28,W*.42-29,H-split-67],[0,d.L],[-extent*1.15,extent*1.15]);line(d.x.map((x,i)=>E(x,residual[i])),COLORS.green,2);text('Résidu cos − p',W*.58,split+14,COLORS.ink,12)}
function drawMatrix(){const d=result, x0=W*.12,y0=70, cell=Math.min(44,W/13);function grid(m,x,y,title){text(title,x,y-20,COLORS.ink,13);m.forEach((row,i)=>row.forEach(([v],j)=>{ctx.fillStyle=v<0?'#f3dedf':'#dfefe5';ctx.fillRect(x+j*cell,y+i*cell,cell-3,cell-3);text(fmt(v,2),x+j*cell+8,y+i*cell+cell*.58,COLORS.ink,12)}))}grid(d.symetrique,x0,y0,'S = (R + Rᵀ)/2');grid(d.antisymetrique,W*.56,y0,'A = (R − Rᵀ)/2');text('R = S + A     ·     ⟨S,A⟩F = 0',x0,y0+cell*3+28,COLORS.green,13);const top=y0+cell*3+70;const P=graph([52,top,W-82,H-top-40],[-180,180],[0,1.5]);let pts=[];for(let t=-180;t<=180;t+=2)pts.push(P(t,Math.SQRT2*Math.abs(Math.sin(t*Math.PI/180))));line(pts,COLORS.green,2);dot(P(states.matrices.theta,d.distance_rotation),COLORS.rose,5);text('Distance de la rotation à S₃ selon θ',52,top-15,COLORS.ink,12)}
const add=(a,b)=>a.map((x,i)=>x+b[i]), sub=(a,b)=>a.map((x,i)=>x-b[i]), scale=(a,s)=>a.map(x=>x*s), dot3=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0), norm=a=>Math.hypot(...a), cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]], mul=(b,u)=>b.map(row=>dot3(row,u));
function geometry(){const d=result;if(current==='produit')return [{centre:[0,0,0],B:d.axes.map((x,i)=>[0,1,2].map(j=>j===i?x:0)),color:COLORS.ink}];if(current==='point')return [{centre:d.centre,B:d.B,color:COLORS.ink}];return [{...d.e1,color:COLORS.green},{...d.e2,color:COLORS.ink}]}
function draw3D(){const d=result, es=geometry();let pts=[];es.forEach(e=>{for(let j=-8;j<=8;j++){let lat=j*Math.PI/16;for(let i=0;i<32;i++){let lon=i*Math.PI/16;pts.push(add(e.centre,mul(e.B,[Math.cos(lat)*Math.cos(lon),Math.cos(lat)*Math.sin(lon),Math.sin(lat)])))}}});if(current==='point')pts.push(d.point);let center=[0,1,2].map(i=>(Math.max(...pts.map(p=>p[i]))+Math.min(...pts.map(p=>p[i])))/2);let radius=Math.max(...pts.map(p=>norm(sub(p,center))));function raw(p){let [x,y,z]=sub(p,center),cy=Math.cos(camera.yaw),sy=Math.sin(camera.yaw),cp=Math.cos(camera.pitch),sp=Math.sin(camera.pitch);let xx=cy*x-sy*y,yy=sy*x+cy*y;return [xx,cp*z-sp*yy,cp*yy+sp*z]}let projected=pts.map(raw),xmin=Math.min(...projected.map(p=>p[0])),xmax=Math.max(...projected.map(p=>p[0])),ymin=Math.min(...projected.map(p=>p[1])),ymax=Math.max(...projected.map(p=>p[1])),factor=Math.min((W-100)/(xmax-xmin),(H-90)/(ymax-ymin));function P(p){let [x,y,z]=raw(p);return [W/2+factor*(x-(xmin+xmax)/2),H/2-factor*(y-(ymin+ymax)/2),z]}
 const segments=[];function seg(a,b,col,width=1){let A=P(a),B=P(b);segments.push({pts:[A,B],depth:(A[2]+B[2])/2,col,width})}
 const grid=radius*.9;for(let i=-3;i<=3;i++){let v=i*grid/3;seg(add(center,[-grid,v,-radius*.6]),add(center,[grid,v,-radius*.6]),COLORS.line);seg(add(center,[v,-grid,-radius*.6]),add(center,[v,grid,-radius*.6]),COLORS.line)}
 es.forEach(e=>{const world=u=>add(e.centre,mul(e.B,u));for(let j=-3;j<=3;j++){let lat=j*Math.PI/8;for(let i=0;i<60;i++){let a=i*2*Math.PI/60,b=(i+1)*2*Math.PI/60;seg(world([Math.cos(lat)*Math.cos(a),Math.cos(lat)*Math.sin(a),Math.sin(lat)]),world([Math.cos(lat)*Math.cos(b),Math.cos(lat)*Math.sin(b),Math.sin(lat)]),e.color)}}for(let j=0;j<12;j++){let lon=j*Math.PI/6;for(let i=0;i<30;i++){let a=-Math.PI/2+i*Math.PI/30,b=a+Math.PI/30;seg(world([Math.cos(a)*Math.cos(lon),Math.cos(a)*Math.sin(lon),Math.sin(a)]),world([Math.cos(b)*Math.cos(lon),Math.cos(b)*Math.sin(lon),Math.sin(b)]),e.color)}}for(let i=0;i<3;i++){const u=[0,0,0];u[i]=1;seg(world(scale(u,-1)),world(u),e.color,1.5)}});
 if(current==='produit'){const corners=[];for(const x of [-1,1])for(const y of [-1,1])for(const z of [-1,1])corners.push(d.boite.map((v,i)=>v*[x,y,z][i]));corners.forEach((a,i)=>corners.forEach((b,j)=>{if(i<j&&a.filter((v,k)=>v!==b[k]).length===1)seg(a,b,COLORS.gold,2)}))}
 if(current==='point'){seg(d.point,d.minimum.point,COLORS.green,3);seg(d.point,d.maximum.point,COLORS.gold,3)}
 if(current==='paire'){seg(d.p1,d.p2,COLORS.gold,4);if(d.separes){const n=d.normal,mid0=scale(add(d.p1,d.p2),.5),mid=add(mid0,scale(n,d.niveau_plan-dot3(n,mid0))),base=Math.abs(n[2])<.8?[0,0,1]:[0,1,0],v0=cross(n,base),v=scale(v0,1/norm(v0)),w=cross(n,v),s=radius*.6;let corners=[[-1,-1],[1,-1],[1,1],[-1,1]].map(([a,b])=>P(add(mid,add(scale(v,a*s),scale(w,b*s)))));ctx.fillStyle='#b6637512';ctx.beginPath();corners.forEach((p,i)=>i?ctx.lineTo(...p.slice(0,2)):ctx.moveTo(...p.slice(0,2)));ctx.closePath();ctx.fill();for(let k=0;k<4;k++)line([corners[k],corners[(k+1)%4]],'#b6637560',1,[4,4])}}
 segments.sort((a,b)=>b.depth-a.depth).forEach(s=>line(s.pts,s.col,s.width));es.forEach((e,i)=>{dot(P(e.centre),e.color,3);text(es.length>1?'c'+(i+1):'c',P(e.centre)[0]+7,P(e.centre)[1]-4,e.color)});
 if(current==='produit'){d.maximiseurs.forEach(p=>dot(P(p),COLORS.green,4));dot(P(d.point),COLORS.rose,6)}else if(current==='point'){[[d.point,'p',COLORS.rose],[d.minimum.point,'min',COLORS.green],[d.maximum.point,'max',COLORS.gold]].forEach(([p,l,c])=>{dot(P(p),c,5);text(l,P(p)[0]+8,P(p)[1]-6,c,12)})}else{[[d.p1,'x',COLORS.green],[d.p2,'y',COLORS.ink]].forEach(([p,l,c])=>{dot(P(p),c,5);text(l,P(p)[0]+7,P(p)[1]-7,c,12)});text(d.separes?`L ≤ d ≤ U   ·   U − L = ${fmt(d.ecart)}`:'Distance des solides · compatible avec zéro si U est petit',20,25,COLORS.ink,12)}
 text('Vue orthographique · glissez pour tourner',20,H-15,COLORS.grey,10);
}
function draw(){if(!result||current==='cours')return;setup();if(current==='approximation')drawApprox();else if(current==='matrices')drawMatrix();else draw3D()}
let drag;canvas.onpointerdown=e=>{if(!['produit','point','paire'].includes(current))return;drag=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(!drag)return;camera.yaw+=(e.clientX-drag[0])*.009;camera.pitch=Math.max(-1.3,Math.min(1.3,camera.pitch+(e.clientY-drag[1])*.009));drag=[e.clientX,e.clientY];draw()};canvas.onpointerup=canvas.onpointercancel=()=>drag=null;new ResizeObserver(draw).observe(canvas);
$('#reset').onclick=()=>{states[current]=clone(defaults[current]);buildControls();calculate()};$('#read-course').onclick=()=>{let lab=current;selectLab('cours');showLesson(lab==='approximation'?1:bootstrap.lessons.findIndex(x=>x.lab===lab))};$('#export').onclick=()=>{if(!result)return;const content=JSON.stringify({experience:current,parametres:states[current],resultats:result,convention:'Calcul en virgule flottante. Pour deux ellipsoïdes : distance des solides.'},null,2),url=URL.createObjectURL(new Blob([content],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`optimisation-${current}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>selectLab(b.dataset.lab));
fetch('/api/bootstrap').then(r=>{if(!r.ok)throw Error('Le serveur local ne répond pas.');return r.json()}).then(data=>{bootstrap=data;buildCourse();selectLab('approximation')}).catch(e=>{$('#error').textContent=e.message;$('#error').hidden=false});
