'use strict';
// Figures du laboratoire : les données viennent du moteur, jamais d'un calcul
// algébrique approché du navigateur. Une caméra ne change que la projection.
const sceneColors={green:'#216858',gold:'#c99435',rose:'#b8586f',mint:'#8ec8b0',ink:'#163b43',blue:'#487eac',purple:'#8665a6'};
function sceneColor(value){return sceneColors[value]||sceneColors.green;}
function fillObjects(target,objects){
 target.replaceChildren();if(!objects?.length){target.hidden=true;return;}target.hidden=false;
 const title=elem('h3','Les objets de cette expérience');target.append(title);const dl=elem('dl');
 for(const o of objects){dl.append(elem('dt',o.symbol),elem('dd',o.meaning));}target.append(dl);
}
function renderPedagogy(r){
 const p=r.pedagogy||{};$('mission').replaceChildren();$('mission').hidden=!p.mission;
 if(p.mission)$('mission').append(elem('span','LA QUESTION À RÉSOUDRE','eyebrow'),elem('p',p.mission));
 fillObjects($('objects'),p.objects);
 $('reading').replaceChildren();$('reading').hidden=!p.reading?.length;
 if(p.reading?.length){$('reading').append(elem('h3','Comment lire l’expérience'));for(const s of p.reading)$('reading').append(elem('p',s));}
 $('reasoning').replaceChildren();$('reasoning').hidden=!p.proof?.length&&!p.questions?.length;
 if(p.proof?.length){const proof=elem('section');proof.append(elem('span','PASSER À LA PREUVE','eyebrow'),elem('h3','Une construction à justifier'));const ol=elem('ol');for(const s of p.proof)ol.append(elem('li',s));proof.append(ol);$('reasoning').append(proof);}
 if(p.questions?.length){const ask=elem('section',undefined,'questions');ask.append(elem('span','AVANT DE REGARDER LA CORRECTION','eyebrow'),elem('h3','À vous de conclure'));const ol=elem('ol');for(const s of p.questions)ol.append(elem('li',s));ask.append(ol);$('reasoning').append(ask);}
}
function setupSceneCanvas(canvas){const dpr=window.devicePixelRatio||1,w=canvas.clientWidth||600,h=canvas.clientHeight||380;canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);const c=canvas.getContext('2d');c.scale(dpr,dpr);c.clearRect(0,0,w,h);return {c,w,h};}
function arrow(c,a,b,color,width=2,label){const dx=b[0]-a[0],dy=b[1]-a[1],angle=Math.atan2(dy,dx),length=Math.hypot(dx,dy);if(length<1)return;c.strokeStyle=c.fillStyle=sceneColor(color);c.lineWidth=width;c.beginPath();c.moveTo(...a);c.lineTo(...b);c.stroke();c.beginPath();c.moveTo(...b);c.lineTo(b[0]-9*Math.cos(angle-.42),b[1]-9*Math.sin(angle-.42));c.lineTo(b[0]-9*Math.cos(angle+.42),b[1]-9*Math.sin(angle+.42));c.closePath();c.fill();if(label){c.save();c.font='12px Segoe UI';c.textAlign='center';c.fillText(label,(a[0]+b[0])/2-dy/length*12,(a[1]+b[1])/2+dx/length*12);c.restore();}}
function sceneCard(s){const card=elem('section',undefined,'scene-card scene-'+s.kind);const head=elem('div',undefined,'scene-heading');head.append(elem('span','OBSERVATOIRE','eyebrow'),elem('h3',s.title));if(s.description)head.append(elem('p',s.description));card.append(head);return card;}
function renderScenes(scenes){
 $('scenes').replaceChildren();$('scenes').hidden=!scenes?.length;
 for(const s of scenes||[]){const card=sceneCard(s);$('scenes').append(card);
  if(s.kind==='jacobi'){renderJacobi(card,s);continue;}
  if(s.kind==='jordan'){renderJordan(card,s);continue;}
  const canvas=elem('canvas');canvas.setAttribute('role','img');canvas.setAttribute('aria-label',s.title);card.append(canvas);canvas._scene=s;
  const footer=elem('div',undefined,'scene-footer');card.append(footer);
  if(s.kind==='oscillators'){canvas._frame=0;oscillatorControls(card,canvas,s,footer);footer.append(elem('p','Les déplacements qᵢ sont représentés sur des axes séparés. Les liaisons pointillées indiquent le couplage du Hamiltonien ; elles ne décrivent pas un ressort de potentiel (qᵢ−qⱼ)².'));}
  else if(s.kind==='space3d'){canvas._camera={yaw:.65,pitch:-.38};let drag;canvas.onpointerdown=e=>{drag=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(!drag)return;canvas._camera.yaw+=(e.clientX-drag[0])*.009;canvas._camera.pitch=Math.max(-1.4,Math.min(1.4,canvas._camera.pitch+(e.clientY-drag[1])*.009));drag=[e.clientX,e.clientY];drawScene(canvas);};canvas.onpointerup=()=>drag=null;canvas.onpointercancel=()=>drag=null;const reset=elem('button','Rétablir la vue','secondary');reset.onclick=()=>{canvas._camera={yaw:.65,pitch:-.38};drawScene(canvas);};const camera=elem('div',undefined,'camera-controls');for(const [label,axis,increment]of [['Tourner à gauche','yaw',-.35],['Tourner à droite','yaw',.35],['Incliner la vue','pitch',.2]]){const b=elem('button',label,'secondary');b.onclick=()=>{canvas._camera[axis]+=increment;drawScene(canvas);};camera.append(b);}camera.append(reset);footer.append(elem('p','Faites glisser la figure ou utilisez les boutons pour tourner la vue. La caméra ne change que la projection sur l’écran.'),camera);}
  else if(s.kind==='matching'){canvas._matching=0;const select=elem('input');select.type='range';select.min=0;select.max=Math.max(0,(s.matchings?.length||1)-1);select.step=1;select.value=0;select.setAttribute('aria-label','Appariement du pfaffien');const label=elem('p');const paint=()=>{canvas._matching=Number(select.value);const m=s.matchings[canvas._matching];label.textContent=`Appariement ${canvas._matching+1}/${s.matchings.length} · signe ${m.sign} · produit ${m.product} · contribution ${m.term}`;drawScene(canvas);};select.oninput=paint;footer.append(select,label);paint();}
  else if(['graph','network','weights','krylov'].includes(s.kind)){canvas._selected=null;canvas.onpointermove=e=>{const r=canvas.getBoundingClientRect(),point=[e.clientX-r.left,e.clientY-r.top];const nearest=(canvas._nodePositions||[]).find(n=>Math.hypot(point[0]-n.x,point[1]-n.y)<22);if(nearest?.id!==canvas._selected){canvas._selected=nearest?.id??null;drawScene(canvas);}};canvas.onpointerleave=()=>{canvas._selected=null;drawScene(canvas);};footer.append(elem('p',s.hint||graphHint(s)));if(s.frames?.length){canvas._frame=0;const controls=elem('div',undefined,'frame-controls'),slider=elem('input'),button=elem('button','Animer','secondary'),caption=elem('span');slider.type='range';slider.min=0;slider.max=s.frames.length-1;slider.step=1;slider.value=0;slider.setAttribute('aria-label','Étape de l’évolution');const paint=()=>{canvas._frame=Number(slider.value);const f=s.frames[canvas._frame];caption.textContent=f.step!==undefined?'Pas '+f.step:'Temps '+fmt(f.time);drawScene(canvas);};let playing=false,last=0;const tick=t=>{if(!playing||!canvas.isConnected)return;if(t-last>180){slider.value=(Number(slider.value)+1)%s.frames.length;last=t;paint();}requestAnimationFrame(tick);};button.onclick=()=>{playing=!playing;button.textContent=playing?'Suspendre':'Animer';if(playing)requestAnimationFrame(tick);};slider.oninput=()=>{playing=false;button.textContent='Animer';paint();};controls.append(button,slider,caption);card.insertBefore(controls,footer);paint();}}
  else{const legend=elem('div',undefined,'legend');for(const curve of s.curves||[]){const item=elem('span');item.append(elem('i',undefined,curve.color||'green'),document.createTextNode(curve.label));legend.append(item);}if(legend.childNodes.length)footer.append(legend);footer.append(elem('p',s.hint||'Les courbes illustrent les données calculées ; les identités sont vérifiées exactement dans les certificats.'));}
  drawScene(canvas);
 }
}
function drawScene(canvas){
 const s=canvas._scene;if(!s)return;if(s.kind==='space3d')drawSpace3d(canvas,s);else if(s.kind==='phase')drawPhase(canvas,s);else if(s.kind==='oscillators')drawOscillators(canvas,s);else drawGraph(canvas,s);
}
function drawSpace3d(canvas,s){
 const {c,w,h}=setupSceneCanvas(canvas),cam=canvas._camera||{yaw:.65,pitch:-.38};const points=s.points||[],scale=Math.max(1,...points.flatMap(p=>[Math.abs(Number(p.x)),Math.abs(Number(p.y)),Math.abs(Number(p.z))]));
 const unit=Math.min(w,h)*.31/scale;
 const project=p=>{const x=Number(p.x),y=Number(p.y),z=Number(p.z),u=x*Math.cos(cam.yaw)-y*Math.sin(cam.yaw),v=x*Math.sin(cam.yaw)+y*Math.cos(cam.yaw);return [w/2+u*unit,h/2+(z*Math.cos(cam.pitch)-v*Math.sin(cam.pitch))*-unit,v*Math.cos(cam.pitch)+z*Math.sin(cam.pitch)];};
 const origin=project({x:0,y:0,z:0});for(let i=0;i<3;i++){const p={x:0,y:0,z:0};p[['x','y','z'][i]]=scale*1.2;const end=project(p);arrow(c,origin,end,'mint',1.2);c.fillStyle=sceneColors.ink;c.font='12px Segoe UI';c.fillText((s.axes||['x','y','z'])[i],end[0]+8,end[1]);}
 const pp=points.map(project);const faces=(s.faces||[]).map((f,i)=>({f:f.indices||f,color:f.color||['green','gold','rose'][i%3]}));faces.sort((a,b)=>a.f.reduce((v,i)=>v+pp[i][2],0)-b.f.reduce((v,i)=>v+pp[i][2],0));for(const {f,color} of faces){if(!f.length)continue;c.beginPath();f.forEach((n,i)=>i?c.lineTo(pp[n][0],pp[n][1]):c.moveTo(pp[n][0],pp[n][1]));c.closePath();c.globalAlpha=.12;c.fillStyle=sceneColor(color);c.fill();c.globalAlpha=1;}
 for(const e of s.edges||[]){const a=pp[e.from],b=pp[e.to];if(!a||!b)continue;c.strokeStyle=sceneColor(e.color);c.lineWidth=2;c.beginPath();c.moveTo(a[0],a[1]);c.lineTo(b[0],b[1]);c.stroke();}
 const order=points.map((p,i)=>({p,i})).sort((a,b)=>pp[a.i][2]-pp[b.i][2]);for(const {p,i} of order){c.fillStyle=sceneColor(p.color);c.beginPath();c.arc(pp[i][0],pp[i][1],p.label?4:2.5,0,Math.PI*2);c.fill();if(p.label){c.font='12px Segoe UI';c.fillText(p.label,pp[i][0]+7,pp[i][1]-7);}}
}
function drawGraph(canvas,s){
 const {c,w,h}=setupSceneCanvas(canvas);let nodes=s.nodes||[];const selected=canvas._selected;
 if(s.valueLabel)nodes=nodes.map(n=>({...n,color:Number(n.value)<0?'rose':n.color||'green'}));
 if(s.kind==='weights')nodes=nodes.map(n=>({...n,label:n.weight!==undefined?String(n.weight):n.label,note:n.monomial||n.note}));
 if(s.frames?.length){const values=s.frames[canvas._frame||0].values;nodes=nodes.map((n,i)=>({...n,value:Number(values[i]),color:Number(values[i])<0?'rose':n.color||'green'}));}
 if(s.kind==='matching'&&s.matchings?.length){s={...s,edges:s.matchings[canvas._matching||0].pairs.map(([from,to])=>({from,to,color:'gold'}))};}
 const coords=nodes.map((n,i)=>[Number(n.x??Math.cos(i*2*Math.PI/nodes.length)),Number(n.y??Math.sin(i*2*Math.PI/nodes.length))]);const xs=coords.map(p=>p[0]),ys=coords.map(p=>p[1]),loX=Math.min(...xs),hiX=Math.max(...xs),loY=Math.min(...ys),hiY=Math.max(...ys);const unit=Math.min((w-110)/(hiX-loX||1),(h-110)/(hiY-loY||1)),spanX=(hiX-loX)*unit,spanY=(hiY-loY)*unit,map=(p)=>[w/2+(p[0]-(loX+hiX)/2)*unit,h/2+(p[1]-(loY+hiY)/2)*unit];
 const positions=coords.map(map);const ids=new Map(nodes.map((n,i)=>[n.id??i,i]));canvas._nodePositions=nodes.map((n,i)=>({id:n.id??i,x:positions[i][0],y:positions[i][1]}));
 for(const e of s.edges||[]){const from=e.from??e.source,to=e.to??e.target,i=ids.get(from),j=ids.get(to);if(i===undefined||j===undefined)continue;const a=positions[i],b=positions[j];c.globalAlpha=selected!==null&&selected!==from&&selected!==to?.15:1;
  const color=e.color||(s.kind==='matching'?'gold':'mint'),width=Math.min(6,1.2+Math.abs(Number(e.weight)||0)*2);
  if(i===j){c.strokeStyle=sceneColor(color);c.lineWidth=width;c.beginPath();c.arc(a[0]+20,a[1]-20,19,.25,Math.PI*1.8);c.stroke();if(e.label){c.font='11px Segoe UI';c.fillStyle=sceneColors.ink;c.fillText(e.label,a[0]+36,a[1]-30);}continue;}
  const length=Math.hypot(b[0]-a[0],b[1]-a[1]),r=23;const p=[a[0]+(b[0]-a[0])*r/length,a[1]+(b[1]-a[1])*r/length],q=[b[0]-(b[0]-a[0])*r/length,b[1]-(b[1]-a[1])*r/length];
  if(s.kind==='matching'||s.directed===false){c.lineWidth=width;c.strokeStyle=sceneColor(color);c.beginPath();c.moveTo(...p);c.lineTo(...q);c.stroke();if(e.label){c.fillStyle=sceneColors.ink;c.font='12px Segoe UI';c.textAlign='center';c.fillText(e.label,(p[0]+q[0])/2,(p[1]+q[1])/2-6);}}
  else{const label=e.label||e.coefficient||(e.weight!==undefined?String(e.weight):'');const reverse=(s.edges||[]).some(other=>(other.from??other.source)===to&&(other.to??other.target)===from);if(reverse){const control=[(p[0]+q[0])/2-(q[1]-p[1])/length*22,(p[1]+q[1])/2+(q[0]-p[0])/length*22];c.strokeStyle=c.fillStyle=sceneColor(color);c.lineWidth=width;c.beginPath();c.moveTo(...p);c.quadraticCurveTo(...control,...q);c.stroke();const angle=Math.atan2(q[1]-control[1],q[0]-control[0]);c.beginPath();c.moveTo(...q);c.lineTo(q[0]-9*Math.cos(angle-.4),q[1]-9*Math.sin(angle-.4));c.lineTo(q[0]-9*Math.cos(angle+.4),q[1]-9*Math.sin(angle+.4));c.closePath();c.fill();if(label){c.font='11px Segoe UI';c.textAlign='center';c.fillText(label,(p[0]+2*control[0]+q[0])/4-(q[1]-p[1])/length*8,(p[1]+2*control[1]+q[1])/4+(q[0]-p[0])/length*8);}}else arrow(c,p,q,color,width,label);}
 }
 c.globalAlpha=1;c.textAlign='center';const amplitude=Math.max(.01,...nodes.map(n=>Math.abs(Number(n.value)||0)));for(let i=0;i<nodes.length;i++){const n=nodes[i],p=positions[i],value=Number(n.value);const radius=Number.isFinite(value)?Math.min(34,13+20*Math.sqrt(Math.abs(value)/amplitude)):22;c.beginPath();c.arc(p[0],p[1],radius,0,Math.PI*2);c.fillStyle=selected===(n.id??i)?sceneColors.gold:sceneColor(n.color||'green');c.globalAlpha=Number.isFinite(value)?.3+.7*Math.abs(value)/amplitude:1;c.fill();c.globalAlpha=1;c.strokeStyle='#fff';c.lineWidth=3;c.stroke();c.fillStyle='#fff';c.font='bold 12px Segoe UI';c.fillText(n.label??String(n.id??i),p[0],p[1]+4);if(n.note||n.value!==undefined){c.fillStyle=sceneColors.ink;c.font='11px Segoe UI';c.fillText(n.note??fmt(n.value),p[0],p[1]+radius+18);}}
}
function drawPhase(canvas,s){
 const curves=(s.curves||[]).map(curve=>({label:curve.label,color:curve.color||'green',kind:'line',x:curve.points.map(p=>Number(p[0])),y:curve.points.map(p=>Number(p[1]))}));
 for(const p of s.markers||[])curves.push({label:p.label,color:p.color||'rose',kind:'dots',x:[p.x],y:[p.y]});
 draw(canvas,{title:s.title,xlabel:s.xlabel||'q',ylabel:s.ylabel||'p',equal:s.equal??!s.xlabel?.includes('θ'),series:curves});
}
function renderJacobi(card,s){
 const box=elem('div',undefined,'jacobi-columns');const entries=s.contributions||[];
 entries.forEach((v,i)=>{const item=matrixCard(v.label,v.matrix||v.entries,v.note);item.dataset.term=i;item.prepend(elem('span',['01','02','03'][i]||String(i+1),'term-number'));box.append(item);});card.append(box);
 const sum=elem('div',undefined,'jacobi-sum');sum.append(elem('span','Trois termes peuvent être non nuls.'),elem('b','Leur somme est exactement nulle.'));card.append(sum);
 if(s.expansion?.length){const words=[...new Set(s.expansion.map(t=>t.word))],terms=elem('div',undefined,'word-expansion'),button=elem('button','Révéler les annulations','secondary'),controls=elem('div',undefined,'word-controls'),label=elem('label','Comparer un mot de Jacobi'),select=elem('select'),caption=elem('p',undefined,'word-caption');select.id='jacobi-word-'+document.querySelectorAll('.scene-jacobi').length;label.htmlFor=select.id;for(const word of words)select.append(new Option(word,word));controls.append(label,select);let show=false;const paint=()=>{terms.replaceChildren();for(const term of s.expansion){const x=elem('span',(term.sign<0?'−':'+')+' '+term.word,'word-term');x.classList.toggle('chosen-word',term.word===select.value);if(show)x.classList.add('cancelled');terms.append(x);}caption.textContent='Le produit '+select.value+' apparaît une fois avec + et une fois avec −. On annule deux mots identiques, sans permuter les matrices.';button.textContent=show?'Retrouver les douze termes':'Révéler les annulations';};select.onchange=paint;button.onclick=()=>{show=!show;paint();};card.append(controls,terms,caption,button);paint();}
}
function renderJordan(card,s){
 const box=elem('div',undefined,'jordan-chains');for(const chain of s.chains||[]){const row=elem('div',undefined,'jordan-chain');row.append(elem('b',chain.label||'λ = '+chain.lambda));const list=elem('div');for(let i=0;i<chain.length;i++){const node=elem('span','v'+(i+1));list.append(node);if(i<chain.length-1)list.append(elem('i','←'));}row.append(list,elem('p',chain.description||'(A−λI)v₁=0 ; (A−λI)vⱼ=vⱼ₋₁.'));box.append(row);}card.append(box,elem('p','Chaque chaîne donne un bloc. Compter les vecteurs nouveaux dans les noyaux successifs permet de reconstruire leurs longueurs.','scene-caption'));
}
function drawHero(){const canvas=$('hero-canvas');if(!canvas)return;canvas._camera={yaw:.58,pitch:-.3};canvas._scene={kind:'space3d',axes:['x','y','z'],points:[],edges:[],faces:[]};const s=canvas._scene;for(const [color,shift]of [['mint',0],['gold',.32]]){const start=s.points.length;for(let i=0;i<8;i++){const x=(i&1)-.5,y=((i>>1)&1)-.5,z=((i>>2)&1)-.5;s.points.push({x:x+.8*y+shift,y:y+.4*z,z,color});}for(let i=0;i<8;i++)for(const b of [1,2,4])if(!(i&b))s.edges.push({from:start+i,to:start+(i|b),color});s.faces.push({indices:[start,start+1,start+3,start+2],color});}drawSpace3d(canvas,s);}
function oscillatorControls(card,canvas,s,footer){
 const controls=elem('div',undefined,'frame-controls'),slider=elem('input'),button=elem('button','Animer les oscillateurs','secondary'),caption=elem('span');slider.type='range';slider.min=0;slider.max=s.frames.length-1;slider.step=1;slider.value=0;slider.setAttribute('aria-label','Instant des oscillateurs');let playing=false,last=0;
 const paint=()=>{canvas._frame=Number(slider.value);caption.textContent='t = '+fmt(s.frames[canvas._frame].time);drawScene(canvas);};const tick=t=>{if(!playing||!canvas.isConnected)return;if(t-last>120){slider.value=(Number(slider.value)+1)%s.frames.length;last=t;paint();}requestAnimationFrame(tick);};button.onclick=()=>{playing=!playing;button.textContent=playing?'Suspendre les oscillateurs':'Animer les oscillateurs';if(playing)requestAnimationFrame(tick);};slider.oninput=()=>{playing=false;button.textContent='Animer les oscillateurs';paint();};controls.append(button,slider,caption);card.insertBefore(controls,footer);paint();
}
function drawOscillators(canvas,s){
 const {c,w,h}=setupSceneCanvas(canvas),frame=s.frames[canvas._frame||0],n=s.modes||frame.values.length,max=Math.max(.01,...s.frames.flatMap(f=>f.values.map(v=>Math.abs(v)))),positions=[];
 for(let i=0;i<n;i++){const y=55+i*(h-100)/(n-1||1),zero=w*.58,x=zero+Number(frame.values[i])/max*w*.24,start=w*.1;positions.push([x,y]);c.strokeStyle='#d6ddd4';c.lineWidth=1;c.beginPath();c.moveTo(start,y+27);c.lineTo(w*.9,y+27);c.stroke();c.beginPath();c.moveTo(zero,y+21);c.lineTo(zero,y+33);c.stroke();c.strokeStyle=sceneColor(['green','gold','rose'][i]);c.lineWidth=2;c.beginPath();c.moveTo(start,y);const end=x-20;for(let k=0;k<23;k++)c.lineTo(start+(end-start)*k/22,y+(k===0||k===22?0:k%2?8:-8));c.stroke();c.fillStyle=sceneColor(['green','gold','rose'][i]);c.fillRect(x-20,y-19,40,38);c.fillStyle='#fff';c.font='bold 13px Segoe UI';c.textAlign='center';c.fillText('q'+(i+1),x,y+5);c.fillStyle=sceneColors.ink;c.font='12px Segoe UI';c.textAlign='right';c.fillText('q'+(i+1)+' = '+fmt(frame.values[i])+(frame.momenta?' · p'+(i+1)+' = '+fmt(frame.momenta[i]):''),w*.96,y-30);if(frame.momenta){const p=Number(frame.momenta[i]);arrow(c,[x,y+44],[x+Math.sign(p)*Math.min(60,Math.abs(p)*25),y+44],'rose',1.5);}c.fillStyle=sceneColors.mint;c.fillRect(start-8,y-24,7,49);}
 c.setLineDash([5,5]);for(let i=1;i<n;i++){c.strokeStyle=sceneColors.rose;c.lineWidth=1.5;c.beginPath();c.moveTo(positions[i-1][0],positions[i-1][1]+20);c.lineTo(positions[i][0],positions[i][1]-20);c.stroke();}c.setLineDash([]);
}

function graphHint(s){
 if(s.directed===false)return 'Survolez un sommet pour isoler ses arêtes. Les nombres sur les arêtes sont les conductances ; vert et rose distinguent les valeurs positives et négatives aux sommets.';
 if(s.kind==='weights')return 'Survolez un poids pour isoler les actions de E et F. Le monôme figure sous le sommet ; les flèches portent leurs coefficients de dérivation.';
 if(s.frames)return 'Les états montrent la loi p au pas choisi ; les flèches représentent les flux de la loi stationnaire π. Faites avancer l’animation puis comparez ces deux objets.';
 if(/compagnon|Krylov|Multiplier par X/i.test(s.title||''))return 'Survolez un vecteur pour isoler ses images. Les flèches vertes avancent dans une base de Krylov ; les retours donnent la relation polynomiale.';
 return 'Survolez un sommet pour isoler ses images. Les flèches indiquent les images et leurs étiquettes précisent l’opération.';
}
