"""Dix laboratoires : cardinalités, exemples limites et structures."""
from commun import lab,slider,select,preset
LABS=[
 lab('denombrer_rationnels','Lister les rationnels et approcher un réel','Ensembles et cardinalités',
 'Écrire les fractions irréductibles p/q dans un ordre qui permet de toutes les rencontrer. Puis chercher celles qui approchent le réel choisi. On distingue deux notions du cours : être dénombrable (pouvoir être listé) et être dense (approcher tout réel aussi précisément que souhaité).',
 [slider('H','Limite H pour |p|+q',2,22,1,9,integer=True),slider('target','Réel à approcher x',-1.8,1.8,.01,.73)],
 [preset('Un premier inventaire',H=6,target=.73),preset('Dénominateurs plus grands',H=20,target=.73),preset('La cible change',H=12,target=-1.41)]),
 lab('diagonale_cantor','Construire une suite absente de la liste','Ensembles et cardinalités',
 'Dans un tableau de zéros et de uns, changer chaque chiffre de la diagonale. La suite obtenue diffère de la première ligne au premier rang, de la deuxième au deuxième rang, etc. Ce raisonnement explique la non-dénombrabilité de ℝ, au programme de MP ; sa démonstration est un prolongement non exigible.',
 [slider('N','Nombre de lignes et de chiffres visibles',3,14,1,8,integer=True),slider('seed','Numéro du tirage reproductible',0,99,1,7,integer=True)],
 [preset('Voir chaque différence',N=6,seed=7),preset('Une autre liste',N=10,seed=21),preset('Agrandir le tableau',N=14,seed=7)]),
 lab('ensemble_cantor','Construire un compact en retirant des intervalles','Ensembles et cardinalités',
 'Partir de [0,1], retirer son tiers central, puis recommencer sur chaque segment restant. L’ensemble de Cantor rassemble les points qui ne sont jamais retirés. Ce prolongement permet de réinvestir le critère fermé et borné, puis de distinguer le nombre de points, la longueur des segments et la connexité par arcs.',
 [slider('level','Nombre d’étapes de construction k',0,8,1,4,integer=True),slider('address','Numéro de sélection d’un segment',0,255,1,5,integer=True)],
 [preset('Trois retraits',level=3,address=5),preset('Les intervalles rétrécissent',level=7,address=85),preset('L’étape initiale',level=0,address=0)]),
 lab('rationnels_irrationnels','Approcher un réel par des rationnels et des irrationnels','Adhérence et densité',
 'Approcher le réel choisi par des décimaux qₙ, puis par les irrationnels qₙ+√2/10ⁿ. Les deux suites tendent vers le même réel. C’est une illustration de la densité étudiée en MPSI : tout intervalle ouvert non vide contient un rationnel et un irrationnel, bien que les deux ensembles soient disjoints.',
 [slider('target','Réel cible x',-2,2,.001,.731),slider('N','Nombre de décimales étudiées',1,12,1,7,integer=True)],
 [preset('Approcher un rationnel',target=.731,N=7),preset('Cible négative',target=-1.414,N=10),preset('Voir l’échelle des erreurs',target=.125,N=12)]),
 lab('sinus_topologue','Un ensemble compact dans lequel certains points ne se relient pas','Connexité',
 'Ajouter au graphe de sin(1/x), pour 0<x≤1, tous ses points limites sur l’axe vertical. L’ensemble obtenu est compact, mais aucun chemin continu dans cet ensemble ne relie un point de cet axe à un point du graphe. Ce prolongement distingue la connexité générale de la connexité par arcs étudiée en MP.',
 [slider('turns','Nombre d’oscillations visibles',2,45,1,12,integer=True),slider('height','Hauteur du point limite y₀',-1,1,.05,.4)],
 [preset('Voir les oscillations près de l’axe',turns=10,height=.4),preset('Afficher davantage d’oscillations',turns=35,height=-.6),preset('Approcher le point (0,0)',turns=20,height=0)]),
 lab('gl_composantes','Changer le signe du déterminant en restant inversible ?','Structures et topologie',
 'Faire varier λ dans les matrices A=Q diag(λ,1,2,3)R, où Q et R sont deux matrices de rotation fixées. Le déterminant vaut 6λ. Sur ℝ, le théorème des valeurs intermédiaires impose de passer par zéro pour changer de signe. Sur ℂ, faire tourner λ sur le cercle évite zéro.',
 [select('field','Matrices réelles ou complexes ?',[('real','Réelles : λ=t'),('complex','Complexes : λ=eⁱᶿ')],'real'),slider('t','Valeur réelle de λ : t',-2,2,.05,.6),slider('angle','Angle θ sur le cercle complexe',0,360,1,120,'°')],
 [preset('Déterminant positif',field='real',t=1,angle=0),preset('Déterminant nul : matrice non inversible',field='real',t=0,angle=0),preset('Passer de 1 à −1 par le cercle complexe',field='complex',t=-1,angle=180)]),
 lab('orthogonal_compact','Quand un ensemble de matrices est-il compact ?','Structures et topologie',
 'Comparer O₄, ensemble des matrices orthogonales, et SL₄, ensemble des matrices de déterminant 1. Les deux sont fermés. Les matrices orthogonales restent bornées, tandis qu’une famille de SL₄ s’étire autant que souhaité. On applique le critère de MP : en dimension finie, compact équivaut à fermé et borné.',
 [slider('angle','Angle des rotations',0,360,1,55,'°'),select('orientation','Signe du déterminant de O',[('positive','Déterminant +1'),('negative','Déterminant −1')],'positive'),slider('T','Paramètre d’étirement T dans SL₄',0,6,.1,2)],
 [preset('Matrice orthogonale de déterminant +1',angle=55,orientation='positive',T=2),preset('Matrice orthogonale de déterminant −1',angle=130,orientation='negative',T=2),preset('Un étirement plus grand dans SL₄',angle=55,orientation='positive',T=6)]),
 lab('point_fixe','Résoudre x=cos(x) par une suite récurrente','Continuité et complétude',
 'Calculer les termes de xₙ₊₁=cos(xₙ), puis comparer avec xₙ₊₁=qxₙ+0,7. Les suites récurrentes et la recherche d’une limite vérifiant f(ℓ)=ℓ sont étudiées en MPSI. On estime ici l’erreur et on explique pourquoi certaines itérations convergent ; le théorème général de contraction est un prolongement.',
 [select('family','Application à itérer',[('cos','cos(x) sur [0,1]'),('affine','qx+0,7 sur ℝ')],'cos'),slider('q','Coefficient affine q',-1.1,1.1,.05,.6),slider('x0','Valeur initiale x₀',0,1,.05,.2),slider('N','Nombre d’itérations',2,60,1,15,integer=True)],
 [preset('Résoudre x=cos(x)',family='cos',q=.6,x0=.2,N=15),preset('Une suite affine qui converge lentement',family='affine',q=.95,x0=.2,N=45),preset('Une suite affine qui s’éloigne du point fixe',family='affine',q=1.05,x0=.2,N=30)]),
 lab('chemins_niveaux','Relier deux régions : le rôle d’un point de contact','Connexité',
 'Étudier les points (x,y) vérifiant F(x,y)≤b⁴, où F est le produit des carrés des distances aux points (−1,0) et (1,0). À b=1, les deux régions se touchent en zéro. Inclure ou exclure ce point change la possibilité de les relier par un chemin continu : c’est la connexité par arcs du cours de MP.',
 [slider('b','Valeur b qui détermine la région',.35,1.8,.01,.8),select('closed','Inclure ou exclure la frontière ?',[('yes','Inclure : F(x,y) ≤ b⁴'),('no','Exclure : F(x,y) < b⁴')],'yes')],
 [preset('Deux ovales',b=.8,closed='yes'),preset('Le point de contact',b=1,closed='yes'),preset('Contact exclu',b=1,closed='no'),preset('Une seule région',b=1.4,closed='yes')]),
 lab('homeomorphisme','Une bijection continue a-t-elle une réciproque continue ?','Continuité et complétude',
 'À chaque angle t∈[0,2π[, associer le point eⁱᵗ du cercle. Des angles proches de 2π donnent des points proches de l’image de 0, alors que ces angles restent loin de 0 : la réciproque n’est pas continue en ce point. Comparer avec t↦(t,t²,t³) sur [−1,1], dont la réciproque est simplement la première coordonnée.',
 [select('family','Application étudiée',[('circle','Associer un angle à un point du cercle'),('curve','Associer t au point (t,t²,t³)')],'circle'),slider('n','Rang n de la suite tₙ=2π−1/n',2,180,1,35,integer=True),slider('t','Valeur t dans le segment [−1,1]',-1,1,.05,.6)],
 [preset('Des angles proches de 2π',family='circle',n=35,t=.6),preset('Des images encore plus proches de 1',family='circle',n=180,t=.6),preset('Retrouver t par la première coordonnée',family='curve',n=35,t=.6)])
]
