"""Dix laboratoires : cardinalités, exemples limites et structures."""
from commun import lab,slider,select,preset
LABS=[
 lab('denombrer_rationnels','Dénombrer sans cesser d’être dense','Ensembles et cardinalités',
 'Parcourir les couples entiers par hauteur, ne garder que les fractions irréductibles, puis approcher un réel. Une liste finie illustre une énumération infinie sans prouver à elle seule la densité.',
 [slider('H','Hauteur maximale |p|+q',2,22,1,9,integer=True),slider('target','Réel à approcher x',-1.8,1.8,.01,.73)],
 [preset('Un premier inventaire',H=6,target=.73),preset('Dénominateurs plus grands',H=20,target=.73),preset('La cible change',H=12,target=-1.41)]),
 lab('diagonale_cantor','Une diagonale échappe à toute liste','Ensembles et cardinalités',
 'Construire une suite binaire qui diffère de la ligne i au rang i. Le raisonnement se prolonge à une liste infinie ; l’écriture ternaire avec chiffres 0 et 2 relie ces suites à des réels.',
 [slider('N','Lignes et colonnes affichées',3,14,1,8,integer=True),slider('seed','Graine reproductible',0,99,1,7,integer=True)],
 [preset('Voir chaque différence',N=6,seed=7),preset('Une autre liste',N=10,seed=21),preset('Agrandir le tableau',N=14,seed=7)]),
 lab('ensemble_cantor','Un compact sans intervalle, pourtant indénombrable','Ensembles et cardinalités',
 'Retirer le tiers central de chaque intervalle. Les étapes sont des unions finies de segments ; leur intersection est le compact de Cantor, parfait, totalement discontinu et indénombrable.',
 [slider('level','Étape de construction k',0,8,1,4,integer=True),slider('address','Adresse binaire d’un intervalle',0,255,1,5,integer=True)],
 [preset('Trois retraits',level=3,address=5),preset('Les intervalles rétrécissent',level=7,address=85),preset('L’étape initiale',level=0,address=0)]),
 lab('rationnels_irrationnels','Deux ensembles denses qui ne se rencontrent pas','Adhérence et densité',
 'Approcher x par qₙ=floor(10ⁿx)/10ⁿ, puis par qₙ+√2/10ⁿ. Chaque suite appartient à un ensemble dense différent ; ni ℚ ni son complémentaire n’a d’intérieur dans ℝ.',
 [slider('target','Réel cible x',-2,2,.001,.731),slider('N','Nombre de décimales étudiées',1,12,1,7,integer=True)],
 [preset('Approcher un rationnel',target=.731,N=7),preset('Cible négative',target=-1.414,N=10),preset('Voir l’échelle des erreurs',target=.125,N=12)]),
 lab('sinus_topologue','Connexe ne signifie pas connexe par arcs','Connexité',
 'Observer S={(x,sin(1/x)):0<x≤1}∪({0}×[−1,1]). La courbe s’accumule sur un segment : le fermé limite est connexe et compact, mais aucun chemin ne joint ce segment à la courbe.',
 [slider('turns','Nombre d’oscillations visibles',2,45,1,12,integer=True),slider('height','Hauteur du point limite y₀',-1,1,.05,.4)],
 [preset('La courbe s’accumule',turns=10,height=.4),preset('Zoom vers le segment',turns=35,height=-.6),preset('Un point central',turns=20,height=0)]),
 lab('gl_composantes','Le signe du déterminant sépare GL₄(ℝ)','Structures et topologie',
 'Étudier une famille dense A=Q diag(λ,1,2,3)R. Sur ℝ, passer d’une orientation à l’autre exige une singularité ; sur ℂ, λ=eⁱᶿ relie 1 à −1 en restant inversible.',
 [select('field','Chemin dans quel corps ?',[('real','Réel : λ=t'),('complex','Complexe : λ=eⁱᶿ')],'real'),slider('t','Paramètre réel t',-2,2,.05,.6),slider('angle','Phase complexe θ',0,360,1,120,'°')],
 [preset('Orientation positive',field='real',t=1,angle=0),preset('La singularité',field='real',t=0,angle=0),preset('Contourner zéro dans ℂ',field='complex',t=-1,angle=180)]),
 lab('orthogonal_compact','O₄ compact, SL₄ fermé mais non borné','Structures et topologie',
 'Comparer les matrices orthogonales, de colonnes unitaires, à la famille Q diag(eᵗ,e⁻ᵗ,1,1)R de déterminant 1. La fermeture seule ne fournit pas la compacité.',
 [slider('angle','Angle des rotations',0,360,1,55,'°'),select('orientation','Composante orthogonale',[('positive','Déterminant +1'),('negative','Déterminant −1')],'positive'),slider('T','Étirement dans SL₄',0,6,.1,2)],
 [preset('Une rotation dense',angle=55,orientation='positive',T=2),preset('Une réflexion composée',angle=130,orientation='negative',T=2),preset('Échapper à toute borne',angle=55,orientation='positive',T=6)]),
 lab('point_fixe','La complétude transforme une contraction en solution','Continuité et complétude',
 'Itérer cos(x) sur [0,1], puis comparer une application affine sur ℝ. Calculer une borne d’erreur démontrée quand |q|<1 ; distinguer absence de contraction, divergence et cas particulier stationnaire.',
 [select('family','Application à itérer',[('cos','cos(x) sur [0,1]'),('affine','qx+0,7 sur ℝ')],'cos'),slider('q','Coefficient affine q',-1.1,1.1,.05,.6),slider('x0','Valeur initiale x₀',0,1,.05,.2),slider('N','Nombre d’itérations',2,60,1,15,integer=True)],
 [preset('Résoudre x=cos(x)',family='cos',q=.6,x0=.2,N=15),preset('Contraction lente',family='affine',q=.95,x0=.2,N=45),preset('Sans contraction',family='affine',q=1.05,x0=.2,N=30)]),
 lab('chemins_niveaux','Des ensembles de niveau changent de connexité','Connexité',
 'Explorer les ovales de Cassini : ((x−1)²+y²)((x+1)²+y²)≤b⁴. Deux composantes deviennent une à b=1 ; le choix strict ou large change la connexité au point de contact.',
 [slider('b','Paramètre de niveau b',.35,1.8,.01,.8),select('closed','Inégalité du sous-niveau',[('yes','F(x,y) ≤ b⁴'),('no','F(x,y) < b⁴')],'yes')],
 [preset('Deux ovales',b=.8,closed='yes'),preset('Le point de contact',b=1,closed='yes'),preset('Contact exclu',b=1,closed='no'),preset('Une seule région',b=1.4,closed='yes')]),
 lab('homeomorphisme','Une bijection continue a-t-elle un inverse continu ?','Continuité et complétude',
 'Comparer t↦eⁱᵗ sur [0,2π[ à l’injection t↦(t,t²,t³) sur un segment compact. Le premier inverse saute à la couture ; pour le second, le théorème compact-Hausdorff assure la continuité.',
 [select('family','Application étudiée',[('circle','Enrouler [0,2π[ sur le cercle'),('curve','Plonger [−1,1] dans ℝ³')],'circle'),slider('n','Indice de la suite près de la couture',2,180,1,35,integer=True),slider('t','Point du segment compact',-1,1,.05,.6)],
 [preset('La couture du cercle',family='circle',n=35,t=.6),preset('Se rapprocher encore',family='circle',n=180,t=.6),preset('Une injection compacte',family='curve',n=35,t=.6)])
]
