"""Dix laboratoires : compacité, extraction, continuité et normes."""
from commun import lab, slider, select, preset

LABS = [
    lab('bolzano_weierstrass', 'Deux valeurs d’adhérence, deux extractions', 'Compacité & continuité',
        'La suite uₙ=(−1)ⁿ+1/(n+1) est bornée mais ne converge pas. Séparer les indices pairs et impairs construit deux sous-suites convergentes avec une erreur exacte.',
        [slider('N','Dernier indice N',20,600,1,100,integer=True),slider('epsilon','Tolérance ε',0.002,0.2,0.002,0.02)],
        [preset('Deux amas visibles',N=60,epsilon=0.05),preset('Des indices strictement croissants',N=300,epsilon=0.01),preset('Une tolérance exigeante',N=80,epsilon=0.002)]),
    lab('extraction_aleatoire', 'Le TP : extraire sans répéter un indice', 'Compacité & continuité',
        'Tirer des valeurs indépendantes uniformes sur [0,3] et retenir uniquement les nouveaux records de proximité à 1. Distinguer l’expérience finie du théorème presque sûr et comparer la loi exacte aux simulations.',
        [slider('N','Nombre N de tirages',100,20000,100,3000,integer=True),slider('seed','Graine aléatoire reproductible',0,999,1,17,integer=True),slider('trials','Nombre d’expériences pour l’histogramme',50,400,25,200,integer=True),slider('d','Distance d testée',0.001,1,0.001,0.01)],
        [preset('L’extraction du TP',N=3000,seed=17,trials=200,d=0.01),preset('Un voisinage difficile',N=100,seed=42,trials=200,d=0.001),preset('Loi du meilleur rapprochement',N=20000,seed=7,trials=100,d=0.001)]),
    lab('cauchy_rationnels', 'Héron : Cauchy dans ℚ, limite dans ℝ', 'Compacité & continuité',
        'La récurrence rationnelle uₙ₊₁=uₙ/2+1/uₙ, u₀=2, approche √2. Des fractions exactes et une majoration du reste établissent le caractère de Cauchy ; la parité prouve que la limite n’appartient pas à ℚ.',
        [slider('n','Dernier indice n',0,8,1,5,integer=True),slider('epsilon','Tolérance ε',0.000001,0.1,0.000001,0.0001)],
        [preset('Les premières fractions',n=3,epsilon=0.001),preset('Convergence quadratique',n=6,epsilon=0.000001),preset('La preuve dépasse la précision flottante',n=8,epsilon=0.000001)]),
    lab('compacts_recouvrements', 'Un recouvrement fini qui couvre vraiment', 'Compacité & continuité',
        'Couvrir [0,1] par des intervalles ouverts de rayon r centrés aux j/m. Comparer avec Uₙ=]−1,1−1/n[, qui recouvrent [0,1[ sans qu’une sous-famille finie suffise.',
        [slider('m','Nombre m de pas du réseau',2,30,1,6,integer=True),slider('r','Rayon r des ouverts',0.01,0.4,0.005,0.12),slider('N','Dernier ouvert U_N retenu',2,100,1,12,integer=True)],
        [preset('Une marge de couverture',m=6,r=0.12,N=12),preset('Les contacts ne suffisent pas',m=10,r=0.05,N=20),preset('Des trous explicites',m=5,r=0.05,N=80)]),
    lab('valeurs_extremes', 'Maximum sur une ellipse, supremum sans maximum', 'Compacité & continuité',
        'Maximiser une forme linéaire sur une ellipse fermée ou sur son intérieur. Calculer les points extrémaux par Cauchy–Schwarz et voir exactement où intervient la compacité.',
        [slider('a','Demi-axe a horizontal',0.5,4,0.1,2.5),slider('b','Demi-axe b vertical',0.5,4,0.1,1.2),slider('theta','Direction θ de la forme linéaire',0,360,5,35,'°'),select('domain','Domaine',[('closed','Ellipse pleine fermée'),('open','Intérieur de l’ellipse')],'closed'),slider('N','Indice N d’approche du supremum',2,200,1,20,integer=True)],
        [preset('Maximum oblique',a=3,b=1,theta=40,domain='closed',N=20),preset('Le supremum n’est pas atteint',a=3,b=1,theta=40,domain='open',N=100),preset('Une direction verticale',a=2,b=3,theta=90,domain='closed',N=40)]),
    lab('heine_continuite', 'Uniforme sur un compact, sans être lipschitzienne', 'Compacité & continuité',
        'Comparer sin(x²), uniformément continue sur chaque compact mais pas sur ℝ, et √x, uniformément continue sur [0,1] avec un module de Hölder, sans constante de Lipschitz.',
        [select('family','Fonction étudiée',[('chirp','sin(x²) : compacts et ℝ'),('sqrt','√x sur [0,1]')],'chirp'),slider('R','Rayon R du compact [−R,R]',0.5,12,0.5,4),slider('n','Indice n de la paire témoin',1,50000,1,500,integer=True)],
        [preset('Heine sur un compact',family='chirp',R=4,n=200),preset('La continuité uniforme échoue sur ℝ',family='chirp',R=8,n=50000),preset('Hölder mais pas Lipschitz',family='sqrt',R=4,n=1000)]),
    lab('image_compacte', 'La somme de deux compacts dessine un stade', 'Compacité & continuité',
        'L’exercice 6 devient une construction géométrique : ajouter une ellipse pleine et un segment orienté. La somme est l’image continue du produit des deux compacts ; sa fonction d’appui se calcule exactement.',
        [slider('a','Demi-axe a de l’ellipse',0.5,3,0.1,1.5),slider('b','Demi-axe b de l’ellipse',0.5,3,0.1,1),slider('length','Demi-longueur s du segment',0.2,3,0.1,1.2),slider('theta','Angle θ du segment',0,180,5,30,'°'),slider('direction','Direction φ du support',0,360,5,75,'°')],
        [preset('Un stade elliptique',a=1.5,b=1,length=1.2,theta=0,direction=45),preset('Somme oblique',a=2.5,b=0.7,length=1.5,theta=55,direction=110),preset('Appui perpendiculaire au segment',a=2,b=1,length=2,theta=30,direction=120)]),
    lab('applications_lineaires', 'Toutes les applications linéaires sont continues', 'Compacité & continuité',
        'Étudier une matrice dense de dimension 4 à 8. Relier les normes d’opérateur 1, 2 et ∞, les valeurs singulières et l’image d’un cercle dans un plan singulier, sans réduire le problème à une matrice 2×2.',
        [slider('dimension','Dimension n',4,8,1,5,integer=True),slider('condition','Rapport κ des valeurs singulières extrêmes',1,100,1,12),slider('seed','Graine de la matrice dense',0,999,1,23,integer=True)],
        [preset('Une matrice dense 5×5',dimension=5,condition=12,seed=23),preset('Forte anisotropie en dimension 8',dimension=8,condition=80,seed=42),preset('Une isométrie orthogonale',dimension=6,condition=1,seed=7)]),
    lab('normes_dimension_infinie', 'Des normes qui cessent d’être équivalentes', 'Compacité & continuité',
        'Dans C([0,1]), les fonctions fₙ(x)=xⁿ vérifient ‖fₙ‖∞=1 tandis que leurs normes intégrales tendent vers zéro. Les rapports exacts empêchent toute constante d’équivalence valable sur cet espace entier.',
        [slider('N','Exposant N de la fonction',1,1000,1,40,integer=True)],
        [preset('Une première concentration au bord',N=10),preset('Le rapport des normes augmente',N=150),preset('Un contre-exemple à toutes les constantes',N=1000)]),
    lab('boule_non_compacte', 'Une infinité de vecteurs séparés dans une boule', 'Compacité & continuité',
        'L’exercice 9 utilise vₙ(x)=eⁱⁿˣ/√(2π). Ces fonctions ont norme L² égale à 1 et restent à distance √2 deux à deux : la boule unité n’est pas compacte en dimension infinie.',
        [slider('M','Nombre M de modes dans la matrice de Gram',3,24,1,12,integer=True),slider('probe','Mode n représenté',1,40,1,5,integer=True)],
        [preset('L’orthogonalité devient une matrice',M=12,probe=5),preset('Des oscillations plus rapides',M=20,probe=30),preset('Une boule sans extraction convergente',M=24,probe=12)]),
]
