"""Dix expériences de géométrie des ensembles, du voisinage aux chemins."""
from commun import lab, slider, select, preset

LABS = [
    lab('boules_normes','Une boule change de forme, pas de définition','Ensembles et voisinages',
        'Comparer les boules de ℝ² pour les normes 1, 2, ∞ et p. La marge r−‖x‖ est calculée exactement : une boule ouverte contient son point test si et seulement si cette marge est strictement positive.',
        [select('norm','Norme choisie',[('1','Norme 1'),('2','Norme euclidienne'),('inf','Norme infinie'),('p','Norme p')],'2'),slider('p','Exposant p',1,8,0.25,3),slider('radius','Rayon r',0.3,2,0.05,1),slider('x','Abscisse du point x',-2,2,0.05,0.7),slider('y','Ordonnée du point y',-2,2,0.05,0.7),select('closed','Boule ouverte ou fermée',[('open','Ouverte : ‖x‖ < r'),('closed','Fermée : ‖x‖ ≤ r')],'open')],
        [preset('Même point, trois normes',norm='1',radius=1,x=0.7,y=0.7),preset('Sur la sphère',norm='2',radius=1,x=1,y=0,closed='open'),preset('Une boule presque carrée',norm='p',p=8,radius=1,x=0.9,y=0.9)]),
    lab('interieur_frontiere','Intérieur, adhérence et frontière au microscope','Ensembles et voisinages',
        'Tester un point dans un disque ouvert ou fermé, un anneau fermé ou un disque épointé. Une frontière appartient parfois à l’ensemble, parfois non ; l’adhérence reste la même pour les deux disques.',
        [select('shape','Ensemble A',[('open','Disque ouvert'),('closed','Disque fermé'),('annulus','Anneau fermé : r/2 ≤ ‖x‖ ≤ r'),('punctured','Disque ouvert privé de 0')],'punctured'),slider('radius','Rayon extérieur r',0.4,2,0.05,1),slider('x','Abscisse du point',-2.2,2.2,0.05,0),slider('y','Ordonnée du point',-2.2,2.2,0.05,0),slider('epsilon','Rayon ε du voisinage observé',0.02,0.6,0.02,0.2)],
        [preset('Le trou appartient à l’adhérence',shape='punctured',radius=1,x=0,y=0),preset('Frontière intérieure de l’anneau',shape='annulus',radius=1,x=0.5,y=0),preset('Une frontière contenue dans A',shape='closed',radius=1,x=1,y=0)]),
    lab('adherence_suite','Le point absent où tous les points s’accumulent','Ensembles et voisinages',
        'Étudier A={1/n : n≥1}, puis A∪{0}. Le nombre de points dessinés ne change pas l’ensemble infini étudié. La distance exacte et l’infimum distinguent point adhérent et point appartenant à A.',
        [slider('N','Nombre N de points dessinés',8,200,1,35,integer=True),slider('x','Point réel x',-0.3,1.3,0.005,0),slider('epsilon','Rayon ε du voisinage',0.005,0.25,0.005,0.08),select('include_zero','Ajouter la limite 0',[('no','A={1/n}'),('yes','A={1/n}∪{0}')],'no')],
        [preset('Distance nulle sans appartenance',x=0,include_zero='no',N=25),preset('Un point isolé de A',x=0.25,include_zero='no',N=35),preset('Rendre l’ensemble compact',x=0,include_zero='yes',N=70)]),
    lab('topologie_relative','Ouvert dans un intervalle, au bord de ℝ','Ensembles et voisinages',
        'Dans X=[0,1], A=X∩]−1/2,b[ est ouvert relativement à X. Construire Bℝ(x,ε)∩X et voir pourquoi le point 0 peut être intérieur dans X, sans être intérieur dans ℝ.',
        [slider('b','Extrémité b de l’ouvert ambiant',0.1,1.4,0.05,0.65),slider('x','Point x de X',0,1,0.025,0),slider('epsilon','Rayon ε',0.025,0.6,0.025,0.2)],
        [preset('Le bord 0 est intérieur dans X',b=0.65,x=0,epsilon=0.2),preset('Le point b est exclu',b=0.5,x=0.5,epsilon=0.1),preset('X est ouvert dans lui-même',b=1.2,x=1,epsilon=0.2)]),
    lab('operations_ouverts','La limite d’ensembles perd une propriété','Ensembles et voisinages',
        'L’intersection des ouverts ]−1/n,1/n[ vaut {0}, qui n’est pas ouvert dans ℝ. L’union des fermés [1/n,1] vaut ]0,1], qui n’est pas fermé. Comparer opérations finies et infinies.',
        [select('operation','Famille étudiée',[('intersection','Intersection d’ouverts'),('union','Union de fermés')],'intersection'),slider('N','Nombre N d’ensembles',2,100,1,15,integer=True),slider('x','Point réel x',-1.1,1.1,0.01,0)],
        [preset('Chaque intersection finie reste ouverte',operation='intersection',N=5,x=0),preset('Le singleton limite',operation='intersection',N=100,x=0),preset('Une limite exclue de l’union',operation='union',N=80,x=0)]),
    lab('distance_ensemble','Une distance continue, deux projections possibles','Distances et convexité',
        'A est l’union de deux disques fermés. Calculer d(x,A) et toutes les projections minimisantes. La fonction distance est toujours 1-lipschitzienne ; la projection peut être multivaluée si A n’est pas convexe.',
        [slider('separation','Distance entre les centres',0.5,4,0.1,3),slider('radius','Rayon des disques',0.25,1.2,0.05,0.7),slider('x','Abscisse du point',-3,3,0.05,0),slider('y','Ordonnée du point',-2.5,2.5,0.05,0.8)],
        [preset('Deux projections au même point',separation=3,radius=0.7,x=0,y=0.8),preset('Le point appartient à A',separation=2,radius=0.8,x=-1,y=0.2),preset('Une distance près de la jonction',separation=1.5,radius=0.8,x=0,y=1.2)]),
    lab('convexite','Un segment entier, pas seulement des points testés','Distances et convexité',
        'Choisir deux points dans un disque, un anneau ou une union de deux disques. Le segment est vérifié par calcul analytique de son rayon minimal ou par réunion d’intervalles de paramètres, puis comparé à un témoin explicite.',
        [select('shape','Ensemble A',[('disk','Disque fermé unité'),('annulus','Anneau fermé : 1/2 ≤ ‖x‖ ≤ 1'),('union','Deux disques de rayon 0,65')],'annulus'),slider('a','Angle du premier point',-180,180,5,0,'°'),slider('b','Angle du second point',-180,180,5,180,'°'),slider('rho','Rayon relatif des points dans A',0.5,1,0.025,0.8),slider('separation','Distance des centres, cas union',0,3,0.1,2)],
        [preset('L’anneau n’est pas convexe',shape='annulus',a=0,b=180,rho=0.8),preset('Deux composantes séparées',shape='union',a=0,b=180,rho=0.5,separation=2),preset('Le disque satisfait la définition',shape='disk',a=-120,b=50,rho=1)]),
    lab('enveloppe_convexe','Fabriquer le plus petit convexe','Distances et convexité',
        'Construire l’enveloppe convexe d’un nuage déterministe par chaînes monotones. Un barycentre à poids positifs reste dans l’enveloppe ; l’aire, les sommets extrêmes et les distances aux côtés viennent du calcul géométrique.',
        [slider('N','Nombre N de points',8,40,1,20,integer=True),slider('seed','Graine du nuage',1,40,1,7,integer=True),slider('alpha','Poids accentué sur le premier point',0,1,0.025,0.6)],
        [preset('Un nuage et ses sommets extrêmes',N=20,seed=7,alpha=0.6),preset('Barycentre presque uniforme',N=35,seed=19,alpha=0),preset('Concentrer le poids sur un sommet',N=15,seed=3,alpha=1)]),
    lab('projection_convexe','Une projection unique et une inéquation','Distances et convexité',
        'Projeter un point sur un rectangle ou un triangle fermé. La caractérisation ⟨x−p,z−p⟩≤0 pour tout z∈C est vérifiée sur les sommets ; la linéarité en z étend la vérification à tout le polytope.',
        [select('shape','Convexe fermé C',[('rectangle','Rectangle [−1,1]×[−0,65,0,65]'),('triangle','Triangle à trois sommets')],'triangle'),slider('x','Abscisse de x',-2.5,2.5,0.05,1.4),slider('y','Ordonnée de x',-2.5,2.5,0.05,1.2),slider('zeta','Position du point z sur le bord',0,1,0.025,0.3)],
        [preset('Projection sur une arête',shape='triangle',x=1.4,y=1.2,zeta=0.3),preset('Projection sur un sommet',shape='triangle',x=0.1,y=2.3,zeta=0.8),preset('Point déjà dans le convexe',shape='rectangle',x=0.5,y=0.2,zeta=0.2)]),
    lab('connexite_chemins','Contourner un trou, séparer deux composantes','Connexité',
        'Relier deux points d’un plan épointé ou d’un anneau par un chemin radial et angulaire. Comparer avec deux disques séparés et avec l’axe réel privé de 0 : une séparation interdit certains chemins.',
        [select('space','Espace X',[('punctured','Plan ℝ² privé de 0'),('annulus','Anneau : 1/2 ≤ ‖x‖ ≤ 1,5'),('disks','Union de deux disques fermés'),('axis','Axe réel privé de 0')],'punctured'),slider('angle','Angle du second point',-180,180,5,180,'°'),slider('r1','Rayon du premier point',0.55,1.4,0.05,0.8),slider('r2','Rayon du second point',0.55,1.4,0.05,1.2),slider('gap','Écart entre les disques',0.15,1.5,0.05,0.4)],
        [preset('Le segment traverse le trou, pas le chemin',space='punctured',angle=180,r1=0.8,r2=1.2),preset('Un anneau connexe non convexe',space='annulus',angle=180,r1=0.7,r2=1.3),preset('Une séparation empêche le chemin',space='disks',gap=0.5)]),
]
