"""Cours, preuves et problèmes originaux de Topologie & Ensembles.

L'espace ambiant et la norme sont annoncés. Les images finies illustrent des
théorèmes portant sur des ensembles ou suites infinis ; elles ne les prouvent
pas. Le PDF source n'est pas redistribué.
"""
from html import escape


def P(label, text):
    return '<p><b>' + escape(label) + '</b> ' + escape(text) + '</p>'


def F(text):
    return '<div class="formula">' + escape(text).replace('\n', '<br>') + '</div>'


def record(lab, title, level, context, formula, proof, application,
           lemma_title, lemma_statement, lemma_formula, lemma_proof,
           ex1_title, ex1_question, ex1_answer, ex2_title, ex2_question, ex2_answer):
    return dict(lab=lab, title=title, level=level, context=context, formula=formula,
                proof=proof, application=application, lemma_title=lemma_title,
                lemma_statement=lemma_statement, lemma_formula=lemma_formula,
                lemma_proof=lemma_proof,
                exercises=[(ex1_title, ex1_question, ex1_answer),
                           (ex2_title, ex2_question, ex2_answer)])


DATA = [
    record('boules_normes', 'Une boule est définie par une inégalité', 'Sup → Spé',
        'Dans ℝ², x=(x₁,x₂) désigne un vecteur, a un centre et r>0 un rayon. Une norme mesure une longueur et induit d(x,y)=‖x−y‖. Les boules des normes 1, 2 et ∞ sont respectivement un losange, un disque et un carré : leur forme change, tandis que leurs définitions restent les mêmes. Un voisinage de a contient une boule ouverte centrée en a ; il n’est pas nécessairement ouvert lui-même.',
        'Bₒ(a,r)={x : ‖x−a‖<r} ; B𝒇(a,r)={x : ‖x−a‖≤r}\n‖x‖₁=|x₁|+|x₂| ; ‖x‖₂=√(x₁²+x₂²) ; ‖x‖∞=max(|x₁|,|x₂|)',
        'Si x∈Bₒ(a,r), poser δ=r−‖x−a‖>0. Pour ‖y−x‖<δ, l’inégalité triangulaire donne ‖y−a‖≤‖y−x‖+‖x−a‖<r : la boule est ouverte. La fonction x↦‖x−a‖ est continue, car |‖x−a‖−‖y−a‖|≤‖x−y‖. Son image réciproque de ]−∞,r] est donc fermée. La marge δ doit être strictement positive pour produire un voisinage intérieur.',
        'Pour x=(0,7;0,7) et r=1, ‖x‖₁=1,4, ‖x‖₂=√0,98≈0,98995 et ‖x‖∞=0,7. Le point est hors du losange et dans les deux autres boules. Cela ne contredit pas l’équivalence des normes : celle-ci compare des rayons différents, elle n’identifie pas leurs boules de même rayon.',
        'Des normes différentes donnent la même topologie en dimension finie',
        'Pour x∈ℝᵈ, on compare les normes usuelles avec des constantes indépendantes de x. Ces inclusions de boules transfèrent les définitions d’ouvert, de convergence et de continuité d’une norme à l’autre.',
        '‖x‖∞≤‖x‖₂≤√d‖x‖∞ ; ‖x‖₂≤‖x‖₁≤√d‖x‖₂\nβN₂(x)≤N₁(x)≤αN₂(x), α,β>0',
        'La première borne découle du maximum des coordonnées et de la somme des carrés ; Cauchy–Schwarz donne la dernière. Plus généralement une norme N vérifie N(x)≤Σ|xᵢ|N(eᵢ), donc est continue pour la norme euclidienne. Sur la sphère euclidienne compacte, elle atteint un minimum m>0 et un maximum M. Par homogénéité, m‖x‖₂≤N(x)≤M‖x‖₂. Le rôle de la dimension finie et de la compacité est essentiel.',
        'Choisir un rayon sûr dans ℝ⁴',
        'Pour x=(1,−2,2,−1), calculer ses normes 1, 2 et ∞. Donner une boule euclidienne contenue dans la boule ouverte infinie de rayon 3, et une boule infinie contenue dans cette même boule euclidienne.',
        'On obtient 6, √10 et 2. Comme ‖z‖∞≤‖z‖₂, B₂(0,3)⊂B∞(0,3). Comme ‖z‖₂≤2‖z‖∞ dans ℝ⁴, B∞(0,3/2)⊂B₂(0,3). Ces inclusions expliquent pourquoi un ouvert pour une norme reste ouvert pour l’autre, sans supposer l’égalité des boules.',
        'Un rayon intérieur calculé, non deviné',
        'Dans la boule ouverte de norme 1, de centre a=(1,−1) et rayon 2, prendre x=(1,4;−0,5). Déterminer une boule centrée en x contenue dans la boule initiale. Le même raisonnement fonctionne-t-il pour un point de la sphère ?',
        '‖x−a‖₁=0,4+0,5=0,9 ; la marge est 1,1. Ainsi B₁(x,1,1) est contenue dans B₁(a,2), avec des inégalités strictes. Sur la sphère la marge vaut zéro, donc ce calcul ne fournit aucun rayon positif ; de fait tout voisinage d’un point de cette sphère contient des points hors de la boule.'),
    record('interieur_frontiere', 'Trois opérations : intérieur, adhérence, frontière', 'Sup → Spé',
        'Pour A⊂E métrique, l’intérieur A° contient les points possédant une boule incluse dans A. L’adhérence Ā contient les points dont toutes les boules rencontrent A. La frontière contient les points où toute boule rencontre A et son complémentaire. « Appartenir à A » et « être adhérent à A » sont deux questions différentes.',
        'x∈A° ⇔ ∃r>0, Bₒ(x,r)⊂A\nx∈Ā ⇔ ∀r>0, Bₒ(x,r)∩A≠∅\nFr(A)=Ā∖A°=Ā∩(E∖A)̄',
        'Si x∉Ā, une boule autour de x manque A, donc est incluse dans E∖A : E∖Ā=(E∖A)°. Inverser le rôle des complémentaires donne E∖A°=(E∖A)̄. En prenant l’intersection, on obtient la formule de frontière, intersection de deux fermés. Ainsi Fr(A) est fermée et Fr(A)=Fr(E∖A). Les quantificateurs ∃r et ∀r distinguent rigoureusement intérieur et adhérence.',
        'Pour le disque ouvert épointé A={0<‖x‖₂<1}, A°=A, Ā={‖x‖₂≤1} et Fr(A)={0}∪{‖x‖₂=1}. Le centre absent est un point de frontière, même si le dessin n’en montre qu’un trou minuscule. Pour le disque fermé, la frontière est incluse dans A.',
        'Ouvert et fermé sont des égalités, non des contraires exclusifs',
        'A est ouvert si A=A° ; A est fermé si A=Ā. Certains ensembles vérifient les deux propriétés, certains aucune. Les mots se rapportent toujours à un espace ambiant fixé.',
        'A°⊂A⊂Ā ; (A°)°=A° ; (Ā)̄=Ā\n∅ et E sont ouverts et fermés dans E',
        'Toute boule témoin d’intérieur rend ses points intérieurs, donc A° est ouvert. Si un fermé F contient A, tout point hors de F a une boule qui évite A, donc Ā⊂F ; Ā est le plus petit fermé contenant A. Dans ℝ connexe, seules ∅ et ℝ sont simultanément ouvertes et fermées. Dans un espace discret, chaque partie l’est : la propriété dépend de l’espace.',
        'Un anneau et deux frontières',
        'Dans ℝ², A={x : 1/2≤‖x‖₂≤1}. Déterminer A°, Ā et Fr(A), puis classer A. Pourquoi le cercle intérieur ne disparaît-il pas de la frontière ?',
        'A°={1/2<‖x‖₂<1}, Ā=A et Fr(A) est la réunion des cercles de rayons 1/2 et 1. A est fermé et borné, donc compact en dimension finie, mais n’est pas ouvert. Une boule autour d’un point du cercle intérieur contient à la fois des points de rayon inférieur à 1/2 et supérieur à 1/2 : elle rencontre les deux côtés.',
        'Une frontière peut avoir un intérieur',
        'Déterminer intérieur, adhérence et frontière de ℚ dans ℝ. Déduire si la frontière d’un ensemble possède toujours un intérieur vide.',
        'Chaque intervalle contient un rationnel et un irrationnel. Ainsi ℚ°=∅, ℚ̄=ℝ et Fr(ℚ)=ℝ, dont l’intérieur est ℝ. La frontière d’un ensemble quelconque n’a donc pas toujours un intérieur vide. Pour un fermé F, en revanche Fr(F)=F∖F° a un intérieur vide : une boule incluse dans cette frontière serait incluse dans F et donc dans F°.'),
    record('adherence_suite', 'L’adhérence se construit avec des suites', 'Sup → Spé',
        'L’ensemble A={1/n : n≥1} est infini dénombrable ; N règle seulement le nombre de points dessinés. Chaque 1/n est isolé, tandis que 0, absent de A, en est un point d’accumulation. Un point adhérent n’est pas nécessairement un point d’accumulation : un singleton contient son unique point adhérent, isolé.',
        'Ā=A∪{0} ; A°=∅ ; Fr(A)=A∪{0}\nx∈Ā ⇔ ∃(aₙ)∈A^ℕ, aₙ→x',
        'Si x∈Ā, choisir aₙ∈A∩B(x,1/(n+1)) ; alors d(aₙ,x)<1/(n+1), donc aₙ→x. Réciproquement une suite dans A convergeant vers x finit dans toute boule de centre x, qui rencontre donc A. Pour l’ensemble des 1/n, une suite convergente de ses éléments a soit une sous-suite constante, soit des dénominateurs tendant vers l’infini ; sa limite appartient alors à A ou vaut 0.',
        'd(0,A)=infₙ1/n=0 mais ce minimum n’est pas atteint dans A. En ajoutant 0, on obtient un fermé borné de ℝ, donc un compact. Agrandir N ne transforme jamais le dessin fini en preuve de l’absence du point 0 dans A.',
        'Fermeture séquentielle et suites extraites',
        'Dans un espace métrique, F est fermé si et seulement si toute suite de F qui converge dans l’espace ambiant a sa limite dans F. La convergence de la suite entière ne se confond pas avec l’existence d’une sous-suite convergente.',
        'F fermé ⇔ [(xₙ∈F et xₙ→x∈E) ⇒ x∈F]\nφ:ℕ→ℕ strictement croissante ; xφ(n) est une suite extraite',
        'La première assertion découle de F=F̄ et de la caractérisation précédente. Une extraction strictement croissante vérifie φ(n)≥n, donc tend vers l’infini ; si xₙ→x, alors xφ(n)→x. L’inverse est faux : (−1)ⁿ possède deux sous-suites constantes de limites 1 et −1, mais ne converge pas.',
        'Un ensemble de matrices qui se ferme en ajoutant une limite',
        'Dans M₄(ℝ) de norme de Frobenius, poser Dₙ=diag(1,1,1,1/n). Déterminer l’adhérence de {Dₙ:n≥1}, son caractère compact et sa distance à l’ensemble des matrices singulières.',
        'Dₙ→D∞=diag(1,1,1,0). Comme pour {1/n}, l’adhérence est {Dₙ}∪{D∞}. L’ensemble initial n’est pas fermé et n’est donc pas compact ; son adhérence est fermée bornée dans ℝ¹⁶, donc compacte. Chaque Dₙ est à distance 1/n des matrices singulières, car sa plus petite valeur singulière vaut 1/n ; l’infimum sur tout l’ensemble est zéro, non atteint par un Dₙ.',
        'Accumulation ou isolement ?',
        'Pour C={0}∪{1/n:n≥1}, caractériser ses points d’accumulation. Montrer qu’une suite parcourant une infinité de points distincts de C ne peut avoir une limite différente de 0.',
        '0 est un point d’accumulation car chaque boule autour de zéro contient des 1/n non nuls. Chaque 1/k possède un voisinage évitant les autres valeurs, obtenu avec la moitié du plus petit écart aux voisins. Une suite de points distincts convergeant vers un point isolé serait finalement égale à ce point, contradiction ; l’unique limite possible est donc zéro.'),
    record('topologie_relative', 'Le mot ouvert dépend de l’espace ambiant', 'Sup → Spé',
        'On fixe X=[0,1] avec la distance héritée de ℝ. Une boule de X vaut Bℝ(x,r)∩X. L’ensemble A=[0,b[ pour 0<b≤1 est ouvert dans X, bien qu’il ne soit pas ouvert dans ℝ. Le bord de l’espace n’est pas automatiquement une frontière relative.',
        'U ouvert dans X ⇔ ∃O ouvert dans E, U=X∩O\nF fermé dans X ⇔ ∃C fermé dans E, F=X∩C',
        'Si U=X∩O, tout x∈U possède une boule ambiante incluse dans O ; son intersection avec X est incluse dans U. Réciproquement choisir pour chaque x∈U une boule B(x,rₓ) dont l’intersection avec X est incluse dans U ; la réunion O de ces boules est ouverte et X∩O=U. La caractérisation des fermés se déduit en prenant les complémentaires dans X.',
        'A=X∩]−1/2,b[. Le point zéro est intérieur relativement à X : pour r<b, B_X(0,r)=[0,r[⊂A. Dans ℝ, aucune boule autour de zéro n’est incluse dans A, car elle contient des réels négatifs. Si b>1 dans le laboratoire, A=X tout entier et sa frontière relative est vide.',
        'Adhérence relative et compacité intrinsèque',
        'L’adhérence se restreint simplement à X, mais l’intérieur ne suit pas la même formule. La compacité d’une partie K⊂X reste la même dans X et dans l’espace ambiant métrique E.',
        'adh_X(A)=X∩adh_E(A)\nint_X(A) peut être plus grand que X∩int_E(A)',
        'Les boules relatives rencontrent A exactement lorsque leurs boules ambiantes le rencontrent, d’où la formule d’adhérence pour A⊂X. Pour la compacité, les suites et leurs limites dans K sont les mêmes avec la distance héritée : la caractérisation séquentielle est inchangée. En revanche être fermé dans X ne signifie pas être fermé dans E si X n’est lui-même pas fermé dans E.',
        'Un intervalle semi-ouvert bien classé',
        'Pour X=[0,1] et A=[0,1/2[, calculer les intérieurs, adhérences et frontières dans ℝ puis dans X. A est-il compact ?',
        'Dans ℝ, intérieur ]0,1/2[, adhérence [0,1/2] et frontière {0,1/2}. Dans X, intérieur [0,1/2[, même adhérence [0,1/2] et frontière {1/2}. A n’est pas compact : la suite 1/2−1/(n+3) converge vers 1/2, hors de A. L’ouverture relative ne décide pas à elle seule de la compacité.',
        'Fermé relatif ne suffit pas',
        'Dans X=]0,1[, considérer F=]0,1/2]. Montrer que F est fermé dans X mais pas compact. Quel rôle joue le caractère non fermé de X dans ℝ ?',
        'F=X∩]−∞,1/2], donc est fermé dans X. Pourtant 1/(n+2)∈F tend vers zéro dans ℝ, hors de F ; aucune sous-suite n’a une autre limite. F n’est pas compact et n’est pas fermé dans ℝ. Un fermé d’un compact est compact ; ici X n’est pas compact, donc ce théorème ne s’applique pas.'),
    record('operations_ouverts', 'Opérations finies et infinies ne se confondent pas', 'Sup → Spé',
        'La stabilité des ouverts utilise le nombre d’ensembles intersectés. Une intersection finie permet de prendre le minimum d’un nombre fini de rayons positifs. Ce minimum peut devenir nul lorsque l’on passe à une infinité de contraintes.',
        '⋃ᵢUᵢ ouvert ; U₁∩…∩Uₘ ouvert\n⋂ᵢFᵢ fermé ; F₁∪…∪Fₘ fermé\n⋂n≥1]−1/n,1/n[={0}',
        'Dans une réunion, un point appartient à au moins un ouvert et garde la boule témoin de cet ouvert. Dans une intersection finie, si x∈Uⱼ et B(x,rⱼ)⊂Uⱼ, prendre r=minⱼrⱼ>0. Pour la famille ]−1/n,1/n[, tout x≠0 est exclu dès que n>1/|x| ; seul zéro reste. Le singleton {0} n’est pas ouvert dans ℝ.',
        'L’intersection après N contraintes est toujours ]−1/N,1/N[, ouverte ; l’intersection infinie est fermée mais non ouverte. De même ⋃n≥1[1/n,1]=]0,1], bien que chaque terme et chaque réunion finie soient fermés. Le passage N→∞ n’est pas une opération finie.',
        'Densité : l’hypothèse ouvert de l’exercice 8',
        'Si A et B sont denses dans E et si A est ouvert, leur intersection est dense. L’ouverture d’un des deux ensembles constitue la réserve de place nécessaire pour utiliser deux fois la densité.',
        'Ā=B̄=E, A ouvert ⇒ (A∩B)̄=E',
        'Fixer une boule B(x,r). Par densité de A, elle contient a∈A. L’ensemble B(x,r)∩A est ouvert et contient a, donc contient B(a,ρ) pour un ρ>0. Par densité de B, cette dernière boule contient b∈B. Alors b∈A∩B∩B(x,r), ce qui prouve la densité. Sans ouverture, ℚ et ℝ∖ℚ sont deux parties denses d’intersection vide.',
        'La réunion infinie qui perd sa limite',
        'Déterminer ⋃n≥1[1/n,1] et son adhérence. Donner une suite qui prouve que cette réunion n’est pas fermée et distinguer l’union de son adhérence.',
        'Chaque réel x∈]0,1] appartient à [1/n,1] pour n≥1/x ; zéro n’appartient à aucun terme. La réunion est donc ]0,1], son adhérence [0,1]. La suite 1/n est dans la réunion et converge vers zéro, absent de celle-ci. L’adhérence ajoute la limite, tandis que l’union demande l’appartenance à au moins un terme.',
        'Intersections finies de denses ouverts',
        'Dans ℝ, montrer que l’intersection d’un nombre fini d’ouverts denses est dense. Pourquoi cette preuve ne permet-elle pas de conclure pour les ouverts denses ℝ∖{qₙ}, où (qₙ) énumère ℚ, avec une simple récurrence finie ?',
        'L’exercice 8 et une récurrence donnent l’assertion finie, puisque l’intersection obtenue reste ouverte. L’intersection infinie vaut ℝ∖ℚ, dense mais non ouverte. Chaque étape finie possède un rayon intérieur ; aucun rayon commun positif ne découle de la récurrence. La densité de cette intersection infinie peut être prouvée ici directement par les irrationnels, ou par le théorème de Baire sur ℝ complet, théorème supplémentaire.'),
    record('distance_ensemble', 'La distance à un ensemble ne demande pas de projection unique', 'Sup → Spé',
        'Pour A non vide dans un espace métrique, d(x,A)=inf_{a∈A}d(x,a). Il s’agit d’un infimum, et non automatiquement d’un minimum. La fonction x↦d(x,A) est définie partout et renseigne sur l’adhérence de A.',
        'd(x,A)=inf_{a∈A}d(x,a)\n|d(x,A)−d(y,A)|≤d(x,y)\nd(x,A)=0 ⇔ x∈Ā',
        'Pour chaque a∈A, d(x,a)≤d(x,y)+d(y,a). Prendre l’infimum donne d(x,A)≤d(x,y)+d(y,A), puis échanger x et y. Si d(x,A)=0, pour tout ε>0 un a∈A vérifie d(x,a)<ε ; x est adhérent. Réciproquement l’adhérence fournit de tels points pour chaque ε. Pour un compact A, a↦d(x,a) est continue et atteint son minimum ; dans ℝᵈ un fermé non vide suffit également, en restreignant la recherche à une boule bornée.',
        'Pour un disque fermé D(c,r), d(x,D)=max(‖x−c‖₂−r,0). Pour une union de deux disques, prendre le minimum des deux distances. Sur la médiatrice de deux disques disjoints, les deux projections peuvent être distinctes : la distance est toujours continue, alors que le choix d’un point projeté peut sauter.',
        'Existence et unicité d’un point le plus proche sont deux problèmes distincts',
        'Une projection minimisante p appartient à A et vérifie d(x,p)=d(x,A). Un ensemble non convexe peut admettre plusieurs minimisants. Un ensemble non fermé peut n’en admettre aucun, même si la distance est nulle.',
        'A=]0,1[, x=0 : d(x,A)=0 sans minimum\nA={−1,1}, x=0 : deux projections, −1 et 1',
        'Le premier cas suit de 1/n→0 sans appartenance de zéro. Dans le second, les distances sont toutes deux 1. En dimension finie, un fermé assure l’existence, tandis que la convexité et la stricte convexité de la norme euclidienne assurent l’unicité. En norme 1 ou ∞, un convexe fermé peut posséder plusieurs points minimisants : l’unicité doit toujours être reliée à la géométrie de la norme.',
        'Une union de disques : deux points également proches',
        'D₋ et D₊ sont les disques fermés de rayon 1/2 centrés en (−2,0) et (2,0). Calculer d((0,1),D₋∪D₊) et les deux projections.',
        'Les deux centres sont à distance √5. La distance cherchée vaut √5−1/2. Les projections sont p₋=(−2,0)+(1/(2√5))(2,1) et p₊=(2,0)+(1/(2√5))(−2,1). Elles sont distinctes et réalisent le même minimum. La fonction distance ne choisit pas entre ces deux points.',
        'La distance à un ouvert dense',
        'Soit A=ℝ∖ℤ. Calculer d(x,A) pour tout x∈ℝ et comparer avec d(x,ℤ). Peut-on reconstituer A à partir de la seule fonction d(·,A) ?',
        'A est dense, donc d(x,A)=0 pour tout x. La distance à ℤ vaut min(|x−⌊x⌋|,|x−⌈x⌉|) et n’est nulle que sur ℤ. La fonction distance à A caractérise Ā, pas A lui-même : A et ℝ ont la même fonction distance, identiquement nulle.'),
    record('convexite', 'Convexe : un segment entier doit rester dans l’ensemble', 'Sup → Spé',
        'Dans un espace vectoriel réel, C est convexe si tout segment reliant deux de ses points reste dans C. Sur un espace complexe, la convexité utilise également des coefficients réels t∈[0,1]. Une vérification numérique de quelques points du segment ne prouve pas cette propriété universelle.',
        'C convexe ⇔ ∀x,y∈C, ∀t∈[0,1], (1−t)x+ty∈C\nConvexe ⇒ connexe par arcs ⇒ connexe',
        'Pour une boule centrée en a, ‖(1−t)x+ty−a‖≤(1−t)‖x−a‖+t‖y−a‖. Cela reste ≤r pour une boule fermée et <r pour une boule ouverte, extrémités comprises. Le segment γ(t)=(1−t)x+ty est continu et relie x à y, d’où la connexité par arcs. Cette dernière implique la connexité, car une séparation de l’ensemble induirait une séparation de l’intervalle [0,1].',
        'L’anneau {1/2≤‖x‖₂≤1} n’est pas convexe : les points (0,8;0) et (−0,8;0) y appartiennent, mais leur milieu est zéro, exclu. Pourtant on les relie par un demi-cercle dans l’anneau. Un seul segment défaillant suffit à réfuter la convexité ; aucun nombre fini de segments réussis ne suffit à l’établir.',
        'Intersections de convexes et ensembles étoilés',
        'Une intersection quelconque de convexes est convexe. Un ensemble étoilé possède un point c depuis lequel tous les segments restent dans l’ensemble ; il est donc connexe par arcs, sans être nécessairement convexe.',
        'Cᵢ convexes ⇒ ⋂ᵢCᵢ convexe\nÉtoilé de centre c : ∀x∈A, [c,x]⊂A',
        'Si x et y appartiennent à tous les Cᵢ, chaque combinaison convexe appartient à tous les Cᵢ. Pour un ensemble étoilé, relier x à c puis c à y par deux segments fournit un chemin. Le critère étoilé ne demande rien sur le segment direct entre x et y. L’ensemble des matrices diagonalisables est étoilé de centre zéro : tA reste diagonalisable ; il est ainsi connexe par arcs, même si une somme de matrices diagonalisables peut ne pas l’être.',
        'Un convexe défini par quatre contraintes',
        'Montrer que C={(x,y): x≥0, y≥0, x+y≤3, 2x+y≤4} est convexe et compact. Déterminer ses sommets et donner un point intérieur.',
        'Chaque contrainte définit un demi-plan fermé convexe ; l’intersection est donc fermée et convexe. Elle est bornée par 0≤x≤2 et 0≤y≤3, donc compacte. Les sommets sont (0,0), (2,0), (1,2), (0,3). Le point (1/2,1/2) satisfait strictement toutes les contraintes, donc possède un voisinage contenu dans C.',
        'Une union qui n’est pas automatiquement convexe',
        'Donner deux convexes compacts de ℝ² dont la réunion est non convexe. Déterminer une condition suffisante simple pour que leur réunion soit convexe.',
        'Deux disques de rayon 1/2 centrés en (−2,0) et (2,0) sont convexes compacts, mais le milieu de leurs centres manque leur réunion. Une condition suffisante est l’inclusion de l’un dans l’autre : la réunion est alors le plus grand. L’intersection non vide seule ne suffit pas ; deux disques qui se chevauchent faiblement peuvent encore laisser manquer un segment entre leurs bords extérieurs.'),
    record('enveloppe_convexe', 'L’enveloppe convexe rassemble tous les barycentres', 'Sup → Spé',
        'Pour des points a₁,…,aₘ de ℝᵈ, leur enveloppe convexe est le plus petit convexe qui les contient. Les poids d’un barycentre sont positifs ou nuls et leur somme vaut 1. Un barycentre à poids quelconques peut sortir du polytope : les signes ne sont pas un détail.',
        'conv{a₁,…,aₘ}={Σᵢλᵢaᵢ : λᵢ≥0, Σᵢλᵢ=1}\nΔₘ={λ∈ℝᵐ : λᵢ≥0, Σᵢλᵢ=1}',
        'L’ensemble des barycentres contient les aᵢ et est convexe : une combinaison de deux familles de poids admissibles reste admissible. Tout convexe contenant les points contient leurs combinaisons convexes finies, par récurrence sur le nombre de termes. Ce double argument établit la minimalité. Δₘ est fermé borné ; l’application λ↦Σλᵢaᵢ est continue, donc l’enveloppe d’un ensemble fini est compacte.',
        'Le nuage généré possède N points, mais seuls les sommets extrêmes définissent le bord du polygone. Les points intérieurs restent utiles pour des barycentres sans créer de nouvelles arêtes. L’algorithme de chaînes monotones utilise le signe d’un déterminant pour supprimer les tournants qui ne délimitent pas le bord convexe.',
        'Carathéodory réduit le nombre de points utiles',
        'Dans ℝᵈ, tout point d’une enveloppe convexe s’exprime à l’aide d’au plus d+1 points. Dans le plan, trois suffisent pour un barycentre ; cela ne signifie pas que le polygone entier possède trois sommets.',
        'x∈conv(A) ⇒ x=Σᵢ₌₁ᵈ⁺¹λᵢaᵢ, λᵢ≥0, Σλᵢ=1',
        'Si une combinaison utilise m>d+1 poids strictement positifs, les vecteurs (aᵢ,1) de ℝᵈ⁺¹ sont liés. Il existe μ non nul tel que Σμᵢaᵢ=0 et Σμᵢ=0. Faire varier les poids λᵢ−tμᵢ ne change ni x ni leur somme. Choisir t=min_{μᵢ>0}λᵢ/μᵢ rend au moins un poids nul sans en rendre aucun négatif. Répéter jusqu’à m≤d+1. Ce résultat est un prolongement au-delà des techniques usuelles de barycentre.',
        'Un barycentre dans un quadrilatère',
        'Pour A=(0,0), B=(3,0), C=(3,2), D=(0,2), calculer le barycentre de poids (1/10,2/10,3/10,4/10). Exprimer le résultat avec seulement trois des sommets.',
        'Le point vaut (3×5/10,2×7/10)=(1,5;1,4). Il s’exprime avec B,C,D de poids 0,3, 0,2 et 0,5 : x=3(0,3+0,2)=1,5 et y=2(0,2+0,5)=1,4. Les poids sont non négatifs et leur somme vaut 1. Plusieurs représentations barycentriques sont possibles dans un polygone.',
        'Pourquoi un poids négatif est dangereux',
        'Pour a=(0,0), b=(1,0), c=(0,1), déterminer conv{a,b,c}. Le point 2b−c est-il dans cette enveloppe malgré une somme de coefficients égale à 1 ?',
        'L’enveloppe est le triangle x≥0, y≥0, x+y≤1. Le point 2b−c=(2,−1) est hors du triangle, car son ordonnée est négative. Les coefficients (0,2,−1) ont bien une somme égale à 1 mais ne sont pas tous non négatifs : ils définissent une combinaison affine, pas convexe.'),
    record('projection_convexe', 'La projection euclidienne se caractérise par un angle', 'Spé',
        'C est un convexe fermé non vide de ℝᵈ euclidien, x un point et p sa projection. Le minimum de la distance existe ; son unicité utilise le carré de la norme euclidienne. La condition angulaire compare x−p à toutes les directions z−p de C.',
        'p=P_C(x) ⇔ p∈C et ∀z∈C, ⟨x−p,z−p⟩≤0',
        'L’existence découle d’une suite minimisante bornée et de la compacité d’une boule fermée en dimension finie. Pour la nécessité, p+t(z−p)∈C et la dérivée à droite de ‖x−p−t(z−p)‖² en t=0 doit être positive ou nulle, soit −2⟨x−p,z−p⟩≥0. Pour la suffisance, développer ‖x−z‖²=‖x−p‖²+‖z−p‖²−2⟨x−p,z−p⟩≥‖x−p‖². L’inégalité est stricte si z≠p, donc p est unique.',
        'Pour un polytope à sommets vⱼ, l’expression ⟨x−p,z−p⟩ est affine en z. Vérifier l’inégalité sur tous les sommets suffit alors pour tous leurs barycentres. Le laboratoire peut donc certifier une propriété universelle par un nombre fini de contraintes, grâce à cette structure analytique, et non grâce à un maillage du bord.',
        'La projection ne dilate pas les distances',
        'Pour x,y∈ℝᵈ, les projections p=P_C(x), q=P_C(y) satisfont une borne plus précise que la continuité. Elle joue un rôle dans les algorithmes de descente et de point fixe.',
        '‖P_C(x)−P_C(y)‖₂²≤⟨P_C(x)−P_C(y),x−y⟩\n‖P_C(x)−P_C(y)‖₂≤‖x−y‖₂',
        'La caractérisation donne ⟨x−p,q−p⟩≤0 et ⟨y−q,p−q⟩≤0. Les additionner et réorganiser produit ‖p−q‖²≤⟨p−q,x−y⟩. Cauchy–Schwarz donne la borne lipschitzienne, en divisant par ‖p−q‖ si elle n’est pas nulle. Ce résultat demande une norme issue d’un produit scalaire et un convexe fermé.',
        'Projeter sur un rectangle',
        'Pour C=[−1,1]×[−2,2] et x=(3,−4), calculer la projection, la distance et vérifier la condition angulaire pour tout z∈C.',
        'La projection vaut p=(1,−2), obtenue en ramenant séparément chaque coordonnée dans son intervalle. La distance vaut √8. Pour z=(z₁,z₂), ⟨x−p,z−p⟩=2(z₁−1)−2(z₂+2)≤0 car z₁≤1 et z₂≥−2. Cette inégalité prouve directement la minimalité et l’unicité.',
        'Un triangle : vérifier seulement trois sommets',
        'Soit C=conv{(0,0),(3,0),(0,3)} et x=(2,2). Proposer p, puis vérifier la condition sur les sommets avant de conclure.',
        'La projection orthogonale sur x₁+x₂=3 donne p=(1,5;1,5), qui appartient à l’arête. x−p=(0,5;0,5). Les produits scalaires avec les trois sommets moins p valent −1,5, 0 et 0. Toute combinaison convexe conserve leur signe, donc la caractérisation prouve p=P_C(x). La distance vaut √0,5.'),
    record('connexite_chemins', 'Un trou empêche un segment, pas forcément un chemin', 'Sup → Spé',
        'Un chemin dans A est une application continue γ:[0,1]→A. A est connexe par arcs si toute paire de points se relie par un chemin. A est connexe si l’on ne peut le partager en deux ouverts relatifs non vides disjoints. Une droite épointée se sépare ; un plan épointé permet de contourner le point retiré.',
        'A connexe ⇔ aucune partition A=U⊔V avec U,V ouverts relatifs non vides\nγ(0)=a, γ(1)=b et γ([0,1])⊂A',
        'Dans ℝ²∖{0}, on relie a à a/‖a‖ par un segment radial de rayon strictement positif, puis les directions a/‖a‖ et b/‖b‖ par un arc de cercle, puis b/‖b‖ à b. Les raccords sont continus et restent hors de zéro. On peut aussi choisir un point c hors des droites ℝa et ℝb et utiliser les deux segments [a,c] et [c,b]. Sur ℝ∖{0}, les parties ]−∞,0[ et ]0,+∞[ constituent une séparation.',
        'L’anneau fermé est connexe par arcs mais non convexe. Deux disques fermés séparés par un écart positif sont chacun connexes et forment deux composantes distinctes. Les chemins dessinés sont construits par des formules ; leurs propriétés ne se déduisent pas du seul nombre de pixels.',
        'Exercice 7 : ℝ et ℝ² ne sont pas homéomorphes',
        'Un homéomorphisme est une bijection continue dont l’inverse est continu. Il conserve la connexité et la connexité par arcs, également après retrait de points correspondants.',
        'ℝ²∖{0} connexe par arcs ; ℝ∖{a} non connexe\nDonc ℝ² et ℝ ne sont pas homéomorphes',
        'Supposons h:ℝ²→ℝ homéomorphisme et posons a=h(0). Sa restriction serait un homéomorphisme de ℝ²∖{0} sur ℝ∖{a}. L’image continue d’un connexe est connexe : une séparation de l’image se tirerait en arrière en une séparation du départ. Or ℝ∖{a}=]−∞,a[⊔]a,+∞[ est séparé, contradiction. Ce raisonnement distingue cardinalité et topologie : ℝ et ℝ² possèdent pourtant le même cardinal.',
        'Deux segments hors de zéro',
        'Relier a=(2,0) à b=(−3,0) dans ℝ²∖{0} par un chemin formé de deux segments. Donner une paramétrisation continue explicite et vérifier qu’elle ne rencontre pas zéro.',
        'Choisir c=(0,1). Pour t∈[0,1/2], γ(t)=(1−2t)a+2tc ; pour t∈[1/2,1], γ(t)=(2−2t)c+(2t−1)b. Les deux formules valent c au raccord. Sur le premier segment, l’ordonnée est positive sauf à a ; sur le second, elle est positive sauf à b. Les extrémités sont non nulles, donc zéro n’est jamais atteint.',
        'Un réel continu sur un anneau prend toutes les valeurs intermédiaires',
        'Sur A={1≤x²+y²≤4}, prendre f(x,y)=x. Déterminer f(A) puis justifier que f ne peut sauter une valeur entre −2 et 2, même si A n’est pas convexe.',
        'Tout point de A vérifie |x|≤2. Chaque c∈[−2,2] est l’abscisse d’un point du cercle extérieur : (c,√(4−c²))∈A. Donc f(A)=[−2,2]. Plus généralement A est connexe par arcs et f continue ; le TVI appliqué à f∘γ sur un chemin relie deux valeurs et garantit toutes les valeurs intermédiaires. La convexité n’est pas nécessaire.'),
    record('bolzano_weierstrass', 'Bolzano–Weierstrass extrait, il ne fait pas converger toute la suite', 'Sup → Spé',
        'Toute suite bornée de ℝᵈ possède une sous-suite convergente. La conclusion porte sur une extraction φ strictement croissante. La suite initiale peut continuer à osciller ; la limite extraite appartient à l’adhérence des valeurs, pas nécessairement à l’ensemble où elles étaient prises.',
        'Suite bornée dans ℝᵈ ⇒ ∃φ strictement croissante, ∃ℓ∈ℝᵈ, xφ(n)→ℓ',
        'En dimension un, enfermer les valeurs dans un intervalle fermé I₀. Diviser en deux et garder une moitié contenant une infinité de termes. Répéter : les Iₖ sont emboîtés, fermés et de longueur |I₀|/2ᵏ. Leur intersection contient un unique ℓ. Choisir nₖ>nₖ₋₁ avec x_nₖ∈Iₖ ; alors |x_nₖ−ℓ|≤|I₀|/2ᵏ. En ℝᵈ, extraire successivement pour chaque coordonnée ; une extraction d’une suite déjà convergente conserve sa limite.',
        'Le laboratoire choisit uₙ=(−1)ⁿ+1/(n+1) et extrait les indices pairs et impairs. Les limites sont respectivement 1 et −1, avec erreur exacte 1/(n+1), sans qu’il soit nécessaire de deviner la limite sur un nuage. La preuve de bissection précédente traite aussi des suites moins explicites. Une suite bornée de matrices 4×4 se traite comme une suite de 16 coordonnées.',
        'Boule fermée et sphère : la bonne extraction à deux étages',
        'Dans un espace normé non nul, la boule unité fermée est compacte si et seulement si la sphère unité est compacte. Pour le sens difficile, il faut extraire simultanément les directions et les rayons, en gérant les termes nuls.',
        'xₙ=rₙvₙ, rₙ=‖xₙ‖∈[0,1], ‖vₙ‖=1 lorsque xₙ≠0',
        'Si la boule est compacte, la sphère est fermée dans cette boule, donc compacte. Réciproquement, si une suite de la boule possède une infinité de termes nuls, elle a une sous-suite constante. Sinon retirer un préfixe et écrire xₙ=rₙvₙ. Extraire les directions par compacité de la sphère, puis extraire les rayons de la sous-suite obtenue par compacité de [0,1]. Le produit converge vers rv dans la boule. Il faut réutiliser les mêmes indices pour les deux facteurs.',
        'Trois limites cachées dans quatre classes d’indices',
        'Pour xₙ=((−1)ⁿ,cos(nπ/2)) dans ℝ², déterminer les valeurs prises, les limites d’adhérence et une extraction vers chacune.',
        'Selon n modulo 4, les valeurs sont (1,1), (−1,0), (1,−1), (−1,0). Les trois limites d’adhérence distinctes sont donc (1,1), (−1,0), (1,−1), et non quatre malgré quatre classes d’indices. Les extractions n=4k, n=4k+1 et n=4k+2 sont constantes. La suite entière ne converge pas.',
        'Une limite en dehors de l’ensemble initial',
        'Une suite prend ses valeurs dans A=]0,1[ et est bornée. Bolzano–Weierstrass assure-t-il une limite extraite dans A ? Donner un contre-exemple et la condition supplémentaire qui réparerait la conclusion.',
        'La suite xₙ=1/(n+2) converge vers zéro, hors de A ; toutes ses sous-suites ont la même limite. BW ne promet qu’une limite dans ℝ. Si A est fermé et borné dans ℝᵈ, toute limite extraite appartient à A : A est compact. La fermeture complète précisément l’hypothèse manquante.'),
    record('extraction_aleatoire', 'Le TP p.17 : records aléatoires et extraction rigoureuse', 'Sup → Spé',
        'On génère des variables indépendantes Uₙ uniformes sur [0,3] et cherche à approcher une cible a intérieure. Un record rapproche le point retenu de a ; une extraction doit en plus conserver des indices strictement croissants. Une simulation finie ne prouve ni une convergence presque sûre ni l’existence d’une infinité de records.',
        '0<ε≤min(a,3−a) : P(|Uₙ−a|<ε)=2ε/3\nP(aucun succès dans m essais)=(1−2ε/3)ᵐ',
        'Pour ε fixé, l’indépendance fait tendre la probabilité d’absence de succès vers zéro lorsque m→∞. Pour chaque k≥1, le rayon εₖ=min(1/k,a/2,(3−a)/2)>0 définit une infinité de succès presque sûrement : la probabilité de ne plus avoir de succès après un rang donné est zéro. L’intersection dénombrable de ces événements de probabilité un garde la probabilité un. On choisit alors nₖ>nₖ₋₁ avec |U_nₖ−a|<εₖ, ce qui construit une sous-suite convergeant vers a presque sûrement.',
        'La cible vaut 1 dans le recueil. Les lots géométriquement croissants facilitent la recherche, mais une étape peut ne pas améliorer le record. La version garantie par bissection du labo BW ne choisit pas une cible d’avance ; le modèle aléatoire justifie au contraire, sous indépendance et loi uniforme, pourquoi la cible choisie peut être atteinte par une extraction.',
        'Prévoir un budget d’essais avant de lancer',
        'La distance du meilleur point parmi m essais peut être étudiée exactement pour de petits rayons qui ne touchent pas les bords. Cela fournit une garantie probabiliste et non une certitude sur une réalisation particulière.',
        'Dₘ=min₁≤j≤m|Uⱼ−a|\nP(Dₘ>ε)=(1−2ε/3)ᵐ, 0<ε≤min(a,3−a)',
        'Dₘ>ε signifie que les m essais évitent tous l’intervalle ]a−ε,a+ε[. Les événements sont indépendants, d’où le produit des probabilités. Pour 0<α<1 et 2ε<3, imposer P(Dₘ≤ε)≥1−α demande m≥ln(α)/ln(1−2ε/3), arrondi à l’entier supérieur. Dans le cas a=3/2, ε=3/2, la probabilité par essai vaut 1 : un essai suffit presque sûrement, sans utiliser un logarithme de zéro. Si le voisinage déborde [0,3], sa longueur réelle d’intersection remplace 2ε.',
        'Atteindre 1 à 0,01 près avec 99 % de confiance',
        'Pour a=1, ε=0,01 et des essais indépendants uniformes sur [0,3], donner un budget suffisant pour une probabilité de succès au moins 0,99. Ce résultat exclut-il tout échec ?',
        'Il faut m≥ln(0,01)/ln(1−0,02/3)≈688,47, donc 689 essais suffisent. La probabilité d’échec reste positive mais ≤0,01. Un échec dans la simulation ne réfute pas la formule ; il est une réalisation possible. Répéter le test avec des graines différentes ne transforme pas une confiance statistique en preuve déterministe.',
        'La cible située au bord',
        'Reprendre a=0 et 0<ε<3. Calculer la probabilité de succès d’un essai et le budget pour ε=0,01, confiance 99 %. Pourquoi le facteur 2 disparaît-il ?',
        'Le voisinage intersecté avec [0,3] est [0,ε[, de longueur ε : la probabilité vaut ε/3. Le budget est ceil[ln(0,01)/ln(1−0,01/3)]=1380. Au bord, une seule moitié du voisinage contient des valeurs possibles. La formule intérieure 2ε/3 ne s’applique donc pas.'),
    record('cauchy_rationnels', 'Cauchy ne signifie convergent que dans un espace complet', 'Sup → Spé',
        'Une suite de Cauchy rapproche tous ses termes suffisamment tardifs entre eux, sans annoncer encore de point limite dans l’espace étudié. La suite rationnelle de Newton u₀=2, uₙ₊₁=uₙ/2+1/uₙ reste dans ℚ et tend vers √2 dans ℝ ; elle fournit le contre-exemple du recueil à la complétude de ℚ.',
        'Cauchy : ∀ε>0, ∃N, ∀m,n≥N, d(uₘ,uₙ)<ε\nuₙ₊₁−√2=(uₙ−√2)²/(2uₙ)',
        'Les uₙ sont rationnels positifs. L’identité affichée donne uₙ≥√2 ; de plus uₙ₊₁−uₙ=(2−uₙ²)/(2uₙ)≤0. La suite décroît et converge dans ℝ vers ℓ≥√2 ; passer à la limite dans la récurrence donne ℓ²=2. Toute suite convergente est de Cauchy par d(uₘ,uₙ)≤d(uₘ,ℓ)+d(uₙ,ℓ). Aucune limite rationnelle n’est possible, car une éventuelle limite dans ℚ serait également √2 dans ℝ, par unicité.',
        'Les étapes sont u₁=3/2, u₂=17/12, u₃=577/408. Si √2=p/q avec p,q premiers entre eux, p²=2q² impose p pair, puis q pair, contradiction : la limite n’est pas rationnelle. Le labo conserve les fractions exactes ; un affichage décimal fini ne peut prouver cette irrationalité ni l’égalité exacte à √2.',
        'Fermés et sous-espaces complets',
        'Toute partie complète d’un espace métrique est fermée dans cet espace. Dans un espace complet, toute partie fermée est complète. On doit conserver l’hypothèse de complétude de l’espace ambiant pour le second sens.',
        'A complet ⇒ A fermé dans E\nE complet et A fermé ⇒ A complet\nE complet ⇔ toute suite de Cauchy converge dans E',
        'Si aₙ∈A tend dans E vers x, elle est de Cauchy ; la complétude de A donne une limite a∈A, et l’unicité impose x=a. Ainsi A est fermé. Réciproquement une suite de Cauchy de A converge dans E par complétude de E ; la fermeture de A place cette limite dans A. Un espace normé complet est appelé Banach.',
        'Une borne rationnelle du défaut de Newton',
        'En partant de u₀=2, montrer que eₙ=uₙ−√2 satisfait eₙ₊₁≤eₙ²/2. Déduire une convergence plus rapide qu’une simple décroissance géométrique une fois eₙ≤1/2.',
        'Comme uₙ≥√2>1, l’identité donne eₙ₊₁=eₙ²/(2uₙ)≤eₙ²/2. Si eₙ≤1/2, alors eₙ₊₁≤eₙ/4, mais le facteur eₙ/2 devient lui-même de plus en plus petit. C’est une convergence quadratique. Cette rapidité ne rend pas √2 rationnel : chaque approximation reste rationnelle sans que sa limite le soit.',
        'Fermé dans ℚ et pourtant incomplet',
        'A=ℚ∩[1,2], muni de la distance usuelle. Montrer qu’il est fermé et borné dans ℚ mais incomplet et non compact.',
        'A est l’intersection avec ℚ d’un fermé de ℝ, donc fermé relativement à ℚ ; il est borné. La suite rationnelle de Newton partant de 2 reste dans A et est de Cauchy, mais sa seule limite réelle est √2, hors de ℚ. A est incomplet. Un compact métrique étant complet, il n’est pas compact. La caractérisation fermé borné des compacts exige ℝᵈ ou ℂᵈ, et ne s’étend pas à ℚ.'),
    record('compacts_recouvrements', 'Compact : toute suite possède une limite extraite dans l’ensemble', 'Sup → Spé',
        'En espace métrique, la compacité peut se définir par extraction de suites, ou par recouvrements ouverts : tout recouvrement ouvert admet un sous-recouvrement fini. Dans ℝᵈ et ℂᵈ, ces propriétés équivalent à « fermé et borné ». En dimension infinie, fermé et borné ne suffit plus.',
        'K compact ⇔ ∀(xₙ)∈K^ℕ, ∃φ strictement croissante, xφ(n)→x∈K\nK⊂⋃ᵢUᵢ ⇒ K⊂Uᵢ₁∪…∪Uᵢₘ pour un nombre fini d’indices',
        'Un compact métrique est borné : sinon choisir d(xₙ,a)>n, ce qui interdit toute sous-suite convergente. Il est fermé : pour une suite de K convergeant vers x, une extraction converge dans K et son unique limite est x. Dans ℝᵈ, réciproquement BW donne une limite extraite pour toute suite d’un fermé borné ; la fermeture garde cette limite dans K. L’équivalence avec les recouvrements ouverts est un théorème des espaces métriques, développé dans la leçon suivante.',
        'Dans le labo, les ouverts centrés aux j/m, j=0,…,m, couvrent [0,1] exactement lorsque r>1/(2m) : au seuil d’égalité, les milieux des mailles restent exclus. Les Uₙ=]−1,1−1/n[ recouvrent [0,1[ mais aucune réunion finie ne suffit. Une collection finie de points dessinés admet toujours un sous-recouvrement fini, même si l’ensemble infini étudié n’est pas compact.',
        'Pourquoi les recouvrements détectent les suites',
        'Dans un espace métrique, la compacité séquentielle implique la précompacité : pour tout ε>0, un nombre fini de boules de rayon ε couvre K. Elle permet ensuite de passer d’un recouvrement arbitraire à un sous-recouvrement fini.',
        'K compact ⇒ ∀ε>0, K couvert par un nombre fini de boules de rayon ε\nRecouvrement ouvert de K ⇒ ∃δ>0 : chaque B_K(x,δ) est incluse dans un membre',
        'Si aucune couverture finie par boules de rayon ε n’existe, choisir xₙ en dehors des boules centrées aux points précédents : les distances mutuelles sont ≥ε, donc aucune sous-suite ne converge. Pour le second fait, s’il échouait, choisir xₙ dont la boule de rayon 1/n n’est contenue dans aucun membre. Extraire xₙ→x ; un ouvert du recouvrement contenant x contient B_K(x,r). Pour n assez grand, B_K(xₙ,1/n)⊂B_K(x,r), contradiction. Une couverture finie par boules de rayon δ donne alors un sous-recouvrement fini.',
        'Un recouvrement sans extraction finie',
        'Vérifier que Uₙ=]1/n,1[, n≥2, recouvrent ]0,1[. Montrer qu’aucun sous-recouvrement fini n’existe. Comment adapter un recouvrement pour rendre visible le rôle de zéro dans [0,1] ?',
        'Pour x>0, choisir n>1/x : x∈Uₙ. Une union finie est contenue dans ]1/N,1[ où N est le plus grand indice choisi, et manque 1/(2N). Ces mêmes Uₙ ne recouvrent pas [0,1], car zéro et un sont absents. Tout véritable recouvrement ouvert de [0,1] doit aussi contenir des ouverts autour de ces extrémités ; leur marge permet la compacité.',
        'Une marge positive dans une boule ouverte',
        'K est un compact non vide d’un espace normé, inclus dans Bₒ(0,1). Prouver qu’il existe r<1 avec K⊂B𝒇(0,r). Pourquoi un ensemble simplement borné ne suffit-il pas ?',
        'La norme est continue et atteint un maximum r sur K. Puisque chaque point de K a une norme strictement inférieure à 1, le maximum atteint vérifie r<1. L’ensemble {1−1/n:n≥2}⊂ℝ est borné et inclus dans ]−1,1[, mais son supremum vaut 1, non atteint ; aucune marge r<1 ne le contient. C’est l’atteinte du maximum, non la seule bornitude, qui produit la marge.'),
    record('valeurs_extremes', 'Un compact transforme les infimums en minimums', 'Sup → Spé',
        'Pour f:K→ℝ continue sur un compact non vide, les extrema existent et sont atteints. Trois hypothèses sont à vérifier séparément : K non vide, K compact, f continue. Un graphique sur un segment peut suggérer un extremum, mais une extrémité exclue ou une discontinuité change la conclusion.',
        '∃x₋,x₊∈K, ∀x∈K, f(x₋)≤f(x)≤f(x₊)',
        'L’image continue d’un compact est compacte, donc f(K) est un fermé borné de ℝ. Son supremum M existe. Choisir yₙ∈f(K) avec M−1/n<yₙ≤M ; comme f(K) est fermé, M∈f(K). Il existe donc x₊ avec f(x₊)=M ; même argument pour le minimum. On peut aussi extraire une suite maximisante dans K puis utiliser la continuité.',
        'Le labo maximise ℓθ(x,y)=x cosθ+y sinθ sur x²/a²+y²/b²≤1, a,b>0. Poser x=au,y=bv et appliquer Cauchy–Schwarz donne M=√(a²cos²θ+b²sin²θ), atteint en (a²cosθ/M,b²sinθ/M). Sur le domaine strict <1, M reste le supremum mais n’est pas atteint ; multiplier le point extremal par 1−1/N construit une suite maximisante.',
        'Coercivité et existence d’un minimiseur',
        'Une fonction continue f:ℝᵈ→ℝ est coercive si f(x)→+∞ lorsque ‖x‖→+∞. Elle possède alors un minimum global, même si le domaine n’est pas compact.',
        '∀M∈ℝ, ∃R>0, ‖x‖≥R ⇒ f(x)≥M\nf coercive et continue ⇒ ∃x*, f(x*)=infℝᵈ f',
        'Choisir M=f(0)+1 et un rayon R tel que hors de la boule de rayon R, f≥M. Sur la boule fermée, f atteint son minimum m≤f(0)<M. Ce minimiseur est global puisque toutes les valeurs extérieures sont plus grandes. En dimension infinie la boule fermée n’est pas forcément compacte, donc ce raisonnement ne se transfère pas tel quel.',
        'Un minimum quartique non convexe',
        'Pour f(x,y)=(x²−1)²+y² sur ℝ², prouver l’existence d’un minimum global et déterminer les minimisants. L’existence impose-t-elle l’unicité ?',
        'f est polynomiale et continue. En posant u=x², (u−1)²−u=(u−3/2)²−5/4≥−5/4, donc f(x,y)≥x²+y²−5/4 : elle est coercive. Comme chaque terme est non négatif, le minimum vaut zéro, atteint exactement en (−1,0) et (1,0). L’existence ne donne donc aucune unicité ; une stricte convexité appropriée serait une hypothèse supplémentaire.',
        'La continuité ne peut être omise',
        'Sur [0,1], définir f(0)=1 et f(x)=x pour x>0. Déterminer infimum et supremum, puis préciser lesquels sont atteints et pourquoi le théorème des extrema ne s’applique pas.',
        'L’infimum vaut zéro sans être atteint, puisque toutes les valeurs sont strictement positives et f(1/n)=1/n→0. Le supremum vaut 1, atteint en 0 et 1. Le domaine est compact non vide, mais f est discontinue en zéro : sa limite à droite vaut zéro alors que f(0)=1. La conclusion complète du théorème manque donc.'),
    record('heine_continuite', 'Heine : un même rayon fonctionne partout sur un compact', 'Sup → Spé',
        'La continuité en a autorise un rayon δ dépendant de a et de ε. La continuité uniforme choisit δ avant tous les couples x,y du domaine. Le théorème de Heine transforme la continuité en continuité uniforme sur un compact ; il ne transforme pas automatiquement une fonction en fonction lipschitzienne.',
        'Continue : ∀a∈A, ∀ε>0, ∃δ>0, ∀x∈A, d(x,a)<δ ⇒ d(f(x),f(a))<ε\nUniforme : ∀ε>0, ∃δ>0, ∀x,y∈A, d(x,y)<δ ⇒ d(f(x),f(y))<ε',
        'Supposons f continue sur K compact mais non uniformément continue. Il existe ε₀>0 et des couples xₙ,yₙ∈K avec d(xₙ,yₙ)<1/n et d(f(xₙ),f(yₙ))≥ε₀. Extraire xₙ→a dans K ; alors yₙ→a par l’inégalité triangulaire. La continuité donne f(xₙ)→f(a), f(yₙ)→f(a), contradiction. L’extraction est l’endroit exact où la compacité intervient.',
        'Le labo choisit f(x)=sin(x²), 2R-lipschitzienne sur [−R,R] car |f′|≤2R. Sur ℝ, les points xₙ=√(2πn) et yₙ=√(2πn+π/2) vérifient yₙ−xₙ=(π/2)/(xₙ+yₙ)→0, mais leurs images valent 0 et 1. La fonction n’est donc pas uniformément continue sur ℝ. La fenêtre d’affichage bornée ne doit pas remplacer le domaine analytique tout entier.',
        'Lipschitz, Hölder et domaine non compact',
        'Une application L-lipschitzienne est uniformément continue. Une borne de type Hölder |f(x)−f(y)|≤C|x−y|ᵅ avec α>0 suffit également. La compacité est une condition suffisante de Heine, pas nécessaire à toute continuité uniforme.',
        '√x sur [0,+∞[ : |√x−√y|≤√|x−y|\nPour ε>0, δ=ε² convient',
        'Si x≥y≥0, (√x−√y)²=x+y−2√xy≤x−y, car y≤√xy. La borne est symétrique et donne la continuité uniforme sur un domaine non compact. Pourtant √x n’est pas lipschitzienne près de zéro : |√x−0|/|x−0|=1/√x est non borné. On sépare ainsi trois notions que le dessin seul peut confondre.',
        'Une oscillation qui détruit l’uniformité',
        'Sur ]0,1], f(x)=sin(1/x). Construire deux suites de points de distance tendant vers zéro et dont les images restent à distance 2.',
        'Prendre xₙ=1/(π/2+2πn) et yₙ=1/(3π/2+2πn). Elles sont positives, tendent vers zéro et leur différence tend vers zéro ; f(xₙ)=1 et f(yₙ)=−1. La continuité uniforme échoue, bien que f soit continue en chaque point du domaine. Le point zéro est hors du domaine et ne peut fournir une extraction dans un compact.',
        'Un rayon explicite pour la racine',
        'Sur [0,4], garantir une variation de √x inférieure à 0,02 avec un rayon uniforme. Peut-on utiliser une dérivée globalement bornée ?',
        'La borne Hölder donne δ=(0,02)²=0,0004 : |x−y|<δ implique |√x−√y|<0,02. La dérivée 1/(2√x) est non bornée près de zéro et n’existe pas finiment en zéro, donc une borne de dérivée uniforme ne convient pas. Heine garantit l’existence d’un rayon, et l’inégalité fournit sa valeur concrète.'),
    record('image_compacte', 'Exercice 6 : produit compact, puis image compacte', 'Spé',
        'A et B sont des compacts métriques, f:A×B→F est continue. Le produit est muni, par exemple, de d((a,b),(a′,b′))=max(d_A(a,a′),d_B(b,b′)). On veut prouver que f(A×B) est compact. Le choix des indices est crucial : deux extractions indépendantes ne s’assemblent pas automatiquement.',
        'A,B compacts ⇒ A×B compact\nf continue ⇒ f(A×B) compact',
        'Pour une suite (aₙ,bₙ), extraire aφ(n)→a∈A. De la suite bφ(n), extraire à nouveau bφ(ψ(n))→b∈B. Les aφ(ψ(n)) convergent encore vers a ; le couple extrait converge donc vers (a,b). Pour une suite zₙ∈f(A×B), choisir un antécédent (aₙ,bₙ) de chaque zₙ ; extraire ces couples et utiliser la continuité. Cette preuve fonctionne pour un nombre fini de facteurs.',
        'L’addition envoie A×B sur la somme de Minkowski A+B. Le labo ajoute une ellipse pleine de demi-axes a,b à un segment [−sv,sv], v=(cosθ,sinθ). Pour w=(cosφ,sinφ), le maximum de ⟨w,z⟩ sur la somme vaut √(a²cos²φ+b²sin²φ)+s|cos(φ−θ)|. Cette fonction d’appui donne des extrema exacts sans mailler toutes les paires du produit.',
        'Deux compacts disjoints sont séparés par une distance positive',
        'Pour A,B compacts non vides et disjoints d’un espace métrique, la distance minimale entre les deux ensembles est strictement positive. « Fermés disjoints » seul ne suffit pas.',
        'dist(A,B)=min_{a∈A,b∈B}d(a,b)>0',
        'La fonction (a,b)↦d(a,b) est continue et atteint un minimum m sur le compact A×B. Si m=0, les points minimisants a et b seraient égaux, contradiction à A∩B=∅. Pour deux fermés non compacts de ℝ², A={(x,0):x∈ℝ}, B={(x,eˣ):x∈ℝ}, les ensembles sont disjoints mais leur distance est zéro, car eˣ→0 quand x→−∞.',
        'Somme d’un cercle et d’un segment',
        'A est le cercle unité de ℝ², B=[−2,2]×{0}. Prouver que A+B est compact sans supposer qu’il soit convexe. Trouver ses abscisses maximale et minimale.',
        'A et B sont fermés bornés donc compacts, et l’addition est continue : A+B est compact par l’exercice 6. Pour a∈A et b∈B, l’abscisse appartient à [−3,3]. Les bornes sont atteintes en a=(±1,0), b=(±2,0), de signes identiques. La preuve de compacité n’utilise pas la convexité ; le cercle lui-même n’est pas convexe.',
        'Des fermés disjoints à distance nulle',
        'Justifier soigneusement que A={(x,0)} et B={(x,eˣ)} sont fermés dans ℝ², puis calculer dist(A,B). Quel point de la preuve compacte manque ici ?',
        'A est l’image réciproque de {0} par (x,y)↦y ; B celle de {0} par (x,y)↦y−eˣ. Ils sont fermés par continuité. Ils sont disjoints puisque eˣ>0, mais les couples (−n,0),(−n,e⁻ⁿ) ont une distance e⁻ⁿ→0 ; l’infimum vaut zéro. La suite minimisante part à l’infini et n’a aucune extraction convergente dans A×B ; le minimum n’est pas atteint.'),
    record('applications_lineaires', 'Une application linéaire est continue si elle possède une borne uniforme', 'Spé',
        'Pour u:E→F linéaire entre espaces normés, la continuité en zéro suffit à la continuité partout. Elle équivaut à l’existence d’un C≥0 vérifiant ‖u(x)‖≤C‖x‖ pour tous les vecteurs. En dimension finie au départ, cette borne existe toujours ; en dimension infinie elle doit être prouvée.',
        'u continue ⇔ u continue en 0 ⇔ ∃C≥0, ∀x∈E, ‖u(x)‖≤C‖x‖\n‖u‖op=sup_{‖x‖≤1}‖u(x)‖',
        'La continuité en zéro avec ε=1 donne δ>0 tel que ‖z‖<δ ⇒ ‖u(z)‖<1. Pour x≠0, appliquer ceci à z=δx/(2‖x‖) donne ‖u(x)‖≤(2/δ)‖x‖. Réciproquement la borne entraîne ‖u(x)−u(y)‖≤C‖x−y‖, donc u est lipschitzienne. Dans une base finie, u(x)=Σxᵢu(eᵢ), et l’inégalité triangulaire avec l’équivalence des normes fournit C.',
        'Pour les matrices réelles denses de dimension 4 à 8 du labo, la norme euclidienne d’opérateur vaut la plus grande valeur singulière. Le laboratoire compare cette borne exacte aux gains de directions testées. Un nombre fini de directions ne donne pas à lui seul le supremum ; la décomposition en valeurs singulières le certifie.',
        'Une application linéaire non continue en dimension infinie',
        'Sur l’espace des polynômes réels muni de la norme uniforme sur [0,1], l’application u(P)=P′(1) est linéaire mais non continue. Les dérivées peuvent amplifier fortement une petite fonction.',
        'Pₙ(x)=xⁿ/n : ‖Pₙ‖∞=1/n→0, u(Pₙ)=1\n‖u∘v‖op≤‖u‖op‖v‖op pour u,v continus',
        'Si u était continue, Pₙ→0 impliquerait u(Pₙ)→0, contradiction. Pour la composition, appliquer ‖u(v(x))‖≤‖u‖op‖v(x)‖≤‖u‖op‖v‖op‖x‖ et prendre le supremum sur la boule unité. La présence de polynômes de degrés arbitraires est précisément ce qui empêche de traiter le premier espace comme un espace de dimension fixe.',
        'Une norme d’opérateur obtenue sans tester mille directions',
        'Pour Q orthogonale 4×4 et A=Q diag(4,2,1,1/2) Qᵀ, calculer ‖A‖op et ‖A⁻¹‖op en norme euclidienne. Donner une direction qui atteint chacun des gains.',
        'Les transformations orthogonales conservent la norme, donc ‖A‖op=4 et ‖A⁻¹‖op=2. Les directions Qe₁ et Qe₄ réalisent respectivement ces gains. Le conditionnement euclidien vaut 8. Ce calcul repose sur la structure spectrale symétrique positive ; pour une matrice générale, utiliser les valeurs singulières, pas uniquement le module des valeurs propres.',
        'Évaluation contre dérivation',
        'Sur les polynômes munis de ‖·‖∞ sur [0,1], comparer v(P)=P(1) et u(P)=P′(1). Pourquoi la linéarité commune ne donne-t-elle pas la même propriété de continuité ?',
        'On a |v(P)|≤‖P‖∞ et la constante 1 est atteinte par P=1, donc v est continue de norme 1. Pour u, les Pₙ=xⁿ/n tendent uniformément vers zéro mais Pₙ′(1)=1 ; u est non continue. La borne uniforme sur la boule unité est le critère pertinent, et non la seule linéarité.'),
    record('normes_dimension_infinie', 'En dimension infinie, le choix de norme change les convergences', 'Spé → au-delà',
        'Sur C([0,1],ℝ), on compare ‖f‖∞=max|f|, ‖f‖₁=∫|f| et ‖f‖₂=√∫|f|². Ces expressions sont des normes sur les fonctions continues : une intégrale nulle impose f=0 par continuité. Elles ne sont pas toutes équivalentes ; un pic peut être haut mais étroit.',
        '‖f‖₁≤‖f‖₂≤‖f‖∞\nfₙ(x)=xⁿ : ‖fₙ‖∞=1, ‖fₙ‖₁=1/(n+1), ‖fₙ‖₂=1/√(2n+1)',
        'La première inégalité résulte de Cauchy–Schwarz sur un intervalle de longueur 1 ; la seconde de |f|≤‖f‖∞. Si les normes 1 et ∞ étaient équivalentes, il existerait C indépendant de f avec ‖f‖∞≤C‖f‖₁. Pour fₙ=xⁿ, cela donnerait 1≤C/(n+1), impossible. Ainsi fₙ→0 pour les normes intégrales mais pas pour la norme uniforme.',
        'Les graphiques présentent des pics dont l’aire décroît tandis que la hauteur reste constante. Les normes exactes sont calculées avant toute quadrature ; un maillage incapable de résoudre le pic n’a pas le droit d’en déduire une norme nulle. Chaque sous-espace de polynômes de degré ≤d possède cependant des normes équivalentes, avec des constantes dépendant de d.',
        'Complétude et complétion dépendent aussi de la norme',
        'C([0,1]) muni de la norme uniforme est complet. Avec une norme intégrale, des suites de fonctions continues peuvent approcher une fonction discontinue dans l’espace complété L¹ ou L². La topologie et la complétude doivent donc être distinguées.',
        'Uniformément Cauchy dans C([0,1]) ⇒ limite continue uniforme\nConvergence L¹ ne garantit pas une limite continue',
        'Une suite uniformément de Cauchy converge point par point par complétude de ℝ. Passer à la limite dans la borne uniforme de Cauchy donne la convergence uniforme vers f. Pour prouver la continuité de f en a, majorer |f(x)−f(a)| par deux erreurs uniformes et |fₙ(x)−fₙ(a)| pour un n fixé. Des rampes continues de largeur 1/n autour de 1/2 approchent au contraire une marche dans L¹ : aucune limite continue ne représente cette marche presque partout.',
        'Une suite de pics normalisés',
        'Pour fₙ(x)=√(2n+1)xⁿ, calculer les normes 1, 2 et ∞. Conclure sur la convergence dans chacune et sur l’équivalence des normes.',
        '‖fₙ‖₂=1, ‖fₙ‖₁=√(2n+1)/(n+1)→0 et ‖fₙ‖∞=√(2n+1)→∞. La suite converge vers zéro en norme 1, ne converge pas vers zéro en norme 2 et est non bornée en norme uniforme. Une convergence dans des normes équivalentes serait simultanée ; ces comportements prouvent leur non-équivalence sur cet espace infini.',
        'Une marche approchée par des fonctions continues',
        'Définir fₙ=0 sur [0,1/2−1/n], affine jusqu’à la valeur 1 en 1/2+1/n, puis constante 1, pour n≥3. Montrer qu’elle approche la marche g=𝟙_{x>1/2} en norme 1, mais pas uniformément.',
        'L’erreur est nulle hors d’une bande de largeur 2/n et vaut au plus 1, donc ‖fₙ−g‖₁≤2/n ; un calcul des deux triangles donne exactement 1/(2n). La norme uniforme de l’erreur vaut 1/2, indépendamment de n, et g est discontinue. Une limite uniforme de fonctions continues serait continue, ce qui exclut également cette convergence uniforme.'),
    record('boule_non_compacte', 'Exercice 9 : une infinité de modes séparés dans la boule unité', 'Spé',
        'E=C([0,2π],ℂ) est muni de la norme ‖f‖₂=(∫|f|²)¹ᐟ². Les modes eₙ(t)=e^(int)/√(2π) sont continus et de norme 1. Deux modes distincts restent à distance √2, quelle que soit leur fréquence : une extraction ne peut les rapprocher.',
        '⟨eₚ,e_q⟩=δpq ; ‖eₙ‖₂=1\np≠q ⇒ ‖eₚ−e_q‖₂²=2',
        'Pour p≠q, ∫₀²πe^(i(p−q)t)dt=[e^(i(p−q)t)/(i(p−q))]₀²π=0. Chaque norme carrée vaut 1 ; développer le carré de la différence donne 1+1−2Re0=2. Toute extraction de modes garde des indices distincts et une distance √2 entre deux termes différents ; elle n’est pas de Cauchy, donc ne converge pas. La boule unité fermée est fermée et bornée mais non compacte : c’est un contre-exemple en dimension infinie.',
        'Le recueil utilise les modes non normalisés uₙ=e^(int), de norme √(2π), et leur distance 2√π. Le passage à eₙ change les valeurs en 1 et √2. Le maillage peut faire apparaître des modes identiques par aliasing ; l’orthogonalité et les distances affichées doivent reposer sur leurs intégrales exactes.',
        'Fermé borné, complet et compact : trois questions',
        'Dans un espace métrique, tout compact est complet et précompact. Une boule en dimension infinie peut manquer de précompacité, même si l’espace ambiant est complet. Le théorème de Riesz caractérise les espaces normés de dimension finie par la compacité de leur boule unité.',
        'E normé sur ℝ ou ℂ : boule unité fermée compacte ⇔ dim E<∞\nCompact métrique ⇔ complet et précompact',
        'Un compact est précompact par le raisonnement des points ε-séparés et complet, car une suite de Cauchy possède une extraction convergente qui entraîne la convergence de la suite entière. Pour des modes séparés de √2, des boules de rayon r<√2/2 ne peuvent chacune contenir deux modes ; aucune couverture finie ne suffit. Ce défaut persiste dans l’espace de Hilbert complet L²([0,2π]), qui contient les mêmes modes.',
        'Retrouver les constantes avant normalisation',
        'Pour uₙ(t)=e^(int), calculer ‖uₙ‖₂ et ‖uₚ−u_q‖₂ pour p≠q. En déduire les résultats normalisés sans perdre le facteur √(2π).',
        '‖uₙ‖₂²=∫₀²π1dt=2π. La distance carrée vaut ∫(2−2cos((p−q)t))dt=4π, donc la distance vaut 2√π. Diviser chaque mode par √(2π) donne norme 1 et distance (2√π)/√(2π)=√2. Ce calcul prouve la non-compacité de la boule unité via la suite normalisée.',
        'Combien de petites boules pour tous les modes ?',
        'Peut-on couvrir tous les eₙ par un nombre fini de boules ouvertes de rayon 0,6 dans la norme 2 ? Comparer avec un dessin de seulement vingt modes.',
        'Deux modes dans une même boule auraient une distance <1,2 par l’inégalité triangulaire, impossible puisque √2≈1,414. Chaque boule contient donc au plus un mode ; une infinité de boules est nécessaire. Vingt modes dessinés se couvrent par vingt boules, ce qui ne fournit aucune couverture de l’ensemble infini et ne prouve aucune compacité.'),
    record('denombrer_rationnels', 'Infini dénombrable : énumérer sans perdre ni répéter', 'Sup',
        'Un ensemble est fini s’il possède un cardinal entier ; il est infini sinon. Un ensemble infini est dénombrable s’il existe une bijection avec ℕ. ℤ, ℕ² et ℚ sont dénombrables, malgré leur apparence très différente. Pour ℚ, représenter chaque nombre sous forme p/q, avec q>0 et pgcd(|p|,q)=1, évite les répétitions.',
        'ℚ={p/q : p∈ℤ, q∈ℕ*, pgcd(|p|,q)=1}\nParcours par hauteurs h=|p|+q ; chaque étage est fini',
        'Pour chaque h≥1, il n’existe qu’un nombre fini de couples avec |p|+q=h. Tous les rationnels possèdent un représentant réduit unique et apparaissent à un étage fini. Ranger les étages dans l’ordre, puis les p dans chaque étage, fournit une liste sans répétition couvrant ℚ. L’infinitude est assurée par l’injection n↦n ; la liste devient donc une bijection avec ℕ. Pour ℕ², le parcours par diagonales n+m constante donne le même mécanisme.',
        'Le panneau de fractions trace seulement les étages jusqu’à une hauteur H. Leur nombre fini est un extrait de l’énumération infinie. La densité de ℚ est une autre propriété : elle parle des voisinages dans ℝ et ne découle pas de la seule énumération.',
        'Une réunion dénombrable d’ensembles dénombrables',
        'Si Aₖ est dénombrable pour chaque k∈ℕ, les éléments se rangent dans un tableau double (k,n). Un parcours diagonal couvre leur union ; on supprime les répétitions éventuelles. Ce mécanisme relie produits et unions dénombrables.',
        'ℕ×ℕ dénombrable ; ⋃k∈ℕAₖ au plus dénombrable\nUn sous-ensemble d’un dénombrable est au plus dénombrable',
        'Une énumération de Aₖ fournit une surjection de ℕ² sur l’union. Composer avec l’énumération diagonale donne une liste ; conserver uniquement la première occurrence de chaque élément donne une injection dans ℕ et, si l’union est infinie, une bijection avec ℕ. Pour un sous-ensemble B⊂ℕ infini, choisir successivement son plus petit élément non encore choisi énumère B.',
        'Les décimaux ne sont pas tous les réels',
        'Montrer que l’ensemble D={p10⁻ⁿ : p∈ℤ,n∈ℕ} des décimaux est dénombrable et dense dans ℝ. Donner un rationnel qui n’est pas décimal.',
        'D est l’image de ℤ×ℕ, donc au plus dénombrable, et contient ℤ donc est infini dénombrable. Pour x∈ℝ, qₙ=⌊10ⁿx⌋10⁻ⁿ vérifie 0≤x−qₙ<10⁻ⁿ, donc qₙ→x. Le rationnel 1/3 n’est pas décimal : si 1/3=p/10ⁿ, alors 10ⁿ=3p, impossible puisque 3 ne divise pas une puissance de 10.',
        'Une liste des couples',
        'Écrire les dix premiers couples de ℕ² en parcourant les diagonales n+m=0,1,2,… avec n croissant. Pourquoi aucun couple n’est-il oublié ?',
        'La liste commence (0,0), (0,1), (1,0), (0,2), (1,1), (2,0), (0,3), (1,2), (2,1), (3,0). Le couple (n,m) apparaît sur la diagonale finie d’indice n+m et y possède une position unique. La construction porte sur toutes les diagonales, même si l’interface n’en affiche qu’un nombre fini.'),
    record('diagonale_cantor', 'La diagonale de Cantor interdit toute liste complète', 'Sup → Spé',
        'Supposer que toutes les suites binaires aient été rangées en lignes s₀,s₁,…, chaque sₙ étant une suite infinie de zéros et uns. La suite d dont le n-ième chiffre est opposé au n-ième chiffre de la n-ième ligne échappe à toutes les lignes. La fenêtre finie illustre ce mécanisme mais n’est pas l’objet du théorème.',
        'dₙ=1−sₙ(n) ; ∀n, d≠sₙ\n{0,1}^ℕ n’est pas dénombrable',
        'Pour chaque n, d diffère de sₙ au moins à la coordonnée n. Si la liste était surjective, d serait égale à une ligne sₖ, mais leur k-ième chiffre est différent, contradiction. Ce raisonnement ne choisit pas « un rang après le dernier » : il change un chiffre de chaque ligne dans une liste infinie. Un tableau N×N ne réfute qu’une liste finie de N mots et ne démontre pas à lui seul la non-dénombrabilité.',
        'Pour relier le tableau à des réels sans ambiguïté d’écriture binaire, encoder les suites dans des chiffres ternaires 0 et 2 : x(s)=Σ₂sₙ/3ⁿ⁺¹. Si deux suites diffèrent au premier rang k, l’écart initial vaut 2/3ᵏ⁺¹ et la queue peut compenser au plus 1/3ᵏ⁺¹ ; l’écart total reste positif.',
        'Cantor : aucun ensemble n’énumère toutes ses parties',
        'Pour toute application f:E→P(E), la partie D={x∈E : x∉f(x)} n’appartient pas à son image. Cette version formule la diagonale sans chiffres et montre |P(E)|>|E| au sens des injections et surjections.',
        'D={x∈E : x∉f(x)}\nSi D=f(a), alors a∈D ⇔ a∉D : contradiction',
        'L’équivalence provient directement de la définition de D. Une injection E→P(E) est donnée par x↦{x}, tandis qu’aucune surjection E→P(E) n’existe par le raisonnement diagonal. En prenant E=ℕ, les parties de ℕ s’identifient à leurs indicatrices binaires, ce qui retrouve le résultat de la première leçon.',
        'Une diagonale explicite dans un tableau',
        'Les quatre premières lignes commencent par 0101, 1100, 0011, 1010. Construire les quatre premiers chiffres de l’antidiagonale et préciser ce qui serait nécessaire pour conclure sur une liste infinie.',
        'Les chiffres diagonaux sont 0,1,1,0 ; l’antidiagonale commence par 1,0,0,1. Ce préfixe distingue le nouveau mot de chacune des quatre lignes au chiffre correspondant. Pour une liste infinie, il faut définir dₙ pour chaque n et utiliser la contradiction à un rang quelconque k ; quatre chiffres seuls ne suffisent pas.',
        'Pourquoi des chiffres ternaires 0 et 2 ?',
        'Deux suites binaires diffèrent pour la première fois au rang k, numéroté à partir de zéro. Minorer l’écart de leurs encodages ternaires. Peut-il être nul à cause de deux écritures d’un même réel ?',
        'La contribution du premier chiffre vaut 2/3ᵏ⁺¹. La queue est majorée par Σn>k2/3ⁿ⁺¹=1/3ᵏ⁺¹. L’écart total est donc au moins 1/3ᵏ⁺¹>0. L’encodage est injectif. L’ambiguïté générale des écritures ternaires met en jeu un chiffre 1 dans l’écriture concurrente ; elle n’identifie pas deux suites distinctes utilisant uniquement 0 et 2.'),
    record('ensemble_cantor', 'Le compact de Cantor : énormément de points, aucun intervalle', 'Sup → Spé',
        'On part de C₀=[0,1] et enlève le tiers ouvert central de chaque intervalle à chaque étape. Cₙ est la réunion de 2ⁿ intervalles fermés de longueur 3⁻ⁿ. Le compact limite C=⋂Cₙ est non dénombrable, d’intérieur vide et totalement discontinu : ses composantes connexes sont des singletons.',
        'C=⋂n≥0Cₙ ; longueur totale de Cₙ=(2/3)ⁿ\nC={Σn≥0 2sₙ/3ⁿ⁺¹ : sₙ∈{0,1}}',
        'Chaque Cₙ est fermé dans [0,1], donc l’intersection est un fermé borné de ℝ, compact et non vide (elle contient 0 et 1). L’encodage ternaire injectif de toutes les suites binaires prouve la non-dénombrabilité. Aucun intervalle non trivial ne reste dans C : si sa longueur est >3⁻ⁿ, il ne peut être inclus dans un seul intervalle de Cₙ et rencontre un trou. Un connexe de ℝ étant un intervalle, les connexes contenus dans C se réduisent à un point.',
        'La longueur totale affichée tend vers zéro, alors que le cardinal reste celui du continu. La longueur et le cardinal mesurent donc deux phénomènes différents. Le dessin de Cₙ, qui contient encore des intervalles, n’a pas la même connexité que la limite C.',
        'Un compact sans points isolés',
        'C est parfait : il est fermé et chacun de ses points est limite de points distincts de C. La propriété s’établit en modifiant un chiffre ternaire arbitrairement tardif.',
        '∀x∈C, ∀ε>0, ∃y∈C, 0<|x−y|<ε',
        'Coder x par une suite de chiffres 0 et 2. Changer uniquement le chiffre de rang n donne un autre point yₙ∈C, distinct, à distance 2/3ⁿ⁺¹. Pour n assez grand, cette distance est <ε. Ainsi aucune extrémité de la construction, pas même zéro ou un, n’est isolée. Fermeture et absence de points isolés définissent ici un ensemble parfait.',
        'Étapes finies et ensemble limite',
        'Au rang n=5, combien d’intervalles subsistent, quelle est leur longueur et leur longueur totale ? Pourquoi ces valeurs ne donnent-elles pas le cardinal de C ?',
        'Il subsiste 2⁵=32 intervalles de longueur 3⁻⁵=1/243, et leur longueur totale vaut 32/243≈0,131687. Chaque intervalle contient déjà une infinité non dénombrable de points ; le nombre d’intervalles ne compte donc pas les points. La non-dénombrabilité de C limite repose sur l’encodage des suites infinies, tandis que la longueur totale tend vers zéro.',
        'Un point qui appartient encore à toutes les étapes',
        'Vérifier que 1/4 appartient à C en utilisant son écriture ternaire. Trouver des points distincts de C qui convergent vers lui.',
        '1/4=Σk≥1 2/3²ᵏ=2/9·1/(1−1/9), donc son écriture ternaire est 0,020202… et utilise seulement 0 et 2. Modifier un seul chiffre à un rang de plus en plus grand donne des points distincts de C, à distance 2/3ⁿ du point initial. Ils convergent vers 1/4 et démontrent son caractère non isolé.'),
    record('rationnels_irrationnels', 'Densité et cardinalité répondent à deux questions différentes', 'Sup → Spé',
        'Dans ℝ, ℚ et ℝ∖ℚ sont tous deux denses. Pourtant ℚ est dénombrable et l’ensemble des irrationnels ne l’est pas. La densité signifie que tout voisinage rencontre l’ensemble ; elle ne donne aucun nombre de points ni aucune appartenance d’un point limite.',
        'qₙ=⌊10ⁿx⌋/10ⁿ : 0≤x−qₙ<10⁻ⁿ\nrₙ=qₙ+√2/10ⁿ : rₙ∉ℚ et rₙ→x',
        'qₙ est rationnel et converge vers x. rₙ est irrationnel, car ajouter à un rationnel le multiple rationnel non nul d’un irrationnel reste irrationnel ; son écart à x est au plus (1+√2)10⁻ⁿ. Tout réel est ainsi limite de suites appartenant à chacun des deux ensembles. Si les irrationnels étaient dénombrables, leur union avec ℚ rendrait ℝ dénombrable, contradiction à Cantor.',
        'L’intérieur de chacun des deux ensembles est vide et leur adhérence est ℝ ; leur frontière est donc ℝ. Une visualisation finie peut montrer deux familles d’approximants, mais elle ne peut représenter tous les points rationnels ou irrationnels d’un intervalle.',
        'La fonction de Dirichlet et les limites sur un dense',
        'La fonction 𝟙_ℚ vaut 1 sur les rationnels et 0 sur les irrationnels ; elle est discontinue partout. Deux fonctions continues égales sur un dense sont, en revanche, égales partout. La continuité est l’hypothèse qui fait passer de valeurs denses à toutes les valeurs.',
        'f,g continues sur E et f=g sur D dense ⇒ f=g sur E',
        'Pour a∈E métrique, choisir dₙ∈D avec dₙ→a. La continuité donne f(a)=lim f(dₙ)=lim g(dₙ)=g(a). Pour 𝟙_ℚ, les suites qₙ et rₙ ci-dessus approchent tout a mais leurs images valent constamment 1 et 0 ; une même limite ne peut être obtenue. L’appartenance de a à ℚ ne change pas cette contradiction.',
        'Une fonction déterminée par ses valeurs rationnelles',
        'f:ℝ→ℝ est continue et vérifie f(q)=q² pour tout q rationnel. Déterminer f(x) pour tout réel. Que se passe-t-il si la continuité est retirée ?',
        'La fonction g(x)=x² est continue ; f et g sont égales sur ℚ dense, donc f=g sur ℝ. Sans continuité, on peut définir f(x)=x² pour les rationnels et x²+1 pour les irrationnels ; l’égalité rationnelle ne détermine plus les autres valeurs.',
        'L’intersection de deux denses peut être vide',
        'Prendre A=ℚ et B=ℝ∖ℚ. Donner leurs intérieurs, adhérences et intersection. Comparer avec l’hypothèse de l’exercice 8 du recueil.',
        'A°=B°=∅ et Ā=B̄=ℝ, mais A∩B=∅. Ni A ni B n’est ouvert dans ℝ. L’exercice 8 exige qu’un des deux denses soit ouvert pour que chaque premier point trouvé conserve un petit voisinage dans lequel on peut appliquer la seconde densité.'),
    record('sinus_topologue', 'Connexe ne signifie pas toujours connexe par arcs', 'Spé → au-delà',
        'Le sinus du topologue est S=G∪V, où G={(x,sin(1/x)):0<x≤1} et V={0}×[−1,1]. G est connexe par arcs ; son adhérence ajoute toute la verticale V. Le nouvel ensemble S est compact et connexe, mais n’est pas connexe par arcs.',
        'S=Ḡ ; G connexe ⇒ Ḡ connexe\nAucune trajectoire continue dans S ne relie V à G',
        'L’image continue de ]0,1] par x↦(x,sin(1/x)) est connexe. Pour y∈[−1,1], choisir θ avec sinθ=y et xₙ=1/(θ+2πn)>0 pour n assez grand ; les points de G tendent vers (0,y). Aucune autre limite n’apparaît, donc S=Ḡ. L’adhérence d’un connexe est connexe : une séparation relative de l’adhérence imposerait une séparation de G, et un côté ouvert non vide doit rencontrer G par densité. S est fermé borné, donc compact.',
        'Le tracé ne représente que x≥δ>0, plus la verticale limite dessinée séparément. Cette union finie visible peut paraître disjointe : elle n’est pas l’ensemble infini S. La preuve de connexité vient de l’adhérence ; la preuve de l’absence de chemin utilise toutes les oscillations arbitrairement proches de zéro.',
        'Pourquoi aucun chemin ne peut quitter la verticale',
        'Supposons γ(t)=(x(t),y(t)) continue dans S, avec un point sur V et plus tard x(t)>0. Sur une composante ]a,b[ de {t:x(t)>0}, le rayon x tend vers zéro à l’extrémité a ; cela impose une oscillation de y incompatible avec sa continuité.',
        'Sur x(t)>0 : y(t)=sin(1/x(t))\nx(a)=0 ⇒ des temps t→a imposent y(t)=1 et y(t)=−1',
        'Fixer un t₀ de cette composante avec x(t₀)>0. Pour tout voisinage temporel ]a,a+η[, prendre un t₁ dedans avec x(t₁)>0. Par continuité et x(a)=0, x([a,t₁]) contient [0,x(t₁)]. Les valeurs 1/(π/2+2πn) et 1/(3π/2+2πn) y appartiennent pour n assez grand, donc des temps dans [a,t₁] donnent y=1 et y=−1. En faisant η→0, ces deux valeurs empêchent l’existence d’une limite de y en a. La contradiction exclut tout chemin entre V et G.',
        'Tous les points de la verticale sont adhérents',
        'Construire une suite de points de G tendant vers (0,1/2), puis une autre vers (0,−1). Pourquoi un simple préfixe du graphe ne suffit-il pas ?',
        'Pour 1/2, prendre xₙ=1/(π/6+2πn), donnant sin(1/xₙ)=1/2. Pour −1, prendre xₙ=1/(3π/2+2πn). Les deux abscisses tendent vers zéro. Un graphe limité à x≥δ>0 reste à une distance positive de la verticale et ne contient pas ces abscisses tardives : l’adhérence du graphe infini dépasse celle du préfixe dessiné.',
        'Classifier le graphe sans sa verticale',
        'G seul est-il fermé, compact, connexe et connexe par arcs ? Comparer avec S et expliquer quelle propriété est conservée par l’adhérence.',
        'G est connexe par arcs : relier deux abscisses positives dans ]0,1] puis composer avec le graphe. Il est borné mais non fermé, puisque (0,0) par exemple est une limite absente ; il n’est donc pas compact. S est fermé borné compact et connexe, mais non connexe par arcs. L’adhérence conserve la connexité, pas la connexité par arcs.'),
    record('gl_composantes', 'Le signe du déterminant sépare les matrices réelles inversibles', 'Spé',
        'On identifie M₄(ℝ) à ℝ¹⁶ avec la norme de Frobenius. GL₄(ℝ)={A:det A≠0} est ouvert, dense et non borné. Les ensembles det>0 et det<0 constituent ses deux composantes connexes par arcs. SL₄(ℝ)={A:det A=1} est un sous-groupe différent de l’ensemble det>0.',
        'GLₙ⁺(ℝ)={A:det A>0}, GLₙ⁻(ℝ)={A:det A<0}\nSLₙ(ℝ)={A:det A=1} ; SLₙ(ℝ)⊂GLₙ⁺(ℝ)',
        'Le déterminant est polynomial continu, donc GL est l’image réciproque de ℝ∖{0}, ouverte. Pour toute A, le polynôme t↦det(A+tI) possède un coefficient dominant 1 et seulement un nombre fini de racines ; il existe des t arbitrairement petits avec A+tI inversible, d’où la densité. Sur un chemin inversible réel, le déterminant reste non nul ; le TVI interdit de changer de signe. Chaque signe est connexe par arcs par décomposition polaire A=QP : faire varier P positif vers I, puis Q dans SO(n), ou dans sa composante de réflexion.',
        'La famille A(t)=Q diag(t,1,2,3) R, Q,R orthogonales denses de déterminant 1, a det A=6t et devient singulière en t=0. Sur ℂ, le chemin Q diag(e^(iθ),1,2,3) R relie ses extrémités sans annuler le déterminant : le détour complexe n’existe pas dans GL₄(ℝ).',
        'GLₙ(ℂ) est connexe par arcs, contrairement au cas réel',
        'Les valeurs complexes non nulles contournent zéro. Une réduction polaire sépare les étirements positifs d’une matrice unitaire ; les phases des valeurs propres de cette dernière fournissent un chemin.',
        'A=UP, P hermitienne positive définie\nP_t=(1−t)P+tI ; U_t=V diag(e^(i(1−t)θⱼ))V*',
        'P_t reste positive définie car z*P_tz est strictement positif pour z≠0. Écrire U=V diag(e^(iθⱼ))V* par le théorème spectral unitaire donne un chemin U_t de U vers I. La concaténation relie A à U puis à I dans GLₙ(ℂ). Les phases sont choisies pour les valeurs propres de la matrice considérée ; il n’est pas nécessaire de choisir une phase globale continue pour toutes les matrices simultanément.',
        'Déterminant positif ne veut pas dire égal à un',
        'Pour A=diag(2,1,1,3), préciser l’appartenance à GL₄⁺(ℝ), SL₄(ℝ) et O(4). Construire un chemin dans GL₄⁺ vers I.',
        'det A=6>0, donc A∈GL₄⁺, mais A∉SL₄ car 6≠1. Elle n’est pas orthogonale car AᵀA=diag(4,1,1,9)≠I. Le chemin diag(2−t,1,1,3−2t), t∈[0,1], reste à coefficients diagonaux positifs et aboutit à I. Le déterminant varie tout en restant strictement positif.',
        'Une matrice singulière approchée par les deux signes',
        'Pour A₀=diag(0,1,2,3), construire deux suites inversibles de déterminants de signes opposés convergeant vers A₀. Déduire que la frontière de GL contient A₀.',
        'Aₙ⁺=diag(1/n,1,2,3) et Aₙ⁻=diag(−1/n,1,2,3) ont des déterminants ±6/n et convergent en norme de Frobenius vers A₀. Le point A₀ n’appartient pas à GL mais est dans son adhérence ; comme GL est ouvert, A₀ est sur sa frontière. Plus généralement la frontière de GL est l’ensemble det=0, par ouverture et densité.'),
    record('orthogonal_compact', 'Un groupe matriciel compact et un groupe fermé non borné', 'Spé',
        'O(4)={Q:QᵀQ=I} conserve les longueurs euclidiennes. Chaque matrice orthogonale possède des colonnes unitaires orthogonales et ‖Q‖F=2. Le groupe SL₄(ℝ) est lui aussi fermé, mais peut étirer une direction tout en comprimant une autre : le déterminant ne contrôle pas la taille.',
        'O(n) fermé et ‖Q‖F=√n ⇒ O(n) compact\nD_t=diag(eᵗ,e⁻ᵗ,1,1)∈SL₄(ℝ), ‖D_t‖F²=e²ᵗ+e⁻²ᵗ+2',
        'L’application Q↦QᵀQ est continue ; O(n) est son image réciproque du singleton I, donc fermé. Les coefficients des colonnes sont bornés et la norme de Frobenius est √n : en dimension finie, O(n) est compact. SL est le fermé det⁻¹({1}), mais D_t montre qu’il est non borné, donc non compact. Les deux arguments utilisent des propriétés distinctes : une équation continue produit la fermeture, une estimation produit la bornitude.',
        'Le laboratoire multiplie des rotations dans deux plans de ℝ⁴, ou une réflexion, à gauche par Q et à droite par R, deux matrices orthogonales denses de déterminant 1. Ces isométries rendent les matrices pleinement 4×4 sans changer leurs valeurs singulières. La projection 2D d’un objet de ℝ⁴ peut masquer certaines distances ; les métriques proviennent des quatre coordonnées.',
        'SO(n), orientations et chemins de rotations',
        'Une matrice orthogonale réelle a un déterminant ±1. O(n) possède deux composantes, tandis que SO(n)={Q∈O(n):det Q=1} est connexe par arcs. Dans ℝ⁴ une rotation n’est pas nécessairement décrite par un unique angle.',
        'QᵀQ=I ⇒ (det Q)²=1\nQ∈SO(n) se réduit orthogonalement en blocs de rotations et blocs 1',
        'Prendre le déterminant de QᵀQ=I donne le signe ±1. Une forme canonique réelle orthogonale décompose Q en rotations planes et en ±1 ; les −1 sont en nombre pair lorsque det Q=1 et se regroupent en rotations d’angle π. Ramener continûment tous les angles à zéro relie Q à I dans SO(n). Une réflexion fixe transforme cette composante en celle de déterminant −1. Le signe ne peut varier sur un chemin orthogonal par continuité.',
        'Une matrice à quatre directions',
        'Pour Q=diag(Rθ,Rφ), où Rα est la rotation plane d’angle α, calculer determinant, norme de Frobenius et norme d’opérateur. Montrer qu’une conjugaison orthogonale dense conserve ces valeurs.',
        'Chaque bloc a un déterminant 1 ; det Q=1. Q est orthogonale, donc ‖Q‖F=√4=2 et ‖Q‖op=1. Pour une matrice orthogonale S, SQSᵀ reste orthogonale, de même déterminant et de mêmes valeurs singulières ; ses normes restent 2 et 1. Le choix de base change les coefficients mais pas la géométrie intrinsèque.',
        'Un volume conservé peut s’accompagner d’une fuite à l’infini',
        'Pour A_t=diag(eᵗ,e⁻ᵗ,1,1), calculer le déterminant, la plus grande valeur singulière et le conditionnement pour t≥0. Que devient la compacité d’un ensemble contenant tous ces A_t ?',
        'Le déterminant vaut 1, σmax=eᵗ et σmin=e⁻ᵗ ; le conditionnement euclidien vaut e²ᵗ. Les normes sont non bornées quand t→∞, donc aucun compact de M₄(ℝ) ne contient toute la famille. La conservation du volume ne borne ni les longueurs ni la sensibilité de l’inversion.'),
    record('point_fixe', 'Une contraction transforme la complétude en convergence garantie', 'Spé → au-delà',
        'Sur un espace métrique complet non vide X, une application T:X→X q-lipschitzienne avec 0≤q<1 possède un unique point fixe. À partir de x₀, les itérations xₙ₊₁=T(xₙ) convergent vers ce point. La stabilité du domaine T(X)⊂X et la complétude doivent être contrôlées avant l’itération.',
        'd(Tx,Ty)≤q d(x,y), 0≤q<1\nd(xₙ,x*)≤qⁿd(x₁,x₀)/(1−q)',
        'Par récurrence d(xₙ₊₁,xₙ)≤qⁿd(x₁,x₀). La somme géométrique borne d(xₘ,xₙ) par qⁿd(x₁,x₀)/(1−q), donc la suite est de Cauchy. La complétude donne une limite x*. T est continue, d’où T(x*)=x*. Si a et b étaient fixes, d(a,b)≤q d(a,b), donc a=b. Faire m→∞ dans la borne de Cauchy produit l’estimation d’erreur affichée.',
        'T(x)=cos x envoie [0,1] dans [cos1,1]⊂[0,1] et possède q=sin1<1 par l’inégalité des accroissements finis. Pour T(x)=ax+b sur ℝ, le taux est |a| : un point fixe peut exister même si l’itération n’est pas contractante, mais la garantie de Banach disparaît.',
        'Existence du point fixe et convergence de l’itération se séparent',
        'Pour l’application affine T(x)=ax+b, si a≠1 le point fixe vaut b/(1−a), mais son attractivité dépend de |a|. Si a=1, il peut n’y avoir aucun point fixe ou en exister une infinité.',
        'xₙ−x*=aⁿ(x₀−x*) si a≠1\na=1,b≠0 : aucun fixe ; a=1,b=0 : tous les points fixes',
        'Soustraire l’identité x*=ax*+b de la récurrence donne le facteur a à chaque étape. Pour |a|<1, l’erreur tend vers zéro ; pour |a|>1 elle grandit sauf départ exactement au point fixe. Pour a=−1 elle alterne sans décroître sauf ce départ. Ainsi résoudre algébriquement T(x)=x ne prouve pas la convergence de l’algorithme proposé.',
        'Combien d’itérations pour cos ?',
        'Pour x₀=0 et xₙ₊₁=cos xₙ, donner une borne suffisante sur n pour une erreur <10⁻⁵, en utilisant q=sin1. Pourquoi cette borne peut-elle être pessimiste ?',
        'd(x₁,x₀)=1, donc l’erreur est ≤qⁿ/(1−q). Il suffit de choisir n avec qⁿ<10⁻⁵(1−q), soit n>ln(10⁻⁵(1−q))/ln(q), environ 77,4 ; n=78 convient. Le taux q majore la dérivée sur tout [0,1], alors que près du fixe la valeur |sin x*|≈0,674 est plus petite ; l’erreur observée peut décroître plus vite.',
        'Un fixe répulsif et un cycle',
        'Pour T(x)=−1,1x+2, déterminer le point fixe et décrire l’itération depuis x₀=0. Reprendre avec T(x)=−x+2.',
        'Le premier fixe est 2/2,1=20/21 ; l’erreur vaut (−1,1)ⁿ(−20/21), alterne et augmente en module. Le fixe existe mais est répulsif. Pour T(x)=−x+2, le fixe vaut 1 et depuis zéro l’itération alterne 0,2,0,2,… ; elle ne converge pas. Le seuil strict |a|<1 est donc indispensable à la conclusion générale de convergence.'),
    record('chemins_niveaux', 'Un niveau continu change la géométrie des composantes', 'Spé',
        'La fonction F_a(x,y)=((x−a)²+y²)((x+a)²+y²), avec a>0, est le produit des carrés des distances aux foyers (±a,0). Les sous-niveaux fermés C_{a,b}={F_a≤b⁴}, b>0, illustrent le passage de deux lobes séparés à un ensemble connexe. Un sous-niveau fermé n’a pas la même connexité que le sous-niveau strict au niveau critique.',
        'C_{a,b}=F_a⁻¹(]−∞,b⁴]) fermé\nb<a : deux composantes ; b=a : lobes joints en 0 ; b>a : une composante',
        'F_a est continue et coercive de degré quatre, donc chaque sous-niveau est fermé borné, compact. Sur la médiatrice x=0, F_a(0,y)=(a²+y²)²≥a⁴. Si b<a, aucun point de C ne touche x=0 : les deux signes de x séparent les lobes. En coordonnées polaires, F_a=r⁴−2a²r²cos2θ+a⁴ ; pour b≥a, chaque direction admise contient un intervalle radial commençant à zéro. Le sous-niveau fermé est étoilé de centre zéro et donc connexe par arcs. Pour b=a, les deux lobes ne se rejoignent qu’en zéro.',
        'Le contour est une courbe de Cassini. Pour b<a, écrire z=x+iy : F_a=|z²−a²|². Le disque fermé |w−a²|≤b² reste dans Re w>0 ; sa racine carrée continue de partie réelle positive décrit exactement le lobe x>0, et son opposé le lobe x<0. Chaque lobe est donc connexe par arcs, et il y a exactement deux composantes. Le maillage peut créer un faux pont ; les inégalités exactes et le statut ouvert ou fermé décident de la classification.',
        'Images réciproques et valeurs intermédiaires',
        'Pour une fonction continue f, l’image réciproque d’un ouvert est ouverte et celle d’un fermé est fermée. L’image continue d’un connexe est connexe. Ces deux principes expliquent la nature des sous-niveaux et les obstacles à un chemin.',
        'f continue ⇒ {f<c} ouvert, {f≤c} fermé\nγ chemin ⇒ f∘γ satisfait le TVI',
        'Si f(x)<c, la continuité préserve cette stricte marge dans une boule autour de x, d’où l’ouverture. La fermeture du sous-niveau large découle du complémentaire {f>c}. Si un chemin reliait un point d’abscisse négative à un point d’abscisse positive dans C_{a,b} pour b<a, sa coordonnée x passerait par zéro par TVI, mais aucun point de ce sous-niveau n’a x=0. Le TVI fournit ici un certificat d’impossibilité.',
        'Le seuil critique, strict ou large ?',
        'Pour a=b=1, montrer que {F₁≤1} est connexe par arcs et que {F₁<1} possède deux composantes. Le point zéro appartient-il à chacun des deux ensembles ?',
        'En polaires, F₁≤1 équivaut à r²(r²−2cos2θ)≤0. Pour une direction où cos2θ≥0, les rayons 0≤r≤√(2cos2θ) sont admis ; chaque point se relie à zéro par son segment radial. Zéro appartient au sous-niveau large car F₁(0)=1. Le sous-niveau strict l’exclut et n’a aucun point sur x=0 ; ses deux lobes ouverts, chacun connexe par arcs, sont séparés.',
        'Bornitude d’un sous-niveau quartique',
        'Utiliser les distances aux foyers pour obtenir une borne radiale simple sur C_{a,b}. Pour a=1,b=2, donner un rayon de boule fermée contenant cet ensemble.',
        'Pour r=√(x²+y²)≥a, chaque distance à un foyer est ≥r−a. Ainsi F_a≥(r−a)⁴. Si F_a≤b⁴, alors r−a≤b, donc r≤a+b. Les points de r<a satisfont aussi cette borne. C_{1,2} est contenu dans la boule fermée de rayon 3 ; une borne plus fine est possible, mais celle-ci suffit à la compacité avec la fermeture.'),
    record('homeomorphisme', 'Une bijection continue peut avoir un inverse discontinu', 'Spé',
        'Un homéomorphisme f:X→Y est une bijection continue dont l’inverse est continu. Il conserve les ouverts relatifs, compacts, connexes et convergences. Une bijection continue seule ne suffit pas : l’enroulement f:[0,2π[→S¹, t↦(cos t,sin t), possède un inverse discontinu au point (1,0).',
        'tₙ=2π−1/n : f(tₙ)→f(0), mais tₙ ne tend pas vers 0\nBijection continue ≠ nécessairement homéomorphisme',
        'L’enroulement est continu et bijectif sur l’intervalle semi-ouvert, car chaque angle possède un représentant unique dans [0,2π[. Les images de tₙ convergent vers (1,0), mais leurs antécédents restent proches de 2π, et non de zéro. La caractérisation séquentielle de la continuité montre donc que f⁻¹ est discontinue à (1,0). Le défaut vient du raccord des deux bouts du cercle sans raccord correspondant dans le domaine.',
        'Le plongement g(t)=(t,t²,t³), t∈[−1,1], a un inverse égal à la projection sur la première coordonnée, donc est un homéomorphisme vers son image. La courbe est tracée avec une projection graphique, mais les trois coordonnées définissent l’application étudiée.',
        'Un compact répare l’inverse d’une injection continue',
        'Si K est compact et F est métrique, une application continue injective f:K→F est un homéomorphisme de K sur f(K). Ce théorème du recueil fournit la continuité de l’inverse sans calcul explicite.',
        'K compact, f continue injective ⇒ f:K→f(K) homéomorphisme',
        'La bijectivité sur l’image est automatique. Tout fermé A de K est compact ; son image f(A) est compacte, donc fermée dans F et dans f(K). Pour g=f⁻¹, g⁻¹(A)=f(A) est donc fermé pour chaque fermé A de K : g est continue. L’argument utilise le fait qu’un compact est fermé dans un espace métrique, plus généralement Hausdorff. L’intervalle [0,2π[ du contre-exemple n’est pas compact.',
        'Une courbe gauche conserve la topologie du segment',
        'Pour g:[−1,1]→ℝ³, g(t)=(t,t²,t³), prouver l’injectivité, la compacité de l’image et la continuité de l’inverse. Déterminer si l’image est connexe par arcs et convexe.',
        'La première coordonnée égale t, donc g est injective et son inverse sur l’image est la projection (x,y,z)↦x, continue. L’image d’un compact est compacte et celle d’un intervalle est connexe par arcs. Elle n’est pas convexe : le milieu de g(−1)=(-1,1,-1) et g(1)=(1,1,1) est (0,1,0), absent car g(0)=(0,0,0).',
        'Une bijection entre deux infinis n’est pas une ressemblance topologique',
        'Expliquer pourquoi une bijection ensembliste entre ℝ et ℝ² ne peut être un homéomorphisme. Quel invariant simple détecte la différence après retrait d’un point ?',
        'Le cardinal des deux ensembles est le même, mais un homéomorphisme préserverait la connexité de leurs complémentaires de points correspondants. ℝ∖{a} possède deux composantes, tandis que ℝ²∖{p} reste connexe par arcs. Cette contradiction, démontrée dans l’exercice 7, montre que la topologie contient une information supplémentaire par rapport au cardinal.'),
]


ORDER = [item['lab'] for item in DATA]
LESSONS = []
EXERCISES = []
for item in DATA:
    LESSONS.append(dict(title=f"{len(LESSONS)+1}. {item['title']}",
                        level=item['level'], lab=item['lab'],
                        html=P('Objets et but.', item['context'])+F(item['formula'])
                             +P('Démonstration.', item['proof'])
                             +P('Lire l’expérience.', item['application'])))
    LESSONS.append(dict(title=f"{len(LESSONS)+1}. {item['lemma_title']}",
                        level=item['level'], lab=item['lab'],
                        html=P('Propriété ciblée.', item['lemma_statement'])
                             +F(item['lemma_formula'])
                             +P('Justification.', item['lemma_proof'])))
    for title, question, answer in item['exercises']:
        EXERCISES.append(dict(title=f'{len(EXERCISES)+1}. {title}',
                              level=item['level'], lab=item['lab'],
                              question=P('Énoncé.', question),
                              answer=P('Corrigé.', answer)))


SOURCES = [
    '<p>Point de départ : recueil fourni par l’utilisateur, fiche M1 « Topologie et ensembles », '
    'pages imprimées 12–25. Définitions p.15–16, TP de suite extraite aléatoire p.17, '
    'propriétés p.19–21, infographie essentielle p.22, exercices 6–9 p.23 et corrigés p.25. '
    'Les expériences, cours et problèmes de cet atelier sont nouvellement rédigés. '
    'Le PDF, ses scans et ses figures ne sont pas redistribués.</p>',
    '<p><a href="https://ocw.mit.edu/courses/18-s190-introduction-to-metric-spaces-january-iap-2023/pages/lecture-notes/">'
    'MIT OpenCourseWare, Paige Bright, Introduction to Metric Spaces</a> : '
    'compléments sur les espaces métriques, les recouvrements et la complétude.</p>',
    '<p><a href="https://www.jirka.org/ra/html/sec_metcompact.html">'
    'Jiří Lebl, Basic Analysis, Completeness and compactness</a> : '
    'compléments universitaires sur la compacité en espaces métriques ; '
    '<a href="https://www.jirka.org/ra/html/sec_metcont.html">Continuous functions</a> : '
    'continuité, images compactes et topologie.</p>',
]
