"""Objectifs, objets, premiers gestes et niveaux de chaque expérience."""
from cours import ORDER


def guide(purpose, objects, assumptions, techniques, steps, sup, spe, beyond, expected):
    # Only the spaced separator splits entries, never the bars in |x|.
    return dict(purpose=purpose, objects=objects.split(' | '),
                assumptions=assumptions.split(' | '),
                techniques=techniques.split(' | '), first_steps=steps,
                levels=dict(sup=sup, spe=spe, beyond=beyond),
                expected=expected, lesson_numbers=[])


LAB_GUIDES = {
    'boules_normes': guide(
        'Donner un sens concret aux définitions de norme, boule ouverte, boule fermée et voisinage. L’objectif CPGE est de transformer une inégalité stricte en un rayon intérieur, puis de comprendre pourquoi des boules de formes différentes donnent la même topologie.',
        'x,y sont les coordonnées du point de ℝ², sans unité | r>0 est le rayon ; p≥1 est l’exposant de la norme p | La marge r−‖(x,y)‖ est calculée par la formule de la norme',
        'Normes sur ℝ² ; l’exposant p reste ≥1 | Une marge nulle n’assure pas l’appartenance à une boule ouverte | L’équivalence des normes compare des rayons adaptés, pas des boules identiques',
        'Inégalité triangulaire | Quantificateur ∃r>0 d’un voisinage | Encadrements des normes 1,2,∞',
        ['Avec r=1 et (x,y)=(0,7;0,7), calculer les trois normes avant de changer le sélecteur.',
         'Choisir (1,0) et comparer boule ouverte et fermée : expliquer le rôle de la marge nulle.',
         'Pour un point de marge positive, écrire le rayon δ=r−‖x‖ et prouver l’inclusion de sa boule témoin.'],
        'Valeur absolue, coordonnées, normes usuelles et inégalités ; lecture d’une définition.',
        'Ouverts d’un espace normé et équivalence des normes en dimension finie.',
        'Boules convexes et géométrie des normes en optimisation.',
        'Une classification exacte du point et une preuve de voisinage intérieur, indépendantes du tracé.'),
    'interieur_frontiere': guide(
        'Distinguer appartenance, intérieur, adhérence et frontière en variant un même disque. La technique CPGE consiste à utiliser correctement ∃ε et ∀ε, puis les identités de complémentation de la fiche M1.',
        'A est le disque ouvert/fermé, l’anneau r/2≤‖x‖≤r ou le disque ouvert épointé | x,y localisent le point testé ; ε est le rayon du voisinage observé | r fixe le rayon extérieur, sans unité',
        'La topologie ambiante est celle de ℝ² euclidien | La propriété doit valoir pour tous les rayons pertinents, pas seulement pour ε choisi | Les critères de classification viennent des distances et inégalités exactes',
        'Définitions quantifiées | Images réciproques de fermés | Complémentaire et frontière',
        ['Choisir le disque épointé et tester zéro : prévoir appartenance, adhérence et frontière séparément.',
         'Tester un point de rayon r sur le disque ouvert, puis fermé ; noter ce qui change et ce qui reste identique.',
         'Passer à l’anneau et rédiger les trois ensembles A°, Ā, Fr(A), en incluant les deux cercles.'],
        'Lecture d’inégalités larges ou strictes, cercles et voisinages.',
        'Intérieur, adhérence, frontière et idempotence de la fermeture.',
        'Ensembles à frontière d’intérieur non vide et régularité des domaines.',
        'Un tableau de quatre propriétés qui ne confond pas un point absent et un point non adhérent.'),
    'adherence_suite': guide(
        'Observer un point absent qui est limite de points de l’ensemble, puis rendre l’ensemble compact en l’ajoutant. Le but est de relier la définition par voisinages à la caractérisation séquentielle de l’adhérence.',
        'A={1/n:n≥1} est fixé et infini ; N ne compte que les points dessinés | x est le point testé et ε le rayon du voisinage | Le sélecteur ajoute éventuellement zéro à l’ensemble étudié',
        'N ne tronque pas la définition mathématique de A | d(0,A)=0 est un infimum non atteint si zéro est absent | La compacité se juge dans ℝ, pas sur le préfixe fini du dessin',
        'Suite convergente et unicité de la limite | Fermeture séquentielle | Minimum et infimum',
        ['Tester x=0 sans ajouter zéro ; réduire ε et prévoir quel n suffit pour 1/n<ε.',
         'Tester x=1/4 puis chercher un rayon qui l’isole des autres points.',
         'Ajouter zéro et justifier par fermé borné la compacité ; expliquer pourquoi augmenter N seul ne la crée pas.'],
        'Suites numériques et limites de 1/n ; points isolés.',
        'Adhérence séquentielle, compacité et distance à un ensemble.',
        'Points d’accumulation, dérivé d’un ensemble et ensembles parfaits.',
        'Une preuve de Ā=A∪{0} et une distinction entre distance nulle et appartenance.'),
    'topologie_relative': guide(
        'Apprendre à annoncer l’espace avant les mots ouvert, fermé et intérieur. Le bord zéro de [0,1] devient un point intérieur relativement à cet intervalle : ce cas forme un réflexe essentiel pour les domaines de fonctions en CPGE.',
        'X=[0,1] est l’espace ambiant relatif | A=X∩]−1/2,b[ ; b peut dépasser 1 | B_X(x,ε)=]x−ε,x+ε[∩X',
        'x appartient à X ; les boules sont restreintes à X | Le même A peut être ouvert dans X sans être ouvert dans ℝ | Quand b>1, A=X et sa frontière relative est vide',
        'Restriction d’un ouvert | Complémentaire relatif | Intérieur et adhérence dans deux espaces',
        ['Fixer b=0,65 et x=0 ; construire le voisinage relatif puis le voisinage ambiant.',
         'Tester x=b et expliquer son exclusion et son appartenance à l’adhérence lorsque b≤1.',
         'Choisir b>1 : classer X dans lui-même et comparer sa frontière dans ℝ.'],
        'Intervalles et restriction d’un domaine.',
        'Topologie relative et images réciproques par l’inclusion.',
        'Sous-espaces topologiques et plongements.',
        'Une classification qui indique explicitement « dans X » ou « dans ℝ » à chaque conclusion.'),
    'operations_ouverts': guide(
        'Voir pourquoi « finie » ne peut être supprimé dans les propriétés d’intersection des ouverts et de réunion des fermés. Le lien CPGE est le choix d’un minimum de rayons strictement positifs et son possible effondrement à l’infini.',
        'N compte les ensembles retenus | Intersection : Uₙ=]−1/n,1/n[ | Union : Fₙ=[1/n,1] ; x est le point testé',
        'Les résultats finis et les résultats infinis sont affichés séparément | Une intersection infinie demande l’appartenance à tous les termes | Une union infinie demande l’appartenance à au moins un terme',
        'Min de rayons en nombre fini | Lois de De Morgan | Contre-exemples explicites',
        ['Pour N=5, écrire l’intersection finie puis déterminer l’intersection infinie sans utiliser le dessin.',
         'Passer à l’union et tester zéro : pourquoi est-il adhérent mais absent ?',
         'Rédiger les quatre règles de stabilité des ouverts/fermés, en soulignant les opérations finies.'],
        'Opérations ensemblistes et ordre sur les réels.',
        'Axiomes de topologie, densité et exercice 8.',
        'Théorème de Baire et intersections dénombrables de denses ouverts.',
        'Deux contre-exemples qui rendent visible l’hypothèse de finitude et une preuve des règles valides.'),
    'distance_ensemble': guide(
        'Calculer une distance à un ensemble puis comparer existence, unicité et continuité de la projection. Le cours fournit une propriété toujours vraie, la continuité 1-lipschitzienne de la distance, même lorsque la projection ne peut être choisie de façon unique.',
        'A est la réunion de deux disques fermés de même rayon r | separation est la distance des centres | x,y localisent le point ; les projections minimisantes sont toutes indiquées',
        'A est fermé non vide dans ℝ², donc le minimum existe | La réunion peut être non convexe et donner deux projections | Le minimum des distances aux deux disques est calculé exactement',
        'Infimum et minimum | Inégalité triangulaire | Minimum de deux fonctions distances',
        ['Placer le point sur la médiatrice avec deux disques disjoints : prévoir les deux projections.',
         'Déplacer le point d’un côté : suivre la distance continue malgré le changement de projection retenue.',
         'Démontrer |d(x,A)−d(y,A)|≤‖x−y‖ et expliquer d(x,A)=0⇔x∈Ā.'],
        'Distances euclidiennes et infimums.',
        'Fonctions lipschitziennes et fermeture d’un ensemble.',
        'Projections multivaluées et distance de Hausdorff.',
        'Une distance unique et continue, avec une projection éventuellement multiple, sans contradiction.'),
    'convexite': guide(
        'Transformer la définition universelle de convexité en une preuve pour un disque et en un témoin de réfutation pour un anneau ou deux disques. L’objectif est de distinguer une propriété pour tous les segments d’un seul segment réussi.',
        'a,b sont les angles des deux points, en degrés | ρ fixe leur rayon relatif ; separation règle les deux disques | Le segment est paramétré par t∈[0,1]',
        'Convexité dans ℝ², coefficients réels non négatifs | Le moteur analyse les intervalles de t où le segment est admis | Une réussite pour la paire choisie ne prouve pas la convexité de tout A',
        'Inégalité triangulaire | Étude d’une fonction quadratique de t | Témoin explicite au milieu',
        ['Sur l’anneau, choisir deux points opposés ; calculer leur milieu avant de regarder le tracé.',
         'Sur le disque, rédiger l’inégalité triangulaire valable pour tous les points et tous les t.',
         'Comparer avec le labo de chemins : donner un ensemble connexe par arcs qui n’est pas convexe.'],
        'Barycentres de deux points, segments et milieux.',
        'Convexité, ensembles étoilés et implication vers la connexité.',
        'Fonctions convexes et géométrie des sous-niveaux.',
        'Une preuve universelle pour le disque et un contre-exemple suffisant pour chaque ensemble non convexe.'),
    'enveloppe_convexe': guide(
        'Construire le plus petit convexe contenant un nuage et comprendre le rôle des poids d’un barycentre. Le laboratoire relie calcul vectoriel de Sup, déterminants de Spé et construction algorithmique du bord.',
        'N est le nombre de points du nuage ; seed rend le nuage reproductible | α accentue le poids du premier point, imposé extrême à droite | Les sommets, l’aire et le barycentre sont calculés à partir des coordonnées',
        'Tous les poids sont non négatifs et leur somme vaut 1 | À α=1, seul le premier point porte le poids | L’enveloppe est celle du nuage fini choisi, pas celle d’une distribution aléatoire entière',
        'Barycentres et convexité | Déterminant de deux vecteurs | Chaînes monotones et points extrêmes',
        ['Pour N=20 et seed=7, distinguer points du nuage et sommets de son enveloppe.',
         'Déplacer α de 0 à 1 ; justifier la présence du barycentre dans le polygone pour chaque α.',
         'Calculer un barycentre à poids négatif dans un triangle et expliquer pourquoi la garantie échoue.'],
        'Coordonnées, barycentres et aire d’un polygone.',
        'Enveloppe convexe, compacité par image du simplexe et déterminants.',
        'Théorème de Carathéodory et programmation linéaire.',
        'Un lien entre les poids, le bord géométrique et la propriété minimale de l’enveloppe convexe.'),
    'projection_convexe': guide(
        'Prouver la minimalité d’un point projeté par une inéquation plutôt que par un dessin. La technique de Spé développe un carré de norme et utilise la convexité ; elle explique aussi l’unicité et la stabilité de la projection.',
        'C est un rectangle ou le triangle de sommets (−1;−0,75),(1;−0,75),(0,1;1,1) | x,y désignent le point extérieur ou intérieur | ζ place z sur le bord ; p=P_C(x) est calculé exactement',
        'Norme euclidienne et convexe fermé non vide | Vérifier les sommets suffit, car l’expression est affine en z | Une norme non euclidienne ne donne pas automatiquement cette unicité',
        'Produit scalaire | Développement de ‖x−z‖² | Inégalité de caractérisation sur les sommets',
        ['Choisir une projection sur une arête ; prévoir si x−p est normal au côté.',
         'Choisir une projection sur un sommet et vérifier que la condition concerne tous les côtés adjacents.',
         'Écrire ⟨x−p,z−p⟩≤0 puis développer le carré pour démontrer minimalité et unicité.'],
        'Orthogonalité et projection sur une droite, avec accompagnement.',
        'Projection sur un convexe, Cauchy–Schwarz et caractère 1-lipschitzien.',
        'Optimisation sous contraintes, cône normal et algorithmes projetés.',
        'Un certificat de projection qui vaut pour tout le convexe, pas pour quelques points échantillonnés.'),
    'connexite_chemins': guide(
        'Construire un chemin qui contourne un trou, puis prouver qu’une séparation interdit certains chemins. Ce labo reprend l’exercice 7 et prépare l’usage du TVI comme invariant topologique.',
        'X est le plan épointé, un anneau, deux disques séparés ou l’axe réel épointé | r₁,r₂ sont les rayons des points et angle fixe la direction du second | gap est l’écart positif entre les disques',
        'Le chemin doit rester dans X à tout instant | Les segments radiaux et arcs ont des rayons strictement positifs | Les deux segments de l’exercice 7 concernent le plan épointé ; l’anneau utilise un chemin radial et angulaire',
        'Paramétrisation par morceaux | TVI sur une coordonnée | Séparations relatives et images continues',
        ['Dans le plan épointé, prendre des points opposés : le segment traverse zéro, mais construire le détour.',
         'Passer à l’anneau et vérifier les rayons du chemin avant de conclure.',
         'Comparer avec ℝ privé de zéro puis rédiger la preuve que ℝ et ℝ² ne sont pas homéomorphes.'],
        'Chemins explicites et intervalles de ℝ.',
        'Connexité, connexité par arcs et invariance par homéomorphisme.',
        'Groupe fondamental et différence entre trou et séparation.',
        'Un chemin construit là où il existe et un certificat d’impossibilité là où une séparation l’interdit.'),
    'bolzano_weierstrass': guide(
        'Utiliser une suite bornée qui ne converge pas pour apprendre ce que promet vraiment Bolzano–Weierstrass. La technique attendue consiste à choisir des indices croissants et à majorer l’erreur de chaque extraction.',
        'uₙ=(−1)ⁿ+1/(n+1), n≥0 | N est le dernier indice dessiné | ε est la tolérance ; pairs et impairs donnent deux sous-suites',
        'La suite complète n’a pas de limite | Les limites extraites sont ±1, avec erreur exacte 1/(n+1) | BW s’applique aux espaces normés réels/complexes de dimension finie',
        'Extraction par parité | Quantificateurs de convergence | Bissection emboîtée pour la preuve générale',
        ['Pour N=60, calculer u₂ₖ et u₂ₖ₊₁ puis annoncer leurs limites.',
         'Choisir ε=0,01 et déterminer les indices au-delà desquels l’erreur est <ε.',
         'Rédiger pourquoi la suite entière ne converge pas malgré deux extractions convergentes.'],
        'Suites, parité et bornitude.',
        'Valeurs d’adhérence, BW et choix d’indices.',
        'Compacité séquentielle et méthodes d’extraction diagonale.',
        'Deux extractions justifiées et une distinction entre convergence de la suite et existence d’une limite extraite.'),
    'extraction_aleatoire': guide(
        'Reprendre le TP p.17 avec des indices réellement croissants et une interprétation probabiliste précise. Le but est de distinguer une réalisation finie, une loi exacte et une convergence presque sûre dans un modèle infini.',
        'Uⱼ indépendantes uniformes sur [0,3] ; cible a=1 | N compte les tirages, seed les reproduit et trials compte les expériences d’histogramme | d∈]0,1] est la distance testée ; D_N est le meilleur rapprochement',
        'Le modèle probabiliste suppose indépendance et uniformité | Seuls les nouveaux records sont retenus, sans répéter un indice | P(D_N>d)=(1−2d/3)^N ; une réussite n’est jamais garantie pour un N fini',
        'Loi géométrique d’absence de succès | Records et extractions | Événements de probabilité un et voisinages dénombrables',
        ['Lancer N=3000 et lire la suite des indices retenus : expliquer pourquoi ils sont strictement croissants.',
         'Fixer d=0,001 avec N=100 puis prévoir la probabilité d’échec avant de comparer plusieurs graines.',
         'Justifier avec les voisinages 1/k pourquoi la suite infinie possède presque sûrement une extraction vers 1.'],
        'Simulation de probabilités, suites et notion d’indépendance.',
        'BW confronté à une cible imposée, loi du minimum et presque-sûreté.',
        'Lemmes de Borel–Cantelli et méthodes de recherche aléatoire.',
        'Une expérience fidèle au TP et des conclusions explicitement probabilistes, avec un budget d’essais calculé.'),
    'cauchy_rationnels': guide(
        'Faire apparaître l’hypothèse de complétude en calculant des approximations rationnelles exactes de √2. Le lien au cours est le contraste entre une suite de Cauchy et une limite qui manque à l’espace ℚ.',
        'u₀=2 et uₙ₊₁=uₙ/2+1/uₙ | n≤8 règle la profondeur des fractions exactes | ε est une tolérance comparée à une majoration démontrée de l’erreur',
        'Les itérés sont des fractions exactes, pas des décimaux déclarés rationnels | La limite est prise dans ℝ pour prouver ensuite le défaut de complétude de ℚ | L’irrationalité de √2 se prouve par parité',
        'Monotonie et minoration | Identité d’erreur quadratique | Suites de Cauchy et unicité de la limite',
        ['Calculer 3/2,17/12,577/408 à la main avant d’augmenter n.',
         'Comparer erreur majorée et affichage flottant : une erreur invisible à l’écran n’est pas une égalité exacte.',
         'Rédiger les trois conclusions : Cauchy dans ℚ, convergence dans ℝ, aucune limite dans ℚ.'],
        'Récurrences, suites monotones et irrationalité de √2.',
        'Complétude, Banach et fermeture d’un sous-espace complet.',
        'Complétion de ℚ et convergence quadratique de Newton.',
        'Une preuve de l’incomplétude de ℚ qui reste valide au-delà de la précision machine.'),
    'compacts_recouvrements': guide(
        'Comprendre un recouvrement ouvert par une condition de couverture exacte. Le laboratoire relie les formulations séquentielle et par recouvrements de la compacité, avec un seuil où des intervalles se touchent mais ne couvrent pas.',
        'Centres j/m, j=0,…,m ; r est leur rayon ouvert | m est le nombre de pas et il y a m+1 centres | Uₙ=]−1,1−1/n[ recouvrent [0,1[ ; N limite seulement la sous-famille affichée',
        'Couverture de [0,1] par les ouverts du réseau iff r>1/(2m) | À l’égalité, les points de contact restent exclus | Aucun nombre fini des Uₙ ne couvre [0,1[',
        'Inégalités strictes aux milieux des mailles | Sous-recouvrement fini | Suites minimisantes et points manquants',
        ['Avec m=10 et r=0,05, chercher explicitement les points manquants aux contacts.',
         'Augmenter r à 0,055 et quantifier la marge qui restaure la couverture.',
         'Pour U₁,…,U_N, trouver un point de [0,1[ au-delà de leur borne et expliquer l’échec de tout choix fini.'],
        'Intervalles ouverts et réunions.',
        'Heine–Borel, recouvrements et compacité métrique.',
        'Nombre de Lebesgue d’un recouvrement et précompacité.',
        'Un seuil strict calculé et un recouvrement infini dont aucune sous-famille finie ne suffit.'),
    'valeurs_extremes': guide(
        'Voir exactement pourquoi un supremum est atteint sur une ellipse fermée, puis perdu lorsqu’on ouvre le même domaine. L’expérience relie compacité, Cauchy–Schwarz et optimisation d’une forme linéaire.',
        'E : x²/a²+y²/b²≤1, avec a,b>0 ; domaine ouvert utilise <1 | ℓθ(x,y)=x cosθ+y sinθ, θ en degrés dans les contrôles | N règle une suite de points intérieurs vers l’extrémité maximisante',
        'Le supremum exact vaut M=√(a²cos²θ+b²sin²θ)>0 | Le point extrémal est (a²cosθ/M,b²sinθ/M) | Sur l’ellipse ouverte, les extrema de cette forme non nulle ne sont pas atteints',
        'Changement de variables x=au,y=bv | Cauchy–Schwarz et cas d’égalité | Théorème des valeurs extrêmes',
        ['Choisir a=3,b=1,θ=40° ; calculer M et prévoir que le maximisant n’est pas radialement aligné avec θ.',
         'Passer au domaine ouvert puis augmenter N : distinguer les valeurs prises et leur supremum.',
         'Rédiger les trois hypothèses du théorème et localiser celle qui disparaît dans le second cas.'],
        'Formes linéaires en coordonnées et extrema sur un segment.',
        'Compacité, extrema atteints et optimisation quadratique.',
        'Fonctions d’appui des convexes et dualité des normes.',
        'Un maximum exact sur le fermé et une suite maximisante sur l’ouvert, sans confusion entre les deux.'),
    'heine_continuite': guide(
        'Lire les quantificateurs de continuité uniforme et identifier les hypothèses de Heine. Deux exemples emblématiques séparent compacité, uniformité et propriété lipschitzienne.',
        'f(x)=sin(x²) sur ℝ, ou sur [−R,R] ; R est un rayon d’étude | Paires xₙ=√(2πn), yₙ=√(2πn+π/2) pour le contre-exemple global | g(x)=√x sur [0,1] ; n règle les témoins près de zéro',
        'sin(x²) est 2R-lipschitzienne sur le compact choisi | Les paires globales peuvent sortir de la fenêtre graphique sans cesser d’appartenir à ℝ | √x est uniformément continue mais non lipschitzienne près de zéro',
        'Quantificateurs et contradiction | Accroissements finis | Modules de continuité Lipschitz et Hölder',
        ['Fixer R=4 et établir |f′|≤8 sur le compact.',
         'Augmenter n et calculer distance des témoins puis distance de leurs images ; expliquer l’échec sur ℝ.',
         'Passer à √x et trouver δ=ε² sans utiliser une dérivée uniformément bornée.'],
        'Continuité, dérivée et accroissements finis.',
        'Théorème de Heine, uniformité et contre-exemples par suites.',
        'Équicontinuité et théorème d’Arzelà–Ascoli.',
        'Trois notions distinctes avec leurs domaines, une borne locale et deux certificats globaux.'),
    'image_compacte': guide(
        'Donner une application géométrique substantielle à l’exercice 6 : le produit de deux compacts est compact, puis l’addition construit leur somme. La fonction d’appui donne des extrémités exactes sans explorer toutes les paires.',
        'A est l’ellipse pleine de demi-axes a,b | B=[−sv,sv], v=(cosθ,sinθ), s=length | φ=direction définit w=(cosφ,sinφ) et la droite d’appui',
        'Les deux domaines sont fermés bornés et non vides | Les angles des contrôles sont en degrés, convertis en radians dans les formules | La somme A+B est l’image du produit par une application continue',
        'Extraction à deux étages avec indices composés | Image continue d’un compact | Cauchy–Schwarz et fonction d’appui additive',
        ['Avec θ=0, dessiner mentalement la somme d’une ellipse et d’un segment horizontal.',
         'Choisir φ perpendiculaire au segment : expliquer pourquoi sa contribution d’appui devient nulle.',
         'Reprendre la preuve de l’exercice 6 en écrivant φ∘ψ pour les indices communs aux deux extractions.'],
        'Addition de vecteurs et images de domaines.',
        'Produit compact, image compacte, extrema et sommes de Minkowski.',
        'Géométrie convexe et optimisation par fonctions d’appui.',
        'Une construction graphique et une preuve d’existence des extrema qui utilisent le même produit compact.'),
    'applications_lineaires': guide(
        'Relier la continuité d’une application linéaire à une borne uniforme, avec de vraies matrices denses de dimension 4 à 8. L’image graphique d’un cercle singulier ne réduit pas l’application entière à une matrice 2×2.',
        'A agit sur ℝⁿ, n=dimension ; seed fixe les bases orthogonales denses | κ=condition est le rapport σmax/σmin, avec σmin=1 | Normes d’opérateur 1,2,∞ et valeurs singulières calculées sur toute la matrice',
        'L’espace de départ a une dimension finie | Le cercle représenté appartient au plan de deux vecteurs singuliers | La norme 2 est σmax ; les normes 1 et ∞ viennent des sommes de colonnes et de lignes',
        'Linéarité et réduction à zéro | Norme subordonnée | SVD et équivalence des normes',
        ['Prendre n=5,κ=12 et lire séparément taille, normes et valeurs singulières.',
         'Passer à κ=1 : vérifier l’isométrie euclidienne malgré les coefficients denses.',
         'Rédiger la borne ‖Ax‖₂≤σmax‖x‖₂ puis comparer avec l’évaluation et la dérivation sur les polynômes.'],
        'Calcul matriciel et majorations par sommes de coefficients.',
        'Continuité des applications linéaires, normes d’opérateur et valeurs singulières.',
        'Conditionnement, opérateurs non bornés et analyse fonctionnelle.',
        'Une borne de continuité valide dans tout ℝⁿ, accompagnée d’une représentation d’un plan clairement identifié.'),
    'normes_dimension_infinie': guide(
        'Réfuter l’équivalence de deux normes par une seule famille de fonctions bien choisie. Le laboratoire explique pourquoi l’hypothèse « dimension finie » ne peut être supprimée du théorème des normes équivalentes.',
        'E=C([0,1],ℝ) contient des polynômes de degrés arbitraires | f_N(x)=x^N ; N est l’exposant | Normes exactes : sup=1, L¹=1/(N+1), L²=1/√(2N+1)',
        'E est un espace de dimension infinie | Le pic près de 1 peut être plus étroit qu’une maille du dessin | Les normes intégrales sont calculées par primitives exactes',
        'Primitives de puissances | Rapport de normes | Contre-exemple à une constante universelle',
        ['Calculer les trois normes pour N=10 et comparer avec le dessin.',
         'Augmenter N à 1000 : écrire pourquoi le rapport ‖f_N‖∞/‖f_N‖₁ interdit toute constante fixe.',
         'Comparer avec les polynômes de degré ≤d : pourquoi l’équivalence y revient-elle pour chaque d fixé ?'],
        'Intégrales, maxima et concentration près d’un bord.',
        'Normes de fonctions et non-équivalence en dimension infinie.',
        'Espaces Lᵖ, complétions et convergence faible.',
        'Une preuve indépendante du maillage : les mêmes fonctions tendent vers zéro dans certaines normes et pas dans d’autres.'),
    'boule_non_compacte': guide(
        'Reprendre l’exercice 9 sous une forme visuelle et algébrique : une matrice de Gram donne l’orthogonalité, et les distances exactes interdisent toute extraction convergente. Le labo montre le point précis où fermé borné cesse d’impliquer compact.',
        'vₙ(t)=e^(int)/√(2π), t∈[0,2π] | M compte les modes affichés dans le tableau de Gram | probe choisit une fréquence ; la suite mathématique possède tous les n≥0',
        'La norme est L² sur les fonctions continues, avec valeurs complexes | ‖vₙ‖₂=1 et distance √2 pour deux indices distincts | Les intégrales sont analytiques ; un tracé peut aliasser les modes sans modifier ces résultats',
        'Intégrales d’exponentielles complexes | Développement d’un carré de norme | Cauchy, précompacité et extraction',
        ['Pour M=12, expliquer tous les 1 diagonaux et 0 hors diagonale de la matrice de Gram.',
         'Augmenter la fréquence représentée : vérifier que la norme et les distances restent identiques.',
         'Prouver qu’aucune extraction de la suite infinie n’est de Cauchy, puis conclure sur la boule unité.'],
        'Oscillations et nombres complexes, avec calcul d’intégrale accompagné.',
        'Exercice 9, orthogonalité et contre-exemple à fermé borné⇒compact.',
        'Théorème de Riesz et boules d’espaces de Hilbert.',
        'Un certificat exact de non-compacité qui reste valable lorsque le nombre de modes visibles change.'),
    'denombrer_rationnels': guide(
        'Construire une vraie méthode d’énumération des rationnels et séparer cardinalité et densité. Le lien Sup est le rangement par diagonales et la réduction de fractions ; le lien Spé est la structure des unions dénombrables.',
        'p∈ℤ, q≥1, fraction réduite p/q avec pgcd(|p|,q)=1 | H borne la hauteur |p|+q pour le dessin | target est un réel x à approcher dans la liste visible',
        'La hauteur H ne transforme pas ℚ en ensemble fini | Chaque rationnel apparaît à une hauteur finie et possède un représentant réduit unique | Une approximation dans une liste finie ne prouve pas à elle seule la densité',
        'PGCD et unicité des fractions réduites | Parcours par diagonales finies | Injection, surjection et bijection',
        ['Avec H=6, retrouver la position de 0,1,−1 et 1/2 dans la liste.',
         'Augmenter H puis justifier qu’un rationnel p/q fixé finit toujours par apparaître.',
         'Prouver la densité séparément par qₙ=⌊10ⁿx⌋/10ⁿ et expliquer pourquoi cette preuve ne dénombre pas ℝ.'],
        'Ensembles de nombres, fractions et dénombrabilité.',
        'Produits et unions dénombrables, cardinalités comparées.',
        'Cardinaux infinis et ensembles constructibles.',
        'Une énumération sans doublon et une preuve de densité qui utilise une autre technique.'),
    'diagonale_cantor': guide(
        'Comprendre la preuve de Cantor chiffre par chiffre et identifier ce que sa fenêtre finie ne démontre pas. L’atelier relie la diagonale des suites binaires à un encodage réel injectif sans ambiguïté d’écriture.',
        'N fixe le nombre de lignes et colonnes visibles | seed produit une table reproductible de zéros et uns | dᵢ=1−sᵢ(i) ; encodage ternaire utilise les chiffres 0 et 2',
        'Le théorème concerne des lignes et colonnes infinies | Le mot visible réfute seulement les lignes visibles ; la définition générale change un chiffre de chaque ligne | L’encodage ternaire est injectif par une borne de queue',
        'Raisonnement par contradiction | Quantification sur tous les rangs | Somme géométrique et injection',
        ['Avec N=6, montrer sur chaque ligne le chiffre où elle diffère de l’antidiagonale.',
         'Agrandir N sans parler d’un dernier rang : écrire la définition pour tous les i∈ℕ.',
         'Minorer l’écart entre deux encodages ternaires au premier chiffre différent.'],
        'Suites binaires et contradiction élémentaire.',
        'Non-dénombrabilité, parties d’un ensemble et encodage ternaire.',
        'Théorème de Cantor et hiérarchie des cardinaux.',
        'Une preuve infinie explicitement distinguée du tableau fini qui l’illustre.'),
    'ensemble_cantor': guide(
        'Réunir dans un exemple compact, fermeture, intérieur vide, non-dénombrabilité et absence de connexes non triviaux. Le but est de montrer que la longueur totale d’une construction ne compte pas ses points.',
        'k=level est le rang de retrait des tiers centraux | C_k contient 2ᵏ intervalles de longueur 3⁻ᵏ | address choisit une adresse binaire modulo 2ᵏ ; son extrémité ternaire appartient au compact limite',
        'C=⋂k≥0C_k est l’objet limite, distinct de chaque étape finie | Les étapes contiennent des intervalles ; C n’en contient aucun de longueur positive | La longueur totale (2/3)ᵏ ne représente pas un cardinal',
        'Intersections de fermés compacts | Encodage ternaire | Connexes de ℝ et points non isolés',
        ['Au rang k=3, compter les intervalles et calculer leur longueur totale.',
         'Lire une adresse et relier les bits aux chiffres ternaires 0 ou 2 du point choisi.',
         'Prouver que C est compact, sans intervalle et non dénombrable en utilisant trois arguments séparés.'],
        'Suites géométriques et ensembles emboîtés.',
        'Compact parfait, intérieur vide et totale discontinuité.',
        'Mesure nulle, dimension fractale ln2/ln3 et espaces de Cantor.',
        'Une classification riche qui distingue l’étape dessinée et l’intersection infinie.'),
    'rationnels_irrationnels': guide(
        'Approcher le même réel par deux suites dans des ensembles denses disjoints. L’expérience prépare les preuves de continuité sur un dense et le contre-exemple à l’intersection arbitraire de deux denses.',
        'x=target est le réel choisi ; N compte les rangs affichés | qₙ=⌊10ⁿx⌋/10ⁿ est rationnel | rₙ=qₙ+√2/10ⁿ est irrationnel ; les décimaux de contrôle sont traités exactement',
        'Le plancher est utilisé aussi pour les nombres négatifs | Les deux suites convergent vers x, sans imposer sa nature rationnelle | Les termes exacts et les erreurs majorées distinguent les ensembles au-delà des flottants',
        'Encadrement par le plancher | Irrationalité d’une somme rationnel+irrationnel | Densité séquentielle',
        ['Prendre x=0,731 et vérifier qₙ≤x avec erreur <10⁻ⁿ.',
         'Prendre une cible négative puis vérifier le sens du plancher, différent d’une troncature vers zéro.',
         'Démontrer la densité des deux ensembles et déterminer leurs frontières dans ℝ.'],
        'Décimaux, plancher et approximations.',
        'Densité, continuité déterminée sur un dense et exercice 8.',
        'Fonction de Dirichlet et propriétés locales des fonctions.',
        'Deux approximations convergentes et une conclusion indépendante de la cardinalité des ensembles.'),
    'sinus_topologue': guide(
        'Étudier un exemple où les implications convexe⇒connexe par arcs⇒connexe ne se renversent pas. Le cœur formateur consiste à prouver la connexité par adhérence puis l’absence de chemin par une oscillation forcée.',
        'G={(x,sin(1/x)):0<x≤1} ; V={0}×[−1,1] ; S=G∪V | turns règle les oscillations dessinées, sans tronquer la définition | height choisit un point (0,y₀) et une suite de G qui l’approche',
        'Le dessin ne montre qu’un préfixe x≥δ de G et la verticale limite | La connexité de S est analytique, pas une connexion de pixels | Le contre-exemple concerne des chemins continus sur tout un intervalle',
        'Image continue d’un intervalle | Adhérence d’un connexe | TVI et oscillations près de zéro',
        ['Choisir y₀=0,4 puis écrire des phases θ+2πn avec sinθ=y₀.',
         'Augmenter turns : expliquer pourquoi aucune coupure finie ne représente l’adhérence complète.',
         'Supposer un chemin quittant la verticale et produire deux suites de temps avec ordonnées ±1.'],
        'Composées trigonométriques et limites, lecture guidée.',
        'Connexité par adhérence et contre-exemple connexe sans arcs.',
        'Connexité locale et pathologies des espaces compacts.',
        'Un compact connexe sans chemin entre ses deux parties, établi par deux démonstrations complémentaires.'),
    'gl_composantes': guide(
        'Utiliser le déterminant comme fonction continue pour comprendre les composantes de GL, et distinguer GL⁺ de SL. Les matrices denses 4×4 relient la topologie à l’algèbre linéaire sans se réduire à un exemple 2×2.',
        'A=Q diag(λ,1,2,3)R, Q,R orthogonales de déterminant 1 | Sur ℝ, λ=t et det A=6t | Sur ℂ, λ=e^(iθ) et det A=6e^(iθ)',
        't=0 donne une matrice singulière | Sur ℝ, un chemin inversible ne peut changer de signe | GL⁺ signifie det>0 ; SL signifie det=1, deux ensembles différents',
        'Déterminant polynomial et continuité | TVI et image réciproque d’un ouvert | Décomposition polaire pour les composantes',
        ['Choisir t=1 puis calculer det A : montrer que A appartient à GL⁺ mais pas à SL.',
         'Déplacer t de 1 à −1 : localiser exactement la singularité et l’obstacle topologique.',
         'Passer au chemin complexe et expliquer comment une phase contourne zéro sans annuler le déterminant.'],
        'Déterminant, matrices inversibles et continuité, guidés.',
        'Topologie de Mₙ, ouverture, densité et composantes de GL.',
        'Groupes de Lie, décomposition polaire et orientation.',
        'Une séparation réelle par le signe et un chemin complexe explicite, avec SL correctement distingué.'),
    'orthogonal_compact': guide(
        'Comparer deux ensembles matriciels fermés dont un seul est compact. La technique CPGE vérifie séparément fermeture par équations continues et bornitude par une norme, puis relie orientation et rotations.',
        'O₄={A:AᵀA=I} ; angle règle les deux rotations planes | orientation choisit det±1 | T règle l’étirement Q diag(eᵀ,e⁻ᵀ,1,1)R dans SL₄',
        'Q,R fixes orthogonales de determinant 1 | Norme de Frobenius de toute orthogonale 4×4 égale à 2 | Le déterminant 1 seul ne borne pas la matrice',
        'Images réciproques de singletons | Trace AᵀA et norme de Frobenius | Fermé borné en dimension 16',
        ['Varier angle et orientation en vérifiant AᵀA=I, norme 2 et determinant±1.',
         'Augmenter T dans SL₄ et calculer le gain eᵀ sans changer le volume.',
         'Rédiger deux preuves de fermeture, puis la borne d’O₄ et le contre-exemple à la borne de SL₄.'],
        'Colonnes unitaires, produits scalaires et rotations.',
        'Compacité des groupes classiques et valeurs singulières.',
        'Groupes de Lie compacts et déformations non compactes.',
        'Deux groupes fermés, avec un argument précis expliquant la compacité de l’un et la fuite de l’autre.'),
    'point_fixe': guide(
        'Relier la définition de Banach à une méthode constructive de résolution. Le labo explique pourquoi une contraction assure existence, unicité et convergence, et pourquoi la seule existence d’un fixe ne suffit pas à une itération fiable.',
        'T(x)=cos x sur [0,1], taux q₀=sin1 | Variante affine T(x)=qx+0,7 sur ℝ, taux |q| | x₀ est le départ et N le nombre d’itérations ; les bornes sont démontrées lorsque le taux est <1',
        'Le domaine est complet et T doit l’envoyer dans lui-même | Le q du contrôle affine peut être négatif ; le taux est sa valeur absolue | q=1 avec biais 0,7 donne aucun fixe ; q=−1 donne un cycle sauf départ au fixe',
        'Somme géométrique et suite de Cauchy | Passage à la limite par continuité | Borne d’erreur a priori et a posteriori',
        ['Pour cos, vérifier T([0,1])⊂[0,1] puis calculer la borne sin1 sur la dérivée.',
         'Choisir q=0,95 dans le modèle affine et comparer nombre d’itérations et borne d’erreur.',
         'Choisir q=−1,05 puis q=1 : distinguer fixe répulsif, cycle et absence de point fixe.'],
        'Récurrences, suites géométriques et dérivées.',
        'Théorème du point fixe, complétude et convergence quantitative.',
        'Picard pour les EDO et algorithmes d’optimisation.',
        'Une méthode de résolution accompagnée de ses hypothèses et d’une estimation garantie de l’erreur.'),
    'chemins_niveaux': guide(
        'Explorer un changement de connexité en faisant varier un niveau, et montrer que l’inégalité stricte ou large décide du pont au seuil. Le lien CPGE est la continuité, ses images réciproques et le TVI sur les chemins.',
        'F(x,y)=((x−1)²+y²)((x+1)²+y²) | b>0 fixe le niveau b⁴ | closed choisit F≤b⁴ ou F<b⁴ ; les foyers sont (±1,0)',
        'Sous-niveau large fermé borné donc compact | Pour b<1, aucun point de l’ensemble n’a x=0 | À b=1, zéro appartient au niveau large et manque au niveau strict',
        'Images réciproques d’ouverts et de fermés | Coordonnées polaires et ensembles étoilés | TVI pour interdire un chemin',
        ['Avec b=0,8, calculer F(0,y) et prouver la séparation des deux lobes.',
         'Choisir b=1 et comparer strict/large avant de se fier au pont visible dans le dessin.',
         'Choisir b=1,4 et écrire le critère radial qui relie chaque point à zéro.'],
        'Courbes de niveau et fonctions polynomiales, guidées.',
        'Compacité de sous-niveaux, connexité et paramètres critiques.',
        'Topologie des niveaux et théorie de Morse.',
        'Une classification analytique de part et d’autre d’un seuil, robuste aux effets du maillage.'),
    'homeomorphisme': guide(
        'Tester la définition entière d’un homéomorphisme, y compris la continuité de l’inverse. La comparaison entre une couture de cercle et une courbe compacte explique le théorème du recueil sur les injections continues d’un compact.',
        'Enroulement : f(t)=(cos t,sin t), t∈[0,2π[ | n règle tₙ=2π−1/n, dont les images tendent vers f(0) | Courbe compacte : g(t)=(t,t²,t³), t∈[−1,1], inverse projection sur la première coordonnée',
        'La bijection continue sur le cercle n’a pas un domaine compact | La représentation de la courbe est une projection graphique de ℝ³ | La continuité de l’inverse compact se prouve par images de fermés',
        'Critère séquentiel de continuité | Image compacte et fermé relatif | Invariant de connexité après retrait d’un point',
        ['Augmenter n sur le cercle et comparer les images proches à leurs antécédents éloignés de zéro.',
         'Passer à la courbe et retrouver son inverse à partir de la première coordonnée.',
         'Rédiger la preuve compact⇒inverse continu, puis rappeler pourquoi ℝ et ℝ² ne sont pas homéomorphes.'],
        'Bijections, composées et suites, accompagnés.',
        'Homéomorphismes, topologie relative et compact-Hausdorff.',
        'Plongements, quotients et invariants topologiques.',
        'Un contre-exemple précis à « bijection continue suffit » et une condition qui rétablit la conclusion.'),
}

for index, lab_id in enumerate(ORDER):
    LAB_GUIDES[lab_id]['lesson_numbers'] = [2*index+1, 2*index+2]
