"""Objectifs, objets, premiers gestes et niveaux de chaque expérience."""
from cours import ORDER


def guide(purpose, objects, assumptions, techniques, steps, sup, spe, beyond, expected):
    # Only the spaced separator splits entries, never the bars in |x|.
    return dict(purpose=purpose, objects=objects.split(' | '),
                assumptions=assumptions.split(' | '),
                techniques=techniques.split(' | '), first_steps=steps,
                levels=dict(sup=sup, spe=spe, beyond=beyond),
                expected=expected, lesson_numbers=[])


LAB_GUIDES = {
    'boules_normes': guide(
        'Une boule rassemble les points situés à moins d’une longueur donnée du centre. Calculer cette longueur avec trois normes, puis prévoir si un même point appartient au losange, au disque ou au carré. Le rayon restant avant le bord permet ensuite de construire une petite boule entièrement contenue dans la grande : c’est le sens concret d’un point intérieur.',
        'Le point est (x,y)∈ℝ² ; le centre est (0,0) et r>0 est le rayon | Norme 1 : |x|+|y| ; norme 2 : √(x²+y²) ; norme ∞ : max(|x|,|y|) | Pour la norme p, p≥1 ; la marge r−‖(x,y)‖ est la longueur disponible avant le bord',
        'La boule ouverte utilise <r ; la boule fermée utilise ≤r | Une marge positive permet un voisinage intérieur ; une marge nulle place le point sur la sphère | Des normes équivalentes donnent les mêmes ouverts en adaptant les rayons ; leurs boules de rayon 1 ne sont pas égales',
        'Calculer trois normes | Appliquer l’inégalité triangulaire | Choisir un rayon intérieur strictement positif',
        ['Pour r=1 et (x,y)=(0,7;0,7), calculer 1,4, √0,98 et 0,7 ; prévoir les trois appartenances avant de changer de norme.',
         'Placer le point (1,0), puis choisir boule ouverte et fermée : traduire la différence entre <1 et ≤1.',
         'Pour un point intérieur, prendre δ=r−‖(x,y)‖ et justifier que tout point à distance <δ de lui reste dans la boule.'],
        'MPSI : coordonnées, valeur absolue et inégalités ; préparation au vocabulaire des normes.',
        'MP : normes usuelles, boules et convexité (p.11), ouverts (p.12), équivalence en dimension finie (p.13).',
        'Prolongement accompagné : comparer les formes des boules pour des exposants p différents.',
        'Trois calculs de longueur, une décision d’appartenance et un rayon intérieur justifié par une inégalité.'),
    'interieur_frontiere': guide(
        'Un point intérieur possède un petit disque qui reste dans A. Un point adhérent peut être approché aussi près que l’on veut par des points de A. Un point de frontière peut être approché depuis A et depuis son complémentaire. Classer le centre et le bord d’un disque, puis expliquer pourquoi un trou réduit à un point change la frontière.',
        'A est un disque ouvert ou fermé, un anneau r/2≤‖z‖≤r, ou un disque ouvert privé du centre | (x,y) est le point testé ; ε>0 règle le rayon du petit disque observé | r>0 est le rayon extérieur ; A°, Ā et Fr(A) désignent intérieur, adhérence et frontière',
        'L’espace de référence est ℝ² avec la longueur euclidienne | « Intérieur » demande l’existence d’un rayon ; « adhérent » demande que tous les rayons rencontrent A | Le dessin d’un voisinage illustre la définition ; les inégalités permettent de conclure pour tous les rayons',
        'Traduire les mots par des boules | Utiliser ∃ε>0 et ∀ε>0 | Calculer intérieur, adhérence et complémentaire',
        ['Prendre le disque privé de son centre et tester (0,0) : chercher des points de A arbitrairement proches, puis un voisinage inclus dans A.',
         'Tester (r,0) sur le disque ouvert, puis fermé : préciser appartenance, intérieur et frontière dans chaque cas.',
         'Passer à l’anneau avec r=1 : calculer A°, Ā et Fr(A), et expliquer le rôle des cercles de rayons 1/2 et 1.'],
        'MPSI : inégalités et suites approchant un réel (p.12–13) ; vocabulaire préparatoire.',
        'MP : points intérieurs et adhérents, intérieur, adhérence et frontière (p.12).',
        'Prolongement accompagné : pourquoi la frontière de ℚ dans ℝ est toute la droite.',
        'Une classification du centre, des bords et du trou, avec les définitions justifiées par des voisinages.'),
    'adherence_suite': guide(
        'Dessiner les nombres 1,1/2,1/3,… et chercher ce qui se passe près de zéro. Zéro n’est pas dans cette liste infinie, mais des points de la liste s’en approchent arbitrairement. Distinguer une distance de borne inférieure nulle et une distance réellement obtenue en un point de A, puis expliquer pourquoi ajouter zéro rend l’ensemble compact.',
        'A={1/n:n≥1} est un ensemble infini ; N compte seulement les premiers points dessinés | x est le réel testé ; ε>0 est le rayon de l’intervalle autour de x | Le choix « ajouter zéro » remplace A par A∪{0}',
        'Sans ajouter zéro, la borne inférieure des distances 1/n vaut 0, sans être une valeur prise ; avec zéro ajouté, le minimum est réalisé en zéro | N ne change pas l’ensemble étudié : tous les n≥1 restent dans sa définition | Dans ℝ, fermé et borné signifie compact ; cela s’applique à A∪{0}, pas à A',
        'Encadrer une suite par 1/n | Distinguer borne inférieure et minimum | Reconnaître un fermé par les limites de ses suites',
        ['Sans ajouter zéro, choisir ε=0,08 : trouver un n avec 1/n<ε, puis recommencer avec ε plus petit.',
         'Tester x=1/4 ; calculer un rayon plus petit que les écarts avec 1/3 et 1/5 pour isoler ce point.',
         'Ajouter zéro et justifier que toutes les limites de suites de l’ensemble y restent ; conclure par fermé et borné.'],
        'MPSI : bornes inférieures, suites convergentes et densité séquentielle (p.12–13).',
        'MP : adhérence et fermés par suites (p.12), compacts de dimension finie (p.13).',
        'Prolongement accompagné : distinguer point isolé et point d’accumulation, où des points distincts s’approchent.',
        'La preuve Ā=A∪{0}, et une explication de distance nulle sans appartenance ni minimum.'),
    'topologie_relative': guide(
        'Travailler sur un domaine limité à X=[0,1]. Autour de zéro, seuls les points de X comptent : un intervalle [0,b[ peut donc être ouvert relativement à X tout en ne l’étant pas dans ℝ. Construire les voisinages dans les deux domaines pour donner un sens précis au mot « relatif ».',
        'X=[0,1] est le domaine de référence | A=X∩]−1/2,b[ ; si b≤1, A=[0,b[ ; si b>1, A=X | Le voisinage relatif du point x est ]x−ε,x+ε[∩X',
        'Le point x appartient à X ; les voisins extérieurs à X ne sont pas examinés | Un ouvert relatif s’écrit X∩O avec O ouvert dans ℝ | La même partie peut avoir deux intérieurs et deux frontières différents selon le domaine de référence',
        'Intersecter un intervalle avec le domaine | Construire un voisinage relatif | Indiquer l’espace dans chaque conclusion',
        ['Prendre b=0,65,x=0,ε=0,2 : écrire le voisinage relatif [0;0,2[ et vérifier qu’il reste dans A.',
         'Prendre b=x=0,5 : expliquer pourquoi ce point manque à A mais peut être approché par des points de A.',
         'Prendre b=1,2 : A est tout X ; comparer sa frontière dans X et sa frontière dans ℝ.'],
        'MPSI : intervalles et domaines des fonctions (p.12–14) ; entrée guidée vers les voisinages.',
        'MP : ouverts, fermés et voisinages relatifs (p.12).',
        'Prolongement accompagné : comparer la topologie d’un sous-ensemble avec celle de l’espace qui le contient.',
        'Des conclusions portant explicitement sur X ou sur ℝ, avec un voisinage qui explique la différence.'),
    'operations_ouverts': guide(
        'Intersecter plusieurs petits intervalles ouverts, puis demander ce qui reste lorsque l’on impose toutes les contraintes. Comparer avec une réunion de segments fermés. Ces deux calculs font comprendre pourquoi le mot « fini » est indispensable dans certaines règles du cours.',
        'Intersection : Uₙ=]−1/n,1/n[ ; après N termes, le résultat est ]−1/N,1/N[ | Réunion : Fₙ=[1/n,1] ; après N termes, le résultat est [1/N,1] | x est le réel testé et N le nombre d’ensembles retenus',
        'L’intersection infinie des Uₙ vaut {0}, qui n’est pas ouvert dans ℝ | La réunion infinie des Fₙ vaut ]0,1], qui n’est pas fermé dans ℝ | Une réunion d’ouverts et une intersection de fermés restent valables avec un nombre quelconque d’ensembles',
        'Calculer une intersection et une réunion | Choisir le minimum d’un nombre fini de rayons | Donner un contre-exemple à une règle trop large',
        ['Choisir N=5 : écrire ]−0,2;0,2[, puis prouver que seul zéro appartient à tous les Uₙ.',
         'Passer aux segments [1/n,1] : zéro reste exclu de toute la réunion ; expliquer pourquoi il appartient à son adhérence.',
         'Écrire les quatre règles sur ouverts et fermés en indiquant à quels endroits l’opération doit rester finie.'],
        'MPSI : unions, intersections, bornes et limites de 1/n (p.12–13).',
        'MP : réunions et intersections d’ouverts et de fermés (p.12) ; usage des parties denses.',
        'Prolongement accompagné : intersections infinies de denses ouverts ; le théorème de Baire est hors programme MP.',
        'Deux calculs d’ensembles infinis et deux contre-exemples qui expliquent les limites des règles finies.'),
    'distance_ensemble': guide(
        'Chercher le point le plus proche dans une réunion de deux disques. Une distance minimale est un nombre, tandis que les points qui la réalisent peuvent être plusieurs. Calculer les deux distances aux disques pour comprendre cette différence, puis relier la fonction distance à la continuité étudiée en MP.',
        'A est la réunion de deux disques fermés de rayon r | La séparation est la distance entre leurs centres ; (x,y) est le point à rapprocher de A | Pour un disque de centre c, la distance vaut max(‖(x,y)−c‖−r,0)',
        'La réunion est fermée non vide dans ℝ² : un point minimisant existe | Sur la médiatrice de deux disques séparés, deux points distincts peuvent réaliser le même minimum | La distance change d’au plus la longueur du déplacement du point : c’est le sens de 1-lipschitzienne',
        'Comparer deux distances calculées | Distinguer un nombre minimal et ses points minimisants | Appliquer l’inégalité triangulaire',
        ['Prendre séparation=3,r=0,7 et (x,y)=(0;0,8) : prévoir pourquoi les deux disques donnent la même distance.',
         'Déplacer x légèrement à droite : calculer quel disque devient plus proche et suivre la distance sans rupture.',
         'À partir de d(x,a)≤d(x,y)+d(y,a), prouver |d(x,A)−d(y,A)|≤d(x,y).'],
        'MPSI : distances euclidiennes ; comparaison avec la projection sur un sous-espace (p.33).',
        'MP : distance associée à une norme et fonction distance 1-lipschitzienne (p.11–13).',
        'Prolongement accompagné : plusieurs projections sur un ensemble non convexe ; la projection convexe générale dépasse le programme MP.',
        'Un minimum calculé, tous les points qui le réalisent, et une borne de continuité de la distance.'),
    'convexite': guide(
        'Pour être convexe, un ensemble doit contenir tout segment reliant deux de ses points. Le disque satisfait cette définition ; un anneau la réfute avec deux points opposés dont le milieu tombe dans le trou. Prévoir un segment, calculer un témoin, puis distinguer une preuve universelle et un seul essai réussi.',
        'a,b sont les angles en degrés des deux points choisis | ρ règle leur distance relative au centre ; la séparation intervient pour la réunion de deux disques | Le segment est z(t)=(1−t)u+tv, avec 0≤t≤1',
        'Un seul point de segment extérieur suffit à prouver que A n’est pas convexe | Un segment contenu dans A ne prouve pas la propriété pour toutes les paires de points | Le moteur utilise des inégalités sur tout t ; les points dessinés servent à les illustrer',
        'Calculer un milieu | Utiliser l’inégalité triangulaire sur un segment | Séparer témoin de réfutation et preuve pour tous les points',
        ['Dans l’anneau, choisir a=0°,b=180°,ρ=0,8 : calculer le milieu des deux points et vérifier qu’il manque à A.',
         'Passer au disque : majorer ‖(1−t)u+tv‖ par (1−t)‖u‖+t‖v‖ pour tout t∈[0,1].',
         'Ouvrir le labo des chemins et expliquer comment un anneau permet un détour malgré le segment qui traverse son trou.'],
        'MPSI : segments, milieux et combinaisons de vecteurs ; préparation géométrique.',
        'MP : convexité des boules et chemin dans une partie convexe (p.11,13).',
        'Prolongement accompagné : un ensemble étoilé permet de relier chaque point à un même centre.',
        'Une preuve de convexité du disque et un témoin précis de non-convexité de l’anneau.'),
    'enveloppe_convexe': guide(
        'Entourer un nuage par le plus petit polygone convexe qui contient tous ses points : c’est son enveloppe convexe. Un barycentre à poids positifs de somme 1 reste à l’intérieur. Calculer ces poids et suivre le barycentre pour relier des coordonnées simples à la définition générale de convexité.',
        'N est le nombre de points ; la graine reproduit le même nuage | α accentue le poids du premier point, choisi le plus à droite | Les sommets sont les points qui déterminent le bord ; les autres points restent dans l’enveloppe',
        'Les poids sont non négatifs et leur somme vaut 1 | Pour α=1, tout le poids porte sur le premier point | L’algorithme construit l’enveloppe du nuage fini choisi ; cette activité est un prolongement de la notion de convexe',
        'Calculer un barycentre | Lire un déterminant comme un sens de rotation | Vérifier les signes et la somme des poids',
        ['Prendre N=20 et graine=7 : compter les points du nuage puis ceux qui forment le bord.',
         'Faire passer α de 0 à 1 : prévoir la position finale et justifier que chaque barycentre reste dans le polygone.',
         'Dans le triangle (0,0),(1,0),(0,1), calculer 2(1,0)−(0,1) et expliquer pourquoi un poids négatif perd la garantie.'],
        'MPSI : combinaisons linéaires et déterminants ; activité géométrique accompagnée.',
        'MP : illustration de la convexité (p.11) et de l’image continue d’un compact (p.13) ; enveloppe non exigible.',
        'Prolongement accompagné : enveloppe convexe, algorithme du bord et théorème de Carathéodory, hors programme MP.',
        'Un polygone contenant le nuage et une justification de la position du barycentre par ses poids.'),
    'projection_convexe': guide(
        'Chercher le point le plus proche d’un rectangle ou d’un triangle fermé. Commencer par la projection sur la droite d’un côté, puis vérifier si le point trouvé appartient au côté ; sinon examiner ses extrémités. Cette expérience prolonge la projection orthogonale sur un sous-espace étudiée en MPSI vers des domaines limités.',
        'C est un rectangle ou le triangle de sommets (−1;−0,75),(1;−0,75),(0,1;1,1) | (x,y) est le point à projeter ; p est son point le plus proche dans C | ζ place le point z sur le bord pour examiner ⟨x−p,z−p⟩',
        'La distance est euclidienne et C est fermé, non vide et convexe | La projection sur un convexe général n’est pas un résultat exigible en MP | Pour ce polygone, vérifier l’inégalité aux sommets suffit grâce aux combinaisons convexes',
        'Projeter sur une droite | Vérifier l’appartenance à un segment | Développer un carré de norme',
        ['Choisir le rectangle et le point (1,4;1,2) : ramener chaque coordonnée dans son intervalle et calculer la distance.',
         'Choisir le triangle : comparer une projection sur un côté et une projection sur un sommet.',
         'Vérifier ⟨x−p,v−p⟩≤0 aux trois sommets ; développer ‖x−z‖² pour comprendre pourquoi p minimise la distance.'],
        'MPSI : projection orthogonale sur un sous-espace et distance à ce sous-espace (p.33).',
        'MP : produit scalaire, convexité (p.11) et fonction distance (p.13) ; cas polygonal traité comme application accompagnée.',
        'Prolongement accompagné : projection sur tout convexe fermé et preuve de son unicité, hors programme MP.',
        'Une construction par côtés et sommets, puis une inégalité qui certifie le point le plus proche.'),
    'connexite_chemins': guide(
        'Deux points peuvent-ils se relier sans sortir de l’ensemble ? Dans le plan privé de zéro, un détour contourne le point retiré ; sur la droite privée de zéro, aucun chemin ne relie un nombre négatif à un nombre positif. Construire le détour puis utiliser le théorème des valeurs intermédiaires pour expliquer l’obstacle sur la droite.',
        'Le domaine est le plan privé de zéro, un anneau, deux disques séparés ou la droite privée de zéro | Dans le plan et l’anneau, r₁,r₂ et l’angle règlent les points ; sur la droite, seuls r₁,r₂ interviennent ; dans les disques, les points sont fixés aux centres | L’écart positif entre les disques est le seul réglage actif de ce mode ; un chemin γ(t) doit rester dans le domaine pour tout t∈[0,1]',
        '« Connexe par arcs » signifie que toute paire de points se relie par un chemin continu | Le détour dans l’anneau doit conserver un rayon entre 1/2 et 1,5 | La connexité générale, sans référence à des chemins, est un prolongement qui n’est pas exigible en MP',
        'Paramétrer deux segments ou un arc de cercle | Vérifier chaque morceau et ses raccords | Appliquer le TVI à une coordonnée',
        ['Prendre deux points opposés du plan privé de zéro : montrer que leur segment rencontre zéro, puis construire un détour par (0,1).',
         'Passer à l’anneau : vérifier que les portions radiales et l’arc gardent des rayons autorisés.',
         'Sur la droite privée de zéro, supposer un chemin entre −1 et 1 et utiliser le TVI pour obtenir une contradiction.'],
        'MPSI : fonctions continues, intervalles et TVI (p.14).',
        'MP : chemins, connexité et composantes connexes par arcs, image continue et TVI (p.13).',
        'Prolongement accompagné : homéomorphismes et comparaison de ℝ et ℝ² après retrait d’un point.',
        'Des chemins écrits explicitement et un raisonnement par TVI qui interdit un chemin dans un autre domaine.'),
    'bolzano_weierstrass': guide(
        'Une suite bornée ne converge pas toujours, mais certaines de ses suites extraites peuvent converger. Avec uₙ=(−1)ⁿ+1/(n+1), séparer les indices pairs et impairs fait apparaître deux limites. Calculer leur erreur avant de conclure, puis retrouver précisément ce que promet le théorème de Bolzano–Weierstrass.',
        'n commence à zéro ; N est le dernier indice dessiné | Les termes pairs u₂ₖ approchent 1 ; les termes impairs u₂ₖ₊₁ approchent −1 | ε>0 fixe la précision demandée ; l’erreur vaut 1/(n+1)',
        'Une suite extraite conserve l’ordre des indices et en choisit une infinité | Les deux limites distinctes prouvent que la suite complète ne converge pas | BW garantit une extraction convergente d’une suite bornée réelle, complexe ou de dimension finie',
        'Choisir les indices pairs et impairs | Majorer l’erreur par une suite tendant vers zéro | Distinguer limite et valeur d’adhérence',
        ['Pour N=60, écrire u₂ₖ et u₂ₖ₊₁ et prévoir leurs deux limites.',
         'Choisir ε=0,01 : résoudre 1/(n+1)<ε et retrouver le rang suffisant pour chaque extraction.',
         'Rédiger pourquoi deux valeurs d’adhérence distinctes empêchent la convergence de la suite complète.'],
        'MPSI : suites extraites, divergence et Bolzano–Weierstrass (p.13).',
        'MP : suites d’un espace normé, suites extraites et valeurs d’adhérence (p.12), dimension finie (p.13).',
        'Prolongement accompagné : extraire successivement dans plusieurs coordonnées ou plusieurs paramètres.',
        'Deux suites extraites avec limites et erreurs démontrées, puis une conclusion sur la suite complète.'),
    'extraction_aleatoire': guide(
        'Reprendre le TP du recueil : tirer des nombres entre 0 et 3 et ne retenir que ceux qui battent le meilleur rapprochement de 1. Vérifier que les indices augmentent et que les distances diminuent. Calculer ensuite la probabilité de réussite d’une expérience finie pour distinguer une simulation réussie d’une garantie certaine.',
        'N est le nombre de tirages ; la graine reproduit les mêmes tirages | d est la distance tolérée à la cible 1 ; D_N est la plus petite distance des N essais | Le nombre d’expériences règle l’histogramme, qui compte les résultats de répétitions finies',
        'Le modèle suppose des tirages indépendants uniformes sur [0,3] | Pour 0<d≤1, la formule du modèle continu est P(D_N>d)=(1−2d/3)^N | Les lois continues et la convergence presque sûre sont hors programme MP : cette partie du TP est un prolongement accompagné',
        'Retenir uniquement les nouveaux meilleurs résultats | Contrôler les indices croissants | Comparer une fréquence simulée avec une formule annoncée',
        ['Prendre N=3000 : lire les indices retenus et vérifier qu’aucun n’est répété.',
         'Prendre N=100,d=0,001 : calculer la probabilité d’échec du modèle, puis changer de graine pour voir plusieurs réalisations.',
         'Expliquer pourquoi BW garantit une extraction vers une certaine limite, mais pas à lui seul une extraction vers la cible 1.'],
        'MPSI : suites extraites et BW (p.13) ; simulation comme illustration, sans résultat de probabilité continue à apprendre.',
        'MP : suites extraites et valeurs d’adhérence (p.12) ; le calcul sur une loi uniforme continue n’est pas exigible.',
        'Prolongement accompagné : loi continue du meilleur rapprochement et convergence presque sûre, hors programme MP.',
        'Une extraction avec indices croissants, une probabilité finie interprétée et une conclusion respectant les limites du modèle.'),
    'cauchy_rationnels': guide(
        'Calculer la suite de Héron u₀=2, uₙ₊₁=uₙ/2+1/uₙ avec des fractions exactes. Montrer qu’elle décroît vers √2 et estimer sa rapidité. Ce travail relève des suites récurrentes de MPSI ; il permet ensuite, en prolongement, de comprendre une suite de Cauchy dont la limite n’appartient pas à ℚ.',
        'n≤8 règle le nombre d’étapes de la récurrence | Les valeurs 2,3/2,17/12,577/408,… restent rationnelles | ε fixe la précision demandée ; l’identité d’erreur donne une borne sans dépendre des décimales affichées',
        'La convergence est d’abord prouvée dans ℝ par monotonie, minoration et passage à la limite | L’irrationalité de √2 se prouve par la parité du numérateur et du dénominateur | Suites de Cauchy, complétude et espaces de Banach sont explicitement hors programme MP',
        'Calculer une récurrence avec fractions | Étudier le signe de uₙ₊₁−uₙ | Passer à la limite et majorer l’erreur',
        ['Avec n=3, retrouver 3/2,17/12,577/408 à la main et vérifier qu’ils sont supérieurs à √2.',
         'Augmenter n : utiliser uₙ₊₁−√2=(uₙ−√2)²/(2uₙ), plutôt qu’une égalité supposée d’après l’affichage.',
         'Prouver que √2 n’est pas rationnel ; en complément, expliquer ce qui manque à ℚ pour contenir la limite.'],
        'MPSI : limite monotone, suites récurrentes, passage à la limite et vitesse de convergence (p.12–13).',
        'MP : convergence et unicité d’une limite (p.12) ; Cauchy et Banach restent hors programme.',
        'Prolongement accompagné : suite de Cauchy, c’est-à-dire termes tardifs tous proches entre eux, et complétude de ℝ.',
        'Une convergence réelle et une borne d’erreur démontrées ; le complément explique pourquoi la limite manque à ℚ.'),
    'compacts_recouvrements': guide(
        'Placer des intervalles ouverts autour des points j/m pour couvrir [0,1]. Lorsque deux intervalles se touchent seulement, leur point de contact n’est dans aucun des deux : calculer le rayon nécessaire pour une vraie couverture. Le lien au programme MP passe par les suites et les fermés bornés ; le théorème général sur les recouvrements est un complément.',
        'm est le nombre de pas et j/m, j=0,…,m, donne m+1 centres | r>0 est le rayon des intervalles ouverts | Les Uₙ=]−1,1−1/n[ couvrent [0,1[ lorsqu’on les prend tous ; N limite les premiers ouverts dessinés',
        'Les intervalles du réseau couvrent [0,1] exactement lorsque r>1/(2m) | Un compact de dimension finie est fermé et borné ; sa définition MP repose sur les suites extraites | La propriété de Borel–Lebesgue par recouvrements est explicitement hors programme MP',
        'Calculer les milieux entre deux centres | Distinguer contact et appartenance à un ouvert | Construire une suite vers une extrémité absente',
        ['Prendre m=10,r=0,05 : vérifier si le point 0,05 appartient à l’un des deux premiers intervalles.',
         'Augmenter r à 0,055 : calculer la largeur du chevauchement et justifier la couverture de toute la maille.',
         'Pour les premiers Uₙ, trouver un point de [0,1[ encore non couvert ; utiliser la suite 1−1/n pour expliquer pourquoi ce domaine n’est pas compact.'],
        'MPSI : intervalles ouverts et suites approchant une borne (p.12–14).',
        'MP : compacité définie par suites extraites, et critère fermé borné en dimension finie (p.13).',
        'Prolongement accompagné : recouvrements ouverts et Borel–Lebesgue, hors programme MP.',
        'Un seuil de couverture strict et une explication séquentielle de la non-compacité du domaine semi-ouvert.'),
    'valeurs_extremes': guide(
        'Chercher la plus grande valeur de x cosθ+y sinθ sur une ellipse pleine. Sur l’ellipse fermée, elle est obtenue en un point précis. Sur son intérieur, on peut s’en approcher autant que l’on veut sans jamais l’obtenir : c’est une borne supérieure, et non un maximum. Faire varier le domaine pour comprendre le théorème des bornes atteintes.',
        'L’ellipse fermée vérifie x²/a²+y²/b²≤1 ; son intérieur utilise <1 | a,b sont les demi-axes ; θ indique la direction du calcul | N règle les points intérieurs (1−1/N)p qui approchent le point p maximisant',
        'La borne supérieure vaut M=√(a²cos²θ+b²sin²θ) | Sur l’ellipse fermée, p=(a²cosθ/M,b²sinθ/M) appartient au domaine et donne M | Sur l’intérieur, M n’est la valeur d’aucun point ; le domaine n’est pas compact',
        'Poser x=au,y=bv | Appliquer Cauchy–Schwarz avec son cas d’égalité | Distinguer borne supérieure et maximum',
        ['Prendre a=3,b=1,θ=40° : calculer M et les coordonnées de p avant d’observer le point.',
         'Choisir l’intérieur de l’ellipse et augmenter N : calculer la valeur (1−1/N)M et sa limite.',
         'Énoncer non-vide, compact et continu ; dire précisément quelle hypothèse disparaît quand on retire le bord.'],
        'MPSI : borne supérieure et approximation par une suite (p.12–13), bornes atteintes sur un segment (p.14).',
        'MP : théorème des bornes atteintes sur un compact non vide et optimisation (p.13).',
        'Prolongement accompagné : maximiser une forme linéaire dans chaque direction pour décrire un convexe.',
        'Un maximum avec son point sur le domaine fermé, puis une borne supérieure sans point maximisant sur l’intérieur.'),
    'heine_continuite': guide(
        'Demander quelle proximité de deux arguments suffit pour rendre leurs images proches. Le choix peut dépendre du point pour la continuité, mais doit fonctionner partout pour la continuité uniforme. Comparer sin(x²) sur un segment et sur ℝ, puis √x près de zéro, avec des paires de points calculées explicitement.',
        'Pour sin(x²), R fixe le segment [−R,R] | Les points xₙ=√(2πn),yₙ=√(2πn+π/2) ont des images 0 et 1 | Pour √x sur [0,1], n règle les points proches de zéro ; |√x−√y|≤√|x−y|',
        'Sur [−R,R], |f′|≤2R donne une borne uniforme | Sur ℝ, |xₙ−yₙ| tend vers zéro mais l’écart des images vaut 1 | √x possède un rayon uniforme δ=ε², sans constante de Lipschitz près de zéro',
        'Comparer l’ordre des quantificateurs | Utiliser les accroissements finis | Construire deux suites d’arguments proches',
        ['Fixer R=4 : majorer la dérivée par 8 et choisir une proximité garantissant un écart d’images <0,01.',
         'Augmenter n : calculer yₙ−xₙ=(π/2)/(xₙ+yₙ) puis comparer les images 0 et 1.',
         'Passer à √x : prévoir δ=(0,02)² pour un écart d’images <0,02, puis expliquer pourquoi la dérivée ne fournit pas une borne globale.'],
        'MPSI : continuité, dérivation et accroissements finis ; rappels de p.14 et prolongements du calcul différentiel.',
        'MP : continuité uniforme, applications lipschitziennes et théorème de Heine (p.13).',
        'Prolongement accompagné : une borne de type Hölder utilise une puissance de la distance, ici √δ.',
        'Un rayon valable sur tout le segment, une paire de suites qui réfute l’uniformité sur ℝ et un exemple uniforme sans Lipschitz.'),
    'image_compacte': guide(
        'Ajouter à chaque point d’une ellipse pleine tous les points d’un segment. L’ensemble obtenu reste compact : il est l’image continue du produit de deux compacts, comme dans l’exercice 6. Calculer ensuite la plus grande coordonnée dans une direction pour voir où les bornes sont réellement obtenues.',
        'A est l’ellipse pleine de demi-axes a,b | B=[−sv,sv], où s est la demi-longueur et v=(cosθ,sinθ) la direction du segment | φ choisit la direction w=(cosφ,sinφ) ; on maximise ⟨w,z⟩ sur A+B',
        'A et B sont compacts non vides et l’addition est continue | Pour extraire dans A×B, la seconde extraction se fait à partir des indices déjà choisis pour A | Les angles des commandes sont en degrés ; les fonctions trigonométriques du calcul utilisent les radians',
        'Extraire successivement les deux coordonnées | Utiliser l’image continue d’un compact | Additionner deux maxima indépendants',
        ['Prendre un segment horizontal : prévoir de combien l’ellipse s’allonge de chaque côté.',
         'Choisir φ perpendiculaire au segment : calculer cos(φ−θ)=0 et expliquer sa contribution nulle à la borne.',
         'Nommer les extractions i(k), puis i(j(k)), avec i et j strictement croissantes ; justifier que les deux coordonnées convergent avec les mêmes indices.'],
        'MPSI : addition de vecteurs et suites extraites (p.13).',
        'MP : produit fini de compacts, image continue et bornes atteintes (p.13).',
        'Prolongement accompagné : somme de Minkowski et fonction d’appui, c’est-à-dire maximum dans chaque direction.',
        'Une construction par addition, sa preuve de compacité et une borne directionnelle avec un point qui la réalise.'),
    'applications_lineaires': guide(
        'Appliquer une matrice dense de dimension 4 à 8 à des vecteurs de longueur 1 et comparer les longueurs obtenues. La norme d’opérateur est le plus grand agrandissement possible. Relier cette borne à ‖Ax−Ay‖≤C‖x−y‖ pour expliquer concrètement la continuité d’une application linéaire.',
        'n est la dimension ; la graine reproduit la même matrice dense | κ est le rapport entre le plus grand et le plus petit agrandissement euclidien | La figure ne montre qu’un cercle dans un plan de ℝⁿ ; les normes sont calculées sur toute la matrice',
        'La norme 1 d’opérateur est la plus grande somme de valeurs absolues d’une colonne ; la norme ∞ utilise les lignes | En norme 2, le calcul passe par la plus grande valeur propre de AᵀA | La décomposition en valeurs singulières utilisée par le logiciel est un prolongement, pas un attendu du programme MP',
        'Calculer des sommes de lignes et colonnes | Majorer ‖Ax‖ par C‖x‖ | Utiliser le théorème spectral sur AᵀA',
        ['Choisir n=5,κ=12 : lire les trois normes et vérifier que les longueurs des vecteurs tests restent sous la borne euclidienne.',
         'Choisir κ=1 : constater que les longueurs sont conservées et relier cela à une matrice orthogonale.',
         'Écrire ‖Ax−Ay‖≤‖A‖op‖x−y‖ puis expliquer pourquoi quelques directions testées ne suffisent pas à trouver le maximum.'],
        'MPSI : applications linéaires, matrices et calcul en coordonnées ; préparation aux majorations.',
        'MP : norme d’opérateur et critère de continuité linéaire (p.13), théorème spectral (p.11).',
        'Prolongement accompagné : décomposition en valeurs singulières, abrégée SVD, et conditionnement ; ces outils ne sont pas exigibles comme tels en MP.',
        'Une borne pour tous les vecteurs et une distinction entre les essais dessinés et le calcul du plus grand agrandissement.'),
    'normes_dimension_infinie': guide(
        'Une fonction peut rester haute près de 1 tout en ayant une aire très petite. Pour f_N(x)=x^N sur [0,1], calculer la norme uniforme, la norme de convergence en moyenne et celle en moyenne quadratique. Leurs rapports montrent pourquoi les normes ne sont pas toujours équivalentes quand on autorise des degrés sans limite.',
        'N est l’exposant ; toutes les fonctions continues sur [0,1] sont admises | Norme uniforme : max|f| ; norme en moyenne : ∫₀¹|f| | Norme en moyenne quadratique : √∫₀¹|f|² ; les notations sont ‖f‖∞,‖f‖₁,‖f‖₂',
        'Les degrés N ne sont pas bornés : on travaille dans un espace de dimension infinie | Les valeurs exactes sont 1,1/(N+1),1/√(2N+1) | Le calcul intégral reste valable même si le dessin ne résout plus la zone étroite près de 1',
        'Calculer une primitive de puissance | Chercher le maximum en x=1 | Contredire une constante d’équivalence par un rapport non borné',
        ['Prendre N=10 : calculer les normes 1,1/11 et 1/√21 avant de les lire.',
         'Prendre N=1000 : calculer le rapport ‖f_N‖∞/‖f_N‖₁=N+1 ; montrer qu’aucune constante fixée ne borne tous les rapports.',
         'Comparer avec les polynômes de degré ≤d fixé : expliquer où intervient la dimension finie dans le théorème d’équivalence.'],
        'MPSI : puissances, intégration et comparaison de suites ; préparation par calculs explicites.',
        'MP : normes uniforme, en moyenne et en moyenne quadratique, non-équivalence démontrée par suites (p.12).',
        'Prolongement accompagné : espaces Lᵖ et complétion ; les espaces de Banach sont hors programme MP.',
        'Trois normes exactes et une suite qui prouve la non-équivalence, sans dépendre de la finesse du dessin.'),
    'boule_non_compacte': guide(
        'Dans une boule unité de fonctions, chercher une suite dont aucun choix d’indices ne permet une convergence. Les modes vₙ=e^(int)/√(2π) ont tous norme 1, mais deux modes distincts restent à distance √2. Calculer cette distance pour montrer concrètement pourquoi fermé et borné ne suffit plus en dimension infinie.',
        't∈[0,2π] et vₙ(t)=e^(int)/√(2π) est une fonction complexe | M est le nombre de modes du tableau ; le numéro choisi règle le mode dessiné | La norme 2 vaut √∫₀²π|f(t)|²dt ; le tableau de Gram rassemble les intégrales de produits de modes',
        'Les intégrales exactes donnent norme 1 et distance √2 entre deux indices distincts | Toute suite convergente a des termes tardifs proches entre eux ; ici deux termes distincts restent toujours séparés | La notion de suite de Cauchy n’est pas nécessaire à cette preuve et est hors programme MP',
        'Intégrer une exponentielle complexe | Développer un carré de norme | Réfuter la convergence de toute suite extraite',
        ['Pour M=12, expliquer les 1 diagonaux et les 0 hors diagonale par une intégrale.',
         'Augmenter le numéro du mode : prévoir pourquoi la norme ne change pas malgré des oscillations plus rapides.',
         'Supposer une extraction convergente ; montrer que la proximité de ses termes contredit leur distance √2.'],
        'MPSI : exponentielles complexes et intégrales, calcul accompagné.',
        'MP : norme en moyenne quadratique (p.12), définition séquentielle du compact et rôle de la dimension finie (p.13).',
        'Prolongement accompagné : espaces de Hilbert et théorème général de Riesz ; Cauchy et Banach sont hors programme MP.',
        'Une distance exacte qui interdit toute extraction convergente et réfute la compacité de la boule unité.'),
    'denombrer_rationnels': guide(
        'Peut-on mettre tous les rationnels dans une liste où chacun a un numéro ? Ranger les fractions réduites par |p|+q permet de voir comment procéder sans doublon. Ne pas confondre cette liste avec la densité : être dense signifie rencontrer chaque intervalle ouvert, pas posséder autant de points que ℝ.',
        'p est entier, q≥1 et p/q est gardé si pgcd(|p|,q)=1 | H est la plus grande hauteur |p|+q dessinée | La cible x permet de chercher une fraction proche parmi les valeurs visibles',
        'Un ensemble dénombrable est en bijection avec ℕ ; au plus dénombrable signifie fini ou dénombrable | Chaque rationnel réduit apparaît à une hauteur finie | ℕᵖ,ℤ,ℚ dénombrables et ℝ non dénombrable sont au programme MP, mais leurs démonstrations ne sont pas exigibles',
        'Réduire une fraction | Ranger par groupes finis | Séparer dénombrabilité et densité',
        ['Prendre H=6 : retrouver 0,1,−1,1/2 et vérifier qu’une fraction comme 2/4 n’ajoute pas un nouveau rationnel.',
         'Pour une fraction réduite p/q choisie, calculer H=|p|+q et justifier sa présence dès ce rang.',
         'Prouver séparément la densité par les décimaux ⌊10ⁿx⌋/10ⁿ, sans conclure que ℝ serait dénombrable.'],
        'MPSI : rationnels, décimaux et densité dans ℝ (p.12–13).',
        'MP : dénombrable et au plus dénombrable, exemples ℕᵖ,ℤ,ℚ (p.22) ; démonstrations non exigibles.',
        'Prolongement accompagné : écrire une énumération complète et prouver son caractère bijectif.',
        'Une liste sans fractions répétées et deux explications distinctes de dénombrabilité et de densité.'),
    'diagonale_cantor': guide(
        'Changer un chiffre de chaque ligne d’un tableau de suites binaires pour fabriquer une suite absente de la liste. Le dessin fait voir les différences ; le raisonnement se poursuit pour tous les rangs. C’est une explication accompagnée de la non-dénombrabilité de ℝ, dont la démonstration n’est pas exigible en MP.',
        'N est le nombre de lignes et de colonnes montrées ; la graine reproduit le tableau | La nouvelle suite a pour chiffre dᵢ=1−sᵢ(i) au rang i | Un bit 0 ou 1 devient un chiffre ternaire 0 ou 2 pour représenter un réel',
        'Le théorème suppose une liste de suites infinies ; le tableau visible n’en montre que les premiers chiffres | Au rang i, la nouvelle suite diffère de la ligne i | Les chiffres ternaires 0 et 2 donnent une représentation injective : deux suites distinctes donnent deux réels distincts',
        'Changer le chiffre diagonal | Raisonner par contradiction à un rang quelconque | Majorer la somme des chiffres suivants',
        ['Prendre N=6 : sur chaque ligne, repérer le chiffre où elle diffère de la nouvelle suite.',
         'Écrire dᵢ=1−sᵢ(i) pour tout i∈ℕ ; expliquer la contradiction si la nouvelle suite était la ligne k.',
         'Pour deux écritures ternaires, examiner le premier chiffre différent et borner le reste par une somme géométrique.'],
        'MPSI : suites, sommes géométriques et raisonnement par contradiction ; activité accompagnée.',
        'MP : savoir que ℝ n’est pas dénombrable (p.22) ; preuve de Cantor non exigible.',
        'Prolongement accompagné : preuve diagonale et comparaison d’un ensemble avec l’ensemble de ses parties.',
        'Une preuve expliquée rang par rang, clairement distincte d’un tableau fini.'),
    'ensemble_cantor': guide(
        'Retirer les tiers centraux de [0,1] et compter les intervalles qui restent. La longueur totale diminue, mais l’intersection de toutes les étapes contient encore une infinité non dénombrable de points. Utiliser cet exemple accompagné pour distinguer longueur, nombre de points et compacité.',
        'k est le nombre d’étapes ; il reste 2ᵏ intervalles de longueur 3⁻ᵏ | Le numéro choisi est ramené entre 0 et 2ᵏ−1 par un reste de division ; ses chiffres binaires 0,1 deviennent les chiffres ternaires 0,2 | C est l’intersection de toutes les étapes, pas seulement l’étape k dessinée',
        'Chaque étape est fermée et contenue dans [0,1] ; leur intersection est donc un fermé borné compact de ℝ | Les étapes contiennent encore des segments ; le compact limite ne contient aucun intervalle de longueur positive | L’ensemble de Cantor et sa non-dénombrabilité sont des prolongements, pas des objets exigibles en MP',
        'Compter avec 2ᵏ et 3ᵏ | Utiliser une intersection de fermés | Séparer longueur totale et cardinal',
        ['Prendre k=3 : compter huit intervalles, de longueur 1/27 chacun, et calculer la longueur totale 8/27.',
         'Lire le numéro d’un intervalle en base 2 puis ses chiffres 0 ou 2 en base 3 ; retrouver son extrémité gauche.',
         'Justifier la compacité par fermé et borné ; en complément, expliquer pourquoi aucun intervalle non trivial ne reste à toutes les étapes.'],
        'MPSI : suites géométriques et ensembles de nombres ; construction accompagnée.',
        'MP : intersections de fermés (p.12) et critère fermé borné (p.13), appliqués à un exemple supplémentaire.',
        'Prolongement accompagné : Cantor parfait, c’est-à-dire fermé sans point isolé, et totalement discontinu, sans connexe non trivial.',
        'Un calcul d’étape et une preuve de compacité de l’intersection, avec longueur et cardinal distingués.'),
    'rationnels_irrationnels': guide(
        'Approcher le même réel par des rationnels puis par des irrationnels. Dans tout intervalle, aussi petit soit-il, il y a donc des nombres de chaque sorte. Calculer deux suites explicites pour comprendre la densité et voir pourquoi deux ensembles denses peuvent ne partager aucun point.',
        'x est le réel choisi ; N donne le nombre de décimales examinées | qₙ=⌊10ⁿx⌋/10ⁿ est rationnel | rₙ=qₙ+√2/10ⁿ est irrationnel ; les deux suites tendent vers x',
        'Le plancher est le plus grand entier ≤ au nombre : il s’applique aussi aux négatifs | L’erreur rationnelle vérifie 0≤x−qₙ<10⁻ⁿ | Ajouter le multiple rationnel non nul de √2 donne un irrationnel, même si x est rationnel',
        'Encadrer par deux décimaux successifs | Prouver une limite par majoration | Utiliser la caractérisation séquentielle de la densité',
        ['Prendre x=0,731 : calculer q₁,q₂,q₃ et vérifier le côté par défaut de l’approximation.',
         'Prendre x=−1,414 : comparer plancher et troncature vers zéro pour retrouver les bonnes inégalités.',
         'Majorer les deux erreurs puis déterminer intérieur, adhérence et frontière de ℚ et de son complémentaire dans ℝ.'],
        'MPSI : approximations décimales et densité des rationnels et irrationnels (p.12–13).',
        'MP : densité, adhérence séquentielle et fonctions continues égales sur un dense (p.12).',
        'Prolongement accompagné : la fonction qui vaut 1 sur ℚ et 0 ailleurs est discontinue partout.',
        'Deux suites approchant le même réel et une preuve de densité indépendante du nombre de points des ensembles.'),
    'sinus_topologue': guide(
        'Observer la courbe y=sin(1/x) lorsque x approche zéro, puis chercher quelles ordonnées elle peut approcher sur la verticale. La construction montre une limite d’ensemble difficile à relier par un chemin. Elle approfondit la connexité par arcs du programme MP ; la connexité générale sans chemins reste un complément explicitement accompagné.',
        'G est le graphe pour 0<x≤1 ; V est le segment {0}×[−1,1] ; S=G∪V | Le nombre d’oscillations change seulement la partie dessinée de G | La hauteur y₀ choisit un point (0,y₀) et une suite du graphe qui l’approche',
        'Le graphe complet a une infinité d’oscillations près de zéro ; la figure n’en montre qu’un nombre fini | S est l’adhérence de G, donc fermé borné et compact dans ℝ² | Montrer « connexe mais pas connexe par arcs » nécessite la connexité générale, non exigible en MP',
        'Choisir des phases de même sinus | Construire une suite vers un point adhérent | Utiliser le TVI pour examiner un chemin supposé',
        ['Choisir y₀=0 : prendre xₙ=1/(2πn), n≥1, et vérifier que les points (xₙ,0) approchent (0,0).',
         'Choisir y₀=0,4 : trouver θ avec sinθ=0,4, puis utiliser 1/(θ+2πn).',
         'En complément, supposer un chemin quittant la verticale : montrer pourquoi des ordonnées 1 et −1 seraient imposées près du même instant.'],
        'MPSI : suites trigonométriques et caractérisation séquentielle d’une limite (p.12–14).',
        'MP : adhérence et fermé (p.12), compact et chemins continus (p.13) ; exemple accompagné.',
        'Prolongement accompagné : sinus du topologue et connexité générale, hors des attendus MP sur les arcs.',
        'Des suites vers tous les points du segment limite et une exploration guidée de l’obstacle à un chemin.'),
    'gl_composantes': guide(
        'Faire varier une matrice réelle inversible et suivre son déterminant. Pour passer d’un signe positif à un signe négatif, un chemin continu doit rencontrer zéro : la matrice devient alors singulière. Comparer avec un chemin complexe qui contourne zéro, puis distinguer déterminant positif et déterminant égal à 1.',
        'A=Q diag(λ,1,2,3)R est une matrice dense 4×4 ; Q,R sont fixes, orthogonales et de déterminant 1 | Sur ℝ, λ=t et det A=6t | Sur ℂ, λ=e^(iθ) et det A=6e^(iθ)',
        't=0 produit une matrice singulière | GL₄⁺(ℝ) désigne det>0 ; SL₄(ℝ) désigne det=1 | La continuité du déterminant et le TVI expliquent l’obstacle réel ; l’étude globale des groupes est un prolongement',
        'Calculer un déterminant | Appliquer le TVI à une fonction réelle continue | Reconnaître une image réciproque d’ouvert',
        ['Choisir t=1 : calculer det A=6 et décider l’appartenance à GL₄⁺ et à SL₄.',
         'Faire passer t de 1 à −1 : localiser la valeur où la matrice cesse d’être inversible.',
         'Choisir le corps complexe et passer de θ=0° à 180° : vérifier que le module du déterminant reste 6.'],
        'MPSI : déterminants et TVI (p.14) ; calcul matriciel en dimension 4.',
        'MP : applications polynomiales continues (p.14), ouverts et composantes par arcs (p.12–13).',
        'Prolongement accompagné : topologie globale des groupes GL et SL, décomposition polaire et groupes de Lie.',
        'Un obstacle réel prouvé par le signe, un détour complexe explicite et trois conditions de déterminant bien distinguées.'),
    'orthogonal_compact': guide(
        'Comparer des matrices qui conservent toutes les longueurs avec des matrices qui conservent seulement le volume. Les premières restent bornées ; les secondes peuvent étirer une direction et comprimer une autre sans changer le déterminant. Prouver séparément la fermeture et la bornitude pour appliquer le critère de compacité de MP.',
        'O₄={A:AᵀA=I} ; l’angle règle deux rotations planes et l’orientation choisit det±1 | La norme de Frobenius est √Σaᵢⱼ² ; elle vaut 2 pour les matrices orthogonales 4×4 | T règle Q diag(eᵀ,e⁻ᵀ,1,1)R, de déterminant 1',
        'Q,R sont fixes, orthogonales et de déterminant 1 | Une équation continue telle que AᵀA=I ou det A=1 définit un fermé | Le déterminant 1 seul ne donne aucune borne sur les coefficients',
        'Utiliser AᵀA=I | Calculer une norme à partir des colonnes | Prouver fermé et borné, ou montrer une suite non bornée',
        ['Faire varier l’angle et l’orientation : vérifier les colonnes unitaires, la norme de Frobenius égale à 2 et le déterminant ±1.',
         'Augmenter T dans la seconde famille : calculer eᵀ et e⁻ᵀ et vérifier leur produit égal à 1.',
         'Rédiger pourquoi O₄ est fermé borné, alors que la famille de déterminant 1 manque de bornitude.'],
        'MPSI : produit scalaire, bases orthonormées et longueur des colonnes (p.33).',
        'MP : isométries, norme associée au produit scalaire (p.10–11) et compacité de dimension finie (p.13).',
        'Prolongement accompagné : comparer groupes orthogonal et spécial linéaire, puis leurs composantes et groupes de Lie.',
        'Deux preuves de fermeture, une borne pour les orthogonales et une famille qui réfute la compacité de SL₄.'),
    'point_fixe': guide(
        'Résoudre x=cos x en répétant xₙ₊₁=cos xₙ, puis comparer avec xₙ₊₁=qxₙ+0,7. Chercher d’abord une solution constante, étudier le domaine et calculer comment l’erreur évolue. Ces étapes relèvent des suites récurrentes de MPSI ; le théorème général de point fixe dans un espace complet est un complément, non un attendu MP.',
        'Pour cos, x₀∈[0,1] et l’intervalle reste stable : cos([0,1])⊂[0,1] | Pour l’affine, q est le coefficient et |q| règle le rapport des erreurs | N est le nombre d’itérations ; un point fixe x* vérifie T(x*)=x*',
        'Une limite éventuelle doit satisfaire l’équation du point fixe par continuité | Pour l’affine et q≠1, x*=0,7/(1−q) et xₙ−x*=qⁿ(x₀−x*) | Banach, complétude et contraction sur un espace général sont hors programme MP ; les bornes de ces exemples se lisent avec des suites géométriques',
        'Chercher une solution constante | Vérifier un intervalle stable | Calculer une erreur géométrique et une précision',
        ['Pour cos avec x₀=0,2, vérifier que les itérés restent dans [0,1] et lire leurs alternances autour de la solution.',
         'Choisir l’affine q=0,6 : calculer x*=1,75 puis l’erreur après N étapes.',
         'Avec x₀=0,2, comparer q=−1 et q=1 : expliquer respectivement le cycle 0,2;0,5 et l’absence de solution constante avec le biais 0,7.'],
        'MPSI : suites arithmético-géométriques, récurrences, intervalle stable et précision (p.13).',
        'MP : continuité et passage à la limite (p.12) ; le théorème général de Banach n’est pas exigible.',
        'Prolongement accompagné : contraction, suite de Cauchy et point fixe de Banach, hors programme MP.',
        'Une équation de solution constante, une étude de l’itération et une borne d’erreur dans les cas convergents.'),
    'chemins_niveaux': guide(
        'Le produit des distances à deux foyers dessine deux régions qui se rejoignent lorsque le niveau atteint une valeur précise. Calculer la fonction sur l’axe x=0 pour savoir si un chemin peut passer d’un côté à l’autre. Au niveau critique, retirer ou conserver le point zéro change la possibilité du passage.',
        'F(x,y)=((x−1)²+y²)((x+1)²+y²), avec foyers (−1,0),(1,0) | b>0 fixe la valeur b⁴ ; le domaine utilise F≤b⁴ ou F<b⁴ | Sur x=0, F(0,y)=(1+y²)²≥1',
        'Le sous-niveau F≤b⁴ est fermé borné donc compact | Pour b<1, aucun point du domaine n’a x=0 | Pour b=1, zéro appartient au domaine ≤, mais pas au domaine < ; les chemins doivent respecter ce choix',
        'Calculer une fonction sur une droite | Utiliser une image réciproque de fermé ou d’ouvert | Appliquer le TVI à l’abscisse d’un chemin',
        ['Choisir b=0,8 : comparer b⁴ avec 1 et prouver qu’un chemin ne peut traverser x=0.',
         'Choisir b=1 : calculer F(0,0) et comparer les deux inégalités pour expliquer le passage au point de contact.',
         'Choisir b=1,4 : vérifier sur la formule radiale que chaque point peut se relier à zéro par un segment.'],
        'MPSI : polynômes, inégalités et TVI (p.14) ; lecture guidée des domaines de niveau.',
        'MP : images réciproques d’ouverts/fermés, compacts et composantes connexes par arcs (p.13).',
        'Prolongement accompagné : ovales de Cassini et changement de géométrie des ensembles de niveau.',
        'Un seuil exact et des chemins permis ou interdits justifiés par une formule, même au point de contact.'),
    'homeomorphisme': guide(
        'Une bijection continue permet-elle de revenir continûment aux points de départ ? Sur le cercle, des images proches de (1,0) peuvent correspondre à des angles proches de 0 ou de 2π : l’inverse pose problème. Comparer avec la courbe (t,t²,t³), où retrouver t par la première coordonnée reste continu.',
        'Sur le cercle, f(t)=(cos t,sin t), t∈[0,2π[ | La suite tₙ=2π−1/n donne des images proches de f(0), mais des antécédents loin de zéro | Sur le segment [−1,1], g(t)=(t,t²,t³) et l’inverse sur l’image est (x,y,z)↦x',
        'Un homéomorphisme est une bijection continue dont l’inverse est aussi continu | [0,2π[ n’est pas compact ; [−1,1] l’est | La figure de la courbe représente seulement une projection de ses trois coordonnées',
        'Tester la continuité par une suite | Lire l’inverse sur la première coordonnée | Utiliser images compactes et fermés relatifs',
        ['Avec n=35 puis n=180, comparer la distance des images à f(0) et la distance des angles tₙ à zéro.',
         'Passer à la courbe : retrouver t dans (t,t²,t³) et vérifier l’injectivité.',
         'En complément, utiliser l’image d’un fermé compact pour expliquer pourquoi une injection continue d’un compact possède un inverse continu sur son image.'],
        'MPSI : continuité séquentielle, bijections et composées (p.14), avec comparaison d’intervalles.',
        'MP : continuité par suites, fermés relatifs (p.12) et images compactes (p.13) ; homéomorphisme comme complément accompagné.',
        'Prolongement accompagné : homéomorphismes, inverse d’une injection compacte et espaces de Hausdorff, non exigibles en MP.',
        'Un inverse dont la continuité échoue à un point et un inverse explicite continu, vérifiés avec des suites et des coordonnées.'),
}

for index, lab_id in enumerate(ORDER):
    LAB_GUIDES[lab_id]['lesson_numbers'] = [2*index+1, 2*index+2]
