'use strict';
const sceneColors=['#8de5c4','#ffba70','#aea4e3','#dcd27e','#ee96b2'];
function abs(x){return Math.abs(x);}
function canvasContext(canvas){const rect=canvas.getBoundingClientRect(),dpr=window.devicePixelRatio||1,w=rect.width||380,h=rect.height||160;if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);}const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);return{ctx,w,h};}
function text(ctx,value,x,y,color='#b7d3d4',size=11,align='left'){ctx.fillStyle=color;ctx.font=`${size}px system-ui`;ctx.textAlign=align;ctx.fillText(value,x,y);}
function line(ctx,x1,y1,x2,y2,color='#355265',width=1){ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke();}
function path(ctx,points,color,width=2){ctx.beginPath();let pen=false;for(const [x,y]of points){if(!Number.isFinite(x)||!Number.isFinite(y)){pen=false;continue;}if(pen)ctx.lineTo(x,y);else ctx.moveTo(x,y);pen=true;}ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke();}
function drawHero(canvas,t){const{ctx,w,h}=canvasContext(canvas);ctx.clearRect(0,0,w,h);const cx=w/2,cy=103,r=Math.min(64,w*.23);text(ctx,'UN MÊME ESPACE, TROIS NORMES',22,24,'#b7d3d4',10);line(ctx,cx-r-18,cy,cx+r+18,cy,'#355265');line(ctx,cx,cy-r-13,cx,cy+r+13,'#355265');const phi=Array.from({length:161},(_,j)=>j/160*2*Math.PI);for(const[k,i]of[[1,0],[2,1],[Infinity,2]]){const pts=phi.map(a=>{const x=Math.cos(a),y=Math.sin(a),n=k===Infinity?Math.max(abs(x),abs(y)):(abs(x)**k+abs(y)**k)**(1/k);return[cx+r*x/n,cy-r*y/n];});path(ctx,pts,sceneColors[i],2);}for(const[i,label]of ['Norme 1','Norme 2','Norme ∞'].entries())text(ctx,label,w*(i+1)/4,cy+r+22,sceneColors[i],11,'center');text(ctx,'UN COMPACT SE CONSTRUIT PAR INTERSECTION',22,209,'#b7d3d4',9);let intervals=[[0,1]];for(let k=0;k<4;k++){const y=224+k*21;for(const[a,b]of intervals){ctx.fillStyle=sceneColors[k%3];ctx.fillRect(28+(w-56)*a,y,(w-56)*(b-a),6);}intervals=intervals.flatMap(([a,b])=>[[a,a+(b-a)/3],[b-(b-a)/3,b]]);}}
function drawGeometry(ctx,w,h,sc,time){let bounds=sc.bounds||[-2,2,-2,2];const[xmin,xmax,ymin,ymax]=bounds,scale=Math.min((w-100)/(xmax-xmin),(h-70)/(ymax-ymin)),ox=(w-scale*(xmax-xmin))/2,oy=(h-scale*(ymax-ymin))/2;const temporal=['subsequences','record_indices','fraction_labels'].some(k=>k in sc),sx=temporal?(w-100)/(xmax-xmin):scale,sy=temporal?(h-70)/(ymax-ymin):scale,dx=temporal?50:ox,dy=temporal?35:oy;const X=x=>dx+(x-xmin)*sx,Y=y=>h-dy-(y-ymin)*sy;
  for(let k=0;k<=4;k++){const x=xmin+(xmax-xmin)*k/4,y=ymin+(ymax-ymin)*k/4;line(ctx,X(x),Y(ymin),X(x),Y(ymax),'#284859');line(ctx,X(xmin),Y(y),X(xmax),Y(y),'#284859');text(ctx,fmt(x),X(x),Y(ymin)+16,'#a9c6cb',9,'center');text(ctx,fmt(y),X(xmin)-7,Y(y)+3,'#a9c6cb',9,'right');}
  if(ymin<=0&&ymax>=0)line(ctx,X(xmin),Y(0),X(xmax),Y(0),'#638a92');if(xmin<=0&&xmax>=0)line(ctx,X(0),Y(ymin),X(0),Y(ymax),'#638a92');
  const labels=[];for(const p of sc.paths||[]){if(!p.points?.length)continue;const color=sceneColors[(p.colorIndex||0)%sceneColors.length];ctx.beginPath();p.points.forEach(([x,y],i)=>i?ctx.lineTo(X(x),Y(y)):ctx.moveTo(X(x),Y(y)));if(p.closed)ctx.closePath();if(p.fill){ctx.fillStyle=color+'30';ctx.fill('evenodd');}ctx.setLineDash(p.dashed||p.boundaryClosed===false?[5,4]:[]);ctx.strokeStyle=color;ctx.lineWidth=2;ctx.stroke();ctx.setLineDash([]);if(p.label&&!labels.some(v=>v.label===p.label))labels.push({label:p.label,color});}
  for(const d of (sc.discs||[]).filter(d=>d.fill)){ctx.beginPath();ctx.arc(X(d.x),Y(d.y),Math.max(.6,d.r*scale),0,2*Math.PI);ctx.fillStyle=sceneColors[(d.colorIndex||0)%5]+'25';ctx.fill();}
  const allPoints=sc.points||[];for(const p of allPoints){const color=sceneColors[(p.colorIndex||0)%5];ctx.beginPath();ctx.arc(X(p.x),Y(p.y),allPoints.length>50?2.3:4.2,0,2*Math.PI);ctx.fillStyle=p.label?.includes('exclu')?'#132c40':color;ctx.fill();ctx.strokeStyle=color;ctx.lineWidth=1.5;ctx.stroke();if(allPoints.length<=8&&p.label)text(ctx,p.label,Math.min(w-10,Math.max(10,X(p.x)+7)),Math.max(12,Y(p.y)-10),color,10,X(p.x)>w*.68?'right':'left');}
  for(const d of sc.discs||[]){const color=sceneColors[(d.colorIndex||0)%5];ctx.beginPath();ctx.arc(X(d.x),Y(d.y),Math.max(2,d.r*scale),0,2*Math.PI);if(d.r<.035&&!d.fill){ctx.fillStyle='#132c40';ctx.fill();}ctx.setLineDash(d.closed===false?[5,4]:[]);ctx.strokeStyle=color;ctx.lineWidth=1.8;ctx.stroke();ctx.setLineDash([]);if(d.label&&!labels.some(v=>v.label===d.label))labels.push({label:d.label,color});}
  text(ctx,sc.x_label||'x',X(xmax)+8,Y(ymin)+2,'#b7d3d4',10);text(ctx,sc.y_label||'y',X(xmin)-8,Y(ymax)-9,'#b7d3d4',10,'right');
  let lx=16;for(const l of labels.slice(0,5)){const width=ctx.measureText(l.label).width;if(lx+width>w-10)break;line(ctx,lx,h-9,lx+12,h-9,l.color,3);text(ctx,l.label,lx+18,h-6,l.color,9);lx+=width+40;}}
function drawMatrices(ctx,w,h,sc){const first=sc.matrix||sc.gram;if(!first?.length)return false;const additional=sc.secondary_matrix||((sc.imaginary||[]).some(row=>row.some(v=>abs(v)>1e-12))?sc.imaginary:null),panels=additional?[first,additional]:[first];panels.forEach((a,k)=>{const n=a.length,m=a[0].length,available=w/panels.length,cell=Math.min((available-45)/m,(h-65)/n),left=available*k+(available-cell*m)/2,top=38;const max=Math.max(1,...a.flat().map(Math.abs));text(ctx,k===0?(sc.matrix_label||'Matrice calculée'):(sc.secondary_matrix?'Matrice de SL₄':'Partie imaginaire'),left,19,'#cfe5dd',11);for(let i=0;i<n;i++)for(let j=0;j<m;j++){const v=a[i][j],q=Math.min(1,abs(v)/max);ctx.fillStyle=v>=0?`rgba(141,229,196,${.12+.74*q})`:`rgba(255,186,112,${.12+.74*q})`;ctx.fillRect(left+j*cell,top+i*cell,cell-2,cell-2);if(cell>=20)text(ctx,Math.abs(v)<1e-12?'0':Number(v.toPrecision(3)).toLocaleString('fr-FR'),left+(j+.5)*cell,top+(i+.5)*cell+4,'#e8f4eb',Math.min(12,cell*.25),'center');}for(let i=0;i<n;i++)if(n<=12)text(ctx,sc.labels?.[i]||String(i+1),left-7,top+(i+.5)*cell+3,'#b7d3d4',9,'right');});return true;}
function drawDiagonal(ctx,w,h,sc){const n=sc.matrix.length,cell=Math.min((w-85)/n,(h-85)/(n+1)),left=(w-cell*n)/2,top=23;for(let i=0;i<n;i++)for(let j=0;j<n;j++){ctx.fillStyle=sc.matrix[i][j]?'#456f78':'#223f53';ctx.fillRect(left+j*cell,top+i*cell,cell-2,cell-2);if(i===j){ctx.strokeStyle='#ffba70';ctx.lineWidth=2;ctx.strokeRect(left+j*cell+1,top+i*cell+1,cell-4,cell-4);}text(ctx,String(sc.matrix[i][j]),left+(j+.5)*cell,top+(i+.5)*cell+3,'#d4eae1',Math.min(12,cell*.5),'center');}for(let j=0;j<n;j++){ctx.fillStyle='#247c65';ctx.fillRect(left+j*cell,top+(n+.35)*cell,cell-2,cell-2);text(ctx,String(sc.anti[j]),left+(j+.5)*cell,top+(n+.85)*cell+3,'#fff',Math.min(12,cell*.5),'center');}text(ctx,'aᵢ = 1 − bᵢᵢ : une différence dans chaque ligne',w/2,h-12,'#ffba70',11,'center');}
function drawCantor(ctx,w,h,sc){const left=55,right=w-25,top=24,levels=sc.levels,step=Math.min(36,(h-62)/levels.length);levels.forEach((intervals,k)=>{text(ctx,`K${k}`,left-14,top+k*step+7,'#b7d3d4',10,'right');for(const[a,b]of intervals){ctx.fillStyle=sceneColors[k%3];ctx.fillRect(left+a*(right-left),top+k*step,Math.max(.45,(b-a)*(right-left)),8);}if(k===levels.length-1){const[a,b]=sc.address_interval;ctx.strokeStyle='#fff';ctx.strokeRect(left+a*(right-left)-2,top+k*step-3,Math.max(4,(b-a)*(right-left)+4),14);}});text(ctx,'0',left,h-17,'#b7d3d4',10);text(ctx,'1',right,h-17,'#b7d3d4',10,'right');text(ctx,'K = intersection de toutes les étapes',w/2,h-17,'#d2e6dd',11,'center');}
function drawScene(canvas,r,time,paused){const{ctx,w,h}=canvasContext(canvas);ctx.clearRect(0,0,w,h);const sc=r.scene;if(sc.kind==='diagonal'){drawDiagonal(ctx,w,h,sc);return;}if(sc.kind==='cantor'){drawCantor(ctx,w,h,sc);return;}if(sc.kind==='matrix'&&drawMatrices(ctx,w,h,sc))return;if((sc.paths?.length||sc.points?.length||sc.discs?.length)&&sc.bounds){drawGeometry(ctx,w,h,sc,time);return;}if(r.charts?.length)plotCanvas(ctx,w,h,r.charts[0],time,paused);}
function plotCanvas(ctx,w,h,chart,time,paused){const series=chart.series||[],points=series.flatMap(s=>s.x.map((x,i)=>[x,s.y[i]])).filter(p=>p.every(Number.isFinite)&&(chart.x_scale!=='log'||p[0]>0)&&(chart.y_scale!=='log'||p[1]>0));if(!points.length)return;const tx=x=>chart.x_scale==='log'?Math.log10(x):x,ty=y=>chart.y_scale==='log'?Math.log10(y):y;const xs=points.map(p=>tx(p[0])),ys=points.map(p=>ty(p[1]));if(series.some(s=>s.style==='stems'))ys.push(0);let xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys);if(xmax===xmin)xmax++;if(ymax===ymin){ymax++;ymin--;}const border=(ymax-ymin)*.08;ymax+=border;ymin-=border;const X=x=>60+(tx(x)-xmin)/(xmax-xmin)*(w-83),Y=y=>h-47-(ty(y)-ymin)/(ymax-ymin)*(h-74);for(let i=0;i<5;i++){const xx=60+(w-83)*i/4,yy=h-47-(h-74)*i/4;line(ctx,xx,27,xx,h-47,'#284859');line(ctx,60,yy,w-23,yy,'#284859');const vx=xmin+(xmax-xmin)*i/4,vy=ymin+(ymax-ymin)*i/4;text(ctx,fmt(chart.x_scale==='log'?10**vx:vx),xx,h-27,'#a9c6cb',10,'center');text(ctx,fmt(chart.y_scale==='log'?10**vy:vy),52,yy+3,'#a9c6cb',10,'right');}for(let i=0;i<series.length;i++){const s=series[i],p=s.x.map((x,j)=>[X(x),Y(s.y[j])]),color=sceneColors[(chart.same_color?0:i)%sceneColors.length];if(s.style==='dots'){for(const[x,y]of p){ctx.beginPath();ctx.arc(x,y,3,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();}}else if(s.style==='stems'){for(const[x,y]of p)line(ctx,x,Y(0),x,y,color,3);}else path(ctx,p,color,2.1);}text(ctx,chart.x_label,w/2,h-6,'#c0d8d5',11,'center');text(ctx,chart.y_label,61,16,'#c0d8d5',10);{const u=(time*.09)%1,xx=60+u*(w-83);line(ctx,xx,27,xx,h-47,'#ffffff55',1);const primary=series.find(s=>s.style!=='dots');if(primary?.x.length){const x=chart.x_scale==='log'?10**(xmin+(xmax-xmin)*u):xmin+(xmax-xmin)*u;let best=0;for(let j=1;j<primary.x.length;j++)if(abs(primary.x[j]-x)<abs(primary.x[best]-x))best=j;const y=primary.y[best];ctx.beginPath();ctx.arc(X(primary.x[best]),Y(y),4,0,Math.PI*2);ctx.fillStyle=sceneColors[0];ctx.fill();text(ctx,`(${fmt(primary.x[best])} ; ${fmt(y)})`,w-23,16,'#d1ede4',11,'right');}}}
