"""Cours et corrections originaux adaptés de la fiche M12 fournie par A. R."""

LESSONS = [
    dict(title="01 · Modéliser avant de calculer", level="Fondations · maths sup", lab="urne", html="""
<p>Une probabilité dépend d’un modèle : univers, événements et règle de tirage. L’équiprobabilité doit être justifiée. Pour une urne contenant R rouges et B bleues, un échantillon de d boules sans remise est une partie uniforme de taille d, et non une suite de d essais indépendants.</p>
<div class="formula">P(X=k) = C(R,k) C(B,d−k) / C(R+B,d)</div>
<p>La convention C(a,b)=0 hors de 0≤b≤a donne immédiatement le support. La normalisation découle de Vandermonde : on classe les parties selon leur nombre de rouges. Avec remise, les indicatrices sont indépendantes et X suit B(d,R/(R+B)).</p>
<p><b>Réflexe de concours :</b> annoncer la variable et son support ; expliquer le numérateur et le dénominateur avant d’écrire une formule.</p>"""),
    dict(title="02 · Indicatrices et dépendance", level="Fondations · maths sup", lab="urne", html="""
<p>Écrivons X=I₁+⋯+I_d, où I_j vaut 1 si le j-ième tirage est rouge. La linéarité de l’espérance ne demande aucune indépendance. Avec N=R+B et p=R/N, E(X)=dp.</p>
<div class="formula">Cov(I_i,I_j)=−p(1−p)/(N−1), i≠j<br>V(X)=dp(1−p)(N−d)/(N−1)</div>
<p>En effet, E(I_i I_j)=R(R−1)/(N(N−1)), puis V(ΣI_j)=ΣV(I_j)+2Σ_{i&lt;j}Cov(I_i,I_j). Quand on tire toute l’urne, la variance est nulle. Quand d est petit devant N, la correction est proche de 1.</p>
<p>L’indépendance implique une covariance nulle lorsque les moments existent. La réciproque est fausse : pour Z uniforme sur {−1,0,1}, Cov(Z,Z²)=0 alors que Z et Z² sont dépendantes.</p>"""),
    dict(title="03 · Sommes et fonctions génératrices", level="Maths sup → maths spé", lab="fluctuations", html="""
<p>Pour X à valeurs dans ℕ, G_X(t)=E(t^X). Sur une loi finie, les dérivations se font terme à terme ; sur une loi infinie, les justifications de convergence sont nécessaires. Pour X,Y indépendantes, G_{X+Y}=G_X G_Y.</p>
<div class="formula">G_{B(n,p)}(t)=(1−p+pt)ⁿ<br>E(X)=G′_X(1), V(X)=G″_X(1)+G′_X(1)−G′_X(1)²</div>
<p>La multiplication prouve B(n,p)+B(m,p)=B(n+m,p) pour des variables indépendantes de même paramètre p. Si leurs paramètres diffèrent, la somme n’est généralement pas binomiale. La convolution donne aussi la démonstration coefficient par coefficient.</p>
<p>La loi géométrique utilisée ici est sur {1,2,…} : G(t)=pt/(1−(1−p)t), E(X)=1/p et V(X)=(1−p)/p². Ne pas confondre avec le nombre d’échecs avant le premier succès.</p>"""),
    dict(title="04 · Marche aléatoire et loi binomiale", level="TP du recueil · maths sup", lab="fluctuations", html="""
<p>À chaque étape, un déplacement vaut +1 avec probabilité p et −1 sinon, indépendamment des précédents. Si K compte les +1 parmi n étapes, K suit B(n,p) et Sₙ=2K−n.</p>
<div class="formula">E(Sₙ)=n(2p−1), V(Sₙ)=4np(1−p)<br>P(Sₙ=s)=C(n,(s+n)/2)p^((s+n)/2)(1−p)^((n−s)/2)</div>
<p>La dernière formule vaut si |s|≤n et s a la parité de n ; sinon la probabilité est nulle. Dans le TP, n=20 et p=1/2 : X=10+S₂₀/2=K. Le retour en zéro a probabilité C(20,10)/2²⁰≈0,176197.</p>
<p><b>Attention à la lecture du TP :</b> S₂₀=4 correspond à K=12, et S₂₀=−4 à K=8. Les valeurs K=6 ou 14 correspondent à un déplacement de −8 ou +8.</p>"""),
    dict(title="05 · Fluctuations et grands nombres", level="Maths sup / spé · selon filière", lab="fluctuations", html="""
<p>Pour Y≥0 et a&gt;0, Y≥a·1_{Y≥a} implique P(Y≥a)≤E(Y)/a : c’est Markov. On l’applique à Y=(X−E(X))² pour obtenir Bienaymé–Tchebychev.</p>
<div class="formula">P(|X−E(X)|≥ε)≤V(X)/ε²<br>P(|K/n−p|≥ε)≤p(1−p)/(nε²)</div>
<p>Le carré centré est positif ; X−E(X) lui-même ne l’est pas nécessairement. Pour une moyenne de variables indépendantes de même espérance m et variance σ², la variance est σ²/n. La borne tend vers 0 : convergence en probabilité, ou loi faible des grands nombres.</p>
<p>La trajectoire d’une fréquence peut remonter et s’éloigner provisoirement de p. Une garantie à chaque instant fixé n’est pas une garantie simultanée sur tous les instants. Une simulation donne une observation, la borne donne une preuve.</p>"""),
    dict(title="06 · Approximer et mesurer l’incertitude", level="Approfondissement · maths spé / ITC", lab="fluctuations", html="""
<p>Pour 0&lt;p&lt;1 fixé, la variable (K−np)/√(np(1−p)) converge en loi vers N(0,1). Le laboratoire compare les masses binomiales à l’approximation Φ((k+1/2−np)/σ)−Φ((k−1/2−np)/σ) : correction de continuité.</p>
<p>Cette approximation n’est pas exacte, particulièrement dans les queues ou si np ou n(1−p) est petit. La somme binomiale reste le résultat de référence. Les bords p=0 ou 1 sont déterministes et ne doivent pas être standardisés par une variance nulle.</p>
<p>Un intervalle de Wilson au niveau nominal 95 % est fourni pour la fréquence finale. Son taux de couverture est une propriété de répétitions d’échantillonnage, pas une probabilité que le paramètre fixé change de valeur. C’est une extension statistique, de couverture approximative, sans prétention de bande simultanée.</p>"""),
    dict(title="07 · Exercice 6 : la moyenne conservée", level="Priorité · maths spé", lab="polarisation", html="""
<p>On part de X₀=c∈(0,1). Conditionnellement à Xₙ=x, Bₙ₊₁ suit Bernoulli(x), et Xₙ₊₁=(1−λ)Xₙ+λBₙ₊₁, avec 0&lt;λ&lt;1. Par récurrence, 0≤Xₙ≤1.</p>
<div class="formula">E(Xₙ₊₁ | Xₙ=x)=x<br>E(Xₙ₊₁² | Xₙ=x)=(1−λ²)x²+λ²x</div>
<p>En prenant les espérances, E(Xₙ)=c et m₂(n+1)=(1−λ²)m₂(n)+λ²c. Comme m₂(0)=c², la résolution de cette récurrence affine donne :</p>
<div class="formula">E(Xₙ²)=c−c(1−c)(1−λ²)ⁿ<br>V(Xₙ)=c(1−c)[1−(1−λ²)ⁿ]</div>
<p>La variance augmente alors que la moyenne reste fixe : la population se sépare vers 0 et 1. Les variables Bₙ ne sont pas une suite de Bernoulli(c) indépendantes. Le langage des martingales décrit cette moyenne conditionnelle conservée, mais la démonstration ci-dessus n’exige aucun théorème de martingales.</p>"""),
    dict(title="08 · Exercice 6 : prouver la polarisation", level="Priorité · preuve complète", lab="polarisation", html="""
<p>La quantité décisive est Dₙ=E[Xₙ(1−Xₙ)]=c(1−c)(1−λ²)ⁿ. Elle tend vers 0. Pour 0&lt;ε&lt;1/2, x(1−x)≥ε(1−ε) sur [ε,1−ε], donc :</p>
<div class="formula">P(ε≤Xₙ≤1−ε)≤Dₙ/[ε(1−ε)] → 0</div>
<p>Pour tout entier k≥2 et x∈[0,1], 0≤x−xᵏ=x(1−x)(1+x+⋯+x^{k−2})≤(k−1)x(1−x). Par espérance, 0≤c−E(Xₙᵏ)≤(k−1)Dₙ. Tous les moments d’ordre positif tendent donc vers c, avec une vitesse explicite.</p>
<p>Pour prouver la convergence en loi sans invoquer seulement les moments, prenons f continue sur [0,1] et sa corde L(x)=(1−x)f(0)+xf(1). La différence f−L s’annule aux extrémités. Elle est arbitrairement petite près de 0 et 1 par continuité uniforme, et bornée sur l’intervalle central, dont la probabilité tend vers 0. Ainsi :</p>
<div class="formula">E[f(Xₙ)] → (1−c)f(0)+cf(1)</div>
<p>C’est la convergence en loi vers Bernoulli(c). Cela ne signifie pas Xₙ→c en probabilité. La convergence presque sûre peut être obtenue avec le théorème de convergence des martingales bornées, proposé seulement en prolongement hors socle.</p>"""),
    dict(title="09 · Exercice 7 : maximum et minimum", level="Priorité · maths sup / spé", lab="extremes", html="""
<p>Soient U₁,…,Uₙ indépendantes uniformes sur [0,θ], avec θ&gt;0. Le bon événement est {Mₙ≤x}=⋂{U_j≤x}. Pour 0≤x≤θ, l’indépendance donne F_M(x)=(x/θ)ⁿ.</p>
<div class="formula">f_M(x)=n x^{n−1}/θⁿ sur (0,θ)<br>E(Mₙ)=θn/(n+1), V(Mₙ)=θ²n/[(n+1)²(n+2)]</div>
<p>Pour le minimum, utiliser l’événement complémentaire : P(mₙ&gt;x)=(1−x/θ)ⁿ. On obtient E(mₙ)=θ/(n+1) et la même variance. Pour 0&lt;ε&lt;1, P(Mₙ/θ≤1−ε)=(1−ε)ⁿ→0 : Mₙ→θ en probabilité.</p>
<p>Sur une même suite infinie de variables uniformes, les maxima sont croissants et bornés ; leur limite est θ presque sûrement. Les simulations de maxima pour différentes tailles ne partagent pas automatiquement ce même couplage.</p>"""),
    dict(title="10 · Exercice 7 : vitesse et estimation", level="Priorité · approfondissement", lab="extremes", html="""
<p>La concentration du maximum ne raconte pas toute l’histoire. Pour Zₙ=n(1−Mₙ/θ) et 0≤z≤n, P(Zₙ&gt;z)=(1−z/n)ⁿ. Pour z≥0 fixé, cette quantité tend vers e^{−z} : Zₙ converge en loi vers Exp(1).</p>
<div class="formula">n(1−Mₙ/θ) ⇒ Exp(1)<br>θ̂=(n+1)Mₙ/n est sans biais pour θ</div>
<p>Le maximum sous-estime θ en moyenne de θ/(n+1). Pour un niveau 1−α fixé, [Mₙ, Mₙ/α^{1/n}] couvre θ avec probabilité exacte 1−α, car P(Mₙ≥θα^{1/n})=1−α. L’intervalle utilise le modèle uniforme, pas un principe universel d’estimation.</p>
<p>La k-ième valeur ordonnée U_(k)/θ suit Beta(k,n+1−k). Sa répartition vaut P(B(n,x/θ)≥k), sa moyenne k/(n+1), sa variance k(n+1−k)/[(n+1)²(n+2)]. Le laboratoire permet de comparer minimum, maximum, rang intérieur et écart renormalisé.</p>"""),
    dict(title="11 · Exercice 8 : arcsinus et matrice chemin", level="Priorité · transversal maths spé", lab="arcsinus", html="""
<p>La variable Uₙ est uniforme discrète sur {1,…,n}, et Xₙ=2cos(πUₙ/(n+1)). Pour f continue, E[f(Xₙ)]=(1/n)Σ_{k=1}^n f(2cos(kπ/(n+1))) converge par sommes de Riemann vers ∫₀¹f(2cos(πt))dt.</p>
<div class="formula">ρ_arc(x)=1/[π√(4−x²)], −2&lt;x&lt;2<br>F_arc(y)=1/2+arcsin(y/2)/π, −2≤y≤2</div>
<p>Le changement de variable x=2cos(πt) explique le poids : la transformation ralentit aux extrémités, qui reçoivent davantage de masse. La densité est intégrable mais non bornée aux bords. La répartition vaut 0 avant −2 et 1 après 2.</p>
<p>La matrice Tₙ a des 1 immédiatement au-dessus et au-dessous de la diagonale, et des 0 ailleurs. Pour θ_k=kπ/(n+1), poser v_j=sin(jθ_k), avec v₀=v_{n+1}=0. L’identité sin((j−1)θ)+sin((j+1)θ)=2cos(θ)sin(jθ) donne Tₙv=2cos(θ_k)v. Ces n valeurs propres sont distinctes et constituent tout le spectre.</p>
<p>Les moments limites impairs sont nuls et les moments pairs d’ordre 2r valent C(2r,r). Pour r=1, le second moment vaut 2. On peut aussi l’approcher par Tr(Tₙ²)/n=2(n−1)/n.</p>"""),
    dict(title="12 · Exercice 8 : Wigner et Catalan", level="Transversal · théorème admis", lab="wigner", html="""
<p>Le modèle de ce laboratoire est Aₙ=Wₙ/√n, avec entrées du triangle supérieur indépendantes, identiquement distribuées selon une loi fixe centrée de variance 1, et symétrie W_ji=W_ij. Les trois lois proposées, normale, signes ±1 et uniforme sur [−√3,√3], ont tous leurs moments finis.</p>
<div class="formula">ρ_sc(x)=√(4−x²)/(2π), −2&lt;x&lt;2<br>μₙ=(1/n)Σ_{j=1}^n δ_{λ_j(Aₙ)} ⇒ μ_sc</div>
<p>Les valeurs propres sont comptées avec leur multiplicité. La convergence faible en probabilité vers la loi du demi-cercle est le théorème de Wigner, admis ici. Le second moment limite vaut 1, les moments impairs 0 et les moments pairs d’ordre 2r sont les nombres de Catalan C(2r,r)/(r+1).</p>
<p>Le pont avec l’algèbre est (1/n)Σλ_j^r=Tr(Aₙʳ)/n. Les termes de trace se lisent comme des marches fermées ; le centrage annule les produits comportant une entrée indépendante présente une seule fois. Les contributions dominantes des marches appariées expliquent les nombres de Catalan. Une preuve générale nécessite aussi de contrôler les fluctuations.</p>
<p><b>Lecture critique de l’extrait :</b> la loi arcsinus concerne Tₙ, tandis que la loi du demi-cercle concerne Wₙ/√n. Converger en moyenne pour les traces ne suffit pas à conclure en probabilité : une variance tendant vers zéro, ou un autre argument de concentration, doit être établi. L’indépendance et des moments finis sans contrôle uniforme d’une famille dépendant de n ne suffisent pas à toutes les versions du théorème.</p>
<p>Pour voir le premier piège, prendre Aₙ=Z·Iₙ où Z suit la loi du demi-cercle. Tous les moments spectraux moyens sont ceux du demi-cercle, mais μₙ=δ_Z reste aléatoire. Ce contre-exemple ne respecte pas les hypothèses de Wigner ; il montre précisément ce que les seuls moments moyens ne prouvent pas.</p>
<p>Une approximation polynomiale sur un compact exige enfin un contrôle des queues spectrales. On ne peut pas supposer que toutes les valeurs propres appartiennent à [−2,2] pour une dimension finie.</p>"""),
]

EXERCISES = [
    dict(title="01 · Urne équilibrée — ex. 4", lab="urne", level="Sup", params=dict(red=10, blue=10, draws=10), question="Une urne contient n rouges et n bleues. On tire n boules sans remise. Déterminer la loi et l’espérance du nombre de rouges.", answer="Le support est {0,…,n}. P(X=k)=C(n,k)C(n,n−k)/C(2n,n). Le dénominateur compte toutes les parties de taille n. Vandermonde donne la normalisation. En écrivant X comme somme de n indicatrices d’espérance 1/2, E(X)=n/2 sans hypothèse d’indépendance."),
    dict(title="02 · Pourquoi la variance diminue", lab="urne", level="Sup", params=dict(red=10, blue=10, draws=20), question="Calculer la covariance de deux indicatrices rouges. Que devient la variance lorsque toutes les boules sont tirées ?", answer="E(I_i I_j)=R(R−1)/(N(N−1)), donc Cov=−p(1−p)/(N−1). En développant la variance de la somme, V(X)=dp(1−p)(N−d)/(N−1). Pour d=N, X=R presque sûrement et la variance est nulle."),
    dict(title="03 · Covariance nulle ≠ indépendance", lab="urne", level="Sup", params={}, question="Z est uniforme sur {−1,0,1}. Les variables Z et Z² sont-elles indépendantes ? Leur covariance est-elle nulle ?", answer="E(Z)=E(Z³)=0, donc Cov(Z,Z²)=0. Pourtant P(Z²=0 | Z=0)=1 tandis que P(Z²=0)=1/3 : elles sont dépendantes. L’expérience sur l’urne illustre un autre cas, avec covariance strictement négative."),
    dict(title="04 · Somme de binomiales — ex. 5", lab="fluctuations", level="Sup / spé", params=dict(n=50, p=.3), question="X~B(n,p) et Y~B(m,p) sont indépendantes. Déterminer la loi de X+Y. Que se passe-t-il si les paramètres diffèrent ?", answer="G_{X+Y}=(1−p+pt)ⁿ(1−p+pt)ᵐ=(1−p+pt)^{n+m}. La somme suit B(n+m,p). Pour deux Bernoulli de paramètres p≠q, la variance p(1−p)+q(1−q) diffère de celle de B(2,(p+q)/2) de −(p−q)²/2 ; la somme n’est pas cette binomiale."),
    dict(title="05 · Une espérance astucieuse — ex. 5", lab="fluctuations", level="Sup", params=dict(n=20,p=.3), question="Si X~B(n,p), calculer E[1/(X+1)] sans additionner numériquement tous les termes.", answer="Utiliser 1/(k+1)=∫₀¹tᵏdt dans la somme finie. E[1/(X+1)]=∫₀¹(1−p+pt)ⁿdt=[1−(1−p)^{n+1}]/[(n+1)p] pour p>0. Pour p=0, X=0 et le résultat vaut 1, également limite de la formule."),
    dict(title="06 · Le retour de la marche — TP", lab="fluctuations", level="Sup", params=dict(n=20,p=.5), question="Une marche symétrique de 20 étapes part de 0. Calculer P(S₂₀=0), puis P(S₂₀=4).", answer="S₂₀=2K−20 avec K~B(20,1/2). Les événements correspondent à K=10 et K=12. Ainsi P(S₂₀=0)=C(20,10)/2²⁰≈0,176197 et P(S₂₀=4)=C(20,12)/2²⁰≈0,120134. Une marche de longueur impaire ne peut pas revenir en 0."),
    dict(title="07 · Dimensionner une simulation", lab="fluctuations", level="Sup / spé", params=dict(n=1000,p=.5,epsilon=.05), question="Combien de Bernoulli indépendantes suffisent, par Tchebychev, pour garantir P(|F_N−p|≥0,05)≤0,05 pour tout p ?", answer="Comme p(1−p)≤1/4, la borne est 1/(4Nε²). Il suffit de N≥1/(4×0,05×0,05²)=2000. C’est une condition suffisante conservatrice, non un minimum exact. Le laboratoire montre la borne et la probabilité binomiale pour n≤1000 ; la démonstration donne le dimensionnement au-delà."),
    dict(title="08 · Deux moments — ex. 6", lab="polarisation", level="Priorité · spé", params=dict(c=.35,lambda_= .25,steps=20), question="Montrer que la moyenne est constante et obtenir une expression fermée du second moment.", answer="En conditionnant par Xₙ=x, E(Xₙ₊₁|x)=x et E(Xₙ₊₁²|x)=(1−λ²)x²+λ²x. Donc m₁=c et m₂−c est multiplié par 1−λ² à chaque étape. Comme m₂(0)=c², m₂(n)=c−c(1−c)(1−λ²)ⁿ."),
    dict(title="09 · Tous les moments — ex. 6", lab="polarisation", level="Priorité · spé", params=dict(c=.35,lambda_= .25,steps=100), question="Donner une preuve quantitative de E(Xₙᵏ)→c pour chaque entier k≥1.", answer="Pour k≥2, 0≤x−xᵏ=x(1−x)Σ_{j=0}^{k−2}xʲ≤(k−1)x(1−x) sur [0,1]. Ainsi 0≤c−E(Xₙᵏ)≤(k−1)c(1−c)(1−λ²)ⁿ→0. Le cas k=1 est déjà exact. Il est inutile de résoudre une récurrence différente pour chaque k."),
    dict(title="10 · Quelle convergence ? — ex. 6", lab="polarisation", level="Priorité · spé", params=dict(c=.5,lambda_= .4,steps=100), question="Xₙ converge-t-elle vers c ? Justifier la loi limite et distinguer les modes de convergence.", answer="La masse de [ε,1−ε] tend vers zéro, tandis que la moyenne reste c. Pour f continue, soustraire la corde (1−x)f(0)+xf(1) et utiliser la continuité aux extrémités : E[f(Xₙ)]→(1−c)f(0)+cf(1). C’est Bernoulli(c), pas la constante c. Par exemple V(Xₙ)→c(1−c)>0 ; comme les variables sont bornées, une convergence en probabilité vers c entraînerait une variance tendant vers zéro."),
    dict(title="11 · Maximum uniforme — ex. 7", lab="extremes", level="Priorité · sup / spé", params=dict(n=20,mode="max"), question="Déterminer la répartition, la densité, l’espérance et la variance de Mₙ sur [0,1].", answer="Pour 0≤x≤1, P(Mₙ≤x)=xⁿ par indépendance. La densité est nx^{n−1}. Intégration : E(Mₙ)=n/(n+1), E(Mₙ²)=n/(n+2), donc V(Mₙ)=n/[(n+1)²(n+2)]. Hors [0,1], la répartition vaut 0 ou 1."),
    dict(title="12 · Vitesse du maximum — ex. 7", lab="extremes", level="Priorité · spé", params=dict(n=80,mode="ecart"), question="Trouver la loi limite de n(1−Mₙ). Que vaut celle de n·mₙ ?", answer="Pour z≥0 fixé et n≥z, P(n(1−Mₙ)>z)=(1−z/n)ⁿ→e^{−z}. On obtient Exp(1). De même P(nmₙ>z)=(1−z/n)ⁿ. Les deux variables ont la même loi marginale, mais ne sont pas indépendantes pour un même échantillon."),
    dict(title="13 · Estimer une borne — ex. 7", lab="extremes", level="Spé · extension", params=dict(n=20,theta=3,mode="max"), question="Sur [0,θ], corriger le biais du maximum et construire un intervalle de niveau exact 95 % pour θ.", answer="E(Mₙ)=θn/(n+1), donc (n+1)Mₙ/n est sans biais. L’intervalle [Mₙ,Mₙ/(0,05)^{1/n}] contient θ si Mₙ≥θ(0,05)^{1/n}. La probabilité de ce dernier événement est 1−0,05=0,95. Le calcul repose sur la loi exacte, pas sur une approximation normale."),
    dict(title="14 · Du cosinus à arcsinus — ex. 8", lab="arcsinus", level="Priorité · spé", params=dict(n=100,power=4), question="Retrouver la loi limite par une somme de Riemann. Calculer ses moments d’ordre 2 et 4.", answer="E[f(Xₙ)]=(1/n)Σf(2cos(kπ/(n+1)))→∫₀¹f(2cos(πt))dt. Le changement de variable donne ρ_arc=1/(π√(4−x²)). Pour les moments pairs, la moyenne de cos^{2r} sur [0,π] vaut C(2r,r)/4ʳ ; la multiplication par 2^{2r} donne C(2r,r). Ainsi m₂=2 et m₄=6."),
    dict(title="15 · Spectre et trace — ex. 8", lab="arcsinus", level="Priorité · spé", params=dict(n=40,mode=3,power=2), question="Construire les vecteurs propres de Tₙ et retrouver le second moment sans diagonaliser.", answer="v_j=sin(jkπ/(n+1)) satisfait v₀=v_{n+1}=0. L’identité d’addition donne λ_k=2cos(kπ/(n+1)). Il y a n valeurs distinctes. Tₙ représente un chemin avec n−1 arêtes ; chaque arête contribue deux fois à Tr(Tₙ²), d’où 2(n−1)/n→2 pour le second moment spectral."),
    dict(title="16 · Arcsinus ou demi-cercle ? — ex. 8", lab="wigner", level="Priorité · transversal", params=dict(n=120,law="signes",matrices=4), question="Comparer les deux seconds moments. Pourquoi la convergence des traces en moyenne ne suffit-elle pas à prouver une convergence en probabilité ?", answer="Pour Tₙ, le second moment tend vers 2 (arcsinus). Pour Aₙ=Wₙ/√n avec variance d’entrée 1, E[Tr(Aₙ²)/n]=1 dans notre modèle, et la limite demi-cercle a m₂=1, m₄=2. Il faut contrôler les fluctuations autour des moyennes. Aₙ=Z Iₙ, avec Z de loi demi-cercle, a les bons moments spectraux moyens mais une mesure δ_Z aléatoire persistante : les seules moyennes ne concluent pas."),
]

# Le nom lambda est réservé en Python ; le protocole JSON emploie « lambda ».
for exercise in EXERCISES:
    if "lambda_" in exercise["params"]:
        exercise["params"]["lambda"] = exercise["params"].pop("lambda_")

SOURCES = [
    "A. R., MemoCPGEScientifAR2027-Proba.pdf, fiche M12 : TP p. 114 ; propriétés p. 118 ; exercices 4 à 8 p. 119 et corrections p. 121–122 (pagination imprimée). Le PDF original reste un document local et n’est pas publié dans ce dépôt.",
    "Les exercices 6 et 7 sont développés avec preuves détaillées ; l’exercice 8 est adapté en séparant arcsinus et demi-cercle, et en explicitant les hypothèses et modes de convergence. La référence X/ENS MP B 2026 est celle indiquée par le recueil.",
    "Référence complémentaire : A. Boutet de Monvel et A. Khorunzhy, Some Elementary Results around the Wigner Semicircle Law, notes diffusées par le MIT : https://web.mit.edu/18.325/www/rmt.pdf . Le théorème général de Wigner est admis dans l’atelier.",
    "Positionnement : fondations de sup, exercices prioritaires de spé, puis extensions annoncées (statistiques d’ordre, intervalles, martingales, matrices aléatoires). Adapter les approfondissements à la filière et au programme suivi. Une simulation n’est jamais utilisée comme démonstration.",
]
