"""Intentions, grandeurs et premiers gestes des 24 expériences d’optique."""


def guide(purpose, objects, assumptions, techniques, first_steps, sup, spe,
          beyond, lessons, expected):
    return dict(purpose=purpose, objects=objects, assumptions=assumptions,
                techniques=techniques, first_steps=first_steps,
                levels=dict(sup=sup, spe=spe, beyond=beyond),
                lesson_numbers=lessons, expected=expected)


LAB_GUIDES = {
    "snell": guide(
        "Comprendre le changement de direction à une interface et reconnaître le seuil où un rayon transmis propagatif cesse d’exister. Les courbes de Fresnel relient ensuite ce tracé au bilan de puissance.",
        ["n₁, n₂ sans unité ; incidence en degrés depuis la normale", "r en degrés ; R et T sont des fractions de puissance, distinctes des amplitudes de champ"],
        ["Deux milieux isotropes transparents, non magnétiques, interface plane", "Rayons géométriques ; les courbes s, p ne représentent pas un champ évanescent spatial complet"],
        ["Projection d’un vecteur d’onde", "Trigonométrie et domaine d’arcsin", "Bilan normal de Poynting"],
        ["Pour air→verre n=1,50 à 40°, prévoir vers quel côté de la normale le rayon tourne ; calculer ensuite le seuil verre→air.", "Comparer les trois préréglages et approcher progressivement l’incidence critique de 41,81° ; regarder séparément Rs et Rp.", "Retrouver n₁sin i=n₂sin r et vérifier R+T=1 avant le seuil ; distinguer réflexion totale et absence de tout champ dans le second milieu."],
        "Descartes–Snell, angle à la normale, ordre de grandeur et réversibilité.", "Conditions aux limites, polarisation s/p, Fresnel et conservation du flux selon filière.", "Onde évanescente, décalage de Goos–Hänchen et réflexion totale frustrée.", [1,2],
        "Un seuil justifié et une distinction claire entre orientation d’un rayon, amplitude et énergie."),
    "lentille": guide(
        "Suivre le passage entre image réelle, virtuelle et image à l’infini. Les constructions font attribuer un sens physique aux signes de la conjugaison plutôt qu’appliquer une formule à des distances toutes positives.",
        ["Focale affichée en mm : son signe est fourni par le choix convergente/divergente", "Distance objet positive s en mm, p=−s ; hauteur et ouverture en mm ; p′ et γ sont algébriques"],
        ["Lentille mince dans l’air, régime paraxial", "Prolongements virtuels pointillés ; l’ouverture règle les rayons représentés, pas une diffraction calculée"],
        ["Conjugaison orientée et grandissement", "Construction par rayons remarquables", "Limite au voisinage du plan focal"],
        ["Avec f′=80 mm, prévoir le signe de p′ pour s=200,80 et 50 mm avant de lancer les préréglages.", "Comparer image réelle, loupe et objet au foyer ; passer ensuite à la lentille divergente avec le même objet.", "Vérifier 1/p′−1/p=1/f′ et γ=p′/p ; expliquer quels segments sont des rayons et quels segments sont seulement prolongés."],
        "Gauss, conjugaison, lentille convergente et divergente ; techniques communes de première année.", "Newton, matrices ABCD et invariant de rayon, introduits si nécessaire.", "Systèmes épais, plans principaux et aberrations hors de Gauss.", [3,4],
        "Trois images classées avec leurs signes et une explication de l’échec de projection d’une image virtuelle."),
    "bessel": guide(
        "Reconstituer un TP de détermination de focale : deux mises au point d’un même objet sur un écran fixe. Explorer aussi le seuil de Silbermann et distinguer incertitude propagée et facilité réelle de réglage.",
        ["D, f′, position et écart d en mm ; la commande de position est s/D sans unité", "σD, σd sont des incertitudes standards en mm ; u(f′) en mm et d/u(d) sans unité"],
        ["Objet réel, écran fixe, lentille mince convergente", "Propagation linéaire d’incertitudes D, d indépendantes ; la difficulté de netteté n’est pas simulée comme un bruit automatique"],
        ["Équation du second degré et discriminant", "Grandissements réciproques", "Dérivées partielles et incertitude composée"],
        ["Prévoir combien de mises au point existent pour D=800,480 et 400 mm avec f′=120 mm.", "Utiliser les deux positions nettes, déplacer manuellement s/D, puis comparer Silbermann et le cas sans mise au point.", "Démontrer f′=(D²−d²)/(4D), calculer u(f′) et expliquer pourquoi un petit d/u(d) rend deux positions difficiles à distinguer même si u(f′) n’augmente pas."],
        "Banc optique, Bessel/Silbermann, mesure et unités.", "Propagation d’incertitude, corrélation éventuelle et stratégie expérimentale.", "Estimation Monte-Carlo et biais du modèle de lentille mince.", [5,6],
        "Une focale avec incertitude déclarée et une décision argumentée sur la distance objet–écran."),
    "telescope": guide(
        "Construire une lunette afocale pour un objet astronomique décrit par sa direction. Comparer grossissement, pupille de sortie et diffraction afin de comprendre ce qu’un changement d’oculaire améliore réellement.",
        ["fo, fe, Dobjectif et défaut de séparation en mm ; angle de l’astre en minutes d’arc", "λ₀ en nm ; grossissement sans unité ; repère angulaire de Rayleigh en secondes d’arc"],
        ["Lunette de Kepler à deux lentilles minces ; rayons paraxiaux", "Pupille circulaire idéale pour le repère de diffraction ; turbulence et aberrations non incluses dans ce banc"],
        ["Chaîne angle→hauteur→angle", "Matrices de séparation et afocalité", "Conversion radians/secondes d’arc"],
        ["Pour fo=1000 mm, fe=25 mm, calculer G et la séparation afocale ; prévoir l’effet de fe=10 mm.", "Comparer ×40 et fort grossissement ; augmenter Dobjectif puis introduire un défaut de séparation de 5 mm.", "Démontrer G=−fo/fe et Dsortie=Dobjectif/|G| ; expliquer pourquoi changer l’oculaire ne modifie pas 1,22λ₀/Dobjectif."],
        "Lunette, grossissement, image à l’infini et réglages de TP.", "Diffraction et échantillonnage au foyer ; calcul du défaut d’afocalité.", "Télescopes réfléchissants, seeing, optique adaptative et PSF instrumentale.", [7,8,35],
        "Une chaîne instrumentale où grossissement, collecte de lumière et résolution sont calculés séparément."),
    "microscope": guide(
        "Régler une image intermédiaire pour regarder sans accommodation et suivre l’amplification d’un détail micrométrique. L’ouverture numérique donne un second critère : agrandir davantage ne crée pas des détails transmis.",
        ["fo, fe, intervalle Δ et hauteur objet en mm ; déplacement de l’objet en μm", "NA sans unité, λ₀ en nm, résolution objet en μm ; G sans unité et puissance en m⁻¹"],
        ["Objectif et oculaire minces, chaîne afocale de Gauss", "NA limitée à 0,35 dans le banc paraxial ; axes de la scène étirés pour rendre les deux échelles lisibles"],
        ["Conjugaison de l’objectif", "Grandissement et grossissement commercial", "Comparaison de résolution ramenée au plan objet"],
        ["Avec fo=8 mm, Δ=160 mm, fe=25 mm, prévoir G et la distance de l’objet légèrement au-delà de fo.", "Comparer les deux grossissements, puis déplacer l’objet de 20 μm ; modifier NA à oculaire fixé.", "Retrouver γobjectif=−Δ/fo et G≈γobjectif×250 mm/fe ; expliquer ce que prédit 0,61λ₀/NA et ce que ce critère n’évalue pas."],
        "Microscope comme objectif et loupe ; réglage d’image intermédiaire du recueil.", "Diffraction, NA et échantillonnage ; conversion de μm aux mm.", "Objectifs à immersion, microscopes corrigés à l’infini et imagerie incohérente.", [9,10],
        "Un réglage afocal calculé, puis un grossissement utile confronté à la résolution et à la défocalisation."),
    "oeil": guide(
        "Utiliser la rétine comme écran fixe pour comprendre accommodation et correction. Un même bilan de conjugaison explique une myopie, une hypermétropie et l’effet du diamètre pupillaire sur deux sortes de flou.",
        ["Distance objet en m ; rétine et pupille en mm", "Excès au repos, correction collée et accommodation en dioptries δ=m⁻¹ ; tache rétinienne en μm"],
        ["Œil réduit à une lentille et espace image en air, pour isoler la conjugaison", "Correction en contact ; flou géométrique et repère diffractif sont des échelles, pas une prescription physiologique"],
        ["Conjugaison à écran fixe", "Addition de vergences en contact", "Triangles semblables et comparaison de flous"],
        ["Avec rétine à 17 mm, prévoir l’accommodation ajoutée nécessaire pour un objet à 25 cm.", "Utiliser objet proche, myopie puis myopie corrigée ; diviser ensuite le diamètre pupillaire par deux.", "Établir Crequise=1/ℓ+1/s et le signe de la correction ; expliquer pourquoi fermer la pupille diminue la défocalisation mais augmente la diffraction."],
        "Vergence, accommodation et lentilles correctrices dans un modèle réduit.", "Bilan de chaîne, profondeur de champ et limites de résolution.", "Dioptres de l’œil, astigmatisme, aberrations et optique physiologique.", [11,3,35],
        "Une correction de signe justifié et un compromis de pupille compris à partir de deux lois d’échelle."),
    "fibre": guide(
        "Passer de la réflexion totale au cône d’acceptance d’une fibre, puis mesurer le retard d’un rayon incliné. Le nombre V ouvre un lien avec les modes sans présenter un dessin de rayons comme leur solution ondulatoire.",
        ["Indices cœur/gaine sans unité ; angle d’entrée dans l’air en degrés à l’axe", "Rayon en μm, longueur en m, λ₀ en nm ; temps axial/incliné en μs, étalement en ns ; NA et V sans unité"],
        ["Fibre droite à saut d’indice, rayons méridiens ; guidage seulement si ncœur>ngaine", "V est un repère de théorie ondulatoire faiblement guidante ; modes, courbures et pertes ne sont pas calculés"],
        ["Deux applications de Snell", "Trigonométrie d’un trajet en zigzag", "Nombres sans dimension et changement de régime"],
        ["Pour n₁=1,48, n₂=1,46, calculer NA et l’angle d’entrée limite avant de tracer le rayon.", "Comparer entrée de 8° et de 25° ; doubler la longueur puis sélectionner le repère monomode.", "Démontrer n₀sinθmax=√(n₁²−n₂²) et Δt=n₁L(1/cosθ−1)/c ; distinguer acceptance et seuil V<2,405."],
        "Réflexion totale et fibre, grand classique du recueil.", "Dispersion intermodale et ordre de grandeur temporel ; introduction du nombre V.", "Modes cylindriques, gradient d’indice, dispersion chromatique et télécommunications.", [12,13],
        "Une entrée acceptée ou rejetée selon un calcul, accompagnée d’un retard et d’une limite explicite du modèle de rayons."),
    "mirage": guide(
        "Retrouver la parabole du profil d’indice du recueil à partir d’un invariant, puis lire le point bas et la position apparente d’un rayon. La comparaison analytique/numérique donne un contrôle de résolution d’équation.",
        ["n₀ sans unité ; échelle a, altitude z₀ et distance x en m", "Angle initial en degrés à l’horizontale ; invariant ncosθ et écart numérique sans unité ou dans l’unité affichée"],
        ["n(z)=n₀√(1+z/a), a>0, domaine z≥0", "Profil stylisé ; trajectoire interrompue au sol, les prolongements apparents ne transportent pas de lumière"],
        ["Intégrale première par invariance", "Intégration d’une courbure constante", "Point stationnaire et vérification numérique"],
        ["Avec a=20000 m, z₀=2 m, θ₀=−0,5°, prévoir si le rayon touche le sol ou remonte avant.", "Observer le point bas du préréglage descendant puis le cas qui rencontre le sol ; augmenter a vers 10⁶ m.", "Retrouver ncosθ constant et vérifier que le coefficient de x² est 1/[4(a+z₀)cos²θ₀] ; comparer la tangente apparente à la courbe réelle."],
        "Trigonométrie, dérivation et intégration ; entrée progressive vers un milieu non homogène.", "Loi du rayon, invariant, modèle atmosphérique et contrôle d’erreur.", "Eikonale, Hamiltonien optique et profils d’indice mesurés.", [14,18],
        "Une trajectoire démontrée, un point bas calculé et un arrêt au sol interprété sans prolonger le domaine physique."),
    "arcenciel": guide(
        "Faire apparaître une caustique par stationnarité de la déviation, puis relier la dispersion à l’ordre des couleurs. Le rayon dans la goutte et le graphe D(i) donnent deux lectures complémentaires d’un même phénomène.",
        ["Incidence en degrés ; une ou deux réflexions internes", "λ₀ en nm ; Cauchy n=a+b/λ² avec b en μm² ; déviation et rayon antisolaire en degrés"],
        ["Goutte sphérique transparente dans l’air ; dispersion de Cauchy sur le visible", "Optique géométrique : la divergence idéale de caustique n’est pas une intensité ondulatoire infinie"],
        ["Composition de déviations", "Dérivée de Snell et stationnarité", "Différentielle d’une déviation spectrale"],
        ["À n≈4/3, prévoir le rayon du primaire et vérifier que la déviation D est proche de 138°, pas de 42°.", "Comparer rouge/violet du primaire puis le secondaire ; déplacer i autour de l’incidence stationnaire.", "Établir sin²i*=[(p+1)²−n²]/[(p+1)²−1] et expliquer l’ordre inverse des couleurs pour le secondaire."],
        "Snell, goutte et trigonométrie du grand classique proposé.", "Caustique, dérivation implicite et dispersion ; lien avec polarisation de Fresnel.", "Airy de caustique, arcs surnuméraires et diffusion de Mie.", [15,2],
        "Une différence entre rayon angulaire de l’arc et déviation du rayon, avec un ordre des couleurs justifié."),
    "prisme": guide(
        "Reconstituer la recherche du minimum au goniomètre, convertir une déviation en indice et confronter plusieurs couleurs à Cauchy. Le cas sans émergence apprend à vérifier les domaines trigonométriques.",
        ["A, i, D en degrés ; λ₀ en nm", "n=a+b/λ², a sans unité et b en μm² ; indice déduit au minimum sans unité"],
        ["Prisme dans l’air, deux faces planes et milieu transparent", "Cauchy utilisée seulement dans la fenêtre visible ; un trajet peut subir réflexion totale à la seconde face"],
        ["Trigonométrie de deux interfaces", "Recherche d’un minimum par symétrie", "Ajustement linéaire en 1/λ²"],
        ["Pour A=60° et n=1,50, prévoir Dmin et l’incidence correspondante.", "Balayer i de part et d’autre du minimum, comparer 450 et 700 nm, puis observer le préréglage sans émergence.", "Retrouver n=sin[(A+Dmin)/2]/sin(A/2), préciser les unités de b et proposer une lecture de goniomètre limitant les erreurs."],
        "Prisme et réglages collimateur/lunette du TP ; déviation minimale.", "Propagation d’erreur angulaire et mesure spectrale d’un indice.", "Dispersion de Sellmeier et résonances hors du domaine de Cauchy.", [16],
        "Un indice mesurable depuis un retournement de raie et un contrôle de validité à chacune des faces."),
    "aberrations": guide(
        "Comparer un miroir sphérique et un paraboloïde pour un faisceau axial. Le tracé exact rend visible l’aberration sphérique, son atténuation paraxiale et le stigmatisme axial de la parabole sans les confondre avec la diffraction.",
        ["R en mm ; demi-ouverture/R et position d’écran −x/R sans unité", "Sommet x=0, centre sphérique x=−R ; interceptions et positions focales en mm"],
        ["Réflexion géométrique exacte d’un faisceau parallèle à l’axe", "Aucune diffraction, aucun calcul de coma hors axe ; le paraboloïde est stigmatique seulement pour la configuration axiale étudiée"],
        ["Normale d’une courbe et réflexion vectorielle", "Développement limité d’une surface", "Égalité de chemins optiques"],
        ["Prévoir ce que devient le foyer des rayons marginaux d’une sphère par rapport à −R/2.", "Comparer sphère à ouverture/R=0,45 puis 0,05 ; déplacer l’écran et choisir la parabole avec la grande ouverture.", "Montrer x(y)=−y²/(2R)−y⁴/(8R³)+… pour la sphère et prouver x+PF=R/2 pour le paraboloïde."],
        "Miroir, normale, loi de réflexion et limite de Gauss.", "Aberration longitudinale, DL et comparaison d’un modèle exact à une approximation.", "Conception de télescopes, coma hors axe et combinaison aberrations/diffraction.", [17,35],
        "Une erreur géométrique quantifiée et un succès axial du paraboloïde dont les limites sont précisées."),
    "fermat": guide(
        "Faire naître Snell d’une optimisation du temps de trajet. La position de traversée volontairement imparfaite permet de comparer un segment plus court à un chemin plus rapide, avec une preuve de convexité.",
        ["Séparation X, altitude h₁ et profondeur h₂ en cm ; point de passage x/X sans unité", "n₁, n₂ sans unité ; chemin optique converti en longueur et durée L/c"],
        ["Deux milieux homogènes séparés par une interface plane", "Un trajet à deux segments, minimum unique ici ; le principe général est une stationnarité"],
        ["Dérivation d’une fonction de position", "Convexité et unicité d’un optimum", "Traduction d’une dérivée en angles de Snell"],
        ["À indices égaux, h₁=8 cm, h₂=5 cm, X=20 cm, calculer la traversée du segment direct.", "Comparer indices égaux puis n₂=1,50 ; déplacer le passage manuel autour du minimum indiqué.", "Dériver L(x), identifier n₁sin i−n₂sin r et montrer L″>0 ; relier cet invariant au rayon courbe du mirage."],
        "Optimisation à une variable, racines et interprétation du chemin optique.", "Principe de Fermat, unicité et intégrales premières.", "Calcul variationnel, Hamiltonien et points conjugués.", [18,14],
        "Une loi de réfraction dérivée d’un minimum et une démonstration de l’unicité pour cette géométrie."),
}

LAB_GUIDES.update({
    "young": guide(
        "Identifier séparément franges d’interférence et enveloppe de diffraction. Le laboratoire montre aussi qu’un minimum non noir peut venir d’un déséquilibre, et qu’une somme d’intensités sans corrélation garde de la lumière.",
        ["λ en nm ; séparation a et largeur b en mm ; D en m", "I₂/I₁ sans unité ; phase additionnelle en degrés ; x et interfrange en mm"],
        ["Fraunhofer paraxial, fentes uniformes de même largeur", "Source commune et polarisation compatible en mode cohérent ; sources indépendantes sans terme croisé"],
        ["Différence de marche et phase", "Somme d’amplitudes complexes", "Deux lois d’échelle i=λD/a et L=2λD/b"],
        ["Pour λ=600 nm, D=2 m, a=0,50 mm, b=0,040 mm, prévoir interfrange et premiers zéros d’enveloppe.", "Doubler a puis b séparément ; comparer déséquilibre I₂/I₁=0,10, sources indépendantes et une seule fente.", "Retrouver visibilité 2√ρ/(1+ρ), déplacement dû à 90° de phase et maxima manquants dans l’enveloppe."],
        "Superposition, phase, interfrange et acquisition de courbes.", "Diffraction de fentes, cohérence et contraste ; statut des chapitres selon filière.", "Interférence de particules et corrélation mutuelle de champs partiellement cohérents.", [19,20,27],
        "Deux échelles mesurées et une cause de perte de contraste identifiée sans confusion avec un changement d’interfrange."),
    "reseau": guide(
        "Résoudre un doublet grâce à la largeur des maxima d’un ensemble de fentes. Augmenter N affine les pics ; changer l’ordre m augmente la dispersion, sous réserve que cet ordre existe et soit transmis par l’enveloppe.",
        ["λ centrale et écart du doublet en nm ; pas d en μm ; N entier et fraction ouverte b/d", "Incidence en degrés ; ordre m entier ; λ/Δλ et mN sans unité"],
        ["N fentes identiques éclairées uniformément, Fraunhofer", "Deux raies indépendantes sommées en intensité ; Rayleigh idéal sans bruit ni aberrations"],
        ["Somme géométrique complexe", "Limite amovible du quotient de sinus", "Comparaison séparation/largeur et critère de Rayleigh"],
        ["Pour 589,3 nm et Δλ=0,60 nm, estimer combien de fentes il faut à l’ordre 1 puis à l’ordre 2.", "Comparer N=100, le voisinage N=982 puis l’ordre 2 ; choisir le préréglage d’ordre absent.", "Démontrer d(sinθ−sinθ₀)=mλ, montrer Ipic∝N² et expliquer l’effet de l’enveloppe b/d sur les ordres manquants."],
        "Interférence de plusieurs sources après introduction guidée d’une somme complexe.", "Réseaux, dispersion et pouvoir spectral R≈mN selon filière.", "Éclairement apodisé, largeur de raie, blaze et instruments spectrographiques.", [21,22],
        "Un seuil de résolution estimé et une distinction entre ordre absent géométriquement et ordre supprimé par diffraction."),
    "diffraction": guide(
        "Reconstruire la forme d’une figure depuis une pupille, puis découvrir le compromis d’apodisation. Les premiers zéros et le bilan de transmission obligent à distinguer demi-largeur, largeur totale et normalisation au pic.",
        ["Largeur a et hauteur b de pupille en mm ; λ en nm ; focale en mm", "Coordonnées focales en mm ; transmittance cosinus d’amplitude ; intensité relative au pic et énergie transmise"],
        ["Diffraction scalaire de Fraunhofer au plan focal, illumination uniforme", "Apodisation t=cos(πx/a) sur |x|≤a/2 ; valeurs amovibles prolongées, pas mises à zéro"],
        ["Intégrale d’une exponentielle", "Séparation d’une transformée bidimensionnelle", "Comparaison lobes centraux/lobes secondaires/puissance"],
        ["Pour a=0,20 mm, b=0,80 mm, f=300 mm, λ=600 nm, prévoir quel axe de la tache sera le plus large.", "Comparer rectangle et fente ; choisir l’apodisation avec la même largeur et regarder le premier zéro.", "Intégrer la pupille, retrouver la demi-largeur λf/a puis 3λf/(2a) apodisée et montrer que la transmission totale cosinus vaut 1/2."],
        "Superposition et intégration après introduction du principe de diffraction.", "Fraunhofer, pupille rectangulaire et transmittance ; programme selon filière.", "Fenêtrage, apodisation optimisée et compromis résolution/contraste.", [22,23],
        "Des dimensions de pupille retrouvées depuis les zéros, et un compromis d’apodisation argumenté avec son coût en flux."),
    "polarisation": guide(
        "Transformer puis analyser un état du champ électrique. L’ellipse, les composantes et la sphère de Poincaré permettent de relier un calcul Jones à une mesure au polariseur, y compris un état circulaire sans extinction directe.",
        ["Angles d’entrée, de lame et d’analyseur en degrés ; retardance δ en degrés", "Jones normalisé, transmission sans unité ; Stokes S₁/S₀, S₂/S₀, S₃/S₀ sur la sphère"],
        ["État monochromatique entièrement polarisé ; lame idéale sans pertes", "Convention exp(−iωt), seconde composante multipliée par exp(iδ), S₃=2Im(Ex*Ey)"],
        ["Projection et loi de Malus", "Changement de base et matrice unitaire", "Ellipse paramétrée et invariance de norme"],
        ["Prévoir l’état issu d’une droite à 45° et d’une lame à δ=90° ; calculer la transmission attendue d’un analyseur.", "Comparer quart d’onde, demi-onde, état circulaire et extinction ; tourner l’analyseur sans changer l’état avant lui.", "Retrouver la matrice de lame et les Stokes ; proposer le protocole analyseur+lame qui distingue cercle et lumière non polarisée."],
        "Malus, projection vectorielle et contrôle d’un état rectiligne.", "Lames à retard et détermination de polarisation, notamment TP de la filière PC.", "Jones, Poincaré, Stokes partiels et lien au qubit de polarisation.", [24,25],
        "Une transformation expliquée par ses composantes et une mesure de transmission, avec convention du sens de rotation déclarée."),
    "michelson": guide(
        "Passer du montage à sa différence de marche et à son plan d’observation. Les anneaux d’inclinaison et les franges de coin donnent deux méthodes de mesure distinctes, avec le facteur deux d’un aller-retour.",
        ["λ en nm ; écart miroir e en μm ; angle α du coin en mrad", "Focale et coordonnées d’observation en mm ; champ en degrés ; phase additionnelle en degrés"],
        ["Source monochromatique et bras cohérents ; compensation de verre idéale", "Anneaux dans un plan focal ; coin dans un plan image adapté, géométrie de petits angles"],
        ["Calcul de chemin optique aller-retour", "Développement de cos i", "Identification du plan de localisation"],
        ["Prévoir le nombre de franges pour une translation de 100 μm à λ=546 nm et le changement de rayons au carré.", "Comparer anneaux, contact optique et coin ; doubler l’inclinaison du coin en conservant λ.", "Démontrer δ=2e cos i puis δ≈δ₀+2αx ; dire pourquoi l’axe radial du foyer et x d’un coin n’ont pas le même sens physique."],
        "Interférences à deux trajets et notion de différence de marche introduites progressivement.", "Michelson, lame d’air, coin, réglages expérimentaux et mesure selon filière.", "Spectroscopie de Fourier et enveloppe de lumière blanche dans Cohérence.", [26,27,28],
        "Une méthode de mesure choisie avec son plan d’observation et un facteur deux vérifié."),
    "coherence": guide(
        "Expliquer une perte de visibilité à partir du spectre ou de la taille de source. Le doublet montre des retours de contraste, contrairement à l’enveloppe gaussienne : une première annulation ne résume pas la cohérence.",
        ["λ et écart de doublet en nm ; largeur FWHM Δν en GHz ; différence de marche en mm", "Largeur source s et séparation a en mm ; Ds en m ; visibilité et γ normalisés"],
        ["Raies indépendantes spectralement ; spectre gaussien ou deux raies fines égales", "Source spatiale uniforme, points indépendants et géométrie paraxiale ; contributions temporelle/spatiale séparables"],
        ["Transformée de Fourier d’un spectre", "Somme trigonométrique et battements", "Produit de corrélations et choix d’un seuil de visibilité"],
        ["Avec Δν=20 GHz, prévoir l’ordre de longueur c/Δν ; pour le doublet 0,60 nm, prévoir une annulation plus rapprochée.", "Balayer δ avec la source ponctuelle, comparer gaussien et doublet, puis élargir la source et utiliser sources indépendantes.", "Calculer V=exp[−π²Δν²(δ/c)²/(4ln2)], les annulations du doublet et le premier zéro as=λDs ; distinguer les trois causes testées."],
        "Phase, contraste et somme de signaux ; entrée accompagnée en cohérence.", "Cohérence temporelle et spatiale, doublet du recueil et diagnostics de TP.", "Wiener–Khintchine et Van Cittert–Zernike avec profils de sources plus généraux.", [27,28,19],
        "Une perte de contraste diagnostiquée par des réglages indépendants et un seuil de cohérence clairement défini."),
    "fabryperot": guide(
        "Voir comment de nombreux trajets résonnent et apprendre à lire une finesse spectrale. Les pics étroits demandent de vérifier également répétition d’ordre, angle interne et différence entre coefficient d’Airy et finesse.",
        ["Épaisseur e en mm, indice n et réflectivité R sans unité ; λ₀ en nm", "Angle interne en degrés ; désaccord/ISL sans unité ; ISL et largeur affichées en GHz ; finesse sans unité"],
        ["Deux miroirs identiques sans absorption ; série stationnaire d’amplitudes", "n constant sur la fenêtre, angle interne connu ; le coefficient F=4R/(1−R)² diffère de ℱ spectrale"],
        ["Série géométrique complexe", "Largeur à mi-hauteur", "Séparation fréquence/longueur d’onde/ordre"],
        ["Prévoir transmission en résonance pour R=0,85, puis distinguer ce résultat de la transmission d’un miroir seul.", "Comparer résonance, antirésonance, haute finesse et R=0 ; doubler e puis changer l’angle interne.", "Retrouver la loi d’Airy, calculer ISL=c/(2ne cosθ) et ℱ ; expliquer ce que les réglages de R et e changent séparément."],
        "Sommes complexes après introduction des deux trajets de Michelson.", "Interférences multiples et résonances ; prolongement accompagné selon filière.", "Pertes, indice de groupe, spectroscopie haute résolution et cavités optomécaniques.", [29,30],
        "Un pic caractérisé par trois nombres distincts : position, intervalle libre et largeur."),
    "fourier": guide(
        "Construire un véritable filtrage du champ d’un objet. Une image de phase et les bilans de Parseval font distinguer amplitude, phase, intensité, contraste et énergie, au-delà d’un simple effet de flou sur une photographie.",
        ["Fréquence de coupure en mm⁻¹ ; pas objet en μm ; λ₀ en nm ; focale en mm", "Objet complexe E ; image |E|² ; spectre affiché logarithmiquement ; puissance relative sans unité"],
        ["Montage 4f cohérent paraxial, masque passif |H|≤1", "FFT unitaire sur grille finie périodisée ; intensités avant/après affichées avec une échelle commune"],
        ["Transformée et coordonnées du plan focal", "Norme de champ et théorème de Parseval", "Échantillonnage et fréquence de Nyquist"],
        ["Avec λ=600 nm, f=200 mm, prévoir où se trouve une modulation de période 50 μm dans le plan de Fourier.", "Comparer aucun masque, passe-bas, passe-haut, fente verticale ; choisir ensuite l’objet de phase et suivre son contraste.", "Vérifier le bilan identité puis masque passif ; calculer fNyquist et expliquer pourquoi on filtre le champ avant de prendre son module au carré."],
        "Sinusoïdes, dimensions et lecture d’une image ; notion de fréquence spatiale guidée.", "Diffraction et transformée de pupille selon filière ; lien à l’informatique scientifique.", "Filtrage cohérent, contraste de phase, fonctions de transfert et problèmes inverses.", [31,32,22],
        "Une transformation d’image interprétée avec sa fréquence physique et un bilan de puissance qui résiste à la normalisation visuelle."),
    "laser": guide(
        "Séparer la stabilité du trajet paraxial et l’apparition d’une oscillation entretenue. Le gain saturé fournit ensuite une puissance limitée et met le rôle du coupleur en relation avec la perte de cavité.",
        ["L en mm ; courbures 1/R en m⁻¹ ; réflectivités de puissance sans unité", "Gain g₀ et perte α en m⁻¹ d’intensité ; Ps et puissance en W ; λ₀ en nm"],
        ["Cavité paraxiale à deux miroirs, gain uniforme saturant g(P)=g₀/(1+P/Ps)", "Critère de stabilité intérieur strict ; confocal classé marginal par ce test, ses modes ne sont pas déclarés inexistants"],
        ["Matrice aller-retour et valeurs propres", "Condition de seuil logarithmique", "Bilan gain/pertes et saturation"],
        ["Avec L=200 mm et courbures 2 m⁻¹, prévoir g₁g₂ puis le seuil avec réflectivités 0,99 et 0,90.", "Comparer gain suffisant et insuffisant à géométrie fixe ; choisir l’instabilité avec miroir convexe puis le confocal marginal.", "Retrouver gseuil=α−ln(R₁R₂)/(2L), P=Ps(g₀/gseuil−1) et identifier les sujets absents du modèle : bruit, multimode, dynamique des populations."],
        "Exponentielle, logarithme et bilan d’amplification introduits progressivement.", "ABCD, résonance et émission stimulée ; entrée guidée hors programme commun.", "Modes propres, rate equations, compétition modale et oscillations de relaxation.", [33,4,30],
        "Deux décisions indépendantes — confinement et seuil — puis une puissance saturée dont la source d’énergie est identifiée."),
    "gaussien": guide(
        "Relier un petit waist à une grande divergence et contrôler que l’élargissement ne perd pas de puissance. La courbure et la phase de Gouy révèlent ce que le simple dessin de rayons ne contient pas.",
        ["Rayon w₀ à 1/e² en μm, λ₀ en nm, indice n sans unité et P en mW", "Plan z/zR sans unité ; w, zR et courbure dans les unités affichées ; I en W·m⁻² et Gouy affiché en degrés"],
        ["TEM₀₀ paraxial dans un milieu homogène transparent", "Rayon d’intensité w, pas diamètre ; aucun diaphragme ni perte ; fronts et enveloppe représentés à des échelles annoncées"],
        ["Intégrale radiale de puissance", "Lois d’échelle w₀, zR, divergence", "Phase complexe et limite au waist"],
        ["Pour w₀=50 μm, λ₀=633 nm, n=1, prévoir zR et le changement d’intensité axiale à z=zR.", "Comparer waist, zR, puis petit et grand waist ; doubler P en conservant la géométrie.", "Intégrer I(r, z) et vérifier P constant ; expliquer Rfront infini au waist, la phase de Gouy et la divergence accrue quand w₀ diminue."],
        "Gaussienne, intégrale et dimensions ; premier lien rayon/onde.", "Diffraction d’un faisceau fini et propagation d’enveloppe, prolongement accompagné.", "Paramètre q, ABCD gaussien, qualité M² et modes d’ordre supérieur.", [34,33],
        "Un compromis de focalisation calculé et une puissance conservée malgré la baisse du maximum."),
    "airy": guide(
        "Tester la discernabilité de deux objets astronomiques ponctuels et comprendre une pupille annulaire. La somme de PSF de deux étoiles indépendantes rend visibles résolution et contraste sans inventer une phase commune.",
        ["D en mm, λ₀ en nm, séparation divisée par 1,22λ₀/D sans unité", "Rapport des flux et obstruction ε sans unité ; angle en secondes d’arc ; profils et taches d’intensité"],
        ["Pupille circulaire ou annulaire idéale, points indépendants sans turbulence", "Le repère Rayleigh choisi est celui de la pupille pleine ; le zéro annulaire calculé peut différer, PSF de Webb non simulée"],
        ["Transformée d’une pupille circulaire", "Somme d’intensités incohérentes", "Comparaison séparation/largeur/contraste"],
        ["À D=200 mm, λ₀=550 nm, calculer le repère Rayleigh et prévoir l’effet de D doublé.", "Comparer séparation 1 puis 0,5, compagnon faible et obstruction ε=0,40 ; lire ensemble coupe et figure bidimensionnelle.", "Expliquer le rôle de J₁ et le prolongement en u=0 ; montrer que l’obstruction perd la fraction ε² du flux et renforce les anneaux."],
        "Dimensions et conversion d’angles ; distinction collecte/grossissement.", "Diffraction circulaire et séparation de deux points, avec Bessel introduite si nécessaire.", "PSF réelle, estimation sous-Rayleigh, contraste de compagnon et déconvolution.", [35,8],
        "Une comparaison de résolution qui tient compte du flux relatif et de la pupille, sans présenter Rayleigh comme frontière absolue."),
    "nonlineaire": guide(
        "Suivre la conversion du fondamental vers sa seconde harmonique et voir pourquoi la pompe constante finit par échouer. L’accord de phase relie une intégrale de champ, une loi sinc² et un bilan énergétique/photonique.",
        ["λω en nm, Iω en GW·cm⁻², d=χeff/2 en pm·V⁻¹, L en mm", "Indices effectifs sans unité ; Δk en mm⁻¹ réglé par orientation ; rendement et fractions d’énergie sans unité"],
        ["Doublage dégénéré d’une seule pompe, ondes colinéaires, enveloppes lentes sans absorption", "Δk est un contrôle effectif indépendant des indices scalaires ; modèle faible seulement si η≪1, modèle couplé conserve |u|²+|v|²=1"],
        ["Intégrale d’une exponentielle et sinc²", "Équations d’enveloppes couplées", "Manley–Rowe et conservation de l’énergie"],
        ["Pour 1064 nm, prévoir la longueur d’onde produite et le nombre de photons fondamentaux consommés par photon généré.", "Comparer faible conversion et déplétion ; allonger L à accord parfait puis introduire Δk et regarder la reconversion.", "Retrouver la loi η∝IωL²sinc²(ΔkL/2), identifier son échec si η>1 et vérifier Nω+2N2ω constant ; relier au PDF à deux pompes distinctes."],
        "Carré d’un sinus, énergie d’un photon et intégrale de phase, après introduction guidée.", "Réinvestissement de Maxwell et des ODE, mais la génération χ² n’est pas un acquis commun obligatoire.", "Accord birefringent, Manley–Rowe, déplétion, paramétrique et cristaux non linéaires.", [36,34],
        "Un rendement borné dans le modèle couplé, une conversion spectrale et un bilan de photons dont la pondération est explicitée."),
})
